### PR TITLE
Fix namespace initialization

### LINKED ISSUE #5587: Start master attempts to create service accounts in the wrong namespace
$ sudo ./_output/local/bin/linux/amd64/openshift start --master=10.1.2.2 --latest-images master

from a clean config dir

```
E1102 18:08:55.076057    9713 ensure.go:132] Could not add service accounts to the system:image-puller role in the "" namespace: an empty namespace may not be set when a resource name is provided
E1102 18:08:55.076135    9713 ensure.go:132] Could not add service accounts to the system:image-builder role in the "" namespace: an empty namespace may not be set when a resource name is provided
E1102 18:08:55.076169    9713 ensure.go:132] Could not add service accounts to the system:deployer role in the "" namespace: an empty namespace may not be set when a resource name is provided
```

Also see

```
E1102 18:10:43.848001    9732 ensure.go:147] Error recording adding service account roles to "default" namespace: namespaces "default" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
E1102 18:10:44.386521    9732 ensure.go:147] Error recording adding service account roles to "openshift-infra" namespace: namespaces "openshift-infra" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
E1102 18:10:44.499072    9732 ensure.go:147] Error recording adding service account roles to "openshift" namespace: invalid update object, missing resource version: &{{ } {openshift      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[openshift.io/sa.initialized-roles:true]} {[]} {}}
```

sometimes - that last message looks sketchy.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5587

### CODE REVIEW

File: pkg/cmd/server/origin/ensure.go [hunk 1]
```diff
@@ -26,12 +26,9 @@ import (
 // ensureOpenShiftSharedResourcesNamespace is called as part of global policy initialization to ensure shared namespace exists
 func (c *MasterConfig) ensureOpenShiftSharedResourcesNamespace() {
 	if _, err := c.KubeClient().Namespaces().Get(c.Options.PolicyConfig.OpenShiftSharedResourcesNamespace); kapierror.IsNotFound(err) {
-		namespace := &kapi.Namespace{
-			ObjectMeta: kapi.ObjectMeta{Name: c.Options.PolicyConfig.OpenShiftSharedResourcesNamespace},
-		}
-		_, err = c.KubeClient().Namespaces().Create(namespace)
-		if err != nil {
-			glog.Errorf("Error creating namespace: %v due to %v\n", namespace, err)
+		namespace, createErr := c.KubeClient().Namespaces().Create(&kapi.Namespace{ObjectMeta: kapi.ObjectMeta{Name: c.Options.PolicyConfig.OpenShiftSharedResourcesNamespace}})
```
Comment (liggitt) [inline pkg/cmd/server/origin/ensure.go]: we needed to pass the created namespace to `ensureNamespaceServiceAccountRoleBindings` or the namespace annotation update would fail with a missing resource version

File: pkg/cmd/server/origin/ensure.go [hunk 2]
```diff
@@ -45,8 +42,16 @@ func (c *MasterConfig) ensureOpenShiftInfraNamespace() {
 
 	// Ensure namespace exists
 	namespace, err := c.KubeClient().Namespaces().Create(&kapi.Namespace{ObjectMeta: kapi.ObjectMeta{Name: ns}})
-	if err != nil && !kapierror.IsAlreadyExists(err) {
+	if kapierror.IsAlreadyExists(err) {
+		// Get the persisted namespace
+		namespace, err = c.KubeClient().Namespaces().Get(ns)
```
Comment (liggitt) [inline pkg/cmd/server/origin/ensure.go]: in the case where we got a AlreadyExists error, we were incorrectly using the returned namespace, which had no name set, instead of fetching the persisted namespace

**Comment by liggitt** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
LGTM but want one more set of eyes

**Comment by liggitt** [comment]
@pweil- or @deads2k have good sets of eyes. one of them (or one eye each) should do

**Comment by deads2k** [comment]
You know that I'd want these set up with parallel structure.

**Comment by deads2k** [comment]
lgtm

**Comment by deads2k** [comment]
This structure on the refactor list overall to make it easier to deal with new service accounts, right?

**Comment by smarterclayton** [comment]
[merge]
