### PR TITLE
Retry the output image push if failed

### LINKED ISSUE #2593: Retry pushing of the result image after successful build
We've seen a lot of flake tests that fails because the push failed for random reason, like this:

```console
Failed to push image: Error pushing to registry: lstat /var/lib/docker/devicemapper/mnt/a644a10c6b42fa825e2d5e4221913ad9dd20cf5fdb221dc640cba94ded951784/rootfs/usr/include/signal.h: input/output error
Build error: Failed to push image: Error pushing to registry: lstat /var/lib/docker/devicemapper/mnt/a644a10c6b42fa825e2d5e4221913ad9dd20cf5fdb221dc640cba94ded951784/rootfs/usr/include/signal.h: input/output error
```

When this happen and the build retries, it fails as well:

```console
Failed to push image: API error (500): push 172.30.84.128:5000/test/origin-ruby-sample is already in progress
Build error: Failed to push image: API error (500): push 172.30.84.128:5000/test/origin-ruby-sample is already in progress
```

We should retry the first push if possible (and perhaps make the # of retries configurable, with some sane default).

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes #2593 

@smarterclayton you said that this is post-3.0 but it was trivial to implement PTAL

### CODE REVIEW

**Comment by soltysh** [comment]
LGTM

File: pkg/build/builder/dockerutil.go [hunk 1]
```diff
@@ -2,11 +2,21 @@ package builder
...
-	"github.com/fsouza/go-dockerclient"
+	docker "github.com/fsouza/go-dockerclient"
+	"github.com/golang/glog"
 	"github.com/openshift/source-to-image/pkg/tar"
 )
 
+var (
+	// Number of retries of pushing the built Docker image into configured
+	// repository
+	DefaultPushRetryCount = 2
```
Comment (soltysh) [inline pkg/build/builder/dockerutil.go]: 2 - which results in just *single* retry is not enough IMHO. Either the delay between retries should be closer to 1 minute or we should retry more times. @smarterclayton ?

Comment (mfojtik) [inline pkg/build/builder/dockerutil.go]: I think waiting 60 seconds is too much, I would rather increase the number of retries to 3-4

Comment (soltysh) [inline pkg/build/builder/dockerutil.go]: I'm fine with both options, although more retries sounds better.

**Comment by smarterclayton** [comment]
@ncdc review

File: pkg/build/builder/dockerutil.go (hunk 1 above)
Comment (ncdc) [inline pkg/build/builder/dockerutil.go]: Longer term, it might be better to make this configurable (via env vars set in the pod) and to do retries up to n times with increasing back off each time.

Another option would be to watch the Docker events for push-related events, but unfortunately it doesn't look like push starts/finishes are logged at all :frowning:

Comment (smarterclayton) [inline pkg/build/builder/dockerutil.go]: But not for now.

----- Original Message -----

Comment (mfojtik) [inline pkg/build/builder/dockerutil.go]: @smarterclayton @ncdc for now I'm for just doing two attempts, we can make that configurable or put more logic there post-3.0

Comment (mfojtik) [inline pkg/build/builder/dockerutil.go]: @smarterclayton @ncdc also besides the race we have in image_change_controller, this errors are rare (at least to me), so having just 2 retries is reasonable if something unexpected happens

Comment (smarterclayton) [inline pkg/build/builder/dockerutil.go]: I don't want config for now, 2 is fine

----- Original Message -----

Comment (soltysh) [inline pkg/build/builder/dockerutil.go]: We'll deal with this retries (making them configurable) as well as other build retries (specifically in controller) at once post-3.0. The only thing I *do* want to see for now is more retries, one is not enough IMHO.

Comment (mfojtik) [inline pkg/build/builder/dockerutil.go]: @soltysh more retries will make the build longer when the error is legitimate

Comment (smarterclayton) [inline pkg/build/builder/dockerutil.go]: 2 with a minimum pause (a few seconds) between them is a good compromise.

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
[test] again

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
[merge] (as we agreed to have 2 retries && 10 seconds wait and we improve in post-3.0)

**Comment by mfojtik** [comment]
re-[merge]
