### PR TITLE
Run zookeeper as non-root user. Fix zookeeper conf volumeMount.

### LINKED ISSUE #10886: zookeeper example fails to start
When I try to deploy the zookeeper example in an OpenShift 3.2 cluster (3 masters, 2 infra nodes, 4 nodes) or inside the CDK (v2.1), the zookeeper pods fail to start (see [Error Log](#error-log)).

The problem results from when OpenShift mounts the volumeMounts listed in `template.json`. Since OpenShift is mounting an empty volume at `/opt/zookeeper/conf`, the existing config files are no longer accessible. Thus, config-and-run.sh returns "No such file or directory".

##### Version
oc v3.2.0.44
kubernetes v1.2.0-36-g4a3f9c5
Docker version 1.9.1, build ab77bde/1.9.1

##### Steps To Reproduce
1. Log into an OpenShift 3.2 environment
2. `cd origin/examples/zookeeper`
3. `oc process -f template.json | oc create -f -`
4. Wait for pods to fail to run.

##### Error Log<a name=error-log></a>

zookeeper pods fail to start, returning the following error:

```
$ oc logs zookeeper-1
/opt/zookeeper/bin/config-and-run.sh: line 7: /opt/zookeeper/conf/zoo-template.cfg: No such file or directory
JMX enabled by default
Using config: /opt/zookeeper/bin/../conf/zoo.cfg
grep: /opt/zookeeper/bin/../conf/zoo.cfg: No such file or directory
mkdir: cannot create directory '': No such file or directory
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.server.quorum.QuorumPeerConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Invalid config, exiting abnormally
```

### PR DESCRIPTION
**Pull request by ghyde**
Fixes #10886

### CODE REVIEW

File: examples/zookeeper/Dockerfile [hunk 1]
```diff
@@ -8,19 +8,21 @@ ENV ZOOKEEPER_VERSION 3.4.6
...
+    && mv /opt/zookeeper/conf{,.template} \
+    && mkdir -p /opt/zookeeper/{conf,data,log}
 
 WORKDIR /opt/zookeeper
-VOLUME ["/opt/zookeeper/conf", "/opt/zookeeper/data", "/opt/zookeeper/log"]
 
 COPY config-and-run.sh ./bin/
-COPY zoo-template.cfg ./conf/
+COPY zoo-template.cfg ./conf.template/
+RUN chown -R jboss:jboss /opt/zookeeper
```
Comment (bparees) [inline examples/zookeeper/Dockerfile]: since the image may not run as jboss, this should be chown -R jboss:0
https://github.com/openshift/jenkins/blob/master/1/Dockerfile#L50

**Comment by ghyde** [comment]
@bparees I updated the Dockerfile.

**Comment by bparees** [comment]
lgtm, will merge post 3.3.

File: examples/zookeeper/config-and-run.sh [hunk 2]
```diff
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+# Check if conf folder is empty
+if [ ! "$(ls -A /opt/zookeeper/conf)" ]; then
```
Comment (stevekuznetsov) [inline examples/zookeeper/config-and-run.sh]: To test that `/opt/zookeper/conf` is a directory and empty, do:
```sh
if [[ -d '/opt/zookeeper/conf' && -z "$(ls -A '/opt/zookeeper/conf)" ]]; then
```

If you don't really care if it's a directory or not you could omit the first check.
```sh
if [[ -z "$(ls -A '/opt/zookeeper/conf)" ]]; then
```

Either way:
 - use a literal text check (`-z`) over the implicit check (`!`)
 - use `[[` over `[`

File: examples/zookeeper/config-and-run.sh [hunk 3]
```diff
@@ -1,5 +1,10 @@
...
+  cp /opt/zookeeper/conf.template/* /opt/zookeeper/conf/
```
Comment (stevekuznetsov) [inline examples/zookeeper/config-and-run.sh]: If what you want is not to over-write files that already exist, you could also `cp --no-clobber` instead of this `if` check.

File: examples/zookeeper/config-and-run.sh (hunk 2 above)
Comment (ghyde) [inline examples/zookeeper/config-and-run.sh]: The folder is already created via the VOLUME command in the Dockerfile, or the volumeMount in OpenShift. That's why I omitted the folder check. But, it's probably good to check.

File: examples/zookeeper/config-and-run.sh (hunk 3 above)
Comment (ghyde) [inline examples/zookeeper/config-and-run.sh]: `cp --no-clobber` is definitely the better option.

**Comment by ghyde** [comment]
@bparees @stevekuznetsov I applied the changes. How's it look now?

File: examples/zookeeper/config-and-run.sh [hunk 4]
```diff
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# Make sure conf folder exists
+if [[ ! -d /opt/zookeeper/conf ]]; then
+  mkdir -p /opt/zookeeper/conf
+fi
+
+# Copy config files if conf folder is empty
+cp --no-clobber /opt/zookeeper/conf.template/* /opt/zookeeper/conf/
```
Comment (bparees) [inline examples/zookeeper/config-and-run.sh]: this is going to copy any non-conflicting files.  you sure that's what you want?  The previous logic only copied files if the folder was empty. Now you're going to merge content.

File: examples/zookeeper/config-and-run.sh [hunk 5]
```diff
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+# Make sure conf folder exists
+if [[ ! -d /opt/zookeeper/conf ]]; then
```
Comment (stevekuznetsov) [inline examples/zookeeper/config-and-run.sh]: The use of `-p` below makes this `if` statement useless

File: examples/zookeeper/config-and-run.sh (hunk 4 above)
Comment (ghyde) [inline examples/zookeeper/config-and-run.sh]: You're right. The script should copy the files over only when the directory is completely empty (i.e., the first time the container is run with volumes attached).

**Comment by ghyde** [comment]
@bparees @stevekuznetsov Changes made.

**Comment by bparees** [comment]
lgtm

**Comment by smarterclayton** [comment]
[merge]
