### PR TITLE
Fix NameFromCommandArgs when passing command after -- 

### LINKED ISSUE #20728: oc create deploymentconfig is broken
```
[mfojtik@dev ~]$ oc create deploymentconfig test --image=centos:7 -- /bin/sleep infinity
error: exactly one NAME is required, got 3
```

@juanvallejo @soltysh seems like the args handling is not working when using the `--` syntax for command. We also might add some test/cmd to exercise this...

/kind bug
/sig master

### PR DESCRIPTION
**Pull request by soltysh**
Fix following invocation:
`oc create deploymentconfig name --image=myimage -- myargs`

/assign @juanvallejo @mfojtik 

Fixes #20728.

### CODE REVIEW

**Comment by soltysh** [comment]
Upstream merged, tagging accordingly.

File: test/cmd/create.sh [hunk 1]
```diff
@@ -13,6 +13,8 @@ trap os::test::junit::reconcile_output EXIT
 os::test::junit::declare_suite_start "cmd/create"
 # validate --dry-run outputs correct success message
 os::cmd::expect_success_and_text 'oc create quota quota --dry-run' 'resourcequota/quota created \(dry run\)'
+# validate -- works in create
+os::cmd::expect_success_and_text 'oc create deploymentconfig sleep --image=busybox -- /bin/sleep infinity' 'deploymentconfig.apps.openshift.io/sleep created'
```
Comment (mfojtik) [inline test/cmd/create.sh]: 👍
