### PR TITLE
Fix etcd flakes in integration and hack/update-swagger-spec

### LINKED ISSUE #7243: client: etcd cluster is unavailable or misconfigured
https://ci.openshift.redhat.com/jenkins/job/origin_extended/617/consoleFull

Is this the disk stall thing?

```
[INFO] OpenShift server health checks done at: 
Thu Feb 11 20:37:15 EST 2016
[INFO] Installing the registry
deploymentconfig "docker-registry" created
service "docker-registry" created
[INFO] Waiting for command to finish: '[[ "$(oc get endpoints docker-registry --output-version=v1 --template="{{ if .subsets }}{{ len .subsets }}{{ else }}0{{ end }}" --config=${ADMIN_KUBECONFIG} || echo "0")" != "0" ]]'...
Error from server: endpoints "docker-registry" not found
[INFO] Success running command: '[[ "$(oc get endpoints docker-registry --output-version=v1 --template="{{ if .subsets }}{{ len .subsets }}{{ else }}0{{ end }}" --config=${ADMIN_KUBECONFIG} || echo "0")" != "0" ]]' after 7 seconds
[INFO] Installing the router
serviceaccount "router" created
securitycontextconstraints "privileged" replaced
[INFO] Generating router TLS certificate
password for stats user admin has been set to KrLgnvWlAb
deploymentconfig "router" created
service "router" created
[INFO] Creating image streams
imagestream "nodejs" created
imagestream "perl" created
imagestream "php" created
imagestream "python" created
imagestream "wildfly" created
imagestream "mysql" created
imagestream "postgresql" created
imagestream "mongodb" created
imagestream "jenkins" created
Error from server: client: etcd cluster is unavailable or misconfigured
!!! Error in test/extended/core.sh:74
    'oc create -n openshift -f examples/image-streams/image-streams-centos7.json --config="${ADMIN_KUBECONFIG}"' exited with status 1
Call stack:
    1: test/extended/core.sh:74 main(...)
Exiting with status 1
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #7243

[test][merge] @liggitt @deads2k for review

### CODE REVIEW

File: hack/util.sh [hunk 1]
```diff
@@ -196,10 +196,10 @@ function start_os_master {
 
 	echo "[INFO] OpenShift server start at: "
 	date
-	
-	wait_for_url "${API_SCHEME}://${API_HOST}:${API_PORT}/healthz" "apiserver: " 0.25 80
-	wait_for_url "${API_SCHEME}://${API_HOST}:${API_PORT}/healthz/ready" "apiserver(ready): " 0.25 80
-	
+
+	wait_for_url "${API_SCHEME}://${API_HOST}:${API_PORT}/healthz" "apiserver: " 0.25 160
+	wait_for_url "${API_SCHEME}://${API_HOST}:${API_PORT}/healthz/ready" "apiserver(ready): " 0.25 160
```
Comment (deads2k) [inline hack/util.sh]: and not just 40 seconds to start.  40 seconds to **API server** start.  That's really bad.

File: test/integration/project_test.go [hunk 2]
```diff
@@ -15,7 +15,6 @@ import (
 
 // TestProjectIsNamespace verifies that a project is a namespace, and a namespace is a project
 func TestProjectIsNamespace(t *testing.T) {
-	defer testutil.RequireEtcd(t).Terminate(t)
```
Comment (deads2k) [inline test/integration/project_test.go]: I'm going to assume that I'm just missing this, but who's starting etcd now?  The `StartTestMaster`?

Comment (smarterclayton) [inline test/integration/project_test.go]: I fixed this, was a bad find and replace.

**Comment by smarterclayton** [comment]
Been running for 5-6 minutes and no failures.

File: hack/util.sh (hunk 1 above)
Comment (smarterclayton) [inline hack/util.sh]: Health comes up after etcd, and it looks like we're ~30s to etcd start,
so...  This could be a disk issue (but this is right after the disk is
zeroed out).  Maybe we run out of IOPs cloning and then zeroing the disk?

**Comment by deads2k** [comment]
Looks like both runs failed on an etcd flake.

**Comment by smarterclayton** [comment]
And these are actually etcd flakes, not imposed ones.

**Comment by smarterclayton** [comment]
Moving back to the issue to track the timeout failure.
