### PR TITLE
integration tests: wait for admission control cache to allow pod creation

### LINKED ISSUE #8589: Test flake in integration test TestRunOnceDurationAdmissionPluginProjectLimit
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/256/console

```
--- FAIL: TestRunOnceDurationAdmissionPluginProjectLimit-2 (13.66s)
	runonce_duration_test.go:38: project, no duration: unexpected: pods "testpod" is forbidden: no API token found for service account integration/default, retry after the token is automatically created and added to the service account
FAIL
Running TestSNI...
```

@csrwng

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #8589 
Added a utility function that waits for admission control to allow pods to be created. Switched tests that directly create pods to use the new function.

### CODE REVIEW

**Comment by csrwng** [comment]
@liggitt or @deads2k ptal

File: test/util/server/server.go [hunk 1]
```diff
@@ -395,6 +401,46 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+		testPod = &kapi.Pod{}
+		testPod.GenerateName = "test"
+		testPod.Spec.Containers = []kapi.Container{
+			{
+				Name:  "container",
+				Image: "test/image",
+			},
+		}
+	}
+	return wait.Poll(time.Second, PodCreationWaitTimeout, func() (bool, error) {
```
Comment (deads2k) [inline test/util/server/server.go]: pollimmediate

File: test/util/server/server.go [hunk 2]
```diff
@@ -395,6 +401,46 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+			// Only continue trying if the reason is that the API token was not found
+			msg := err.(kapierrors.APIStatus).Status().Message
+			if !strings.Contains(msg, "no API token found for service acccount") {
+				return false, err
+			}
+			return false, nil
+		}
+		err = client.Pods(namespace).Delete(pod.Name, &kapi.DeleteOptions{})
+		if err != nil {
+			return false, err
```
Comment (deads2k) [inline test/util/server/server.go]: don't need to fail, do you?

File: test/util/server/server.go [hunk 3]
```diff
@@ -395,6 +401,46 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
 	return foundTokenSecret && foundDockercfgSecret
 }
 
+// WaitForPodCreationServiceAccounts ensures that the service account needed for pod creation exists
+// and that the cache for the admission control that checks for pod tokens has caught up to allow
+// pod creation. A test pod can be passed to test admission creation. If nil, a default pod is used
+// for the test.
+func WaitForPodCreationServiceAccounts(client *kclient.Client, namespace string, serviceAccounts []string, testPod *kapi.Pod) error {
```
Comment (deads2k) [inline test/util/server/server.go]: I'm hard pressed to think of why someone would want to try with a particular pod.

File: test/util/server/server.go [hunk 4]
```diff
@@ -395,6 +401,46 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+	if err != nil {
+		return err
+	}
+	if testPod == nil {
+		testPod = &kapi.Pod{}
+		testPod.GenerateName = "test"
+		testPod.Spec.Containers = []kapi.Container{
+			{
+				Name:  "container",
+				Image: "test/image",
```
Comment (deads2k) [inline test/util/server/server.go]: Can you choose an image that is likely to be present on the node already or will pull very quickly?  Its possible that someone will lift this for our e2e which actually has a node.

File: test/util/server/server.go (hunk 2 above)
Comment (csrwng) [inline test/util/server/server.go]: you may want to ensure that you are starting your test with no pods in it.

File: test/util/server/server.go (hunk 3 above)
Comment (csrwng) [inline test/util/server/server.go]: Because you may be testing specific conditions for pods that would cause a simple pod to fail.

**Comment by csrwng** [comment]
[test]

File: test/util/server/server.go (hunk 3 above)
Comment (deads2k) [inline test/util/server/server.go]: > Because you may be testing specific conditions for pods that would cause a simple pod to fail.

Add it when we need it?  Seems extremely specific.

Comment (csrwng) [inline test/util/server/server.go]: sure, if @liggitt's ok with it. It was his suggestion :)

Comment (liggitt) [inline test/util/server/server.go]: fine to add later if we care

File: test/util/server/server.go (hunk 4 above)
Comment (liggitt) [inline test/util/server/server.go]: do we want the test pod to actually run?

File: test/util/server/server.go [hunk 5]
```diff
@@ -37,6 +39,10 @@ import (
 // controllers to start up, and populate the service accounts in the test namespace
 const ServiceAccountWaitTimeout = 30 * time.Second
 
+// PodCreationWaitTimeout is used to determine how long to wait after the service accocunt token
```
Comment (liggitt) [inline test/util/server/server.go]: typo

File: test/util/server/server.go [hunk 6]
```diff
@@ -395,6 +401,46 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+				return false, err
+			}
+			// Only continue trying if the reason is that the API token was not found
+			msg := err.(kapierrors.APIStatus).Status().Message
+			if !strings.Contains(msg, "no API token found for service acccount") {
+				return false, err
+			}
+			return false, nil
+		}
+		err = client.Pods(namespace).Delete(pod.Name, &kapi.DeleteOptions{})
```
Comment (liggitt) [inline test/util/server/server.go]: we want to delete immediately (not graceful deletion)

File: test/util/server/server.go (hunk 4 above)
Comment (deads2k) [inline test/util/server/server.go]: > do we want the test pod to actually run?

without a node?  doubtful.

File: test/util/server/server.go (hunk 5 above)
Comment (csrwng) [inline test/util/server/server.go]: fixed

File: test/util/server/server.go (hunk 6 above)
Comment (csrwng) [inline test/util/server/server.go]: fixed

File: test/util/server/server.go (hunk 3 above)
Comment (csrwng) [inline test/util/server/server.go]: removed

File: test/util/server/server.go [hunk 7]
```diff
@@ -395,6 +401,45 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+
+	return wait.PollImmediate(time.Second, PodCreationWaitTimeout, func() (bool, error) {
+		pod, err := client.Pods(namespace).Create(testPod)
+		if err != nil {
+			if !kapierrors.IsForbidden(err) {
+				return false, err
+			}
+			// Only continue trying if the reason is that the API token was not found
+			msg := err.(kapierrors.APIStatus).Status().Message
+			if !strings.Contains(msg, "no API token found for service acccount") {
```
Comment (liggitt) [inline test/util/server/server.go]: typo in "acccount", but I'm not even sure I'd check the particular error message

File: test/util/server/server.go [hunk 8]
```diff
@@ -395,6 +401,45 @@ func serviceAccountSecretsExist(client *kclient.Client, namespace string, sa *ka
...
+				return false, err
+			}
+			return false, nil
+		}
+		var immediately int64 = 0
+		err = client.Pods(namespace).Delete(pod.Name, &kapi.DeleteOptions{GracePeriodSeconds: &immediately})
```
Comment (liggitt) [inline test/util/server/server.go]: kapi.NewDeleteOptions(0)

File: test/util/server/server.go (hunk 7 above)
Comment (liggitt) [inline test/util/server/server.go]: maybe just log the error so we have visibility if we hit the timeout because of some other failure

File: test/util/server/server.go (hunk 8 above)
Comment (csrwng) [inline test/util/server/server.go]: cool

File: test/util/server/server.go (hunk 7 above)
Comment (csrwng) [inline test/util/server/server.go]: so keep on trying regardless of the error?

Comment (liggitt) [inline test/util/server/server.go]: I would. I also wonder about removing the service account aspect of this, especially since you're not using the given service accounts in the test pod.

Comment (deads2k) [inline test/util/server/server.go]: > I would. I also wonder about removing the service account aspect of this, especially since you're not using the given service accounts in the test pod.

that's probably an oversight more than intent.

Comment (csrwng) [inline test/util/server/server.go]: it looks like in at least the test cases where we use this we just use the default service account. so yeah, I guess it makes sense to just default to that and add the argument later if needed?

**Comment by csrwng** [comment]
latest comments addressed

**Comment by liggitt** [comment]
LGTM

**Comment by csrwng** [comment]
[merge]
