### PR TITLE
Fixes issue #8505 (https://github.com/openshift/origin/issues/8505)

### LINKED ISSUE #8505: Error on rsync not in container
When I try to rsync to a container that doesn't have rsync available the error message is not formatted properly. @bparees  suggested @csrwng look at it - though I may have misinterpreted.

This line is the error line
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/rsync/copymulti.go#L29

as it catches and returns from this line:

https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/rsync/copyrsync.go#L88

Here is the error I get 

spousty@gadol htdocs] $ ~/Downloads/oc rsync . httpd-1-wzrs5:/usr/local/apache2/htdocs 
WARNING: cannot use rsync: rsync not available in containerindex.html

Seems like it should 
1) Not append the file name to the output
2) Hint that I should try to use --strategy tar option

### PR DESCRIPTION
**Pull request by oatmealraisin**
Added newline print to warning when individual strategies fail, also changed return to report the correct issue.

fixes #8505

### CODE REVIEW

**Comment by bparees** [comment]
can you paste a sample of the new output in this PR?

**Comment by oatmealraisin** [comment]
New output looks like:

oc rsync test/ blog-1-build:/
WARNING: cannot use rsync: rsync not available in container
WARNING: cannot use tar: tar not available in container
error: No available strategies to copy to container.

Old output

WARNING: cannot use rsync: rsync not available in containerWARNING: cannot use tar: tar not available in containererror: tar not available in container

The old is on one line, and the returned error (that is printed..somewhere) is the last error from the loop

**Comment by bparees** [comment]
if you update the description to include "fixes #8505" it'll auto-close the issue when this PR merges.

also can you reword your commit to actually describe the change?  it's easier for people looking at the git log than having to go reference the issue based on the commit text.

(you can include a link to the issue in the body of the commit text, just make sure the first line is more meaningful)

**Comment by bparees** [comment]
@oatmealraisin bump, can you update the commit text?

**Comment by bparees** [comment]
hm, i see you added the description to the body.  close enough.
[merge]

File: pkg/cmd/cli/cmd/rsync/copymulti.go [hunk 1]
```diff
@@ -26,13 +26,14 @@ func (ss copyStrategies) Copy(source, destination *pathSpec, out, errOut io.Writ
...
-			fmt.Fprintf(errOut, "WARNING: cannot use %s: %v", s.String(), err.Error())
+			fmt.Fprintf(errOut, "WARNING: cannot use %s: %v\n", s.String(), err.Error())
 			continue
 		}
 		io.Copy(errOut, errBuf)
 		break
 	}
-	return err
+
+	return strategySetupError("No available strategies to copy to container.")
```
Comment (bparees) [inline pkg/cmd/cli/cmd/rsync/copymulti.go]: so this change is causing the test failure.  you're now always returning a failure message instead of a nil error when things are ok.

```
Running test/end-to-end/core.sh:288: executing 'oc rsync examples/sample-app frontend-1-73dal:/tmp' expecting success...
FAILURE after 0.428s: test/end-to-end/core.sh:288: executing 'oc rsync examples/sample-app frontend-1-73dal:/tmp' expecting success: the command returned the wrong error code
Standard output from the command:
sending incremental file list
sample-app/
sample-app/README.md
sample-app/application-template-custombuild.json
sample-app/application-template-dockerbuild.json
sample-app/application-template-pullspecbuild.json
sample-app/application-template-stibuild.json
sample-app/cleanup.sh
sample-app/container-setup.md
sample-app/github-webhook-example.json
sample-app/pullimages.sh
sample-app/logs/
sample-app/logs/.gitkeep

sent 92822 bytes  received 210 bytes  62021.33 bytes/sec
total size is 92073  speedup is 0.99

Standard error from the command:
error: No available strategies to copy to container.
```

File: pkg/cmd/cli/cmd/rsync/copymulti.go [hunk 2]
```diff
@@ -26,12 +26,19 @@ func (ss copyStrategies) Copy(source, destination *pathSpec, out, errOut io.Writ
 		err = s.Copy(source, destination, out, errBuf)
 		if _, isSetupError := err.(strategySetupError); isSetupError {
 			glog.V(4).Infof("Error output:\n%s", errBuf.String())
-			fmt.Fprintf(errOut, "WARNING: cannot use %s: %v", s.String(), err.Error())
+			fmt.Fprintf(errOut, "WARNING: cannot use %s: %v\n", s.String(), err.Error())
+
+			// Unless we set err back to nil in future strategies, we need to report an
+			// appropriate error
+			err = strategySetupError("No available strategies to copy to container.")
```
Comment (bparees) [inline pkg/cmd/cli/cmd/rsync/copymulti.go]: i'd tackle this a different way:
```
foundStrategy:=false
for s range ss {
  // blah blah
   if setup error {
     blah blah
    continue
   } 
   foundStrategy=true
} // end range loop

if err==nil && !foundStrategy {
  err=strategySetupError
}
return err
```

**Comment by oatmealraisin** [comment]
@csrwng ptal?

File: pkg/cmd/cli/cmd/rsync/copymulti.go [hunk 3]
```diff
@@ -21,17 +21,26 @@ var _ copyStrategy = copyStrategies{}
...
 			continue
 		}
+
 		io.Copy(errOut, errBuf)
+		foundStrategy = true
 		break
 	}
+
+	if !foundStrategy {
+		err = strategySetupError("No available strategies to copy to container.")
```
Comment (csrwng) [inline pkg/cmd/cli/cmd/rsync/copymulti.go]: just minor nit ... rsync can be used to copy "from" container as well. Maybe omit the "to container" part ?

Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/rsync/copymulti.go]: Done

**Comment by csrwng** [comment]
LGTM [merge]

**Comment by oatmealraisin** [comment]
Fixes https://github.com/openshift/origin/issues/5986
