### PR TITLE
Don't enforce quota in registry by default

### LINKED ISSUE #9393: Quota enforcement in registry is not disabled by default
The quota enforcer is always running (but it should be disabled unless the user opts in).  Breaks users who don't give limit range access to clients and is a regression.

@miminar

### PR DESCRIPTION
**Pull request by miminar**
The quota enforcement has been off by default for existing deployments.
Let's keep it off by default for the new ones as well.

Resolves #9393

### CODE REVIEW

**Comment by miminar** [comment]
[test][testextended][extended:core(admission)]

**Comment by miminar** [comment]
Flake #9402. And two errors in extended tests:

```
[Fail] [images] openshift limit range admission [It] should deny a push of built image exceeding openshift.io/Image limit 
/data/src/github.com/openshift/origin/test/extended/images/limitrange_admission.go:56

[Fail] [images] openshift limit range admission [It] should deny a push of built image exceeding limit on openshift.io/images resource 
/data/src/github.com/openshift/origin/test/extended/images/limitrange_admission.go:87
```

I need to investigate them. They may be test flakes or an error in server's admission plugin. Either way, this change didn't introduce the problem.

[test]

**Comment by smarterclayton** [comment]
This isn't enough (wont fix the issue) - the absence of the ENV var must default to "off" in the registry middleware - today the quotaEnforcing code is still added even when quota is off, which causes limit range checks, which breaks backwards compatibility.

The middleware needs to default to not using the quotaBlobStore if the env var isn't set to true

**Comment by smarterclayton** [comment]
When we add backward compat things, we can't default new features to on if those features also require changes to the master for several releases.

**Comment by miminar** [comment]
@smarterclayton but we default to **not** enforcing quota by default right now.
See [config file](https://github.com/openshift/origin/blob/master/images/dockerregistry/config.yml#L21) and [middleware's default](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/quotarestrictedblobstore.go#L58).

So you'd have to have either a custom config file or a new deployment config created with current defaults (the enforce env var set to `true`) to have it enabled.

**Comment by miminar** [comment]
@smarterclayton oh I see now. There's a bug. Will update.

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 1]
```diff
@@ -168,7 +168,7 @@ func (r *repository) Blobs(ctx context.Context) distribution.BlobStore {
 
 	bs := r.Repository.Blobs(ctx)
 
-	if quotaEnforcing != nil {
+	if !quotaEnforcing.enforcementDisabled {
```
Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: @smarterclayton this was the culprit - well, my accomplice.

Comment (smarterclayton) [inline pkg/dockerregistry/server/repositorymiddleware.go]: :).  After Alexey lands his changes to distribution I have a refactor to the middleware initialization path that prevents us from reloading the clients multiple times (which was not intentional) that will affect some of this code.  But the quick fix here is good.

**Comment by miminar** [comment]
So the extended tests actually fail because of issue #9343 (tl;dr; we fail to parse output of docker 1.10). The builder reports succes for failer. The images are actually refused as reported by registry:

```
time="2016-06-17T17:40:53.920732704Z" level=error msg="response completed with error" err.code=DENIED err.message="requested access to the resource is denied"
```

**Comment by miminar** [comment]
The other was flake #9129. [test]

**Comment by smarterclayton** [comment]
Lgtm [merge]

Will be part of 1.3.0.alpha.2

**Comment by smarterclayton** [comment]
[merge]

```

=== BEGIN TEST CASE ===
test/cmd/basicresources.sh:238: executing 'oc create -f
test/testdata/external-service.yaml' expecting success
FAILURE after 0.618s: test/cmd/basicresources.sh:238: executing 'oc
create -f test/testdata/external-service.yaml' expecting success: the
command returned the wrong error code
There was no output from the command.
Standard error from the command:
The Service "external" is invalid.
spec.clusterIP: Invalid value: "172.30.0.100": provided IP is already allocated
=== END TEST CASE ===

```
