### PR TITLE
new-app: fix newapp test flake

### LINKED ISSUE #4948: test-cmd new-app flake
https://travis-ci.org/openshift/origin/jobs/83369573

```
error: no image or template matched "openshift/bogusImage", specify --allow-missing to use this image name.
!!! Error in test/cmd/newapp.sh:86
	'[ "$(oc new-app  openshift/bogusImage https://github.com/openshift/ruby-hello-world.git -o yaml --allow-missing)" ]' exited with status 1
Call stack:
	1: test/cmd/newapp.sh:86 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:272
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:272 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #4948

### CODE REVIEW

**Comment by csrwng** [comment]
@deads2k ptal

**Comment by csrwng** [comment]
[test]

File: pkg/generate/app/dockerimagelookup.go [hunk 1]
```diff
@@ -76,7 +76,7 @@ func (r DockerClientSearcher) Search(terms ...string) (ComponentMatches, error)
 				termMatches = append(termMatches, matches...)
 			case ErrNoMatch:
 			default:
-				return nil, err
+				glog.V(1).Infof("An error occurred searching the Docker registry: %v", err)
```
Comment (deads2k) [inline pkg/generate/app/dockerimagelookup.go]: This isn't an obvious change to me.  Why are we now ignoring any match error for docker?

Comment (kargakis) [inline pkg/generate/app/dockerimagelookup.go]: Is there a possibility I run new-app and get no output now because of this? If so, we may want to output by default.

Comment (csrwng) [inline pkg/generate/app/dockerimagelookup.go]: The registry is just one of our search sources. If we can't find anything we should simply move on to search on the next source (the local docker daemon), if available. This is basically doing the same for the registry as we do for other sources. If for example we don't have a local docker accessible, we simply don't search it or get any results from it. Same for the openshift server if we can't connect to it to search for image streams or templates.

Comment (csrwng) [inline pkg/generate/app/dockerimagelookup.go]: > Is there a possibility I run new-app and get no output now because of this? If so, we may want to output by default.

You will always get an output, saying that we couldn't find a match for your input.

Comment (kargakis) [inline pkg/generate/app/dockerimagelookup.go]: Ok, just wanted to make sure

**Comment by deads2k** [comment]
@csrwng travis still fails on the same line.

```
service "ruby-hello-world" deleted
error: no image or template matched "openshift/bogusImage", specify --allow-missing-images to use this image name.
!!! Error in test/cmd/newapp.sh:86
	'[ "$(oc new-app  openshift/bogusImage https://github.com/openshift/ruby-hello-world.git -o yaml --allow-missing-images)" ]' exited with status 1
Call stack:
	1: test/cmd/newapp.sh:86 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:272
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:272 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by csrwng** [comment]
@deads2k  I am disabling the test until we get a fix for it. Created the issue #4991 to track it

**Comment by deads2k** [comment]
> @deads2k I am disabling the test until we get a fix for it. Created the issue #4991 to track it

Ok.  Once travis goes green, I'll merge.

**Comment by kargakis** [comment]
I think this is ok to merge. Travis error is related to the upstream websocket patch we are carrying @smarterclayton fyi
```
2015/10/07 15:54:05 http: panic serving 127.0.0.1:35389: bad read
goroutine 16 [running]:
net/http.func·011()
	/usr/local/go/src/net/http/server.go:1130 +0xcc
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*errorReader).Read(0xc20803a680, 0xc20812e800, 0x800, 0x800, 0xc20800ac40, 0x0, 0x0)
	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:151 +0x129
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.messageCopy(0xc20807c3f0, 0x2af1ac8751e0, 0xc20803a680, 0xc208000000, 0x0, 0x0, 0x0)
	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/_test/_obj_test/stream.go:105 +0x2aa
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.(*Reader).handle(0xc2080ae060, 0xc20807c3f0)
	github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/_test/_obj_test/stream.go:79 +0x2c6
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream.func·009(0xc20807c3f0)
	/home/travis/gopath/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream/stream_test.go:171 +0x1aa
golang.org/x/net/websocket.Server.serveWebSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa2f988, ...)
	/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:89 +0x2db
golang.org/x/net/websocket.Handler.ServeHTTP(0xc20800a4e0, 0x2af1ac874de0, 0xc208104320, 0xc20801e1a0)
	/home/travis/gopath/src/github.com/openshift/origin/Godeps/_workspace/src/golang.org/x/net/websocket/server.go:112 +0x9b
net/http/httptest.(*waitGroupHandler).ServeHTTP(0xc20800a640, 0x2af1ac874de0, 0xc208104320, 0xc20801e1a0)
	/usr/local/go/src/net/http/httptest/server.go:200 +0xf8
net/http.serverHandler.ServeHTTP(0xc2080b67e0, 0x2af1ac874de0, 0xc208104320, 0xc20801e1a0)
	/usr/local/go/src/net/http/server.go:1703 +0x1f7
net/http.(*conn).serve(0xc208104280)
	/usr/local/go/src/net/http/server.go:1204 +0x1088
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:1751 +0x3cd
--- FAIL: TestStreamClosedDuringRead-2 (0.12s)
	stream_test.go:131: unexpected server read: []
FAIL
coverage: 70.4% of statements
FAIL	
github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/wsstream	0.679s
```

**Comment by deads2k** [comment]
re[test]

**Comment by deads2k** [comment]
jenkins issue re[test]

**Comment by deads2k** [comment]
still failing travis.  New error this time:

```
test/cmd/newapp.sh: line 96: docker: command not found
!!! Error in test/cmd/newapp.sh:96
	'docker build -t test/scratchimage .' exited with status 127
Call stack:
	1: test/cmd/newapp.sh:96 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:272
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:272 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by csrwng** [comment]
Created an issue to create an extended test for the local docker image: https://github.com/openshift/origin/issues/5000 and removed it from newapp.sh

**Comment by deads2k** [comment]
[merge]
