### PR TITLE
Import from repository doesn't panic

### LINKED ISSUE #8593: null refernce in case docker manifest does not contain "signatures" section
I've tried to import-image an imagestream which is connected to a nexus3 docker repo.

##### Version
oc v1.1.6
kubernetes v1.2.0-36-g4a3f9c5

##### Steps To Reproduce
1. oc image-import 
2. exception comes

##### Current Result

[stacktrace on the server](https://github.com/openshift/origin/files/230844/stacktrace.txt)
[manifest file](https://github.com/openshift/origin/files/230847/latest.json.txt)

##### Expected Result

I think the error "missing singer key" might be ok as a problem where we bail out, but a null deference stacktrace should be fixed. I did not yet understood why the signatures part was not added in the repo.

### PR DESCRIPTION
**Pull request by miminar**
- Check the import status before a use of image object.
- Also to set tag names on import status objects in order to produce
  nice output (containing tag names that failed to import).

Resolves #8593

cc @smarterclayton, @legionus

### CODE REVIEW

File: pkg/image/registry/imagestreamimport/rest.go [hunk 1]
```diff
@@ -278,6 +278,18 @@ func checkImportFailure(status api.ImageImportStatus, stream *api.ImageStream, t
...
 		LastTransitionTime: now,
 	}
+
+	if tag == "" && status.Image != nil {
+		image := status.Image
+		ref, err := api.ParseDockerImageReference(image.DockerImageReference)
+		if err == nil {
+			tag = ref.Tag
+			if len(status.Tag) > 0 {
+				tag = status.Tag
```
Comment (legionus) [inline pkg/image/registry/imagestreamimport/rest.go]: This assignment doesn't use the `ref`. Why this `if` inside `err == nil` ?

Comment (miminar) [inline pkg/image/registry/imagestreamimport/rest.go]: Good catch, this block needs to be moved outside of `if err == nil`.

**Comment by smarterclayton** [comment]
Please add a test that exercises all the failure paths here

**Comment by miminar** [comment]
Comments addressed.

**Comment by smarterclayton** [comment]
LGTM thanks [merge]
