### PR TITLE
Fix regression: new-app with custom Git ref

### LINKED ISSUE #6345: oc new-app doesn't work with custom branch
The help gives an example:

```console
$ oc new-app --help
...                                                  
  # Create an application from a remote repository using its beta4 branch  
  $ oc new-app https://github.com/openshift/ruby-hello-world#beta4         
...
```

But it doesn't work:

```console
$ oc new-app https://github.com/openshift/ruby-hello-world#beta4
error: no match for "https://github.com/openshift/ruby-hello-world#beta4", specify --allow-missing-images to use this image name.

The 'new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet
or is only on the local system.

See 'new-app' for examples.
```

And blindly following the advice of "--allow-missing-images" leads to even more confusion:

```console
$ oc new-app https://github.com/openshift/ruby-hello-world#beta4 --allow-missing-images                                                                                      
error: can't include "https://github.com/openshift/ruby-hello-world#beta4": can't include "https://github.com/openshift/ruby-hello-world#beta4": the docker pull spec "https://github.com/openshift/ruby-hello-world#beta4" must be two or three segments separated by slashes
```

### PR DESCRIPTION
**Pull request by rhcarvalho**
Fixes #6345.

Regression introduced in 891fc216e97b9b74cc7f2ba4a568022b1e92a4e4.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees @gabemontero PTAL

[test]

File: pkg/generate/app/sourcelookup.go [hunk 1]
```diff
@@ -15,6 +16,11 @@ import (
 	s2igit "github.com/openshift/source-to-image/pkg/scm/git"
 )
 
+var (
+	argumentGit         = regexp.MustCompile("^(http://|https://|git@|git://).*(?:#([a-zA-Z0-9]*))?$")
+	argumentGitProtocol = regexp.MustCompile("^(git@|git://)")
```
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: @gabemontero I'm reintroducing these to fix a regression, perhaps you have in mind a better solution?
Should we also fix something in S2I?

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: why not just strip the #foo anchor off the end if present and then call IsRemoteRepository?

Comment (gabemontero) [inline pkg/generate/app/sourcelookup.go]: yeah, ideally, the logic in source-to-image/pkg/scm/git/git.go should not choke on the #foo (I'm assuming ParseURL/url.Parse is returning an err)

Comment (gabemontero) [inline pkg/generate/app/sourcelookup.go]: and we would add an url with #foo as a test in source-to-image/pkg/scm/git/git_test.go

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: @bparees do you know where do we make `#foo` become the ref?

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: url.Parse shouldn't choke on an anchor tag....

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: @rhcarvalho not offhand, sorry.  i'm just suggesting you strip it for the validation check, leave it on otherwise.

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: but it is a good point that #foo is valid in a url, so this shouldn't be failng validation at all, even without special casing it.

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: nvm... `urlWithoutRef`

Comment (gabemontero) [inline pkg/generate/app/sourcelookup.go]: url.Parse *shouldn't* choke on it, but from my experience, it chokes on a few things it shouldn't choke on ;-)

i would still add the failing URL example to the git_test.go file I mentioned, and debug there to make sure the expected validation decision is occurring vs. adding the precursor checking in sourcelookup.go

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: The problem is in ListRemote:

```go
if _, _, err := gitRepo.ListRemote(s); err != nil {
	log.Printf("ls-remote err = %v", err)
	return false
}
```

```
ls-remote err = fatal: https://github.com/openshift/ruby-hello-world#beta4/info/refs not valid: is this a git repository?
```

**Comment by rhcarvalho** [comment]
Based on the discussion, I've changed the approach. Now we just remove the fragment part of the URL before calling `git ls-remote`.

@bparees PTAL

File: pkg/generate/app/sourcelookup.go (hunk 1 above)
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: ok, so i'm back to the position that we should strip the # before checking for git-validity.

**Comment by rhcarvalho** [comment]
Test failure is a known flake: https://github.com/openshift/origin/issues/6065

File: pkg/generate/app/sourcelookup.go (hunk 1 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: That's what I've done :+1:

**Comment by bparees** [comment]
lgtm [merge]
