### PR TITLE
Skip registry client test if registry is not reachable

### LINKED ISSUE #5559: external registry ping flake on Jenkins
Error log [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6540/console):
```
--- FAIL: TestRegistryClientConnectPulpRegistry-2 (0.31s)
	dockerregistryclient_test.go:47: unable to retrieve image info: error checking for V2 registry at https://registry.access.redhat.com/v2/: Get https://registry.access.redhat.com/v2/: read tcp 209.132.182.63:443: connection reset by peer
FAIL
```

### PR DESCRIPTION
**Pull request by miminar**
Resolves #5559

### CODE REVIEW

**Comment by miminar** [comment]
@stevekuznetsov could you please take a look?

File: test/integration/dockerregistryclient_test.go [hunk 1]
```diff
@@ -3,12 +3,54 @@
...
+		errStr = err.Error()
+	}
+	return true, errStr
+}
+
+// requireReachableRegistry allows to skip a test if given registry cannot be reached or resolved.
+func requireReachableRegistry(t *testing.T, registry, version string, allowInsecure bool) {
+	reachable, err := isRegistryReachable(registry, version, allowInsecure)
+	if !reachable {
+		t.Skip("skipping due to unreachable registry %s: %v", registry, err)
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: Can you show sample output we'll get from `hack/test-integration.sh`?  I'm not completely comfortable with the idea of skipping these, but I don't know for sure that I'm opposed either.

File: test/integration/dockerregistryclient_test.go [hunk 2]
```diff
@@ -3,12 +3,54 @@
...
+				}
+			}
+		}
+		errStr = err.Error()
+	}
+	return true, errStr
+}
+
+// requireReachableRegistry allows to skip a test if given registry cannot be reached or resolved.
+func requireReachableRegistry(t *testing.T, registry, version string, allowInsecure bool) {
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: Check an env var of some kind to allow us to always force this to run the test.  If we take this, there are cases where we'll want to be sure this runs.

Plumb the value down from test-integration.sh

File: test/integration/dockerregistryclient_test.go (hunk 1 above)
Comment (stevekuznetsov) [inline test/integration/dockerregistryclient_test.go]: Once the jUnit integration is in we'll be able to easily see skips. This is nice.

File: test/integration/dockerregistryclient_test.go [hunk 3]
```diff
@@ -3,12 +3,54 @@
...
+// isRegistryReachable returns false if a Get on registry url fails with similar error:
+//   Get https://registry.com/v2/: dial tcp registry.com:443: i/o timeout
+//   Get https://registry.com/v2/: dial tcp: lookup registry.com: no such host
+//   Get https://registry.com/v2/: dial tcp registry.com:443: getsockopt: connection refused
+//   Get https://registry.com/v2/: read tcp 127.0.0.1:39849->registry.com:443: read: connection reset by peer
+func isRegistryReachable(registry, version string, allowInsecure bool) (bool, string) {
+	client := http.Client{Timeout: time.Second * 4}
+	_, err := client.Get(fmt.Sprintf("https://%s/%s/", registry, version))
+	if err != nil && allowInsecure {
+		_, err = http.Get(fmt.Sprintf("http://%s/%s/", registry, version))
```
Comment (stevekuznetsov) [inline test/integration/dockerregistryclient_test.go]: If I'm asking for an insecure connection, why bother doing the `GET` on `https` in the first place?

File: test/integration/dockerregistryclient_test.go [hunk 4]
```diff
@@ -37,6 +79,8 @@ func TestRegistryClientConnect(t *testing.T) {
 }
 
 func TestRegistryClientConnectPulpRegistry(t *testing.T) {
+	requireReachableRegistry(t, "registry.access.redhat.com", "v2", false)
```
Comment (stevekuznetsov) [inline test/integration/dockerregistryclient_test.go]: Might as well make these strings `const` so there can't be drift between their uses.

File: test/integration/dockerregistryclient_test.go [hunk 5]
```diff
@@ -3,12 +3,54 @@
...
+		switch t := err.(type) {
+		case *url.Error:
+			switch t := t.Err.(type) {
+			case *net.OpError:
+				if t.Op == "dial" || t.Op == "read" {
+					return false, err.Error()
+				}
+			}
+		}
+		errStr = err.Error()
```
Comment (stevekuznetsov) [inline test/integration/dockerregistryclient_test.go]: Why choose the message over the error?

File: test/integration/dockerregistryclient_test.go (hunk 1 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: `hack/test-integration.sh` shows just `ok`:

    $ printf "127.0.0.2 index.docker.io docker.io" >> /etc/hosts
    $ ./hack/test-integration.sh '^TestRegistry'

    Test test/integration -tags='integration !docker etcd' ...

    Building test executable...
    Starting etcd...
    etcd: {"etcdserver":"2.1.1","etcdcluster":"2.1.0"}
    {"message":"Internal Server Error"}
    ok      TestRegistryClientConnect
    ok      TestRegistryClientConnectPulpRegistry
    ok      TestRegistryClientDockerHubV2
    ...

I can see the skip message only when I run the tests manually:

    $ go test -test.run TestRegistryClient -v ./test/integration/dockerregistryclient_test.go 
    === RUN TestRegistryClientConnect
    --- PASS: TestRegistryClientConnect (0.00s)
    === RUN TestRegistryClientConnectPulpRegistry
    --- PASS: TestRegistryClientConnectPulpRegistry (3.71s)
    === RUN TestRegistryClientDockerHubV2
    --- SKIP: TestRegistryClientDockerHubV2 (0.00s)
            dockerregistryclient_test.go:48: skipping due to unreachable registry index.docker.io: Get https://index.docker.io/v2/: dial tcp 127.0.0.2:443: connection refused
    === RUN TestRegistryClientDockerHubV1
    ...

I'll shorten the skip message a bit.

File: test/integration/dockerregistryclient_test.go (hunk 2 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Will do.

File: test/integration/dockerregistryclient_test.go (hunk 3 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Docker and OpenShift clients do the same. They first try `https` and if they fail, they fallback to `http`.

File: test/integration/dockerregistryclient_test.go (hunk 5 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: I considered it a log message, not an error leading to a test failure. But in the end `error` probably makes more sense.

File: test/integration/dockerregistryclient_test.go (hunk 4 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Makes sense. Will do.

File: test/integration/dockerregistryclient_test.go (hunk 1 above)
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: > hack/test-integration.sh shows just ok:

You'll need to update that to indicate the skip.

File: test/integration/dockerregistryclient_test.go (hunk 2 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: @deads2k resolved. I added `LET_UNREACHABLE_FAIL`. Couldn't think of a better name.

**Comment by miminar** [comment]
Issues addressed. Example output:

    ./hack/test-integration.sh '^TestRegistry'

    Test test/integration -tags='integration !docker etcd' ...

    Building test executable...
    Starting etcd...
    etcd: {"etcdserver":"2.1.1","etcdcluster":"2.1.0"}
    {"message":"Internal Server Error"}
    skipped TestRegistryClientConnect
            dockerregistryclient_test.go:57: skipping due to unreachable registry: Get https://index.docker.io/v2/: dial tcp 127.0.0.2:443: connection refused
    skipped TestRegistryClientConnectPulpRegistry
            dockerregistryclient_test.go:57: skipping due to unreachable registry: Get https://registry.access.redhat.com/v2/: dial tcp 127.0.0.2:443: connection refused
    ok      TestRegistryClientDockerHubV1
    skipped TestRegistryClientDockerHubV2
            dockerregistryclient_test.go:57: skipping due to unreachable registry: Get https://index.docker.io/v2/: dial tcp 127.0.0.2:443: connection refused
    ok      TestRegistryClientImageV1
    skipped TestRegistryClientImageV2
            dockerregistryclient_test.go:57: skipping due to unreachable registry: Get https://index.docker.io/v2/: dial tcp 127.0.0.2:443: connection refused
    ok      TestRegistryClientQuayIOImage
    ok      TestRegistryClientRegistryNotFound

    real    0m10.082s
    user    0m1.169s
    sys     0m0.308s
    ./hack/test-integration.sh took 40 seconds

    Complete

**Comment by deads2k** [comment]
@miminar I might should have led with this.  Do you see this as something we'll turn on in the merge queue (I'd probably tend towards no, but I think @bparees is the most affected) or do you see as something for your local runs.

Since `test-cmd.sh` will fail without docker connectivity, I assumed this was for local invocations, but you defaulted the env-var to "allow skip"

**Comment by deads2k** [comment]
@miminar what about a retry on some kinds of failure instead of a skip?

File: hack/test-integration.sh [hunk 6]
```diff
@@ -99,19 +105,30 @@ trap cleanup EXIT SIGINT
...
+	fi
+	if [[ -n "${VERBOSE:-}" ]]; then
+		echo "$out"
 	fi
 
 	tput cuu 1 # Move up one line
 	tput el		# Clear "running" line
 
-	if [[ ${result} -eq 0 ]]; then
+	if [[ $skipped = 1 ]]; then
```
Comment (liggitt) [inline hack/test-integration.sh]: move the skip check inside the if ${result} -eq 0... skips should qualify a 0 return code that would otherwise be reported as success, not excuse a non-zero return code

**Comment by liggitt** [comment]
I don't want any "skip if unavailable" tests running in the merge queue... we need to be able to know what tests are running. I'm also concerned what skipping this test could allow into master. Do we have alternative tests we could do that don't depend on dockerhub? Do we need to move this into extended tests instead (and skip the check, so we know when it fails)?

**Comment by bparees** [comment]
@deads2k not clear why i'm affected by this?

but i agree with everything else that's been said that it's a bad idea...certainly as a default.

**Comment by miminar** [comment]
> Since test-cmd.sh will fail without dockerhub connectivity, I assumed this was for local invocations, but you defaulted the env-var to "allow skip"

My concern is a [flake #5559](https://github.com/openshift/origin/issues/5559). That's why I defaulted to *skip*.

> what about a retry on some kinds of failure instead of a skip?

@deads2k it might occasionally help.

> Do we have alternative tests we could do that don't depend on dockerhub? Do we need to move this into extended tests instead (and skip the check, so we know when it fails)?

@liggitt the problematic registry is our `registry.access.redhat.com`. There's no connection issue in recent Jenkins history to Docker hub. But I think they should be treated the same way.

Moving the tests to extended seems reasonable to me. @deads2k, @bparees any objections?

**Comment by deads2k** [comment]
> Moving the tests to extended seems reasonable to me. @deads2k, @bparees any objections?

Let's try the retry first.  Extended tests don't get much attention.

**Comment by miminar** [comment]
@deads2k Ok, rewritten.

File: test/integration/dockerregistryclient_test.go [hunk 7]
```diff
@@ -4,11 +4,61 @@ package integration
...
+	quayRegistryName        = "quay.io"
+
+	maxRetryCount = 4
+	retryAfter    = time.Millisecond * 500
+)
+
+var reUnreachableErr *regexp.Regexp
+
+func init() {
+	reUnreachableErr = regexp.MustCompile(`(?:dial|read) tcp|net/http|could not be reached`)
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: heh, might need a test for the test.  I can definitely see the intent, but I can't say with certainty that this fulfills the intent.  @liggitt can you read it?

Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: :) ok, I'll split it with into few `strings.Contains()` tests.

File: test/integration/dockerregistryclient_test.go [hunk 8]
```diff
@@ -4,11 +4,68 @@ package integration
...
+
+		if reachable {
+			if failOnError {
+				t.Fatalf("got unexpected error: %v", err)
+			}
+			return err
+		}
+
+		if attempt >= maxRetryCount {
+			t.Fatalf("registry unreachable: %v", err)
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: return an error in this case

File: test/integration/dockerregistryclient_test.go [hunk 9]
```diff
@@ -4,11 +4,68 @@ package integration
...
+			"could not be reached",
+		} {
+			if strings.Contains(err.Error(), substr) {
+				reachable = false
+				break
+			}
+		}
+
+		if reachable {
+			if failOnError {
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: just return the error and let the caller sort out what he wants to do.

File: test/integration/dockerregistryclient_test.go [hunk 10]
```diff
@@ -4,11 +4,68 @@ package integration
...
+	retryAfter    = time.Millisecond * 500
+)
+
+// retryWhenUnreachable invokes given function several times until it succeeds,
+// returns network unrelated error or maximum number of attempts is reached.
+// Should be used to wrap calls to remote registry to prevent test failures
+// because of short-term outages.
+func retryWhenUnreachable(t *testing.T, failOnError bool, f func() error) error {
+	timeout := retryAfter
+	for attempt, err := 0, f(); err != nil; attempt, err = attempt+1, f() {
```
Comment (deads2k) [inline test/integration/dockerregistryclient_test.go]: I find this construction difficult to read, but I don't feel strongly enough in test code to force it to change.

**Comment by deads2k** [comment]
I think I'll like it after the API tweak

File: test/integration/dockerregistryclient_test.go (hunk 10 above)
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: simplified

**Comment by miminar** [comment]
@deads2k addressed. Thanks for patience :).

**Comment by deads2k** [comment]
lgtm [merge]
