### PR TITLE
handle forbidden server errs on older versions

### LINKED ISSUE #10082: `oc version` fails to get server version with "error: unexpected end of JSON input"
```
$ oc cluster up
...
$ oc login -u system:admin
You have access to the following projects and can switch between them with 'oc project <projectname>':

    default
  * myproject
    openshift
    openshift-infra

Using project "myproject".
$ oc version
oc v1.3.0-alpha.2+75fce88
kubernetes v1.3.0+57fb9ac
features: Basic-Auth
error: unexpected end of JSON input
```

/cc @juanvallejo @deads2k @fabianofranz

### PR DESCRIPTION
**Pull request by juanvallejo**
Older server versions do not support the `/version/openshift` endpoint. This updates error handling on `pkg/cmd/cli/cmd/version.go` to give a better output:

##### Before on an older server image
```
oc v1.3.0-alpha.2+75fce88
kubernetes v1.3.0+57fb9ac
features: Basic-Auth
error: unexpected end of JSON input
```

**The error at the end changed from** `error: unexpected end of JSON input` **to** `Error from server: User "<user>" cannot "get" on "/version/openshift"` when issuing command from a non-admin account.

##### After on the same image
```
oc v1.3.0-alpha.0+efda5a8-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth

Server https://10.13.137.149:8443
OpenShift unknown
Kubernetes v1.2.0-36-g4a3f9c5
```

"Unauthorized" users would no longer receive the error about not being able to make a "get" request to the version endpoint (this error would be ignored) as by default ["that rule is in the system:discovery role, which is granted to all users by default"](https://github.com/openshift/origin/issues/10081#issuecomment-235893420)

fixes #10082 and #10081 

cc @fabianofranz @deads2k @liggitt @stevekuznetsov

### CODE REVIEW

**Comment by juanvallejo** [comment]
[test]

File: pkg/cmd/cli/cmd/version.go [hunk 1]
```diff
@@ -126,13 +126,14 @@ func (o VersionOptions) RunVersion() error {
 		}
 
 		ocVersionBody, err := oClient.Get().AbsPath("/version/openshift").Do().Raw()
-		if err != nil && !(kapierrors.IsNotFound(err) || kapierrors.IsUnauthorized(err)) {
+		if err != nil && !(kapierrors.IsNotFound(err) || kapierrors.IsUnauthorized(err) || kapierrors.IsForbidden(err)) {
```
Comment (stevekuznetsov) [inline pkg/cmd/cli/cmd/version.go]: Wasn't the JSON error a NotFound?

File: pkg/cmd/cli/cmd/version.go [hunk 2]
```diff
@@ -126,13 +126,14 @@ func (o VersionOptions) RunVersion() error {
...
 			done <- err
 			return
 		}
 		var ocServerInfo version.Info
+
 		err = json.Unmarshal(ocVersionBody, &ocServerInfo)
-		if err != nil {
+		if err != nil && len(ocVersionBody) > 0 {
```
Comment (stevekuznetsov) [inline pkg/cmd/cli/cmd/version.go]: Would make more sense to check for the 404 explicitly instead of this

File: pkg/cmd/cli/cmd/version.go (hunk 1 above)
Comment (juanvallejo) [inline pkg/cmd/cli/cmd/version.go]: No, the JSON error for some reason "found" the endpoint, but returned an empty response, that's why I check for a non-empty byte array in [L136](https://github.com/openshift/origin/pull/10093#discussion-diff-72683831R136)

Comment (stevekuznetsov) [inline pkg/cmd/cli/cmd/version.go]: When I was standing over your shoulder I thought it was surely a 404 since it was the older server ... maybe I'm crazy.

Comment (stevekuznetsov) [inline pkg/cmd/cli/cmd/version.go]: Yep, definitely crazy

Comment (juanvallejo) [inline pkg/cmd/cli/cmd/version.go]: No worries, here's the `--loglevel=10` output:

`$ oc login -u developer`
`$ oc version --loglevel=10`
```
oc v1.3.0-alpha.0+f2ac159-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth
I0728 18:07:32.674349   13549 loader.go:330] Config loaded from file /home/jvallejo/Documents/go/src/github.com/openshift/origin/openshift.local.config/master/admin.kubeconfig
I0728 18:07:32.674974   13549 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0+57fb9ac (linux/amd64) kubernetes/57fb9ac" -H "Authorization: Bearer 8u242_OKlT-6gNAZ5oMWaInl3yZ1-wGvxdodDHZKWeU" https://10.13.137.149:8443/api
I0728 18:07:32.698810   13549 round_trippers.go:318] GET https://10.13.137.149:8443/api 200 OK in 23 milliseconds
I0728 18:07:32.698836   13549 round_trippers.go:324] Response Headers:
I0728 18:07:32.698843   13549 round_trippers.go:327]     Cache-Control: no-store
I0728 18:07:32.698849   13549 round_trippers.go:327]     Content-Type: application/json
I0728 18:07:32.698855   13549 round_trippers.go:327]     Date: Thu, 28 Jul 2016 22:07:32 GMT
I0728 18:07:32.698861   13549 round_trippers.go:327]     Content-Length: 136
I0728 18:07:32.698908   13549 request.go:901] Response Body: {"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]}
I0728 18:07:32.699103   13549 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: oc/v1.3.0+57fb9ac (linux/amd64) kubernetes/57fb9ac" -H "Accept: application/json, */*" -H "Authorization: Bearer 8u242_OKlT-6gNAZ5oMWaInl3yZ1-wGvxdodDHZKWeU" https://10.13.137.149:8443/apis
I0728 18:07:32.700191   13549 round_trippers.go:318] GET https://10.13.137.149:8443/apis 200 OK in 1 milliseconds
I0728 18:07:32.700204   13549 round_trippers.go:324] Response Headers:
I0728 18:07:32.700212   13549 round_trippers.go:327]     Content-Type: application/json
I0728 18:07:32.700218   13549 round_trippers.go:327]     Date: Thu, 28 Jul 2016 22:07:32 GMT
I0728 18:07:32.700222   13549 round_trippers.go:327]     Content-Length: 1382
I0728 18:07:32.700225   13549 round_trippers.go:327]     Cache-Control: no-store
I0728 18:07:32.700260   13549 request.go:901] Response Body: {"kind":"APIGroupList","groups":[{"name":"apps","versions":[{"groupVersion":"apps/v1alpha1","version":"v1alpha1"}],"preferredVersion":{"groupVersion":"apps/v1alpha1","version":"v1alpha1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]},{"name":"authentication.k8s.io","versions":[{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"authentication.k8s.io/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]},{"name":"autoscaling","versions":[{"groupVersion":"autoscaling/v1","version":"v1"}],"preferredVersion":{"groupVersion":"autoscaling/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]},{"name":"batch","versions":[{"groupVersion":"batch/v1","version":"v1"},{"groupVersion":"batch/v2alpha1","version":"v2alpha1"}],"preferredVersion":{"groupVersion":"batch/v1","version":"v1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]},{"name":"extensions","versions":[{"groupVersion":"extensions/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"extensions/v1beta1","version":"v1beta1"},"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.13.137.149:8443"}]}]}
I0728 18:07:32.700960   13549 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: oc/v1.3.0 (linux/amd64) openshift/f2ac159" -H "Authorization: Bearer 8u242_OKlT-6gNAZ5oMWaInl3yZ1-wGvxdodDHZKWeU" https://10.13.137.149:8443/oapi
I0728 18:07:32.701905   13549 round_trippers.go:318] GET https://10.13.137.149:8443/oapi 200 OK in 0 milliseconds
I0728 18:07:32.701918   13549 round_trippers.go:324] Response Headers:
I0728 18:07:32.701922   13549 round_trippers.go:327]     Cache-Control: no-store
I0728 18:07:32.701927   13549 round_trippers.go:327]     Content-Type: application/json
I0728 18:07:32.701930   13549 round_trippers.go:327]     Date: Thu, 28 Jul 2016 22:07:32 GMT
I0728 18:07:32.701934   13549 round_trippers.go:327]     Content-Length: 93
I0728 18:07:32.701962   13549 request.go:901] Response Body: {"kind":"APIVersions","apiVersion":"v1","versions":["v1"],"serverAddressByClientCIDRs":null}
I0728 18:07:32.702122   13549 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: oc/v1.3.0 (linux/amd64) openshift/f2ac159" -H "Accept: application/json, */*" -H "Authorization: Bearer 8u242_OKlT-6gNAZ5oMWaInl3yZ1-wGvxdodDHZKWeU" https://10.13.137.149:8443/version/openshift
I0728 18:07:32.702927   13549 round_trippers.go:318] GET https://10.13.137.149:8443/version/openshift 200 OK in 0 milliseconds
I0728 18:07:32.702941   13549 round_trippers.go:324] Response Headers:
I0728 18:07:32.702947   13549 round_trippers.go:327]     Cache-Control: no-store
I0728 18:07:32.702955   13549 round_trippers.go:327]     Content-Type: application/json
I0728 18:07:32.702960   13549 round_trippers.go:327]     Date: Thu, 28 Jul 2016 22:07:32 GMT
I0728 18:07:32.702965   13549 round_trippers.go:327]     Content-Length: 142
I0728 18:07:32.702991   13549 request.go:901] Response Body: {
  "major": "1",
  "minor": "3+",
  "gitCommit": "efda5a8",
  "gitVersion": "v1.3.0-alpha.0+efda5a8",
  "buildDate": "2016-07-28T17:55:12Z"
}
I0728 18:07:32.703120   13549 round_trippers.go:299] curl -k -v -XGET  -H "User-Agent: oc/v1.3.0+57fb9ac (linux/amd64) kubernetes/57fb9ac" -H "Authorization: Bearer 8u242_OKlT-6gNAZ5oMWaInl3yZ1-wGvxdodDHZKWeU" -H "Accept: application/json, */*" https://10.13.137.149:8443/version
I0728 18:07:32.703931   13549 round_trippers.go:318] GET https://10.13.137.149:8443/version 200 OK in 0 milliseconds
I0728 18:07:32.703946   13549 round_trippers.go:324] Response Headers:
I0728 18:07:32.703952   13549 round_trippers.go:327]     Date: Thu, 28 Jul 2016 22:07:32 GMT
I0728 18:07:32.703957   13549 round_trippers.go:327]     Content-Length: 235
I0728 18:07:32.703961   13549 round_trippers.go:327]     Cache-Control: no-store
I0728 18:07:32.703965   13549 round_trippers.go:327]     Content-Type: application/json
I0728 18:07:32.703993   13549 request.go:901] Response Body: {
  "major": "1",
  "minor": "3",
  "gitVersion": "v1.3.0+57fb9ac",
  "gitCommit": "57fb9ac",
  "gitTreeState": "clean",
  "buildDate": "2016-07-28T17:55:12Z",
  "goVersion": "go1.6.3",
  "compiler": "gc",
  "platform": "linux/amd64"
}

Server https://10.13.137.149:8443
OpenShift v1.3.0-alpha.0+efda5a8
Kubernetes v1.3.0+57fb9ac
```

Comment (liggitt) [inline pkg/cmd/cli/cmd/version.go]: in the case of a not found / unauthorized / forbidden error, we should not continue on

if kapierrors.IsNotFound(err) || kapierrors.IsUnauthorized(err) || kapierrors.IsForbidden(err) {
  // handle unknown server version
  return
}
if err != nil {
  done <- err
  return
}
... parse json, output error or parsed version ...
```

File: pkg/cmd/cli/cmd/version.go [hunk 3]
```diff
@@ -145,7 +146,7 @@ func (o VersionOptions) RunVersion() error {
 		}
 		var kubeServerInfo kubeversion.Info
```
Comment (liggitt) [inline pkg/cmd/cli/cmd/version.go]: we should never get here with a non-nil err

File: pkg/cmd/cli/cmd/version.go (hunk 1 above)
Comment (juanvallejo) [inline pkg/cmd/cli/cmd/version.go]: > in the case of a not found / unauthorized / forbidden error, we should not continue on

Okay, should any kind of error message be returned?

**Comment by juanvallejo** [comment]
> we should never get here with a non-nil err, return early in the case of a unknown/unauthorized/forbidden error

Done! https://github.com/openshift/origin/pull/10093/commits/ae68abccd17b4804f32e474ab7fab48b6b23ee77

**Comment by juanvallejo** [comment]
Updated output in the case of a not found / unauthorized / forbidden error:
```
oc v1.3.0-alpha.0+10133fa-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth
```

Normal output (when remote call to server succeeds) remains the same:
```
oc v1.3.0-alpha.0+10133fa-dirty
kubernetes v1.3.0+57fb9ac
features: Basic-Auth

Server https://10.13.137.149:8443
OpenShift v1.3.0-alpha.0+10133fa-dirty
Kubernetes v1.3.0+57fb9ac
```

**Comment by liggitt** [comment]
make the server output follow the same format as `openshift version` (`openshift` and `kubernetes`)

**Comment by juanvallejo** [comment]
flake re[test]

**Comment by juanvallejo** [comment]
re[test]

**Comment by stevekuznetsov** [comment]
@juanvallejo even though it isn't (quite yet) enforced by the bot ... it's good practice to link the flakes that occur with the logs in your comment so someone can debug the flakes like I do in comments like this: https://github.com/openshift/origin/pull/10047#issuecomment-236569709

**Comment by juanvallejo** [comment]
@stevekuznetsov 
> it's good practice to link the flakes that occur with the logs in your comment

Thanks, will do in future

**Comment by stevekuznetsov** [comment]
re[test]

**Comment by juanvallejo** [comment]
@fabianofranz or @liggitt could you take a look please?

**Comment by fabianofranz** [comment]
LGTM [merge]
