### PR TITLE
Fix kube e2e intra-pod test

### LINKED ISSUE #6577: [E2E] [DIND] intra-pod communication tests should work OOTB.
When running the end to end kube networking `intra-pod` communications test, we get instant failure.    - - Ive created this cluster on DIND.
- I suspect a simlar error would happen in other environments.
- curious: if the exact same error happens in EC2 deployments?
- curious: should intra-pod communication tests work on openshift?

Be warned that @marun mentioned the lack of secrets service account mounting might  be b/c its not needed for an  openshift app, i.e. its a security "feature", rather than a bug :) ?  

In any case , I 'll reproduce what I saw here, because 
- the networking test is very powerful for debugging a "real" working kube cluster from a "running apiserver and controller manager".
- we want an end-to-end binary and verification of upstream e2es running in openshift clusters.
-  even If the only conclusion from this Issue is that networking.go intrapod tests are not valid in openshift in its current state, then that is ok. 

**The details**

The root cause from my digging into it a little, is  due to missing service accounts.  That is, 
```
bash-4.3# docker logs 34693d80cd13
2016/01/07 17:10:41 Unable to create client; error: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
```

We consider this an important test for kube basic functionality, so would be to know  if :
- there was simply a configuration switch we can turn on to get this working, i.e., service accounts might not be mounted in openshift by default?
- or, is there is a deeper reason for the missing certs ? If so maybe  we can work with upstream to make the networking test machinery more flexible, so that it can support  different intra-pod communication paradigms.

This is reproducible via DIND clusters, after applying #6541 , 
```
export OPENSHIFT_DIND_DEV_CLUSTER=true
export OPENSHIFT_MEMORY=4000
export OPENSHIFT_SDN_NODE_ON_MASTER=true
vagrant up
vagrant ssh
make e2e
_output/local/bin/linux/amd64/e2e.test --provider=local --kubeconfig=/tmp/openshift-dind-cluster/openshift/openshift.local.config/master/openshift-master.kubeconfig --ginkgo.focus="intra-pod"
```

Then we can enter  one of the nodes:

```
[vagrant@openshift-dind-host vagrant]$ docker exec -t -i ce4731479256 /bin/bash
```

And look in the container that tried to run:

```
bash-4.3# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
bash-4.3# docker ps -a
CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                      PORTS               NAMES
255eb79d15b9        gcr.io/google_containers/nettest:1.6   "/webserver -service="   6 minutes ago       Exited (1) 6 minutes ago                        k8s_webserver.a3289770_nettest-o0wv5_e2e-tests-nettest-y74lk_42e4fadd-b562-11e5-bc63-02420b9e4eaf_0e027af6
45f01227ad8f        openshift/origin-pod:v1.1              "/pod"                   6 minutes ago       Exited (0) 6 minutes ago                        k8s_POD.e127fd63_nettest-o0wv5_e2e-tests-nettest-y74lk_42e4fadd-b562-11e5-bc63-02420b9e4eaf_b8bac4e1
34693d80cd13        gcr.io/google_containers/nettest:1.6   "/webserver -service="   11 minutes ago      Exited (1) 11 minutes ago                       k8s_webserver.16269777_nettest-xx55t_e2e-tests-nettest-nnz1t_8e8a4264-b561-11e5-bc63-02420b9e4eaf_7ef45279
eae5dda0cca7        openshift/origin-pod:v1.1              "/pod"                   11 minutes ago      Exited (0) 11 minutes ago                       k8s_POD.e127fd63_nettest-xx55t_e2e-tests-nettest-nnz1t_8e8a4264-b561-11e5-bc63-02420b9e4eaf_033ecb73
```

And grabbing the logs, we get the output pasted at the top with the unmounted /var/run/... error.

### PR DESCRIPTION
**Pull request by marun**
~~This PR requires the mount propagation support added by docker 1.10.  It should not be merged until #7668 has merged.~~

~~Fixes #6577~~

Update: This PR has been retargeted to fixing the kube e2e test against non-dind clusters.

### CODE REVIEW

**Comment by marun** [comment]
cc: @openshift/networking

**Comment by marun** [comment]
cc: @liggitt The addition of the 'edit' role allows the test to run.  Review appreciated for 2904396; the rest of the commits are from #7668 and will be rebased out before merge.

File: test/extended/util/test.go [hunk 1]
```diff
@@ -139,6 +142,14 @@ func verifyTestSuitePreconditions() {
...
 		// behavior)
 		addE2EServiceAccountsToSCC(c, namespaces, "anyuid")
+
+		// The intra-pod test requires that the service account have
+		// permission to retrieve service endpoints.
+		osClient, _, err := configapi.GetOpenShiftClient(KubeConfigPath())
+		if err != nil {
+			FatalErr(err)
+		}
+		addRoleToE2EServiceAccounts(osClient, namespaces, bootstrappolicy.EditRoleName)
```
Comment (liggitt) [inline test/extended/util/test.go]: @smarterclayton and so it begins. I can't decide if I want to just make all the upstream service accounts cluster admins and stop worrying about it, or actually bound their permissions and at least know when the upstream e2e's are bumping the limits

Comment (smarterclayton) [inline test/extended/util/test.go]: Bound their permissions is my preference.  I thought endpoints were allowed to viewers since EAP needs it?  Is EAP setting up a custom role (I hope not, I hope not, I hope not...)

Comment (liggitt) [inline test/extended/util/test.go]: @marun if read access is all that is required, then let's start with the View role. For some reason, I thought I remembered you saying it needed the ability to create pods

Comment (marun) [inline test/extended/util/test.go]: Done

File: test/extended/util/test.go [hunk 2]
```diff
@@ -173,3 +184,26 @@ func addE2EServiceAccountsToSCC(c *kclient.Client, namespaces *kapi.NamespaceLis
...
+
+func addRoleToE2EServiceAccounts(c *client.Client, namespaces *kapi.NamespaceList, roleName string) {
+	err := kclient.RetryOnConflict(kclient.DefaultRetry, func() error {
+		for _, ns := range namespaces.Items {
+			if strings.HasPrefix(ns.Name, "e2e-") {
+				sa := fmt.Sprintf("system:serviceaccount:%s:default", ns.Name)
+				addRole := &policy.RoleModificationOptions{
+					RoleNamespace:       "",
+					RoleName:            roleName,
+					RoleBindingAccessor: policy.NewClusterRoleBindingAccessor(c),
```
Comment (liggitt) [inline test/extended/util/test.go]: not a cluster role binding, should be local to the particular namespace

Comment (marun) [inline test/extended/util/test.go]: Done.

**Comment by marun** [comment]
@liggitt I've manually verified that this works against a vm dev cluster.  I'd like to see it merged so that folks like @jayunit100 can use it in advance of it working against dind.  #7668 will fix #6577 instead.

**Comment by marun** [comment]
Not sure what is happening with travis, the errors don't appear to originate from this PR's changes.

**Comment by marun** [comment]
[test]

**Comment by marun** [comment]
@liggitt bump

**Comment by liggitt** [comment]
LGTM, [merge]
