### PR TITLE
Lazily initialize Osin client for token endpoint

### LINKED ISSUE #16078: GitHub oauth request/token flow is broken in 3.7.0-alpha.1
https://api.ci.openshift.org/oauth/token/request

Goes to GitHub, auth correctly, then comes back and reports:

```
Error getting token: The client is not authorized to request a token using this method. 

Request another token
```

We checked the `openshift-browser-client` secret, reset, and restarted.

```
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.281605   66362 wrap.go:42] GET /apis/oauth.openshift.io/v1/oauthclientauthorizations/smarterclayton:openshift-browser-client: (955.975µs) 404 [[openshift/v1.7.0+695f48a16f (linux/amd64) kubernet
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.283842   66362 wrap.go:42] GET /apis/oauth.openshift.io/v1/oauthclients/openshift-browser-client: (1.165796ms) 200 [[openshift/v1.7.0+695f48a16f (linux/amd64) kubernetes/d2e5420] 10.128.0.2:4407
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.286309   66362 wrap.go:42] POST /apis/oauth.openshift.io/v1/oauthauthorizetokens: (4.200209ms) 201 [[openshift/v1.7.0+695f48a16f (linux/amd64) kubernetes/d2e5420] 10.128.0.2:44070]
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.286786   66362 wrap.go:42] GET /oauth/authorize?client_id=openshift-browser-client&redirect_uri=https%3A%2F%2Fapi.ci.openshift.org%2Foauth%2Ftoken%2Fdisplay&response_type=code: (8.469858ms) 302
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.332308   66362 wrap.go:42] GET /apis/oauth.openshift.io/v1/oauthclients/openshift-browser-client: (1.263523ms) 200 [[openshift/v1.7.0+695f48a16f (linux/amd64) kubernetes/d2e5420] 10.128.0.2:4407
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.332597   66362 wrap.go:42] POST /oauth/token: (2.001652ms) 400 [[Go-http-client/2.0] 104.198.208.39:50210]
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: I0831 14:26:34.332980   66362 wrap.go:42] GET /oauth/token/display?code=SOME_REALLY_LONG_CODE&state=: (2.843432ms) 500
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: goroutine 4567248 [running]:
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc432257570, 0x1f4)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc432257570, 0x1f4)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
# Please edit the object below. Lines beginning with a '#' will be ignored,
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc423fc69c0, 0x1f4)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:185 +0xb5
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/pkg/auth/server/tokenrequest.(*endpointDetails).displayToken(0xc4216b09e0, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/auth/server/tokenrequest/endpoints.go:71 +0x484
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/pkg/auth/server/tokenrequest.(*endpointDetails).(github.com/openshift/origin/pkg/auth/server/tokenrequest.displayToken)-fm(0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/auth/server/tokenrequest/endpoints.go:41 +0x48
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: net/http.HandlerFunc.ServeHTTP(0xc421741980, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /usr/lib/golang/src/net/http/server.go:1942 +0x44
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/github.com/gorilla/context.ClearHandler.func1(0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/gorilla/context/context.go:141 +0x8b
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: net/http.HandlerFunc.ServeHTTP(0xc4216b0ae0, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /usr/lib/golang/src/net/http/server.go:1942 +0x44
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: net/http.(*ServeMux).ServeHTTP(0xc42170c4e0, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /usr/lib/golang/src/net/http/server.go:2238 +0x130
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithMaxInFlightLimit.func1(0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/maxinflight.go:96 +0x311
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: net/http.HandlerFunc.ServeHTTP(0xc42169e000, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /usr/lib/golang/src/net/http/server.go:1942 +0x44
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x189
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: net/http.HandlerFunc.ServeHTTP(0xc42165f5c0, 0x7f3bd907fee8, 0xc431a655f8, 0xc42568f600)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /usr/lib/golang/src/net/http/server.go:1942 +0x44
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4216b1500, 0xef3b860, 0xc431a655f8, 0xc42568f600, 0xc4211e57a0)
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: /tmp/openshift/build-rpm-release/tito/rpmbuild-origint1Stjl/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1c0
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "\n<style>\n\tbody     { font-family: sans-serif; font-size: 14px; margin: 2em 2%; background-color: #F9F9F9; }\n\th2       { font-size: 1.4em;}\n\th3       { font-size: 1em; margin: 1.5e
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "\n  "
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "Error getting token: The client is not authorized to request a token using this method."
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "\n"
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "\n\n<br><br>\n<a href=\""
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "request"
Aug 31 14:26:34 origin-ci-ig-m-11v4 atomic-openshift-master-api[66362]: logging error output: "\">Request another token</a>\n"
```

### PR DESCRIPTION
**Pull request by enj**
This change makes it so that the Osin OAuth client for the token request endpoint is lazily initialized when the endpoint is called.  Initializing in this case refers to fetching the private OpenShift browser OAuth client from the API to get its secret (it is required to build the Osin client).  This behavior was lost when we moved away from using the OAuth registries.

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #16078

@openshift/sig-security

/assign @deads2k @liggitt

I plan to open a separate PR with something that tests this endpoint to make sure we do not regress again.  Tracked in #16146

### CODE REVIEW

**Comment by enj** [comment]
Simple test started before the master is up:

```
$ while true; do curl -k --connect-timeout 1 https://10.13.129.10:8443/oauth/token/request; done
...
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
curl: (7) Failed to connect to 10.13.129.10 port 8443: Connection refused
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
OAuth token endpoint is not ready
<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.

<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.

<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.

<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.

<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.

<a href="https://10.13.129.10:8443/oauth/authorize?client_id=openshift-browser-client&amp;redirect_uri=https%3A%2F%2F10.13.129.10%3A8443%2Foauth%2Ftoken%2Fdisplay&amp;response_type=code">Found</a>.
...
```

File: pkg/auth/server/tokenrequest/endpoints.go [hunk 1]
```diff
@@ -21,31 +24,56 @@ const (
...
 func (endpoints *endpointDetails) Install(mux login.Mux, paths ...string) {
 	for _, prefix := range paths {
-		mux.HandleFunc(path.Join(prefix, RequestTokenEndpoint), endpoints.requestToken)
-		mux.HandleFunc(path.Join(prefix, DisplayTokenEndpoint), endpoints.displayToken)
+		mux.HandleFunc(path.Join(prefix, RequestTokenEndpoint), endpoints.readyHandler(endpoints.requestToken))
+		mux.HandleFunc(path.Join(prefix, DisplayTokenEndpoint), endpoints.readyHandler(endpoints.displayToken))
 		mux.HandleFunc(path.Join(prefix, ImplicitTokenEndpoint), endpoints.implicitToken)
 	}
+
+	go wait.Until(func() {
```
Comment (deads2k) [inline pkg/auth/server/tokenrequest/endpoints.go]: If you do it like this, you need to have a stop channel.

Why not simply make a getter for thing which returns osinOauthClient or returns an error.  I'm fine with failing requests to this endpoint until this bit is ready.

**Comment by enj** [comment]
@deads2k PTAL

**Comment by enj** [comment]
This looks suspicious...

```
I0901 20:51:10.005162   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (9.376475ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.005407   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:build-strategy-docker-binding
I0901 20:51:10.006828   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:build-strategy-source-binding: (1.164077ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.019904   31318 wrap.go:42] GET /healthz: (374.445µs) 500
goroutine 13948 [running]:
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc42299a930, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:207 +0xdd
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc42299a930, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:186 +0x35
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc426c9b400, 0x1f4)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:185 +0xb5
net/http.Error(0x7f8e0dc41208, 0xc422efaf90, 0xc427a27680, 0x408, 0x1f4)
	/usr/lib/golang/src/net/http/server.go:1954 +0xda
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:110 +0x3cb
net/http.HandlerFunc.ServeHTTP(0xc421b32c60, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc4286b4300, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x567
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc422391f10, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x72
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x5694460, 0xf, 0xc4252163f0, 0xc422391f10, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/handler.go:161 +0x301
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server.(*director).ServeHTTP(0xc4224f5640, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	<autogenerated>:72 +0x86
github.com/openshift/origin/pkg/cmd/server/origin.namespacingFilter.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/origin/handlers.go:96 +0xd2
net/http.HandlerFunc.ServeHTTP(0xc423a56cc0, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/pkg/cmd/server/handlers.AuthorizationFilter.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authorization.go:64 +0x113
net/http.HandlerFunc.ServeHTTP(0xc423727f80, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/pkg/cmd/server/handlers.ImpersonationFilter.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/impersonation.go:30 +0x312a
net/http.HandlerFunc.ServeHTTP(0xc424071a90, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/pkg/cmd/server/handlers.AuthenticationHandlerFilter.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/pkg/cmd/server/handlers/authentication.go:32 +0x299
net/http.HandlerFunc.ServeHTTP(0xc4233b40c0, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.WithCORS.func1(0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/cors.go:75 +0x189
net/http.HandlerFunc.ServeHTTP(0xc422ffe480, 0x7f8e0dc41208, 0xc422efaf90, 0xc4280dcc00)
	/usr/lib/golang/src/net/http/server.go:1942 +0x44
github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc4224f5900, 0xcc4ecc0, 0xc422efaf90, 0xc4280dcc00, 0xc4286187e0)
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:91 +0x8d
created by github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:93 +0x1c0

logging error output: "[+]ping ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[+]poststarthook/quota.openshift.io-clusterquotamapping ok\n[+]poststarthook/project.openshift.io-projectcache ok\n[+]poststarthook/project.openshift.io-projectauthorizationcache ok\n[+]poststarthook/security.openshift.io-bootstrapscc ok\n[+]poststarthook/authorization.openshift.io-ensureSARolesDefault ok\n[+]poststarthook/authorization.openshift.io-ensureopenshift-infra ok\n[+]poststarthook/bootstrap-controller ok\n[+]poststarthook/ca-registration ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[+]autoregister-completion ok\n[+]poststarthook/template.openshift.io-sharednamespace ok\n[-]poststarthook/authorization.openshift.io-bootstrapclusterroles failed: reason withheld\nhealthz check failed\n"
 [[Go-http-client/2.0] 127.0.0.1:37216]
I0901 20:51:10.048463   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (41.140104ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.048718   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:build-strategy-source-binding
I0901 20:51:10.050220   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:build-strategy-jenkinspipeline-binding: (1.20649ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.057908   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.195624ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.058137   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:build-strategy-jenkinspipeline-binding
I0901 20:51:10.063279   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:node-bootstrapper: (4.905505ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.072490   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (8.739094ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.072714   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:node-bootstrapper
I0901 20:51:10.074097   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:attachdetach-controller: (1.111927ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.094337   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (19.786197ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.094565   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:attachdetach-controller
I0901 20:51:10.105647   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:cronjob-controller: (10.830104ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.118059   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (2.563913ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.118301   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:cronjob-controller
I0901 20:51:10.119696   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:daemon-set-controller: (1.121384ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.122462   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.925863ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.122906   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:daemon-set-controller
I0901 20:51:10.124319   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:deployment-controller: (1.186902ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.130489   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (5.712321ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.130714   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:deployment-controller
I0901 20:51:10.143194   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:disruption-controller: (12.213674ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.151616   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.949896ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.151865   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:disruption-controller
I0901 20:51:10.169349   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:endpoint-controller: (17.226158ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.182946   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (13.03035ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.183407   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:endpoint-controller
I0901 20:51:10.184761   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:generic-garbage-collector: (1.149815ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.197537   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.293048ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.197775   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:generic-garbage-collector
I0901 20:51:10.199257   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:horizontal-pod-autoscaler: (1.209754ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.226741   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (27.018863ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.227019   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:horizontal-pod-autoscaler
I0901 20:51:10.228470   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:job-controller: (1.187809ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.230914   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.955617ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.231134   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:job-controller
I0901 20:51:10.232560   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:namespace-controller: (1.215109ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.235515   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (2.46663ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.235745   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:namespace-controller
I0901 20:51:10.237106   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:node-controller: (1.101664ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.241372   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (3.815451ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.241781   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:node-controller
I0901 20:51:10.268039   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:persistent-volume-binder: (26.029842ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.273446   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (4.892202ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.273672   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:persistent-volume-binder
I0901 20:51:10.275046   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:pod-garbage-collector: (1.115178ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.277175   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.667203ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.278454   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:pod-garbage-collector
I0901 20:51:10.289291   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:replicaset-controller: (10.605488ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.295525   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (5.771232ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.295746   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:replicaset-controller
I0901 20:51:10.307018   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:replication-controller: (11.006436ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.329353   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (21.835537ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.329582   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:replication-controller
I0901 20:51:10.330981   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:resourcequota-controller: (1.162719ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.339763   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (8.312261ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.340021   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:resourcequota-controller
I0901 20:51:10.347318   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:route-controller: (7.051652ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.352497   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (4.709449ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.352763   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:route-controller
I0901 20:51:10.366585   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:service-account-controller: (13.569727ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.371581   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (4.455728ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.371821   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:service-account-controller
I0901 20:51:10.373112   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:service-controller: (1.097453ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.395722   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (22.161666ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.395974   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:service-controller
I0901 20:51:10.397391   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:statefulset-controller: (1.137497ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.405748   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.894542ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.405981   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:statefulset-controller
I0901 20:51:10.410001   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:ttl-controller: (3.776309ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.422600   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.086346ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.422852   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:ttl-controller
I0901 20:51:10.424361   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:controller:certificate-controller: (1.243135ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.436148   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (11.31811ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.436392   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:certificate-controller
I0901 20:51:10.437722   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:build-controller: (1.115996ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.445936   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.737071ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.446185   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:build-controller
I0901 20:51:10.471510   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:build-config-change-controller: (25.074102ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.494590   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (22.490544ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.497957   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:build-config-change-controller
I0901 20:51:10.499456   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:deployer-controller: (1.252627ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.534794   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (34.822724ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.535081   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:deployer-controller
I0901 20:51:10.536614   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:deploymentconfig-controller: (1.245884ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.549494   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.381445ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.549721   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:deploymentconfig-controller
I0901 20:51:10.551192   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:deployment-trigger-controller: (1.201062ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.560473   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (8.807703ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.560700   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:deployment-trigger-controller
I0901 20:51:10.569757   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:template-instance-controller: (8.797198ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.582459   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.206039ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.582692   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:template-instance-controller
I0901 20:51:10.594287   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/admin: (11.310063ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.600466   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (5.680627ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.600702   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/admin
I0901 20:51:10.602777   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:origin-namespace-controller: (1.814674ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.615484   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.230682ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.615710   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:origin-namespace-controller
I0901 20:51:10.617193   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:serviceaccount-controller: (1.217794ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.628658   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (10.994526ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.628910   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:serviceaccount-controller
I0901 20:51:10.630383   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:serviceaccount-pull-secrets-controller: (1.226585ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.643501   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.63643ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.643740   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:serviceaccount-pull-secrets-controller
I0901 20:51:10.646068   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:image-trigger-controller: (2.044958ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.664535   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.280793ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.664765   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:image-trigger-controller
I0901 20:51:10.669774   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:service-serving-cert-controller: (4.738574ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.693192   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (22.912073ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.693422   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:service-serving-cert-controller
I0901 20:51:10.694817   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:image-import-controller: (1.135166ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.703297   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (8.006955ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.707941   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:image-import-controller
I0901 20:51:10.709453   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:sdn-controller: (1.283834ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.717511   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (7.553269ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.717737   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:sdn-controller
I0901 20:51:10.731499   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:cluster-quota-reconciliation-controller: (13.48792ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.744549   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.548094ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.744784   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:cluster-quota-reconciliation-controller
I0901 20:51:10.746330   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:unidling-controller: (1.221283ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.760031   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (13.234006ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.760269   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:unidling-controller
I0901 20:51:10.763359   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:service-ingress-ip-controller: (2.86069ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.765727   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.918806ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.765962   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:service-ingress-ip-controller
I0901 20:51:10.767430   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:pv-recycler-controller: (1.216753ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.769746   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.825427ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.769988   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:pv-recycler-controller
I0901 20:51:10.782097   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:resourcequota-controller: (1.158726ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.793052   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (10.503468ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.793304   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:resourcequota-controller
I0901 20:51:10.794617   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:horizontal-pod-autoscaler: (1.113525ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.796954   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.868729ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.797165   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:horizontal-pod-autoscaler
I0901 20:51:10.799135   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:openshift:controller:template-service-broker: (1.715461ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.801482   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.870434ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.801689   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:openshift:controller:template-service-broker
I0901 20:51:10.803233   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/cluster-admin: (1.269641ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.816495   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.779134ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.816716   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/cluster-admin
I0901 20:51:10.818527   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:discovery: (1.540181ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.831600   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.581128ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.831856   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:discovery
I0901 20:51:10.833358   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:basic-user: (1.247561ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.846532   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (12.719377ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.846756   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:basic-user
I0901 20:51:10.848288   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:node-proxier: (1.253576ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.850582   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.814171ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.850815   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:node-proxier
I0901 20:51:10.852265   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:kube-controller-manager: (1.203269ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.854520   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.769088ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.854762   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:kube-controller-manager
I0901 20:51:10.855971   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:kube-dns: (1.005931ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.858137   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.721798ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.858382   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:kube-dns
I0901 20:51:10.859621   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:kube-scheduler: (1.016294ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.861770   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.698408ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.862015   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:kube-scheduler
I0901 20:51:10.863211   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/system:node: (1.005505ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.865326   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: (1.726171ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.865547   31318 storage_rbac.go:220] created clusterrolebinding.rbac.authorization.k8s.io/system:node
I0901 20:51:10.867121   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/namespaces/openshift/roles/shared-resource-viewer: (1.332836ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.869986   31318 wrap.go:42] POST /api/v1/namespaces: (2.404316ms) 409 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.872222   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/namespaces/openshift/roles: (1.752331ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.872461   31318 storage_rbac.go:251] created role.rbac.authorization.k8s.io/shared-resource-viewer in openshift 
I0901 20:51:10.873974   31318 wrap.go:42] GET /apis/rbac.authorization.k8s.io/v1beta1/namespaces/openshift/rolebindings/shared-resource-viewers: (1.259472ms) 404 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.876633   31318 wrap.go:42] POST /api/v1/namespaces: (2.196289ms) 409 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.879076   31318 wrap.go:42] POST /apis/rbac.authorization.k8s.io/v1beta1/namespaces/openshift/rolebindings: (1.945106ms) 201 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:10.879310   31318 storage_rbac.go:281] created rolebinding.rbac.authorization.k8s.io/shared-resource-viewers in openshift
I0901 20:51:11.024573   31318 wrap.go:42] GET /healthz: (240.559µs) 200 [[Go-http-client/2.0] 127.0.0.1:37222]
I0901 20:51:11.038445   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:11.038638   31318 wrap.go:42] GET /oauth/token/request: (290.535µs) 403 [[Go-http-client/2.0] 127.0.0.1:37224]
I0901 20:51:12.029779   31318 wrap.go:42] GET /healthz: (263.356µs) 200 [[Go-http-client/2.0] 127.0.0.1:37248]
I0901 20:51:12.038078   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:12.038258   31318 wrap.go:42] GET /oauth/token/request: (292.242µs) 403 [[Go-http-client/2.0] 127.0.0.1:37250]
I0901 20:51:13.004271   31318 wrap.go:42] GET /healthz: (196.101µs) 200 [[Go-http-client/2.0] 127.0.0.1:37278]
I0901 20:51:13.009779   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:13.009956   31318 wrap.go:42] GET /oauth/token/request: (307.67µs) 403 [[Go-http-client/2.0] 127.0.0.1:37280]
I0901 20:51:14.006950   31318 wrap.go:42] GET /healthz: (227.151µs) 200 [[Go-http-client/2.0] 127.0.0.1:37366]
I0901 20:51:14.015017   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:14.015203   31318 wrap.go:42] GET /oauth/token/request: (329.839µs) 403 [[Go-http-client/2.0] 127.0.0.1:37368]
I0901 20:51:15.007613   31318 wrap.go:42] GET /healthz: (247.524µs) 200 [[Go-http-client/2.0] 127.0.0.1:37568]
I0901 20:51:15.018409   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:15.018590   31318 wrap.go:42] GET /oauth/token/request: (319.052µs) 403 [[Go-http-client/2.0] 127.0.0.1:37570]
I0901 20:51:16.004393   31318 wrap.go:42] GET /healthz: (205.568µs) 200 [[Go-http-client/2.0] 127.0.0.1:37748]
I0901 20:51:16.009555   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:16.009703   31318 wrap.go:42] GET /oauth/token/request: (247.615µs) 403 [[Go-http-client/2.0] 127.0.0.1:37750]
I0901 20:51:17.004318   31318 wrap.go:42] GET /healthz: (170.006µs) 200 [[Go-http-client/2.0] 127.0.0.1:37764]
I0901 20:51:17.009434   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:17.009587   31318 wrap.go:42] GET /oauth/token/request: (253.51µs) 403 [[Go-http-client/2.0] 127.0.0.1:37766]
I0901 20:51:18.007531   31318 wrap.go:42] GET /healthz: (237.452µs) 200 [[Go-http-client/2.0] 127.0.0.1:37786]
I0901 20:51:18.014521   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:18.014698   31318 wrap.go:42] GET /oauth/token/request: (296.897µs) 403 [[Go-http-client/2.0] 127.0.0.1:37788]
I0901 20:51:18.042566   31318 wrap.go:42] GET /api/v1/namespaces/default: (1.736947ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:18.044200   31318 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (1.199741ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:19.013340   31318 wrap.go:42] GET /healthz: (221.453µs) 200 [[Go-http-client/2.0] 127.0.0.1:37794]
I0901 20:51:19.023425   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:19.023602   31318 wrap.go:42] GET /oauth/token/request: (329.931µs) 403 [[Go-http-client/2.0] 127.0.0.1:37796]
I0901 20:51:20.008197   31318 wrap.go:42] GET /healthz: (214.699µs) 200 [[Go-http-client/2.0] 127.0.0.1:37802]
I0901 20:51:20.013640   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:20.013788   31318 wrap.go:42] GET /oauth/token/request: (234.641µs) 403 [[Go-http-client/2.0] 127.0.0.1:37804]
I0901 20:51:21.004333   31318 wrap.go:42] GET /healthz: (178.02µs) 200 [[Go-http-client/2.0] 127.0.0.1:37810]
I0901 20:51:21.009540   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:21.009684   31318 wrap.go:42] GET /oauth/token/request: (230.974µs) 403 [[Go-http-client/2.0] 127.0.0.1:37812]
I0901 20:51:22.004169   31318 wrap.go:42] GET /healthz: (206.852µs) 200 [[Go-http-client/2.0] 127.0.0.1:37818]
I0901 20:51:22.009535   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:22.009684   31318 wrap.go:42] GET /oauth/token/request: (235.065µs) 403 [[Go-http-client/2.0] 127.0.0.1:37820]
I0901 20:51:23.006621   31318 wrap.go:42] GET /healthz: (167.89µs) 200 [[Go-http-client/2.0] 127.0.0.1:37828]
I0901 20:51:23.011594   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:23.011742   31318 wrap.go:42] GET /oauth/token/request: (243.106µs) 403 [[Go-http-client/2.0] 127.0.0.1:37830]
I0901 20:51:24.023738   31318 wrap.go:42] GET /healthz: (237.586µs) 200 [[Go-http-client/2.0] 127.0.0.1:37836]
I0901 20:51:24.031866   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:24.032045   31318 wrap.go:42] GET /oauth/token/request: (291.779µs) 403 [[Go-http-client/2.0] 127.0.0.1:37838]
I0901 20:51:25.008820   31318 wrap.go:42] GET /healthz: (178.887µs) 200 [[Go-http-client/2.0] 127.0.0.1:37844]
I0901 20:51:25.017929   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:25.018094   31318 wrap.go:42] GET /oauth/token/request: (307.061µs) 403 [[Go-http-client/2.0] 127.0.0.1:37846]
I0901 20:51:26.004532   31318 wrap.go:42] GET /healthz: (246.875µs) 200 [[Go-http-client/2.0] 127.0.0.1:37876]
I0901 20:51:26.009883   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:26.010068   31318 wrap.go:42] GET /oauth/token/request: (323.053µs) 403 [[Go-http-client/2.0] 127.0.0.1:37878]
I0901 20:51:27.026743   31318 wrap.go:42] GET /healthz: (252.982µs) 200 [[Go-http-client/2.0] 127.0.0.1:37924]
I0901 20:51:27.034880   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:27.035062   31318 wrap.go:42] GET /oauth/token/request: (289.47µs) 403 [[Go-http-client/2.0] 127.0.0.1:37926]
I0901 20:51:28.011554   31318 wrap.go:42] GET /healthz: (205.941µs) 200 [[Go-http-client/2.0] 127.0.0.1:38050]
I0901 20:51:28.019521   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:28.019702   31318 wrap.go:42] GET /oauth/token/request: (294.009µs) 403 [[Go-http-client/2.0] 127.0.0.1:38052]
I0901 20:51:28.058467   31318 wrap.go:42] GET /api/v1/namespaces/default: (1.518398ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:28.060185   31318 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (1.278602ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:29.004109   31318 wrap.go:42] GET /healthz: (202.969µs) 200 [[Go-http-client/2.0] 127.0.0.1:38160]
I0901 20:51:29.009397   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:29.009547   31318 wrap.go:42] GET /oauth/token/request: (245.844µs) 403 [[Go-http-client/2.0] 127.0.0.1:38162]
I0901 20:51:30.020128   31318 wrap.go:42] GET /healthz: (227.349µs) 200 [[Go-http-client/2.0] 127.0.0.1:38292]
I0901 20:51:30.028105   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:30.028284   31318 wrap.go:42] GET /oauth/token/request: (303.61µs) 403 [[Go-http-client/2.0] 127.0.0.1:38296]
I0901 20:51:31.005861   31318 wrap.go:42] GET /healthz: (274.864µs) 200 [[Go-http-client/2.0] 127.0.0.1:38386]
I0901 20:51:31.013882   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:31.014055   31318 wrap.go:42] GET /oauth/token/request: (296.254µs) 403 [[Go-http-client/2.0] 127.0.0.1:38388]
I0901 20:51:32.012061   31318 wrap.go:42] GET /healthz: (184.082µs) 200 [[Go-http-client/2.0] 127.0.0.1:38402]
I0901 20:51:32.020292   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:32.020486   31318 wrap.go:42] GET /oauth/token/request: (346.085µs) 403 [[Go-http-client/2.0] 127.0.0.1:38404]
I0901 20:51:33.005697   31318 wrap.go:42] GET /healthz: (226.479µs) 200 [[Go-http-client/2.0] 127.0.0.1:38420]
I0901 20:51:33.011231   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:33.011448   31318 wrap.go:42] GET /oauth/token/request: (349.214µs) 403 [[Go-http-client/2.0] 127.0.0.1:38422]
I0901 20:51:34.008156   31318 wrap.go:42] GET /healthz: (187.239µs) 200 [[Go-http-client/2.0] 127.0.0.1:38428]
I0901 20:51:34.016107   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:34.016272   31318 wrap.go:42] GET /oauth/token/request: (299.326µs) 403 [[Go-http-client/2.0] 127.0.0.1:38430]
I0901 20:51:35.005326   31318 wrap.go:42] GET /healthz: (241.828µs) 200 [[Go-http-client/2.0] 127.0.0.1:38436]
I0901 20:51:35.010844   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:35.010987   31318 wrap.go:42] GET /oauth/token/request: (269.739µs) 403 [[Go-http-client/2.0] 127.0.0.1:38438]
I0901 20:51:36.005589   31318 wrap.go:42] GET /healthz: (216.617µs) 200 [[Go-http-client/2.0] 127.0.0.1:38444]
I0901 20:51:36.011333   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:36.011477   31318 wrap.go:42] GET /oauth/token/request: (272.118µs) 403 [[Go-http-client/2.0] 127.0.0.1:38446]
I0901 20:51:37.004892   31318 wrap.go:42] GET /healthz: (212.842µs) 200 [[Go-http-client/2.0] 127.0.0.1:38452]
I0901 20:51:37.010964   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:37.011156   31318 wrap.go:42] GET /oauth/token/request: (326.086µs) 403 [[Go-http-client/2.0] 127.0.0.1:38454]
I0901 20:51:38.005335   31318 wrap.go:42] GET /healthz: (247.226µs) 200 [[Go-http-client/2.0] 127.0.0.1:38460]
I0901 20:51:38.010724   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:38.010892   31318 wrap.go:42] GET /oauth/token/request: (257.067µs) 403 [[Go-http-client/2.0] 127.0.0.1:38462]
I0901 20:51:38.116256   31318 wrap.go:42] GET /api/v1/namespaces/default: (1.271763ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:38.117859   31318 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (1.211253ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:39.005918   31318 wrap.go:42] GET /healthz: (217.34µs) 200 [[Go-http-client/2.0] 127.0.0.1:38476]
I0901 20:51:39.013737   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:39.013907   31318 wrap.go:42] GET /oauth/token/request: (251.218µs) 403 [[Go-http-client/2.0] 127.0.0.1:38478]
I0901 20:51:40.011317   31318 wrap.go:42] GET /healthz: (221.107µs) 200 [[Go-http-client/2.0] 127.0.0.1:38480]
I0901 20:51:40.030348   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:40.030523   31318 wrap.go:42] GET /oauth/token/request: (290.451µs) 403 [[Go-http-client/2.0] 127.0.0.1:38482]
I0901 20:51:41.007191   31318 wrap.go:42] GET /healthz: (227.469µs) 200 [[Go-http-client/2.0] 127.0.0.1:38504]
I0901 20:51:41.014848   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:41.015040   31318 wrap.go:42] GET /oauth/token/request: (360.728µs) 403 [[Go-http-client/2.0] 127.0.0.1:38506]
I0901 20:51:42.009962   31318 wrap.go:42] GET /healthz: (310.323µs) 200 [[Go-http-client/2.0] 127.0.0.1:38530]
I0901 20:51:42.022092   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:42.022283   31318 wrap.go:42] GET /oauth/token/request: (323.986µs) 403 [[Go-http-client/2.0] 127.0.0.1:38532]
I0901 20:51:43.012870   31318 wrap.go:42] GET /healthz: (240.341µs) 200 [[Go-http-client/2.0] 127.0.0.1:38620]
I0901 20:51:43.021041   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:43.021227   31318 wrap.go:42] GET /oauth/token/request: (305.547µs) 403 [[Go-http-client/2.0] 127.0.0.1:38622]
I0901 20:51:44.004508   31318 wrap.go:42] GET /healthz: (242.614µs) 200 [[Go-http-client/2.0] 127.0.0.1:38756]
I0901 20:51:44.011322   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:44.011498   31318 wrap.go:42] GET /oauth/token/request: (338.256µs) 403 [[Go-http-client/2.0] 127.0.0.1:38758]
I0901 20:51:45.007253   31318 wrap.go:42] GET /healthz: (232.394µs) 200 [[Go-http-client/2.0] 127.0.0.1:38802]
I0901 20:51:45.013206   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:45.013413   31318 wrap.go:42] GET /oauth/token/request: (310.71µs) 403 [[Go-http-client/2.0] 127.0.0.1:38804]
I0901 20:51:46.006898   31318 wrap.go:42] GET /healthz: (265.453µs) 200 [[Go-http-client/2.0] 127.0.0.1:38990]
I0901 20:51:46.014659   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:46.014843   31318 wrap.go:42] GET /oauth/token/request: (285.483µs) 403 [[Go-http-client/2.0] 127.0.0.1:38996]
I0901 20:51:47.008979   31318 wrap.go:42] GET /healthz: (214.327µs) 200 [[Go-http-client/2.0] 127.0.0.1:39008]
I0901 20:51:47.017145   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:47.017328   31318 wrap.go:42] GET /oauth/token/request: (336.876µs) 403 [[Go-http-client/2.0] 127.0.0.1:39010]
I0901 20:51:48.018360   31318 wrap.go:42] GET /healthz: (217.57µs) 200 [[Go-http-client/2.0] 127.0.0.1:39018]
I0901 20:51:48.040520   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:48.040709   31318 wrap.go:42] GET /oauth/token/request: (314.077µs) 403 [[Go-http-client/2.0] 127.0.0.1:39020]
I0901 20:51:48.132431   31318 wrap.go:42] GET /api/v1/namespaces/default: (1.48741ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:48.134166   31318 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (1.303715ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:49.022766   31318 wrap.go:42] GET /healthz: (232.624µs) 200 [[Go-http-client/2.0] 127.0.0.1:39028]
I0901 20:51:49.030671   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:49.030867   31318 wrap.go:42] GET /oauth/token/request: (315.854µs) 403 [[Go-http-client/2.0] 127.0.0.1:39030]
I0901 20:51:50.007849   31318 wrap.go:42] GET /healthz: (214.122µs) 200 [[Go-http-client/2.0] 127.0.0.1:39044]
I0901 20:51:50.047675   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:50.047893   31318 wrap.go:42] GET /oauth/token/request: (360.334µs) 403 [[Go-http-client/2.0] 127.0.0.1:39046]
I0901 20:51:51.006937   31318 wrap.go:42] GET /healthz: (205.751µs) 200 [[Go-http-client/2.0] 127.0.0.1:39056]
I0901 20:51:51.042493   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:51.042686   31318 wrap.go:42] GET /oauth/token/request: (355.944µs) 403 [[Go-http-client/2.0] 127.0.0.1:39058]
I0901 20:51:52.007336   31318 wrap.go:42] GET /healthz: (234.463µs) 200 [[Go-http-client/2.0] 127.0.0.1:39084]
I0901 20:51:52.015567   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:52.015767   31318 wrap.go:42] GET /oauth/token/request: (286.65µs) 403 [[Go-http-client/2.0] 127.0.0.1:39086]
I0901 20:51:53.025902   31318 wrap.go:42] GET /healthz: (244.165µs) 200 [[Go-http-client/2.0] 127.0.0.1:39270]
I0901 20:51:53.034001   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:53.034181   31318 wrap.go:42] GET /oauth/token/request: (275.548µs) 403 [[Go-http-client/2.0] 127.0.0.1:39272]
I0901 20:51:54.007519   31318 wrap.go:42] GET /healthz: (188.88µs) 200 [[Go-http-client/2.0] 127.0.0.1:39442]
I0901 20:51:54.015216   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:54.015398   31318 wrap.go:42] GET /oauth/token/request: (279.297µs) 403 [[Go-http-client/2.0] 127.0.0.1:39444]
I0901 20:51:55.004488   31318 wrap.go:42] GET /healthz: (274.206µs) 200 [[Go-http-client/2.0] 127.0.0.1:39460]
I0901 20:51:55.011266   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:55.011430   31318 wrap.go:42] GET /oauth/token/request: (270.75µs) 403 [[Go-http-client/2.0] 127.0.0.1:39462]
I0901 20:51:56.005365   31318 wrap.go:42] GET /healthz: (157.579µs) 200 [[Go-http-client/2.0] 127.0.0.1:39476]
I0901 20:51:56.010628   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:56.010789   31318 wrap.go:42] GET /oauth/token/request: (253.032µs) 403 [[Go-http-client/2.0] 127.0.0.1:39478]
I0901 20:51:57.005525   31318 wrap.go:42] GET /healthz: (238.127µs) 200 [[Go-http-client/2.0] 127.0.0.1:39490]
I0901 20:51:57.011889   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:57.012053   31318 wrap.go:42] GET /oauth/token/request: (319.68µs) 403 [[Go-http-client/2.0] 127.0.0.1:39492]
I0901 20:51:58.004507   31318 wrap.go:42] GET /healthz: (209.249µs) 200 [[Go-http-client/2.0] 127.0.0.1:39500]
I0901 20:51:58.011308   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:58.011461   31318 wrap.go:42] GET /oauth/token/request: (221.761µs) 403 [[Go-http-client/2.0] 127.0.0.1:39502]
I0901 20:51:58.155099   31318 wrap.go:42] GET /api/v1/namespaces/default: (2.165462ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:58.156737   31318 wrap.go:42] GET /api/v1/namespaces/default/services/kubernetes: (1.285998ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:51:59.007312   31318 wrap.go:42] GET /healthz: (260.491µs) 200 [[Go-http-client/2.0] 127.0.0.1:39520]
I0901 20:51:59.015730   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:51:59.015949   31318 wrap.go:42] GET /oauth/token/request: (323.806µs) 403 [[Go-http-client/2.0] 127.0.0.1:39522]
I0901 20:52:00.011663   31318 wrap.go:42] GET /healthz: (225.556µs) 200 [[Go-http-client/2.0] 127.0.0.1:39528]
I0901 20:52:00.043188   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:00.043381   31318 wrap.go:42] GET /oauth/token/request: (365.253µs) 403 [[Go-http-client/2.0] 127.0.0.1:39530]
I0901 20:52:01.016822   31318 wrap.go:42] GET /healthz: (244.071µs) 200 [[Go-http-client/2.0] 127.0.0.1:39536]
I0901 20:52:01.027816   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:01.027992   31318 wrap.go:42] GET /oauth/token/request: (292.401µs) 403 [[Go-http-client/2.0] 127.0.0.1:39538]
I0901 20:52:02.007482   31318 wrap.go:42] GET /healthz: (266.685µs) 200 [[Go-http-client/2.0] 127.0.0.1:39546]
I0901 20:52:02.015756   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:02.015967   31318 wrap.go:42] GET /oauth/token/request: (332.909µs) 403 [[Go-http-client/2.0] 127.0.0.1:39548]
I0901 20:52:03.017281   31318 wrap.go:42] GET /healthz: (217.527µs) 200 [[Go-http-client/2.0] 127.0.0.1:39558]
I0901 20:52:03.025537   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:03.025724   31318 wrap.go:42] GET /oauth/token/request: (298.663µs) 403 [[Go-http-client/2.0] 127.0.0.1:39560]
I0901 20:52:04.013350   31318 wrap.go:42] GET /healthz: (197.355µs) 200 [[Go-http-client/2.0] 127.0.0.1:39594]
I0901 20:52:04.021343   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:04.021532   31318 wrap.go:42] GET /oauth/token/request: (336.643µs) 403 [[Go-http-client/2.0] 127.0.0.1:39600]
I0901 20:52:05.006430   31318 wrap.go:42] GET /healthz: (241.729µs) 200 [[Go-http-client/2.0] 127.0.0.1:39780]
I0901 20:52:05.014085   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:05.014269   31318 wrap.go:42] GET /oauth/token/request: (307.516µs) 403 [[Go-http-client/2.0] 127.0.0.1:39782]
I0901 20:52:06.007038   31318 wrap.go:42] GET /healthz: (270.896µs) 200 [[Go-http-client/2.0] 127.0.0.1:39830]
I0901 20:52:06.016023   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:06.016198   31318 wrap.go:42] GET /oauth/token/request: (301.628µs) 403 [[Go-http-client/2.0] 127.0.0.1:39832]
I0901 20:52:07.004158   31318 wrap.go:42] GET /healthz: (189.423µs) 200 [[Go-http-client/2.0] 127.0.0.1:39864]
I0901 20:52:07.009601   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:07.009760   31318 wrap.go:42] GET /oauth/token/request: (269.06µs) 403 [[Go-http-client/2.0] 127.0.0.1:39866]
I0901 20:52:08.004122   31318 wrap.go:42] GET /healthz: (211.736µs) 200 [[Go-http-client/2.0] 127.0.0.1:40052]
I0901 20:52:08.009474   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:08.009661   31318 wrap.go:42] GET /oauth/token/request: (266.422µs) 403 [[Go-http-client/2.0] 127.0.0.1:40054]
I0901 20:52:08.015944   31318 wrap.go:42] GET /healthz: (133.084µs) 200 [[Go-http-client/2.0] 127.0.0.1:40056]
I0901 20:52:08.022885   31318 rbac.go:116] RBAC DENY: user "system:anonymous" groups ["system:unauthenticated"] cannot "get" nonResourceURL "/oauth/token/request" cluster-wide
I0901 20:52:08.023027   31318 wrap.go:42] GET /oauth/token/request: (253.263µs) 403 [[Go-http-client/2.0] 127.0.0.1:40058]
I0901 20:52:08.042529   31318 wrap.go:42] GET /api/v1/namespaces/kube-system: (1.324586ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
I0901 20:52:08.044169   31318 wrap.go:42] GET /api/v1/namespaces/kube-public: (1.171313ms) 200 [[integration.test/v1.7.0+695f48a16f (linux/amd64) kubernetes/8070990] 127.0.0.1:37166]
--- FAIL: TestWellKnownOAuthOff (69.06s)
	master_routes_test.go:226: unexpected error: server did not become healthy: {
		  "kind": "Status",
		  "apiVersion": "v1",
		  "metadata": {},
		  "status": "Failure",
		  "message": "User \"system:anonymous\" cannot \"get\" on \"/oauth/token/request\"",
		  "reason": "Forbidden",
		  "details": {},
		  "code": 403
		}
	etcd.go:141: dumping etcd to "/tmp/openshift/test-integration/tmp-testwellknownoauthoff556912309/etcd-dump-TestWellKnownOAuthOff-v2.json"
FAIL
```

**Comment by enj** [comment]
Queue broken on #16143

/retest
