### PR TITLE
Take care of manifest config blob 

### LINKED ISSUE #10730: Registry fails to serve imported manifest of schema 2 to old client
Manifest V2 schema 2 refers to a special blob by a digest. The blob is a config file which used to be embedded in manifest V2 schema 1. During an image import, the config file is stored in image object. Registry storage is not modified. When such an image is pulled by older client (supporting just manifest V2 schema 1), the registry attempts to convert schema 2 fetched from etcd to schema 1. For this it needs the config file. It attempts to load it from registry's storage and fails.

##### Version
openshift v1.3.0-alpha.3+3fc2c7c-dirty
kubernetes v1.3.0+507d3a7

docker:
```
Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-common-1.9.1-40.el7.x86_64
 Go version:      go1.4.2
 Git commit:      ab77bde/1.9.1
```

##### Steps To Reproduce
1. deploy registry
2. login as a user **U** and start a new project **P**
3. tag some remote image of schema 2: `oc tag --source docker docker.io/busybox:latest busybox:latest`
4. login to docker 1.9 with **U**'s token
5. manually pull the image: `docker pull ${REGISTRY_URL}/P/busybox:latest`

##### Current Result
```
Trying to pull repository 172.30.241.183:5000/pjoe/busybox ... failed
manifest invalid: manifest invalid
```

##### Expected Result
Successful pull.

##### Additional Information
- This case should be handled by pullthroughmiddleware. The middleware needs to override `Get()` method.
- A case where imagestreamimage is tagged to another repository/namespace needs to be tested as well.

### PR DESCRIPTION
**Pull request by mfojtik**
clone of: https://github.com/openshift/origin/pull/10759

Resolves #10730

Manifest V2 schema 2 introduces a special blob called config which used to be emeedded in earlier schema. See [upstream's spec](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#image-manifest-field-descriptions) for details. The config is stored as a regular blob on registry's storage. Thus the config needs to be treated similar to a regular layer:

1. the pullthrough middleware needs to be able to fetch it from remote repository
2. we need to increase a size of image for the size of its config
3. the config's digest needs to be cached as a regular layer inside a registry for subsequent lookups
4. image pruning needs to prune it the same way as regular layer

The PR addresses the first 3 items. I'd like to cover the pruning case in a follow-up.

### CODE REVIEW

**Comment by mfojtik** [comment]
[merge]

**Comment by mfojtik** [comment]
@liggitt @miminar we need to get this today. I fixed that failing test here.

File: test/end-to-end/core.sh [hunk 1]
```diff
@@ -480,6 +508,42 @@ os::cmd::expect_success "oc exec -p ${registry_pod} du /registry > '${LOG_DIR}/p
...
+os::cmd::expect_success "oc project ${CLUSTER_ADMIN_CONTEXT}"
+os::cmd::expect_success 'oc env -n default dc/docker-registry REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true'
+wait_for_registry
+echo "[INFO] Registry configured to accept manifest V2 schema 2"
+
+echo "[INFO] Accept manifest V2 schema 2"
+os::cmd::expect_success "oc login -u schema2-user -p pass"
+os::cmd::expect_success "oc project schema2"
+# tagging remote docker.io/busybox image
+os::cmd::expect_success "oc tag --source=docker busybox '${DOCKER_REGISTRY}/schema2/busybox'"
```
Comment (liggitt) [inline test/end-to-end/core.sh]: actually, I was wrong... I think this was supposed to be `docker tag`, but without the `--source`

Comment (liggitt) [inline test/end-to-end/core.sh]: it's trying to tag and push using pure docker API calls

Comment (mfojtik) [inline test/end-to-end/core.sh]: `--source` removed

**Comment by mfojtik** [comment]
[merge]

**Comment by miminar** [comment]
@mfojtik thanks! You were faster :smile:

**Comment by miminar** [comment]
[merge]

**Comment by soltysh** [comment]
[test]

**Comment by mfojtik** [comment]
[merge]
