### PR TITLE
Match subpaths correctly when path contains trailing slash

### LINKED ISSUE #13862: Router path parameters broken in 1.5
Routes that are created with a path / are now only responding to traffic in / and not any subsequent paths

ie.
Route: example.com
Path: /

example.com --> OK
example.com/test --> NOT OK

The web console has / as a suggested value
This was not the same behaviour in 1.4.1

##### Version
v1.5.0

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #13862

* Make paths of `"/"` and `""` behave identically
* If the path specified in a route ends with a `/`, omit `/` from the subpath regex

### CODE REVIEW

**Comment by liggitt** [comment]
will open cherry picks once reviewed

File: pkg/router/template/router_test.go [hunk 1]
```diff
@@ -670,3 +671,94 @@ func TestAddRouteEdgeTerminationInsecurePolicy(t *testing.T) {
...
+				"example.com/sub",
+				"example.com/sub/",
+			},
+			nomatch: []string{"other.com"},
+		},
+		{
+			name:     "subpath with trailing slash",
+			hostname: "example.com",
+			path:     "/sub/",
+			wildcard: false,
```
Comment (smarterclayton) [inline pkg/router/template/router_test.go]: wildcard test?

Comment (liggitt) [inline pkg/router/template/router_test.go]: added

**Comment by liggitt** [comment]
[test]

**Comment by kargakis** [comment]
lgtm [test]

**Comment by smarterclayton** [comment]
[merge] post rebase, can you backport to 1.5 and I'll cut a release?

**Comment by knobunc** [comment]
Tracked by bug https://bugzilla.redhat.com/show_bug.cgi?id=1448944
