### PR TITLE
oc new-app display correct error on missing context directory

### LINKED ISSUE #14298: oc new-app with context-dir does not find Dockerfile
[provide a description of the issue]

Creating an app with new-app from a git repo with both a context-dir and strategy=docker ends up with:

oc new-app --name=docker-centos-app1 https://gitlab.XX.com/XX/XX.git#XX --context-dir=/docker-centos-app1 --strategy=docker -o yaml > app1.yaml
error: No Dockerfile was found in the repository and the requested build strategy is 'docker'

Not telling him the strategy ends up with:
error: No language matched the source repository

I tried to specify context-dir both with the leading / and without it.

##### Version
oc v3.5.5.15
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://XX:443
openshift v3.5.5.5
kubernetes v1.5.2+43a9be4

##### Steps To Reproduce
1. see description

##### Current Result
Cannot build from Dockerfile

##### Expected Result
Can build from Dockerfile

### PR DESCRIPTION
**Pull request by coreydaley**
Adds additional check for existence of supplied context directory
and displays correct error
Also added test for the correct error

Previously a missing context directory would display an error
about a missing Dockerfile (when using the docker strategy)

Fixes #14298

### CODE REVIEW

**Comment by coreydaley** [comment]
[test]

**Comment by coreydaley** [comment]
@bparees ptal

File: pkg/generate/app/sourcelookup.go [hunk 1]
```diff
@@ -597,7 +597,11 @@ func CloneAndCheckoutSources(repo git.Repository, remote, ref, localDir, context
 		}
 	}
 	if len(contextDir) > 0 {
-		glog.V(5).Infof("Using context directory %q. The full source path is %q", contextDir, filepath.Join(localDir, contextDir))
+		if _, err := os.Stat(filepath.Join(localDir, contextDir)); os.IsNotExist(err) {
+			return "", fmt.Errorf("supplied context directory '%s' does not exist in '%s' repository", contextDir, remote)
+		} else {
+			glog.V(5).Infof("Using context directory %q. The full source path is %q", contextDir, filepath.Join(localDir, contextDir))
+		}
```
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: looks like there are other paths where a contextdir is consumed that this won't catch, e.g.:
https://github.com/openshift/origin/blob/master/pkg/generate/app/sourcelookup.go#L249

i think maybe you need to be checking the path later in the code flow.

Comment (coreydaley) [inline pkg/generate/app/sourcelookup.go]: Hmm, if it's not caught here, it will give the Dockerfile not found error even if the context directory is what is missing.

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: why?  this is returning a path(including the contextdir).  the consumer of that path should be able to check if that path actually exists or not, before it goes looking for a Dockerfile in that path.

Comment (coreydaley) [inline pkg/generate/app/sourcelookup.go]: fixed per our conversation via email

**Comment by bparees** [comment]
[merge][severity:bug]
