### PR TITLE
Initialise BinaryBuildSource to an empty value in the default case

### LINKED ISSUE #7976: spec.source.type == "Binary" not used for creating default
## Version

1.1.3

## Description

When using binary source validation fails when only a `type: "Binary"` is given but no `binary: {}`. This behaviour is different for the build strategy where a `type: "Docker"` is sufficient without providing a `dockerStrategy:`

This behaviour is inconsistent and either providing only the `type` is allowed, too for both parts of forbidden for both (but not allowed for strategy but not for source)

## Steps To Reproduce

For example thus definition is valid:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    binary: {}
  strategy:
    dockerStrategy: {}
```

but this not:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    type: "Binary"
  strategy:
    type: "Docker"
```

The mixed form also works:

```yaml
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "cdi-camel-binary-build"
spec:
  source:
    binary: {}
  strategy:
    type: "Docker"
```

## Additional Information

The validation code for the source can be found [here](https://github.com/openshift/origin/blob/master/pkg/build/api/validation/validation.go#L106-L108) and clearly doesn't take into account any given type. For a `binary` source no extra information is needed most of the time so that this config is usually empty. It would be better to allow a type specification here, too.

Interestingly, the client [adds an empty `dockerStrategy`](https://github.com/openshift/origin/blob/482a64f46f0d8f51d332958b50729f9a47d628c9/pkg/build/api/v1/conversion.go#L215-L222) when a `Strategy.Type == "Docker"` is present.

My suggestion is to do the same for the source, especially the [documentation](https://github.com/openshift/openshift-docs/blob/master/dev_guide/builds.adoc#binary-source) suggests this as a valid use case. (Alternatively, the documentation should be updated to remove 'type:' and mention 'binary:' as mandatory).

If we could agree on the correct behaviour I can prepare a PR for this.

### PR DESCRIPTION
**Pull request by rhuss**
If `Type` for a `Build.Source` is set to `BuildSourceBinary` but no value provided, then initialise `BinaryBuildSource` with an empty object.

Fixes #7976.

### CODE REVIEW

**Comment by rhuss** [comment]
The check fails because of a lint rule which [croaks](https://travis-ci.org/openshift/origin/jobs/116063977#L195-L215) that an inner `err` declaration shadows an out `err` declaration.

While this is true (and btw has nothing todo with this PR), I wonder whether one could relax this rule since its so a common usage pattern to name error `err` (even twice).

**Comment by liggitt** [comment]
while it is common, it's also a common source of bugs (I've personally been bitten twice by it). We're trying to roll the checks out gradually package by package, thought it's unclear why the build sometimes starts complaining about one that is unrelated to a particular PR

**Comment by rhuss** [comment]
thanks for the heads up. I'm really just about to learn more idiomatic Go, and Origin (along with k8s) is an excellent teacher ;-)

File: pkg/build/api/v1/conversion.go [hunk 1]
```diff
@@ -212,9 +212,17 @@ func convert_v1_BuildStrategy_To_api_BuildStrategy(in *BuildStrategy, out *newer
 
 func addConversionFuncs(scheme *runtime.Scheme) {
 	err := scheme.AddDefaultingFuncs(
+		func(source *BuildSource) {
+			if (source != nil) && (source.Type == BuildSourceBinary) {
+				// initialize the Binary source to an empty default state if type but no value set
+				if source.Binary == nil {
```
Comment (bparees) [inline pkg/build/api/v1/conversion.go]: you can actually just make this another condition on the first if-check.

**Comment by bparees** [comment]
one nit and lgtm
[test]

File: pkg/build/api/v1/conversion.go (hunk 1 above)
Comment (rhuss) [inline pkg/build/api/v1/conversion.go]: you are right. 

should I fix that ? (and in the other defaulting functions below, too) ?

Comment (bparees) [inline pkg/build/api/v1/conversion.go]: yes please

Comment (rhuss) [inline pkg/build/api/v1/conversion.go]: done (also removed redundant comment)

**Comment by bparees** [comment]
lgtm, thanks @rhuss! 
[merge]
