### PR TITLE
Include update operation in build admission controller

### LINKED ISSUE #6556: Can edit a build config to a strategy that isn't allowed by policy - builds still fail correctly
If I apply the policy changes to restrict certain build strategies, I can create a BC with an allowed strategy and then edit the BC to use a restricted strategy, that edit should fail.  Instead it allows the modification.  It does still correctly prevent the builds from being launched.

### PR DESCRIPTION
**Pull request by csrwng**
It is possible to update a bc that was created with an allowed type to a type that is not allowed. This change closes that loophole.

Fixes #6556

### CODE REVIEW

**Comment by csrwng** [comment]
@bparees ptal
@jwforres fyi

File: test/integration/build_admission_test.go [hunk 1]
```diff
@@ -54,6 +54,15 @@ func TestPolicyBasedRestrictionOfBuildCreateAndCloneByStrategy(t *testing.T) {
 		}
 	}
 
+	// make sure build updates are rejected
+	for _, strategy := range buildStrategyTypes() {
+		for clientType, client := range clients {
+			if _, err := updateBuild(t, client.Builds(testutil.Namespace()), builds[string(strategy)+clientType]); !kapierror.IsForbidden(err) {
+				t.Errorf("epxected forbidden for strategy %s and client %s: got %v", strategy, clientType, err)
```
Comment (bparees) [inline test/integration/build_admission_test.go]: expected

Comment (csrwng) [inline test/integration/build_admission_test.go]: fixed

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by csrwng** [comment]
rebased
[merge]

**Comment by bparees** [comment]
[merge]

**Comment by deads2k** [comment]
[test]

**Comment by deads2k** [comment]
@csrwng Not a known flake:

```
FAILURE after 0.168s: hack/../test/cmd/builds.sh:79: executing 'oc patch bc/ruby-sample-build -p '{"spec":{"output":{"to":{"name":"different:tag1"}}}}'' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
Error from server: resource: required value
!!! Error in hack/../test/cmd/../../hack/cmd_util.sh:195
	'return 1' exited with status 1
Call stack:
	1: hack/../test/cmd/../../hack/cmd_util.sh:195 os::cmd::expect_success(...)
	2: hack/../test/cmd/builds.sh:79 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:288
	'${test}' exited with status 1
Call stack:
	1: hack/test-cmd.sh:288 main(...)
Exiting with status 1
[FAIL] !!!!! Test Failed !!!!
```

**Comment by csrwng** [comment]
@deads2k thanks. Just discovered that this is a bug in the upstream API server... patch calls the admission control plugin with an empty object. If it gets permission, then proceeds to patch the stored object. So the admission control plugin never gets a chance to determine whether the patched object is valid or not. https://github.com/openshift/origin/blob/master/Godeps/_workspace/src/k8s.io/kubernetes/pkg/apiserver/resthandler.go#L399-L407

To get this PR in, I can add a check for an empty object and let it go through. However, you'll be able to use patch to change a build config to a type that you're not allowed to use.

**Comment by csrwng** [comment]
Opened k8s issue: https://github.com/kubernetes/kubernetes/issues/19479

**Comment by csrwng** [comment]
Added check for an actual update @deads2k ptal

File: pkg/build/admission/admission.go [hunk 2]
```diff
@@ -143,3 +154,11 @@ func (a *buildByStrategy) checkAccess(strategy buildapi.BuildStrategy, subjectAc
 func notAllowed(strategy buildapi.BuildStrategy, attr admission.Attributes) error {
 	return admission.NewForbidden(attr, fmt.Errorf("build strategy %s is not allowed", buildapi.StrategyType(strategy)))
 }
+
+func isValidUpdate(obj runtime.Object) (bool, error) {
+	accessor, err := meta.Accessor(obj)
+	if err != nil {
+		return false, err
+	}
+	return len(accessor.ResourceVersion()) > 0, nil
```
Comment (deads2k) [inline pkg/build/admission/admission.go]: Can't I do a force update without a `ResourceVersion`?  `Name` would have to be present.

Comment (csrwng) [inline pkg/build/admission/admission.go]: ha, you're right... name is a better check

Comment (csrwng) [inline pkg/build/admission/admission.go]: updated to use name

**Comment by deads2k** [comment]
Removing merge tags while I look at how hard proper admission will be.  Depending on how bad it is, we may wait and apply this on top.  I will update one way or the other this afternoon.

**Comment by csrwng** [comment]
reverted to not checking object on update - will depend on upstream fix

**Comment by deads2k** [comment]
Try building on top of https://github.com/openshift/origin/pull/6608.  It should make the update admission chain work how you expect.

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
[test]

**Comment by csrwng** [comment]
@deads2k I added a commit to modify the bootstrap policy for the build controller sa. Because we are now checking build update operations, the build controller cannot update builds without having access to the build type virtual resources. How would migration of existing policy be handled in this case?

**Comment by liggitt** [comment]
Wait, why didn't the build controller already have those permissions? How was it able to create builds without them?

**Comment by csrwng** [comment]
@liggitt the build controller doesn't create builds, only the BuildConfig controller does. Looking at the startup code, the BuildImageChangeTriggerController gets a PrivilegedLoopbackOpenShiftClient, not a service account client.

File: pkg/build/admission/admission.go [hunk 3]
```diff
@@ -35,7 +35,7 @@ type buildByStrategy struct {
 // on policy based on the build strategy type
 func NewBuildByStrategy(client client.Interface) admission.Interface {
 	return &buildByStrategy{
-		Handler: admission.NewHandler(admission.Create),
+		Handler: admission.NewHandler(admission.Create, admission.Update),
```
Comment (liggitt) [inline pkg/build/admission/admission.go]: is it odd that we're gating create and update on create permission on the subresource? I'd sort of expect create to check create, and update to check update

File: pkg/cmd/server/bootstrappolicy/infra_sa_policy.go [hunk 4]
```diff
@@ -98,6 +98,10 @@ func init() {
 					Verbs:     sets.NewString("update"),
 					Resources: sets.NewString("builds"),
 				},
+				{
+					Verbs:     sets.NewString("create"),
+					Resources: sets.NewString("builds/docker", "builds/source", "builds/custom"),
+				},
```
Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/infra_sa_policy.go]: so this is needed because the build controller *updates* builds? If so, it would make more sense to have this be an update permission

Comment (deads2k) [inline pkg/cmd/server/bootstrappolicy/infra_sa_policy.go]: > so this is needed because the build controller updates builds? If so, it would make more sense to have this be an update permission

Not from a user perspective.  Granting the power to create docker builds is functionally equivalent to updating a build to be a docker build.  Why make me repeat myself?  These are virtual resources used for field level access control.

Now, why are build kinds mutable on a given build, that seems like a good question. :)

File: pkg/build/admission/admission.go (hunk 3 above)
Comment (csrwng) [inline pkg/build/admission/admission.go]: I had discussed this with @bparees ... I'm fine with either way. Because it is a virtual resource, separating create from update didn't seem to gain us much. You still have separate permission for create or update of the actual resource and requiring that permissions be aligned seemed overkill.

File: pkg/cmd/server/bootstrappolicy/infra_sa_policy.go (hunk 4 above)
Comment (csrwng) [inline pkg/cmd/server/bootstrappolicy/infra_sa_policy.go]: @deads2k so are you saying that instead of gating updates on builds by type, we should ensure that you're not changing the type in the builds store? I agree, there's no reason to allow you to update the type.

File: pkg/build/admission/admission.go (hunk 3 above)
Comment (liggitt) [inline pkg/build/admission/admission.go]: fair enough, just reads weird

Comment (liggitt) [inline pkg/build/admission/admission.go]: maybe worth a comment in the policy, in case someone is confused

**Comment by csrwng** [comment]
added comment and updated test fixture

**Comment by csrwng** [comment]
seems like a flake [test]

**Comment by deads2k** [comment]
flake: https://github.com/openshift/origin/issues/6635

**Comment by deads2k** [comment]
lgtm.  squash and merge at will.

**Comment by csrwng** [comment]
[merge]

**Comment by csrwng** [comment]
[merge]

**Comment by csrwng** [comment]
Failing on https://github.com/openshift/origin/issues/6651

**Comment by liggitt** [comment]
[test][merge]
