### PR TITLE
SDN controller requires access to watch resources

### LINKED ISSUE #14964: flake: GCE cluster provision failure (2)
From https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/2821/

Similar to https://github.com/openshift/origin/issues/14575 (perhaps can be dupped ??)

The first inkling of some trouble was:

```
TASK [openshift_node : Start and enable node] **********************************
Thursday 29 June 2017  16:01:54 +0000 (0:00:00.156)       0:15:03.087 ********* 
FAILED - RETRYING: Start and enable node (1 retries left).
FAILED - RETRYING: Start and enable node (1 retries left).
FAILED - RETRYING: Start and enable node (1 retries left).
FAILED - RETRYING: Start and enable node (1 retries left).
ok: [ci-prtest-5a37c28-3889-ig-m-k63s]
ok: [ci-prtest-5a37c28-3889-ig-n-2l38]
ok: [ci-prtest-5a37c28-3889-ig-n-0xsr]
ok: [ci-prtest-5a37c28-3889-ig-n-j2s8]
```

but perhaps it recovered given the final set of `ok` messages.

But then we got this:

```
RUNNING HANDLER [openshift_node : restart node] ********************************
Thursday 29 June 2017  16:02:40 +0000 (0:00:00.053)       0:15:49.265 ********* 
fatal: [ci-prtest-5a37c28-3889-ig-m-k63s]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [ci-prtest-5a37c28-3889-ig-n-j2s8]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [ci-prtest-5a37c28-3889-ig-n-0xsr]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
fatal: [ci-prtest-5a37c28-3889-ig-n-2l38]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See \"systemctl status origin-node.service\" and \"journalctl -xe\" for details.\n"}
```

And 

```
Failure summary:

  1. Host:     ci-prtest-5a37c28-3889-ig-m-k63s
     Play:     Configure nodes
     Task:     openshift_node : restart node
     Message:  Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
               

  2. Host:     ci-prtest-5a37c28-3889-ig-n-j2s8
     Play:     Configure nodes
     Task:     openshift_node : restart node
     Message:  Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
               

  3. Host:     ci-prtest-5a37c28-3889-ig-n-0xsr
     Play:     Configure nodes
     Task:     openshift_node : restart node
     Message:  Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
               

  4. Host:     ci-prtest-5a37c28-3889-ig-n-2l38
     Play:     Configure nodes
     Task:     openshift_node : restart node
     Message:  Unable to restart service origin-node: Job for origin-node.service failed because the control process exited with error code. See "systemctl status origin-node.service" and "journalctl -xe" for details.
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes bug 1465361
Fixes #14964

[test]

### CODE REVIEW

**Comment by smarterclayton** [comment]
@deads2k it's too easy for a reflector to fail to watch and go into LIST polling without noticing if reflector's default interval is 1s.  We should probably be backing off the reflector or otherwise rate limiting it.

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 1]
```diff
@@ -207,14 +207,14 @@ func init() {
 		Rules: []rbac.PolicyRule{
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: This applies to the SDN master but not the nodes, correct?

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 2]
```diff
@@ -207,14 +207,14 @@ func init() {
...
 			rbac.NewRule("get", "create", "update").Groups(networkGroup, legacyNetworkGroup).Resources("clusternetworks").RuleOrDie(),
 			rbac.NewRule("get", "list").Groups(networkGroup, legacyNetworkGroup).Resources("egressnetworkpolicies").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: The master does not need to get or list egressnetworkpolicies.

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 3]
```diff
@@ -207,14 +207,14 @@ func init() {
...
-			rbac.NewRule("get", "list", "create", "delete").Groups(networkGroup, legacyNetworkGroup).Resources("hostsubnets").RuleOrDie(),
-			rbac.NewRule("get", "list", "create", "update", "delete").Groups(networkGroup, legacyNetworkGroup).Resources("netnamespaces").RuleOrDie(),
+			rbac.NewRule("get", "list", "watch", "create", "delete").Groups(networkGroup, legacyNetworkGroup).Resources("hostsubnets").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: (as mentioned on the other bug, this fix is correct but only applies in an obscure case, for F5 integration)

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 4]
```diff
@@ -207,14 +207,14 @@ func init() {
...
+			rbac.NewRule("get", "list", "watch", "create", "update", "delete").Groups(networkGroup, legacyNetworkGroup).Resources("netnamespaces").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: this fix is correct... and the lack of "watch" here should have caused test/cmd/sdn.sh to fail... weird

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 5]
```diff
@@ -207,14 +207,14 @@ func init() {
...
 			rbac.NewRule("get", "list").Groups(kapiGroup).Resources("pods").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: FWIW it doesn't currently need "get", though it does use "list" (at startup, to make sure that all running pods are inside the current clusterNetworkCIDR).

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 6]
```diff
@@ -207,14 +207,14 @@ func init() {
...
 			rbac.NewRule("list").Groups(kapiGroup).Resources("services").RuleOrDie(),
 			rbac.NewRule("list").Groups(kapiGroup).Resources("namespaces").RuleOrDie(),
 			rbac.NewRule("get").Groups(kapiGroup).Resources("nodes").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: That's no good. The master needs "list" and "watch" on nodes so that it can create/delete hostsubnets as nodes are created/deleted. (Um... and I have no explanation for how networking-minimal could pass with this being wrong... Is the SDN possibly picking up permissions from somewhere else? Oh, we use a SharedInformer here now, is that it?)

File: pkg/cmd/server/bootstrappolicy/controller_policy.go [hunk 7]
```diff
@@ -207,14 +207,14 @@ func init() {
...
 			rbac.NewRule("update").Groups(kapiGroup).Resources("nodes/status").RuleOrDie(),
-			rbac.NewRule("list").Groups(extensionsGroup).Resources("networkPolicies").RuleOrDie(),
+			rbac.NewRule("list", "watch").Groups(extensionsGroup).Resources("networkPolicies").RuleOrDie(),
```
Comment (danwinship) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: the master should not need any access to networkpolicies

File: pkg/cmd/server/bootstrappolicy/controller_policy.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: Correct

File: pkg/cmd/server/bootstrappolicy/controller_policy.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: How so?  You're running as cluster-admin in that test (unless you explicitly switch to another user).  And the controllers should only be delayed by 1s max because of the relisting behavior.

File: pkg/cmd/server/bootstrappolicy/controller_policy.go (hunk 5 above)
Comment (smarterclayton) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: Hrm, can probably leave it.  "get"/"list"/"watch" are so closely coupled that we probably should have just done a placeholder

File: pkg/cmd/server/bootstrappolicy/controller_policy.go (hunk 6 above)
Comment (smarterclayton) [inline pkg/cmd/server/bootstrappolicy/controller_policy.go]: The master is using a shared informer, I'll add the permissions explicitly though.

**Comment by smarterclayton** [comment]
Updated with comments addressed

**Comment by danwinship** [comment]
LGTM
[testextended][extended:networking]

**Comment by dcbw** [comment]
LGTM

**Comment by deads2k** [comment]
> @deads2k it's too easy for a reflector to fail to watch and go into LIST polling without noticing if reflector's default interval is 1s. We should probably be backing off the reflector or otherwise rate limiting it.

It's hard to know what is "good".  I guess its a function of whether we want the failures to mostly work or mostly fail.  I'm actually inclined to have two modes that are toggled by env var.  If we panic during our tests we're unlikely to ship a mistake, but if we do ship a mistake limping along on a relist seems better than straight up failing.

The difference between 1 second and 10 seconds on a long list doesn't matter.  You're talking about switching to O(minutes)?

**Comment by smarterclayton** [comment]
I'm thinking backoff from 1s up to 20-30s.  I am extremely concerned about anything that is a fixed rate failing forever, we already know exactly what that looks like in very large clusters and we're going to stop doing it :)
