### PR TITLE
made login fail with bad token

### LINKED ISSUE #7000: `oc login --token` with an invalid token interactively prompts for password
When using `oc login --token=whatever`, and the token provided is incorrect, the `login` prompt hangs waiting for a password. This should not occur.

/cc  @liggitt

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This PR makes logging in with a bad token (`oc login --token=`) fail straight away instead of interactively asking for credentials.

@liggitt PTAL

fixes #7000

### CODE REVIEW

**Comment by liggitt** [comment]
Add a test

File: pkg/cmd/cli/cmd/loginoptions.go [hunk 1]
```diff
@@ -217,7 +217,7 @@ func (o *LoginOptions) gatherAuthInfo() error {
 				return err
 			}
 
-			fmt.Fprint(o.Out, "The token provided is invalid (probably expired).\n\n")
+			return fmt.Errorf("The token provided is invalid (probably expired).\n\n")
```
Comment (liggitt) [inline pkg/cmd/cli/cmd/loginoptions.go]: and change to "... invalid or expired"

**Comment by stevekuznetsov** [comment]
@liggitt  done

[test]me

**Comment by liggitt** [comment]
LGTM, [merge]
