### PR TITLE
Web console: fix log start on pod state transition

### LINKED ISSUE #7533: Web console: logs don't load when pod moves from pending to running
When I open the log tab when the pod is pending, the logs don't start streaming when the pod starts running. I need to refresh the page or navigate away and back.

/cc @jwforres @benjaminapetersen

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix #7533 

- Ensure log run vars are set in GET and WATCH on build, pod & deployment 

@spadgett @jwforres

### CODE REVIEW

File: assets/app/scripts/controllers/deployment.js [hunk 1]
```diff
@@ -104,6 +104,8 @@ angular.module('openshiftConsole')
                 };
               }
               $scope.deployment = deployment;
+              $scope.logOptions.container = $filter("annotation")(deployment, "pod");
+              $scope.logCanRun = !(_.includes(['New', 'Pending'], $filter('deploymentStatus')(deployment)));
```
Comment (spadgett) [inline assets/app/scripts/controllers/deployment.js]: The updates are complicated enough I'd rather pull them into a function instead of repeating them twice (here and the other controllers).

Comment (benjaminapetersen) [inline assets/app/scripts/controllers/deployment.js]: agree.  i can pull that out into a fn.

**Comment by benjaminapetersen** [comment]
Moved duplication out into a `setLogVars` fn in all three files.

**Comment by spadgett** [comment]
Can you squash and fix up the commit messages?

File: assets/app/scripts/controllers/build.js [hunk 2]
```diff
@@ -42,6 +42,11 @@ angular.module('openshiftConsole')
 
     var watches = [];
 
+    var setLogVars = function(build, $scope) {
```
Comment (spadgett) [inline assets/app/scripts/controllers/build.js]: Shouldn't need to pass `$scope` here and below.

Comment (benjaminapetersen) [inline assets/app/scripts/controllers/build.js]: Yeah isn't really necessary, was just preference for giving the fn everything it needs as args.  I'll cut `$scope`.

**Comment by benjaminapetersen** [comment]
Updated, should be good to go.

**Comment by spadgett** [comment]
LGTM [merge]
