### PR TITLE
On node startup, perform more checks of known requirements

### LINKED ISSUE #6916: Able to cause kubelet to panic
v1.1.1-301-ge88b251 - I think this is because I'm using DOCKER_HOST=http://.... but docker is listening on unix.  Not sure.

```
E0129 22:26:33.453143    4015 util.go:82] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:76
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:64
/usr/lib/golang/src/runtime/asm_amd64.s:402
/usr/lib/golang/src/runtime/panic.go:387
/usr/lib/golang/src/runtime/panic.go:42
/usr/lib/golang/src/runtime/sigpanic_unix.go:26
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go:339
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go:2067
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/dockertools/manager.go:425
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:3158
/data/src/github.com/openshift/origin/Godeps/_workspace/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1669
/usr/lib/golang/src/runtime/asm_amd64.s:401
/usr/lib/golang/src/runtime/panic.go:387
/usr/lib/golang/src/runtime/hashmap.go:385
```

### PR DESCRIPTION
**Pull request by smarterclayton**
Ensure we test the Docker socket more thoroughly for possible issues, then check permissions on directories and filesystems that we require in both normal and containerized mode.

Stop allowing Docker to fail in all-in-one - Macs will have to run openshift start master.

Fixes #6916

### CODE REVIEW

File: pkg/cmd/server/kubernetes/node_config.go [hunk 1]
```diff
@@ -157,9 +159,8 @@ func BuildKubernetesNodeConfig(options configapi.NodeConfig) (*NodeConfig, error
 	server.TLSCertFile = options.ServingInfo.ServerCert.CertFile
 	server.TLSPrivateKeyFile = options.ServingInfo.ServerCert.KeyFile
 
-	if value := cmdutil.Env("OPENSHIFT_CONTAINERIZED", ""); len(value) > 0 {
-		server.Containerized = value == "true"
-	}
+	containerized := cmdutil.Env("OPENSHIFT_CONTAINERIZED", "") == "true"
+	server.Containerized = containerized
```
Comment (liggitt) [inline pkg/cmd/server/kubernetes/node_config.go]: Why do we always override with the envvar value now?

**Comment by smarterclayton** [comment]
[test]

File: pkg/cmd/server/kubernetes/node_config.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/cmd/server/kubernetes/node_config.go]: Accident

Comment (smarterclayton) [inline pkg/cmd/server/kubernetes/node_config.go]: Nm, intentional.  Because we haven't loaded flags yet - we don't need to use their default because it makes no sense.

**Comment by smarterclayton** [comment]
This is now blocked on `TestNodeAuth` and being able to avoid loading the
proxy on startup - since that's something we need to do in #6908 going to
make sure that lands first.

**Comment by smarterclayton** [comment]
Ok, this is ready for review:

* Checks for a set of node conditions if we're going to load the kubelet
* Adds `openshift start network` to launch proxy and SDN
* Adds `--enable-proxy` and `--enable-plugins` to `node` and `network` to control fine grained start modes
* Changes the integration tests to disable the proxy and SDN plugins
* Loads etcd in each integration test instead of running a separate etcd process

**Comment by smarterclayton** [comment]
This closes out the proxy issue about adding a new command to start the proxy independently.

**Comment by smarterclayton** [comment]
Fixes #6908

**Comment by smarterclayton** [comment]
--- FAIL: TestAuthProxyOnAuthorize-2 (14.73s)
	auth_proxy_test.go:53: proxy server is on http://127.0.0.1:44764
	buildcontroller_test.go:322: unexpected error: error #0: client: etcd member http://127.0.0 ... has no leader

Interesting, this may be the healthz flake, but now because we start etcd much more often in integration it shows up

**Comment by liggitt** [comment]
@smarterclayton would we rather do this the same way we did the master?
`openshift start node kubelet`
`openshift start node proxy`

**Comment by smarterclayton** [comment]
I don't know - I expect we'll have more components (DNS, idler), but idler has to be part of proxy, and technically SDN has to be part of proxy right now today because it intercepts and filters the service list.  So i'm hesistant to say that "proxy | kubelet" would be correct for buckets.

**Comment by liggitt** [comment]
sure... just feels weird to do master as subcommands and node as "start node --exclude-thing-1"

**Comment by smarterclayton** [comment]
Hrm... I can see both ways.  With master, it was sub roles that
wouldn't be colocated.

On node, it's more like you might want to split certain pieces off,
but, the pieces are intertwined.  To run idling, you have to have the
proxy.  So do safe multitenant services, you have to have proxy
running.  But if you don't want network, you can disable it directly.

**Comment by smarterclayton** [comment]
Updated to have --enable

**Comment by smarterclayton** [comment]
Will update controllers after this merges

**Comment by smarterclayton** [comment]
@liggitt PTAL

File: pkg/cmd/server/kubernetes/node.go [hunk 2]
```diff
@@ -47,10 +51,74 @@ func (ce defaultCommandExecutor) Run(command string, args ...string) error {
 
 const minimumDockerAPIVersionWithPullByID = "1.18"
 
+// EnsureKubeletAccess performs a number of test operations that the Kubelet requires to properly function.
+// All errors here are fatal.
+func (c *NodeConfig) EnsureKubeletAccess() {
+	if _, err := os.Stat("/var/lib/docker"); os.IsPermission(err) {
+		glog.Fatal("error: Unable to view the /var/lib/docker directory - are you running as root?")
```
Comment (liggitt) [inline pkg/cmd/server/kubernetes/node.go]: tolerate if AllowDisabledDocker?

Comment (smarterclayton) [inline pkg/cmd/server/kubernetes/node.go]: I can call HandleDockerError

Comment (smarterclayton) [inline pkg/cmd/server/kubernetes/node.go]: I can't call HandleDockerError.  Hrm...

Comment (smarterclayton) [inline pkg/cmd/server/kubernetes/node.go]: I can call it.

**Comment by smarterclayton** [comment]
[merge] you can post hoc

**Comment by liggitt** [comment]
We *have* to have tests for these modes. I'd expect an extended test that proves you can actually start the node with split components and it is functional

**Comment by liggitt** [comment]
Unmerge until we have some tests

**Comment by smarterclayton** [comment]
Now I know how to get you to come back to a PR

**Comment by smarterclayton** [comment]
Your tests, sir.

File: pkg/cmd/server/start/start_node.go [hunk 3]
```diff
@@ -249,30 +273,39 @@ func (o NodeOptions) IsRunFromConfig() bool {
 	return (len(o.ConfigFile) > 0)
 }
 
-func StartNode(nodeConfig configapi.NodeConfig) error {
+func StartNode(nodeConfig configapi.NodeConfig, nodeArgs *NodeArgs) error {
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: just pass in the `Components`... want to severely constrain what can override config

File: pkg/cmd/server/start/start_allinone.go [hunk 4]
```diff
@@ -105,19 +99,19 @@ func NewCommandStartAllInOne(basename string, out io.Writer) (*cobra.Command, *A
 
 	masterArgs, nodeArgs, listenArg, imageFormatArgs, _ := GetAllInOneArgs()
 	options.MasterOptions.MasterArgs, options.NodeArgs = masterArgs, nodeArgs
-	// by default, all-in-ones all disabled docker.  Set it here so that if we allow it to be bound later, bindings take precedence
-	options.NodeArgs.AllowDisabledDocker = true
```
Comment (liggitt) [inline pkg/cmd/server/start/start_allinone.go]: worth an announcement

File: pkg/cmd/server/start/start_allinone.go [hunk 5]
```diff
@@ -67,14 +67,8 @@ func NewCommandStartAllInOne(basename string, out io.Writer) (*cobra.Command, *A
...
-			if err := options.Complete(); err != nil {
-				fmt.Fprintln(c.Out(), kcmdutil.UsageError(c, err.Error()))
-				return
-			}
-			if err := options.Validate(args); err != nil {
-				fmt.Fprintln(c.Out(), kcmdutil.UsageError(c, err.Error()))
-				return
-			}
+			kcmdutil.CheckErr(options.Complete())
+			kcmdutil.CheckErr(options.Validate(args))
```
Comment (liggitt) [inline pkg/cmd/server/start/start_allinone.go]: does this print usage in error cases?

Comment (smarterclayton) [inline pkg/cmd/server/start/start_allinone.go]: No, it doesn't.

File: pkg/cmd/server/start/start_node.go [hunk 6]
```diff
@@ -249,30 +273,39 @@ func (o NodeOptions) IsRunFromConfig() bool {
...
 	config, err := kubernetes.BuildKubernetesNodeConfig(nodeConfig)
 	if err != nil {
 		return err
 	}
-	glog.Infof("Starting node %s (%s)", config.KubeletServer.HostnameOverride, version.Get().String())
+
+	if nodeArgs.Components.Enabled("kubelet") {
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: constants for component names (used here and in the flag bindings and validation)

File: pkg/cmd/server/start/start_node.go [hunk 7]
```diff
@@ -249,30 +273,39 @@ func (o NodeOptions) IsRunFromConfig() bool {
...
+		config.EnsureDocker(docker.NewHelper())
+	}
+
+	if nodeArgs.Components.Enabled("proxy") {
+		config.RunProxy()
+	}
+	if nodeArgs.Components.Enabled("kubelet") {
+		config.RunKubelet()
+	}
+	if nodeArgs.Components.Enabled("plugins") {
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: plugins or sdn?

File: pkg/cmd/server/start/start_node.go [hunk 8]
```diff
@@ -249,30 +273,39 @@ func (o NodeOptions) IsRunFromConfig() bool {
...
-			}
-		}
+	if nodeArgs.Components.Enabled("kubelet") {
+		config.EnsureKubeletAccess()
+		config.EnsureVolumeDir()
+		config.EnsureDocker(docker.NewHelper())
+	}
+
+	if nodeArgs.Components.Enabled("proxy") {
+		config.RunProxy()
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: I thought the startup order of sdn -> proxy -> sysctl fixup was specifically needed... did that change?

File: pkg/cmd/util/flags/flags.go [hunk 9]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+
+// Enabled returns true if the component is enabled.
+func (f *ComponentFlag) Enabled(name string) bool {
+	return f.Calculated().Has(name)
+}
+
+// Calculated returns the effective enabled list.
+func (f *ComponentFlag) Calculated() sets.String {
+	if f.calculated == nil {
+		f.calculated = f.Expand(f.enabled).Difference(f.Expand(f.disabled)).Intersection(f.allowed)
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: why intersect with allowed? wouldn't you want to catch things in `enabled` that weren't allowed and fail validation, rather than silently removing them?

File: pkg/cmd/server/start/start_node.go (hunk 8 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Still the order.

File: pkg/cmd/server/start/start_node.go (hunk 7 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Plugins, doesn't have to be a SDN

File: pkg/cmd/util/flags/flags.go [hunk 10]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+}
+
+// Expand turns a string into a fully expanded set of components, resolving any mappings.
+func (f *ComponentFlag) Expand(value string) sets.String {
+	if len(value) == 0 {
+		return sets.NewString()
+	}
+	set := sets.NewString(strings.Split(value, ",")...)
+	for k := range set {
+		set.Insert(f.mappings[k]...)
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: this leaves the original aliases in the set as well?

Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: does anything weird happen if you mutate a map while iterating over it's keys?

File: pkg/cmd/util/flags/flags.go [hunk 11]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+	}
+	return copied
+}
+
+// Bind registers the necessary flags with a flag set.
+func (f *ComponentFlag) Bind(flags *pflag.FlagSet, flagFormat, messagePrefix string) {
+	flags.StringVar(&f.enabled, fmt.Sprintf(flagFormat, "enable"), f.enabled, messagePrefix+" enable")
+	flags.StringVar(&f.disabled, fmt.Sprintf(flagFormat, "disable"), f.disabled, messagePrefix+" disable")
+
+	f.isSet = func() bool { return flags.Lookup(fmt.Sprintf(flagFormat, "enable")).Changed }
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: needs to check disable as well, right?

File: pkg/cmd/server/start/start_node.go (hunk 8 above)
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: how? RunProxy happens before RunPlugin... iirc, RunProxy does some stuff synchronously before spawning a goroutine which requires the SDN already be running

File: pkg/cmd/server/start/start_node.go [hunk 12]
```diff
@@ -94,6 +68,62 @@ func NewCommandStartNode(basename string, out io.Writer) (*cobra.Command, *NodeO
 	return cmd, options
 }
 
+const networkLong = `
+Start a node
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: make the description networky

File: test/extended/alternate_launches.sh [hunk 13]
```diff
@@ -67,6 +68,61 @@ wait_for_url "${API_SCHEME}://${API_HOST}:${API_PORT}/healthz/ready" "apiserver(
...
+# test alternate node level launches
+echo "[INFO] Testing alternate node configurations"
+
+# proxy only
+sudo env "PATH=${PATH}" TEST_CALL=1 OPENSHIFT_ON_PANIC=crash openshift start network --enable=proxy \
+ --config=${NODE_CONFIG_DIR}/node-config.yaml \
+ --loglevel=4 \
+&>"${LOG_DIR}/os-network-1.log" &
+os::cmd::try_until_text 'cat ${LOG_DIR}/os-network-1.log' 'syncProxyRules took'
+pgrep -f "TEST_CALL=1" | xargs -r sudo kill
```
Comment (liggitt) [inline test/extended/alternate_launches.sh]: clever

File: pkg/cmd/util/flags/flags.go (hunk 11 above)
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: nm, I see how you're using it above... could use a better name

File: pkg/cmd/util/flags/flags.go [hunk 14]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+	return set
+}
+
+// Allowed returns a copy of the allowed list of components.
+func (f *ComponentFlag) Allowed() sets.String {
+	return sets.NewString(f.allowed.List()...)
+}
+
+// Mappings returns a copy of the mapping list for short names.
+func (f *ComponentFlag) Mappings() map[string][]string {
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: unused?

File: pkg/cmd/util/flags/flags.go [hunk 15]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+}
+
+// Enabled returns true if the component is enabled.
+func (f *ComponentFlag) Enabled(name string) bool {
+	return f.Calculated().Has(name)
+}
+
+// Calculated returns the effective enabled list.
+func (f *ComponentFlag) Calculated() sets.String {
+	if f.calculated == nil {
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: if this gets called before bound flags are parsed into `f.enabled` and `f.disabled`, `f.calculated` will ignore them

File: pkg/cmd/util/flags/flags.go [hunk 16]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+	return &ComponentFlag{
+		allowed:  set,
+		mappings: mappings,
+		enabled:  strings.Join(set.List(), ","),
+		isSet:    func() bool { return false },
+	}
+}
+
+// Disable marks the provided components as disabled.
+func (f *ComponentFlag) Disable(components ...string) {
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: same here, this interacts oddly depending on whether it's called before or after args are parsed

File: pkg/cmd/util/flags/flags.go [hunk 17]
```diff
@@ -33,3 +35,96 @@ func Resolve(args map[string][]string, fn func(*pflag.FlagSet)) []error {
...
+// Calculated returns the effective enabled list.
+func (f *ComponentFlag) Calculated() sets.String {
+	if f.calculated == nil {
+		f.calculated = f.Expand(f.enabled).Difference(f.Expand(f.disabled)).Intersection(f.allowed)
+	}
+	return f.calculated
+}
+
+// Actual returns a copy of the set of enabled components, or an error if there are conflicts.
+func (f *ComponentFlag) Actual() (sets.String, error) {
```
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: `Actual` and `Expand` are complex enough to justify unit tests

File: test/util/server/server.go [hunk 18]
```diff
@@ -230,36 +231,36 @@ func DefaultAllInOneOptions() (*configapi.MasterConfig, *configapi.NodeConfig, e
...
-		return nil, nil, err
+		return nil, nil, nil, err
 	}
 
-	return masterOptions, nodeOptions, nil
+	return masterOptions, nodeOptions, startOptions.NodeArgs, nil
 }
 
-func StartConfiguredAllInOne(masterConfig *configapi.MasterConfig, nodeConfig *configapi.NodeConfig) (string, error) {
+func StartConfiguredAllInOne(masterConfig *configapi.MasterConfig, nodeConfig *configapi.NodeConfig, nodeArgs *start.NodeArgs) (string, error) {
```
Comment (liggitt) [inline test/util/server/server.go]: just need the components

**Comment by liggitt** [comment]
[test][extended:networking,alternate_launches]

**Comment by liggitt** [comment]
I like the --enable/--disable approach a lot

File: pkg/cmd/util/flags/flags.go (hunk 9 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: That's what validation is for

File: test/extended/alternate_launches.sh (hunk 13 above)
Comment (smarterclayton) [inline test/extended/alternate_launches.sh]: Have I mentioned how much I hate bash and subprocess handling?

File: pkg/cmd/util/flags/flags.go (hunk 10 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: > The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next. If map entries that have not yet been reached are removed during iteration, the corresponding iteration values will not be produced. If map entries are created during iteration, that entry may be produced during the iteration or may be skipped. The choice may vary for each entry created and from one iteration to the next. If the map is nil, the number of iterations is 0.

I'm going to create another set to return to hide expansions

File: pkg/cmd/server/start/start_node.go (hunk 8 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Hrm, I thought we broke the dependency, but will check

**Comment by liggitt** [comment]
re[test]

File: pkg/cmd/server/start/start_allinone.go (hunk 5 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_allinone.go]: General rule is that every component below should return usage errors, I'm ok with returning slightly less info for a time and adding it back.  UsageError right now is almost pointless.

File: pkg/cmd/util/flags/flags.go (hunk 14 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: Utility, to avoid people putting in a wrong hack

File: pkg/cmd/util/flags/flags.go (hunk 15 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: Yes, like most flags this depends on being bound.  Will godoc comment

Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: Actually, all flags assume you've invoked Set or Bind.  So if you don't do that...

File: pkg/cmd/util/flags/flags.go (hunk 16 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: Same as any other flag, you expect it to be set.

File: pkg/cmd/util/flags/flags.go (hunk 15 above)
Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: not just bound, but already parsed, right?

Comment (liggitt) [inline pkg/cmd/util/flags/flags.go]: `Disable` calling into this and potentially locking things pre-parse is what concerns me

**Comment by smarterclayton** [comment]
PTAL

File: pkg/cmd/server/start/start_node.go [hunk 19]
```diff
@@ -249,30 +279,46 @@ func (o NodeOptions) IsRunFromConfig() bool {
...
-		}
+	if components.Enabled(ComponentKubelet) {
+		config.EnsureKubeletAccess()
+		config.EnsureVolumeDir()
+		config.EnsureDocker(docker.NewHelper())
+	}
+
+	// SDN plugins get the opportunity to filter service rules, so they start first
+	if components.Enabled(ComponentPlugins) {
+		config.RunPlugin()
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: what does this do if you do `start node --enable=plugins` and don't actually have a sdn plugin configured? does the process hang in the foreground or tell you you don't have any plugins?

File: pkg/cmd/util/flags/flags.go (hunk 15 above)
Comment (smarterclayton) [inline pkg/cmd/util/flags/flags.go]: Using flags before you parse flags is undefined behavior.  We don't lock it
elsewhere.

File: pkg/cmd/server/start/start_node.go (hunk 19 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: That's the config.  You passed "openshift start node --config=....
--enable=plugins", enable plugins does the right thing and stays open.

File: pkg/cmd/server/start/start_node.go [hunk 20]
```diff
@@ -249,30 +279,46 @@ func (o NodeOptions) IsRunFromConfig() bool {
...
+	}
+	// start the proxy before the kubelet so in the future we can run the Kubelet
+	// through the proxy
+	if components.Enabled(ComponentProxy) {
+		config.RunProxy()
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: the `sdn -> proxy -> reset` order means if you are using sdn, you can't successfully start plugins and proxy in separate processes, right? either the proxy would hang, or the sysctl reset wouldn't interleave with the proxy successfully

File: test/util/server/server.go [hunk 21]
```diff
@@ -219,10 +219,11 @@ func CreateNodeCerts(nodeArgs *start.NodeArgs, masterURL string) error {
 	return nil
 }
 
-func DefaultAllInOneOptions() (*configapi.MasterConfig, *configapi.NodeConfig, error) {
+func DefaultAllInOneOptions() (*configapi.MasterConfig, *configapi.NodeConfig, *start.NodeArgs, error) {
```
Comment (liggitt) [inline test/util/server/server.go]: return components, not args, plumb all the way through to StartNode

File: pkg/cmd/server/start/start_node.go (hunk 20 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: if you're doing separate processes, you would define start order.  If you're using multi tenant plugin, you need to run in the same process.

**Comment by smarterclayton** [comment]
[test]

File: pkg/cmd/server/start/start_node.go (hunk 20 above)
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: is there a possible start order that would work, since the proxy and sdn bits are interleaved? wouldn't block on it, but also would want to note that sdn/proxy won't work separately until we fix the interleave

**Comment by liggitt** [comment]
LGTM once alternate_launch and network tests pass
allinone change is worth an announcement

**Comment by smarterclayton** [comment]
Network dind tests are broken, i'm rerunning just alternates

File: pkg/cmd/server/start/start_node.go (hunk 20 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Separate proxy and SDN are only interleaved when you are multi tenant, and
then you have to run them single process to get filtering.

**Comment by liggitt** [comment]
> Network dind tests are broken, i'm rerunning just alternates

ok. can one of the network folks pull this and try out both sdns just as a sanity check (paging @dcbw, @danwinship, @marun)

File: pkg/cmd/server/start/start_node.go (hunk 20 above)
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: oh, I misread... looks like we're doing the sysctl reset for SingleTenantPluginName as well, though. worth noting, anyway

Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: The reset affects proxy, not multi tenant specific.  The multi tenant
filters the proxy.  Yes, will note somewhere.

**Comment by marun** [comment]
@liggitt @smarterclayton  #7456 fixes the dind tests, please merge and rebase on top.

**Comment by marun** [comment]
I'll validate locally for good measure, but the sooner we get the networking_extended job unstuck the better.

**Comment by smarterclayton** [comment]
This is green, waiting for @marun's investigation of the issue he was seeing

**Comment by liggitt** [comment]
Several issues found:
1. The SDN relies on the node record existing (the node self-registration having already occurred) in order to initialize successfully, so RunKubelet() has to remain before StartSDN()
2. There is a hidden dependency between RunKubelet and StartSDN where the network plugin given to the kubelet blocks pods waiting on a channel which is unblocked by StartSDN(). When the SDN is in a different process, the kubelet never starts.

**Comment by smarterclayton** [comment]
Document and validate against the hidden dependencies, probably breaks the
alternate launches test, but review now while i fix it.

**Comment by liggitt** [comment]
pull in the commit from https://github.com/openshift/origin/pull/7456/ so we can run the network tests on this (they're green with that commit)

**Comment by liggitt** [comment]
LGTM on green [test][extended:alternate_launches,networking]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] now that the bot is unstuck
