### PR TITLE
Read insecure annotation on an image stream when import-image is invoked

### LINKED ISSUE #8452: oc import-image doesn't take insecure annotation into consideration when importing
Spawned from #8440.

I create a repository an IS (like the one in #8440) that requires insecure flag, but I don't put it into yaml definition. After creating the IS the import will fail. 
I edit the IS adding `openshift.io/image.insecureRepository="true"` and re-import image with `oc import-image` and the import again fails. But if I add `--inscure` flag to `oc import-image` the import succeeds. Import should take the annotation into consideration.

##### Version
oc v1.1.6-48-g561e4fa
kubernetes v1.2.0-36-g4a3f9c5

@pweil- working on it

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #8452.

@pweil- @smarterclayton ptal

### CODE REVIEW

File: pkg/cmd/cli/cmd/importimage.go [hunk 1]
```diff
@@ -374,13 +374,15 @@ func (o *ImportImageOptions) createImageImport() (*imageapi.ImageStream, *imagea
 		},
 		Spec: imageapi.ImageStreamImportSpec{Import: true},
 	}
+	insecureAnnotation := stream.Annotations[imageapi.InsecureRepositoryAnnotation]
+	insecure := o.Insecure || insecureAnnotation == "true"
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: If a user passes `oc import-image --insecure=false`, should that take priority over the image stream?  Why or why not?

Comment (soltysh) [inline pkg/cmd/cli/cmd/importimage.go]: For why not - no opinions. For why yes - because that's what we do everywhere else, the flag has higher precedence than what's already there. I'll prepare an update to that...

**Comment by soltysh** [comment]
@smarterclayton added the precedence you've asked for, ptal.

File: pkg/cmd/cli/cmd/importimage.go [hunk 2]
```diff
@@ -40,15 +40,15 @@ func NewCmdImportImage(fullName string, f *clientcmd.Factory, out io.Writer) *co
...
+			kcmdutil.CheckErr(opts.Complete(f, cmd, args, out))
 			kcmdutil.CheckErr(opts.Validate(cmd))
 			kcmdutil.CheckErr(opts.Run())
 		},
 	}
 	cmd.Flags().StringVar(&opts.From, "from", "", "A Docker image repository to import images from")
 	cmd.Flags().BoolVar(&opts.Confirm, "confirm", false, "If true, allow the image stream import location to be set or changed")
 	cmd.Flags().BoolVar(&opts.All, "all", false, "If true, import all tags from the provided source on creation or if --from is specified")
-	cmd.Flags().BoolVar(&opts.Insecure, "insecure", false, "If true, allow importing from registries that have invalid HTTPS certificates or are hosted via HTTP")
+	opts.Insecure = cmd.Flags().Bool("insecure", false, "If true, allow importing from registries that have invalid HTTPS certificates or are hosted via HTTP")
```
Comment (pweil-) [inline pkg/cmd/cli/cmd/importimage.go]: why use this syntax if you're checking later if the flag was changed and setting it to nil?  You're effectively going to get the same thing as `.BoolVar(opts.Insecure, "insecure", false,...)` right?

File: pkg/cmd/cli/cmd/importimage.go [hunk 3]
```diff
@@ -75,11 +75,15 @@ type ImportImageOptions struct {
 
 // Complete turns a partially defined ImportImageOptions into a solvent structure
 // which can be validated and used for aa import.
-func (o *ImportImageOptions) Complete(f *clientcmd.Factory, args []string, out io.Writer) error {
+func (o *ImportImageOptions) Complete(f *clientcmd.Factory, cmd *cobra.Command, args []string, out io.Writer) error {
 	if len(args) > 0 {
 		o.Target = args[0]
 	}
 
+	if !cmd.Flags().Lookup("insecure").Changed {
```
Comment (pweil-) [inline pkg/cmd/cli/cmd/importimage.go]: this probably deserves a comment about the image stream annotation and precedence

File: pkg/cmd/cli/cmd/importimage.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: Yeah, you need to be checking whether the flag is set in Complete() and resetting it (or create a new boolean to track the user provided value).

**Comment by soltysh** [comment]
@pweil- @smarterclayton comments addressed. ptal

**Comment by pweil-** [comment]
LGTM

**Comment by smarterclayton** [comment]
Needs update

File: pkg/cmd/cli/cmd/importimage.go (hunk 2 above)
Comment (soltysh) [inline pkg/cmd/cli/cmd/importimage.go]: Just for clarity, that syntax is to prevent those NPE I'm getting right now in tests ;)

**Comment by soltysh** [comment]
@smarterclayton @pweil- updated

**Comment by soltysh** [comment]
@smarterclayton last call and if I don't hear from you I assume you're ok with merging this as is.

**Comment by smarterclayton** [comment]
Paul had an outstanding comment

**Comment by soltysh** [comment]
That comment is addressed within the flag description and inside the actual code where the actual assignment happens.

**Comment by smarterclayton** [comment]
Lgtm [merge]
