### PR TITLE
Error when test-cmd is given an invalid regex

### LINKED ISSUE #7004: `hack/test-cmd.sh` fails when bad regex is given
For example:
```
$ hack/test-cmd.sh sdfkjsdf
!!! Error in hack/test-cmd.sh:57
	'tests=($(find_tests ${1:-.*}))' exited with status 1
Call stack:
	1: hack/test-cmd.sh:57 main(...)
Exiting with status 1
```

If the API we have is "give us a regex and we run any matching buckets" this type of input should result in no buckets being run, but not this failure.

### PR DESCRIPTION
**Pull request by enj**
Fixes #7004

xref #10201 

@stevekuznetsov Can you give me some examples that break `test-go` and `test-extended-conformance`?

### CODE REVIEW

File: hack/test-cmd.sh [hunk 1]
```diff
@@ -78,9 +84,15 @@ set -e
 
 function find_tests {
   find "${OS_ROOT}/test/cmd" -name '*.sh' -not -wholename '*images_tests.sh' | grep -E "${1}" | sort -u
+  exit 0
```
Comment (enj) [inline hack/test-cmd.sh]: @stevekuznetsov Any idea why this is needed?

**Comment by stevekuznetsov** [comment]
Changes from @csrwng in another PR will fix extended tests. Don't worry about those.

File: hack/test-cmd.sh (hunk 1 above)
Comment (stevekuznetsov) [inline hack/test-cmd.sh]: No, why did you insert it? Best practice is to never `exit` in a function - always `return`

File: hack/test-cmd.sh [hunk 2]
```diff
@@ -78,9 +84,15 @@ set -e
 
 function find_tests {
   find "${OS_ROOT}/test/cmd" -name '*.sh' -not -wholename '*images_tests.sh' | grep -E "${1}" | sort -u
```
Comment (stevekuznetsov) [inline hack/test-cmd.sh]: Rewrite this in a `for` loop (think you're not using Bash, but a normal language) and the case where you have no tests accumulated to print should be easy to detect right here (and `return` non zero)

**Comment by stevekuznetsov** [comment]
I'm fairly certain `hack/test-go.sh` breaks when you specify a directory that doesn't exist or one without any tests in it.

File: hack/test-cmd.sh (hunk 2 above)
Comment (enj) [inline hack/test-cmd.sh]: If I returned a non-zero code from the function, then the script will terminate and run the `cleanup` function.  How would I propagate the `no_test_error` or something equivalent in that case?

**Comment by enj** [comment]
@stevekuznetsov So how would you change any of the cases below?

```
$ hack/test-go.sh fdlasjfjlshf
can't load package: package github.com/openshift/origin/fdlasjfjlshf: cannot find package "github.com/openshift/origin/fdlasjfjlshf" in any of:
	/home/mkhan/.gvm/gos/go1.7/src/github.com/openshift/origin/fdlasjfjlshf (from $GOROOT)
	/home/mkhan/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/fdlasjfjlshf (from $GOPATH)
[ERROR] PID 6228: hack/test-go.sh:291: `go test ${gotest_flags} ${test_packages}` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/test-go.sh:291: `go test ${gotest_flags} ${test_packages}`
[INFO]   Exiting with code 1.
hack/test-go.sh failed after 0 seconds
```

```
$ hack/test-go.sh api
can't load package: package github.com/openshift/origin/api: no buildable Go source files in /home/mkhan/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/api
[ERROR] PID 6632: hack/test-go.sh:291: `go test ${gotest_flags} ${test_packages}` exited with status 1.
[INFO] 		Stack Trace: 
[INFO] 		  1: hack/test-go.sh:291: `go test ${gotest_flags} ${test_packages}`
[INFO]   Exiting with code 1.
hack/test-go.sh failed after 0 seconds
```

```
$ hack/test-go.sh cmd
?   	github.com/openshift/origin/cmd	[no test files]
hack/test-go.sh succeeded after 2 seconds
```

```
$ hack/test-go.sh pkg/cmd/cli/secrets
ok  	github.com/openshift/origin/pkg/cmd/cli/secrets	1.057s	coverage: 17.6% of statements
hack/test-go.sh succeeded after 56 seconds
```

**Comment by stevekuznetsov** [comment]
> how would you change any of the cases below

`go test` handles them well, no changes necessary

File: hack/test-cmd.sh (hunk 2 above)
Comment (stevekuznetsov) [inline hack/test-cmd.sh]: If no tests are selected, the user made a mistake in 99% of cases. Handling that with a nice `os::log::error` and a failure seems fine to me.

Comment (enj) [inline hack/test-cmd.sh]: That I 100% agree with, but do you want me to rewrite `cleanup` so that it can be called basically from the start of the script so you don't get undeclared variable errors?

Comment (stevekuznetsov) [inline hack/test-cmd.sh]: Ah - I see what you mean. `cleanup` (and `cleanup_openshift`) should both run with `set +e` for now. This is not particularly great, but since they're best-effort cleanups we can let it slide until a refactor. A correct implementation would, as you say, check before jumping and not fail if things are unset. That being said, that's out of scope for this PR. Having a nice error message come out from this logic that happens to trigger cleanup as well is OK.

**Comment by enj** [comment]
[test]

**Comment by enj** [comment]
@stevekuznetsov PTAL

File: hack/util.sh [hunk 3]
```diff
@@ -740,7 +740,7 @@ function os::log::warn() {
 readonly -f os::log::warn
 
 function os::log::error() {
-  os::log::with-severity "${1}" "ERROR"
+  os::log::with-severity "${1}" "ERROR" 1>&2
```
Comment (stevekuznetsov) [inline hack/util.sh]: We wanted this on `warn` too, right?

Comment (enj) [inline hack/util.sh]: Done.

File: hack/test-cmd.sh [hunk 4]
```diff
@@ -76,8 +76,24 @@ trap "cleanup" EXIT
...
+        if grep -q -E "${test_regex}" <<< "${test}"; then
+            selected_tests+=( "${test}" )
+        fi
+    done
+
+    if [[ "${#selected_tests[@]}" -eq 0 ]]; then
+        os::log::error "No tests were selected due to invalid regex."
+        return 1
+    else
+        printf '%s\n' "${selected_tests[@]}" | sort -u
```
Comment (stevekuznetsov) [inline hack/test-cmd.sh]: Can we confirm `sort -u <<<"${selected_tests[@]}"` doesn't do what we want? The `printf` is an artifact of something in the other pull.

Comment (stevekuznetsov) [inline hack/test-cmd.sh]: Actually I'm not sure we need sorting or deduping here, can probably just `echo "${selected_tests[@]}"`

Comment (enj) [inline hack/test-cmd.sh]: Yeah I guess it's not possible for there to be duplicates in that list.

**Comment by stevekuznetsov** [comment]
tests green, LGTM [merge]
