### PR TITLE
Fix auth checks for cross-repo mount requests

### LINKED ISSUE #9540: Push regression with new registry
With the new registry 2.4 (about to land with #8938) and docker 1.10+ a feature called cross-repo mount is utilized during image push. It works like this:

- docker keeps a database of source references for each blob
  - it is updated whenever a blob is downloaded from a any registry/repository or successfully pushed to a new one
- when pushing a blob *B* to a repository *R*/*foo* while a mapping between the blob and another repository *bar* in the same registry *R* exists, it will set headers requesting to mount the blob from repository *bar* to repository *foo*
  - registry verifies the blob exists in repository *bar* and returns a special response saying "mounted"
  - docker then doesn't need to re-upload the blob, resulting in a significant speed-up

The problem is that on registry's side an authorization check is done both for target (*foo*) and source repository (*bar*). Docker daemon expects that if it already owns a blob coming from some registry, any other user requesting to push the blob back to it is authorized to access previously registered location.

This means we will be broken in cases like:

1. *bob* tags `docker.io/foo:v1` to image stream `foo` in project *P*
2. he uses the `foo` as a base image to build his new application *app*
3. docker pulls it, a new layer is added on top and pushed to internal registry
4. another user *alice* (or even *bob* himself) tags `docker.io/foo:v1` to image stream `foo` in another project *P2*
5. same as step 2
6. docker repulls the `docker.io/foo:v1` (no change), adds a new layer on top and pushes to internal registry
  - this fails because a cross repo mount from repository `P/foo` is requested and `system:serviceaccount:P2:builder` isn't authorized to access layers from namespace `P`

This used to work before so it's a **regression**.

##### Version
once the #8938 lands

##### Proposed solution
In our `auth.go` module when asked for access to `repository:pull:foo`, determine from context whether the request wants to push with a blob cross-repo mounted from `foo`. If yes, allow it unconditionally.

Related to #6841

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #9540

When pushing blobs to a target repo `t`, clients may request the server mount a blob from a source repo `s` as an optimization. Before allowing that, the server authorizes the following permissions:

* `pull` and `push` on `t`
* `pull` on `s`

In cases where the user is not authorized to `pull` from `s`, rather than an authorization error, the blob push should just proceed unoptimized (allowing the user to push the full content of the blob to `t`, which proves they have access to it, since they just pushed it)

This PR:

* detects if `pull` access check failures are likely to be related to cross-repo mounts:
  * there was no `push` access request for the repo which failed the `pull` access check
  * there was at least one `push` access request for some other repo (which is required to pass)
* adds errors related to those `pull` access checks to the request context, keyed by repo (ns+name)
* updates the blobstore, tagregistry, and manifestregistry to check the request context for access errors for the relevant repo before performing any action
* updates the blobstore `Create` method to disable cross-repo mounting if the request context contains an access error for the source repo

### CODE REVIEW

**Comment by miminar** [comment]
I like it! Thanks. I'll cherry-pick to my #9582.

File: pkg/dockerregistry/server/auth.go [hunk 1]
```diff
@@ -197,7 +237,11 @@ func (ac *AccessController) Authorized(ctx context.Context, accessRecords ...reg
 				verifiedPrune = true
 			default:
 				if err := verifyImageStreamAccess(ctx, imageStreamNS, imageStreamName, verb, osClient); err != nil {
-					return nil, ac.wrapErr(err)
+					if verb == "pull" {
```
Comment (miminar) [inline pkg/dockerregistry/server/auth.go]: I don't see a possibility for the `verb` be set to `"pull"`.

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 2]
```diff
@@ -183,12 +183,20 @@ func getBoolOption(name string, defval bool, options map[string]interface{}) boo
...
+	}
+
 	if r.ctx == ctx {
 		return r, nil
 	}
 	repo := repository(*r)
 	repo.ctx = ctx
-	return &repo, nil
+
+	return &errorManifestService{
```
Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: Repository itself is a manifest service, no need to wrap it.

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 3]
```diff
@@ -183,12 +183,20 @@ func getBoolOption(name string, defval bool, options map[string]interface{}) boo
 
 // Manifests returns r, which implements distribution.ManifestService.
 func (r *repository) Manifests(ctx context.Context, options ...distribution.ManifestServiceOption) (distribution.ManifestService, error) {
+	if err := r.checkPendingErrors(ctx); err != nil {
```
Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: Let's propagate the evaluation to leaves. We'll want to decide what to do with them in individual methods like `blobStore.Get()` (don't authorize against namespace but rather see if mounted blob is present there).

Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: yeah, forgot to remove this once I created the error manifest wrapper

File: pkg/dockerregistry/server/repositorymiddleware.go (hunk 2 above)
Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: got it

File: pkg/dockerregistry/server/auth.go [hunk 4]
```diff
@@ -21,6 +21,19 @@ import (
 	imageapi "github.com/openshift/origin/pkg/image/api"
 )
 
+type deferredErrors map[string]error
+
+func (d deferredErrors) Add(namespace string, name string, err error) {
+	d[namespace+"/"+name] = err
```
Comment (miminar) [inline pkg/dockerregistry/server/auth.go]: I'd rather define `(*repository).Name()` returning `string` and go without helpers.

File: pkg/dockerregistry/server/auth.go [hunk 5]
```diff
@@ -61,6 +74,27 @@ func UserClientFrom(ctx context.Context) (client.Interface, bool) {
...
+	return ok && authPerformed
+}
+
+const deferredErrorsKey = "openshift.auth.deferredErrors"
+
+func WithDeferredErrors(parent context.Context, errs deferredErrors) context.Context {
+	return context.WithValue(parent, deferredErrorsKey, errs)
+}
+func DeferredErrorsFrom(ctx context.Context) (deferredErrors, bool) {
+	errs, ok := ctx.Value(authPerformedKey).(deferredErrors)
```
Comment (miminar) [inline pkg/dockerregistry/server/auth.go]: `s/authPerformedKey/deferredErrorsKey/`

File: pkg/dockerregistry/server/auth.go (hunk 4 above)
Comment (liggitt) [inline pkg/dockerregistry/server/auth.go]: I want to make sure we're working with the ns and name

**Comment by miminar** [comment]
LGTM

**Comment by liggitt** [comment]
[test]
[testextended][extended:core(builds)]
[testextended][extended:core(images)]

**Comment by liggitt** [comment]
[testextended][extended:core(builds)]

**Comment by liggitt** [comment]
[testextended][extended:core(images)]

**Comment by liggitt** [comment]
[merge]

**Comment by liggitt** [comment]
fyi @smarterclayton

**Comment by liggitt** [comment]
Re[test] #9512

File: pkg/dockerregistry/server/auth.go [hunk 6]
```diff
@@ -197,7 +237,11 @@ func (ac *AccessController) Authorized(ctx context.Context, accessRecords ...reg
 				verifiedPrune = true
 			default:
 				if err := verifyImageStreamAccess(ctx, imageStreamNS, imageStreamName, verb, osClient); err != nil {
-					return nil, ac.wrapErr(err)
+					if access.Action == "pull" {
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/auth.go]: Nit: invert and return early
