### PR TITLE
oc start-build --from-repo now uses clone+checkout

### LINKED ISSUE #8922: oc start-build --from-repo does not clone submodules
Similar to https://github.com/openshift/origin/issues/5910 which got fixed - builds from a URL will clone submodules, but builds from a local git repo won't (even though the submodule code is remote).
##### Steps To Reproduce

Create the following build:

```
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: logging-auth-proxy
  name: logging-auth-proxy
spec:
  output:
    to:
      kind: ImageStreamTag
      name: logging-auth-proxy:latest
  resources: {}
  source:
    git:
      uri: https://github.com/sosiouxme/origin-aggregated-logging
      ref: issue-example-build-from-repo-submodule
    contextDir: deployer/common/openshift-auth-proxy
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: library/node:0.10.36
    type: Docker
```
1. oc start-build --follow
2. git clone --recursive https://github.com/sosiouxme/origin-aggregated-logging -b issue-example-build-from-repo-submodule /tmp/foo
3. oc start-build --follow --from-dir=/tmp/foo
4. oc start-build --follow --from-repo=/tmp/foo
##### Current Result

1 and 3 work, 4 fails because of missing submodule
##### Expected Result

All work - when given a local git repo in 4, should at least attempt to clone submodules. If the submodule isn't accessible, it's obviously fine for the clone to fail and just continue the build without it (as in current behavior).

### PR DESCRIPTION
**Pull request by oatmealraisin**
This allows us to handle submodules.  However, it takes up a bit more
resources.  This shouldn't be a problem - even the Linux kernel only
took about 3 seconds to clone to another local directory.

Fixes #8922 
@bparees @sosiouxme ptal?

### CODE REVIEW

**Comment by oatmealraisin** [comment]
[test]

File: pkg/cmd/cli/cmd/startbuild.go [hunk 1]
```diff
@@ -479,31 +479,53 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
...
+				}
+				defer os.RemoveAll(tempDirectory)
+
+				// We only want to grab the contents of the specified commit, with
+				// submodules included
+				cloneOptions := git.CloneOptions{
+					Recursive: true,
+					Shallow:   false,
+					// TODO: Should we output this at a loglevel?  If so, what level?
+					Quiet: true,
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: let's say loglevel 3 and above.

File: pkg/cmd/cli/cmd/startbuild.go [hunk 2]
```diff
@@ -479,31 +479,53 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
...
+				}
+
+				// Clone the repository to a temp directory for future tar-ing
+				if err := repo.CloneWithOptions(tempDirectory, clean, cloneOptions); err != nil {
+					return nil, err
+				}
+				if err := repo.Checkout(tempDirectory, options.Commit); err != nil {
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: you've already got "commit" defined above, might as well use it.

what is the behavior here if "commit" is an empty string?

File: pkg/cmd/cli/cmd/startbuild.go [hunk 3]
```diff
@@ -479,31 +479,53 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
...
+					return nil, err
+				}
+				if err := os.RemoveAll(filepath.Join(tempDirectory, ".git")); err != nil {
+					return nil, err
+				}
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: doesn't this need to be a defer?  it looks like you're wiping out the local temp dir before you actually stream it anywhere.

File: pkg/cmd/cli/cmd/startbuild.go (hunk 2 above)
Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: Will change it to 'commit', I meant that one but must have gotten them mixed up when coding.

commit is by default set to HEAD, so we can't have an empty string.  If we have an incorrect commit, line 503 should return an error

File: pkg/cmd/cli/cmd/startbuild.go [hunk 4]
```diff
@@ -462,7 +462,7 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
 			if len(options.Commit) > 0 {
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: so this check is pointless?

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: ah, sorry, the critical line was hidden from me, i see now.

File: pkg/cmd/cli/cmd/startbuild.go (hunk 3 above)
Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: I figured this is the part that would have the most memory usage.  Since we didn't use it with `git archive` before, I didn't think the directory was necessary.

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: git archive was streaming the archive output directly to the tar stream.  you're not doing that.  near as i can tell this code is:
1) copying the repo to a tempdir
2) deleting that tempdir
3) tar streaming the tempdir (which doesn't exist anymore)

am i missing something?

File: pkg/cmd/cli/cmd/startbuild.go [hunk 5]
```diff
@@ -479,31 +479,56 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
...
-						pw.CloseWithError(io.EOF)
-					}
-				}()
-				r = pr
 			}
+
+			pr, pw := io.Pipe()
+			go func() {
+				w := gzip.NewWriter(pw)
+				if err := tar.New().CreateTarStream(path, false, w); err != nil {
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: also isn't this tarring the wrong directory in the repo case?  shouldn't it be "clean" or "tempDirectory" that you stream, not "path" (which was the original repo directory, not the properly cloned+commit-checked-out directory)

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: (which is why the code is not streaming an empty dir like i thought it was, it's streaming the wrong dir instead)

File: pkg/cmd/cli/cmd/startbuild.go (hunk 3 above)
Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: My intent is to delete the .git directory (with all of the historical blobs and whatnot)
Is it not doing that?  I use filepath.Join() within the os.RemoveAll

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: sorry you're correct that you're only deleting the .git directory, but regardless:
1) you need to clean up the entire temp directory when you're done streaming the content, we can't leave junk around
2) i don't think you're streaming the right directory (the tempdirectory) right now.

Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: Yes you're right, I'm streaming the wrong directory, fixing it asap.  Is the defer RemoveAll on line 488 not cleaning the temp directory?

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: >  Is the defer RemoveAll on line 488 not cleaning the temp directory?

yes it is, sorry my bad.  Saw the removall down here and assumed that was how you were cleaning up, didn't read it carefully enough.

Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: All fine haha I can't believe I missed the path/clean error further on

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: however the defer is probably a bad idea because we could return while the go routine is still running.  you need to use a channel to ensure the go routine finished before the cleanup happens, something like:
defer func(){ <- waitForStream ; cleanup; }

and of course then you also need to make sure the waitForStream eventually happens, so you need some additional error handling.

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: actually not sure how you safely do this at all since the stream is being created here, but not consumed here.

Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: On line 540, I believe the directory gets consumed?  I may be wrong, but it looks like that method does the job of tar-ing the directory.  Would this make it safe to delete afterwards?

Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: it creates a stream, it's not clear to me that means the directory has been fully read into that stream. you will have to do some testing to confirm.

**Comment by oatmealraisin** [comment]
So I think (hope) I've proven that the code is safe to delete as is.  Using the code in the original as the test case, we can show that this code runs fine.  
```
oc start-build logging-auth-proxy --follow --from-dir /tmp/foo
Uploading directory "/tmp/foo" as binary input for the build ...
logging-auth-proxy-1
warning: OpenShift server version "v1.3.0-alpha.2+f2b7fdd-dirty" differs from this image "v1.3.0-alpha.2"
Receiving source from STDIN as archive ...
Step 1 : FROM library/node:0.10.36
 ---> 600febd9d7b6
Step 2 : MAINTAINER Luke Meyer <lmeyer@redhat.com>
 ---> Using cache
 ---> d980df35d93f
Step 3 : ENTRYPOINT openshift-auth-proxy
 ---> Using cache
 ---> 3396f4e65132
Step 4 : COPY . /opt/openshift-auth-proxy
 ---> Using cache
 ---> 824a983cf3a7
Step 5 : RUN cd /opt/openshift-auth-proxy     && npm install -g .
 ---> Using cache
 ---> 649992ed0d05
Step 6 : ENV "OPENSHIFT_BUILD_NAME" "logging-auth-proxy-1" "OPENSHIFT_BUILD_NAMESPACE" "default"
 ---> Using cache
 ---> 5a874cec0111
Step 7 : LABEL "io.openshift.build.source-context-dir" "deployer/common/openshift-auth-proxy"
 ---> Using cache
 ---> c9e91c6676a7
Successfully built c9e91c6676a7
Pushing image 172.30.154.146:5000/default/logging-auth-proxy:latest ...
Push successful
```

However, it would probably still run fine if there was no code in the directory.  So we change the line at 504 to `os.RemoveAll(os.Join(tempDirectory, "deployer", "common))`, which contains the files that were not being copied originally.  Without these, the build would fail.

On running this code, we get the same output as before:
```
oc start-build logging-auth-proxy --follow --from-dir /tmp/foo
Uploading directory "/tmp/foo" as binary input for the build ...
logging-auth-proxy-1
warning: OpenShift server version "v1.3.0-alpha.2+f2b7fdd-dirty" differs from this image "v1.3.0-alpha.2"
Receiving source from STDIN as archive ...
Step 1 : FROM library/node:0.10.36
 ---> 600febd9d7b6
Step 2 : MAINTAINER Luke Meyer <lmeyer@redhat.com>
 ---> Using cache
 ---> d980df35d93f
Step 3 : ENTRYPOINT openshift-auth-proxy
 ---> Using cache
 ---> 3396f4e65132
Step 4 : COPY . /opt/openshift-auth-proxy
 ---> Using cache
 ---> 824a983cf3a7
Step 5 : RUN cd /opt/openshift-auth-proxy     && npm install -g .
 ---> Using cache
 ---> 649992ed0d05
Step 6 : ENV "OPENSHIFT_BUILD_NAME" "logging-auth-proxy-1" "OPENSHIFT_BUILD_NAMESPACE" "default"
 ---> Using cache
 ---> 5a874cec0111
Step 7 : LABEL "io.openshift.build.source-context-dir" "deployer/common/openshift-auth-proxy"
 ---> Using cache
 ---> c9e91c6676a7
Successfully built c9e91c6676a7
Pushing image 172.30.154.146:5000/default/logging-auth-proxy:latest ...
Push successful
```

Great, but it still may be empty and succeeding.  So we move line 504 to 532, immediately after the clone, before the tar.

Running this code, we get a failure:
```
oc start-build logging-auth-proxy --follow --from-repo /tmp/foo
Uploading "/tmp/foo" at commit "HEAD" as binary input for the build ...
logging-auth-proxy-4
warning: OpenShift server version "v1.3.0-alpha.2+f2b7fdd-dirty" differs from this image "v1.3.0-alpha.2"
Receiving source from STDIN as archive ...
error: build error: open /tmp/docker-build124180944/deployer/common/openshift-auth-proxy/Dockerfile: no such file or directory
```

This should be because we have deleted the content before the tar-ing takes place.

@bparees ptal?

File: pkg/cmd/cli/cmd/startbuild.go [hunk 6]
```diff
@@ -474,36 +475,78 @@ func streamPathToBuild(git git.Repository, in io.Reader, out io.Writer, client o
...
+					pw.CloseWithError(err)
+				} else {
+					w.Close()
+					pw.CloseWithError(io.EOF)
+				}
+				transferFinished <- false
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: why not true?  (I realize you're doing nothing w/ the value, but true seems more sensible.  or better still, the value of "err"

Comment (oatmealraisin) [inline pkg/cmd/cli/cmd/startbuild.go]: I could change it to true, but the only effect that I wanted was to send a signal through to indicating that a deletion is OK.  I don't think we should do error handling on the other side of the channel, because it is specifically for garbage collection.

**Comment by bparees** [comment]
Marking 1.4 because i don't think we want to risk this change in 1.3 at this point.

**Comment by bparees** [comment]
@oatmealraisin needs a rebase

**Comment by oatmealraisin** [comment]
@bparees Rebased

File: pkg/cmd/cli/cmd/startbuild.go [hunk 7]
```diff
@@ -488,36 +491,78 @@ func streamPathToBuild(repo git.Repository, in io.Reader, out io.Writer, client
...
 				go func() {
-					if err := repo.Archive(clean, options.Commit, "tar.gz", pw); err != nil {
-						pw.CloseWithError(fmt.Errorf("unable to create Git archive of %q for build: %v", clean, err))
-					} else {
-						pw.CloseWithError(io.EOF)
+					timeout := 300 * time.Second
+					select {
+					case <-transferFinished:
+					case <-time.After(timeout):
+						glog.Warning("Transferring directory %q timed out after %q seconds.", clean, timeout.Seconds())
```
Comment (bparees) [inline pkg/cmd/cli/cmd/startbuild.go]: is there really a need for this?  the previous iteration of the code didn't worry about the timeout case.  can you just move the removeAll down below where the transfer actually happens, with a flag to indicate if you should removeall (because you cloned to a tempdir) or not removeall (because you just uploaded from a dir the user specified)

**Comment by bparees** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
[test]

**Comment by oatmealraisin** [comment]
I believe there was a flake, #9548 

@bparees I changed to a boolean flag, ptal?

**Comment by bparees** [comment]
the change looks good to me, but you've been victimized by your other pull merging:

```
++ Building go targets for linux/amd64: cmd/oc
# github.com/openshift/origin/pkg/cmd/cli/cmd
pkg/cmd/cli/cmd/startbuild.go:512: undefined: "github.com/openshift/origin/pkg/generate/git".CloneOptions
```

so you'll need to rework that code.

**Comment by oatmealraisin** [comment]
@bparees Yep just noticed that, I'm on it

**Comment by oatmealraisin** [comment]
Flake #9548 

[test]

**Comment by oatmealraisin** [comment]
Flake #9457, [test]

**Comment by bparees** [comment]
@oatmealraisin pretty sure the extended test failure is caused by these changes, it's not a known flake.

**Comment by oatmealraisin** [comment]
@bparees Yes sorry, I'm working on the Jenkins PR atm

**Comment by oatmealraisin** [comment]
[test]

**Comment by oatmealraisin** [comment]
[test]

**Comment by oatmealraisin** [comment]
Flake #11517 , [test]

**Comment by oatmealraisin** [comment]
@bparees I've gotten the extended tests working, ptal?

**Comment by oatmealraisin** [comment]
@bparees The code will search upwards for the root dir.  I'm having trouble testing locally, don't know if this will pass, but ptal?

File: test/extended/builds/start.go [hunk 8]
```diff
@@ -127,17 +131,20 @@ var _ = g.Describe("[builds][Slow] starting a build using CLI", func() {
 
 		g.It("should accept --from-repo with --commit as input", func() {
 			g.By("starting the build with a Git repository")
-			// NOTE: This actually takes the commit from the origin repository. If the
-			// test-build-app changes, this commit has to be bumped.
-			br, err := exutil.StartBuildAndWait(oc, "sample-build", "--commit=f0f3834", fmt.Sprintf("--from-repo=%s", exampleBuild))
+			gitCmd := exec.Command("git", "rev-parse", "HEAD")
```
Comment (bparees) [inline test/extended/builds/start.go]: do HEAD~1 so we're not just building HEAD.  otherwise the git commit matching check later is suspect.

Comment (oatmealraisin) [inline test/extended/builds/start.go]: Would a tag be better? That way it doesn't change at all

Comment (bparees) [inline test/extended/builds/start.go]: also if someone does break this w/ a commit to origin we probably want to know

**Comment by oatmealraisin** [comment]
Flake #11406, [test]

**Comment by oatmealraisin** [comment]
Waiting for Custom Build Strategy fix

**Comment by bparees** [comment]
@oatmealraisin please squash in the meantime.

**Comment by bparees** [comment]
@oatmealraisin i'm comfortable w/ merging this based on the only failure being a known issue, once you squash.

**Comment by oatmealraisin** [comment]
@bparees Roger that, squashing

**Comment by bparees** [comment]
[merge]

**Comment by oatmealraisin** [comment]
Still getting hit by custom builds

**Comment by bparees** [comment]
@oatmealraisin you're in the merge queue.

**Comment by bparees** [comment]
and @coreydaley is working on the custom build strategy failures.

**Comment by oatmealraisin** [comment]
@bparees Roger, just posting that I haven't abandoned the PR :eye: :eye:
