### PR TITLE
Check for forbidden error on ImageStreamImport client

### LINKED ISSUE #6836: new-build regression
## One week ago

```
$ git checkout master@{one.week.ago}
$ make clean build
rm -rf _output Godeps/_workspace/pkg
hack/build-go.sh 
++ Building go targets for linux/amd64: cmd/openshift cmd/oc
++ Placing binaries
hack/build-go.sh took 52 seconds
```

```
[vagrant@localhost origin]$ oc new-build -D'FROM busybox' --to busy
--> Found Docker image c1bc9b4 (10 days old) from Docker Hub for "busybox"
    * An image stream will be created as "busybox:latest" that will track the source image
    * A Docker build using a predefined Dockerfile will be created
      * The resulting image will be pushed to image stream "busy:latest"
      * Every time "busybox:latest" changes a new build will be triggered
--> Creating resources with label build=busy ...
    ImageStream "busybox" created
    ImageStream "busy" created
    BuildConfig "busy" created
--> Success
    Build configuration "busy" created and build triggered.
    Run 'oc logs -f bc/busy' to stream the build progress.
```

## Today

```
[vagrant@localhost origin]$ oc new-build -D'FROM busybox' --to busy
error: only a partial match was found for "busybox": "busybox"
```

### PR DESCRIPTION
**Pull request by csrwng**
The fallback for the ImageStreamImport searcher in new-app/new-build is not working with a server version v1.1.1 and a newer client. Because the resource exists but is not exposed through policy, the request will return a 403. Added a 403 check to return an ErrImageStreamImportUnsupported error so the fallback can occur.

Fixes #6836

### CODE REVIEW

**Comment by csrwng** [comment]
@smarterclayton @rhcarvalho

File: pkg/client/imagestreams.go [hunk 1]
```diff
@@ -131,12 +132,12 @@ func transformUnsupported(err error) error {
...
 		return nil
 	}
-	if apierrs.IsNotFound(err) {
+	if apierrs.IsNotFound(err) || apierrs.IsForbidden(err) {
 		status, ok := err.(kclient.APIStatus)
 		if !ok {
 			return ErrImageStreamImportUnsupported
 		}
-		if status.Status().Details == nil || status.Status().Details.Kind == "" {
+		if status.Status().Code == http.StatusForbidden || status.Status().Details == nil || status.Status().Details.Kind == "" {
```
Comment (smarterclayton) [inline pkg/client/imagestreams.go]: Put this into it's if block and add a comment

Comment (smarterclayton) [inline pkg/client/imagestreams.go]: Also add a test :)

Comment (smarterclayton) [inline pkg/client/imagestreams.go]: There is an integration test or unit test that verifies this somewhere

**Comment by csrwng** [comment]
fixed and added test

File: pkg/client/imagestreams.go [hunk 2]
```diff
@@ -140,5 +140,12 @@ func transformUnsupported(err error) error {
 			return ErrImageStreamImportUnsupported
 		}
 	}
+	// The ImageStreamImport resource exists in v1.1.1 of origin but is not yet
+	// enabled by policy. A create request will return a Forbidden(403) error.
+	// We want to return ErrImageStreamImportUnsupported to allow fallback behavior
+	// in clients.
```
Comment (smarterclayton) [inline pkg/client/imagestreams.go]: Also, an admin may just want to forbid import just for normal use.

**Comment by smarterclayton** [comment]
LGTM [merge] thanks

**Comment by smarterclayton** [comment]
I may end up moving this out of this method so that clients have to check it themselves - will come back to this once I sort out the outcome.  We use "ErrImageStreamImportNotSupported" to indicate whether we support "scheduled" or not, so we'll probably need some story.
