### PR TITLE
Issue 2358 - better handling of server url parsing in osc login

### LINKED ISSUE #2358: 'osc login' fails when host includes trailing slash
When a host is provided to `osc login`, either as argument or through the `--server` flag, if a trailing slash is present the login will fail.

```
$ osc login --server=https://localhost:8443/
(...)
Error from server: "/v1beta3/users/~" is forbidden because myself cannot get on /v1beta3/users/~
```

Without a trailing slash it succeeds:

```
$ osc login --server=https://localhost:8443
(...)
Login successful.
``` 

I didn't check the code but it is known that [net/url#Parse](https://golang.org/pkg/net/url/#Parse) is not very smart. We should be smarter about parsing the URL provided - for example, we could (try to) guess the protocol, but currently `--server=localhost:8443` will fail with a "Unable to connect to the server: unsupported protocol scheme localhost" message.

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes #2358.

Notice this only fixes the server url parsing on login. At some point we may want to move `flagtypes.Addr` upstream and change the `--server` flag type to `Addr` instead of `string`.

### CODE REVIEW

**Comment by fabianofranz** [comment]
@deads2k please review.

File: pkg/cmd/cli/cmd/login.go [hunk 1]
```diff
@@ -142,11 +142,15 @@ func (o *LoginOptions) Complete(f *osclientcmd.Factory, cmd *cobra.Command, args
 		o.StartingKubeConfig = kclientcmdapi.NewConfig()
 	}
 
+	addr := flagtypes.Addr{Value: "localhost:8443", DefaultScheme: "https", DefaultPort: 8443, AllowPrefix: false}.Default()
```
Comment (fabianofranz) [inline pkg/cmd/cli/cmd/login.go]: Notice I changed to `AllowPrefix: false` so that we get rid on `/` or whatever path is provided, and only use the scheme/host/port.

**Comment by deads2k** [comment]
I'm pretty sure that paths are supposed to valid as part of the server URL.  Consider the case of someone hiding us behind a proxy or some such thing.

@liggitt Is that your understanding as well?

**Comment by liggitt** [comment]
Not sure... we need openshift and k8s API urls... would we append "/api" and "/osapi" to whatever path they gave us?

**Comment by deads2k** [comment]
I guess we can always loosen if we need to.  lgtm [merge]

**Comment by smarterclayton** [comment]
Path prefixes are allowed

**Comment by deads2k** [comment]
> Path prefixes are allowed

[unmerge]?

**Comment by liggitt** [comment]
remove your merging comment to unmerge

**Comment by deads2k** [comment]
@fabianofranz It seems likely that a URL path that is only "/" is an accident.  I could see stripping that one case.

**Comment by fabianofranz** [comment]
That's what I was afraid of.  :)

----- Original Message -----

**Comment by fabianofranz** [comment]
That, or remove trailing slashes in path no matter its content? /path/to/my/openshift/ => /path/to/my/openshift

----- Original Message -----

**Comment by deads2k** [comment]
> That, or remove trailing slashes in path no matter its content? /path/to/my/openshift/ => /path/to/my/openshift

I wouldn't.  Those are likely to mean something.

**Comment by fabianofranz** [comment]
Yeah, but don't we always append something that starts with "/"? cc @liggitt

----- Original Message -----

**Comment by smarterclayton** [comment]
Although client is very specific about how it handles that (path.Join which removes double slashes)

**Comment by fabianofranz** [comment]
Fixed, so now the only thing we do here is `addr.Path = ""` in case of `addr.Path == "/"`. Also using  `flagtypes.Addr` not only in the arg but also in the flag, so that it's properly validated before we set `o.Server`. @deads2k please review again.

File: pkg/cmd/flagtypes/addr.go [hunk 2]
```diff
@@ -106,6 +106,8 @@ func (a *Addr) Set(value string) error {
 
 	if !a.AllowPrefix {
 		addr.Path = ""
+	} else if addr.Path == "/" {
```
Comment (smarterclayton) [inline pkg/cmd/flagtypes/addr.go]: The behavior of url Parse is to always set this I believe.  I'm not sure we should be clearing it here.

Comment (fabianofranz) [inline pkg/cmd/flagtypes/addr.go]: url Parse doesn't change it, so it's only there if it's in the original string.

----- Original Message -----

Comment (smarterclayton) [inline pkg/cmd/flagtypes/addr.go]: Hrm - I don't really want to clear it here - what if someone else needs it?  Why clear it here?

----- Original Message -----

Comment (fabianofranz) [inline pkg/cmd/flagtypes/addr.go]: It's important to normalize the original value we get, so it doesn't result in duplicates in config depending on how it was provided to the command, for example.

Comment (smarterclayton) [inline pkg/cmd/flagtypes/addr.go]: I'm not sure that's what flagtype.Addr is for.

----- Original Message -----

Comment (fabianofranz) [inline pkg/cmd/flagtypes/addr.go]: Because of the original issue - https://github.com/openshift/origin/issues/2358. It happens exactly when there is a trailing slash in the host.

----- Original Message -----

Comment (smarterclayton) [inline pkg/cmd/flagtypes/addr.go]: The task of normalizing user input doesn't belong to flagtype.Addr.  It belongs to code that does checks for normalization prior to writing config.

----- Original Message -----

Comment (fabianofranz) [inline pkg/cmd/flagtypes/addr.go]: url Parse is pretty dumb btw (ah nevermind, I think I already said that).  :)

Comment (fabianofranz) [inline pkg/cmd/flagtypes/addr.go]: It fails before the config writing process (when exchanging the token, checking current user, etc). So I probably agree, but we still need to normalize it here in login too.

----- Original Message -----

Comment (smarterclayton) [inline pkg/cmd/flagtypes/addr.go]: In login yes, but this is flagtypes.Addr which is shared by everything.

----- Original Message -----

**Comment by fabianofranz** [comment]
Comments addressed. I no longer change `flagtypes.Addr`, instead we now have a normalizer specifically targeted for configs and how we expect URL's to be stored in there. Runs in login and when building the config in smart_merge. @deads2k @smarterclayton please review.

File: pkg/cmd/cli/config/helpers.go [hunk 3]
```diff
@@ -39,3 +45,59 @@ func RelativizeClientConfigPaths(cfg *clientcmdapi.Config, base string) (err err
...
+
+	// remove trailing slash if that's the only path we have
+	if addr.Path == "/" {
+		addr.Path = ""
+	}
+
+	return addr.String(), nil
+}
+
+func seemsURL(s string) bool {
```
Comment (deads2k) [inline pkg/cmd/cli/config/helpers.go]: rename to `hasScheme`.

File: pkg/cmd/cli/config/helpers.go [hunk 4]
```diff
@@ -39,3 +45,59 @@ func RelativizeClientConfigPaths(cfg *clientcmdapi.Config, base string) (err err
...
+		return "", fmt.Errorf("Not a valid URL: %v", err)
+	}
+
+	// normalize host:port
+	if strings.Contains(addr.Host, ":") {
+		_, port, err := net.SplitHostPort(addr.Host)
+		if err != nil {
+			return "", fmt.Errorf("Not a valid host:port: %v", err)
+		}
+		_, err = strconv.ParseUint(port, 10, 64)
```
Comment (deads2k) [inline pkg/cmd/cli/config/helpers.go]: It's been a while, but shouldn't `bitSize` be 16?

File: pkg/cmd/cli/config/smart_merge.go [hunk 5]
```diff
@@ -97,7 +97,11 @@ func CreateConfig(namespace string, clientCfg *client.Config) (*clientcmdapi.Con
 	config.AuthInfos[userNick] = *credentials
 
 	cluster := clientcmdapi.NewCluster()
-	cluster.Server = clientCfg.Host
+	if normalizedServerURL, err := NormalizeServerURL(clientCfg.Host); err == nil {
```
Comment (deads2k) [inline pkg/cmd/cli/config/smart_merge.go]: `clientCfg.Host` should already be known to work at this point no matter who is calling it.  I think this is unnecessary.

**Comment by deads2k** [comment]
minor comments.  Otherwise, lgtm.

**Comment by fabianofranz** [comment]
Comments addressed, [merge].
