### PR TITLE
fix swagger version reporting

### LINKED ISSUE #15666: Versions in Swagger API "x-kubernetes-group-version-kind" all reporting as "latest"
Since the 1.7 rebase, the version information is missing under "x-kubernetes-group-version-kind" under api/swagger-spec/openshift-openapi-spec.json - instead of reporting things like "version": "v1" (or whatever), everything is coming through as "version": "latest"

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #15666 

It was the change in serialisation of "Version" to "version" under "x-kubernetes-group-version-kind" that made us hit the rogue sed command.

@deads2k fyi

### CODE REVIEW

File: hack/update-generated-swagger-spec.sh [hunk 1]
```diff
@@ -49,7 +49,7 @@ generated_file="${SWAGGER_SPEC_OUT_DIR}/openshift-openapi-spec.json"
 oc get --raw "/swagger.json" --config="${MASTER_CONFIG_DIR}/admin.kubeconfig" > "${generated_file}"
 
 os::util::sed 's|https://127.0.0.1:38443|https://127.0.0.1:8443|g' "${generated_file}"
-os::util::sed -E 's|"version": "[^\"]+"|"version": "latest"|g' "${generated_file}"
+os::util::sed -E '0,/"version":/ s|"version": "[^\"]+"|"version": "latest"|g' "${generated_file}"
```
Comment (bparees) [inline hack/update-generated-swagger-spec.sh]: sorry my sed-fu is not that great, this new prefix does what exactly?

Comment (jim-minter) [inline hack/update-generated-swagger-spec.sh]: Does the first replace in the file then leaves the rest of the instances alone.  "Between lines 0 and the line containing the first match, do the following replace".  `jq` would be better here, but...
