### PR TITLE
Bug 1371511 - add namespace awareness to oadm prune commands

### LINKED ISSUE #9502: oadm prune --namespace=myns does not limit to specified namespace
While working on my pruning image card, I wanted to test the pruning only within my test namespace, but invoking `oadm prune images -n test --loglevel=4` showed me that all namespaces were taken into consideration. Looking at the pruning source code ([builds.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/builds.go#L70), [deployments.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/deployments.go#L70), [images.go](https://github.com/openshift/origin/blob/16bcdd0e49490976c2c942ed90b0de7db757a8cf/pkg/cmd/admin/prune/images.go#L127)) we always use `kapi.NamespaceAll`. The question is should we take namespace into consideration? 

In my opinion, and from talking to @miminar for builds and deployments it's quite straightforward, so yes. Unfortunately for images, it's not that simple, since Images are non-namespaced objects, but others using them (ImageStreams, Pods, ReplicationControllerss, BuildConfigs, Builds, DeploymentConfigs) are. The only problem here is, that we can't be sure if an Image which might be a candidate for pruning in one namespace, might be still used in others. In other words, we would have to look through all namespaces still but remove only from those specified. 

@miminar @smarterclayton @derekwaynecarr @deads2k thoughts?

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #9502 and https://bugzilla.redhat.com/show_bug.cgi?id=1371511.

@miminar ptal

### CODE REVIEW

File: pkg/image/prune/prune_test.go [hunk 1]
```diff
@@ -870,6 +871,28 @@ func TestImagePruning(t *testing.T) {
...
+		"image exceeding limits with namespace specified": {
+			pruneOverSizeLimit: newBool(true),
+			namespace:          "foo",
+			images: imageList(
+				unmanagedImage("id", "otherregistry/foo/bar@id", false, "", ""),
+				sizedImage("id2", registryURL+"/foo/bar@id2", 100, nil),
+				sizedImage("id3", registryURL+"/foo/bar@id3", 200, nil),
+			),
+			streams: streamList(
+				stream(registryURL, "foo", "bar", tags(
```
Comment (miminar) [inline pkg/image/prune/prune_test.go]: One more test having at least two image streams where one belongs to different namespace?

File: pkg/image/prune/prune.go [hunk 2]
```diff
@@ -825,6 +829,10 @@ func (p *pruner) Prune(
 	errs := []error{}
 
 	errs = append(errs, pruneStreams(p.g, prunableImageNodes, streamPruner)...)
+	// if namespace is specified prune only ImageStreams and nothing more
```
Comment (miminar) [inline pkg/image/prune/prune.go]: I'd avoid computing `graphWithoutPrunableImages` and `prunableComponents` if we prune only image streams.

File: pkg/image/prune/prune_test.go (hunk 1 above)
Comment (soltysh) [inline pkg/image/prune/prune_test.go]: It doesn't make sense, since namespace filtering is done when listing objects.

File: pkg/image/prune/prune.go (hunk 2 above)
Comment (soltysh) [inline pkg/image/prune/prune.go]: ok.

File: pkg/image/prune/prune_test.go (hunk 1 above)
Comment (miminar) [inline pkg/image/prune/prune_test.go]: Oh I see, nevermind.

**Comment by soltysh** [comment]
@miminar updated, except for the additional test, as mentioned the filtering is done one layer above. ptal

**Comment by miminar** [comment]
But I would still like to see at least one test that ensures the pruning affects only chosen namespace. Could you please provide integration or cmd test?

**Comment by soltysh** [comment]
Due to some refactoring I had to do to make the code testable I've split that into 2nd commit, ptal

File: pkg/cmd/admin/prune/builds_test.go [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+
+		OSClient: osFake,
+		Out:      ioutil.Discard,
+	}
+
+	if err := opts.Run(); err != nil {
+		t.Errorf("Unexpected error: %v", err)
+	}
+
+	for _, a := range osFake.Actions() {
```
Comment (miminar) [inline pkg/cmd/admin/prune/builds_test.go]: Assert also there's at least on action in Actions list.

File: pkg/cmd/admin/prune/deployments_test.go [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+	if err := opts.Run(); err != nil {
+		t.Errorf("Unexpected error: %v", err)
+	}
+
+	for _, a := range osFake.Actions() {
+		if a.GetNamespace() != "foo" {
+			t.Errorf("Unexpected namespace while pruning %s: %s", a.GetResource(), a.GetNamespace())
+		}
+	}
+	for _, a := range kFake.Actions() {
```
Comment (miminar) [inline pkg/cmd/admin/prune/deployments_test.go]: Same as above.

File: pkg/cmd/admin/prune/images_test.go [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+
+func TestImagePruneNamespaced(t *testing.T) {
+	kFake := ktestclient.NewSimpleFake()
+	osFake := testclient.NewSimpleFake()
+	opts := &PruneImagesOptions{
+		Namespace: "foo",
+
+		OSClient: osFake,
+		KClient:  kFake,
+		Out:      ioutil.Discard,
```
Comment (miminar) [inline pkg/cmd/admin/prune/images_test.go]: Heh nice! Need to remember this one.

File: pkg/cmd/admin/prune/images_test.go [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+	for _, a := range osFake.Actions() {
+		// images are non-namespaced
+		if a.GetResource() == "images" {
+			continue
+		}
+		if a.GetNamespace() != "foo" {
+			t.Errorf("Unexpected namespace while pruning %s: %s", a.GetResource(), a.GetNamespace())
+		}
+	}
+	for _, a := range kFake.Actions() {
```
Comment (miminar) [inline pkg/cmd/admin/prune/images_test.go]: Not empty actions.

**Comment by soltysh** [comment]
@miminar nitpicks also addressed

**Comment by miminar** [comment]
LGTM

**Comment by soltysh** [comment]
[merge]
