### PR TITLE
preserve err type loginoptions

### LINKED ISSUE #17136: GSSAPI extended tests broken due to error type loss
#17073 broke the types of errors returned from `pkg/oc/cli/cmd/login/loginoptions.go`.  This breaks how `pkg/oc/cli/cmd/login/login.go` handles unauthorized errors.

```
=== BEGIN TEST CASE ===
/run/os/gssapi-tests.sh:30: executing 'oc login' expecting failure and text 'Login failed \(401 Unauthorized\)'
FAILURE after 0.460s: /run/os/gssapi-tests.sh:30: executing 'oc login' expecting failure and text 'Login failed \(401 Unauthorized\)': the output content test failed
There was no output from the command.
Standard error from the command:
error: unhandled challenge - verify you have provided the correct host and port and that the server is currently running.
=== END TEST CASE ===
```

### LINKED ISSUE #17150: Login message not shown when login redirects
```
$ oc login
error: not authorized - verify you have provided the correct host and port and that the server is currently running.
$ oc login https://api.ci.openshift.org
error: not authorized - verify you have provided the correct host and port and that the server is currently running.
$ oc login https://api.ci.openshift.org --loglevel=8
I1102 12:08:36.986805   23425 loader.go:357] Config loaded from file /Users/clayton/.kube/ci.kubeconfig
I1102 12:08:36.988795   23425 round_trippers.go:383] HEAD https://api.ci.openshift.org:443/
I1102 12:08:36.988812   23425 round_trippers.go:390] Request Headers:
I1102 12:08:37.268003   23425 round_trippers.go:408] Response Status: 403 Forbidden in 279 milliseconds
I1102 12:08:37.268033   23425 round_trippers.go:411] Response Headers:
I1102 12:08:37.268042   23425 round_trippers.go:414]     Cache-Control: no-store
I1102 12:08:37.268048   23425 round_trippers.go:414]     Content-Type: application/json
I1102 12:08:37.268054   23425 round_trippers.go:414]     Content-Length: 210
I1102 12:08:37.268060   23425 round_trippers.go:414]     Date: Thu, 02 Nov 2017 16:08:36 GMT
I1102 12:08:37.268120   23425 round_trippers.go:383] GET https://api.ci.openshift.org:443/.well-known/oauth-authorization-server
I1102 12:08:37.268131   23425 round_trippers.go:390] Request Headers:
I1102 12:08:37.268138   23425 round_trippers.go:393]     X-Csrf-Token: 1
I1102 12:08:37.307328   23425 round_trippers.go:408] Response Status: 200 OK in 39 milliseconds
I1102 12:08:37.307350   23425 round_trippers.go:411] Response Headers:
I1102 12:08:37.307358   23425 round_trippers.go:414]     Cache-Control: no-store
I1102 12:08:37.307365   23425 round_trippers.go:414]     Content-Type: application/json
I1102 12:08:37.307371   23425 round_trippers.go:414]     Content-Length: 537
I1102 12:08:37.307376   23425 round_trippers.go:414]     Date: Thu, 02 Nov 2017 16:08:36 GMT
I1102 12:08:37.307695   23425 round_trippers.go:383] GET https://api.ci.openshift.org/oauth/authorize?client_id=openshift-challenging-client&code_challenge=RWFVZmloLyP3MF2LITayUtFNfYKiqRXKuZbJLNfoqI0&code_challenge_method=S256&redirect_uri=https%3A%2F%2Fapi.ci.openshift.org%2Foauth%2Ftoken%2Fimplicit&response_type=code
I1102 12:08:37.307709   23425 round_trippers.go:390] Request Headers:
I1102 12:08:37.307715   23425 round_trippers.go:393]     X-Csrf-Token: 1
I1102 12:08:37.349737   23425 round_trippers.go:408] Response Status: 401 Unauthorized in 42 milliseconds
I1102 12:08:37.349759   23425 round_trippers.go:411] Response Headers:
I1102 12:08:37.349767   23425 round_trippers.go:414]     Link: <https://api.ci.openshift.org/oauth/token/request>; rel="related"
I1102 12:08:37.349774   23425 round_trippers.go:414]     Warning: 199 Origin "You must obtain an API token by visiting https://api.ci.openshift.org/oauth/token/request"
I1102 12:08:37.349781   23425 round_trippers.go:414]     Content-Type: text/plain; charset=utf-8
I1102 12:08:37.349786   23425 round_trippers.go:414]     Content-Length: 90
I1102 12:08:37.349791   23425 round_trippers.go:414]     Date: Thu, 02 Nov 2017 16:08:36 GMT
F1102 12:08:37.350452   23425 helpers.go:120] error: not authorized - verify you have provided the correct host and port and that the server is currently running.
```

Should have printed the warning.  Regression @openshift/sig-security

### PR DESCRIPTION
**Pull request by juanvallejo**
Fixes #17136
Fixes #17150

Preserves the error  type returned in https://github.com/openshift/origin/blob/master/pkg/oc/cli/cmd/login/loginoptions.go#L237

cc @openshift/cli-review

### CODE REVIEW

File: test/integration/oauth_request_header_test.go [hunk 1]
```diff
@@ -304,12 +304,14 @@ func TestOAuthRequestHeader(t *testing.T) {
...
 	// Attempt a login using a redirecting auth proxy
 	loginOutput := &bytes.Buffer{}
+	loginErrOutput := &bytes.Buffer{}
 	loginOptions := &login.LoginOptions{
 		Server:             anonConfig.Host,
 		CAFile:             masterCAFile,
 		StartingKubeConfig: &clientcmdapi.Config{},
 		Reader:             bytes.NewBufferString("myusername\nmypassword\n"),
 		Out:                loginOutput,
+		ErrOut:             loginErrOutput,
```
Comment (enj) [inline test/integration/oauth_request_header_test.go]: ioutil.Discard

File: test/integration/oauth_oidc_test.go [hunk 2]
```diff
@@ -156,12 +156,14 @@ func TestOAuthOIDC(t *testing.T) {
...
 	// Attempt a login using a redirecting auth proxy
 	loginOutput := &bytes.Buffer{}
+	loginErrOutput := &bytes.Buffer{}
 	loginOptions := &login.LoginOptions{
 		Server:             clientConfig.Host,
 		CAFile:             masterCAFile,
 		StartingKubeConfig: &clientcmdapi.Config{},
 		Reader:             bytes.NewBufferString("mylogin\nmypassword\n"),
 		Out:                loginOutput,
+		ErrOut:             loginErrOutput,
```
Comment (enj) [inline test/integration/oauth_oidc_test.go]: ioutil.Discard

File: pkg/oc/bootstrap/docker/up.go [hunk 3]
```diff
@@ -1112,7 +1113,7 @@ func (c *ClientStartConfig) RegisterTemplateServiceBroker(out io.Writer) error {
 // Login logs into the new server and sets up a default user and project
 func (c *ClientStartConfig) Login(out io.Writer) error {
 	server := c.OpenShiftHelper().Master(c.ServerIP)
-	return openshift.Login(initialUser, initialPassword, server, c.LocalConfigDir, c.originalFactory, c.command, out)
+	return openshift.Login(initialUser, initialPassword, server, c.LocalConfigDir, c.originalFactory, c.command, out, ioutil.Discard)
```
Comment (enj) [inline pkg/oc/bootstrap/docker/up.go]: It is probably debatable if this should use ioutil.Discard or not.

File: pkg/oc/cli/cmd/login/loginoptions.go [hunk 4]
```diff
@@ -231,10 +232,14 @@ func (o *LoginOptions) gatherAuthInfo() error {
 		// client is connecting to the right host:port
 		if statusErr, ok := err.(*kerrors.StatusError); ok {
 			if statusErr.Status().Code == http.StatusInternalServerError {
-				return fmt.Errorf("error: The server was unable to respond - %v", suggestion)
+				fmt.Fprintf(o.ErrOut, "error: The server was unable to respond - %v", suggestion)
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions.go]: This needs a newline at the end and you probably want to print the error as well.  Not special casing `StatusInternalServerError` would also be reasonable thing to do.

**Comment by enj** [comment]
Do not forget to squash.

File: pkg/oc/bootstrap/docker/up.go (hunk 3 above)
Comment (juanvallejo) [reply pkg/oc/bootstrap/docker/up.go]: cc @csrwng

Comment (juanvallejo) [reply pkg/oc/bootstrap/docker/up.go]: The alternative would be to wire each handler to receive a second io.Writer for errs

File: pkg/oc/cli/cmd/login/loginoptions.go (hunk 4 above)
Comment (juanvallejo) [reply pkg/oc/cli/cmd/login/loginoptions.go]: Thanks, will go ahead and remove the special case for internal server err - the error we print is pretty much the same as the one below this

File: pkg/oc/bootstrap/docker/up.go (hunk 3 above)
Comment (csrwng) [reply pkg/oc/bootstrap/docker/up.go]: why not use the same writer for both? (out)

Comment (csrwng) [reply pkg/oc/bootstrap/docker/up.go]: the more info we can return to users about failures, etc. the better

Comment (juanvallejo) [reply pkg/oc/bootstrap/docker/up.go]: thanks, went ahead and re-used `out` for both

File: pkg/oc/cli/cmd/login/loginoptions.go [hunk 5]
```diff
@@ -226,15 +226,10 @@ func (o *LoginOptions) gatherAuthInfo() error {
 	token, err := tokencmd.RequestToken(o.Config, o.Reader, o.Username, o.Password)
 	if err != nil {
 		suggestion := "verify you have provided the correct host and port and that the server is currently running."
+		fmt.Fprintf(o.ErrOut, "error: %v - %v\n", err, suggestion)
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions.go]: No point in making the suggestion var now.

**Comment by enj** [comment]
@juanvallejo we need some kind of test (unit preferred) to make sure #17150 does not happen.

File: pkg/oc/cli/cmd/login/loginoptions.go (hunk 5 above)
Comment (juanvallejo) [reply pkg/oc/cli/cmd/login/loginoptions.go]: thought it might help this line not get too long - will update though

**Comment by juanvallejo** [comment]
@enj thanks, added a unit test. ptal

File: pkg/cmd/util/tokencmd/request_token.go [hunk 6]
```diff
@@ -30,7 +30,7 @@ const (
 	// See IETF Draft:
 	// https://tools.ietf.org/html/draft-ietf-oauth-discovery-04#section-2
 	// Copied from pkg/cmd/server/origin/nonapiserver.go
-	oauthMetadataEndpoint = "/.well-known/oauth-authorization-server"
+	OauthMetadataEndpoint = "/.well-known/oauth-authorization-server"
```
Comment (enj) [inline pkg/cmd/util/tokencmd/request_token.go]: Do not export this, it is already a copy from a different file.  Hard code the string, it can never change.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 7]
```diff
@@ -2,19 +2,29 @@ package login
...
+	"io/ioutil"
 	"net/http"
 	"net/http/httptest"
+	"reflect"
 	"regexp"
 	"strings"
 	"testing"
 
+	"github.com/spf13/pflag"
+
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Space seems out of place.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 8]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
 }
 
+type oauthMetadataResponse struct {
+	metadata *util.OauthAuthorizationServerMetadata
+}
+
+func (r *oauthMetadataResponse) Serialize() string {
+	b, err := json.Marshal(r.metadata)
+	if err != nil {
+		return ""
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Fail the test on this.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 9]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+func TestPreserveErrTypeAuthInfo(t *testing.T) {
+	invoked := make(chan struct{}, 2)
+	metadataResponse := &oauthMetadataResponse{}
+
+	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		invoked <- struct{}{}
+
+		if r.URL.Path == tokencmd.OauthMetadataEndpoint {
+			w.WriteHeader(http.StatusOK)
+			io.WriteString(w, metadataResponse.Serialize())
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Can't you just write the raw bytes?

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 10]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+		w.WriteHeader(http.StatusUnauthorized)
+	}))
+
+	metadataResponse.metadata = &util.OauthAuthorizationServerMetadata{
+		Issuer:                        server.URL,
+		AuthorizationEndpoint:         server.URL + "/oauth/authorize",
+		TokenEndpoint:                 server.URL + "/oauth/token",
+		CodeChallengeMethodsSupported: []string{"plain", "S256"},
+	}
+	defer server.Close()
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Move up.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 11]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+	options := newLoginOptions(server.URL, "test", "test", false)
+	options.Config = clientConfig
+
+	err := options.gatherAuthInfo()
+	if err == nil {
+		t.Fatalf("expecting unauthorized error when gathering authinfo")
+	}
+
+	if !kapierrs.IsUnauthorized(err) {
+		t.Fatalf("expecting error of type metav1.StatusReasonUnauthorized, but got %v", reflect.TypeOf(err))
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Can just do `%T` to get the type.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 12]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+		InsecureTLS:        insecure,
+
+		Out:    ioutil.Discard,
+		ErrOut: ioutil.Discard,
+	}
+
+	return loginOptions
+}
+
+func defaultClientConfig(flags *pflag.FlagSet) kclientcmd.ClientConfig {
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: Flags, wat?

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 13]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+	}
+}
+
+func newLoginOptions(server string, username string, password string, insecure bool) *LoginOptions {
+	flagset := pflag.NewFlagSet("test-flags", pflag.ContinueOnError)
+	flags := []string{}
+	clientConfig := defaultClientConfig(flagset)
+	flagset.Parse(flags)
+
+	startingConfig, _ := clientConfig.RawConfig()
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: If this is an error, it should fail the test.

File: pkg/oc/cli/cmd/login/loginoptions_test.go [hunk 14]
```diff
@@ -256,6 +266,96 @@ func TestDialToHTTPServer(t *testing.T) {
...
+
+	return string(b)
+}
+
+func TestPreserveErrTypeAuthInfo(t *testing.T) {
+	invoked := make(chan struct{}, 2)
+	metadataResponse := &oauthMetadataResponse{}
+
+	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		invoked <- struct{}{}
```
Comment (enj) [inline pkg/oc/cli/cmd/login/loginoptions_test.go]: You need a check to fail the test if this would dead lock the buffered channel.

File: pkg/oc/cli/cmd/login/loginoptions_test.go (hunk 12 above)
Comment (juanvallejo) [reply pkg/oc/cli/cmd/login/loginoptions_test.go]: Heh, had originally grabbed these two helpers [from here](https://github.com/openshift/origin/blob/master/test/integration/login_test.go#L127). Went ahead and cleaned the test up - no longer need them for this test

**Comment by juanvallejo** [comment]
@enj thanks for the review, comments addressed

**Comment by enj** [comment]
/lgtm

Approving since this all auth code.
