### PR TITLE
Deployment canary

### LINKED ISSUE #2637: Support canary for rolling deployments
During rolling deployment, a canary check should be performed for the first new replica to avoid rolling out a bunch of broken replicas. Wait for the first replica, and fail the deployment if the pod doesn't start successfully. 

Outstanding design issues:

* Should there be a distinct timeout on `RollingDeploymentStrategyParams` for the canary check? The only possible existing parameter which could be reused is `TimeoutSeconds` which defaults to 120 seconds and is intended to represent the time to wait for a given replica count to be achieved (which is roughly analagous, but doesn't account for pod/container status).

This issue will require carring an upstream patch for the rolling updater.

Punch list item for https://github.com/openshift/origin/issues/2628.

### PR DESCRIPTION
**Pull request by ironcladlou**
Implements deployment canary functionality for #2637 implements the fixes to deployment behavior described in https://github.com/openshift/origin/pull/2892#issuecomment-110493587.

Fixes #2637

### CODE REVIEW

File: pkg/deploy/strategy/support/lifecycle.go [hunk 1]
```diff
@@ -203,3 +203,121 @@ func NewPodWatch(client kclient.Interface, namespace, name, resourceVersion stri
 		return obj.(*kapi.Pod)
 	}
 }
+
+func NewContainersReadyCanary(kclient kclient.Interface, timeout time.Duration) *ContainersReadyCanary {
```
Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: I don't think `ContainersReadyCanary` describes this very well.  I would call the interface PodAcceptor or UpdateAcceptor and describe this as "FirstContainerReady"

File: pkg/deploy/strategy/support/lifecycle.go [hunk 2]
```diff
@@ -203,3 +203,121 @@ func NewPodWatch(client kclient.Interface, namespace, name, resourceVersion stri
...
+	}
+
+	// Wait for container readiness to be observed once per container in the pod.
+	containersReady := map[string]bool{}
+	for _, container := range pod.Spec.Containers {
+		containersReady[container.Name] = false
+	}
+
+	// Make a pod store to poll and ensure it gets cleaned up.
+	podStore, stopStore := c.getPodStore(pod.Namespace, pod.Name)
```
Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: Why do we need a store and not just a watch?

File: pkg/deploy/strategy/support/lifecycle.go [hunk 3]
```diff
@@ -203,3 +203,121 @@ func NewPodWatch(client kclient.Interface, namespace, name, resourceVersion stri
...
+			allReady := true
+			for _, ready := range containersReady {
+				if !ready {
+					allReady = false
+					break
+				}
+			}
+			// If all containers have been ready once, return success.
+			if allReady {
+				glog.V(0).Infof("All containers ready for %s/%s", pod.Namespace, pod.Name)
```
Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: Don't v(0)

File: pkg/deploy/strategy/support/lifecycle.go [hunk 4]
```diff
@@ -203,3 +203,121 @@ func NewPodWatch(client kclient.Interface, namespace, name, resourceVersion stri
...
+				glog.V(0).Infof("Couldn't find pod %s/%s to inspect container readiness", pod.Namespace, pod.Name)
+				break
+			}
+			if err != nil {
+				glog.V(0).Infof("Error getting pod %s/%s to inspect container readiness: %v", pod.Namespace, pod.Name, err)
+				break
+			}
+			updatedPod := obj.(*kapi.Pod)
+			// Update the observed ready status of any containers.
+			for _, status := range updatedPod.Status.ContainerStatuses {
```
Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: break these into functions for readability

**Comment by smarterclayton** [comment]
Looks pretty straightforward

File: pkg/deploy/strategy/support/lifecycle.go (hunk 1 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/support/lifecycle.go]: I like your naming a lot better. I'll use it.

File: pkg/deploy/strategy/support/lifecycle.go (hunk 2 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/support/lifecycle.go]: So, using `watch.Interface` directly in a way that's resilient turns out to be more code than I'd expect. You can't just use ResultChan until you're done- you have to account for watch timeouts/failures, and then re-establish your watch (which is more logic to deal with resourceVersion). I actually notice that the few places in origin that use `watch.Interface` don't actually account for any of that.

My rationale is that the reflector/store handles all the `watch.Interface` details reliably, but means I sacrifice access to a channel. I need for/select mechanics to handle timeouts. So I compromise by using reflector (to handle the watch) and a store (which I can poll locally in a for/select).

If you feel strongly I should just be using `watch.Interface` directly, can you also speak to whether I should be handling watch re-establishment? It's code I'd rather not deal with, but I can.

Comment (liggitt) [inline pkg/deploy/strategy/support/lifecycle.go]: > I actually notice that the few places in origin that use watch.Interface don't actually account for any of that.

Please open issues to track

File: pkg/deploy/strategy/support/lifecycle.go (hunk 3 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/support/lifecycle.go]: The only time this code is used is via the deployer code running in a pod (the logs are only accessible right now via `docker log` and the log level isn't configurable). The other deployer code doesn't even use log levels for this reason. Should I continue to omit levels here for the same reason, or what? I really want to see this stuff from the container logs.

Comment (liggitt) [inline pkg/deploy/strategy/support/lifecycle.go]: yeah, we don't have a good way to set log verbosity levels for the deployer pod... errors need to be in the deployment pod log by default

File: pkg/deploy/strategy/support/lifecycle.go (hunk 2 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/support/lifecycle.go]: @liggitt 
>> I actually notice that the few places in origin that use watch.Interface don't actually account for any of that.

>Please open issues to track

First I'd like to get @smarterclayton's take. I might be missing why it's okay to not deal with re-establishment.

I need to nail down this design decision ASAP.

Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: I'm fine with pod store for now.  However, in a very large namespace this is potentially a huge amount of data - I'm not sure there is any advantage over polling here.  What does the polling solution look like?  How can you best use the data you already have loaded to do the right thing?

File: pkg/deploy/strategy/support/lifecycle.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: Open an issue to track that post 3.0

----- Original Message -----

File: pkg/deploy/strategy/support/lifecycle.go (hunk 2 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/support/lifecycle.go]: Notice that the ListWatcher for the reflector feeding the store filters on `metadata.name`, so the store only ever contains just 1 pod: the one I want to watch. I then poll the local store. So I get server side watch efficiency and poll that single-entry store on the client in a for/select w/ a ticker+timeout.

Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: Ok, that's fine, just make sure it's not leaking goroutines.

----- Original Message -----

Comment (smarterclayton) [inline pkg/deploy/strategy/support/lifecycle.go]: @csrwng as discussed can you help test and work with Dan

----- Original Message -----

Comment (csrwng) [inline pkg/deploy/strategy/support/lifecycle.go]: yup, on it... setting up tests with this branch

**Comment by csrwng** [comment]
@ironcladlou - So I had a sequence of unexpected events after a failed canary deployment. The scenario is I have an image with tags v1, v2, and fail. Tag fail is the one that doesn't work. So here's what I did:
```
- create the deployment config with tag v1, replicas = 5
    Result: 
    rc-1 - replicas: 5 - image: v1
- edit the dc and set it to deploy tag 'fail'
    Result:
    rc-1 - replicas: 5 - image: v1 
    rc-2 - replicas; 0 - image: fail, state: failed
- edit the dc and set it to deploy tag 'v2'
    rc-1 - replicas: 5 - image: v1
    rc-2 - replicas: 0 - image: fail, state: failed
    rc-3 - replicas: 5 - image: v2 
- rollback to rc-1
    rc-1 - replicas: 0 - image: v1
    rc-2 - replicas: 0 - image: fail, state: failed
    rc-3 - replicas: 0 - image: v2 
    rc-4 - replicas: 11 - image: v1
- scale rc-4 to 5
    rc-1 - replicas: 0 - image: v1
    rc-2 - replicas: 0 - image: fail, state: failed
    rc-3 - replicas: 0 - image: v2 
    rc-4 - replicas: 5 - image: v1
    rc-5 - replicas: 5 - image: v2 !!!
```
I wouldn't expect the behavior of the deployment after the failed canary to add more pods, neither would I expect the results I got from rollback or scale afterwards

**Comment by csrwng** [comment]
Follow-up after above test...  I scaled rc-5 down to 0. It came down to 0. However, I left and came back. After a while, it was up to 16 replicas.

**Comment by ironcladlou** [comment]
@csrwng 
> I had a sequence of unexpected events

You're very polite. :blush:

I see at least one issue here which explains `rollback to rc-1`. I'll fix it and then see what happens with the rollback/scenario based on the first fix.

Really good finds!

**Comment by abhgupta** [comment]
@ironcladlou I would propose the following:

1. no previous deployments
 - use config replica count
2. single "active" deployment exists
 - use its replica count
3. multiple "active" deployments exist
 - use the latest "active" deployment's desired replica annotation
4. no "active" deployment exists but a "completed" deployment exists
 - use 0 as the replica count
 - we assume that the completed deployment was intentionally scaled down to 0 
5. no "active" or "completed" deployments exist
 - use the latest deployment's desired replica annotation

In all cases:

1. when scaling up a new deployment, we should scale down all previous active deployments to 0
2. we should set the desired replica count annotation in all cases

**Comment by abhgupta** [comment]
I am open to adopting a simpler solution, but the above represents what I believe is expected.

**Comment by smarterclayton** [comment]
Define new deployment.

----- Original Message -----

**Comment by abhgupta** [comment]
New deployment is a new RC that gets created automatically either when a trigger fires, or when the user manually bumps up the LatestVersion for the DC. Even a rollback results in the creation of a new deployment, albeit with older images/config.

Initially, a new RC is created with a replica count of 0 and then, based on strategy, the replica count is increased to the "desired value". My points above highlight what this "desired value" for the new deployment should be, as implemented by the strategies that we manage.

**Comment by csrwng** [comment]
@ironcladlou I tested canary for initial deployment. With a working image, it works as expected. It will deploy all 5 replicas after it does the initial canary. However, with a failing image, it worked initially as expected. It ran the canary and because it didn't work, it didn't deploy the other replicas. Then I went and edited the dc to point to the good image and that kicked off a new deployment. However, instead of deploying the 5 replicas that I would expect, it only deployed 1.

**Comment by abhgupta** [comment]
@csrwng Can you please run your situation through my proposed steps and let me know if the proposed steps hold up to your scenario?

**Comment by abhgupta** [comment]
@csrwng Referring to https://github.com/openshift/origin/pull/2892#issuecomment-110200853

**Comment by smarterclayton** [comment]
We should use the latest complete deployment number or its target.  I'm not sure we should be scaling down other deployments - why is that truly necessary?

**Comment by abhgupta** [comment]
There should really be only a single "active" (non-zero replicas) deployment for a DC in "complete" state. We will add code to clean up failed deployments and scale back the N-1 deployments in case of errors. However, failures can result during this step and we can end up with aborted/failed and multiple active deployments. When scaling up a new deployment, we should clean up older active ones.

A new deployment will only be initiated when previous deployments have either completed or failed. So, there is no concern about having multiple previous active deployments  that are all valid.

**Comment by smarterclayton** [comment]
> On Jun 8, 2015, at 11:10 PM, Abhishek Gupta <notifications@github.com> wrote:
> 
> There should really be only a single "active" (non-zero replicas) deployment for a DC in "complete" state. We will add code to clean up failed deployments and scale back the N-1 deployments in case of errors. However, failures can result during this step and we can end up with aborted/failed and multiple active deployments. When scaling up a new deployment, we should clean up older active ones.
> 

> A new deployment will only be initiated when previous deployments have either completed or failed. So, there is no concern about having multiple previous active deployments that are all valid.
> 
Why can't I scale up a previous deployment for testing?

**Comment by abhgupta** [comment]
@smarterclayton Fair point, revised proposal:

1. no previous deployments exist OR no "completed" deployment exists
 - use config replica count
2. multiple deployments exist
 - use the latest "complete" deployment's replica count
3. latest "complete" deployment has replica count of 0
 - use 0 as the replica count
 - we assume that the completed deployment was intentionally scaled down to 0

In all cases, when scaling up a new deployment, we should scale down ONLY the latest completed deployment to 0

**Comment by smarterclayton** [comment]
Originally we had discussed scaling down old ones.  I'm not against it, but we need to be sure that's the right behavior.  Do we gradually scale them down?  Is the total number the most recent successful deployment or its annotation for it's desired?  I think maybe we want a middle ground:

Scale down all deployments that are not the most recent successful.  Use the replica count from most recent successful (or its higher annotation).

The question is that that has to be reentrant. Is that algorithm safe against races?

**Comment by abhgupta** [comment]
> Do we gradually scale them down?

Depends on the deployment strategy - "recreate" will do it in a single shot, while "rolling" will do it gradually.

For re-entrant behavior and race-conditions, I will discuss with @ironcladlou as he is working on the current implementation.

**Comment by smarterclayton** [comment]
Why do we need to gradually scale down older deployments?  By definition, if we scale them down, they don't matter to the whole strategy (because they were manual).  Why don't we scale them to 0 instantly?

----- Original Message -----

**Comment by ironcladlou** [comment]
>Scale down all deployments that are not the most recent successful. Use the replica count from most recent successful (or its higher annotation).

If the deployment was successful, when can we consider the desired replicas annotation? If the current replica count doesn't match the desired, but the deployment was successful, does that imply the user manually scaled the deployment? If so, shouldn't we preserve the actual replica count rather than following the annotation?

**Comment by smarterclayton** [comment]
> On Jun 9, 2015, at 7:58 AM, Dan Mace <notifications@github.com> wrote:
> 
> Scale down all deployments that are not the most recent successful. Use the replica count from most recent successful (or its higher annotation).
> 
> If the deployment was successful, when can we consider the desired replicas annotation? If the current replica count doesn't match the desired, but the deployment was successful, does that imply the user manually scaled the deployment? If so, shouldn't we preserve the actual replica count rather than following the annotation?
> 
The annotation should be removed or ignored when the deployment completes.  Otherwise, we have no way to distinguish the two cases.  Since the annotation takes priority *during* the deployment, we have to honor it.  Or make rules about when it applies.

**Comment by ironcladlou** [comment]
>The annotation should be removed or ignored when the deployment completes. Otherwise, we have no way to distinguish the two cases. 

I think this solves it. So far I think "Clayton's Compromise" will serve:

1. Scale down all deployments that are not the most recent successful. Use the replica count from most recent successful.
2. Remove the desired replicas annotation during the transition of the deployment to Complete (this can be atomic with the state transition).

Anybody see any holes?

**Comment by csrwng** [comment]
sgtm

**Comment by abhgupta** [comment]
@smarterclayton For gradual scaledown, I was referring to the latest active deployment. For older active deployments, I would agree that it makes sense to scale them down instantly.

**Comment by ironcladlou** [comment]
There's one possible gap in the logic.

```
# initial deployment
deployment-1 - replicas 5 - complete 

# deployment of version 2, failure midway during scale-up
deployment-1 - replicas 3 - complete
deployment-2 - replicas 2 - failed
```

At this point, deployment-1 has a replica count of 3 and no desired replicas annotation. If version 3 is deployed, the desired replicas would be 3.

**Comment by smarterclayton** [comment]
Define failure midway through scale-up?  Why wouldn't target annotations be set on deployment 2 and deployment 1 be restored to 5?

----- Original Message -----

**Comment by ironcladlou** [comment]
>Define failure midway through scale-up

The rolling updater scales by 1 each update interval, and then waits for that replica count to be achieved. The call to update the replica count can fail (connectivity), the replica count wait could time out (pods not getting scheduled), etc. The updater will abort if a +1 interval fails, leaving us in the state I described.

>Why wouldn't target annotations be set on deployment 2

In the example, deployment-2 would indeed have the desired replica count, but by the rules we've defined above, we would be looking only at the last Completed deployment (deployment-1) for the next desired replica count.

> and deployment 1 be restored to 5?

This sounds like fail-back behavior, which we've been treating as orthogonal. Right now, when the deployment fails, we do nothing.

**Comment by smarterclayton** [comment]
----- Original Message -----
> >Define failure midway through scale-up
> 
> The rolling updater scales by 1 each update interval, and then waits for that
> replica count to be achieved. The call to update the replica count can fail
> (connectivity), the replica count wait could time out (pods not getting
> scheduled), etc. The updater will abort if a +1 interval fails, leaving us
> in the state I described.

If the canary fails... why are there still new bad pods running?

> 
> >Why wouldn't target annotations be set on deployment 2
> 
> In the example, deployment-2 would indeed have the desired replica count, but
> by the rules we've defined above, we would be looking only at the last
> Completed deployment (deployment-1) for the next desired replica count.

Then the rules we defined are probably wrong.

> 
> > and deployment 1 be restored to 5?
> 
> This sounds like fail-back behavior, which we've been treating as orthogonal.
> Right now, when the deployment fails, we do nothing.

Which is ok, but canary without fail back is useless.  It doesn't do much good to define the algorithm and then not take that into account.

**Comment by ironcladlou** [comment]
>If the canary fails... why are there still new bad pods running?

Quick clarification: this is a case where the canary passes, but then a subsequent scale-up of the remaining replicas towards the desired count fails, which is always a possibility.

**Comment by ironcladlou** [comment]
So not bad pods running, but a partial rollout.

**Comment by smarterclayton** [comment]
Ok.  That's fine then.  I think we should leave the desired replicas annotation on.  In this case we need to be able to observe the deployments at any point in time and restore the users last desired count.

**Comment by smarterclayton** [comment]
Let's restate the goals of deployment real quick.

1. User describes a desired end state and the system works towards it (ie, I want N things that look like this)
2. Deployments are created to transition between states.
3. Deployments can be interrupted by recoverable or unrecoverable errors; recoverable errors should not block transition to a new state, unrecoverable errors that block forward progress can result in a stopped deployment
4. In the absence of unrecoverable errors, we should work to converge the last recorded user desired state.
5. Deployments older than the current complete deployment are candidates for scale down immediately by a running deployment process.  This is safe for concurrency.

**Comment by smarterclayton** [comment]
```
# initial deployment
deployment-1 - replicas 5 - complete 

# deployment of version 2, failure midway during scale-up
deployment-1 - replicas 3 - complete (should have annotation 5)
deployment-2 - replicas 2 - failed (should have annotation 5)
```

Should have annotations

```
# initial deployment
deployment-1 - replicas 5 - complete 

# deployment of version 2, failure midway during scale-up
deployment-1 - replicas 3 - complete (should have annotation 5)
deployment-2 - replicas 2 - failed (should have annotation 5)

# auto scaler scales up the group to 8 by adding 3 to deployment-1

deployment-1 - replicas 6 - complete (should have annotation 5)
deployment-2 - replicas 2 - failed (should have annotation 5)
```

The next deployment should observe that X is greater than the annotation size (2+6 = 8 > 5) but prefer the annotation and continue to 5 (which is ok, because the autoscaler will keep adding to the group).

The user can always scale back up manually.

**Comment by ironcladlou** [comment]
Taking into account the auto-scaler and the ability for users to re-adjust manually, sounds like "always use the desired annotation from the last completed deployment" (and never deleting the annotation) will get us to a better place.

**Comment by ironcladlou** [comment]
More stuff I thought of.

```
# deployment of version 2, failure midway during scale-up
deployment-1 - replicas 3 - complete (should have annotation 5)
deployment-2 - replicas 2 - failed (should have annotation 5)
# new deployment created to try again
deployment-3 - replicas 0 - pending
```
The way rolling is set up right now, deployment-3 is the new deployment (N) and deployment-2 is the previous (N-1). The cleanup rules we defined would mean that deployment-2 would be scaled to 0, and deployment-1 would remain at 3. The rolling update would transition deployment-2 to deployment-3, and in the end we'd have:

```
# deployment of version 2, failure midway during scale-up
deployment-1 - replicas 3 - complete (should have annotation 5)
deployment-2 - replicas 0 - failed (should have annotation 5)
deployment-3 - replicas 5 - complete
```

Would things be more consistent if we always scaled down any previous !Complete deployments and transitioned from <last Complete deployment> to <new deployment>?

**Comment by smarterclayton** [comment]
----- Original Message -----
> More stuff I thought of.
> 
> ```
> # deployment of version 2, failure midway during scale-up
> deployment-1 - replicas 3 - complete (should have annotation 5)
> deployment-2 - replicas 2 - failed (should have annotation 5)
> # new deployment created to try again
> deployment-3 - replicas 0 - pending
> ```
> The way rolling is set up right now, deployment-3 is the new deployment (N)
> and deployment-2 is the previous (N-1). The cleanup rules we defined would
> mean that deployment-2 would be scaled to 0, and deployment-1 would remain
> at 3. The rolling update would transition deployment-2 to deployment-3, and
> in the end we'd have:
> 
> ```
> # deployment of version 2, failure midway during scale-up
> deployment-1 - replicas 3 - complete (should have annotation 5)
> deployment-2 - replicas 0 - failed (should have annotation 5)
> deployment-3 - replicas 5 - complete
> ```
> 
> Would things be more consistent if we always scaled down any previous
> !Complete deployments and transitioned from <last Complete deployment> to
> <new deployment>?

1 ... N ... M

where N is the last complete and M is the most recent

1. Scale down 1-(N-1) to zero
2. Scale down (N+1)-(M-1) to zero
3. Use N and M as the scale counters.  We should probably pass N and M to the rolling deployment, not M-1 and M

**Comment by ironcladlou** [comment]
>1 ... N ... M where N is the last complete and M is the most recent 1. Scale down 1-(N-1) to zero 2. Scale down (N+1)-(M-1) to zero 3. Use N and M as the scale counters. We should probably pass N and M to the rolling deployment, not M-1 and M

Exactly. I was thinking with this addition, we'd be at a point where the flow is:

1. M is created with desired replica count set to N's desired replica count
2. The pre-strategy deployer setup would:
  1. Scale down all deployments not in (M, N)
  2. Pass M and N to the strategy

**Comment by abhgupta** [comment]
Mostly sounds good - just note that M and N could be the same deployment. 

The one question that I have is - if we keep following the desired replica annotation, then will the annotation value ever differ from the initial config value? Scale up/down will never have an impact and the whole point of having annotations in the first place becomes moot.

I would favor using N.replicas + M.replicas as the target, provided N and M are different. We should expect them to be the same and for either of them to be nil.

**Comment by smarterclayton** [comment]
----- Original Message -----
> >1 ... N ... M where N is the last complete and M is the most recent 1. Scale
> >down 1-(N-1) to zero 2. Scale down (N+1)-(M-1) to zero 3. Use N and M as
> >the scale counters. We should probably pass N and M to the rolling
> >deployment, not M-1 and M
> 
> Exactly. I was thinking with this addition, we'd be at a point where the flow
> is:
> 
> 1. M is created with desired replica count set to N's desired replica count
> 2. The pre-strategy deployer setup would:
>   1. Scale down all deployments not in (M, N)

You need to do this in numerical order so that multiple processes running in parallel don't have unanticipated behavior.

**Comment by smarterclayton** [comment]
----- Original Message -----
> Mostly sounds good - just note that M and N could be the same deployment.
> 
> The one question that I have is - if we keep following the desired replica
> annotation, then will the annotation value ever differ from the initial
> config value? Scale up/down will never have an impact and the whole point of
> having annotations in the first place becomes moot.

The annotation can go away after complete - i'm just saying if the annotation is present it means another deployer is modifying the deployment and we need to bail.

> 
> I would favor using N.replicas + M.replicas as the target, provided N and M
> are different. We should expect them to be the same and for either of them
> to be nil.

That number isn't necessarily correct - with rolling you have some number P that is greater than original N+M extra depending on how many new pods you create at a time.

**Comment by abhgupta** [comment]
I would just like us to try and honor any scale up/down of the existing deployment when we create a new deployment and try to determine its target replica count.

**Comment by ironcladlou** [comment]
>The annotation can go away after complete - i'm just saying if the annotation is present it means another deployer is modifying the deployment and we need to bail.

Not sure I follow what this is implying. There can only be one deployer per version. If we delete the annotation we're back to the problem from https://github.com/openshift/origin/pull/2892#issuecomment-110384700 which is what led us to decide the annotation had to stick around.

**Comment by abhgupta** [comment]
And its not ok to ignore the effects of scale up/down. A deployment (RC1) could start initially at 1 and the user could have scaled it up to 10. A new deployment (RC2) should not have a replica count of 1.

**Comment by abhgupta** [comment]
So, here goes another attempt:
1. The desired replica annotation should be set on a deployment based on previous deployment's replica (or config/pod-template if this is the first deployment) - this should be used by the deployment strategy implementation
2. The annotation should be removed after a deployment completes (or be ignored)
3. If M (most recent existing deployment) is complete, use the actual replica count from M; otherwise, use the desired annotation from M 

The scale-down of existing deployments should follow the logic that @smarterclayton mentioned in https://github.com/openshift/origin/pull/2892#issuecomment-110446702

**Comment by abhgupta** [comment]
@smarterclayton Had a chat with @ironcladlou and now I have doubts over what "M" is in your example.

Which one is it:

1. the most recent existing deployment
2. the new deployment being created

**Comment by smarterclayton** [comment]
The newest deployment.

**Comment by abhgupta** [comment]
If M is the new deployment being deployed/scaled-up, I believe we are in agreement:

1. The desired replica annotation should be set on a new deployment by the platform and this should be used by the deployment strategy implementation
2. The target replica for M will be the actual replica count of N
3. If N doesn't exist then the config template replica value will be used
4. Clean-up of failed deployments will be done such that if M fails, then M should end up with 0 replicas and N should be scaled back to its original replica count (handled by https://github.com/openshift/origin/issues/2854)
5. The scale-down of existing deployments will be handled by the platform prior to handing off to the strategy implementation and should follow the logic that @smarterclayton mentioned in #2892 (comment)
6. We will feed N (last complete deployment) and M (the new deployment) to the strategy to transition

**Comment by smarterclayton** [comment]
SGTM

----- Original Message -----

**Comment by ironcladlou** [comment]
+1, we're all on the same page. I'll have something ready for manual testing very soon.

**Comment by ironcladlou** [comment]
@csrwng @abhgupta @smarterclayton I've pushed code which implements our new rules, and things are looking much better. [Here's a gist](https://gist.github.com/ironcladlou/e5274d55836770348248) with logs/context from the complete/fail/complete scenario. Any manual testing or review would be appreciated while I work to get the unit tests solvent (there's a ton to redo- but the deployment code is now much simpler with our rules).

**Comment by ironcladlou** [comment]
I still have some units to fix, but want to see what I get from a [test]...

File: pkg/cmd/infra/deployer/deployer.go [hunk 5]
```diff
@@ -77,88 +74,111 @@ func NewCommandDeployer(name string) *cobra.Command {
...
-			oldDeployments = append(oldDeployments, &allControllers.Items[i])
+		if lastDeployment != nil && candidate.Name == lastDeployment.Name {
+			continue
+		}
+		if candidate.Spec.Replicas == 0 {
+			// The deployment is already scaled down
+			continue
+		}
+		candidate.Spec.Replicas = 0
+		_, err := d.updateDeployment(namespace, &candidate)
```
Comment (kargakis) [inline pkg/cmd/infra/deployer/deployer.go]: This will not wait for the deployment to scale down. I guess it's fine to not wait here but the following successful log might need rewording...

File: pkg/cmd/infra/deployer/deployer.go [hunk 6]
```diff
@@ -77,88 +74,111 @@ func NewCommandDeployer(name string) *cobra.Command {
...
+}
+
+type Deployer struct {
+	strategyFor      func(config *deployapi.DeploymentConfig) (strategy.DeploymentStrategy, error)
+	getDeployment    func(namespace, name string) (*kapi.ReplicationController, error)
+	getControllers   func(namespace string) (*kapi.ReplicationControllerList, error)
+	updateDeployment func(namespace string, deployment *kapi.ReplicationController) (*kapi.ReplicationController, error)
+}
+
 // deploy executes a deployment strategy.
```
Comment (kargakis) [inline pkg/cmd/infra/deployer/deployer.go]: Any love for our godoc?:)

File: pkg/deploy/strategy/recreate/recreate.go [hunk 7]
```diff
@@ -52,126 +59,93 @@ func NewRecreateDeploymentStrategy(client kclient.Interface, codec runtime.Codec
...
+// for initial deployments.
+func (s *RecreateDeploymentStrategy) DeployWithAcceptor(from *kapi.ReplicationController, to *kapi.ReplicationController, desiredReplicas int, updateAcceptor kubectl.UpdateAcceptor) error {
+	config, err := deployutil.DecodeDeploymentConfig(to, s.codec)
+	if err != nil {
+		return fmt.Errorf("couldn't decode config from deployment %s: %v", to.Name, err)
 	}
 
-	params := deploymentConfig.Template.Strategy.RecreateParams
+	params := config.Template.Strategy.RecreateParams
+	retryParams := &kubectl.RetryParams{s.retryPeriod, s.retryTimeout}
```
Comment (kargakis) [inline pkg/deploy/strategy/recreate/recreate.go]: You can use `NewRetryParams` for these

File: pkg/cmd/infra/deployer/deployer.go (hunk 6 above)
Comment (ironcladlou) [inline pkg/cmd/infra/deployer/deployer.go]: I'll be doing a godocs sweep after I finish the unit tests, there's a lot to do.

File: pkg/cmd/infra/deployer/deployer.go (hunk 5 above)
Comment (ironcladlou) [inline pkg/cmd/infra/deployer/deployer.go]: I think the lack of waiting is fine for this case (cleanup). With this PR I switched Recreate to use the Scaler, and I could port that here too if it's a big deal.

Comment (ironcladlou) [inline pkg/cmd/infra/deployer/deployer.go]: I went ahead and ported this to also use Scaler since I need to redo the unit tests anyway. Thanks!

File: pkg/deploy/strategy/recreate/recreate.go (hunk 7 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/recreate/recreate.go]: Fixed, thanks

File: pkg/cmd/infra/deployer/deployer.go (hunk 5 above)
Comment (kargakis) [inline pkg/cmd/infra/deployer/deployer.go]: Well, I made the first comment because the glog you were printing as soon as you updated the deployment was informing the user that it was scaled which is not true ("scaling" would be more precise). I still believe that not waiting for those deployments is fine and we probably shouldn't...

Comment (ironcladlou) [inline pkg/cmd/infra/deployer/deployer.go]: I think I'd rather use the Scaler for consistency across the board. If we don't want to wait as long, we can adjust the Scaler parameters.

Comment (ironcladlou) [inline pkg/cmd/infra/deployer/deployer.go]: But a scale to 0 should be quick regardless.

Comment (kargakis) [inline pkg/cmd/infra/deployer/deployer.go]: "should":)

**Comment by csrwng** [comment]
@ironcladlou - So far it's looking much better. Deploy after a failed rolling deployment is working as expected. However, I still see some weirdness with rollback. For example, the following sequence:
```
deploy v1 (repl=5) -> v1 rc with 5 replicas
deploy fail -> fail rc with 1 failed replica
deploy v2 -> v2 rc with 5 replicas -- other rc's set to 0
scale v2 to 3 -> v2 rc with 3 replicas
rollback to initial rc(v1 rc) -> v2 rc with 3 replicas !!!
```
So for the last rollback, it initially created a v1 rc, scaled up to 3, scaled the previous v2 rc to 0. All good. But shortly after, a new v2 rc was created and the v1 rc was scaled down to 0, and the new v2 rc was scaled up to 3. - Net change was none.

**Comment by smarterclayton** [comment]
Can we make sure we have a DC example image that fails it's readiness check in response to an env var?  Nettest upstream may do some of this already, pretty sure readiness is tested.

**Comment by ironcladlou** [comment]
Unit tests are done. Checking to see if [test] is still green while people review.

@csrwng @smarterclayton I'm going to look into the rollbacks thing now.

**Comment by ironcladlou** [comment]
[test] again to banish flakes

File: Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/rolling_updater.go [hunk 8]
```diff
@@ -368,6 +386,14 @@ func (r *RollingUpdater) Update(config *RollingUpdaterConfig) error {
 		if err != nil {
 			return err
 		}
+		// Perform the update acceptance check exactly once.
+		if config.UpdateAcceptor != nil && !updateAccepted {
+			err := config.UpdateAcceptor.Accept(newRc)
+			if err != nil {
```
Comment (csrwng) [inline Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/kubectl/rolling_updater.go]: combine with above line?

**Comment by abhgupta** [comment]
LGTM

**Comment by ironcladlou** [comment]
Rebased, the tests are still flaking on the delete issue.

File: pkg/cmd/infra/deployer/deployer.go [hunk 9]
```diff
@@ -77,88 +76,124 @@ func NewCommandDeployer(name string) *cobra.Command {
...
+	// New deployments must have a desired replica count.
+	desiredReplicas, hasDesired := deployutil.DeploymentDesiredReplicas(deployment)
+	if !hasDesired {
+		return fmt.Errorf("deployment %s has no desired replica count", deployutil.LabelForDeployment(deployment))
 	}
 
-	if newConfig, err = deployutil.DecodeDeploymentConfig(newDeployment, latest.Codec); err != nil {
-		return nil, nil, err
+	// Find all controllers in order to pick out the deployments.
+	controllers, err := d.getControllers(namespace)
```
Comment (csrwng) [inline pkg/cmd/infra/deployer/deployer.go]: It'd be better to retrieve only the controllers for the deployment config by filtering with the 'deploymentconfig' label.

**Comment by csrwng** [comment]
I created separate issues for the things I found:
https://github.com/openshift/origin/issues/3070
https://github.com/openshift/origin/issues/3071

Other than that, I have not seen any problems with deployments in my testing. LGTM

**Comment by ironcladlou** [comment]
@deads2k https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/3078/console

>--- FAIL: TestServiceAccountAuthorization-2 (7.07s)
	service_account_test.go:92: unexpected error: User "system:serviceaccount:default:default" cannot create namespaces at the cluster scope

Any clue what this is? Passes locally, passed on previous jenkins runs, still waiting on travis.

**Comment by liggitt** [comment]
@deads2k didn't know if AddRole had to trigger a policy cache update before operations would succeed

**Comment by ironcladlou** [comment]
@smarterclayton I think this is ready to go.

**Comment by smarterclayton** [comment]
Approved [merge]

**Comment by deads2k** [comment]
> didn't know if AddRole had to trigger a policy cache update before operations would succeed

After AddRole is completed, the cache does have to be updated before you'll see the effect of the policy change.

**Comment by liggitt** [comment]
huh, must have been a fast cache... never seen an AddRole related flake before

**Comment by deads2k** [comment]
> huh, must have been a fast cache... never seen an AddRole related flake before

Yeah.  It's extremely uncommon to miss.
