### PR TITLE
Pick build container for logs with istio auto-inject - fixes #18997

### LINKED ISSUE #18997: Istio: OpenShift unable to show logs from builds and deployments
When using Istio auto-injection, builder and deployer pods get sidecar proxies auto injected.

When a build is created, and `oc logs -f bc/bcname` is issued, it errors:

```
% oc new-app --name fail-project nodejs~https://github.com/openshift/nodejs-ex
% oc logs -f bc/fail-project
Cloning "https://github.com/openshift/nodejs-ex" ...
	Commit:	93fc25fd35068aa311f4722e4d7e5187b06edd7b (Merge pull request #170 from dharmit/add-minishift-to-readme)
	Author:	Ben Parees <bparees@users.noreply.github.com>
	Date:	Tue Mar 6 13:34:31 2018 -0500
error retrieving logs for build pod: foo/fail-project-1-build container: , a container name must be specified for pod fail-project-1-build, choose one of: [sti-build istio-proxy] or one of the init containers: [git-clone manage-dockerfile istio-init]
```

##### Version
```
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
```

##### Steps To Reproduce
See Description. it's `oc new-app` and `oc logs -f`.

##### Current Result
See Description for error message.

##### Expected Result
No error message and show me the logs.

##### Additional Information
This is under an auto-injected project using Istio 0.6.0. A sidecar proxy is injected into _any_ pod in the namespace, including _builder_ and _deployer_ pods.

### PR DESCRIPTION
**Pull request by wozniakjan**
When using istio auto-inject, the build pod is enhanced with a container sidecar - proxy https://github.com/openshift/origin/issues/18997

Given the build pod container name can change and istio appends its containers to the end of the container list, it should be possible to treat the first container in the pod's container list as the desired build container.

@openshift/sig-developer-experience any better suggestions? Do we want to stream the logs from all containers in builder pod instead?

### CODE REVIEW

File: pkg/build/registry/buildlog/rest.go [hunk 1]
```diff
@@ -306,7 +306,10 @@ func (r *REST) Get(ctx apirequest.Context, name string, opts runtime.Object) (ru
 			}
 
 			containerLogOpts := buildapi.BuildToPodLogOptions(buildLogOpts)
-			containerLogOpts.Container = ""
+			//istio auto-inject may add sidecar containers to the build pod
+			//we are interested in getting logs from the build container only
+			containerLogOpts.Container = buildPod.Spec.Containers[0].Name
```
Comment (bparees) [inline pkg/build/registry/buildlog/rest.go]: i'm not totally confident we can rely on the ordering (someone could inject their container earlier in the list, theoretically).  It might be better to iterate looking for containers that match one of our expected names that we use when creating the build pod.

Comment (wozniakjan) [reply pkg/build/registry/buildlog/rest.go]: ok, and are these the container names we are interested in?
```
pkg/build/controller/strategy/sti.go:83:        Name: "sti-build",
pkg/build/controller/strategy/custom.go:90:     Name: "custom-build",
pkg/build/controller/strategy/docker.go:60:     Name: "docker-build",
```

and would it be a good idea to group these in an enum type?

Comment (bparees) [reply pkg/build/registry/buildlog/rest.go]: yeah that should be the list.  having a constant list defined somewhere would make sense.

Comment (bparees) [reply pkg/build/registry/buildlog/rest.go]: (the downside to this approach of course is that we need to keep updating it if we add future images in the future)

Comment (wozniakjan) [reply pkg/build/registry/buildlog/rest.go]: I've tried to group those container names together so hopefully in future, we see where to add the new container names

**Comment by bparees** [comment]
/retest
/lgtm
/hold
(want to see extended_builds pass before this merges)
