### PR TITLE
Fix ProjectNodeSelector config

### LINKED ISSUE #2399: projectNodeSelector doesn't appear in master config via --write-config
Per https://github.com/openshift/origin/pull/2148, expected to see `projectNodeSelector` in a default master config file created with `openshift start --write-config`, but it's absent:

https://gist.github.com/adellape/23c1167e1e1ef2df1534

Same when using `openshift start master --write-config`.

```
# openshift version
openshift v0.5.2-8-g31e42ed
kubernetes v0.17.0-441-g6b6b47a
```

cc: @pravisankar @deads2k @liggitt

### PR DESCRIPTION
**Pull request by liggitt**
Removes json serialization tags from internal config
Removes `omitempty` from serialized config, so the key is always output
Stops trying to validate the node selector string as a file
Removed command line flag for default node selector (config only)

Fixes #2399

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k review

**Comment by deads2k** [comment]
This should probably move to a stanza somewhere, right?  I'd say we take some lumps and make the move.  We can either manage it through clever conversions without a break or simply break it.

**Comment by deads2k** [comment]
It's semi-related to policy I guess.

**Comment by liggitt** [comment]
>  I'd say we take some lumps and make the move

I don't think anyone could reasonably be using it, since specifying it would flag your config as invalid since a file named after the selector didn't exist

**Comment by liggitt** [comment]
updated... thoughts on `projectRequestConfig -> projectConfig`, and moving the default node selector into that stanza?

File: pkg/cmd/server/start/master_args.go [hunk 1]
```diff
@@ -199,7 +199,11 @@ func (args MasterArgs) BuildSerializeableMasterConfig() (*configapi.MasterConfig
 			Latest: args.ImageFormatArgs.ImageTemplate.Latest,
 		},
 
-		ProjectRequestConfig: configapi.ProjectRequestConfig{},
+		ProjectConfig: configapi.ProjectConfig{
+			DefaultNodeSelector:    args.ProjectNodeSelector,
```
Comment (deads2k) [inline pkg/cmd/server/start/master_args.go]: I think I'm against exposing this on `openshift start`.  In keeping with our goal of `openshift start` being the simplest possible toy, this exposure looks unnecessary.  Shall we pull it?

**Comment by deads2k** [comment]
> thoughts on projectRequestConfig -> projectConfig, and moving the default node selector into that stanza?

I like it.

File: pkg/cmd/server/start/master_args.go (hunk 1 above)
Comment (liggitt) [inline pkg/cmd/server/start/master_args.go]: Yes, removed the command line arg. @pravisankar, advanced options like default node selector are only available via config

**Comment by deads2k** [comment]
lgtm 

@smarterclayton confirm that we're good to break config?

**Comment by liggitt** [comment]
@smarterclayton this groups project options under a stanza... the node selector config option validation was broken previously, so I'm confident no one was using it.

@detiber this groups the following options:
```
{# TODO: Allow users to override projectNodeSelector #}
projectNodeSelector: ""
{% if False %}
{# TODO: Allow users to override projectRequestConfig and set sane values #}
projectRequestConfig:
  projectRequestMessage: ""
  projectRequestTemplate: ""
{% endif %}
```
to this:
```
{% if False %}
projectConfig:
  {# TODO: Allow users to override defaultNodeSelector #}
  defaultNodeSelector: ""
  {# TODO: Allow users to override projectRequestMessage/projectRequestTemplate and set sane values #}
  projectRequestMessage: ""
  projectRequestTemplate: ""
{% endif %}
```

**Comment by smarterclayton** [comment]
Acceptable.

**Comment by deads2k** [comment]
[merge]

**Comment by liggitt** [comment]
@adellape this groups project config like this:
```
projectConfig:
  defaultNodeSelector: ""
  projectRequestMessage: ""
  projectRequestTemplate: ""
```

**Comment by liggitt** [comment]
spurious, re[merge]
