### PR TITLE
ext tests: do not modify client namespace when dumping registry logs

### LINKED ISSUE #13576: Extended.[builds][Slow] update failure status Build status fetch builder image failure should contain the fetch builder image failure reason and message
Failing tests:
```
Extended.[builds][Slow] update failure status Build status failed assemble runtime artifacts should contain the failure reason related to failing to fetch runtime image artifacts
Extended.[builds][Slow] update failure status Build status postcommit hook failure should contain the post commit hook failure reason and message
Extended.[builds][Slow] update failure status Build status failed assemble container should contain the failure reason related to an assemble script failing in s2i
Extended.[builds][Slow] update failure status Build status fetch S2I source failure should contain the S2I fetch source failure reason and message
Extended.[builds][Slow] update failure status Build status push image to registry failure should contain the image push to registry failure reason and message
Extended.[builds][Slow] update failure status Build status Docker fetch source failure should contain the Docker build fetch source failure reason and message
Extended.[builds][Slow] update failure status Build status fetch builder image failure should contain the fetch builder image failure reason and message
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended/104

Extended build flake ... failing when trying to retrieve build from 'default' namespace instead of the test namespace.

```
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/failure_status.go:157
Expected error:
    <*errors.StatusError | 0xc4205eb080>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: ""},
            Status: "Failure",
            Message: "User \"extended-test-update-buildstatus-39ldw-jvrjv-user\" cannot get builds in project \"default\"",
            Reason: "Forbidden",
            Details: {
                Name: "statusfail-runtimeartifacts-1",
                Group: "",
                Kind: "builds",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    User "extended-test-update-buildstatus-39ldw-jvrjv-user" cannot get builds in project "default"
not to have occurred
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/builds/failure_status.go:154
```

### PR DESCRIPTION
**Pull request by csrwng**
Fixes #13576 

The code to dump the registry logs was setting the namespace on the derived admin client to "default" which also set it on the original client. Now saving the original namespace so it can be restored after retrieving the registry logs.

### CODE REVIEW

File: test/extended/util/framework.go [hunk 1]
```diff
@@ -390,13 +390,19 @@ func (t *BuildResult) dumpRegistryLogs() {
...
+	// here so we can restore it when done with registry logs
+	savedNamespace := t.oc.Namespace()
 	oadm := t.oc.AsAdmin().SetNamespace("default")
 	out, err := oadm.Run("logs").Args("dc/docker-registry", "--since="+since.String()).Output()
 	if err != nil {
 		fmt.Fprintf(g.GinkgoWriter, "Error during log retrieval: %+v\n", err)
 	} else {
 		fmt.Fprintf(g.GinkgoWriter, "%s\n", out)
 	}
+	t.oc.SetNamespace(savedNamespace)
```
Comment (bparees) [inline test/extended/util/framework.go]: not AsAdmin?  couldn't there be cases where the namespace is only accessible as admin?

Comment (csrwng) [inline test/extended/util/framework.go]: There really is no validation of the namespace you tell it to use besides setting it inside the kubeFramework struct. AsAdmin() will create a copy of the oc client and point it to the admin.kubeconfig. The problem above is that the copy is only a shallow copy, oadm (which you get by calling oc.AsAdmin()) and oc both point to the same kubeFramework object. It doesn't matter on which you call SetNamespace.

Comment (bparees) [inline test/extended/util/framework.go]: k

**Comment by bparees** [comment]
[merge]
