### PR TITLE
User can get only blobs he's able to see

### LINKED ISSUE #6841: Plan for cross-repo Docker mounting in the registry
Now that cross-repo mounting has landed in docker/distribution and the engine, we should plan for what we need to do to support it.  I think it's as simple as a test read on the other repo, in which case the performance win should be massive as long as the docker daemon is properly associating the image we pulled with a credential for push.

### LINKED ISSUE #9755: Docker registry allows to serve any blob user wants
Previously there was an authorization check comprising of existence check on a layer link inside the repository.

We're skipping layer links completely now. The [`Stat()`](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/errorblobstore.go#L22) and [`ServeBlob()`](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/errorblobstore.go#L76) calls reach directly to global registry blob store (storing blobs pushed to the registry). Because of that, any user, who is authorized to pull from at least one repository, can pull any blob he wants. Thanks to our [blobDescriptorService()](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/blobdescriptorservice.go#L29).

The only restriction from pulling any blob a user wants is that he doesn't know what blobs are stored in the registry unless he is able to get somehow an image manifest or image object.

##### Version
Docker registry 2.4.0.

##### Steps To Reproduce
1. push any image as a userA to image stream **A/IS**
2. choose one of its layers (`oc get -o yaml isimage <imagename>`), let's call it layer **L**
3. login as a userB
4. create a new project **P** and a new image stream in there (`oc create imagestream IS`)
5. stat the blob using simple curl:

```
$ curl -v -X HEAD -u "userB:$btoken" "$registry_url/v2/P/IS/blobs/L"
``` 

##### Current Result
```
* About to connect() to 172.30.241.183 port 5000 (#0)
*   Trying 172.30.241.183...
* Connected to 172.30.241.183 (172.30.241.183) port 5000 (#0)
* Server auth using Basic with user 'alice'
> HEAD /v2/target/busybox/blobs/sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f HTTP/1.1
> Authorization: Basic YWxpY2U6d1RyTFN6VnQxTjJvREl5ZENrVDEzR1pTekZsMnFYWVlYYmdDQmw4QzRPWQ==
> User-Agent: curl/7.29.0
> Host: 172.30.241.183:5000
> Accept: */*
> 
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Cache-Control: max-age=31536000
< Content-Length: 667590
< Content-Type: application/octet-stream
< Docker-Content-Digest: sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f
< Docker-Distribution-Api-Version: registry/2.0
< Etag: "sha256:8ddc19f16526912237dd8af81971d5e4dd0587907234be2b83e249518d5b673f"
< Date: Fri, 08 Jul 2016 15:28:43 GMT
```
##### Expected Result
Unauthorized

##### Additional info
Suggested priority: P1

### PR DESCRIPTION
**Pull request by miminar**
Closes #9755, closes #6841

This PR fixes several issues:

1. The most important is a fix for #9819. Where a user authorized to a single repository can pull any blob stored in the registry.
2. This also enables cross-repo mount feature. It allows a client to *mount* a blob from another repository in the registry to the destination repository (the target of the push). Docker client remembers source registry/repository for each layer it pulled. During a push of a blob **B** to a repository **D**, it instructs the registry to mount **B** from another repository **S** in the same registry if it previously pulled the blob from there. This speeds up push time a lot. This PR enables this functionality **only** for local repositories.
3. It fixes a bug in digestToRepositoryCache.RememberDigest where the first association inserted was lost immediately.
4. It ensures that DockerImageManifestMediaType gets set for all the new and existing images. This requires no migration.

The 1st issue is addressed by replacing regular layer link Stat call done in our blobDescriptorService with a fall-back to image stream images in etcd. The blob must exist either locally or remotely if a remote image is tagged in the image stream. If it's tagged locally, the blob<->repository cache will be checked before the etcd query.

It's blobDescriptorService is nearly a lowest possible level where we can intercept Stat calls on local blobs. Unfortunately blob descriptor service doesn't know, which repository is being accessed without being told via context. That's why upper layers need to set repository on the context for every method that may invoke Stat or Clear on a local layer link.

The fix for 2nd issue is applies only to local repositories. Mounting from remotes needs to be addressed specifically. There's a follow-up #10120.

### CODE REVIEW

**Comment by miminar** [comment]
Quick&dirty. I'll polish tomorrow.

[test]

File: pkg/image/api/helper.go [hunk 1]
```diff
@@ -463,6 +463,8 @@ func ImageWithMetadata(image *Image) error {
 			return nil
 		}
 
+		image.DockerImageManifestMediaType = schema1.MediaTypeManifest
```
Comment (smarterclayton) [inline pkg/image/api/helper.go]: We'll need the migrator in order to make this work then?  How will a user upgrading get the correct behavior?  Or is this just extra data we forgot?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 2]
```diff
@@ -25,6 +38,140 @@ type blobDescriptorService struct {
...
+
+	processedBlobs := map[string]struct{}{}
+	processedImages := map[string]struct{}{}
+
+	for _, tagEvent := range tagEvents {
+		if _, processed := processedImages[tagEvent.Image]; processed {
+			continue
+		}
+		if imageHasBlob(r, processedBlobs, match, tagEvent.Image, dgst.String(), !r.pullthrough) {
+			tagName := event2Name[tagEvent]
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: So the big question is the access pattern - you do the cache on *all* candidate images (which fills the digest cache pretty rapidly), but we might only want to cache the image that we actually found's layers.  Is there a case where a user is going to pull two images from the same image stream in close succession?

Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Also, you added `rememberLayersOfImage` below but you don't use it from `imageHasBlob`?

File: test/end-to-end/core.sh [hunk 3]
```diff
@@ -44,6 +44,14 @@ function wait_for_app() {
   os::cmd::try_until_text "curl -s http://${FRONTEND_IP}:5432/keys/foo" "1337"
 }
 
+function remove_docker_images() {
```
Comment (smarterclayton) [inline test/end-to-end/core.sh]: Why do this?

Comment (smarterclayton) [inline test/end-to-end/core.sh]: nm, I see this is extracting existing code

File: pkg/image/api/helper.go (hunk 1 above)
Comment (miminar) [inline pkg/image/api/helper.go]: It should be already set for all the schema2 manifests. It's set by the registry on a push and by importer on import. All the code using this field is written with this in mind (empty value is considered as schema v1).

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 2 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > but we might only want to cache the image that we actually found's layers. Is there a case where a user is going to pull two images from the same image stream in close succession?

Good catch. It seemed to me like a waste to throw away the fetched data. But using this approach we may push out frequently accessed items if the cache is close to full.

> Also, you added rememberLayersOfImage below but you don't use it from imageHasBlob?

I planned to use it but it proved as not useful in the end. I'll remove it.

File: test/end-to-end/core.sh [hunk 4]
```diff
@@ -190,9 +209,32 @@ echo "[INFO] Docker login successful"
...
+os::cmd::expect_success "oc new-project crossmount"
+os::cmd::expect_success "oc create imagestream repo"
+
 echo "[INFO] Back to 'default' project with 'admin' user..."
 os::cmd::expect_success "oc project ${CLUSTER_ADMIN_CONTEXT}"
 os::cmd::expect_success_and_text 'oc whoami' 'system:admin'
+os::cmd::expect_success "oc tag --source docker centos/ruby-22-centos7:latest -n custom ruby-22-centos7:latest"
+os::cmd::expect_success 'oc policy add-role-to-user registry-viewer pusher -n custom'
+
+os::cmd::expect_success_and_text "curl -I -X HEAD -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/$rubyimageblob'" "404 Not Found"
```
Comment (smarterclayton) [inline test/end-to-end/core.sh]: Can you do a test of cross mount of a pull through image?  If it's currently broken due to the lookup problem that's ok, I just want a test either way.

Comment (miminar) [inline test/end-to-end/core.sh]: > Can you do a test of cross mount of a pull through image? If it's currently broken due to the lookup problem that's ok, I just want a test either way.

See the last curl. I'll add a `pullthrough` comment so it's obvious.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 2 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > I planned to use it but it proved as not useful in the end. I'll remove it.

Caching just the layers of matching image now. The `rememberLayersOfImage` is useful after all. Leaving it as is.

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 5]
```diff
@@ -25,6 +38,137 @@ type blobDescriptorService struct {
...
+	if err != nil {
+		if kerrors.IsNotFound(err) {
+			context.GetLogger(r.ctx).Debugf("image %q not found: imageName")
+		} else {
+			context.GetLogger(r.ctx).Errorf("failed to get image: %v", err)
+		}
+		return false
+	}
+
+	if managed := image.Annotations[imageapi.ManagedByOpenShiftAnnotation]; requireManaged && managed != "true" {
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: If you've tagged in an image successfully, you've proved you have access to it.  All this case guards against is pullthrough (for now).  Can you add a comment describing why this is needed?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 6]
```diff
@@ -25,6 +38,137 @@ type blobDescriptorService struct {
...
+
+	// verify that an image holding this blob is actually present in the image stream
+	repo, found := RepositoryFrom(ctx)
+	if !found {
+		context.GetLogger(ctx).Errorf("failed to retrieve repository from context")
+		return distribution.Descriptor{}, distribution.ErrBlobUnknown
+	}
+
+	if imageStreamHasBlob(repo, dgst) {
+		return desc, err
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Shouldn't this be desc, nil?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 7]
```diff
@@ -25,6 +38,137 @@ type blobDescriptorService struct {
...
+	return distribution.Descriptor{}, distribution.ErrBlobUnknown
+}
+
+// imageStreamHasBlob returns true if the given blob digest is referenced in image stream corresponding to
+// given repository. If not found locally, image stream's images will be iterated and fetched from newest to
+// oldest until found. Each processed image will update local cache of blobs.
+func imageStreamHasBlob(r *repository, dgst digest.Digest) bool {
+	repositories := r.cachedLayers.RepositoriesForDigest(dgst)
+	match := imageapi.DockerImageReference{Namespace: r.namespace, Name: r.name}.Exact()
+	for _, repo := range repositories {
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: What's the expiration on the cache?  This check will allow someone to maintain access to an image for that period of time after their image is untagged.  In practice if the expiration is low we are ok, but if it is high admins may be at risk.  In practice a user may have a running pod already with the image, which means they can already keep access to an image after removed.

We *may* need to make the cache duration configurable and document the trade off.  At worst, the cache expiration needs to be in the low minutes (5-10).

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 8]
```diff
@@ -25,6 +38,137 @@ type blobDescriptorService struct {
 	distribution.BlobDescriptorService
 }
 
+// Stat returns a a blob descriptor if the given blob is either linked in repository or is referenced in
+// corresponding image stream. This method is invoked from inside of upstream's linkedBlobStore. It expects
+// a proper repository object to be set on given context by upper openshift middleware wrappers.
 func (bs *blobDescriptorService) Stat(ctx context.Context, dgst digest.Digest) (distribution.Descriptor, error) {
-	return dockerRegistry.BlobStatter().Stat(ctx, dgst)
+	// if there is a repo layer link, return its desc
+	desc, err := bs.BlobDescriptorService.Stat(ctx, dgst)
```
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Is there a cache for this already in the registry?

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 7 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: The access to the manifest is lost once it's untagged. Ideally, access to its blobs should be denied at the same time. However, even if we ditch the cache, we're still using layer links. These won't be removed until pruned. Client will most probably hit the link itself during stat. So proper pruning is of higher priority to deal with this extended access.

Nevertheless the TTL should be configurable indeed. Otherwise, with few enough images, the entries may never get  out of cache until registry is restarted.

I'll add a TTL.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 6 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > Shouldn't this be desc, nil?

It should.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 8 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > Is there a cache for this already in the registry?

Ahh, I completely forgot. There is. It's a wrapper just above this wrapper. In our default config it's `inmemory` cache. Unfortunately it's not expiring and boundless. We need to turn it off.

Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: We may need to reorder it rather than turning it off - my worry is
that lower code depends on it.

Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > We may need to reorder it rather than turning it off - my worry is that lower code depends on it.

Not really. The order of wrappers and stores is:

    errorBlobStore { pullthroughBlobStore { quotaRestrictedBlobStore { linkedBlobStore { cachedBlobStatter {
       cache: inMemoryBlobDescriptorCacheProvider,
       backend: blobDescriptorService { upstreamBlobDescriptorService },
    }}}}}

The inMemoryCache will be updated with any successful stat we return with our backend and the result will be kept forever. Reordering (moving our blobDescriptorService one level up) is not possible without patching upstream again. I'd rather use `cachedLayers` cache as a replacement for the inMemoryCache because in our case all the layer links and etcd data are ephemeral with proper periodic pruning.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 5 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Comment added.

File: pkg/dockerregistry/server/errorblobstore.go [hunk 9]
```diff
@@ -23,44 +24,50 @@ func (r *errorBlobStore) Stat(ctx context.Context, dgst digest.Digest) (distribu
...
 	}
-	if err := checkPendingCrossMountErrors(ctx, opts); err != nil {
-		context.GetLogger(r.repo.ctx).Debugf("disabling cross-mount because of pending error: %v", err)
-		options = append(options, guardCreateOptions{DisableCrossMount: true})
-	} else {
-		options = append(options, guardCreateOptions{})
+	isCrossMount, err := checkPendingCrossMountErrors(ctx, opts)
+	if isCrossMount {
+		if err != nil {
+			context.GetLogger(ctx).Infof("disabling cross-repo mount because o error: %v", err)
```
Comment (soltysh) [inline pkg/dockerregistry/server/errorblobstore.go]: s/o error/of an error

**Comment by soltysh** [comment]
Why we want to carry a patch to distribution? Have we tried upstreaming the fix?

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 8 above)
Comment (smarterclayton) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: So the *only* place in memory cache was being used was here?  No one else
is expecting to make blob store calls that are inexpensive (because they're
guarded by the cache) but will only find out that they are very expensive?

File: test/end-to-end/core.sh [hunk 10]
```diff
@@ -204,9 +209,32 @@ echo "[INFO] Docker login successful"
...
+os::cmd::expect_success_and_text "curl -I -X HEAD -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/cache/ruby-22-centos7/blobs/$rubyimageblob'" "200 OK"
+# 202 means that cross-repo mount has failed (in this case because of blob doesn't exist in the source repository), client needs to reupload the blob
+os::cmd::expect_success_and_text "curl -I -X POST -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/uploads/?mount=$rubyimageblob&from=cache/hello-world'" "202 Accepted"
```
Comment (smarterclayton) [inline test/end-to-end/core.sh]: Add negative tests that verify a user who doesn't have access gets an explicit error on push (when nothing is mounted).  Also that they can't access the blob directly, and that users don't have access to the blobs.  Tests probably need to be both here and in the unit tests.

File: pkg/dockerregistry/server/auth.go [hunk 11]
```diff
@@ -61,46 +47,85 @@ func init() {
...
+// API. It needs to be wrapped using wrapErr() before passing up to request dispatcher to generate proper auth
+// challenge error.
+type errAccessDenied struct {
+	err    error
+	reason string
+}
+
+func (e *errAccessDenied) Error() string {
+	if e.err != nil {
+		return fmt.Sprintf("OpenShift client error: %v", e.err)
```
Comment (liggitt) [inline pkg/dockerregistry/server/auth.go]: don't put "OpenShift" in error messages... this is shared with atomic registry

File: pkg/dockerregistry/server/errorblobstore.go [hunk 12]
```diff
@@ -107,7 +95,7 @@ func checkPendingCrossMountErrors(ctx context.Context, opts *storage.CreateOptio
 	if err != nil {
 		return err
 	}
-	return checkPendingErrors(context.GetLogger(ctx), ctx, namespace, name)
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: previously, we differentiated between the context held by the startup code, and the request context. not sure if that's important, but this was preserving that

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 13]
```diff
@@ -621,34 +611,6 @@ func (r *repository) getSignatures(dgst digest.Digest) ([]digest.Digest, error)
...
-func (r *repository) deserializedManifestFromImage(image *imageapi.Image) (*schema2.DeserializedManifest, error) {
-	var manifest schema2.DeserializedManifest
-	if err := json.Unmarshal([]byte(image.DockerImageManifest), &manifest); err != nil {
-		return nil, err
-	}
-	return &manifest, nil
-}
-
 func (r *repository) checkPendingErrors(ctx context.Context) error {
-	return checkPendingErrors(context.GetLogger(r.ctx), ctx, r.namespace, r.name)
```
Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: previously, we differentiated between the context held by the startup code (used to look up the logger), and the request context. not sure if that's important, but this was preserving that

File: pkg/dockerregistry/server/auth_test.go [hunk 14]
```diff
@@ -30,16 +32,17 @@ import (
...
+		openshiftResponse   response
+		expectedErrorString string
 	}{
 		{
-			// Test invalid openshift bearer token
-			openshiftResponse: response{401, "Unauthorized"},
-			expectedError:     ErrOpenShiftAccessDenied,
+			name:                "invalid openshift bearer token",
+			openshiftResponse:   response{401, "Unauthorized"},
+			expectedErrorString: "OpenShift client error:",
```
Comment (liggitt) [inline pkg/dockerregistry/server/auth_test.go]: why is this not checking the exact type?

File: pkg/dockerregistry/server/auth_test.go [hunk 15]
```diff
@@ -48,10 +51,10 @@ func TestVerifyImageStreamAccess(t *testing.T) {
 					Reason:    "not authorized!",
 				}),
 			},
-			expectedError: ErrOpenShiftAccessDenied,
+			expectedErrorString: "OpenShift access denied",
```
Comment (liggitt) [inline pkg/dockerregistry/server/auth_test.go]: same here, we should check the exact type

File: pkg/dockerregistry/server/auth.go [hunk 16]
```diff
@@ -345,18 +359,15 @@ func verifyImageStreamAccess(ctx context.Context, namespace, imageRepo, verb str
 		},
 	}
 	response, err := client.LocalSubjectAccessReviews(namespace).Create(&sar)
-
 	if err != nil {
-		context.GetLogger(ctx).Errorf("OpenShift client error: %s", err)
 		if kerrors.IsUnauthorized(err) || kerrors.IsForbidden(err) {
-			return ErrOpenShiftAccessDenied
+			return &errAccessDenied{err: err}
```
Comment (liggitt) [inline pkg/dockerregistry/server/auth.go]: the point of having a typed error is that we can compare against it. we also don't want to surface internal errors to the end user

File: pkg/dockerregistry/server/auth.go [hunk 17]
```diff
@@ -251,56 +256,65 @@ func (ac *AccessController) Authorized(ctx context.Context, accessRecords ...reg
...
-		return "", "", ErrNamespaceRequired
-	}
-	name := repoParts[1]
-	if len(name) == 0 {
-		return "", "", ErrNamespaceRequired
+// wrapErr wraps errors related to authorization in an authChallenge error that will present a WWW-Authenticate challenge response
+func (ac *AccessController) wrapErr(ctx context.Context, err error) error {
+	switch err.(type) {
+	case *errAccessDenied:
+		context.GetLogger(ctx).Error(err.Error())
```
Comment (liggitt) [inline pkg/dockerregistry/server/auth.go]: I would not expect wrapErr to be logging... doing so means that we could still get nasty error messages logged for benign cases like this: https://github.com/openshift/origin/pull/9819/commits/c4f5056a29c8fda4794572327572e636d927d0a7#diff-4fcaa728857c0df2a0e21105899aedb3R285

**Comment by liggitt** [comment]
please separate out the error/auth/logging refactor commits from this PR

**Comment by miminar** [comment]
> Why we want to carry a patch to distribution? Have we tried upstreaming the fix?

The carry patch code have been submitted upstream docker/distribution#1757 but was changed to expose just CreateOptions (we already carry a patch for that 8c8bc43bcc2dd921ca3076f64014eac4e0716acb). Actually, we need both variants of the patch. I'll re-submit this once again, or perphaps I'll join both patches into a single PR.

**Comment by soltysh** [comment]
> I coined a carry patch to address P0 issue quickly. Negotiating with distribution upstream takes a lot of time.

So is the time needed to carry those. 

> I'll re-submit this once again, or perphaps I'll join both patches into a single PR.

Yes, please.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 8 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > So the *only* place in memory cache was being used was here?  No one else is expecting to make blob store calls that are inexpensive (because they're guarded by the cache) but will only find out that they are very expensive?

I made a bad mistake. The inmemory cache is used also for stat-ing the global blob store. If turned off, all the stats will take much longer when done against slow storage.

And I was wrong also in the case of the order. Our `blobDescriptorService` actually wraps the `cachedBlobStatter` (see the updated comment above). So functional-wise we're fine having it enabled. Unfortunately, it doubles the memory usage per blob cached. We'd better push upstream an ability for defining our own `blobDescriptorCacheProvider`.

That can be easily done as a follow-up. For now, I'll just re-enable the inmemory cache.

**Comment by miminar** [comment]
> please separate out the error/auth/logging refactor commits from this PR, we need to keep this PR as small and targeted as possible

Removed, I'll open separate PR for the logging refactor.

File: pkg/dockerregistry/server/errorblobstore.go [hunk 18]
```diff
@@ -23,44 +24,50 @@ func (r *errorBlobStore) Stat(ctx context.Context, dgst digest.Digest) (distribu
...
 	if err != nil {
 		return nil, err
 	}
-	if err := checkPendingCrossMountErrors(ctx, opts); err != nil {
-		context.GetLogger(r.repo.ctx).Debugf("disabling cross-mount because of pending error: %v", err)
-		options = append(options, guardCreateOptions{DisableCrossMount: true})
-	} else {
-		options = append(options, guardCreateOptions{})
+	isCrossMount, err := checkPendingCrossMountErrors(ctx, opts)
+	if isCrossMount {
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: don't make this conditional... I always want the guardCreateOptions in place so we don't silently unprotect something if other types of distribution.BlobCreateOption objects start getting passed through

File: test/end-to-end/core.sh (hunk 10 above)
Comment (miminar) [inline test/end-to-end/core.sh]: > Tests probably need to be both here and in the unit tests.

[Auth unit tests](https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/auth_test.go) seem sufficient to me. Additional negative tests have been just added by @liggitt's https://github.com/openshift/origin/commit/d1796620d753a09503ba7dd346c52f536c0b4434#diff-4ea7c8f0aaeae849c3760842d6b42c60R194

**Comment by miminar** [comment]
Flake #9951. re-[test]

File: test/end-to-end/core.sh (hunk 10 above)
Comment (smarterclayton) [inline test/end-to-end/core.sh]: I don't think they cover it, we need blob tests for authenticated users,
and users with similar / overlapping namespace permissions.  We also need
to explicitly call out the cached permissions behavior with a test.

**Comment by miminar** [comment]
I've submitted the carry patch upstream as docker/distribution#1857 with minor changes. I'm backporting to 2.4.0 a rebasing this on top. Will re-submit soon.

File: pkg/dockerregistry/server/errorblobstore.go (hunk 18 above)
Comment (miminar) [inline pkg/dockerregistry/server/errorblobstore.go]: > don't make this conditional

fixed

File: vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go [hunk 19]
```diff
@@ -289,11 +281,19 @@ func (lbs *linkedBlobStore) Enumerate(ctx context.Context, ingestor func(digest.
...
 
-func (lbs *linkedBlobStore) mount(ctx context.Context, sourceRepo reference.Named, dgst digest.Digest) (distribution.Descriptor, error) {
+func (lbs *linkedBlobStore) mount(ctx context.Context, repoOverride distribution.RepositoryOverride, sourceRepo reference.Named, dgst digest.Digest) (distribution.Descriptor, error) {
 	repo, err := lbs.registry.Repository(ctx, sourceRepo)
 	if err != nil {
 		return distribution.Descriptor{}, err
 	}
+
+	if repoOverride != nil {
+		repo, err = repoOverride(ctx, repo)
```
Comment (liggitt) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: this seems really heavyweight... why wouldn't we just add an optional `Stat *distribution.Descriptor` field to the `Mount` struct? If present, the repo/blobs/stat calls are not needed at all

Comment (liggitt) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: see the last couple commits in https://github.com/liggitt/origin/commits/miminar-remote-layer-federation as an example. That keeps the flow of information going in one direction, and I'd prefer a smaller upstream change like that

Comment (miminar) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: > why wouldn't we just add an optional Stat *distribution.Descriptor field to the Mount struct

@liggitt good idea, I like it. I'll amend your commit a bit to stat the source repository.

My initial feeling was that upstream code should work with wrapped objects everywhere. Not just using wrapped ones on some places and their own on others. However, the less intrusive change, the higher chances to be accepted upstream.

Comment (liggitt) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: was the intent to stat the source one first and fall back to our wrapped repo in failure cases?

Comment (miminar) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: > was the intent to stat the source one first and fall back to our wrapped repo in failure cases?

the intent was just to use the wrapped one which, internally, first stats the source local repo and then falls back to pullthrough stat for corresponding source image stream

Comment (miminar) [inline vendor/github.com/docker/distribution/registry/storage/linkedblobstore.go]: @liggitt applied most of your changes. Thanks!

**Comment by miminar** [comment]
I'll try to make a better coverage.

**Comment by miminar** [comment]
re-[test]

I got side-tracked today (need to finish rebase of the registry for 3.2). I will finish extending the tests next week.

**Comment by liggitt** [comment]
Doesn't this need to be part of the 3.2 back port?

**Comment by miminar** [comment]
> Doesn't this need to be part of the 3.2 back port?

It should. Though it's yet unknown whether and when it will happen. The backport PR shall be up to date with whatever registry fixes are in origin:master.

**Comment by miminar** [comment]
During testing I found additional problems. It's possible to stat/get a blob from a repository whose corresponding image stream has been removed. This seems to be a case for pre 2.4 as well. I'll include a fix in this PR.

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 20]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
 	distribution.BlobDescriptorService
 }
 
+// Stat returns a a blob descriptor if the given blob is either linked in repository or is referenced in
+// corresponding image stream. This method is invoked from inside of upstream's linkedBlobStore. It expects
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: is "This method is invoked from inside of upstream's linkedBlobStore" still accurate with the modified upstream?

Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Yes, it is. It just doesn't apply to a cross-repo mount stat in the source repository anymore. All the other stat calls go through this service.

**Comment by miminar** [comment]
I've extended the PR just with the non-existent-image-stream fix. The additional tests are not yet in review-able state. I'll submit them tomorrow.

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 21]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+			// and remember the association
+			repo.cachedLayers.RememberDigest(dgst, repo.blobrepottl, imageapi.DockerImageReference{
+				Namespace: repo.namespace,
+				Name:      repo.name,
+			}.Exact())
+		}
+		return desc, err
+	}
+
+	if !repoFound {
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: don't need to check this, short-circuited already on !repoFound above

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 22]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+		return distribution.Descriptor{}, distribution.ErrBlobUnknown
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: should we be returning this or just propagating the error we received?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 23]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
-	return dockerRegistry.BlobStatter().Stat(ctx, dgst)
+	repo, repoFound := RepositoryFrom(ctx)
+	if !repoFound {
+		context.GetLogger(ctx).Errorf("failed to retrieve repository from context")
+	}
+
+	// if there is a repo layer link, return its descriptor
+	desc, err := bs.BlobDescriptorService.Stat(ctx, dgst)
+	if err == nil {
+		if repoFound {
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: don't need to check this, we already made sure we have a repo above

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 24]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+			// and remember the association
+			repo.cachedLayers.RememberDigest(dgst, repo.blobrepottl, imageapi.DockerImageReference{
+				Namespace: repo.namespace,
+				Name:      repo.name,
+			}.Exact())
+		}
+		return desc, err
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: `return desc, nil`

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 25]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+}
+
+func (bs *blobDescriptorService) Clear(ctx context.Context, dgst digest.Digest) error {
+	if repo, found := RepositoryFrom(ctx); found {
+		repo.cachedLayers.ForgetDigest(dgst, imageapi.DockerImageReference{
+			Namespace: repo.namespace,
+			Name:      repo.name,
+		}.Exact())
+	} else {
+		context.GetLogger(ctx).Errorf("failed to retrieve repository from context")
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: is this really an error?

Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: and if so, should we still be calling `bs.BlobDescriptorService.Clear(ctx, dgst)`? what does clearing the descriptor do? would that affect other users of this blob?

File: pkg/dockerregistry/server/digestcache.go [hunk 26]
```diff
@@ -52,42 +64,122 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
+			entry := arr[index]
+			copy(arr[index:], arr[index+1:])
+			if entry.evictOn.Before(evictOn) {
+				entry.evictOn = evictOn
+			}
+			arr[len(arr)-1] = entry
+
+		} else {
+			// repository is a new entry
+			if len(arr) >= bucketSize {
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: we only remember 10 repos for a given layer? won't common layers in sti images, etc, be in hundreds of repos?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 27]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+		context.GetLogger(r.ctx).Debugf("skipping not managed image")
+		return false
+	}
+
+	if len(image.DockerImageLayers) == 0 {
+		if len(image.DockerImageManifestMediaType) > 0 {
+			// image has no layers
+			return false
+		}
+		err = imageapi.ImageWithMetadata(image)
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: should fix the godoc on ImageWithMetadata to indicate it mutates the passed image

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 28]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+		processedImages[tagEvent.Image] = struct{}{}
+	}
+
+	context.GetLogger(r.ctx).Warnf("blob %q exists locally but is not referenced in repository %s/%s", dgst.String(), r.namespace, r.name)
+
+	return false
+}
+
+// imageHasBlob returns true if the image identified by imageName refers to the given blob. The image is
+// fetched. If requireManged is true and the image is not managed (it refers to remote registry), the image
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: s/requireManged/requireManaged/

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 29]
```diff
@@ -25,6 +38,155 @@ type blobDescriptorService struct {
...
+// a proper repository object to be set on given context by upper openshift middleware wrappers.
 func (bs *blobDescriptorService) Stat(ctx context.Context, dgst digest.Digest) (distribution.Descriptor, error) {
-	return dockerRegistry.BlobStatter().Stat(ctx, dgst)
+	repo, repoFound := RepositoryFrom(ctx)
+	if !repoFound {
+		context.GetLogger(ctx).Errorf("failed to retrieve repository from context")
+	}
+
+	// if there is a repo layer link, return its descriptor
+	desc, err := bs.BlobDescriptorService.Stat(ctx, dgst)
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: are we just assuming our `blobDescriptorService{}` was set up to contain a nested `BlobDescriptorService` that does ACL checks?

File: pkg/dockerregistry/server/digestcache.go [hunk 30]
```diff
@@ -52,42 +64,122 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
+			b.list = b.list[:len(b.list)-1]
 		}
-		arr = append(arr, repo)
 	}
-	i.list = arr
+}
+
+// getIndexOf returns an index of given repository in bucket's array. If not found, -1 will be returned.
+// If now is given, all the entries with eviction time before now will be removed.
+func (b *repositoryBucket) getIndexOf(repo string, now *time.Time) int {
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: getIndexOf mutating the list is very unexpected. split this into two functions, one that searches for a repo, and one that evicts things with expired TTLs

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 29 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Yes. That's how [the upstream code](https://github.com/miminar/distribution/blob/master/registry/storage/registry.go#L292) currently looks like. We don't have a warranty it will stay this way. What we can do is add a unit tests invoking various stat/get/create methods and ensuring this or some mock blobDescriptorService gets called. Would that be a sufficient guaranty?

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 23 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: The above check doesn't return. It just logs the error. I wanted to fallback to regular stat if the repository isn't set. But I guess that in such a case something went badly wrong and we should return - I'll make it so.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 21 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: we haven't  ... yet

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 22 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: We should propagate.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 25 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > is this really an error?

If it's an error in `Stat`, it's certainly an error here. Our `errorBlobStore` must make sure that repository is set for each and every method call. If unset, there's an error in our code.

> and if so, should we still be calling bs.BlobDescriptorService.Clear(ctx, dgst)? what does clearing the descriptor do? would that affect other users of this blob?

I'm not sure. In this case we clear layer link pointing to a blob. That means the blob won't be gettable from the repository unless it stays referenced in corresponding image stream.

Since I'll be reworking the Stat call to fail immediately on repository unset, I'll do the same here.

File: pkg/dockerregistry/server/digestcache.go (hunk 26 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: That's possible, but I don't expect all of the repositories to be searched equally. This structure doesn't really fit the way  layers are spread across repositories. There's an empty layer which will be practically in each repository. There will be layers unique to particular repositories as well. Perhaps a priority queue storing pairs of (`blob`, `repository`) would be more fitting.

I don't find it necessary to rework the data structure completely in this PR. Would the current structure be sufficient with maybe some amendments to the size constraints until some follow-up?

File: pkg/dockerregistry/server/digestcache.go (hunk 30 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: > getIndexOf mutating the list is very unexpected. split this into two functions, one that searches for a repo, and one that evicts things with expired TTLs. Move the check for expired TTL into Has

Will do.

**Comment by soltysh** [comment]
The e2e changes LGTM.

File: images/dockerregistry/config.yml [hunk 31]
```diff
@@ -23,5 +23,6 @@ middleware:
         pullthrough: true
         enforcequota: false
         projectcachettl: 1m
+        blobrepottl: 10m
```
Comment (smarterclayton) [inline images/dockerregistry/config.yml]: Pick a name that is more descriptive - `linkedblobcachettl`

Comment (miminar) [inline images/dockerregistry/config.yml]: `linkedblobcachettl` doesn't seem right since the ttl applies not only to local layer links but to the remote blobs as well. What about `blobrepositorycachettl`?

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 27 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > should fix the godoc on ImageWithMetadata to indicate it mutates the passed image

godoc'd

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 28 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > s/requireManged/requireManaged/

fixed

File: pkg/dockerregistry/server/digestcache.go (hunk 26 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: I've raised the number of most frequented repositories for a blob to remember to 16. Still not much big a number but let's keep low on resources for now and rework the caching from the ground afterwards.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 21 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > drop this block, we short-circuited already on !repoFound above

Really short-circuiting now and block dropped.

**Comment by miminar** [comment]
Still working on a test coverage for repository middleware.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 29 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > are we just assuming our blobDescriptorService{} was set up to contain a nested BlobDescriptorService that does ACL checks?

I added a unit test verifying that the `blobDescriptorService` is used with the upstream App.

**Comment by miminar** [comment]
> During testing I found additional problems. It's possible to stat/get a blob from a repository whose corresponding image stream has been removed. This seems to be a case for pre 2.4 as well. 

Fixing this would require nontrivial changes to the way we store layer links and would involve migration. It will have to be fixed in some later PR. I'll create an issue for that.

**Comment by smarterclayton** [comment]
Does the link need to be removed from all historical blobs?

**Comment by miminar** [comment]
> Does the link need to be removed from all historical blobs?

I'm not sure what you mean by historical blobs. The stat performed on a layer link verifies not only the presence of the link, but the presence of the blob itself. If there is a dangling layer link in some repository (pointing to a deleted blob), the stat will fail. Otherwise existing blob and layer link in the repository means it can be pulled from the repository regardless of whether the image stream exists or not.

Reworked image pruning will get rid us of dangling links, unreferenced links and unreferenced blobs.

My worry is that the blob will be pull-able from the repository for possibly long time since the image is untagged or imagestream deleted until the scheduled prune operation kicks in.

**Comment by miminar** [comment]
I found a bug in digestcache where the first association was always immediately lost. Added a test coverage which hits cache and misses after eviction timeout. Hoping for clean pass.

**Comment by smarterclayton** [comment]
I mean, should we write a migration that deletes all layer links out of the
registry (once we roll out this change)?  At that point there will be no
links to pull.

**Comment by miminar** [comment]
> I mean, should we write a migration that deletes all layer links out of the registry (once we roll out this change)?  At that point there will be no links to pull.

It would be safer. But the orphaned layer links will keep piling up nevertheless until we rework image pruning (due to `oc delete image/... imagestream/...`).

Note that this is not a regression (it's just a regression from the way how it should work). Blobs could be pulled this way long before a rebase to 2.4.

Moreover, the migration tool would have to trigger some pruner inside the registry or operate directly on registry's storage. Even though we can delete layer links from outside, we have no way to list them (the orphaned ones).

**Comment by miminar** [comment]
Made the unit tests race free.

**Comment by miminar** [comment]
Looks like flake #9775.

**Comment by miminar** [comment]
Flake #9856. re-[test]

**Comment by miminar** [comment]
Another  #9775. re-[test]

**Comment by miminar** [comment]
I've just found one more glitch which breaks cross-repo mount from remote registry. I'll fix and re-submit.

**Comment by miminar** [comment]
Instead of adding another commit to this huge PR, I decided to do a follow-up instead. #10120 enables remote layer federation.

**Comment by miminar** [comment]
@liggitt thanks for the input so far. Is there anything else I can improve?

**Comment by mfojtik** [comment]
@liggitt can we merge this?

File: vendor/github.com/docker/distribution/testutil/handler.go [hunk 32]
```diff
@@ -0,0 +1,148 @@
+package testutil
```
Comment (liggitt) [inline vendor/github.com/docker/distribution/testutil/handler.go]: is this actually a carry or just committing an existing package we now depend on?

File: pkg/image/api/helper.go [hunk 33]
```diff
@@ -463,6 +463,8 @@ func ImageWithMetadata(image *Image) error {
 			return nil
```
Comment (liggitt) [inline pkg/image/api/helper.go]: should we be setting the media type even if we don't have a history?

File: pkg/image/api/helper.go [hunk 34]
```diff
@@ -523,6 +525,8 @@ func ImageWithMetadata(image *Image) error {
 			return err
 		}
 
+		image.DockerImageManifestMediaType = schema2.MediaTypeManifest
```
Comment (liggitt) [inline pkg/image/api/helper.go]: should we only override this if it is empty?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 35]
```diff
@@ -25,6 +39,156 @@ type blobDescriptorService struct {
...
+}
+
+func (bs *blobDescriptorService) Clear(ctx context.Context, dgst digest.Digest) error {
+	repo, found := RepositoryFrom(ctx)
+	if !found || repo == nil {
+		err := fmt.Errorf("failed to retrieve repository from context")
+		context.GetLogger(ctx).Error(err)
+		return err
+	}
+
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: is this operation accessible via the API? do we have to guard access to this? what happens if you clear a given digest that is not actually referenced from a repo or in an image stream?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 36]
```diff
@@ -25,6 +39,156 @@ type blobDescriptorService struct {
...
+	repositories := r.cachedLayers.RepositoriesForDigest(dgst)
+	match := imageapi.DockerImageReference{Namespace: r.namespace, Name: r.name}.Exact()
+	for _, repo := range repositories {
+		if repo == match {
+			context.GetLogger(r.ctx).Debugf("found cached blob %q in repository %s/%s", dgst.String(), r.namespace, r.name)
+			return true
+		}
+	}
+
+	// verify directly with etcd
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: is this the point at which we expect things to get expensive? do we want to add tracing here so we know how frequently we're hitting this path, and how long it's taking us?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 37]
```diff
@@ -25,6 +39,156 @@ type blobDescriptorService struct {
...
+			context.GetLogger(r.ctx).Debugf("image %q not found: imageName")
+		} else {
+			context.GetLogger(r.ctx).Errorf("failed to get image: %v", err)
+		}
+		return false
+	}
+
+	// in case of pullthrough disabled, client won't be able to download a blob belonging to not managed image
+	// (image stored in external registry), thus don't consider them as candidates
+	if managed := image.Annotations[imageapi.ManagedByOpenShiftAnnotation]; requireManaged && managed != "true" {
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: is this set to "true" for all non-pullthrough images, or is it missing from the oldest images?

File: pkg/dockerregistry/server/blobdescriptorservice.go [hunk 38]
```diff
@@ -25,6 +39,156 @@ type blobDescriptorService struct {
...
+		context.GetLogger(r.ctx).Debugf("skipping not managed image")
+		return false
+	}
+
+	if len(image.DockerImageLayers) == 0 {
+		if len(image.DockerImageManifestMediaType) > 0 {
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: comment explaining why this field makes us short-circuit?

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 37 above)
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: answering my own question, looks like we started setting that in c0fc084b3bae50fa3c937c79293608b56549ec68

File: vendor/github.com/docker/distribution/testutil/handler.go (hunk 32 above)
Comment (miminar) [inline vendor/github.com/docker/distribution/testutil/handler.go]: The latter. I wasn't sure, which annotation is more appropriate. Is `<drop>` more fitting this case?

File: pkg/image/api/helper.go (hunk 33 above)
Comment (miminar) [inline pkg/image/api/helper.go]: Good point. It makes sense to set it.

File: pkg/image/api/helper.go (hunk 34 above)
Comment (miminar) [inline pkg/image/api/helper.go]: > should we only override this if it is empty?

I don't think so. This function is called after operations such as replacement of manifest. All the metadata needs to be updated based on that. This field depends on the manifest as well.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 35 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: > is this operation accessible via the API?

It is: [`DELETE /v2/<name>/blobs/<digest>`](https://github.com/docker/distribution/blob/master/docs/spec/api.md#deleting-a-layer)

> do we have to guard access to this?

We already do in the auth controller https://github.com/miminar/origin/blob/pullthrough-no-copy-on-head-8613/pkg/dockerregistry/server/auth.go#L370. User needs to be able to `delete images`. But that's not precise. It should be `delete imagestreams/layers`. Non of our client tools invokes that except for pruner though.

> what happens if you clear a given digest that is not actually referenced from a repo or in an image stream? does that let me delete a blob I shouldn't have access to?

This is a wrapper only for linkedBlobStore, which allows to delete only links to blobs. So each invocation may only remove reference to the blob from single repository (aka image stream).

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 36 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: That will be interesting data. I'l add that.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 38 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: sure thing

File: vendor/github.com/docker/distribution/testutil/handler.go (hunk 32 above)
Comment (miminar) [inline vendor/github.com/docker/distribution/testutil/handler.go]: In the end, the dependency wasn't really necessary. The imported function `CreateRandomTarFile` created unnecessarily large one file taking too much time.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 38 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: Added a line below.

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 36 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: debug logging added

**Comment by miminar** [comment]
All the upstream patches are merged now.

**Comment by miminar** [comment]
Flake #9683. re-[test]

**Comment by miminar** [comment]
Completely new flake #10181 this time:

```
FAILURE after 0.807s: test/cmd/migrate.sh:64: executing 'oadm migrate image-references --include=imagestreams docker.io/*=my.docker.io/* --all-namespaces=false --loglevel=1 --confirm' expecting success and text 'migrated=1': the output content test failed
Standard output from the command:
migrated:  imagestreams/busybox -n default
migrated:  imagestreams/test -n default
summary: total=2 errors=0 ignored=0 unchanged=0 migrated=2
```

re-[test]

File: pkg/dockerregistry/server/blobdescriptorservice.go (hunk 35 above)
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice.go]: ok

File: pkg/dockerregistry/server/blobdescriptorservice_test.go [hunk 39]
```diff
@@ -0,0 +1,433 @@
...
+		{
+			name:     "get blob",
+			method:   http.MethodGet,
+			endpoint: v2.RouteNameBlob,
+			vars: []string{
+				"name", "user/app",
+				"digest", desc.Digest.String(),
+			},
+			expectedStatus:            http.StatusOK,
+			expectedMethodInvocations: map[string]int{"Stat": 3},
```
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice_test.go]: how stable/valuable is this number? if it suddenly changes to 4 on a registry bump, will we investigate why or just change it everywhere?

File: pkg/dockerregistry/server/digestcache_test.go [hunk 40]
```diff
@@ -0,0 +1,556 @@
...
+
+const (
+	allowedDeviation = time.Millisecond * 10
+
+	ttl1m = time.Minute
+	ttl5m = time.Minute * 5
+	ttl8m = time.Minute * 8
+)
+
+var stale = time.Unix(0, 0)
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: is this global var needed/used?

File: pkg/dockerregistry/server/digestcache.go [hunk 41]
```diff
@@ -26,20 +27,36 @@ func newDigestToRepositoryCache(size int) (digestToRepositoryCache, error) {
 	return digestToRepositoryCache{Cache: c}, nil
 }
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: add a `util.Clock` field to `digestToRepositoryCache`, and default it to `util.RealClock`. Propagate that to the repositoryBuckets (either as args, or as fields). That lets you test TTL eviction in a controlled way in unit tests with a fake clock you control

File: pkg/dockerregistry/server/digestcache.go [hunk 42]
```diff
@@ -52,42 +69,123 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
+			entry := arr[index]
+			copy(arr[index:], arr[index+1:])
+			if entry.evictOn.Before(evictOn) {
+				entry.evictOn = evictOn
+			}
+			arr[len(arr)-1] = entry
+
+		} else {
+			// repo is a new entry
+			if len(arr) >= bucketSize {
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: trimming from the front and appending to the end still requires memory allocation... shift items to the front and truncate at the end instead (https://play.golang.org/p/R8FGDMCnwW)

File: pkg/dockerregistry/server/digestcache_test.go [hunk 43]
```diff
@@ -0,0 +1,556 @@
...
+		expectedEntries []bucketEntry
+	}{
+		{
+			name:  "no existing entries",
+			ttl:   ttl5m,
+			repos: []string{"a", "b"},
+			expectedEntries: []bucketEntry{
+				{
+					repository: "a",
+					evictOn:    now.Add(ttl5m),
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: won't these times cause test flakes? `now` won't be the same when this testcase is set up and when the test runs

File: pkg/dockerregistry/server/digestcache_test.go [hunk 44]
```diff
@@ -0,0 +1,556 @@
...
+					repository: "orange",
+					evictOn:    now.Add(ttl8m),
+				},
+			},
+		},
+
+		{
+			name:    "over bucket size",
+			ttl:     ttl1m,
+			repos:   []string{"new1", generated[2].repository, "new2", generated[4].repository},
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: the mix of generated and hard-coded is hard to follow

Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: add a test where we're more than one over the bucketsize and make sure we get trimmed down to exactly the bucket size

File: pkg/dockerregistry/server/digestcache_test.go (hunk 40 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > is this global var needed/used?

It is (https://github.com/openshift/origin/pull/9819/files#diff-76f17549cddaa8e6d3bfa366cebbc558R224) but I guess I could just leave stale entries with `evictOn` unset for the same result.

File: pkg/dockerregistry/server/digestcache.go (hunk 41 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: > add a util.Clock field to digestToRepositoryCache, and default it to util.RealClock. Propagate that to the repositoryBuckets (either as args, or as fields). That lets you test TTL eviction in a controlled way in unit tests with a fake clock you control

I see, clever.

File: pkg/dockerregistry/server/digestcache.go (hunk 42 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: Good catch.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 43 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: Yes, that's why I'm comparing times with a small deviation allowed. Will be soled with mocked clock.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 44 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: This is the one. But I agree it's not very pleasant to the eye. I'll add a separate test for that.

File: pkg/dockerregistry/server/blobdescriptorservice_test.go (hunk 39 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice_test.go]: > how stable/valuable is this number? if it suddenly changes to 4 on a registry bump, will we investigate why or just change it everywhere?

It can be easily changed on the next bump. What I find valuable is a difference between number of calls with registry object set and unset. In the latter case it's always 1. In case of blobs it will be higher than 1. Shall I make the value an enumeration (`zero`, `one`, `morethanone`) instead?

File: pkg/dockerregistry/server/errorblobstore.go [hunk 45]
```diff
@@ -23,44 +23,57 @@ func (r *errorBlobStore) Stat(ctx context.Context, dgst digest.Digest) (distribu
...
+	err = checkPendingCrossMountErrors(ctx, opts)
+	if err == nil && opts.Mount.ShouldMount {
+		desc, err = statSourceRepository(ctx, opts.Mount.From, opts.Mount.From.Digest())
+	}
+
+	if err != nil {
+		context.GetLogger(ctx).Infof("disabling cross-repo mount because of an error: %v", err)
+		options = append(options, guardCreateOptions{DisableCrossMount: true})
+	} else if !opts.Mount.ShouldMount {
+		context.GetLogger(ctx).Infof("ensuring cross-repo is disabled: %v", err)
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: make this debug level?

File: pkg/dockerregistry/server/errorblobstore.go [hunk 46]
```diff
@@ -23,44 +23,57 @@ func (r *errorBlobStore) Stat(ctx context.Context, dgst digest.Digest) (distribu
...
 		options = append(options, guardCreateOptions{DisableCrossMount: true})
 	} else {
-		options = append(options, guardCreateOptions{})
+		context.GetLogger(ctx).Debugf("attempting cross-repo mount")
+		options = append(options, statCrossMountCreateOptions{desc: desc})
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: should we actually do the `statSourceRepository()` call inside `statCrossMountCreateOptions#Apply`?

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 47]
```diff
@@ -271,7 +283,13 @@ func (r *repository) Get(ctx context.Context, dgst digest.Digest, options ...dis
 	}
 
 	ref := imageapi.DockerImageReference{Namespace: r.namespace, Name: r.name, Registry: r.registryAddr}
-	manifest, err := r.manifestFromImageWithCachedLayers(image, ref.DockerClientDefaults().Exact())
+	if managed := image.Annotations[imageapi.ManagedByOpenShiftAnnotation]; managed == "true" {
+		ref.Registry = ""
```
Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: what does an empty registry here do? don't we still need to default tag and namespace?

Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: a comment would be helpful

Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: functions like `identifyCandidateRepositories` compare `ref.Registry` against a known localRegistry:
```
// skip anything that matches the innate registry
// TODO: there may be a better way to make this determination
if len(localRegistry) != 0 && localRegistry == ref.Registry {
	continue
}
```

should we really be clearing this, or setting it to a "local registry" value? the effects of this change are very hard to reason about

File: pkg/dockerregistry/server/repositorymiddleware.go [hunk 48]
```diff
@@ -516,30 +535,56 @@ func (r *repository) getImageStreamImage(dgst digest.Digest) (*imageapi.ImageStr
...
+			r.cachedLayers.RememberDigest(digest.Digest(layer.Name), r.blobrepositorycachettl, cacheName)
+		}
+		return
+	}
+
+	manifest, err := r.getManifestFromImage(image)
+	if err != nil {
+		context.GetLogger(r.ctx).Errorf("cannot remember layers of image %q: %v", image.Name, err)
+	}
+	r.rememberLayersOfManifest(manifest, cacheName)
```
Comment (liggitt) [inline pkg/dockerregistry/server/repositorymiddleware.go]: shouldn't use manifest if err was non-nil

File: test/end-to-end/core.sh [hunk 49]
```diff
@@ -136,6 +136,11 @@ os::cmd::expect_success "docker tag -f centos/ruby-22-centos7:latest ${DOCKER_RE
 os::cmd::expect_success "docker push ${DOCKER_REGISTRY}/cache/ruby-22-centos7:latest"
 echo "[INFO] Pushed ruby-22-centos7"
 
+# get image's digest
+rubyimagedigest=$(oc get -o jsonpath='{.status.tags[?(@.tag=="latest")].items[0].image}' is/ruby-22-centos7)
+# get a random, non-empty blob
+rubyimageblob=$(oc get isimage -o go-template='{{range .image.dockerImageLayers}}{{if gt .size 1024.}}{{.name}},{{end}}{{end}}' ruby-22-centos7@${rubyimagedigest} | cut -d , -f 1)
```
Comment (liggitt) [inline test/end-to-end/core.sh]: echo these so they show up in the log?

File: test/end-to-end/core.sh [hunk 50]
```diff
@@ -215,13 +234,39 @@ os::cmd::expect_success 'oc policy add-role-to-user system:image-pusher system:a
...
 echo "[INFO] Back to 'default' project with 'admin' user..."
 os::cmd::expect_success "oc project ${CLUSTER_ADMIN_CONTEXT}"
 os::cmd::expect_success_and_text 'oc whoami' 'system:admin'
+os::cmd::expect_success "oc tag --source docker centos/ruby-22-centos7:latest -n custom ruby-22-centos7:latest"
+os::cmd::expect_success 'oc policy add-role-to-user registry-viewer pusher -n custom'
+os::cmd::expect_success 'oc policy add-role-to-user system:image-pusher pusher -n crossmount'
+
+echo "[INFO] Docker cross-repo mount"
+os::cmd::expect_success_and_text "curl -I -X HEAD -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/$rubyimageblob'" "404 Not Found"
+os::cmd::expect_success_and_text "curl -I -X HEAD -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/cache/ruby-22-centos7/blobs/$rubyimageblob'" "200 OK"
```
Comment (liggitt) [inline test/end-to-end/core.sh]: put the positive test first, then the negative test

File: test/end-to-end/core.sh [hunk 51]
```diff
@@ -215,13 +234,39 @@ os::cmd::expect_success 'oc policy add-role-to-user system:image-pusher system:a
...
+# 202 means that cross-repo mount has failed (in this case because of blob doesn't exist in the source repository), client needs to reupload the blob
+os::cmd::expect_success_and_text "curl -I -X POST -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/uploads/?mount=$rubyimageblob&from=cache/hello-world'" "202 Accepted"
+# 201 means that blob has been cross mounted from given repository
+os::cmd::expect_success_and_text "curl -I -X POST -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/uploads/?mount=$rubyimageblob&from=cache/ruby-22-centos7'" "201 Created"
+# check that the blob is linked now
+os::cmd::expect_success_and_text "curl -I -X HEAD -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/$rubyimageblob'" "200 OK"
+# remove pusher's permissions to read from the source repository
+os::cmd::expect_success "oc policy remove-role-from-user system:image-pusher pusher -n cache"
```
Comment (liggitt) [inline test/end-to-end/core.sh]: after removing permission, add a try_until_text check to make sure the authz cache is updated:
```
os::cmd::try_until_text "oc policy can-i get imagestreams/layers -n cache '--token=${pusher_token}'" "no"
```

File: test/end-to-end/core.sh [hunk 52]
```diff
@@ -215,13 +234,39 @@ os::cmd::expect_success 'oc policy add-role-to-user system:image-pusher system:a
...
+# cross-repo mount failed because of access denied
+os::cmd::expect_success_and_text "curl -I -X POST -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/uploads/?mount=$rubyimageblob&from=cache/ruby-22-centos7'" "202 Accepted"
+# wait until image is imported
+os::cmd::try_until_text "oc get -n custom is/ruby-22-centos7 --template='{{if .status.tags}}{{if gt (len .status.tags) 0}}tagged{{end}}{{end}}'" tagged $((20*TIME_SEC))
```
Comment (liggitt) [inline test/end-to-end/core.sh]: would this be simpler? can we just wait for the latest tag to appear?
```
... -o 'jsonpath={.status.tags[*].tag}'" "latest"
```

File: test/end-to-end/core.sh [hunk 53]
```diff
@@ -215,13 +234,39 @@ os::cmd::expect_success 'oc policy add-role-to-user system:image-pusher system:a
...
+# cross repo mount from a remote repository (cross-repo mount with pullthrough)
+os::cmd::expect_success_and_text "curl -I -X POST -u 'pusher:${pusher_token}' '${DOCKER_REGISTRY}/v2/crossmount/repo/blobs/uploads/?mount=$rubyimageblob&from=custom/ruby-22-centos7'" "201 Created"
```
Comment (liggitt) [inline test/end-to-end/core.sh]: do we have a negative test for a cross-mount from a pull-through?

File: pkg/dockerregistry/server/blobdescriptorservice_test.go (hunk 39 above)
Comment (liggitt) [inline pkg/dockerregistry/server/blobdescriptorservice_test.go]: I don't care, but a comment (even just the explanation above) on the significance of `3` would be helpful in the future in case we need to fix the test.

File: pkg/dockerregistry/server/repositorymiddleware.go (hunk 47 above)
Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: > should we really be clearing this, or setting it to a "local registry" value? the effects of this change are very hard to reason about

There are two kind of entries in the `cachedLayers`:

1. `<registry>/<namespace>/<name>`
2. `<namespace>/<name>`

The former is set and used by a pullthrough middleware which operates on remote blobs, it's not interested in the latter.

The latter is set and used by blob descriptor service operating on local blobs. It's also set on this place when it's clear that image's blobs are or should be available locally. Registry's location might change over time so I'd rather avoid depending on it.

Nevertheless the code for not managed image is wrong anyway (even prior to this change). The code will append `:latest` tag causing cache misses in the pullthrough middleware. I'll fix it.

Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: Fixed and commented.

File: pkg/dockerregistry/server/errorblobstore.go (hunk 46 above)
Comment (miminar) [inline pkg/dockerregistry/server/errorblobstore.go]: > should we actually do the statSourceRepository() call inside statCrossMountCreateOptions#Apply?

Doing it this way now.

File: pkg/dockerregistry/server/errorblobstore.go (hunk 45 above)
Comment (miminar) [inline pkg/dockerregistry/server/errorblobstore.go]: > make this debug level? this is going to be most requests

Changed to debug level.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 44 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > This is the one. But I agree it's not very pleasant to the eye. I'll add a separate test for that.

Test added.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 43 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > Yes, that's why I'm comparing times with a small deviation allowed. Will be solved with mocked clock.

Mocking clock now.

File: pkg/dockerregistry/server/digestcache.go (hunk 42 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: > trimming from the front and appending to the end still requires memory allocation

File: pkg/dockerregistry/server/digestcache_test.go (hunk 40 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > is this global var needed/used?

Removed.

File: pkg/dockerregistry/server/blobdescriptorservice_test.go (hunk 39 above)
Comment (miminar) [inline pkg/dockerregistry/server/blobdescriptorservice_test.go]: > I don't care, but a comment (even just the explanation above) on the significance of 3 would be helpful in the future in case we need to fix the test.

Commented and fixed a possible race.

File: test/end-to-end/core.sh (hunk 52 above)
Comment (miminar) [inline test/end-to-end/core.sh]: > would this be simpler? can we just wait for the latest tag to appear?

nice :smile:

File: test/end-to-end/core.sh (hunk 53 above)
Comment (miminar) [inline test/end-to-end/core.sh]: The cross-repo mount on pullthrough isn't really addressed by this PR. I'll remove this test. Cross-repo mount from remote registries was meant to implement remote layer federation, but it's just not enough. #10120 discusses it in more detail.

File: pkg/dockerregistry/server/repositorymiddleware.go (hunk 48 above)
Comment (miminar) [inline pkg/dockerregistry/server/repositorymiddleware.go]: Yes, thanks. Fixed.

File: test/end-to-end/core.sh (hunk 49 above)
Comment (miminar) [inline test/end-to-end/core.sh]: > echo these so they show up in the log?

done

File: test/end-to-end/core.sh (hunk 50 above)
Comment (miminar) [inline test/end-to-end/core.sh]: > put the positive test (200 on cache/ruby-22-centos7) first, then the negative test (404 on crossmount) second

done

File: test/end-to-end/core.sh (hunk 51 above)
Comment (miminar) [inline test/end-to-end/core.sh]: > after removing permission, add a try_until_text check to make sure the authz cache is updated:

added

**Comment by liggitt** [comment]
> @miminar: 
> And I was wrong also in the case of the order. Our blobDescriptorService actually wraps the cachedBlobStatter (see the updated comment above). So functional-wise we're fine having it enabled. Unfortunately, it doubles the memory usage per blob cached. We'd better push upstream an ability for defining our own blobDescriptorCacheProvider.
> That can be easily done as a follow-up. For now, I'll just re-enable the inmemory cache.

Is there a follow up to track this?

**Comment by miminar** [comment]
> Is there a follow up to track this?

No, I'm opening an issue.

File: pkg/dockerregistry/server/errorblobstore.go [hunk 54]
```diff
@@ -127,3 +130,42 @@ func (f guardCreateOptions) Apply(v interface{}) error {
...
+func (f statCrossMountCreateOptions) Apply(v interface{}) error {
+	opts, ok := v.(*distribution.CreateOptions)
+	if !ok {
+		return fmt.Errorf("Unexpected create options: %#v", v)
+	}
+
+	if !opts.Mount.ShouldMount {
+		return nil
+	}
+
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: just use opts.Mount.From and opts.Mount.Digest() instead of struct fields?

File: pkg/dockerregistry/server/errorblobstore.go [hunk 55]
```diff
@@ -127,3 +130,42 @@ func (f guardCreateOptions) Apply(v interface{}) error {
...
+	desc, err := statSourceRepository(f.ctx, f.sourceRepoName, f.blobDigest)
+	if err != nil {
+		context.GetLogger(f.ctx).Infof("cannot mount blob %s from repository %s: %v - disabling cross-repo mount", f.blobDigest.String(), f.sourceRepoName.Name())
+		opts.Mount.ShouldMount = false
```
Comment (liggitt) [inline pkg/dockerregistry/server/errorblobstore.go]: is there any case where we would fail a stat and the linkedBlobStore would succeed? should we disable mounting or just let it attempt to continue?

**Comment by liggitt** [comment]
re: https://github.com/openshift/origin/pull/9819#issuecomment-236099677 - does an orphaned layer link fail a stat correctly? is there a follow up issue to remove layer links in pruning?

File: pkg/dockerregistry/server/errorblobstore.go (hunk 54 above)
Comment (miminar) [inline pkg/dockerregistry/server/errorblobstore.go]: Oh, how could I overlook.

File: pkg/dockerregistry/server/errorblobstore.go (hunk 55 above)
Comment (miminar) [inline pkg/dockerregistry/server/errorblobstore.go]: > is there any case where we would fail a stat and the linkedBlobStore would succeed?

The `linkedBlobStore.Create()` will almost certainly succeed. That cannot be said of the mount though. Nevertheless, since we have the determining knowledge whether to mount or not, we should be explicit about our intention.

**Comment by miminar** [comment]
> re: #9819 (comment) - does an orphaned layer link fail a stat correctly?

It does.

> is there a follow up issue to remove layer links in pruning?

There's https://trello.com/c/3ZmBKDZZ/437-8-refactor-registry-layer-and-signature-pruning
This is one of the requirements.

File: pkg/dockerregistry/server/digestcache.go [hunk 56]
```diff
@@ -23,23 +27,42 @@ func newDigestToRepositoryCache(size int) (digestToRepositoryCache, error) {
...
 	}
 	repos := value.(*repositoryBucket)
-	repos.Add(repo)
+	repos.Add(ttl, repo)
+}
+
+// ForgetDigest removes an association between given digest and repository from the cache.
+func (c digestToRepositoryCache) ForgetDigest(dgst digest.Digest, repo string) {
+	key := dgst.String()
+	value, ok := c.Get(key)
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: not sure we want to bump to the front of the LRU cache when removing a repo... maybe use `Peek()` instead?

File: pkg/dockerregistry/server/digestcache_test.go [hunk 57]
```diff
@@ -0,0 +1,612 @@
...
+					repository: "bmw",
+					evictOn:    now.Add(ttl8m),
+				},
+				{
+					repository: "audi",
+					evictOn:    now.Add(ttl8m),
+				},
+			},
+		},
+
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: add a test to check adding existing entry with single item in the list
```
{
	name:  "add existing entry with single item",
	ttl:   ttl8m,
	repos: []string{"apple"},
	entries: []bucketEntry{
		{repository: "apple", evictOn: now.Add(ttl5m)},
	},
	expectedEntries: []bucketEntry{
		{repository: "apple", evictOn: now.Add(ttl8m)},
	},
},
```

File: pkg/dockerregistry/server/digestcache.go [hunk 58]
```diff
@@ -52,42 +75,134 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
+			if entry.evictOn.Before(evictOn) {
+				entry.evictOn = evictOn
+			}
+			arr[len(arr)-1] = entry
+
+		} else {
+			// repo is a new entry
+			if len(arr) >= bucketSize {
+				copy(arr, arr[1:])
+				arr = arr[:bucketSize-1]
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: if the array is longer than the bucketSize, then we're chopping off the most recently added items here. probably not a big deal, since if we add correctly, we never exceed the bucketSize

File: pkg/dockerregistry/server/digestcache.go [hunk 59]
```diff
@@ -52,42 +75,134 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
+		if index >= 0 {
+			copy(b.list[index:], b.list[index+1:])
+			b.list = b.list[:len(b.list)-1]
+		}
+	}
+}
+
+// getIndexOf returns an index of given repository in bucket's array. If not found, -1 will be returned.
+func (b *repositoryBucket) getIndexOf(repo string) int {
+	arr := b.list
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]:
```
for i, entry := range b.list {
  if v.entry == repo {
    return i
  }
}
return -1
```

File: pkg/dockerregistry/server/digestcache_test.go [hunk 60]
```diff
@@ -0,0 +1,612 @@
...
+					evictOn:    now.Add(ttl5m),
+				},
+			},
+			expectedEntries: []bucketEntry{
+				{
+					repository: "pear",
+					evictOn:    now.Add(ttl5m),
+				},
+			},
+		},
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache_test.go]: add a test case removing an entry from a single list:
```
{
	name:  "remove existing entry with single item",
	repos: []string{"apple"},
	entries: []bucketEntry{
		{repository: "apple", evictOn: now.Add(ttl5m)},
	},
	expectedEntries: []bucketEntry{},
},

```

File: pkg/dockerregistry/server/digestcache.go [hunk 61]
```diff
@@ -52,42 +75,134 @@ func (c digestToRepositoryCache) RepositoriesForDigest(dgst digest.Digest) []str
...
 
-// Copy returns a copy of the contents of this bucket in a threadsafe fasion.
-func (i *repositoryBucket) Copy() []string {
-	i.mu.Lock()
-	defer i.mu.Unlock()
-	out := make([]string, len(i.list))
-	copy(out, i.list)
+// evictStale removes stale entries from the list and shifts all the survivalists to the front.
+func (b *repositoryBucket) evictStale() {
+	arr := b.list
```
Comment (liggitt) [inline pkg/dockerregistry/server/digestcache.go]: saw this method of filtering a list at https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating, and I can't decide if I like it or not:
```
results := b.list[:0]
for _, entry := range b.list {
  if now.Before(entry.evictOn) {
    results = append(results, entry)
  }
}
b.list = results
```

**Comment by liggitt** [comment]
nits on digestcache, can address in a follow-up if you want, LGTM

File: pkg/dockerregistry/server/digestcache.go (hunk 56 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: > not sure we want to bump to the front of the LRU cache when removing a repo... maybe use Peek() instead?

Good catch. Fixed.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 57 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > add a test to check adding existing entry with single item in the list

added

File: pkg/dockerregistry/server/digestcache.go (hunk 58 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: I'm taking an advantage of not touching.

File: pkg/dockerregistry/server/digestcache.go (hunk 59 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: Rewritten.

File: pkg/dockerregistry/server/digestcache_test.go (hunk 60 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache_test.go]: > add a test case removing an entry from a single list:

added

File: pkg/dockerregistry/server/digestcache.go (hunk 61 above)
Comment (miminar) [inline pkg/dockerregistry/server/digestcache.go]: > saw this method of filtering a list at https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating, and I can't decide if I like it or not:

I like it! Changed.

**Comment by miminar** [comment]
> nits on digestcache, can address in a follow-up if you want, LGTM

Thanks a lot! It's totally different PR now with your suggestions applied. But each one made it a lot better.

**Comment by miminar** [comment]
Flake #10008

**Comment by liggitt** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] #9938
