### PR TITLE
Disable ThirdPartyController

### LINKED ISSUE #14878: github.com/openshift/origin/test/integration .TestEtcd2StoragePath
```
--- FAIL: TestEtcd2StoragePath (61.10s)
	etcd_storage_path_test.go:953: failed to clean up etcd: &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"the server could not find the requested resource (delete clusterrolebindings.rbac.authorization.k8s.io crb1a1)", Reason:"NotFound", Details:(*v1.StatusDetails)(0xc43d0fcf50), Code:404}}
	etcd.go:126: dumping etcd to "/tmp/openshift/test-integration/etcd-dump-runtime.call32.json"
FAIL
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_integration/3680/

### PR DESCRIPTION
**Pull request by enj**
This change makes it so that the third party resource controller does not run.  This controller breaks the API's go-restful containers by removing handlers.  The remove functionality is broken, and destroys the server mux when it is called.

Supersedes #14739
Fixes #14878

xref emicklei/go-restful/issues/344

@openshift/security 

[test]

### CODE REVIEW

**Comment by enj** [comment]
Flake #14897, tests are good otherwise.  @deads2k @smarterclayton PTAL.

**Comment by deads2k** [comment]
@enj there should be a list of disabled poststarthooks.  Please use that instead.

File: test/integration/master_routes_test.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ var expectedIndex = []string{
 	"/healthz/ping",
 	"/healthz/poststarthook/bootstrap-controller",
 	"/healthz/poststarthook/ca-registration",
-	"/healthz/poststarthook/extensions/third-party-resources",
+	// "/healthz/poststarthook/extensions/third-party-resources",  // Do not enable this controller, it breaks go-restful
```
Comment (deads2k) [inline test/integration/master_routes_test.go]: this comment

**Comment by deads2k** [comment]
squash and lgtm.

**Comment by enj** [comment]
[merge] comments addressed.
