### PR TITLE
Fix TestRegistryClientImageV1, TestRegistryClientImageV2

### LINKED ISSUE #9130: TestRegistryClientImageV1/TestRegistryClientImageV2 failure
```
--- FAIL: TestRegistryClientImageV1 (1.46s)
	dockerregistryclient_test.go:222: the default tag "sha256:52776e94e88f0335b7165113ea40ebdf0c919eb208d357287537544987d14b19" has not been set on repository "openshift/origin"
FAIL
```
Same error for `TestRegistryClientImageV2`
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/1423/console

### PR DESCRIPTION
**Pull request by legionus**
Fix #9130

@miminar @soltysh

### CODE REVIEW

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

File: test/integration/dockerregistryclient_test.go [hunk 1]
```diff
@@ -224,14 +222,19 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
 	}
 }
 
+func TestRegistryClientImageV2ManifestV2(t *testing.T) {
+	t.Skip("openshift/schema-v2-test-repo is being pushed by Docker 1.10, which causes this test to fail because digests don't match")
```
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Why would this fail? The importer should be able to import manifest V2 schema 2 just fine both by tag and digest.

File: test/integration/dockerregistryclient_test.go [hunk 2]
```diff
@@ -224,14 +222,19 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
 	}
 }
 
+func TestRegistryClientImageV2ManifestV2(t *testing.T) {
```
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: TestRegistryClientAPIv2ManifestV2Schema2

File: test/integration/dockerregistryclient_test.go [hunk 3]
```diff
@@ -224,14 +222,19 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
...
+	t.Skip("openshift/schema-v2-test-repo is being pushed by Docker 1.10, which causes this test to fail because digests don't match")
+	doTestRegistryClientImage(t, dockerHubV2RegistryName, "schema-v2-test-repo", "v2")
+}
+
 func TestRegistryClientImageV2(t *testing.T) {
```
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: TestRegistryClientAPIv2ManifestV2Schema1

File: test/integration/dockerregistryclient_test.go [hunk 4]
```diff
@@ -224,14 +222,19 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
...
-	t.Skip("openshift/origin is being pushed by Docker 1.9, which causes this test to fail because digests don't match")
-	doTestRegistryClientImage(t, dockerHubV2RegistryName, "v2")
+	t.Log("openshift/schema-v1-test-repo is being pushed by Docker 1.8.2")
+	doTestRegistryClientImage(t, dockerHubV2RegistryName, "schema-v1-test-repo", "v2")
 }
 
 func TestRegistryClientImageV1(t *testing.T) {
```
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: TestRegistryClientAPIv1

File: test/integration/dockerregistryclient_test.go (hunk 1 above)
Comment (soltysh) [inline test/integration/dockerregistryclient_test.go]: Having this skip always is not a good idea. If anything, you should skip conditionally, only.

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: It's broken for the same reason as #9130.  Nothing has changed in this. If it worked, then initially the test would not break.  I assume that our client does not fully support v2 schema. I think this is related to https://github.com/fsouza/go-dockerclient/issues/488

Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Oh no, why do we go through docker daemon when we already depend on distribution client?

Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Anyway, this should work if there's docker 1.10 or higher installed right?

Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Could you conditionally skip this test based on the version of docker? Or maybe even better: verify that it succeeds with docker >=1.10 and that it fails with docker <1.10.

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: @soltysh This test is left for the future. We must do our best to make it work. But this PR I made in order to bring back old tests to a working state.

Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: By the way, there's already a helper to get docker version: https://github.com/miminar/origin/blob/remote-layer-federation/test/extended/images/helper.go#L326.

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: No. I don't want to add hacks. I added the client fix to work correctly with a v2 schema.

**Comment by legionus** [comment]
[test]

File: test/integration/dockerregistryclient_test.go (hunk 1 above)
Comment (soltysh) [inline test/integration/dockerregistryclient_test.go]: I really like @miminar idea here. It's not a hack, it's a test and we need to make sure we work ok. 

Where is the fix for v2 schema client? If that works the test should as well, right?

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: @soltysh I believe that to check the docker version and skip the test in this case is a hack. Nevermind. After [commit](https://github.com/openshift/origin/pull/10003/commits/c452be1ac0d1278c9dc236059db55c903d642bae) it's no longer needed anymore. All tests must work without exceptions.

Moreover, before this fix, our client has always worked using v1 schema.

Comment (soltysh) [inline test/integration/dockerregistryclient_test.go]: Awesome!

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: I will backport this PR after his review and landing.

File: pkg/dockerregistry/client.go [hunk 5]
```diff
@@ -611,6 +699,8 @@ func (repo *v1repository) getTags(c *connection) (map[string]string, error) {
 	if err != nil {
 		return nil, fmt.Errorf("error creating request: %v", err)
 	}
+	addAcceptHeader(req)
```
Comment (miminar) [inline pkg/dockerregistry/client.go]: I don't think this makes sense for `v1Repository`.

File: pkg/dockerregistry/client.go [hunk 6]
```diff
@@ -597,6 +603,88 @@ func (repo *v2repository) getImage(c *connection, image, userTag string) (*Image
...
 }
 
+func (repo *v2repository) getImageConfig(c *connection, dgst string) ([]byte, error) {
+	endpoint := repo.endpoint
+	endpoint.Path = path.Join(endpoint.Path, fmt.Sprintf("/v2/%s/blobs/%s", repo.name, dgst))
+	req, err := http.NewRequest("GET", endpoint.String(), nil)
+	if err != nil {
+		return nil, fmt.Errorf("error creating request: %v", err)
+	}
+	addAcceptHeader(req)
```
Comment (miminar) [inline pkg/dockerregistry/client.go]: Seems superfluous here.

File: pkg/dockerregistry/client.go (hunk 5 above)
Comment (legionus) [inline pkg/dockerregistry/client.go]: Ooops. Yes.

File: pkg/dockerregistry/client.go [hunk 7]
```diff
@@ -597,6 +603,88 @@ func (repo *v2repository) getImage(c *connection, image, userTag string) (*Image
...
+				repo.retries--
+				time.Sleep(time.Second / 2)
+				return repo.getImageConfig(c, dgst)
+			}
+			delete(c.cached, repo.name)
+			// docker will not return a NotFound on any repository URL - for backwards compatibility, return NotFound on the
+			// repo
+			body, _ := ioutil.ReadAll(resp.Body)
+			glog.V(4).Infof("passed valid auth token, but unable to find image config at %q, %d %v: %s", req.URL.String(), resp.StatusCode, resp.Header, body)
+			return nil, errTagNotFound{true, dgst, repo.name}
```
Comment (miminar) [inline pkg/dockerregistry/client.go]: `errTagNotFound` seems wrong in this context.

Comment (legionus) [inline pkg/dockerregistry/client.go]: `errTagNotFound` used by `ImageByID` as well. This is common error code.

Comment (legionus) [inline pkg/dockerregistry/client.go]: @miminar Fixed.

Comment (miminar) [inline pkg/dockerregistry/client.go]: This error results in one of the following descriptions based on requested tag:

```go
	if e.wasDefault {
		return fmt.Sprintf("the default tag %q has not been set on repository %q", e.tag, e.repository)
	}
	return fmt.Sprintf("tag %q has not been set on repository %q", e.tag, e.repository)
```

Neither of them apply here. Can we define some other error message or make the `errTagNotFound` more generic?

Comment (legionus) [inline pkg/dockerregistry/client.go]: @miminar Done as mentioned above.

File: pkg/dockerregistry/client.go (hunk 5 above)
Comment (legionus) [inline pkg/dockerregistry/client.go]: Fixed

File: test/integration/dockerregistryclient_test.go [hunk 8]
```diff
@@ -224,14 +230,19 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
 	}
 }
 
-func TestRegistryClientImageV2(t *testing.T) {
-	t.Skip("openshift/origin is being pushed by Docker 1.9, which causes this test to fail because digests don't match")
-	doTestRegistryClientImage(t, dockerHubV2RegistryName, "v2")
+func TestRegistryClientAPIv2ManifestV2Schema2(t *testing.T) {
+	t.Log("openshift/schema-v2-test-repo is being pushed by Docker 1.11.1")
```
Comment (miminar) [inline test/integration/dockerregistryclient_test.go]: Nice!

Can we just replace `is being pushed` with `was pushed`?

Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: @miminar Done

**Comment by legionus** [comment]
[test]

File: pkg/dockerregistry/client.go [hunk 9]
```diff
@@ -713,6 +800,16 @@ func (repo *v1repository) getImage(c *connection, image, userTag string) (*Image
 	return &Image{Image: *dockerImage}, nil
 }
 
+// errBlobNotFound is an error indicating the requested blob does not exist on the server.
```
Comment (miminar) [inline pkg/dockerregistry/client.go]: `s/on the server/in the repository/`

Comment (legionus) [inline pkg/dockerregistry/client.go]: @miminar Done

**Comment by legionus** [comment]
[test]

File: pkg/dockerregistry/client.go [hunk 10]
```diff
@@ -713,7 +800,17 @@ func (repo *v1repository) getImage(c *connection, image, userTag string) (*Image
 	return &Image{Image: *dockerImage}, nil
 }
 
-// errTagNotFound is an error indicating the requested tag does not exist on the server. May be returned on
+// errBlobNotFound is an error indicating the requested blob does not exist in the server.
```
Comment (miminar) [inline pkg/dockerregistry/client.go]: `s/server/repository/`

**Comment by miminar** [comment]
One nit, LGTM otherwise.

File: pkg/dockerregistry/client.go (hunk 10 above)
Comment (legionus) [inline pkg/dockerregistry/client.go]: @miminar Done

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
@soltysh merge ?

File: pkg/dockerregistry/client.go [hunk 11]
```diff
@@ -597,6 +603,87 @@ func (repo *v2repository) getImage(c *connection, image, userTag string) (*Image
...
+		return nil, convertConnectionError(c.url.String(), fmt.Errorf("error getting image config for %s: %v", repo.name, err))
+	}
+	defer resp.Body.Close()
+
+	switch code := resp.StatusCode; {
+	case code == http.StatusUnauthorized:
+		if len(repo.token) != 0 {
+			// The DockerHub returns JWT tokens that take effect at "now" at second resolution, which means clients can
+			// be rejected when requests are made near the time boundary.
+			if repo.retries > 0 {
```
Comment (mfojtik) [inline pkg/dockerregistry/client.go]: this should be `wait.Poll`

**Comment by mfojtik** [comment]
LGTM (one nit that can be fixed as follow up)

File: pkg/dockerregistry/client.go (hunk 11 above)
Comment (soltysh) [inline pkg/dockerregistry/client.go]: Actually, we're using this pattern in the registry already several times. I suggest leaving this as is.

File: pkg/dockerregistry/client.go [hunk 12]
```diff
@@ -597,6 +603,87 @@ func (repo *v2repository) getImage(c *connection, image, userTag string) (*Image
...
+
+		return nil, fmt.Errorf("error retrieving image config: server returned %d", resp.StatusCode)
+	}
+
+	body, err := ioutil.ReadAll(resp.Body)
+	if err != nil {
+		return nil, fmt.Errorf("can't read image body from %s: %v", req.URL, err)
+	}
+
+	return body, nil
```
Comment (soltysh) [inline pkg/dockerregistry/client.go]: What worries me the most is this whole code block is a copy&pase of `getTaggedImage`. I'm ok with this being in but we need to merge the two into single method.

File: test/integration/dockerregistryclient_test.go [hunk 13]
```diff
@@ -198,22 +198,28 @@ func doTestRegistryClientImage(t *testing.T, registry, version string) {
...
 	}
-	if len(image.ContainerConfig.Entrypoint) == 0 {
-		t.Errorf("%s: unexpected image: %#v", version, image)
+
+	if image.Comment != "Imported from -" {
+		t.Errorf("%s: unexpected image comment", version)
+	}
+
+	if image.Architecture != "amd64" {
+		t.Errorf("%s: unexpected image architecture", version)
```
Comment (soltysh) [inline test/integration/dockerregistryclient_test.go]: Why we need those two checks?

**Comment by soltysh** [comment]
LGTM [merge]

File: test/integration/dockerregistryclient_test.go (hunk 13 above)
Comment (legionus) [inline test/integration/dockerregistryclient_test.go]: This is done in order to check the filling metadata. In other words what config blob was obtained. This is a test repository so that I can be sure that they need to be there.

File: pkg/dockerregistry/client.go (hunk 12 above)
Comment (legionus) [inline pkg/dockerregistry/client.go]: They are different. Equally just how they do request and do retry.

**Comment by soltysh** [comment]
Flake from #10037.

re-[merge]
