### PR TITLE
Limits the amount of suggestions of a faulty new-build command to 5, fixes #7729

### LINKED ISSUE #7729: Excessive output when multiple images returned for new-app on big repository.
Running hack/../test/cmd/builds.sh:52: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to origin-test:v1.1' expecting success...
    FAILURE after 2.031s: hack/../test/cmd/builds.sh:52: executing 'oc new-build -D $'FROM openshift/origin:v1.1\nENV ok=1' --to origin-test:v1.1' expecting success: the command returned the wrong error code
    There was no output from the command.
    Standard error from the command:
    error: multiple images or templates matched "openshift/origin:v1.1": 27

    The argument "openshift/origin:v1.1" could apply to the following Docker images or OpenShift image streams:

    * Docker image "openshift/origin:latest", 8cc5ae7, from local
      Use --docker-image="openshift/origin:latest" to specify this image or template

    * Docker image "openshift/origin:7ba70f0", 8cc5ae7, from local
      Use --docker-image="openshift/origin:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-sti-builder:latest", 3a9762e, from local
      Use --docker-image="openshift/origin-sti-builder:latest" to specify this image or template

    * Docker image "openshift/origin-gitserver:7ba70f0", 472e009, from local
      Use --docker-image="openshift/origin-gitserver:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-gitserver:latest", 472e009, from local
      Use --docker-image="openshift/origin-gitserver:latest" to specify this image or template

    * Docker image "openshift/origin-docker-builder:7ba70f0", cd107aa, from local
      Use --docker-image="openshift/origin-docker-builder:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-docker-builder:latest", cd107aa, from local
      Use --docker-image="openshift/origin-docker-builder:latest" to specify this image or template

    * Docker image "openshift/origin-recycler:7ba70f0", 828e007, from local
      Use --docker-image="openshift/origin-recycler:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-recycler:latest", 828e007, from local
      Use --docker-image="openshift/origin-recycler:latest" to specify this image or template

    * Docker image "openshift/origin-deployer:7ba70f0", 5cd5a66, from local
      Use --docker-image="openshift/origin-deployer:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-docker-registry:7ba70f0", f821f3b, from local, 38.658mb
      Use --docker-image="openshift/origin-docker-registry:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-keepalived-ipfailover:7ba70f0", 5b68f13, from local
      Use --docker-image="openshift/origin-keepalived-ipfailover:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-haproxy-router:7ba70f0", 8391e00, from local
      Use --docker-image="openshift/origin-haproxy-router:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-haproxy-router:latest", 8391e00, from local
      Use --docker-image="openshift/origin-haproxy-router:latest" to specify this image or template

    * Docker image "openshift/origin-pod:7ba70f0", df56d4e, from local
      Use --docker-image="openshift/origin-pod:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-pod:latest", df56d4e, from local
      Use --docker-image="openshift/origin-pod:latest" to specify this image or template

    * Docker image "openshift/origin-release:latest", 12a65c5, from local
      Use --docker-image="openshift/origin-release:latest" to specify this image or template

    * Docker image "openshift/origin-haproxy-router-base:latest", 71e799e, from local
      Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

    * Docker image "openshift/origin-base:latest", abb5237, from local, 70.131mb
      Use --docker-image="openshift/origin-base:latest" to specify this image or template

    * Docker image "openshift/origin-custom-docker-builder:latest", d7128e9, from local
      Use --docker-image="openshift/origin-custom-docker-builder:latest" to specify this image or template

    * Docker image "openshift/origin-custom-docker-builder:7ba70f0", d7128e9, from local
      Use --docker-image="openshift/origin-custom-docker-builder:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-deployer:latest", 5cd5a66, from local
      Use --docker-image="openshift/origin-deployer:latest" to specify this image or template

    * Docker image "openshift/origin-f5-router:latest", f24facb, from local
      Use --docker-image="openshift/origin-f5-router:latest" to specify this image or template

    * Docker image "openshift/origin-docker-registry:latest", f821f3b, from local, 38.658mb
      Use --docker-image="openshift/origin-docker-registry:latest" to specify this image or template

    * Docker image "openshift/origin-f5-router:7ba70f0", f24facb, from local
      Use --docker-image="openshift/origin-f5-router:7ba70f0" to specify this image or template

    * Docker image "openshift/origin-keepalived-ipfailover:latest", 5b68f13, from local
      Use --docker-image="openshift/origin-keepalived-ipfailover:latest" to specify this image or template

    * Docker image "openshift/origin-sti-builder:7ba70f0", 3a9762e, from local
      Use --docker-image="openshift/origin-sti-builder:7ba70f0" to specify this image or template

Happened in #7128 (job [12095](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/12095/console)).

### PR DESCRIPTION
**Pull request by oatmealraisin**
Limits the amount of suggestions of a faulty new-build command to 5, with highest match score appearing first.

fixes #7729 

Old output: 
```
oc new-build -D $'FROM openshft/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshft/origin:v1.1": 15

The argument "openshft/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin:latest", 819ca62, from local, 133.052mb
  Use --docker-image="docker.io/openshift/origin:latest" to specify this image or template

* Docker image "myproject/origin-test-1:6c16fcd3", 783819e, from local
  Use --docker-image="myproject/origin-test-1:6c16fcd3" to specify this image or template

* Docker image "openshift/origin-release:latest", 8968bf1, from local, 412.836mb
  Use --docker-image="openshift/origin-release:latest" to specify this image or template

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-builder:latest", b171beb, from local
  Use --docker-image="docker.io/openshift/origin-docker-builder:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-registry:latest", b2fbc24, from local, 48.080mb
  Use --docker-image="docker.io/openshift/origin-docker-registry:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-sti-builder:latest", 7464c40, from local
  Use --docker-image="docker.io/openshift/origin-sti-builder:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-deployer:latest", b449a8c, from local
  Use --docker-image="docker.io/openshift/origin-deployer:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-haproxy-router:latest", e77286e, from local, 18.265mb
  Use --docker-image="docker.io/openshift/origin-haproxy-router:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-builder:v1.3.0-alpha.1", 51ecec8, from local
  Use --docker-image="docker.io/openshift/origin-docker-builder:v1.3.0-alpha.1" to specify this image or template

* Docker image "docker.io/openshift/origin-deployer:v1.3.0-alpha.1", 8dcfa74, from local
  Use --docker-image="docker.io/openshift/origin-deployer:v1.3.0-alpha.1" to specify this image or template

* Docker image "docker.io/openshift/origin-pod:latest", cf08328, from local, 1.517mb
  Use --docker-image="docker.io/openshift/origin-pod:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-registry:v1.3.0-alpha.1", 8663602, from local, 45.227mb
  Use --docker-image="docker.io/openshift/origin-docker-registry:v1.3.0-alpha.1" to specify this image or template

* Docker image "docker.io/openshift/origin-pod:v1.3.0-alpha.1", 1086c95, from local, 1.517mb
  Use --docker-image="docker.io/openshift/origin-pod:v1.3.0-alpha.1" to specify this image or template
```

New output:
```
oc new-build -D $'FROM openshft/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshft/origin:v1.1": 15

The argument "openshft/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin:latest", 819ca62, from local, 133.052mb
  Use --docker-image="docker.io/openshift/origin:latest" to specify this image or template

* Docker image "myproject/origin-test-1:6c16fcd3", 783819e, from local
  Use --docker-image="myproject/origin-test-1:6c16fcd3" to specify this image or template

* Docker image "openshift/origin-release:latest", 8968bf1, from local, 412.836mb
  Use --docker-image="openshift/origin-release:latest" to specify this image or template

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template
```

@bparees

### CODE REVIEW

**Comment by smarterclayton** [comment]
That sort order doesn't look right - I would expect origin-base to be below origin:latest.  Where's v1.1*?

**Comment by oatmealraisin** [comment]
@smarterclayton At some point the v1.1 gets ignored and it returns latest.  Any idea where this could be?  I've been looking, can't find it.  From what I've been reading in code, the openshift/origin:v1.1 is passed as one term to the search.  This may also solve the origin-base issue.

**Comment by smarterclayton** [comment]
I think we want to implement a scoring sort that does closeness based on
heuristics that alters the high level sort.

On Jun 21, 2016, at 11:30 AM, Ryan Murphy <notifications@github.com> wrote:

@smarterclayton <https://github.com/smarterclayton> At some point the v1.1
gets ignored and it returns latest. Any idea where this could be? I've been
looking, can't find it. From what I've been reading in code, the
openshift/origin:v1.1 is passed as one term to the search. This may also
solve the origin-base issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/9353#issuecomment-227477729>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABG_p5bb-C1zAraEqiqjzuO36RY4Fe5Hks5qOAOkgaJpZM4I2t4_>
.

**Comment by oatmealraisin** [comment]
Based on dockerimagelookup.go:matchTag() and scorers.go:partialScorer(), it looks like we already implement pretty specific scoring, which gets sorted by sort.Sort.  As for the v1.1 vs latest, I only had :latest images on my machine.  If I pull older images, it returns those as well.  

After a rebase, I've tried to reproduce docker.io/openshift/origin:latest being second on the list, but it is now returned as the top result.

Output is now:
```
 oc new-build -D $'FROM openshft/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshft/origin:v1.1": 12

The argument "openshft/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "docker.io/openshift/origin:latest", 3f9c6ac, from local, 143.030mb
  Use --docker-image="docker.io/openshift/origin:latest" to specify this image or template

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "openshift/origin-release:latest", 8968bf1, from local, 412.836mb
  Use --docker-image="openshift/origin-release:latest" to specify this image or template

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-deployer:v1.3.0-alpha.2", 9dd34e7, from local
  Use --docker-image="docker.io/openshift/origin-deployer:v1.3.0-alpha.2" to specify this image or template
```
@bparees @smarterclayton ptal?

**Comment by bparees** [comment]
and what happens if you also have an "openshift/origin-test:v1.1.2" image and look for origin-test:v1.1?

**Comment by oatmealraisin** [comment]
An exact match would occur with origin-test:v1.1, partial match for v1.1.2 using the search term as a prefix.  Because of the partial match, the process errors out.

The result is:
```
oc new-build -D $'FROM origin-test:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "origin-test:v1.1": 3

The argument "origin-test:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-test:v1.1.2", e934940, from local, author The CentOS Project <cloud-ops@centos.org>
  Use --docker-image="openshift/origin-test:v1.1.2" to specify this image or template

* Docker image "openshift/origin-test:v1.1.1", e934940, from local, author The CentOS Project <cloud-ops@centos.org>
  Use --docker-image="openshift/origin-test:v1.1.1" to specify this image or template

* Docker image "docker.io/openshift/origin:latest", 3f9c6ac, from local, 143.030mb
  Use --docker-image="docker.io/openshift/origin:latest" to specify this image or template

```

I added openshift/origin-test:v1.1.1 to test what would happen with multiple version numbers.

**Comment by bparees** [comment]
thanks.  Just wanted to confirm it appears before :latest in the list.

**Comment by bparees** [comment]
@oatmealraisin you might experiment w/ retagging things on your machine.  I suspect whether origin or origin-base shows up first depends on which one was tagged/created more recently on your local machine, as opposed to a definitive order.  It would be good to check that before we conclude it's working correctly.

**Comment by oatmealraisin** [comment]
I changed the scoring so that the versions are prefixed, so v1.1 will partially match with v1.1*, etc. 
@bparees ptal?

**Comment by bparees** [comment]
lgtm.  @smarterclayton was there a reason you didn't want to partially score the tags?  (or anything else for that matter?)

**Comment by oatmealraisin** [comment]
[test]

**Comment by smarterclayton** [comment]
My primary concern was "the smell test" - when a user looks at the
list, what matches would they consider "obvious".  Tag prefixes are
easy (when a user gives us a tag), but it seems unlikely that a user
asking for foo/bar expects bar or foo to match the tag.

A lot of this is asking yourself which match should be higher in
common input cases and figuring out how to prioritize them.  Users
will be angry if we look lazy, but if we're even broadly helpful
that's enough.

**Comment by bparees** [comment]
Given that answer seems like partially matching the tags makes sense, so i'm going to call a lgtm on this.
[merge]

**Comment by bparees** [comment]
actually i'm going to retract that.  if we're cutting the result list at 5, we should print a message letting the user know that not all matches are being displayed.

**Comment by smarterclayton** [comment]
Yeah, and tell them to use -S to do it (I assume -S doesn't trim, right?)

**Comment by oatmealraisin** [comment]
@smarterclayton 
I thought that new-build didn't have -S?  Should we point them at new-app -S --dry-run?

**Comment by oatmealraisin** [comment]
re[test]

**Comment by smarterclayton** [comment]
New-build should have -S.  IF we haven't added it yet.... well... that makes this harder.  I assume you fixed new-app as well?

**Comment by oatmealraisin** [comment]
new-build doesn't have -S.  Should be pretty easy to implement, though!

This should fix anything that returns a ErrMulti, so I believe it fixes new-app.

**Comment by oatmealraisin** [comment]
Added some logic to point at `oc new-app -S <input>` only if we cut output.  Otherwise, proceed as normal.

Previous output, more than 5 results:
```
oc new-build -D $'FROM openshif/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshif/origin:v1.1": 8

The argument "openshif/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-release:latest", 8968bf1, from local, 412.836mb
  Use --docker-image="openshift/origin-release:latest" to specify this image or template

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-release:latest", 9d53669, from local
  Use --docker-image="docker.io/openshift/origin-release:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-base:latest", 811acd6, from local
  Use --docker-image="docker.io/openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-deployer:v1.3.0-alpha.1", 8dcfa74, from local
  Use --docker-image="docker.io/openshift/origin-deployer:v1.3.0-alpha.1" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-registry:v1.3.0-alpha.1", 8663602, from local, 45.227mb
  Use --docker-image="docker.io/openshift/origin-docker-registry:v1.3.0-alpha.1" to specify this image or template

* Docker image "docker.io/openshift/origin-pod:v1.3.0-alpha.1", 1086c95, from local, 1.517mb
  Use --docker-image="docker.io/openshift/origin-pod:v1.3.0-alpha.1" to specify this image or template

```

New output, more than 5 results:
```
oc new-build -D $'FROM openshif/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshif/origin:v1.1": 8

The argument "openshif/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-release:latest", 8968bf1, from local, 412.836mb
  Use --docker-image="openshift/origin-release:latest" to specify this image or template

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-release:latest", 9d53669, from local
  Use --docker-image="docker.io/openshift/origin-release:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-base:latest", 811acd6, from local
  Use --docker-image="docker.io/openshift/origin-base:latest" to specify this image or template

To view a full list of matches, use 'oc new-app -S openshif/origin:v1.1'
```

Previous output, less than 5 results:
```
oc new-build -D $'FROM openshif/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshif/origin:v1.1": 4

The argument "openshif/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-registry:v1.3.0-alpha.2", f729de7, from local, 48.080mb
  Use --docker-image="docker.io/openshift/origin-docker-registry:v1.3.0-alpha.2" to specify this image or template

* Docker image "docker.io/openshift/origin-pod:v1.3.0-alpha.2", b8d4571, from local, 1.517mb
  Use --docker-image="docker.io/openshift/origin-pod:v1.3.0-alpha.2" to specify this image or template
```

New output, less than 5 results:
```
oc new-build -D $'FROM openshif/origin:v1.1\nENV ok=1' --to origin-test:v1.1
error: multiple images or templates matched "openshif/origin:v1.1": 4

The argument "openshif/origin:v1.1" could apply to the following Docker images, OpenShift image streams, or templates:

* Docker image "openshift/origin-haproxy-router-base:latest", eeadaef, from local, 18.243mb
  Use --docker-image="openshift/origin-haproxy-router-base:latest" to specify this image or template

* Docker image "openshift/origin-base:latest", 3788e83, from local, 74.943mb
  Use --docker-image="openshift/origin-base:latest" to specify this image or template

* Docker image "docker.io/openshift/origin-docker-registry:v1.3.0-alpha.2", f729de7, from local, 48.080mb
  Use --docker-image="docker.io/openshift/origin-docker-registry:v1.3.0-alpha.2" to specify this image or template

* Docker image "docker.io/openshift/origin-pod:v1.3.0-alpha.2", b8d4571, from local, 1.517mb
  Use --docker-image="docker.io/openshift/origin-pod:v1.3.0-alpha.2" to specify this image or template
```

**Comment by oatmealraisin** [comment]
[test]

**Comment by oatmealraisin** [comment]
@bparees @smarterclayton ptal?

File: pkg/cmd/cli/cmd/newapp.go [hunk 1]
```diff
@@ -639,10 +639,29 @@ func transformError(err error, commandName, commandPath string, groups errorGrou
...
+					heredoc.Docf(`
+						The argument %[1]q could apply to the following Docker images, OpenShift image streams, or templates:
+
+						%[2]sTo view a full list of matches, use 'oc new-app -S %[1]s'`, t.Value, buf.String(),
+					),
+					t,
+					t.Errs...,
+				)
+
+				return
```
Comment (bparees) [inline pkg/cmd/cli/cmd/newapp.go]: probably safer to break instead of return, lest we add additional processing/output at the bottom of this method.

Comment (bparees) [inline pkg/cmd/cli/cmd/newapp.go]: nm, i see why you returned. this is fine.

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by bparees** [comment]
i don't think @oatmealraisin actually had the "openshif/origin:v1.1" tag in his local docker daemon.  notice it wasn't in the full listing either (the "previous output" example)

**Comment by oatmealraisin** [comment]
@smarterclayton like bparees I didn't have any closer images unfortunately.  I had been messing with my docker images, so they are a bit odd.  I tested the v1.1 functionality earlier in the thread, if that helps!

**Comment by smarterclayton** [comment]
OK.
