### PR TITLE
Annotate roles with systemOnly

### LINKED ISSUE #14411: Influx of roles w/o systemOnly annotation
There is a sudden influx of roles coming back from the API. We believe it is due to kubernetes imports.  Previously ~ 8 roles made it through our `systemOnly` filter.  At the moment I'm seeing 53 (with 101 total roles).

Filtered:

```
["admin","basic-user","edit","system:auth-delegator","system:basic-user","system:build-controller","system:certificate-signing-controller","system:controller:attachdetach-controller","system:controller:certificate-controller","system:controller:cronjob-controller","system:controller:daemon-set-controller","system:controller:deployment-controller","system:controller:disruption-controller","system:controller:endpoint-controller","system:controller:generic-garbage-collector","system:controller:horizontal-pod-autoscaler","system:controller:job-controller","system:controller:namespace-controller","system:controller:node-controller","system:controller:persistent-volume-binder","system:controller:pod-garbage-collector","system:controller:replicaset-controller","system:controller:replication-controller","system:controller:resourcequota-controller","system:controller:route-controller","system:controller:service-account-controller","system:controller:service-controller","system:controller:statefulset-controller","system:controller:ttl-controller","system:daemonset-controller","system:deployer","system:deployment-controller","system:deploymentconfig-controller","system:disruption-controller","system:endpoint-controller","system:garbage-collector-controller","system:gc-controller","system:heapster","system:hpa-controller","system:image-builder","system:image-puller","system:image-pusher","system:job-controller","system:kube-aggregator","system:kube-controller-manager","system:kube-dns","system:kube-scheduler","system:namespace-controller","system:node-problem-detector","system:replicaset-controller","system:replication-controller","system:statefulset-controller","view"]
```

Unfiltered:

```
["admin","basic-user","cluster-admin","cluster-debugger","cluster-reader","cluster-status","edit","registry-admin","registry-editor","registry-viewer","self-access-reviewer","self-provisioner","storage-admin","sudoer","system:auth-delegator","system:basic-user","system:build-controller","system:build-strategy-custom","system:build-strategy-docker","system:build-strategy-jenkinspipeline","system:build-strategy-source","system:certificate-signing-controller","system:controller:attachdetach-controller","system:controller:certificate-controller","system:controller:cronjob-controller","system:controller:daemon-set-controller","system:controller:deployment-controller","system:controller:disruption-controller","system:controller:endpoint-controller","system:controller:generic-garbage-collector","system:controller:horizontal-pod-autoscaler","system:controller:job-controller","system:controller:namespace-controller","system:controller:node-controller","system:controller:persistent-volume-binder","system:controller:pod-garbage-collector","system:controller:replicaset-controller","system:controller:replication-controller","system:controller:resourcequota-controller","system:controller:route-controller","system:controller:service-account-controller","system:controller:service-controller","system:controller:statefulset-controller","system:controller:ttl-controller","system:daemonset-controller","system:deployer","system:deployment-controller","system:deploymentconfig-controller","system:discovery","system:disruption-controller","system:endpoint-controller","system:garbage-collector-controller","system:gc-controller","system:heapster","system:hpa-controller","system:image-auditor","system:image-builder","system:image-pruner","system:image-puller","system:image-pusher","system:image-signer","system:imagetrigger-controller","system:job-controller","system:kube-aggregator","system:kube-controller-manager","system:kube-dns","system:kube-scheduler","system:master","system:namespace-controller","system:node","system:node-admin","system:node-bootstrapper","system:node-problem-detector","system:node-proxier","system:node-reader","system:oauth-token-deleter","system:openshift:controller:build-controller","system:openshift:controller:deployer-controller","system:openshift:controller:deployment-trigger-controller","system:openshift:controller:deploymentconfig-controller","system:openshift:controller:template-instance-controller","system:openshift:template-service-broker","system:openshift:templateservicebroker-client","system:persistent-volume-provisioner","system:pv-attach-detach-controller","system:pv-binder-controller","system:pv-provisioner-controller","system:pv-recycler-controller","system:registry","system:replicaset-controller","system:replication-controller","system:router","system:sdn-manager","system:sdn-reader","system:service-ingress-ip-controller","system:service-load-balancer-controller","system:service-serving-cert-controller","system:statefulset-controller","system:unidling-controller","system:webhook","view"]
```

##### Version
oc v3.6.0-alpha.1+a1dffba-860-dirty
kubernetes v1.6.1+5115d708d7
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.6.0-alpha.1+3ecdeba-864
kubernetes v1.6.1+5115d708d7

bpeterse at dhcp129-188 in ~/

##### Steps To Reproduce
In web console, navigate to `membership` page, click `edit membership`, use any of the select boxes under the `Add another role` heading.  Toggle the `show hidden roles` checkbox.

##### Current Result
53 filtered roles, 101 total roles

##### Expected Result
8 filtered roles, 101 total roles

@enj @jwforres

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes #14411 

Update the bootstrap/policy convertClusterRoles function to annotate systemOnly roles

A short whitelist is included in this file defining the expected roles that
should be visible to an end user.  All other roles should receive the
systemOnly annotation allowing the web console (or other clients) to
filter and provide a friendly user experience.

Future roles should be considered against this whitelist and discussed
with the web console team.

- updates bootstrappolicy/policy convertClusterRoles
- adds web_console_role_test.go to bootstrappolicy package

Example of test failure:

screen shot 2017-06-07 at 1 37 38 pm

current whitelist:

```go
var rolesToShow = sets.NewString(
	"admin",
	"basic-user",
	"edit",
	"system:deployer",
	"system:image-builder",
	"system:image-puller",
	"system:image-pusher",
	"view",
)
```

current blacklist:

```go
var rolesToHide = sets.NewString(
	"cluster-admin",
	"cluster-debugger",
	"cluster-reader",
	"cluster-status",
	"registry-admin",
	"registry-editor",
	"registry-viewer",
	"self-access-reviewer",
	"self-provisioner",
	"storage-admin",
	"sudoer",
	"system:auth-delegator",
	"system:build-strategy-custom",
	"system:build-strategy-docker",
	"system:build-strategy-jenkinspipeline",
	"system:build-strategy-source",
	"system:discovery",
	"system:heapster",
	"system:image-auditor",
	"system:image-pruner",
	"system:image-signer",
	"system:kube-aggregator",
	"system:kube-controller-manager",
	"system:kube-dns",
	"system:kube-scheduler",
	"system:master",
	"system:node",
	"system:node-admin",
	"system:node-bootstrapper",
	"system:node-problem-detector",
	"system:node-proxier",
	"system:node-reader",
	"system:oauth-token-deleter",
	"system:openshift:template-service-broker",
	"system:openshift:templateservicebroker-client",
	"system:persistent-volume-provisioner",
	"system:registry",
	"system:router",
	"system:sdn-manager",
	"system:sdn-reader",
	"system:webhook",
)
```

Much thanks to @enj for assistance in this PR.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@liggitt @jwforres

File: pkg/cmd/server/bootstrappolicy/web_console_role_test.go [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+
+// NOTE: If this test fails, talk to the web console team to decide if your
+// new role(s) should be visible to an end user in the web console.
+
+var rolesToHide = sets.NewString(
+	"cluster-admin",
+	"cluster-debugger",
+	"cluster-reader",
+	"cluster-status",
+	"registry-admin",
```
Comment (liggitt) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: why are these roles in here? these don't come from kube

Comment (benjaminapetersen) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: So if I remove them the test will fail like this:
screen shot 2017-06-07 at 2 59 01 pm 

The goal was to make it as easy/painless as possible for someone unfamiliar with the `systemOnly` annotation to just add the string name of their role to either `rolesToShow` or `rolesToHide`, get the test to pass & keep the console clean/free of future surprises.

The only "special" case we made is the `isControllerRole()` function, to make it slightly easier to maintain this list.  I'm not terribly concerned (in this test) where the roles come from, so long as they are correctly hidden/visible in the end.

Do you have a preference for a change here?

Comment (enj) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: To add to what Ben said, `rolesToShow` is used by the test so it must include all roles, not just the Kube ones.  I am considering a followup to make it so the Origin roles are not manually annotated, and instead use the same logic with `rolesToShow`.  I think this will make it easier in the long run to keep things in sync (only two lists to keep up to date).

File: pkg/cmd/server/bootstrappolicy/web_console_role_test.go [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+// it is the same logic that is run on the membership page
+func isSystemOnlyRole(role authorizationapi.ClusterRole) bool {
+	return role.Annotations[roleSystemOnly] == roleIsSystemOnly
+}
+
+// helper so that roles following this pattern do not need to be manaully added
+// to the hide list
+func isControllerRole(role *authorizationapi.ClusterRole) bool {
+	return strings.HasPrefix(role.Name, "system:controller:") ||
+		strings.HasPrefix(role.Name, "system:controller:openshift:") ||
```
Comment (enj) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: The `system:controller:openshift:*` check is unnecessary since its covered by the first one.

File: pkg/cmd/server/bootstrappolicy/web_console_role_test.go [hunk 3]
```diff
@@ -0,0 +1,102 @@
+package bootstrappolicy
+
+import (
+	// standard lib
```
Comment (enj) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: Remove comments from import block.

Comment (benjaminapetersen) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: done

File: pkg/cmd/server/bootstrappolicy/web_console_role_test.go (hunk 2 above)
Comment (benjaminapetersen) [inline pkg/cmd/server/bootstrappolicy/web_console_role_test.go]: done

**Comment by benjaminapetersen** [comment]
[test]

**Comment by benjaminapetersen** [comment]
Updated.
Ran `UPDATE_BOOTSTRAP_POLICY_FIXTURE_DATA=true hack/test-go.sh pkg/cmd/server/bootstrappolicy` to regen the yaml.

[test]

File: pkg/cmd/server/bootstrappolicy/policy.go [hunk 4]
```diff
@@ -1321,8 +1321,24 @@ func convertClusterRoles(in []rbac.ClusterRole) ([]authorizationapi.ClusterRole,
...
+			newRole.Annotations[roleSystemOnly] = roleIsSystemOnly
+		}
 		out = append(out, *newRole)
 	}
 
 	return out, kutilerrors.NewAggregate(errs)
 }
+
+// The current list of roles considered useful for normal users (non-admin)
+var rolesToShow = sets.NewString(
```
Comment (jwforres) [inline pkg/cmd/server/bootstrappolicy/policy.go]: @enj yes this looks like the right list to me

**Comment by enj** [comment]
[merge]
