### PR TITLE
Volume strategic merge

### LINKED ISSUE #4351: Volume command doesn't retry on conflicts
`oc volume dc/test-deployment-config --remove --confirm`

```
error: deploymentConfig "test-deployment-config" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
!!! Error in test/cmd/volumes.sh:29
  '[ "$(oc volume dc/test-deployment-config --remove --confirm)" ]' exited with status 1
Call stack:
  1: test/cmd/volumes.sh:29 main(...)
Exiting with status 1
!!! Error in hack/test-cmd.sh:269
  '${test}' exited with status 1
Call stack:
  1: hack/test-cmd.sh:269 main(...)
```

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/4461/console

### PR DESCRIPTION
**Pull request by gnufied**
Implement volume request using strategic merge patch. Fixes #4351

### CODE REVIEW

**Comment by fabianofranz** [comment]
@openshift/cli-review @deads2k

**Comment by fabianofranz** [comment]
@liggitt

**Comment by fabianofranz** [comment]
[test]

**Comment by fabianofranz** [comment]
Needs tests.

**Comment by fabianofranz** [comment]
@smarterclayton

**Comment by gnufied** [comment]
@fabianofranz okay I am going to add some unit tests. Or did you mean some e2e tests too?

**Comment by gnufied** [comment]
please hold on from merging this until I add some more tests.

**Comment by fabianofranz** [comment]
@gnufied unit and if possible something in `test/cmd/volumes.sh`. Thanks!

**Comment by gnufied** [comment]
@fabianofranz PTAL, I have added unit tests for this.  I do not think it is easily doable to further test this via `test/cmd/volume.sh` externally since nothing changes from end user perspective. cc @childsb

File: pkg/cmd/cli/cmd/set/volume_test.go [hunk 1]
```diff
@@ -0,0 +1,109 @@
...
+		GroupVersionKind: unversioned.GroupVersionKind{
+			Group:   "test.group",
+			Version: "v1",
+		},
+		ObjectConvertor: api.Scheme,
+	}
+	return fakeMapping
+}
+
+func TestVolumeRunWithPatch(t *testing.T) {
```
Comment (jsafrane) [inline pkg/cmd/cli/cmd/set/volume_test.go]: I would appreciate a test both for add and remove, this one does remove only.

Comment (gnufied) [inline pkg/cmd/cli/cmd/set/volume_test.go]: okay, will add. But partly It was intentional, the add path requires mocked objects which are rather complicated to fake/mock. :(

**Comment by fabianofranz** [comment]
@deads2k could you give this one a pass?

File: pkg/cmd/cli/cmd/set/volume.go [hunk 2]
```diff
@@ -391,6 +394,14 @@ func (v *VolumeOptions) RunVolume(args []string) error {
 		return err
 	}
 
+	if v.List {
+		listingErrors := v.printVolumes(infos)
+		if len(listingErrors) > 0 {
+			return cmdutil.ErrExit
```
Comment (deads2k) [inline pkg/cmd/cli/cmd/set/volume.go]: why aren't errors reported here?

**Comment by deads2k** [comment]
I didn't go super deep, but it looks reasonable.

File: pkg/cmd/cli/cmd/set/volume.go (hunk 2 above)
Comment (gnufied) [inline pkg/cmd/cli/cmd/set/volume.go]: I could move error printing to here but since `v.printVolumes` already prints the errors, I did not bother.

File: pkg/cmd/cli/cmd/set/volume_test.go (hunk 1 above)
Comment (gnufied) [inline pkg/cmd/cli/cmd/set/volume_test.go]: Added a test for the scenario when volume is added as well.

**Comment by gnufied** [comment]
@jsafrane Added a test case for add volume scenario as well. PTAL.

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by deads2k** [comment]
Could use a squash.

**Comment by fabianofranz** [comment]
> Could use a squash.

Right, holding merge until it gets squashed.

**Comment by gnufied** [comment]
@fabianofranz @deads2k Okay, I have squashed the commits.

**Comment by fabianofranz** [comment]
LGTM [merge]

**Comment by gnufied** [comment]
[test]

**Comment by gnufied** [comment]
The error here looks like a flake.

**Comment by fabianofranz** [comment]
Flaked on https://github.com/openshift/origin/issues/11094
re[merge]

**Comment by gnufied** [comment]
@fabianofranz @childsb  while I am looking at https://github.com/openshift/origin/issues/11094 do we want to block this PR from getting merged?

**Comment by fabianofranz** [comment]
@gnufied no, that's a flake unrelated to this PR. Working on it does not prevent this from getting merged.

**Comment by gnufied** [comment]
#11094 [merge]
