### PR TITLE
NO-JIRA: Fix issue 28445

### LINKED ISSUE #28445: openshift-tests dry-run is failing
`openshift-tests` binary is throwing error asking for cluster configuration even for a dry-run.
```
error running options: could not load client configuration: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variableerror: could not load client configuration: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
Ideally, a dry run shouldn't be expecting cluster details as it only displays list of tests.

This is occurring after the change https://github.com/openshift/origin/pull/28436

[root@raji-workspace2 origin]# openshift-tests run all --dry-run

##### Steps To Reproduce
1. git clone https://github.com/openshift/origin
2. cd origin
3. make GO_REQUIRED_MIN_VERSION:= WHAT=cmd/openshift-tests
4. ./openshift-tests run kubernetes/conformance --dry-run

##### Current Result
Fails to run openshift-tests dry-run
##### Expected Result
Should display the list of tests

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Fixes #28445
The check of DryRun variable at https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/cmd_runsuite.go#L235 must be done before calling `clusterinfo.GetMonitorRESTConfig` at https://github.com/openshift/origin/blob/master/pkg/test/ginkgo/cmd_runsuite.go#L200

### CODE REVIEW

**Comment by Rajalakshmi-Girish** [comment]
Our job at https://prow.ppc64le-cloud.cis.ibm.net/job-history/s3/ppc64le-prow-logs/logs/postsubmit-os-origin-build-golang-master-ppc64le has been failing since 6th Dec night IST after the merge of https://github.com/openshift/origin/pull/28436

image

**Comment by Rajalakshmi-Girish** [comment]
@jwforres @mfojtik Can you please take a look?

**Comment by mfojtik** [comment]
cc @soltysh

File: pkg/test/ginkgo/cmd_runsuite.go [hunk 1]
```diff
@@ -258,6 +247,17 @@ func (o *GinkgoRunSuiteOptions) Run(suite *TestSuite, junitSuiteName string, mon
 		parallelism = 10
 	}
 
+        restConfig, err := clusterinfo.GetMonitorRESTConfig()
```
Comment (soltysh) [inline pkg/test/ginkgo/cmd_runsuite.go:250]: @Rajalakshmi-Girish two things to address:
1. please move this right after the `DryRun` one, that's sufficient to make it work
2. please make sure to `gofmt` your code, otherwise it'll fail

**Review by soltysh — CHANGES_REQUESTED** [review]

File: pkg/test/ginkgo/cmd_runsuite.go (hunk 1 above)
Comment (Rajalakshmi-Girish) [reply pkg/test/ginkgo/cmd_runsuite.go]: @soltysh Can you please check now?

**Comment by Rajalakshmi-Girish** [comment]
@soltysh Can you please take a look now?

**Review by soltysh — APPROVED** [review]
/ok-to-test
/lgtm
/approve
