### PR TITLE
Fix logic to add Dockerfile to BuildConfig

### LINKED ISSUE #6675: oc new-app with repo containing dockerfile does the wrong thing
if the repo contains a dockerfile, new-app is creating a Dockerfile input in the buildconfig (containing the content of the dockerfile from the repo), which means if the user updates their dockerfile in the repo and rebuilds, they won't get any changes since the dockerfile defined in the BC takes precedence.

### PR DESCRIPTION
**Pull request by rhcarvalho**
Distinguish when AddDockerfile was called, and only then append the
Dockerfile contents.

This fixes a bug where 'oc new-app' would incorrectly add Dockerfile
contents if there is a Dockerfile in the source Git repository.

Fixes #6675.

### CODE REVIEW

**Comment by rhcarvalho** [comment]
@bparees PTAL

**Comment by rhcarvalho** [comment]
I tried to add tests in `pkg/generate/app/cmd/newapp_test.go:TestRunAll` to cover this and prevent a future regression, but I could not reproduce the bug with that level of testing. My guess is that the mock components influence the resulting list of objects.

This would be a bit harder to test in `test/cmd`, because we're trying to ensure that the output doesn't have any contents in the Dockerfile field (nor anything other than Git)... possible to write, but might not be the most beautiful thing.

@bparees any suggestions in this matter?

**Comment by rhcarvalho** [comment]
This PR should make all flows of `oc new-app` and `oc new-build` behave the same as before #6615 merged, with the exception of the flow that #6615 intended to fix: creating a build config from multiple sources.

**Comment by liggitt** [comment]
can we add tests for the broken cases to make sure we fixed them and make sure we don't regress?

**Comment by bparees** [comment]
> This would be a bit harder to test in test/cmd, because we're trying to ensure that the output doesn't have any contents in the Dockerfile field (nor anything other than Git)... possible to write, but might not be the most beautiful thing.

i think you can use expect_success_and_not_text_contains (or whatever it's called) at least for now to ensure the dockerfile didn't get injected in the buildconfig.

File: pkg/generate/app/sourcelookup.go [hunk 1]
```diff
@@ -378,7 +380,7 @@ func StrategyAndSourceForRepository(repo *SourceRepository, image *ImageRef) (*B
 		Binary: repo.binary,
 	}
 
-	if repo.Info() != nil && repo.Info().Dockerfile != nil {
+	if (repo.ignoreRepository || repo.dockerfile) && repo.Info() != nil && repo.Info().Dockerfile != nil {
```
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: what's this "ignoreRepository" magic and why is it coming back?

**Comment by rhcarvalho** [comment]
@bparees @liggitt wdyt about reusing one of the existing calls to new-app with "github.com/openshift/ruby-hello-world"?

one of the 11 hits in

- test/cmd/basicresources.sh
- test/cmd/builds.sh
- test/cmd/newapp.sh

though @liggitt's idea of using jsonpath would make it neater, at the expense of a 12th incarnation of a similar call.

File: pkg/generate/app/sourcelookup.go (hunk 1 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: It is coming back to fix the bug that was introduced. The idea is that I'm reverting to how it worked before, and now adding a new bool that is only used by new-build.

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: `ignoreRepository` was set to true when creating a reference to a dockerfile as a single source for a build, so that this branch would be executed, while the next one would not (look at the whole function body)

**Comment by liggitt** [comment]
don't touch existing calls, add new ones for new test cases. something like:
```
# positive check
expect_success_and_text "oc new-app <args that would result in a dockerfile> -o=jsonpath={..spec.source.dockerfile}" "FROM ..."
# negative check
expect_success_and_text "oc new-app <args that would not result in a dockerfile> -o=jsonpath={..spec.source.git.uri}" "http://..."
expect_failure_and_text "oc new-app <args that would not result in a dockerfile> -o=jsonpath={..spec.source.dockerfile}" "dockerfile is not found"
```

File: pkg/generate/app/sourcelookup.go (hunk 1 above)
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: i know you didn't introduce it, but that's a horrible name for a field(way too generic) and the logic using it needs commenting. [/rant]

File: pkg/generate/app/sourcelookup.go [hunk 2]
```diff
@@ -90,6 +90,7 @@ type SourceRepository struct {
 	buildWithDocker  bool
 	ignoreRepository bool
 	binary           bool
+	dockerfile       bool
```
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: comment this field or rename it.

It means that the repository has an explicitly provided dockerfile from the CLI, not to be confused with meaning the git repo contains a dockerfile.

Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: this needs to be more specific... does this mean "extract the dockerfile from the repo?"

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: From this struct's perspective, it doesn't know about the CLI. It's more about "was AddDockerfile called?"
Will think about how to make it better once I figure out the regression test.

File: pkg/generate/app/sourcelookup.go (hunk 1 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: :cry:

File: pkg/generate/app/sourcelookup.go (hunk 2 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: Calling it `forceAddDockerfile` now.

Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: or `inlineDockerfile`... something to indicate the effect it will have

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: hasExternalDockerFileInput :)

**Comment by rhcarvalho** [comment]
Added regression test, @bparees @liggitt PTAL

**Comment by rhcarvalho** [comment]
[test]

**Comment by rhcarvalho** [comment]
BTW, I tested that the test fails without the patch :smile:

File: pkg/generate/app/sourcelookup.go [hunk 3]
```diff
@@ -378,7 +381,7 @@ func StrategyAndSourceForRepository(repo *SourceRepository, image *ImageRef) (*B
 		Binary: repo.binary,
 	}
 
-	if repo.Info() != nil && repo.Info().Dockerfile != nil {
+	if (repo.ignoreRepository || repo.forceAddDockerfile) && repo.Info() != nil && repo.Info().Dockerfile != nil {
```
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: i'm still bothered by this ignoreRepository name+lack of comments (what's the scenario where ignoreRepository is true and forceAddDockerfile is false?  I don't think there is one, so just checking forceAddDockerfile should be sufficient here)

File: test/cmd/newapp.sh [hunk 4]
```diff
@@ -167,4 +167,7 @@ os::cmd::expect_success 'oc new-app mongo -o json | python -m json.tool'
 # Ensure custom branch/ref works
 os::cmd::expect_success 'oc new-app https://github.com/openshift/ruby-hello-world#beta4'
 
+# Ensure the resulting BuildConfig doesn't have unexpected sources
+os::cmd::expect_success_and_not_text 'oc new-app https://github.com/openshift/ruby-hello-world -o=jsonpath="{.items[?(@.kind==\"BuildConfig\")].spec.source}"' 'dockerfile|binary'
```
Comment (liggitt) [inline test/cmd/newapp.sh]: add `--output-version=v1` to make sure we're running jsonpath on the right api version

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: agree

Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: and I would prefer a name like `inlineDockerfile`... @bparees, any better ideas?

Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: inlineDockerfile is ok with me i guess.

File: test/cmd/newapp.sh (hunk 4 above)
Comment (bparees) [inline test/cmd/newapp.sh]: do we have a test case that we're confident in for --dockerfile?  I don't see any newapp.sh invocation that tests it and you(@rhcarvalho) have made me nervous about the reliability of our integration tests due to the mocking.

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: `ignoreRepository` is true if the `SourceRepository` was created by either `NewSourceRepositoryForDockerfile` or `NewBinarySourceRepository`.

Unless we'll dig deeper and make further tests, I don't want to change that logic.

The current patch makes it be "whatever it was before + make `oc new-build <repo> --dockerfile` work".

File: test/cmd/newapp.sh (hunk 4 above)
Comment (rhcarvalho) [inline test/cmd/newapp.sh]: Added.

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: i can live with it for now but i'd definitely like to see this logic renamed/commented/cleaned up in a follow up.

File: test/cmd/newapp.sh (hunk 4 above)
Comment (bparees) [inline test/cmd/newapp.sh]: where?

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: I think `inlineDockerfile` tells *less* about the intent of the bool. For that to make sense, a reader needs to think about that coming from `oc new-build --dockerfile ...`, if that is what "inline" means in the context.

All the bool does for now, if you think about this PR + #6615 together, is to hint us into adding the Dockerfile contents, however and wherever it came from (because, sadly, it is quite hard to reason about it).

@bparees :+1: for a follow up.

Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: no, inline means the docker file will be inlined into the resulting build config

Comment (liggitt) [inline pkg/generate/app/sourcelookup.go]: `addDockerfileToBuildConfig` :)

**Comment by liggitt** [comment]
@smarterclayton for approval, needed to prevent regression in new-app

File: test/cmd/newapp.sh (hunk 4 above)
Comment (rhcarvalho) [inline test/cmd/newapp.sh]: @bparees I am confident with the tests we added in #6615. If want to take another look:

https://github.com/openshift/origin/blob/38319a8338660479e1bfe6da31b6279865c5eba1/pkg/generate/app/cmd/newapp_test.go#L1131-L1165

and 

https://github.com/openshift/origin/blob/38319a8338660479e1bfe6da31b6279865c5eba1/pkg/generate/app/cmd/newapp_test.go#L1200-L1212


The comment about mocking was related to image discovery, it doesn't invalidate our existing tests, but just make certain scenarios hard to reproduce (with the current mocks, that we could improve and make it suitable for testing multiple match scenarios).

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: > All the bool does for now, if you think about this PR + #6615 together, is to hint us into adding the Dockerfile contents, however and wherever it came from (because, sadly, it is quite hard to reason about it).

if it's a hint as to whether or not we should add the dockerfile content, then @liggitt's inlineDockerfile (or addDockerfileToBuildConfig) makes perfect sense.  "dockerfile" tells me nothing.

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: > addDockerfileToBuildConfig :)

I started with that ;)
However, the problem is that that name lies. There are cases when we add the Dockerfile to the BC and this bool is false (and this is obvious by looking at the if condition).

I'll quote @smarterclayton here:

> Names are names - they get used a small fraction of the time.  Worrying
about names too much is just as bad as worrying not enough about names.

So let's not bikeshed on this. I'm willing to clean this up in a follow up.

Comment (rhcarvalho) [inline pkg/generate/app/sourcelookup.go]: > "dockerfile" tells me nothing.

Hmm it's not "dockerfile" for some hours already :)

Take a fresh look, it's been called "forceAddDockerfile".

File: test/cmd/newapp.sh (hunk 4 above)
Comment (rhcarvalho) [inline test/cmd/newapp.sh]: > where?

I meant I added the `--output-version=v1` @liggitt asked for. Just saw your comment later, and answered in the previous comment above. Reiterating, I'm confident with the tests we have for the behavior change we introduced in #6615.

**Comment by liggitt** [comment]
LGTM, would like @bparees sign off as well and @smarterclayton's approval

File: pkg/generate/app/sourcelookup.go (hunk 3 above)
Comment (bparees) [inline pkg/generate/app/sourcelookup.go]: >>    Names are names - they get used a small fraction of the time. Worrying
>>    about names too much is just as bad as worrying not enough about names.

> So let's not bikeshed on this. I'm willing to clean this up in a follow up.

that's a hilarious quote given how many times he has forced name changes on fields.  i'll have to remember that one.

also the whole reason this regression occurred is because of the poorly named "ignoreRepository" field.  If it were named better, I bet this issue would not have occurred when you were making your changes.

So I'd rather not underestimate the importance of good names.

but i'm fine with forceAddDockerfile at this point.

**Comment by bparees** [comment]
lgtm.

**Comment by smarterclayton** [comment]
Approved

**Comment by bparees** [comment]
batted 50% on tests....failure looks like the image-import timeout issue.  [merge]

**Comment by bparees** [comment]
```
FAILURE after 60.044s: hack/../test/cmd/newapp.sh:21: executing 'oc get imagestreamtags mysql:latest' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
There was no output from the command.
```

@deads2k @liggitt what's the prognosis on getting the import parallelization back in?

[merge]

**Comment by deads2k** [comment]
> @deads2k @liggitt what's the prognosis on getting the import parallelization back in?

I probably won't bother until https://github.com/openshift/origin/pull/6288 lands and depending on @liggitt's preference I may tidy up the partitioning bucketer I built here: https://github.com/openshift/origin/pull/6658 to do it.
