### PR TITLE
fix nodelist defaulting

### LINKED ISSUE #1161: `openshift start master` should not automatically create a node entry
While it is helpful for `openshift start` to automatically add `$(hostname -f)` as a node for the 30-second all-in-one startup scenario, this is not desirable when starting just the master; nodes should be added explicitly, and we can't assume the master will be one. The self entry in that case is likely to confuse and, being defined automatically, may not specify resource availability consistently with the way other nodes are defined even if it is desired.

We discussed other flags for preventing auto-adding self as node at startup, but the simplest/clearest approach seems to be to distinguish `openshift start` (where you would need and expect self to be added) from `openshift start master` (where you would not).

### PR DESCRIPTION
**Pull request by deads2k**
Fixes #1161 

When running an all-in-one, we always make sure that the --hostname parameter is included in the nodelist.  When running an explicit master (`openshift start master`), we never touch the list.

@liggitt

### CODE REVIEW

File: pkg/cmd/server/command.go [hunk 1]
```diff
@@ -126,4 +129,18 @@ func (cfg *Config) Complete(args []string) {
 		// if we've explicitly called out an etcd server, don't start etcd in-process
 		cfg.StartEtcd = !cfg.EtcdAddr.Provided
 	}
+
+	// if this is an all-in-one start, be sure to add our hostname to the NodeList if it is not already present
+	isAllInOne := (len(args) == 0)
+	if isAllInOne {
+		nodeList := util.NewStringSet(cfg.NodeList...)
```
Comment (liggitt) [inline pkg/cmd/server/command.go]: build the set by iterating over the list, `ToLower`-ing, and `ToLower` hostname, to make sure `--hostname=Localhost --nodes=localhost` doesn't make you end up with `localhost, localhost`

Comment (deads2k) [inline pkg/cmd/server/command.go]: done.

File: pkg/cmd/server/command_test.go [hunk 2]
```diff
@@ -164,11 +164,26 @@ func TestCommandBindingHostname(t *testing.T) {
...
 }
 
-func TestCommandBindingNodes(t *testing.T) {
+// AllInOne always adds the default hostname
+func TestCommandBindingNodesForAllInOneAppend(t *testing.T) {
 	valueToSet := "first,second,third"
 	actualCfg := executeCommand([]string{"--nodes=" + valueToSet})
 
 	expectedConfig := NewDefaultConfig()
+	expectedConfig.NodeList.Set(expectedConfig.Hostname + "," + valueToSet)
```
Comment (liggitt) [inline pkg/cmd/server/command_test.go]: toLower hostname in case the detected hostname is mixed-case? also, doesn't this depend on alpha ordering?

Comment (deads2k) [inline pkg/cmd/server/command_test.go]: Everyone should be so lucky as to run tests on deads-dev-01...

File: pkg/cmd/server/command.go [hunk 3]
```diff
@@ -126,4 +129,16 @@ func (cfg *Config) Complete(args []string) {
 		// if we've explicitly called out an etcd server, don't start etcd in-process
 		cfg.StartEtcd = !cfg.EtcdAddr.Provided
 	}
+
+	// if this is an all-in-one start, be sure to add our hostname to the NodeList if it is not already present
+	isAllInOne := (len(args) == 0)
```
Comment (liggitt) [inline pkg/cmd/server/command.go]: logically, this can use `cfg.StartMaster && cfg.StartNode` as well... if we're both a master and a node, make sure we know about ourselves

**Comment by liggitt** [comment]
LGTM

**Comment by deads2k** [comment]
squashed [merge]

**Comment by deads2k** [comment]
failed on `TestRestrictedAccessForProjectAdmins` with listing projects.  Looks like the project authorization cache isn't being updated within two seconds on some of the jenkins machines.

**Comment by deads2k** [comment]
We need a better way to figure out when the project authorization cache is ready (or make it more responsive).  For now, #1190 should help.  re[merge]

**Comment by liggitt** [comment]
kicking stuck [merge] queue

**Comment by deads2k** [comment]
Didn't have the asset server fix.  re[merge]

@liggitt  let's never touch that file again...

**Comment by deads2k** [comment]
Something must be wrong with project listing (but not with policy or caching, the getters pass)
```
--- FAIL: TestRestrictedAccessForProjectAdmins (9.93 seconds)
	authorization_test.go:81: expected hammer-project, got []api.Project{}
	authorization_test.go:89: expected mallet-project, got []api.Project{}
FAIL
```

@derekwaynecarr I'm out on Monday, can you take a look?  Welcome back.

**Comment by brenton** [comment]
@deads2k, any chance this will make it in today?

**Comment by deads2k** [comment]
Talked @derekwaynecarr.  I'll disable the list test for now with a TODO to get this through the merge queue.

**Comment by deads2k** [comment]
re[merge]

**Comment by deads2k** [comment]
build integration test transient: [merge]
