### PR TITLE
DeploymentConfig stop fixes

### LINKED ISSUE #2721: Deployment config reaper does not appear to be deleting rcs
Seeing this from hack/test-cmd against master - deleting the DC should have removed many more of those RCs prior to creation.

```
buildConfigs/ruby-sample-build
buildConfigs/sinatra-app-example
buildConfigs/sinatra-example-1
buildConfigs/sinatra-example-2
builds/ruby-sample-build-1
builds/sinatra-app-example-1
builds/sinatra-example-1-1
imageStreams/sinatra-app-example
imageStreams/sinatra-example-1
imageStreams/sinatra-example-2
deploymentConfigs/database
deploymentConfigs/frontend
deploymentConfigs/sinatra-app-example-a
deploymentConfigs/sinatra-app-example-b
deploymentConfigs/sinatra-example-1
deploymentConfigs/sinatra-example-2
replicationcontrollers/database-2
replicationcontrollers/database-app-1
replicationcontrollers/database-rc-1
replicationcontrollers/frontend-1
replicationcontrollers/frontend-2
replicationcontrollers/frontend-app-1
```

### PR DESCRIPTION
**Pull request by ironcladlou**
This PR supercedes #2692. It adds a commit which deletes the DeploymentConfig prior to reaping its deployments prevent the kind of races outlined in #2721.

Closes #2721.

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by ironcladlou** [comment]
cc @abhgupta @smarterclayton @ncdc @kargakis

File: hack/test-cmd.sh [hunk 1]
```diff
@@ -464,8 +465,8 @@ osc process -f examples/sample-app/application-template-dockerbuild.json -l app=
 wait_for_command 'osc get rc/database-1' "${TIME_MIN}"
 osc get dc/database
 osc stop dc/database
-[ ! "$(osc get rc/database-1)" ]
 [ ! "$(osc get dc/database)" ]
+[ ! "$(osc get rc/database-1)" ]
```
Comment (smarterclayton) [inline hack/test-cmd.sh]: Undo this change

Comment (smarterclayton) [inline hack/test-cmd.sh]: In a follow on

**Comment by smarterclayton** [comment]
[merge]

File: pkg/deploy/reaper/reaper.go [hunk 2]
```diff
@@ -36,34 +35,24 @@ type DeploymentConfigReaper struct {
 // zero replicas, waits for all of them to get deleted and then deletes both the
 // replication controller and its deployment configuration.
 func (reaper *DeploymentConfigReaper) Stop(namespace, name string, gracePeriod *kapi.DeleteOptions) (string, error) {
-	dc, err := reaper.osc.DeploymentConfigs(namespace).Get(name)
-	if err != nil {
+	if err := reaper.osc.DeploymentConfigs(namespace).Delete(name); err != nil {
```
Comment (ironcladlou) [inline pkg/deploy/reaper/reaper.go]: This will need changed for reentrancy (the patch predates https://github.com/openshift/origin/issues/2721#issuecomment-108661712). Will fix in a followup to make it more robust. @kargakis, maybe you can pick that up if you get here first.

File: hack/test-cmd.sh (hunk 1 above)
Comment (ironcladlou) [inline hack/test-cmd.sh]: @kargakis or I can do this along with the forthcoming reentrancy patch.

**Comment by kargakis** [comment]
Nice, @ironcladlou

**Comment by ironcladlou** [comment]
cc @thoraxe @sdodson: this is a critical fix made in the past week that you guys might need to be aware of.
