### PR TITLE
new-app: Fix detectSource test

### LINKED ISSUE #2898: newapp_test doesn't check source detection correctly
The DeepEqual condition should error if `!reflect.DeepEqual`:
```
		for i, ref := range refs {
			if reflect.DeepEqual(ref, test.expectedRefs[i]) {
				t.Errorf("%s: Refs don't match. Expected %v, got %v", test.name, test.expectedRefs[i], ref)
			}
		}
```

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #2898 

@liggitt fyi

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

File: pkg/generate/app/cmd/newapp_test.go [hunk 1]
```diff
@@ -415,6 +415,7 @@ func TestDetectSource(t *testing.T) {
 	dockerResolver := app.DockerRegistryResolver{
 		Client: dockerregistry.NewClient(),
 	}
+	mocks := app.MockSourceRepositories()
```
Comment (liggitt) [inline pkg/generate/app/cmd/newapp_test.go]: this is just changing to use the same pointer for both expected and repository... in general, that's bad, because any mutation (even an invalid one) will still result in a match.

Comment (kargakis) [inline pkg/generate/app/cmd/newapp_test.go]: Yes, that mutation is needed here. In the process of detecting the source, `detectSource` [edits](https://github.com/openshift/origin/blob/719543c31713c49fc449553f5571f4c6d32631e4/pkg/generate/app/cmd/newapp.go#L347) (see [UsedBy](https://github.com/openshift/origin/blob/719543c31713c49fc449553f5571f4c6d32631e4/pkg/generate/app/sourcelookup.go#L57-L60)) the source repository and I need that edit to propagate to the mock repository. Unfortunately we cannot mock that since if the repo is [in use](https://github.com/openshift/origin/blob/719543c31713c49fc449553f5571f4c6d32631e4/pkg/generate/app/cmd/newapp.go#L279) in the first place, we wont get a source detection for it.

**Comment by kargakis** [comment]
@smarterclayton PTAL

**Comment by smarterclayton** [comment]
Approved LGTM [merge

**Comment by smarterclayton** [comment]
[merge]
