### PR TITLE
Fix deploy test conflict flake

### LINKED ISSUE #5612: Test flake: deploy_test_triggers can fail with deploymentConfig update conflicts
Observed in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/6614/console for #5530.

```
--- FAIL: TestTriggers_manual-2 (0.05s)
	deploy_trigger_test.go:304: Starting test openshift
	deploy_trigger_test.go:91: Couldn't create updated DeploymentConfig: deploymentConfig "config" cannot be updated: the object has been modified; please apply your changes to the latest version and try again &api.DeploymentConfig{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"config", GenerateName:"", Namespace:"integration", SelfLink:"/oapi/v1/namespaces/integration/generatedeploymentconfigs/config", UID:"4fe7be5f-81ac-11e5-854d-0e93450de951", ResourceVersion:"10754", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:63582098077, nsec:0, loc:(*time.Location)(0x467cda0)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil)}, Triggers:[]api.DeploymentTriggerPolicy{api.DeploymentTriggerPolicy{Type:"Manual", ImageChangeParams:(*api.DeploymentTriggerImageChangeParams)(nil)}}, Template:api.DeploymentTemplate{Strategy:api.DeploymentStrategy{Type:"Recreate", CustomParams:(*api.CustomDeploymentStrategyParams)(nil), RecreateParams:(*api.RecreateDeploymentStrategyParams)(nil), RollingParams:(*api.RollingDeploymentStrategyParams)(nil), Resources:api.ResourceRequirements{Limits:api.ResourceList{"cpu":resource.Quantity{Amount:10.000, Format:"DecimalSI"}, "memory":resource.Quantity{Amount:10000000000.000, Format:"DecimalSI"}}, Requests:api.ResourceList(nil)}}, ControllerTemplate:api.ReplicationControllerSpec{Replicas:1, Selector:map[string]string{"a":"b"}, Template:(*api.PodTemplateSpec)(0xc208a1d8c0)}}, LatestVersion:1, Details:(*api.DeploymentDetails)(0xc208aad2c0)}
```

Probably another fight with the deploymentConfig controller updating the  status message.

### PR DESCRIPTION
**Pull request by ironcladlou**
Retry update conflict errors during deploy trigger test.

Fixes #5612

### CODE REVIEW

**Comment by ironcladlou** [comment]
[test]

**Comment by deads2k** [comment]
lgtm. 

@smarterclayton or @liggitt for approval.

**Comment by kargakis** [comment]
LGTM

File: test/integration/deploy_trigger_test.go [hunk 1]
```diff
@@ -77,21 +81,29 @@ func TestTriggers_manual(t *testing.T) {
...
-	}
-	if config.LatestVersion != 1 {
-		t.Fatalf("Generated deployment should have version 1: %#v", config)
-	}
-	glog.Infof("config(1): %#v", config)
-
-	new, err := openshift.Client.DeploymentConfigs(testutil.Namespace()).Update(config)
-	if err != nil {
-		t.Fatalf("Couldn't create updated DeploymentConfig: %v %#v", err, config)
+	retryErr := wait.ExponentialBackoff(wait.Backoff{Steps: maxUpdateRetries}, func() (bool, error) {
```
Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: This is exactly the case where you should have used retry.OnConflict

File: test/integration/deploy_trigger_test.go [hunk 2]
```diff
@@ -243,28 +255,42 @@ func TestTriggers_configChange(t *testing.T) {
 
 	assertEnvVarEquals("ENV1", "VAL1", deployment, t)
 
-	// submit a new config with an updated environment variable
-	if config, err = openshift.Client.DeploymentConfigs(testutil.Namespace()).Generate(config.Name); err != nil {
-		t.Fatalf("Error generating config: %v", err)
-	}
+	retryErr := wait.ExponentialBackoff(wait.Backoff{Steps: maxUpdateRetries}, func() (bool, error) {
```
Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: This should be RetryOnConflict

File: test/integration/deploy_trigger_test.go (hunk 1 above)
Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Woopsie daisy

Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Switched to use RetryOnConflict

File: test/integration/deploy_trigger_test.go (hunk 2 above)
Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Switched to use RetryOnConflict

File: test/integration/deploy_trigger_test.go [hunk 3]
```diff
@@ -77,21 +80,25 @@ func TestTriggers_manual(t *testing.T) {
...
-		t.Fatalf("Couldn't create updated DeploymentConfig: %v %#v", err, config)
+	retryErr := kclient.RetryOnConflict(wait.Backoff{Steps: maxUpdateRetries}, func() error {
+		config, err = openshift.Client.DeploymentConfigs(testutil.Namespace()).Generate(config.Name)
+		if err != nil {
+			return err
+		}
+		if config.LatestVersion != 1 {
+			t.Fatalf("Generated deployment should have version 1: %#v", config)
+		}
+		glog.Infof("config(1): %#v", config)
```
Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: Shouldn't this be log.Printf?

File: test/integration/deploy_trigger_test.go [hunk 4]
```diff
@@ -243,28 +250,34 @@ func TestTriggers_configChange(t *testing.T) {
...
-	deployment.Annotations[deployapi.DeploymentStatusAnnotation] = string(deployapi.DeploymentStatusComplete)
-	// update the deployment
-	if _, err = openshift.KubeClient.ReplicationControllers(testutil.Namespace()).Update(deployment); err != nil {
-		t.Fatalf("Error updating existing deployment: %v", err)
-	}
+		// before we update the config, we need to update the state of the existing deployment
+		// this is required to be done manually since the deployment and deployer pod controllers are not run in this test
+		deployment.Annotations[deployapi.DeploymentStatusAnnotation] = string(deployapi.DeploymentStatusComplete)
+		// update the deployment
+		if _, err = openshift.KubeClient.ReplicationControllers(testutil.Namespace()).Update(deployment); err != nil {
```
Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: err :=

File: test/integration/deploy_trigger_test.go [hunk 5]
```diff
@@ -243,28 +250,34 @@ func TestTriggers_configChange(t *testing.T) {
 
 	assertEnvVarEquals("ENV1", "VAL1", deployment, t)
 
-	// submit a new config with an updated environment variable
-	if config, err = openshift.Client.DeploymentConfigs(testutil.Namespace()).Generate(config.Name); err != nil {
-		t.Fatalf("Error generating config: %v", err)
-	}
+	retryErr := kclient.RetryOnConflict(wait.Backoff{Steps: maxUpdateRetries}, func() error {
+		// submit a new config with an updated environment variable
+		if config, err = openshift.Client.DeploymentConfigs(testutil.Namespace()).Generate(config.Name); err != nil {
```
Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: err :=

Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: This is deliberately assigning to the outer scope

Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Oops, nevermind, it doesn't need to

Comment (smarterclayton) [inline test/integration/deploy_trigger_test.go]: :)

**Comment by ironcladlou** [comment]
@smarterclayton cleaned up variables/scopes.

File: test/integration/deploy_trigger_test.go (hunk 3 above)
Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Yeah, converted those and removed glog dependency

**Comment by smarterclayton** [comment]
I'd add you to the merge queue... but I don't think it will make a difference.
