### PR TITLE
Fix #4206

### LINKED ISSUE #4206: `oc new-app` error message when template has invalid JSON
Trying to use `oc new-app` with an existing template (file exists and can be read) that contains invalid JSON (parsing fails) returns an error message that doesn't help figuring out you have a problem in your template:

```
$ cat > bad-template.json <<EOF                                                         
{
"there should not be a trailing comma": "here",
}
EOF
$ oc new-app bad-template.json
error: no image or template matched "bad-template.json"
```

This pops up some times when editing an existing template and make small mistakes.

### PR DESCRIPTION
**Pull request by jprukner**
Fixes #4206 the way it shows correct error message if passed json template is invalid.
@rhcarvalho @mfojtik PTAL

### CODE REVIEW

**Comment by rhcarvalho** [comment]
[test]

File: pkg/generate/app/componentresolvers.go [hunk 1]
```diff
@@ -41,6 +41,12 @@ func (r PerfectMatchWeightedResolver) Resolve(value string) (*ComponentMatch, er
 	imperfect := ScoredComponentMatches{}
 	group := []WeightedResolver{}
 	for i, resolver := range r {
+		if isFile(value){
+			_, err := resolver.Searcher.Search(value)
```
Comment (mfojtik) [inline pkg/generate/app/componentresolvers.go]: if _, err := resolver.Searcher.Search(value); err != nil {
  return nil, err
}

(since you're not using the error anywhere below).

**Comment by mfojtik** [comment]
LGTM [test]

**Comment by rhcarvalho** [comment]
@mfojtik I'll take a closer look if this doesn't break anything. Do we have tests covering all new-app usages?

File: pkg/generate/app/componentresolvers.go [hunk 2]
```diff
@@ -75,6 +75,15 @@ func (r PerfectMatchWeightedResolver) Resolve(value string) (*ComponentMatch, er
 	}
 	switch len(imperfect) {
 	case 0:
+		if isFile(value) {
```
Comment (rhcarvalho) [inline pkg/generate/app/componentresolvers.go]: This file looks quite complex to understand, @jprukner could you add a comment here explaining why we do this check?

```go
case 0:
    // If value is a file and there is a TemplateFileSearcher in one of the resolvers
    // and trying to use it gives an error, use this error instead of ErrNoMatch.
    // E.g., calling `oc new-app template.json` where template.json is a file
    // with invalid JSON, it's better to return the JSON syntax error than a more
    // generic message.
    if isFile(value) {
```

**Comment by rhcarvalho** [comment]
@fabianofranz you might be the one who understands better how this should behave, could you PTAL?

**Comment by rhcarvalho** [comment]
[test] again

File: pkg/generate/app/componentresolvers.go (hunk 2 above)
Comment (jprukner) [inline pkg/generate/app/componentresolvers.go]: Ok, I'll add that. @rhcarvalho

**Comment by fabianofranz** [comment]
LGTM

**Comment by mfojtik** [comment]
[merge]

File: pkg/generate/app/componentresolvers.go [hunk 3]
```diff
@@ -75,6 +75,20 @@ func (r PerfectMatchWeightedResolver) Resolve(value string) (*ComponentMatch, er
 	}
 	switch len(imperfect) {
 	case 0:
+		// If value is a file and there is a TemplateFileSearcher in one of the resolvers
+		// and trying to use it gives an error, use this error instead of ErrNoMatch.
+		// E.g., calling `oc new-app template.json` where template.json is a file
+		// with invalid JSON, it's better to return the JSON syntax error than a more
+		// generic message.
+		if isFile(value) {
```
Comment (smarterclayton) [inline pkg/generate/app/componentresolvers.go]: This is leaking an abstraction - why doesn't template file searcher properly handle this and return an appropriate error?

Comment (smarterclayton) [inline pkg/generate/app/componentresolvers.go]: Nothing in this code should know anything about specific searchers or resolvers.

Comment (rhcarvalho) [inline pkg/generate/app/componentresolvers.go]: > why doesn't template file searcher properly handle this and return an appropriate error?

@smarterclayton `TemplateFileSearcher` does handle that and return an appropriate error. The problem is that we [ignore all specific errors from resolvers](https://github.com/openshift/origin/blob/76a51df142c5299da4e4aee1272b87b67b1c429b/pkg/generate/app/componentresolvers.go#L71-L73) and return a generic `ErrNoMatch` that eventually became a poor error message as described in #4206.

The way it works today is that if you have a file `template.json` with invalid data, running:
```
$ oc new-app template.json
```

will still succeed if e.g., there's a template named "template.json" stored in the server, or there's a Docker image named "template.json"... but when none of those things work, we were losing the relevant JSON SyntaxError...

How do you think we could do this better?

Comment (smarterclayton) [inline pkg/generate/app/componentresolvers.go]: Come up with a new error type that resolves can guarantee users will get
(or a side error that will result in it being shown).

On Thu, Sep 17, 2015 at 10:58 AM, Rodolfo Carvalho <notifications@github.com
> wrote:

> In pkg/generate/app/componentresolvers.go
> <https://github.com/openshift/origin/pull/4660#discussion_r39755444>:
>
> > @@ -75,6 +75,20 @@ func (r PerfectMatchWeightedResolver) Resolve(value string) (*ComponentMatch, er
> >  	}
> >  	switch len(imperfect) {
> >  	case 0:
> > +		// If value is a file and there is a TemplateFileSearcher in one of the resolvers
> > +		// and trying to use it gives an error, use this error instead of ErrNoMatch.
> > +		// E.g., calling `oc new-app template.json` where template.json is a file
> > +		// with invalid JSON, it's better to return the JSON syntax error than a more
> > +		// generic message.
> > +		if isFile(value) {
>
> why doesn't template file searcher properly handle this and return an
> appropriate error?
>
> @smarterclayton <https://github.com/smarterclayton> TemplateFileSearcher
> does handle that and return an appropriate error. The problem is that we ignore
> all specific errors from resolvers
> <https://github.com/openshift/origin/blob/76a51df142c5299da4e4aee1272b87b67b1c429b/pkg/generate/app/componentresolvers.go#L71-L73>
> and return a generic ErrNoMatch that eventually became a poor error
> message as described in #4206
> <https://github.com/openshift/origin/issues/4206>.
>
> The way it works today is that if you have a file template.json with
> invalid data, running:
>
> $ oc new-app template.json
>
> will still succeed if e.g., there's a template named "template.json"
> stored in the server, or there's a Docker image named "template.json"...
> but when none of those things work, we were losing the relevant JSON
> SyntaxError...
>
> How do you think we could do this better?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4660/files#r39755444>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

Comment (smarterclayton) [inline pkg/generate/app/componentresolvers.go]: That resolvers can guarantee the users will get, or return a set of errors
on the side that will be displayed (i think the former is probably cleaner)

On Thu, Sep 17, 2015 at 5:12 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> Come up with a new error type that resolves can guarantee users will get
> (or a side error that will result in it being shown).
>
> On Thu, Sep 17, 2015 at 10:58 AM, Rodolfo Carvalho <
> notifications@github.com> wrote:
>
>> In pkg/generate/app/componentresolvers.go
>> <https://github.com/openshift/origin/pull/4660#discussion_r39755444>:
>>
>> > @@ -75,6 +75,20 @@ func (r PerfectMatchWeightedResolver) Resolve(value string) (*ComponentMatch, er
>> >  	}
>> >  	switch len(imperfect) {
>> >  	case 0:
>> > +		// If value is a file and there is a TemplateFileSearcher in one of the resolvers
>> > +		// and trying to use it gives an error, use this error instead of ErrNoMatch.
>> > +		// E.g., calling `oc new-app template.json` where template.json is a file
>> > +		// with invalid JSON, it's better to return the JSON syntax error than a more
>> > +		// generic message.
>> > +		if isFile(value) {
>>
>> why doesn't template file searcher properly handle this and return an
>> appropriate error?
>>
>> @smarterclayton <https://github.com/smarterclayton> TemplateFileSearcher
>> does handle that and return an appropriate error. The problem is that we ignore
>> all specific errors from resolvers
>> <https://github.com/openshift/origin/blob/76a51df142c5299da4e4aee1272b87b67b1c429b/pkg/generate/app/componentresolvers.go#L71-L73>
>> and return a generic ErrNoMatch that eventually became a poor error
>> message as described in #4206
>> <https://github.com/openshift/origin/issues/4206>.
>>
>> The way it works today is that if you have a file template.json with
>> invalid data, running:
>>
>> $ oc new-app template.json
>>
>> will still succeed if e.g., there's a template named "template.json"
>> stored in the server, or there's a Docker image named "template.json"...
>> but when none of those things work, we were losing the relevant JSON
>> SyntaxError...
>>
>> How do you think we could do this better?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openshift/origin/pull/4660/files#r39755444>.
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

Comment (rhcarvalho) [inline pkg/generate/app/componentresolvers.go]: Follow up: #4743
