### PR TITLE
Fixing oc rsync command fails if oc command has space in path

### LINKED ISSUE #15187: oc rsync fails if 'oc' command has space in it's path
[provide a description of the issue]

##### Version
[provide output of the `openshift version` or `oc version` command]
oc 3.3.1.5  and  oc 3.5.5.5

##### Steps To Reproduce
1. [step 1]  copy 'oc' command to a folder with spaces in it
2. [step 2]  use full path to call that oc command, and call oc rsync. ex:

home/rob/tmp/with\ spaces/oc rsync --token=xxx  --server=https://192.168.99.100:8443  --insecure-skip-tls-verify=true  --exclude='.git'  eap-app-1-qpldm:/opt/eap/standalone/deployments/  -n  myproj  /home/rob/apps/eclipse/workspaces/runtime-New_configuration/.metadata/.plugins/org.jboss.ide.eclipse.as.core/myproj@eap-app/deploy/

##### Current Result
rsync: Failed to exec /home/rob/tmp/with: No such file or directory (2)
rsync error: error in IPC code (code 14) at pipe.c(85) [Receiver=3.1.2]
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in IPC code (code 14) at io.c(226) [Receiver=3.1.2]
error: exit status 14

##### Expected Result

The rsync occurs as expected

##### Additional Information
Hardy thinks the problem may be here: 
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/rsync/copyrsync.go#L37

The oc command calls rsync and passes in the "OpenShift CLI rsh command as the remote shell command for rsync".  This is obviously failing hard because of the spaces. rsync thinks only the first part of the 'oc' command's path (pre space) is the command to call. 

This code may need to ensure that the 'oc' command's spaces are properly escaped. 

The issue may be in SiblingCommand:   https://github.com/openshift/origin/blob/85eb37b34f0657631592356d020cef5a58470f8e/pkg/cmd/util/sibling.go#L12

Either way, when passing the 'oc' command into rsync, it is not accounting for spaces.

### PR DESCRIPTION
**Pull request by coreydaley**
oc sibling commands (example rsync) fail if there is a space
in the path to the oc command

escapes spaces in the command path

Fixes #15187

### CODE REVIEW

**Comment by coreydaley** [comment]
[test]

**Comment by coreydaley** [comment]
@openshift/devex ptal

**Comment by bparees** [comment]
reproduced the failure and confirmed the fix?

**Comment by coreydaley** [comment]
@bparees yes

**Comment by gabemontero** [comment]
Has having an automated test case been considered / if so, what was the outcome?

Seems like some form of test-cmd.sh type test (perhaps a new .sh file in test/cmd) could be constructed.

**Comment by bparees** [comment]
I pointed @coreydaley to the existing extended test for oc rsync, but i'm willing to roll the dice on not having a test for this scenario if it's been manually tested.

**Comment by coreydaley** [comment]
@gabemontero @bparees I am open to appending a test to test/extended/cli/rsync.go if you guys feel it is needed.

**Comment by gabemontero** [comment]
if the new test is not onerous I say let's do it now ... but i am willing to defer to the previous point from @bparees

**Comment by bparees** [comment]
> but i am willing to defer to the previous point from @bparees

i'm not gonna argue against doing the right thing :)

**Comment by coreydaley** [comment]
@bparees well just guilt me into it why don't you ...

**Comment by coreydaley** [comment]
@jim-minter ptal
Is this closer to what you are recommending?  I will include tests in another push once I verify that I am on the correct path.

File: pkg/bootstrap/docker/up.go [hunk 1]
```diff
@@ -629,7 +629,7 @@ func (c *CommonStartConfig) CheckExistingOpenShiftContainer(out io.Writer) error
 		return errors.NewError("unexpected error while checking OpenShift container state").WithCause(err)
 	}
 	if running {
-		return errors.NewError("OpenShift is already running").WithSolution("To start OpenShift again, stop the current cluster:\n$ %s\n", cmdutil.SiblingCommand(c.command, "down"))
+		return errors.NewError("OpenShift is already running").WithSolution("To start OpenShift again, stop the current cluster:\n$ %s\n", strings.Join(cmdutil.EscapeCommand(cmdutil.SiblingCommand(c.command, "down")), " "))
```
Comment (jim-minter) [inline pkg/bootstrap/docker/up.go]: No EscapeCommand here

File: pkg/cmd/cli/cmd/rsync/copyrsync.go [hunk 2]
```diff
@@ -34,16 +34,15 @@ var rshExcludeFlags = sets.NewString("delete", "strategy", "quiet", "include", "
 
 func newRsyncStrategy(f *clientcmd.Factory, c *cobra.Command, o *RsyncOptions) (copyStrategy, error) {
 	// Determine the rsh command to pass to the local rsync command
-	rsh := cmdutil.SiblingCommand(c, "rsh")
-	rshCmd := []string{rsh}
+	rshCmd := cmdutil.SiblingCommand(c, "rsh")
```
Comment (jim-minter) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: `rshCmd := []string{strings.Join(cmdutil.SiblingCommand(c, "rsh"), " ")}`

File: pkg/cmd/cli/cmd/rsync/copyrsync.go [hunk 3]
```diff
@@ -34,16 +34,15 @@ var rshExcludeFlags = sets.NewString("delete", "strategy", "quiet", "include", "
...
 	// Append all original flags to rsh command
 	c.Flags().Visit(func(flag *pflag.Flag) {
 		if rshExcludeFlags.Has(flag.Name) {
 			return
 		}
 		rshCmd = append(rshCmd, fmt.Sprintf("--%s=%s", flag.Name, flag.Value.String()))
 	})
-	rshCmdStr := strings.Join(rshCmd, " ")
+	rshCmdStr := strings.Join(cmdutil.EscapeCommand(rshCmd), " ")
```
Comment (jim-minter) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: the EscapeCommand needs to go in the rshCmd = append ... line above

File: pkg/cmd/util/sibling.go [hunk 4]
```diff
@@ -26,5 +34,21 @@ func SiblingCommand(cmd *cobra.Command, name string) string {
...
 
-	return strings.Join(command, " ")
+	return command
+}
+
+// EscapeCommand wraps each element of the command in double quotes
+// if it contains any of the following: single quote, double quote, backslash, or space
+// It also replaces every pre-existing quoting character in the element with a pair.
+// Examples: ' -> '', " -> ""
+func EscapeCommand(command []string) []string {
```
Comment (jim-minter) [inline pkg/cmd/util/sibling.go]: This escaping style is pretty rsync-specific so should the function should be named accordingly and be put in the appropriate rsync-related package

File: pkg/cmd/util/sibling.go [hunk 5]
```diff
@@ -26,5 +34,21 @@ func SiblingCommand(cmd *cobra.Command, name string) string {
...
+	for key := range command {
+		needsQuoted := MatchEscapeCharacters.MatchString(command[key])
```
Comment (jim-minter) [inline pkg/cmd/util/sibling.go]: - use strings.ContainsAny and strings.Replace, not regexes
- you've chosen to quote using " so replacement ' -> '' must not be done (but you still need to quote if the string contains a ')
- guard replace " -> "" with needsQuoted
- command[key] = \`"\` + command[key] + \`"\` saves the fmt.Sprintf and raw quotes are clearer here

File: pkg/bootstrap/docker/up.go (hunk 1 above)
Comment (coreydaley) [inline pkg/bootstrap/docker/up.go]: Fixed in next push

File: pkg/cmd/cli/cmd/rsync/copyrsync.go (hunk 3 above)
Comment (coreydaley) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: EscapeCommand takes a []string, iterates over all of the elements quoting them if needed, and then returns a []string that then needs to be joined.  Why should it go in the rshCmd = append ... instead of below it?

File: pkg/cmd/util/sibling.go (hunk 5 above)
Comment (coreydaley) [inline pkg/cmd/util/sibling.go]: updated in next push

File: pkg/cmd/cli/cmd/rsync/copyrsync.go (hunk 3 above)
Comment (jim-minter) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: brainfade on my part.  I think you'll still want `rshCmd := []string{strings.Join(cmdutil.SiblingCommand(c, "rsh"), " ")}` above though.

File: pkg/cmd/cli/cmd/rsync/copyrsync.go (hunk 2 above)
Comment (coreydaley) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: SiblingCommand returns a []string that can be iterated over when passed to escapeRsyncCommand.  Am I just missing something here?

**Comment by coreydaley** [comment]
@bparees @jim-minter ptal

File: pkg/cmd/cli/cmd/rsync/copyrsync.go [hunk 6]
```diff
@@ -111,6 +110,21 @@ func (r *rsyncStrategy) Validate() error {
 	return nil
 }
 
+// escapeRsyncCommand wraps each element of the command in double quotes
+// if it contains any of the following: single quote, double quote, backslash, or space
+// It also replaces every pre-existing quoting character in the element with a pair.
+// Example: " -> ""
+func escapeRsyncCommand(command []string) []string {
```
Comment (csrwng) [inline pkg/cmd/cli/cmd/rsync/copyrsync.go]: This is a good candidate for a unit test :)

File: pkg/oc/cli/cmd/rsync/copyrsync.go [hunk 7]
```diff
@@ -111,6 +110,21 @@ func (r *rsyncStrategy) Validate() error {
 	return nil
 }
 
+// escapeRsyncCommand wraps each element of the command in double quotes
+// if it contains any of the following: single quote, double quote, backslash, or space
+// It also replaces every pre-existing quoting character in the element with a pair.
+// Example: " -> ""
```
Comment (Miciah) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: Now it only replaces double-quotes, not other quoting characters, so this comment is misleading.

Is this rsync feature well known? It might be worth adding an explanation (e.g., "When it adds double quotes, it also doubles every pre-existing double-quote; rsync interprets a doubled double-quote within a double-quoted string as a single double-quote."), or possibly changing the name to `rsyncEscapeCommand` to emphasize that this function performs rsync-style escaping (as opposed to shell-style escaping of an rsync command).

Comment (coreydaley) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: Updated in next push, thanks for the feedback.

**Comment by coreydaley** [comment]
@bparees updated and all tests are green

File: pkg/oc/cli/cmd/rsync/copyrsync.go [hunk 8]
```diff
@@ -111,6 +110,21 @@ func (r *rsyncStrategy) Validate() error {
 	return nil
 }
 
+// rsyncEscapeCsommand wraps each element of the command in double quotes
```
Comment (bparees) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: s/Csommand/Command/

File: pkg/oc/cli/cmd/rsync/copyrsync.go [hunk 9]
```diff
@@ -111,6 +110,21 @@ func (r *rsyncStrategy) Validate() error {
...
+// if it contains any of the following: single quote, double quote, backslash, or space
+// It also replaces every pre-existing double quote character in the element with a pair.
+// Example: " -> ""
+func rsyncEscapeCommand(command []string) []string {
+	for key := range command {
+		needsQuoted := strings.ContainsAny(command[key], `'" \`)
+		if needsQuoted {
+			command[key] = strings.Replace(command[key], `"`, `""`, -1)
```
Comment (bparees) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: I may need to brush up on my escaping, how does replacing a " with a "" help?  wouldn't we want to replace a " with a \" ?

Comment (bparees) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: and for that matter why not just escape all the characters with backslashes, or is that not windows friendly?

Comment (Miciah) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: > I may need to brush up on my escaping, how does replacing a " with a "" help? wouldn't we want to replace a " with a \\" ?

I was confused too when I saw it.  It's an rsync thing.  From the rsync manpage,

> Note that doubling a single-quote inside a single-quoted string gives you a single-quote; likewise  for double-quotes (though you need to pay attention to which quotes your shell is parsing and which quotes rsync is parsing).

This is why in an earlier comment I suggested changing the name (to emphasize that this is rsync escaping, not shell escaping) and adding a comment to explain the rsync-style escaping.

Comment (bparees) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: ok but this is escaping all the parts of the command invocation, right?  e.g.:

["/usr/bin/oc","rsync","podname","/foo/bar"]

so they shouldn't all be escaped that way, just the parts that are the path arguments to rsync, right?

File: pkg/oc/cli/cmd/rsync/copyrsync.go (hunk 8 above)
Comment (coreydaley) [inline pkg/oc/cli/cmd/rsync/copyrsync.go]: fixed in next push

**Comment by coreydaley** [comment]
@bparees @jim-minter @csrwng ptal

@jim-minter 
Had a quick discussion with @bparees earlier and we decided that it IS our responsibility to not generate a bad command path, but it IS NOT our responsibility for the args that are provided to rsync, and that they should be escaping those arguments themselves.  I think this is actually the PR that I had put together the first time before things got a bit out of hand.

**Comment by bparees** [comment]
@coreydaley and I discussed this on IRC.  We don't have a responsibility to manage the args being passed to rsync, the users can/should escape those paths if necessary.  What we broke, and need to fix, is when we are generating the path to the oc binary and we aren't properly escaping it.

/lgtm
/approve

**Comment by jim-minter** [comment]
I don't 100% agree.  This function is constructing an argument to rsync (-e) from non-rsync options, therefore it is responsible for escaping and it might as well do it correctly.  In practice the only inputs at the moment are $0 (may have space, unlikely to have quotes but not impossible) and the container name (has this been validated at this point to prove that there are no quotes and that therefore no breakout is possible?).

I think SiblingCommand is not the place to do any escaping - it should return a []string and the caller should handle it.  I think that the proper rsync escaping might as well be used to construct the -e argument, then we never have to revisit this ever again.

**Comment by bparees** [comment]
> I don't 100% agree. This function is constructing an argument to rsync (-e) from non-rsync options, therefore it is responsible for escaping and it might as well do it correctly. In practice the only inputs at the moment are $0 (may have space, unlikely to have quotes but not impossible) and the container 

I think that is a separate concerns and should be treated separately(hey, you advocated for smaller PRs! :) ).  Especially considering that the escaping mechanism used for rsync args is not the same as the escaping mechanism used for the sibling command path elements(ie how double quotes are handled).  We can certainly have the debate as to how/if "oc rsync" should massage its arguments, but I don't think this PR/issue is the place for it.  This is about ensuring that when we invoke a secondary oc command on behalf of the user, we get the path to the oc binary correct/valid.

> name (has this been validated at this point to prove that there are no quotes and that therefore no breakout is possible?).

I don't know, but breakout of what exactly?  Pretty sure rsync doesn't use any elevated privileges, if you can rsync, you can rsh into the pod and do what you like.

> I think SiblingCommand is not the place to do any escaping - it should return a []string and the caller should handle it. I think that the proper rsync escaping might as well be used to construct the -e argument, then we never have to revisit this ever again.

The intended use of SiblingCommand (to construct a value path to invoke a secondary command that is a peer of the current command) is pretty clear (at least to me, if there are other uses that I'm not seeing where someone would want the raw value, we can discuss), I don't think it's unreasonable to just return a usable path instead of a potentially unusable one rather than forcing the caller to sort if out.

**Comment by jim-minter** [comment]
> Especially considering that the escaping mechanism used for rsync args is not the same as the escaping mechanism used for the sibling command path elements(ie how double quotes are handled). 

Here, it needs to be.

>  I don't think it's unreasonable to just return a usable path instead of a potentially unusable one rather than forcing the caller to sort if out.

The usable path is one that is a []string, where [0] and [1:] can be sent as arguments to exec.Command, not the one which is pre-munged and needs to be decoded.

**Comment by bparees** [comment]
> Here, it needs to be.

Why?

The reason this issue exists is because we are generating a path ourselves internally and we are not properly escaping that path.  It is independent of how we handle or manage the user provided arguments.  (Which, again, the user can escape or quote as need be)

Again, i'm happy to continue the discussion of what help, if any, we should provide to a user who's passing a source/destination path that contains spaces, to oc rsync, but it's independent of "how do we figure out the right(and properly escaped) path to the oc binary so we can invoke it in a subsequent operation"


> The usable path is one that is a []string, where [0] and [1:] can be sent as arguments to exec.Command, not the one which is pre-munged and needs to be decoded.

I don't see any decoding being done by the users of SiblingCommand(of which I only see two, this one, and oc cluster up which really does just want a string to print out).  This takes the result of SiblingCommand and passes it to exec with additional arguments.  Perhaps it *should* be passing it as an array of strings instead of a single string (plus more args), but the exec mechanism appears to be content with it as is.  Presumably because Exec itself is splitting on spaces (which is what would have caused this problem in the first place).
