### PR TITLE
Make DNS conformant with upstream

### LINKED ISSUE #8556: Integrated sky dns can't resolve service short hostname in pod
[Description]
Integrated sky dns can't resolve service short hostname in pod

##### Version
Openshift 1.1.6

##### Steps To Reproduce
1.  oc get service
2.  oc rsh pod-name
3. ping service-name (short hostname), can't resolve 
4. ping service-name.project-name.svc.cluster.local, resolve correct ipaddress  

##### Current Result
can't resolve with service short hostname 
##### Expected Result
resolve success 
##### Additional Information
/etc/resolve.conf in pod have correct config, search domain have project-name.svc.cluster.local svc.cluster.local

Anyone have idea on this, thanks

### PR DESCRIPTION
**Pull request by smarterclayton**
Our DNS implementation was not returning an etcd-alike error to indicate to SkyDNS that the name was not found (and prompt NXDOMAIN error status). This changes the error we return, enables the upstream DNS tests, and adds our own e2e test for wildcarding and endpoints within the pod. This will supercede our integration test (which may not be necessary anymore).

[test]

Fixes #8556

### CODE REVIEW

**Comment by smarterclayton** [comment]
Not technically a regression, probably too high risk to land for 1.2 at this very late date.  However, the fact that we are now conformant with upstream is important...

**Comment by smarterclayton** [comment]
Wheee more flakes

```
FAILURE after 0.221s: test/cmd/builds.sh:72: executing 'oc new-build -D $'FROM centos:7' --no-output' expecting success: the command returned the wrong error code
There was no output from the command.
Standard error from the command:
error: only a partial match was found for "centos:7": "docker.io/centos:centos7"

The argument "centos:7" only partially matched the following Docker image, OpenShift image stream, or template:

* Docker image "docker.io/centos:centos7", 28e524a, from local, author The CentOS Project <cloud-ops@centos.org>
  Use --docker-image="docker.io/centos:centos7" to specify this image or template
```

**Comment by smarterclayton** [comment]
@bparees have you seen the above flake?

**Comment by bparees** [comment]
@smarterclayton no but i've been seeing a ton of similar flakes w/ new-app lately not finding things in dockerhub (which i attribute to the fact that we're going through the openshift registry for all our queries now, but i could be wrong)

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@liggitt review when you have a chance

File: pkg/cmd/server/api/v1/conversions.go [hunk 1]
```diff
@@ -308,6 +312,21 @@ func addConversionFuncs(scheme *runtime.Scheme) {
 			return nil
 		},
 		api.Convert_resource_Quantity_To_resource_Quantity,
+		// TODO: https://github.com/kubernetes/kubernetes/issues/24381
+		func(in *bool, out **bool, s conversion.Scope) error {
```
Comment (liggitt) [inline pkg/cmd/server/api/v1/conversions.go]: My head hurts now

Comment (smarterclayton) [inline pkg/cmd/server/api/v1/conversions.go]: Just imagine how much fun it was to debug that.

File: pkg/cmd/server/api/v1/conversions.go [hunk 2]
```diff
@@ -308,6 +312,21 @@ func addConversionFuncs(scheme *runtime.Scheme) {
...
+			b := *in
+			*out = &b
+			return nil
+		},
+		func(in **bool, out *bool, s conversion.Scope) error {
+			if *in == nil {
```
Comment (liggitt) [inline pkg/cmd/server/api/v1/conversions.go]: Does this assume it knows whether nil is supposed to default to true or false?

Comment (smarterclayton) [inline pkg/cmd/server/api/v1/conversions.go]: That would be in defaulting - which would run before this function is called.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
gentle review nag

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
New flake in debug (timing):

FAILURE after 0.691s: test/cmd/debug.sh:24: executing 'oc debug
dc/test-deployment-config -o yaml' expecting success and text '\-
/bin/sh': the command returned the wrong error code; the output
content test failedThere was no output from the command.
Standard error from the command:
error: cannot debug test-deployment-config: replicationcontrollers
"test-deployment-config-0" not found


[test]

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
Only slightly less gentle review nag

File: pkg/cmd/server/api/v1/conversions.go [hunk 3]
```diff
@@ -131,6 +131,10 @@ func addDefaultingFuncs(scheme *runtime.Scheme) {
 			if len(obj.BindNetwork) == 0 {
 				obj.BindNetwork = "tcp4"
 			}
+			if obj.AllowRecursiveQueries == nil {
```
Comment (liggitt) [inline pkg/cmd/server/api/v1/conversions.go]: this flips the default when the field is unspecified... we can't do that, can we?

Comment (smarterclayton) [inline pkg/cmd/server/api/v1/conversions.go]: Now that ansible sets up DNSmasq, we can - @sdodson you were planning (or already have) made that the default?

File: pkg/dns/serviceresolver.go [hunk 4]
```diff
@@ -115,13 +119,14 @@ func (b *ServiceResolver) Records(dnsName string, exact bool) ([]msg.Service, er
 				if fallback, ok := b.fallback(prefix, exact); ok {
 					return b.Records(fallback+b.base, exact)
 				}
+				return nil, errNoSuchName
 			}
-			return nil, err
+			return nil, errNoSuchName
```
Comment (liggitt) [inline pkg/dns/serviceresolver.go]: should this only be returned if the err is an IsNotFound?

File: pkg/dns/serviceresolver.go [hunk 5]
```diff
@@ -115,13 +119,14 @@ func (b *ServiceResolver) Records(dnsName string, exact bool) ([]msg.Service, er
...
 		}
 
 		// no portalIP and not headless, no DNS
 		if len(svc.Spec.ClusterIP) == 0 {
-			return nil, nil
+			return nil, errNoSuchName
```
Comment (liggitt) [inline pkg/dns/serviceresolver.go]: in cases where we recognize the service, but don't want to return records, will returning `errNoSuchName` trigger a recursive lookup we don't want? seems like we'd actually want to stop in this case and return no records

File: pkg/dns/serviceresolver.go [hunk 6]
```diff
@@ -188,7 +193,7 @@ func (b *ServiceResolver) Records(dnsName string, exact bool) ([]msg.Service, er
 		// return endpoints
 		endpoints, err := b.endpoints.Endpoints(namespace).Get(name)
 		if err != nil {
-			return nil, err
+			return nil, errNoSuchName
```
Comment (liggitt) [inline pkg/dns/serviceresolver.go]: same question here, should errors other than an IsNotFound error trigger an errNoSuchName?

File: pkg/dns/serviceresolver.go [hunk 7]
```diff
@@ -239,7 +244,7 @@ func (b *ServiceResolver) Records(dnsName string, exact bool) ([]msg.Service, er
 		glog.V(4).Infof("Answered %s:%t with %#v", dnsName, exact, services)
 		return services, nil
 	}
-	return nil, nil
+	return nil, errNoSuchName
```
Comment (liggitt) [inline pkg/dns/serviceresolver.go]: same question here, this is a recognized service with no endpoints, right? will returning errNoSuchName trigger a recursive lookup we don't want?

File: pkg/dns/serviceresolver.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/dns/serviceresolver.go]: It's been long enough that I've forgotten.  I don't remember whether SRVFAIL is the right behavior.

File: pkg/dns/serviceresolver.go (hunk 7 above)
Comment (smarterclayton) [inline pkg/dns/serviceresolver.go]: I think that in order to get conformant behavior with upstream, we have to do this.  They materialize to etcd, so the answers to all your questions is the same (if they can't get the data, they write nothing to etcd).  So the failure modes being different than Kube would in theory be not conformant.

File: pkg/cmd/server/api/v1/conversions.go (hunk 3 above)
Comment (sdodson) [inline pkg/cmd/server/api/v1/conversions.go]: It's on by default for 1.2/3.2 installs when NetworkManager is available. Apparently Centos cloud images don't include NM by default so we have that gap. I'll be working on closing that next week.

Comment (sdodson) [inline pkg/cmd/server/api/v1/conversions.go]: Wait, so our default will soon be to allow recursive lookups unless the config files override this?

Comment (smarterclayton) [inline pkg/cmd/server/api/v1/conversions.go]: Yes.  Admin will have to open the port if they want to make it open
for others, masters will default to 8053.

Comment (sdodson) [inline pkg/cmd/server/api/v1/conversions.go]: So, this only goes in after nodes run dns on their own so they no longer need to connect to master's skydns? Trying to understand why we didn't simply enable recursive lookups long ago like upstream does.

Comment (smarterclayton) [inline pkg/cmd/server/api/v1/conversions.go]: In origin it doesn't bother me that much - someone can always turn off
recursive, but for now, being compatible and tested the same was as
upstream concerns me a great deal more.

File: pkg/cmd/server/start/master_args.go [hunk 8]
```diff
@@ -209,6 +209,8 @@ func (args MasterArgs) BuildSerializeableMasterConfig() (*configapi.MasterConfig
 		DNSConfig: &configapi.DNSConfig{
 			BindAddress: dnsServingInfo.BindAddress,
 			BindNetwork: dnsServingInfo.BindNetwork,
+
+			AllowRecursiveQueries: true,
```
Comment (liggitt) [inline pkg/cmd/server/start/master_args.go]: I'm fine making the default true for new configs and all-in-one startups, but leave the old behavior intact at https://github.com/openshift/origin/pull/8474/files/38a403227faaab4ab9de73ecef63d4ce9846dbb6#diff-d59c94963a713e75e3b30c98b1dc40f2R134 (unspecified in config means false)

**Comment by smarterclayton** [comment]
@liggitt any other comments?

**Comment by liggitt** [comment]
No other comments, LGTM

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge] again w/ pulp down

**Comment by smarterclayton** [comment]
[merge] - disabled pulp test

File: pkg/cmd/server/start/master_args.go [hunk 9]
```diff
@@ -101,7 +101,7 @@ func NewDefaultMasterArgs() *MasterArgs {
 		MasterAddr:       flagtypes.Addr{Value: "localhost:8443", DefaultScheme: "https", DefaultPort: 8443, AllowPrefix: true}.Default(),
 		EtcdAddr:         flagtypes.Addr{Value: "0.0.0.0:4001", DefaultScheme: "https", DefaultPort: 4001}.Default(),
 		MasterPublicAddr: flagtypes.Addr{Value: "localhost:8443", DefaultScheme: "https", DefaultPort: 8443, AllowPrefix: true}.Default(),
-		DNSBindAddr:      flagtypes.Addr{Value: "0.0.0.0:53", DefaultScheme: "tcp", DefaultPort: 53, AllowPrefix: true}.Default(),
+		DNSBindAddr:      flagtypes.Addr{Value: "0.0.0.0:8053", DefaultScheme: "tcp", DefaultPort: 8053, AllowPrefix: true}.Default(),
```
Comment (deads2k) [inline pkg/cmd/server/start/master_args.go]: This broke `TEST_END_TO_END=direct hack/test-end-to-end.sh` because it longer starts DNS on 53, so our lookups fail.

Comment (smarterclayton) [inline pkg/cmd/server/start/master_args.go]: Ok, fix direct.  Or wait until node DNS lands.
