### PR TITLE
Fix manifest verification if pullthrough enabled

### LINKED ISSUE #12329: Extended.[builds][Slow] build can have Dockerfile input being created from new-build should create a image via new-build and infer the origin tag
this test is occasionally flaking because the registry rejects the push:

```
2016-12-22T09:11:40.767619000Z Pushing image 172.30.222.203:5000/extended-test-build-dockerfile-env-o6qro-0xsy0/centos:latest ...
2016-12-22T09:11:41.711758000Z Pushed 1/2 layers, 53% complete
2016-12-22T09:11:49.690709000Z Pushed 2/2 layers, 100% complete
2016-12-22T09:11:50.196426000Z Registry server Address: 
2016-12-22T09:11:50.196722000Z Registry server User Name: serviceaccount
2016-12-22T09:11:50.196966000Z Registry server Email: serviceaccount@example.org
2016-12-22T09:11:50.197244000Z Registry server Password: <<non-empty>>
2016-12-22T09:11:50.197465000Z error: build error: Failed to push image: errors:
2016-12-22T09:11:50.197675000Z manifest blob unknown: blob unknown to registry
2016-12-22T09:11:50.197874000Z manifest blob unknown: blob unknown to registry
2016-12-22T09:11:50.198071000Z manifest blob unknown: blob unknown to registry
2016-12-22T09:11:50.198327000Z manifest blob unknown: blob unknown to registry
2016-12-22T09:11:50.198586000Z manifest blob unknown: blob unknown to registry



 df -m output: Filesystem                                      1M-blocks  Used Available Use% Mounted on
/dev/xvda2                                          25588 15892      9697  63% /
devtmpfs                                             3891     0      3891   0% /dev
tmpfs                                                3784     0      3784   0% /dev/shm
tmpfs                                                3784    49      3735   2% /run
tmpfs                                                3784     0      3784   0% /sys/fs/cgroup
/dev/mapper/docker--vg-openshift--xfs--vol--dir      5090   814      4277  16% /mnt/openshift-xfs-vol-dir
tmpfs                                                 757     0       757   0% /run/user/0
tmpfs                                                2048   823      1226  41% /tmp
tmpfs                                                 757     0       757   0% /run/user/1000




 docker info output: 
Containers: 13
 Running: 4
 Paused: 0
 Stopped: 9
Images: 238
Server Version: 1.12.2-rc2
Storage Driver: devicemapper
 Pool Name: docker-202:2-42397575-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.304 GB
 Data Space Total: 107.4 GB
 Data Space Available: 10.17 GB
 Metadata Space Used: 13.94 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
```

full build is here:
https://ci.openshift.redhat.com/jenkins/job/origin_extended_build_tests/882

p2 because it's an extended test, not blocking the merge queue, but the implication that this could cause build failures in custom environments means it should be taken pretty seriously.

### PR DESCRIPTION
**Pull request by legionus**
Allow to use pullthrough for manifest verification.

Fix #12329 #12389 
https://bugzilla.redhat.com/show_bug.cgi?id=1408661
https://bugzilla.redhat.com/show_bug.cgi?id=1408374

@miminar @mfojtik @pweil- please review.

### CODE REVIEW

**Comment by legionus** [comment]
[testextended][extended:core(build can have Dockerfile input being created from new-build)]

**Comment by legionus** [comment]
[test]

File: pkg/dockerregistry/server/pullthroughblobstore.go [hunk 1]
```diff
@@ -118,6 +118,10 @@ func (r *pullthroughBlobStore) proxyStat(ctx context.Context, retriever importer
 }
 
 // ServeBlob attempts to serve the requested digest onto w, using a remote proxy store if necessary.
+// Important! This function is called for GET and HEAD requests. Docker client uses[1] HEAD request
```
Comment (mfojtik) [inline pkg/dockerregistry/server/pullthroughblobstore.go]: @smarterclayton is this a "bug" in the mirroring? (iow. should we disable mirroring on HEAD request?)

**Comment by mfojtik** [comment]
@legionus thank you! I will let @miminar to review the approach.

File: pkg/dockerregistry/server/pullthroughblobstore.go (hunk 1 above)
Comment (legionus) [inline pkg/dockerregistry/server/pullthroughblobstore.go]: @mfojtik Now the mirroring process starts when you push the image (docker uses HEAD to check layers). So the base image will begin to download immediately. I don't think it's wrong because once you push the image you want to pull it after a while.

Comment (mfojtik) [inline pkg/dockerregistry/server/pullthroughblobstore.go]: @legionus ok I think that makes sense for the mirroring case (I want to mirror the full image with all blobs when I push)

**Comment by miminar** [comment]
This LGTM as long as @smarterclayton is fine with mirroring blobs on HEAD requests.

Mirroring them makes sense to me because a Docker client, having the blobs already pulled, won't attempt to upload them if the HEAD returns 200. As a consequence, they won't get mirrored either because the Docker already has them. Without fetching them, we may loose ability to serve the image once the remote registry is down or the blobs get pruned.

A unit test would be nice.

File: pkg/dockerregistry/server/manifestschema1handler.go [hunk 2]
```diff
@@ -110,8 +110,12 @@ func (h *manifestSchema1Handler) Payload() (mediaType string, payload []byte, ca
 func (h *manifestSchema1Handler) Verify(ctx context.Context, skipDependencyVerification bool) error {
 	var errs distribution.ErrManifestVerification
 
-	// we want to verify that referenced blobs exist locally - thus using upstream repository object directly
-	repo := h.repo.Repository
+	// we want to verify that referenced blobs exist locally or accessable over
+	// pullthroughBlobStore. The base image of this image can be remote repository
+	// and since we use pullthroughBlobStore all the checks about the existence
```
Comment (miminar) [inline pkg/dockerregistry/server/manifestschema1handler.go]: all the layer existence checks

File: pkg/dockerregistry/server/manifestschema1handler.go [hunk 3]
```diff
@@ -110,8 +110,12 @@ func (h *manifestSchema1Handler) Payload() (mediaType string, payload []byte, ca
...
+	// of the layers will be successful. This means that the docker client
+	// will not attempt to send them to us as it will assume that they already here.
```
Comment (miminar) [inline pkg/dockerregistry/server/manifestschema1handler.go]: that the registry has them.

File: pkg/dockerregistry/server/manifestschema1handler.go [hunk 4]
```diff
@@ -110,8 +110,12 @@ func (h *manifestSchema1Handler) Payload() (mediaType string, payload []byte, ca
 func (h *manifestSchema1Handler) Verify(ctx context.Context, skipDependencyVerification bool) error {
 	var errs distribution.ErrManifestVerification
 
-	// we want to verify that referenced blobs exist locally - thus using upstream repository object directly
-	repo := h.repo.Repository
+	// we want to verify that referenced blobs exist locally or accessable over
```
Comment (legionus) [inline pkg/dockerregistry/server/manifestschema1handler.go]: @miminar fixed

File: pkg/dockerregistry/server/manifestschema1handler.go (hunk 2 above)
Comment (legionus) [inline pkg/dockerregistry/server/manifestschema1handler.go]: @miminar fixed

File: pkg/dockerregistry/server/manifestschema1handler.go (hunk 3 above)
Comment (legionus) [inline pkg/dockerregistry/server/manifestschema1handler.go]: @miminar fixed

**Comment by legionus** [comment]
> A unit test would be nice.

@miminar we already have extended test for this issue.

**Comment by miminar** [comment]
> @miminar we already have extended test for this issue.

I'd still like the unit test. Nevertheless, I don't make it a hard requirement. As I said, LGTM.

**Comment by legionus** [comment]
> I'd still like the unit test. Nevertheless, I don't make it a hard requirement. As I said, LGTM.

OK. Thanks! I keep the task in mind for improving tests for dockerregistry, but I want to start it after #11925.

**Comment by legionus** [comment]
@mfojtik merge ?

File: pkg/dockerregistry/server/pullthroughblobstore.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/dockerregistry/server/pullthroughblobstore.go]: Yeah, HEAD or GET effectively triggers a mirror because it helps automate mirror (just HEAD every image in the repo to clone them)
