### PR TITLE
Handle fallback to docker.io for 1.9 docker, which uses docker.io in .docker/config.json

### LINKED ISSUE #7580: private image import does not work when secret from .docker/config.json
While working with #7555 I found out that the server matching isn't picking up secret when uploaded with:
```
oc secrets new mysecret .dockerconfigjson=$HOME/.docker/config.json
```
The server value in this file is: `docker.io` but either `auth.docker.io/token` or `index.docker.io/v1` are being searched for. If secret is created manually with server pointing to one of the aforementioned URLs it's working correctly.

@smarterclayton fyi
I hope to start working on it as soon as other blocker bugs are fixed. 
@pweil- mind marking this as P1, yet another one ;)

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #7580 

@smarterclayton ptal, apparently there's a bug in docker 1.9 (definitely in f23) that uses `docker.io` instead of `https://index.docker.io/v1/` when saving config file upon `docker login`. I've added one more fallback for that case. I've tested that against docker 1.10 - there's no such problem anymore. Still I don't want people having problems like I did. The case that was fixed upstream, that you've mentioned in the original issue, is handling `v1`/`v2` parts of the URL.

### CODE REVIEW

File: pkg/image/importer/credentials.go [hunk 1]
```diff
@@ -139,6 +139,11 @@ func basicCredentialsFromKeyring(keyring credentialprovider.DockerKeyring, targe
 			glog.V(5).Infof("Being asked for %s, trying %s for legacy behavior", target, "index.docker.io/v1")
 			return basicCredentialsFromKeyring(keyring, &url.URL{Host: "index.docker.io", Path: "/v1"})
 		}
+		// docker 1.9 saves 'docker.io' in config in f23, see https://bugzilla.redhat.com/show_bug.cgi?id=1309739
+		if value == "index.docker.io" {
```
Comment (smarterclayton) [inline pkg/image/importer/credentials.go]: Isn't this broken for imagePullSecrets as well then?  Do we need a Kube fix?

Comment (liggitt) [inline pkg/image/importer/credentials.go]: yeah, fix needs to be in the keyring, most likely

Comment (liggitt) [inline pkg/image/importer/credentials.go]: hmm... maybe in both places...

**Comment by smarterclayton** [comment]
Lgtm [merge]

File: pkg/image/importer/credentials.go (hunk 1 above)
Comment (soltysh) [inline pkg/image/importer/credentials.go]: It's already handled upstream, see [here](https://github.com/kubernetes/kubernetes/blob/release-1.2/pkg/credentialprovider/keyring.go#L130).

**Comment by smarterclayton** [comment]
/var/lib/jenkins/.vagrant.d/gems/gems/vagrant-openshift-3.0.5/lib/vagrant-openshift/action/download_artifacts_origin.rb:24:in
`initialize': wrong number of arguments (2 for 3) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in
`new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:90:in
`finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in
`block in initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in
`map'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:20:in
`initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in
`new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:170:in
`to_app'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in
`call'


Merge flake @danmcp

**Comment by danmcp** [comment]
@stevekuznetsov

**Comment by bparees** [comment]
[merge] vagrant plugin was broken.

@danmcp @smarterclayton hopefully vagrant is fixed here: https://github.com/openshift/vagrant-openshift/pull/432
