### PR TITLE
Fix for bugz #1389165 - extended route validation breaks included templates

### LINKED ISSUE #11767: Printing the value of the router certificate in oc status is a security leak
Running oc status after creating a sample app.

```
 * route/frontend was not accepted by router "router":
  - spec.tls.certificate: Invalid value: "-----BEGIN CERTIFICATE-----\nMIIDIjCCAgqgAwIBAgIBATANBgkqhkiG9w0BAQUFADCBoTELMAkGA1UEBhMCVVMx\nCzAJBgNVBAgMAlNDMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0Rl\nZmF1bHQgQ29tcGFueSBMdGQxEDAOBgNVBAsMB1Rlc3QgQ0ExGjAYBgNVBAMMEXd3\ndy5leGFtcGxlY2EuY29tMSIwIAYJKoZIhvcNAQkBFhNleGFtcGxlQGV4YW1wbGUu\nY29tMB4XDTE1MDExMjE0MTk0MVoXDTE2MDExMjE0MTk0MVowfDEYMBYGA1UEAwwP\nd3d3LmV4YW1wbGUuY29tMQswCQYDVQQIDAJTQzELMAkGA1UEBhMCVVMxIjAgBgkq\nhkiG9w0BCQEWE2V4YW1wbGVAZXhhbXBsZS5jb20xEDAOBgNVBAoMB0V4YW1wbGUx\nEDAOBgNVBAsMB0V4YW1wbGUwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMrv\ngu6ZTTefNN7jjiZbS/xvQjyXjYMN7oVXv76jbX8gjMOmg9m0xoVZZFAE4XyQDuCm\n47VRx5Qrf/YLXmB2VtCFvB0AhXr5zSeWzPwaAPrjA4ebG+LUo24ziS8KqNxrFs1M\nmNrQUgZyQC6XIe1JHXc9t+JlL5UZyZQC1IfaJulDAgMBAAGjDTALMAkGA1UdEwQC\nMAAwDQYJKoZIhvcNAQEFBQADggEBAFCi7ZlkMnESvzlZCvv82Pq6S46AAOTPXdFd\nTMvrh12E1sdVALF1P1oYFJzG1EiZ5ezOx88fEDTW+Lxb9anw5/KJzwtWcfsupf1m\nV7J0D3qKzw5C1wjzYHh9/Pz7B1D0KthQRATQCfNf8s6bbFLaw/dmiIUhHLtIH5Qc\nyfrejTZbOSP77z8NOWir+BWWgIDDB2//3AkDIQvT20vmkZRhkqSdT7et4NmXOX/j\njhPti4b2Fie0LeuvgaOdKjCpQQNrYthZHXeVlOLRhMTSk3qUczenkKTOhvP7IS9q\n+Dzv5hqgSfvMG392KWh5f8xXfJNs4W5KLbZyl901MeReiLrPH3w=\n-----END CERTIFICATE-----": error verifying certificate: x509: certificate has expired or is not yet valid (ExtendedValidationFailed)
  * route/jenkins was not accepted by router "router":
  - spec.tls.certificate: Invalid value: "-----BEGIN CERTIFICATE-----\nMIIDIjCCAgqgAwIBAgIBATANBgkqhkiG9w0BAQUFADCBoTELMAkGA1UEBhMCVVMx\nCzAJBgNVBAgMAlNDMRUwEwYDVQQHDAxEZWZhdWx0IENpdHkxHDAaBgNVBAoME0Rl\nZmF1bHQgQ29tcGFueSBMdGQxEDAOBgNVBAsMB1Rlc3QgQ0ExGjAYBgNVBAMMEXd3\ndy5leGFtcGxlY2EuY29tMSIwIAYJKoZIhvcNAQkBFhNleGFtcGxlQGV4YW1wbGUu\nY29tMB4XDTE1MDExMjE0MTk0MVoXDTE2MDExMjE0MTk0MVowfDEYMBYGA1UEAwwP\nd3d3LmV4YW1wbGUuY29tMQswCQYDVQQIDAJTQzELMAkGA1UEBhMCVVMxIjAgBgkq\nhkiG9w0BCQEWE2V4YW1wbGVAZXhhbXBsZS5jb20xEDAOBgNVBAoMB0V4YW1wbGUx\nEDAOBgNVBAsMB0V4YW1wbGUwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMrv\ngu6ZTTefNN7jjiZbS/xvQjyXjYMN7oVXv76jbX8gjMOmg9m0xoVZZFAE4XyQDuCm\n47VRx5Qrf/YLXmB2VtCFvB0AhXr5zSeWzPwaAPrjA4ebG+LUo24ziS8KqNxrFs1M\nmNrQUgZyQC6XIe1JHXc9t+JlL5UZyZQC1IfaJulDAgMBAAGjDTALMAkGA1UdEwQC\nMAAwDQYJKoZIhvcNAQEFBQADggEBAFCi7ZlkMnESvzlZCvv82Pq6S46AAOTPXdFd\nTMvrh12E1sdVALF1P1oYFJzG1EiZ5ezOx88fEDTW+Lxb9anw5/KJzwtWcfsupf1m\nV7J0D3qKzw5C1wjzYHh9/Pz7B1D0KthQRATQCfNf8s6bbFLaw/dmiIUhHLtIH5Qc\nyfrejTZbOSP77z8NOWir+BWWgIDDB2//3AkDIQvT20vmkZRhkqSdT7et4NmXOX/j\njhPti4b2Fie0LeuvgaOdKjCpQQNrYthZHXeVlOLRhMTSk3qUczenkKTOhvP7IS9q\n+Dzv5hqgSfvMG392KWh5f8xXfJNs4W5KLbZyl901MeReiLrPH3w=\n-----END CERTIFICATE-----": error verifying certificate: x509: certificate has expired or is not yet valid (ExtendedValidationFailed)
```

First, I didn't set that cert, so I shouldn't be seeing the value of it.  Second, we shouldn't be printing this value because it's a potential security leak (someone can screenshot it over my shoulder).  Third, it's way too much text.

The validation message should probably not include the current value for certificates.

### PR DESCRIPTION
**Pull request by ramr**
@knobunc  @liggitt   PTAL  Thx
addressed the concerns you had in bug 1389165 [link](https://bugzilla.redhat.com/show_bug.cgi?id=1389165) as well - there were already existing tests that covered some of those but added a few more.

Also fixes #11767

### CODE REVIEW

**Comment by liggitt** [comment]
I'm not seeing where an expired or not-yet-valid cert is tolerated

File: pkg/route/api/validation/validation_test.go [hunk 1]
```diff
@@ -987,6 +1011,166 @@ func TestExtendedValidateRoute(t *testing.T) {
...
+			expectedErrors: 0,
+		},
+		{
+			name: "future validity date 2038 cert with different host",
+			route: &api.Route{
+				Spec: api.RouteSpec{
+					Host: "www.in.the.future.test",
+					TLS: &api.TLSConfig{
+						Termination: api.TLSTerminationEdge,
+						Certificate: testValidInFutureCert,
```
Comment (liggitt) [inline pkg/route/api/validation/validation_test.go]: it looks like this is only passing because you omit a CA, so no validation is done at all. need to have a test with CA with not-yet-valid and expired dates to make sure CA validation passes even when the cert timestamps aren't valid.

File: pkg/route/api/validation/validation.go [hunk 2]
```diff
@@ -125,18 +125,18 @@ func ExtendedValidateRoute(route *routeapi.Route) field.ErrorList {
...
-	}
 
-	verifyOptions := &x509.VerifyOptions{
-		DNSName: hostname,
-		Roots:   certPool,
+		verifyOptions = &x509.VerifyOptions{
+			DNSName: hostname,
+			Roots:   certPool,
+		}
 	}
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: when verifying, probably need to override the current time in VerifyOptions to be the NotAfter time on the cert

Comment (liggitt) [inline pkg/route/api/validation/validation.go]: and I would add two tests with cert->intermediate->root chains:
* include the intermediate cert in the Certificate data
* include the intermediate cert in the CACertificate data

(examples of intermediate chains at https://github.com/openshift/origin/tree/master/pkg/auth/authenticator/request/x509request/testdata)

**Comment by liggitt** [comment]
I'm also unsure we should include the full value of the cert/key/ca field in validation errors... in practice, it makes display of those errors unusable

File: pkg/route/api/validation/validation_test.go (hunk 1 above)
Comment (ramr) [inline pkg/route/api/validation/validation_test.go]: ok - will add a few more tests with an CA/intermediate CA - the one above is with self-signed cert.

File: pkg/route/api/validation/validation.go (hunk 2 above)
Comment (ramr) [inline pkg/route/api/validation/validation.go]: intermediates would have to be part of the CA cert. will add the above tests and check. thx

**Comment by ramr** [comment]
@liggitt  can clean up the errors if we want - it follows the other errors which pass the field value to   `field.Invalid`.

**Comment by liggitt** [comment]
yeah, in places where the data is confidential (like the key) or known to not be useful to display, we omit it and put a placeholder in like `"<certificate data>"`

**Comment by ramr** [comment]
@liggitt  addressed your comments - added more tests for intermediate CAs + future valid/expired certs plus made changes to pass the intermediates options to the verifier and cleaned up the errors to not leak cert/key data.   PTAL Thx

One thing that was weird was for certs that expired a year or two back, setting the `CurrentTime` for the VerifyOptions (https://golang.org/pkg/crypto/x509/#VerifyOptions) works but if the certs expired in `2000` (one of the test data set has that), it still returns an expired cert error. So I did have to do an explicit check/guard for that and only return the error if: 
`if invalidErr, ok := err.(x509.CertificateInvalidError); !ok || invalidErr.Reason != x509.Expired { ...`.

**Comment by ramr** [comment]
[test]

File: pkg/route/api/validation/validation_test.go [hunk 3]
```diff
@@ -110,6 +110,30 @@ bGvtpjWA4r9WASIDPFsxk/cDEEEO6iPxgMOf5MdpQC2y2MU0rzF/Gg==
...
...JDQTERMA8GA1UECgwIU2VjdXJpdHkxEzARBgNVBAsM\nClNlbGZTaWduZXIxGTAXBgNVBAMMEHNlbGYuc2lnbmVyLnRlc3QwIBcNMzgwMTAx\nMDgwMDAyWhgPMjA1ODAxMDEwODAwMDJaMF0xCzAJBgNVBAYTAlVTMQswCQYDVQQI\nDAJDQTERMA8GA1UECgwIU2VjdXJpdHkxEzARBgNVBAsMClNlbGZTaWduZXIxGTAX\nBgNVBAMMEHNlbGYuc2lnbmVyLnRlc3QwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\nggEKAoIBAQDBAtP5vHkVS9qZNmI9QKj7B/ATt2+Fw+f4xD+6Q2+1sOkLH3x6+D85\n5A+xAAvQdz5qf+yfvtNOhWqmIG5Zh0TzaiA5lw2U0YL4FT4Z4nbYAPMO45lctvRH\nnXBeSO7N/JiFBlvMPqP4gsimstEgiNm225KlQRHOqMfOEAC15pyUrE643Gs0DCVR\nL1tZuwdfBUpybxAPDWpgx7CNTc0beuNXooroMU1dCdM+BjYHYfSCnoNwa4qp130e\n6vRWnzlhfXbFTsCVCe4y6edF/+M3PegIx0+PhkgeSOxd2+nBsiatrG5ZyiP5iaRK\n2278nFERyUQ1SbhicDrhlU9TQAMcTMAvAgMBAAGjUDBOMB0GA1UdDgQWBBQ28jRf\nN/CCqVyOU8mOZpG8ow86WjAfBgNVHSMEGDAWgBQ28jRfN/CCqVyOU8mOZpG8ow86\nWjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQC+Nu8pEUB7agGHUU/e\n1NHI84guwKKA2qNnkQZKn6h49AA/bPjKr9SFQHNxFFMyrVInt1Ez9sRNviArQc+w\nDToHY+T/3WUVcQIQnRW3m4r6UUsxKZjtrSBD2Dhr6nL9hVVtGIfimuuxxJt1JItJ\nUaOY+Kq4gtWOJMcV5xTEaPmkphAgwoZzjZj7Z9SZwVLGopJa8kB3EvlkxUO3DmSp\n9Lq3AhHRYgwWcjcd9UC9NyXQ9hBTV2iPBSvc2I4vmYQwnOutBEeNM0IPQQk7f2VL\nfKSS26HocZpiN0e7vO0XoJfh4VkOIn7BGNwxiDr9cIRL4ZHhZ0/kRQuXCHHYbTdq\n9mKv\n-----END CERTIFICATE-----\n"
```
Comment (liggitt) [inline pkg/route/api/validation/validation_test.go]: in the future, for readibility, use raw strings and literal newlines:
```
testValidInFutureCert = `-----BEGIN CERTIFICATE-----
MIIDjzCCAnegAwIBAgIJAJcdKWMFNUEGMA0GCSqGSIb3DQEBCwUAMF0xCzAJBgNV
BAYTAlVTMQswCQYDVQQIDAJDQTERMA8GA1UECgwIU2VjdXJpdHkxEzARBgNVBAsM
ClNlbGZTaWduZXIxGTAXBgNVBAMMEHNlbGYuc2lnbmVyLnRlc3QwIBcNMzgwMTAx
...
```

**Comment by knobunc** [comment]
@liggitt do you want that chance to be made now?  Or are we good to merge?

**Comment by ramr** [comment]
Done - made the readability changes.
[test]

**Comment by knobunc** [comment]
[merge]

**Comment by liggitt** [comment]
question about date validation and needs squash

File: pkg/route/api/validation/validation.go [hunk 4]
```diff
@@ -300,9 +301,14 @@ func validateCertificatePEM(certPEM string, options *x509.VerifyOptions) (*x509.
...
 
 	if options != nil {
+		// Ensure we don't report errors for expired certs or if
+		// the validity is in the future.
+		options.CurrentTime = cert.NotAfter.AddDate(0, 0, -1)
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: looks like the intermediate certs are failing... if we have a cert valid from A-B signed by another cert valid from C-D, and A-B/C-D are non-overlapping, that chain will not be valid at any single instant.

Comment (liggitt) [inline pkg/route/api/validation/validation.go]: I'm wondering if we can just validate the well-formedness of the CA bundle and skip the validation.

File: pkg/route/api/validation/validation.go [hunk 5]
```diff
@@ -300,9 +301,14 @@ func validateCertificatePEM(certPEM string, options *x509.VerifyOptions) (*x509.
 	}
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: we probably want to make sure all the `CERTIFICATE` blocks in the PEM parse

File: pkg/route/api/validation/validation.go [hunk 6]
```diff
@@ -125,23 +125,24 @@ func ExtendedValidateRoute(route *routeapi.Route) field.ErrorList {
 	//       break, so disable the hostname validation for now.
 	// hostname := route.Spec.Host
 	hostname := ""
-	var certPool *x509.CertPool
+	var verifyOptions *x509.VerifyOptions
 
 	if len(tlsConfig.CACertificate) > 0 {
-		certPool = x509.NewCertPool()
+		certPool := x509.NewCertPool()
 		if ok := certPool.AppendCertsFromPEM([]byte(tlsConfig.CACertificate)); !ok {
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: AppendCertsFromPEM returns ok even if the CA bundle contains invalid certs, which could break the router. `pkg/cmd/util/CertificatesFromPEM()` will return an error if there are malformed certs, which is probably what you want.

File: pkg/route/api/validation/validation.go (hunk 5 above)
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: not sure what to do if there are non-CERTIFICATE PEM blocks in here... will that choke the router?

Comment (ramr) [inline pkg/route/api/validation/validation.go]: We are appending only the certs from the PEM to the cert pool. 
As re: router should be fine - only cert and key blocks would be used.

**Comment by ramr** [comment]
@liggitt   made changes as per your comments. 
[test]

File: pkg/route/api/validation/validation.go [hunk 7]
```diff
@@ -125,23 +125,28 @@ func ExtendedValidateRoute(route *routeapi.Route) field.ErrorList {
...
-	var certPool *x509.CertPool
+	var verifyOptions *x509.VerifyOptions
 
 	if len(tlsConfig.CACertificate) > 0 {
-		certPool = x509.NewCertPool()
-		if ok := certPool.AppendCertsFromPEM([]byte(tlsConfig.CACertificate)); !ok {
-			result = append(result, field.Invalid(tlsFieldPath.Child("caCertificate"), tlsConfig.CACertificate, "failed to parse CA certificate"))
+		certPool := x509.NewCertPool()
+		if certs, err := cmdutil.CertificatesFromPEM([]byte(tlsConfig.CACertificate)); err != nil {
+			result = append(result, field.Invalid(tlsFieldPath.Child("caCertificate"), "<ca certificate data>", "failed to parse CA certificate"))
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: include the error? `"failed to parse CA certificate: %v", err`

File: pkg/route/api/validation/validation.go [hunk 8]
```diff
@@ -152,14 +157,13 @@ func ExtendedValidateRoute(route *routeapi.Route) field.ErrorList {
...
+			result = append(result, field.Invalid(tlsFieldPath.Child("key"), "<key data>", err.Error()))
 		}
 	}
 
 	if len(tlsConfig.DestinationCACertificate) > 0 {
-		roots := x509.NewCertPool()
-		if ok := roots.AppendCertsFromPEM([]byte(tlsConfig.DestinationCACertificate)); !ok {
-			result = append(result, field.Invalid(tlsFieldPath.Child("destinationCACertificate"), tlsConfig.DestinationCACertificate, "failed to parse destination CA certificate"))
+		if _, err := cmdutil.CertificatesFromPEM([]byte(tlsConfig.DestinationCACertificate)); err != nil {
+			result = append(result, field.Invalid(tlsFieldPath.Child("destinationCACertificate"), "<destination ca certificate data>", "failed to parse destination CA certificate"))
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: include error in message

**Comment by ramr** [comment]
@liggitt  done - [test]

File: pkg/route/api/validation/validation.go [hunk 9]
```diff
@@ -276,35 +282,27 @@ func validateInsecureEdgeTerminationPolicy(tls *routeapi.TLSConfig, fldPath *fie
...
-
 	if options != nil {
-		_, err = cert.Verify(*options)
+		// Ensure we don't report errors for expired certs or if
+		// the validity is in the future.
+		options.CurrentTime = certs[0].NotAfter.AddDate(0, 0, -1)
+		_, err = certs[0].Verify(*options)
 		if err != nil {
-			return cert, fmt.Errorf("error verifying certificate: %s", err.Error())
+			if invalidErr, ok := err.(x509.CertificateInvalidError); !ok || invalidErr.Reason != x509.Expired {
```
Comment (ramr) [inline pkg/route/api/validation/validation.go]: The original issue was to ensure cert+key+ca matched/was valid - which is why the extended validation was added. So ... we would need this.

Comment (liggitt) [inline pkg/route/api/validation/validation.go]: Are we sure the expiration error doesn't short circuit the signing validation error

Comment (ramr) [inline pkg/route/api/validation/validation.go]: There's tests for invalid cacert/cert/key combinations with good certificates which test for that.

Comment (liggitt) [inline pkg/route/api/validation/validation.go]: ok

File: pkg/route/api/validation/validation.go [hunk 10]
```diff
@@ -276,35 +282,27 @@ func validateInsecureEdgeTerminationPolicy(tls *routeapi.TLSConfig, fldPath *fie
...
-	cert, err := x509.ParseCertificate(data.Bytes)
-	if err != nil {
-		return nil, fmt.Errorf("error parsing certificate: %s", err.Error())
-	}
-
 	if options != nil {
-		_, err = cert.Verify(*options)
+		// Ensure we don't report errors for expired certs or if
+		// the validity is in the future.
+		options.CurrentTime = certs[0].NotAfter.AddDate(0, 0, -1)
```
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: if we're ignoring expired certs, there's not need to mess with CurrentTime at all

File: pkg/route/api/validation/validation.go (hunk 9 above)
Comment (liggitt) [inline pkg/route/api/validation/validation.go]: add a comment about why we ignore expired certs (doesn't choke the router, shouldn't reject routes), and why we don't simulate the current time in verify options (can't pick a single point in time that validates if the cert was signed by an expired intermediate)

**Comment by liggitt** [comment]
remove the currenttime hack, comment why we're ignoring expired certs, squash, then LGTM

**Comment by ramr** [comment]
done - changed as per @liggitt  comments and squashed.
[test]

**Comment by liggitt** [comment]
Thanks, LGTM

**Comment by knobunc** [comment]
[merge]
