### PR TITLE
SCC: recognize that SELinux levels can be logically equivalent

### LINKED ISSUE #15627: PSP/SCC should sort linux levels for logical comparison
In another issue it was noticed that PSP/SCC should recognize that SELinux levels can be logically equivalent.  Currently levels will be failed today if the exact ordering is not met:

For example:  s0:c0,c6 is equal to s0:c6,c0

Enhance PSP/SCC to take into account logical equivalence of the SELinux level.

@childsb @pmorie @php-coder @openshift/sig-security

### PR DESCRIPTION
**Pull request by php-coder**
For example: s0:c0,c6 is the same as s0:c6,c0

Fixes #15627

### CODE REVIEW

**Comment by adelton** [comment]
We should be able to support ranges, like `s0-s0:c0.c255`. Also, the categories shouldn't be sorted as strings as the numerical part can have multiple digits.

I'm also not sure that we are looking for equality here -- don't we look for dominance and superset instead?

**Comment by php-coder** [comment]
> We should be able to support ranges, like s0-s0:c0.c255.

Ok, I'll add it.

> Also, the categories shouldn't be sorted as strings as the numerical part can have multiple digits.

It doesn't matter how they are sorted as we're sorting both parts. In other words, the sorting logic doesn't affect the result.

**Comment by php-coder** [comment]
> We should be able to support ranges, like s0-s0:c0.c255.

Added. @adelton PTAL

**Comment by adelton** [comment]
> It doesn't matter how they are sorted as we're sorting both parts. In other words, the sorting logic doesn't affect the result.

But are we really looking for equality? IMHO, `s0:c0.c2` should admit pod which asks for `s0:c1`, shouldn't it?

**Comment by rhatdan** [comment]
I think we should omit single category labels altogether.  People understand the uniqueness, they don't understand dominance.  MCS Separation has a hidden secret, dominance.   In order to stop people confusion we should stick to a single count of Categories, and guarantee uniqueness.

**Comment by php-coder** [comment]
@adelton @rhatdan I don't understand what are you talking about unfortunately :( If you want me to edit this PR somehow then could you be more specific, please?

File: pkg/security/securitycontextconstraints/selinux/mustrunas.go [hunk 1]
```diff
@@ -67,3 +71,70 @@ func (s *mustRunAs) Validate(pod *api.Pod, container *api.Container) field.Error
...
+		}
+	}
+
+	return []string{sensitivity}
+}
+
+func parseCategories(categories string) []string {
+	parts := strings.Split(categories, ",")
+
+	// "c0.c3" => [ "c0", "c1", "c2", c3" ]
```
Comment (smarterclayton) [inline pkg/security/securitycontextconstraints/selinux/mustrunas.go]: why isn't this 

```
categories := strings.Split('.')
sort.Strings(categories)
```

?   Why are you go into deeper parsing?

Comment (smarterclayton) [reply pkg/security/securitycontextconstraints/selinux/mustrunas.go]: Oh, I see that this is an expansion.  Please add godoc to the method

File: pkg/security/securitycontextconstraints/selinux/mustrunas_test.go [hunk 2]
```diff
@@ -79,43 +79,76 @@ func TestMustRunAsValidate(t *testing.T) {
...
+			seLinux:         levelWithIdenticalSensitivity,
+			expectedSeLinux: newValidOpts(),
+			expectedMsg:     "",
+		},
+		"valid level with different order of categories": { // "s0:c6,c0" == "s0:c0,c6"
+			seLinux:         levelWithDifferentOrderOfCategories,
+			expectedSeLinux: newValidOpts(),
+			expectedMsg:     "",
+		},
+		"valid level with abbreviated categories": { // "s0:c0.c3" == "s0:c0,c1,c2,c3"
```
Comment (smarterclayton) [inline pkg/security/securitycontextconstraints/selinux/mustrunas_test.go]: need some additional tests, test edges cases and multiple equivalences.

File: pkg/security/securitycontextconstraints/selinux/mustrunas.go (hunk 1 above)
Comment (Miciah) [inline pkg/security/securitycontextconstraints/selinux/mustrunas.go]: s/c3"/"c3"/

File: pkg/security/securitycontextconstraints/selinux/mustrunas.go [hunk 3]
```diff
@@ -67,3 +71,70 @@ func (s *mustRunAs) Validate(pod *api.Pod, container *api.Container) field.Error
...
+			begin := strings.TrimPrefix(categoryRange[0], "c")
+			end := strings.TrimPrefix(categoryRange[1], "c")
+
+			// bitSize 16 because we expect that categories will be in a range [0, 1024)
+			from, err1 := strconv.ParseInt(begin, 10, 16)
+			to, err2 := strconv.ParseInt(end, 10, 16)
+			if err1 == nil && err2 == nil && from < to {
+				parts = make([]string, to-from+1)
+				for i := from; i <= to; i++ {
+					parts[i] = fmt.Sprintf("c%d", i)
```
Comment (Miciah) [inline pkg/security/securitycontextconstraints/selinux/mustrunas.go]: This will go out of bounds if `categoryRange[0]` is not `c0` (e.g., `parseCategories("c1.c4")` panics—might be a good test case).  You cannot use the same variable for the index and the format, at least not without some arithmetic.

Comment (php-coder) [reply pkg/security/securitycontextconstraints/selinux/mustrunas.go]: @Miciah Indeed, good catch, thanks!

File: pkg/security/securitycontextconstraints/selinux/mustrunas_test.go (hunk 2 above)
Comment (php-coder) [reply pkg/security/securitycontextconstraints/selinux/mustrunas_test.go]: What do you mean by "multiple equivalences"?

**Comment by php-coder** [comment]
More code and tests were added. Feedback is highly appreciated!

**Comment by php-coder** [comment]
Test flake https://github.com/openshift/origin/issues/14085
/test extended_conformance_gce

**Comment by php-coder** [comment]
Test flake https://github.com/openshift/origin/issues/16402
/test cmd

**Comment by php-coder** [comment]
Bug in Kubernetes: https://github.com/kubernetes/kubernetes/issues/53590
/test origin-ut

**Comment by php-coder** [comment]
@openshift/sig-security PTAL

**Comment by php-coder** [comment]
Ping.

**Comment by adelton** [comment]
In general, my question is if the SCC allows `c0.c4` and the pod asks for `c0`, should it be permitted or not?

**Comment by php-coder** [comment]
> In general, my question is if the SCC allows c0.c4 and the pod asks for c0, should it be permitted or not?

```
<semushin> pweil, WDYT? Sounds like yes, a pod should be permitted; but it could be a case for another PR.
<pweil> semushin, yes, I think that would match, probably a lower priority follow up
```

File: pkg/security/securitycontextconstraints/selinux/mustrunas_test.go [hunk 4]
```diff
@@ -80,42 +86,158 @@ func TestMustRunAsValidate(t *testing.T) {
...
+			expectedSeLinux: newValidOptsWithLevel("s1:c1"),
+			expectedMsg:     "does not match required level",
+		},
+		"invalid level, expected category with a wrong prefix": {
+			seLinux:         newValidOpts(),
+			expectedSeLinux: newValidOptsWithLevel("s0:c1.w2"),
+			expectedMsg:     "does not match required level",
+		},
+		"invalid level, actual category with a wrong prefix": {
+			seLinux:         newValidOptsWithLevel("s0:c1.w2"),
```
Comment (eparis) [inline pkg/security/securitycontextconstraints/selinux/mustrunas_test.go]: Isn't this the same as https://github.com/openshift/origin/pull/16432/files#diff-7116cbe02d68c6308574bed3cf7fb864R130

Comment (php-coder) [reply pkg/security/securitycontextconstraints/selinux/mustrunas_test.go]: The values are the same but in the first case they are in expected category and in another case in an actual category. I was looking on the code coverage and these 2 tests cover all the possible branches. Let me know if you think that 2 tests are superfluous, I can remove one of them, if you want.

**Comment by eparis** [comment]
What dan is saying in https://github.com/openshift/origin/pull/16432#issuecomment-331880566 is that you should NOT try to determine dominance or any special relationship between category sets. That is all policy and you can't know what policy says. Some policies may have very wierd inter-relations between level and category sets. Please only account of exact equivalence.

This really needs to be a libselinux function :-(

@stephensmalley   I can't find a libselinux function to really help us. We just want to know is the string `s-s0:c1,c2,c3` the same as `so:c1.c3`. I was hoping that a combination of `context_new`, `context_str` and `selinux_file_context_cmp` could be used to get this answer but it doesn't look like we have anything which does some form of semantic category normalization...

So maybe this PR is the best thing we can do.

File: pkg/security/securitycontextconstraints/selinux/mustrunas_test.go (hunk 4 above)
Comment (eparis) [reply pkg/security/securitycontextconstraints/selinux/mustrunas_test.go]: oh oh, I wrong. I see now. Sorry.

**Comment by stephensmalley** [comment]
security_canonicalize_context(3) from libselinux.  Oddly, no man page.
Sample usage:
$ cat canon.c
#include <selinux/selinux.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
	const char *ctx;
	char *canoncon;
	int rc;

	ctx = argv[1];
	rc = security_canonicalize_context(ctx, &canoncon);
	if (rc < 0)
		perror(ctx);
	else {
		printf("%s\n", canoncon);
		free(canoncon);
	}
	exit(rc);
}
$ make LDLIBS+=-lselinux canon
$ $ ./canon unconfined_u:unconfined_r:unconfined_t:s0:c0,c1,c2
unconfined_u:unconfined_r:unconfined_t:s0:c0.c2

**Comment by stephensmalley** [comment]
Also, if you want something more than strict equality checking, then do a permission check via selinux_check_access(3) or security_compute_av() on the context class, contains permission, and add a mlsconstrain statement for that class/perm to mcs policy (already exists in MLS policy, precisely for this reason - to allow userspace to perform a dominance check without hardcoded policy).

**Comment by rhatdan** [comment]
I just opened a PR to add this function to the go bindings.

https://github.com/opencontainers/selinux/pull/19

Not tested yet, but I will add a test suite mentioned above.

**Comment by php-coder** [comment]
Rebased and include improvements from Kubernetes PR. PTAL.

**Comment by php-coder** [comment]
Test flake https://github.com/openshift/origin/issues/17605
/test extended_conformance_install

**Comment by php-coder** [comment]
The old version of sources were used.
/test extended_conformance_gce

**Comment by php-coder** [comment]
@pweil- @deads2k PTAL

**Comment by php-coder** [comment]
@pweil- @deads2k @smarterclayton PTAL

**Comment by php-coder** [comment]
@smarterclayton Ping

**Comment by php-coder** [comment]
@smarterclayton New Year Ping.

**Comment by php-coder** [comment]
@pweil- Paul, could you review it and maybe approve it, please?

**Comment by php-coder** [comment]
Rebased. PTAL.

**Comment by php-coder** [comment]
The PR has been updated. In order to merge in the upstream, it was decided to make it as simple as possible and solve only the original issue with ordering. No support for ranges and expansion at this point.

@openshift/sig-security PTAL

File: pkg/security/securitycontextconstraints/selinux/mustrunas.go [hunk 5]
```diff
@@ -2,9 +2,12 @@ package selinux
 
 import (
 	"fmt"
+	"sort"
+	"strings"
 
 	"k8s.io/apimachinery/pkg/util/validation/field"
 	api "k8s.io/kubernetes/pkg/apis/core"
+	psputil "k8s.io/kubernetes/pkg/security/podsecuritypolicy/util"
```
Comment (php-coder) [inline pkg/security/securitycontextconstraints/selinux/mustrunas.go]: I decided to use PSP's utils instead of duplicating them. That's why this PR has `vendor-update` tag.

**Comment by simo5** [comment]
@pweil- given we will eventually migrate away from SCC to PSP, I think I prefer to just copy here for now, or we'll have public functions in PSP that are used by nothing but PSP once we drop SCC. Also any change to PSP would end up with more maintenance to keep SCC working until we can drop it.
So IMO it is good as proposed.

**Comment by simo5** [comment]
Actually I would even endorse copying the psputil function as a private function for mustrunas.go and avoid the vendoring warnings.

**Comment by pweil-** [comment]
> @pweil- given we will eventually migrate away from SCC to PSP, I think I prefer to just copy here for now, or we'll have public functions in PSP that are used by nothing but PSP once we drop SCC. Also any change to PSP would end up with more maintenance to keep SCC working until we can drop it.
> So IMO it is good as proposed.

I'm ok with this strategy, however if the comparisons were exposed in psputil and used then any changes we do upstream to enhance it wouldn't have to be copied, we'd just get them upon rebase.  It is also not something we'd need to do an in depth review on when we decide to migrate to make sure we're not missing a difference.  That burden is on your team though so it's your call. :+1:

**Comment by php-coder** [comment]
@pweil- @simo5 Thanks for the feedback!

I updated the PR and removed the dependency to PSP's `util` package.
