### PR TITLE
Remove incorrect print statement from list pods

### LINKED ISSUE #9244: Output of JSON not exactly json...
When running the oadm command requesting output of json format, it contains a header which doens't go away, therefore the output is not _just_ the json requested format

##### Version
```
openshift v1.2.0
kubernetes v1.2.0-36-g4a3f9c5
etcd 2.2.5
```

##### Steps To Reproduce
1. Running Pod on some random node
```
[vagrant@localhost ~]$ oadm manage-node localhost.localdomain --list-pods

Listing matched pods on node: localhost.localdomain

NAME              READY     STATUS    RESTARTS   AGE
testapp-1-8dq74   1/1       Running   0          58s
```
2. Execute the command to spit out the above in json format

##### Current Result
```

[vagrant@localhost ~]$ oadm manage-node localhost.localdomain --list-pods -o json

Listing matched pods on node: localhost.localdomain

{
    "metadata": {
        "selfLink": "/api/v1/pods",
        "resourceVersion": "999"
    },
    "items": [
        {
            "metadata": {
<SNIP>
```

##### Expected Result
```

[vagrant@localhost ~]$ oadm manage-node localhost.localdomain --list-pods -o json
{
    "metadata": {
        "selfLink": "/api/v1/pods",
        "resourceVersion": "999"
    },
    "items": [
        {
            "metadata": {
<SNIP>
```

##### Additional Information
This is just one small example.  If I were to run `oc get testapp-1-8dq74 -o json`, it works just as I would expect it too.  Other `oadm` commands also appear to work as expected.  I'm not sure if this is isolated to the `manage-node` command or not.

This may potentially be related to #7899

### PR DESCRIPTION
**Pull request by enj**
fixes #9244 

The print statements in `listpods.go` and `evacuate.go` cause issues when using `-o`.  These have been moved to `stderr`.

`oadm manage-node <node1> --list-pods -o json` now outputs the expected to `stdout`:

```json
{
    "metadata": {
        "selfLink": "/api/v1/pods",
        "resourceVersion": "3157"
    },
    "items": [
        {
...
```

### CODE REVIEW

File: pkg/cmd/admin/node/evacuate.go [hunk 1]
```diff
@@ -115,7 +115,6 @@ func (e *EvacuateOptions) RunEvacuate(node *kapi.Node) error {
 		}
 
 		if firstPod {
-			fmt.Fprint(e.Options.Writer, "\nMigrating these pods on node: ", node.ObjectMeta.Name, "\n\n")
```
Comment (liggitt) [inline pkg/cmd/admin/node/evacuate.go]: would be better to plumb a stderr writer and use that

Comment (enj) [inline pkg/cmd/admin/node/evacuate.go]: @liggitt Done.

**Comment by liggitt** [comment]
lgtm, [merge]
