### PR TITLE
Fix image size calculation in importer

### LINKED ISSUE #7706: Images on DockerHub fail to import size because they are in schema1
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/5142/consoleFull
```
--- FAIL: TestImageStreamImport-2 (6.29s)
	imageimporter_test.go:105: unexpected image output: (*api.Image)(nil)
FAIL
I0229 17:38:57.818710   25915 importer.go:308] importing remote Docker repository registry=https://registry-1.docker.io repository=library/mongo insecure=false
I0229 17:38:57.820419   25915 credentials.go:24] asked to provide Basic credentials for https://auth.docker.io/token
I0229 17:38:58.056945   25915 importer.go:352] unable to access tags for repository &importer.importRepository{Ref:api.DockerImageReference{Registry:"", Namespace:"", Name:"mongo", Tag:"", ID:""}, Registry:(*url.URL)(0xc20807a580), Name:"library/mongo", Insecure:false, Tags:[]importer.importTag(nil), Digests:[]importer.importDigest(nil), MaximumTags:3, AdditionalTags:[]string(nil), Err:error(nil)}: &url.Error{Op:"Get", URL:"https://registry-1.docker.io/v2/library/mongo/tags/list", Err:(*errors.errorString)(0xc2087ad360)}
--- FAIL: TestImageStreamImportDockerHub-2 (1.80s)
	imageimporter_test.go:523: unexpected repository: &api.RepositoryImportStatus{Status:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"Internal error occurred: Get https://registry-1.docker.io/v2/library/mongo/tags/list: token auth attempt for registry: https://auth.docker.io/token?scope=repository%3Alibrary%2Fmongo%3Apull&service=registry.docker.io request failed with status: 500 Internal Server Error", Reason:"InternalError", Details:(*unversioned.StatusDetails)(0xc2087d7c20), Code:500}, Images:[]api.ImageImportStatus(nil), AdditionalTags:[]string(nil)}
	imageimporter_test.go:530: unexpected object: (*api.Image)(nil)
	imageimporter_test.go:534: unexpected object: (*api.Image)(nil)
	imageimporter_test.go:538: unexpected object: (*api.Image)(nil)
	imageimporter_test.go:542: unexpected object: api.ImageImportStatus{Tag:"", Status:unversioned.Status{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ListMeta:unversioned.ListMeta{SelfLink:"", ResourceVersion:""}, Status:"Failure", Message:"Internal error occurred: Get https://registry-1.docker.io/v2/mysql/doesnotexistinanyform/manifests/latest: token auth attempt for registry: https://auth.docker.io/token?scope=repository%3Amysql%2Fdoesnotexistinanyform%3Apull&service=registry.docker.io request failed with status: 500 Internal Server Error", Reason:"InternalError", Details:(*unversioned.StatusDetails)(0xc20897f3b0), Code:500}, Image:(*api.Image)(nil)}
FAIL
```

### PR DESCRIPTION
**Pull request by legionus**
After upgrading docker/distibution V1Compatibility no longer contains Size. For
this reason, the image size calculation is wrong. A new way to calculate the
size repeats the way that dockerregistry calculates the size.

Fix #7706 

@smarterclayton @pweil- @mfojtik @miminar @kargakis

### CODE REVIEW

**Comment by legionus** [comment]
[test]

**Comment by soltysh** [comment]
[test]

File: pkg/image/importer/importer.go [hunk 1]
```diff
@@ -397,6 +418,7 @@ func importRepositoryFromDocker(ctx gocontext.Context, retriever RepositoryRetri
 			importDigest.Err = err
 			continue
 		}
+		importDigest.Err = calculateImageSize(ctx, repo, importDigest.Image)
```
Comment (soltysh) [inline pkg/image/importer/importer.go]: I'd rather we calculcate the size only when it's not there. Not all registries we use are hub.docker.com, for that cases (where v1 schema is supported) it's unnecessarily calculates the size. 

This could be done as a followup to this issue, we care to unblock the queue, atm.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Please use the pattern we are using above (`if err := ...; err != nil { importDigest.Err = err; continue }`) for readability.

This definitely will be broken on v1, which does not have layer sizes.

Comment (deads2k) [inline pkg/image/importer/importer.go]: Seems like a more natural fit inside of `schema1ToImage` to build a complete `Image` object.  The additional fanout is less than beautiful, but it would keep the API looking more consistent.  `schema1ToImage` would return a complete and valid look.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Can you make sure the integration test is properly testing v1 sizes against registry.access.redhat.com?

Comment (legionus) [inline pkg/image/importer/importer.go]: Schema v1 supported by hub.docker.com. Before that we used is not documented structure to calculate the size.

https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md#manifest-field-descriptions

```
v1Compatibility string

V1Compatibility is the raw V1 compatibility information. This will contain the JSON
object describing the V1 of this image.

```

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: It doesn't matter that it's not documented - it's what is deployed in
production in many places still.

File: pkg/image/importer/importer.go [hunk 2]
```diff
@@ -282,6 +282,27 @@ func applyErrorToRepository(repository *importRepository, err error) {
 	}
 }
 
+func calculateImageSize(ctx gocontext.Context, repo distribution.Repository, image *api.Image) error {
```
Comment (deads2k) [inline pkg/image/importer/importer.go]: Same as `fillImageWithMetadata`? https://github.com/openshift/origin/blob/master/pkg/dockerregistry/server/repositorymiddleware.go#L418

File: pkg/image/importer/importer.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Why are we not using the descriptor on the layers reference to calculate
the size?  We already have that data in schema on `layers` - in
schema2toManifest (which this PR should create) we would be able to
calculate the fake size.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: I don't see the need to call stat

File: pkg/image/importer/importer.go [hunk 3]
```diff
@@ -282,6 +282,27 @@ func applyErrorToRepository(repository *importRepository, err error) {
...
+	bs := repo.Blobs(ctx)
+
+	layerSet := sets.NewString()
+	size := int64(0)
+	for i := range image.DockerImageLayers {
+		layer := &image.DockerImageLayers[i]
+		desc, err := bs.Stat(ctx, digest.Digest(layer.Name))
```
Comment (legionus) [inline pkg/image/importer/importer.go]: `schema1ToImage` is only about image creation. It's not getting digests and do not have anything to calculate the size.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: According to the v2 spec size must be filled out in layers.  Is that not
the case?

Comment (legionus) [inline pkg/image/importer/importer.go]: Schema v1 don't have the size:

https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-1.md#example-manifest

Schema v2 have it:

https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md#example-image-manifest

But right now we talking about schema v1.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Ah, this is because we aren't fetching them as schema2.  So then I'm going
to retract the statement above.

If we are talking to a v1 registry - we'll get data from v1compatibility.
If we're talking to a v2 registry prior to this change from the Hub, we'll
get the data from v1compatibility
If we're talking to a v2 registry that is using schema2 internally, we'll
get the data from layers

The old code should be copying the v1compatibility data into the layers
field of the Image
The new code should be using schema2 and copying the size in

We can live in 1.1 with zero length fields for new images.  If we ask for
schema2 in 1.2 and master, how of a change is that?  How close are we to
schema2 in master?

For now, let's disable this test while we sort out the answers to the two
questions above.

File: pkg/image/importer/importer.go (hunk 1 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: >  it's unnecessarily calculates the size. 

@soltysh @smarterclayton  I added the check to calculate the size only when it is equal to zero. This would eliminate unnecessary requests if we have all the information.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: I'm still concerned because each of those stats could fail, resulting in
other failures.  We probably *don't* want to fail import if size can't be
calculated.  We probably don't want to add a fan-out of 20 requests on
setup.

I'd prefer to not fix this until we have schema2 support.  I thought we
were getting a schema2 response without size.

File: pkg/image/importer/importer.go (hunk 3 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: If Docker 1.10 or newer ask for old (schema1) image manifest then it will be returned without conversion to schema2. Take a look: https://github.com/docker/distribution/blob/master/registry/handlers/images.go#L65 (`isSchema2` is false).

docker-registry-2.4 does not help if we will ask for old image. We can't force docker/distribution to return only schema2.

>  How close are we to schema2 in master?

I'm fixing tests in https://github.com/openshift/origin/pull/8938

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: If we pass multiple accept headers (v2,v1) to the registry, will it
return the v2 version if it has it?

Comment (legionus) [inline pkg/image/importer/importer.go]: In addition, for backward compatibility our dockerregistry-2.4 will return scheme1 until the scheme2 is not explicitly allowed in the config.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: It's ok if we return scheme1 to clients since the image API can return
the newer data.

File: pkg/image/importer/importer.go (hunk 1 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: > I'm still concerned because each of those stats could fail, resulting in other failures. We probably *don't* want to fail import if size can't be calculated. We probably don't want to add a fan-out of 20 requests on setup. 

Yes, this is possible. We use NewRetryRepository to make few retries. But fix is necessary for the scheme1.

File: pkg/image/importer/importer.go (hunk 3 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: Yes, but i'm talking about importer and hub.docker.com. The server can return schema1 to use even if we support the scheme2.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: I think that's acceptable.  I don't think this issue is as severe as
originally stated.  The cost of doing all the stats outweighs the value,
especially if this is going to be less of a problem soon.

So in general, the only thing we need to fix right now is the tests, open a
follow up issue, and handle it there.

Comment (legionus) [inline pkg/image/importer/importer.go]: > I think that's acceptable. 

Our tests show that we had a regression after upgrading the hub.docker.com. But OK, you know better.

> this is going to be less of a problem soon.

It will be less of a problem only then when there will be no schema1 on the servers.

> we need to fix right now is the tests

I know that now is broken: `TestImageStreamImport`, `TestImageStreamImportDockerHub`, but there could be more.

Comment (legionus) [inline pkg/image/importer/importer.go]: I don't know how you can help upgrading the dockerregisrty. My PR is also affected by this issue.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: It is acceptable if in the master branch of Origin we explicitly call out that importing schema1 from the DockerHub (that have been down converted from schema2) will not have size set, because we anticipate this problem resolving itself by a) more images on the hub being schema2, b) we want to support schema2 import on the rebase.

I'll open a PR to disable the tests now and we can lower the priority.

Comment (legionus) [inline pkg/image/importer/importer.go]: > I'll open a PR to disable the tests now and we can lower the priority.

OK. Then I close this PR.

Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Opened test change in https://github.com/openshift/origin/pull/9118

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
@smarterclayton @soltysh I added caching for layer size.
What do you think about this solution ?

**Comment by legionus** [comment]
[test]

File: pkg/image/api/helper.go [hunk 4]
```diff
@@ -474,6 +474,8 @@ func ImageWithMetadata(image *Image) error {
 			image.DockerImageLayers[i].Name = layer.DockerBlobSum
 		}
 		if len(manifest.History) == len(image.DockerImageLayers) {
+			// This code does not work since hub.docker.com has been updated.
+			// The V1Compatibility no longer contains Size.
```
Comment (soltysh) [inline pkg/image/api/helper.go]: This will be true for docker hub, but for other repos supporting V1, it's not. I'd drop this comment entirely.

File: pkg/image/importer/importer.go [hunk 5]
```diff
@@ -299,9 +319,35 @@ func formatRepositoryError(repository *importRepository, refName string, refID s
...
+	size := int64(0)
+	for i := range image.DockerImageLayers {
+		layer := &image.DockerImageLayers[i]
+
+		if layerSize, ok := cache.LayerSizeCache[layer.Name]; ok {
+			size += layerSize
+			continue
+		}
+
+		desc, err := bs.Stat(ctx, digest.Digest(layer.Name))
```
Comment (soltysh) [inline pkg/image/importer/importer.go]: Before we start stat-ing, can we also check image manifest, schema v2 has a [Descriptor](https://github.com/openshift/origin/blob/128e499c9b5a7fb9a965234a23e40dc30f814d43/pkg/image/api/dockertypes.go#L60-L71) for [each layer](https://github.com/openshift/origin/blob/128e499c9b5a7fb9a965234a23e40dc30f814d43/pkg/image/api/dockertypes.go#L86), doesn't it contain reasonable values?

File: pkg/image/api/helper.go (hunk 4 above)
Comment (legionus) [inline pkg/image/api/helper.go]: This comment is valid for all v2 -> v1 conversions.

File: pkg/image/importer/importer.go (hunk 5 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: I have a check on the lack of size:
https://github.com/openshift/origin/pull/9115/files#diff-c85ad4ce0adaea09a2751949b944a92bR479
https://github.com/openshift/origin/pull/9115/files#diff-c85ad4ce0adaea09a2751949b944a92bR529

but I'll add an additional check of the size of each layer.

Comment (legionus) [inline pkg/image/importer/importer.go]: @soltysh Actually, I'm not sure this is right. The `calculateImageSize` is called after `ImageWithMetadata`. If after calling the `ImageWithMetadata`, the metadata size is zero, it means we can't trust the layers size and we have to use `Stat`.

File: pkg/image/api/helper.go (hunk 4 above)
Comment (soltysh) [inline pkg/image/api/helper.go]: Rephrase it in following way:
"This code does not work for images imported from v2 schema registries or converted from v2 to v1, since schema v2 does not contain size information."
Or something more appropriate, please.

Comment (legionus) [inline pkg/image/api/helper.go]: @soltysh Fixed

File: pkg/image/importer/importer.go (hunk 5 above)
Comment (soltysh) [inline pkg/image/importer/importer.go]: OK, I missed that one. Thanks!

**Comment by soltysh** [comment]
The changes itself looks good, but I won't let this in without tests. We're having too many problems with images to let any code in without at least simple unit test.

File: pkg/image/api/helper.go [hunk 6]
```diff
@@ -474,6 +474,9 @@ func ImageWithMetadata(image *Image) error {
 			image.DockerImageLayers[i].Name = layer.DockerBlobSum
 		}
 		if len(manifest.History) == len(image.DockerImageLayers) {
+			// This code does not work for images imported from v2 schema
+			// registries or converted from v2 to v1, since schema v2 does not
+			// contain size information.
```
Comment (miminar) [inline pkg/image/api/helper.go]: > since schema v2 does not contain size information.

It does, it's just hidden in layer descriptors. This information is lost during conversion to v1 though.

File: pkg/image/importer/importer.go [hunk 7]
```diff
@@ -65,6 +66,7 @@ func NewImageStreamImporter(retriever RepositoryRetriever, maximumTagsPerRepo in
 		limiter:   limiter,
 
 		digestToRepositoryCache: make(map[gocontext.Context]map[manifestKey]*api.Image),
+		digestToLayerSizeCache:  make(map[gocontext.Context]map[string]int64),
```
Comment (miminar) [inline pkg/image/importer/importer.go]: What's the purpose of grouping layer sizes per individual contexts? Context does not have any impact on `layer <-> size` mapping. Digest should have just one corresponding size.

File: pkg/image/api/helper.go (hunk 6 above)
Comment (soltysh) [inline pkg/image/api/helper.go]: So current comment is accurate.

Comment (miminar) [inline pkg/image/api/helper.go]: > So current comment is accurate.

It's not. Because schema v2 contains size information.

Comment (soltysh) [inline pkg/image/api/helper.go]: Agreed, the last part is wrong.

File: pkg/image/importer/importer.go [hunk 8]
```diff
@@ -50,6 +50,7 @@ type ImageStreamImporter struct {
 	limiter   flowcontrol.RateLimiter
 
 	digestToRepositoryCache map[gocontext.Context]map[manifestKey]*api.Image
+	digestToLayerSizeCache  map[gocontext.Context]map[string]int64
```
Comment (miminar) [inline pkg/image/importer/importer.go]: Please add a description for `string`.

File: pkg/image/importer/importer.go [hunk 9]
```diff
@@ -299,9 +319,35 @@ func formatRepositoryError(repository *importRepository, refName string, refID s
...
+		}
+
+		desc, err := bs.Stat(ctx, digest.Digest(layer.Name))
+		if err != nil {
+			return err
+		}
+
+		cache.LayerSizeCache[layer.Name] = desc.Size
+		layer.LayerSize = desc.Size
+		size += desc.Size
```
Comment (miminar) [inline pkg/image/importer/importer.go]: Exclude duplicate layers as in #9668.

Comment (legionus) [inline pkg/image/importer/importer.go]: It is done in line [329](https://github.com/openshift/origin/pull/9115#discussion-diff-69731090R329)

Comment (legionus) [inline pkg/image/importer/importer.go]: @miminar done

File: pkg/image/importer/importer.go (hunk 8 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: I added a description.

File: pkg/image/importer/importer.go (hunk 7 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: I removed the context.

File: pkg/image/importer/importer.go [hunk 10]
```diff
@@ -78,17 +82,28 @@ func (i *ImageStreamImporter) contextImageCache(ctx gocontext.Context) map[manif
 	return cache
 }
 
+type imageStreamImporterCache struct {
+	ImageCache     map[manifestKey]*api.Image
```
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: We already have digestToRepositoryCache, why do we need a second cache?

File: pkg/image/importer/importer.go [hunk 11]
```diff
@@ -78,17 +82,28 @@ func (i *ImageStreamImporter) contextImageCache(ctx gocontext.Context) map[manif
...
+	LayerSizeCache map[string]int64
+}
+
 // Import tries to complete the provided isi object with images loaded from remote registries.
 func (i *ImageStreamImporter) Import(ctx gocontext.Context, isi *api.ImageStreamImport) error {
-	cache := i.contextImageCache(ctx)
+	if i.digestToLayerSizeCache == nil {
```
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: This should be hidden inside of contextImageCache.  Initialize and return all your caches at once, don't do it at multiple layers.

File: pkg/image/importer/importer.go [hunk 12]
```diff
@@ -299,9 +314,41 @@ func formatRepositoryError(repository *importRepository, refName string, refID s
 	return
 }
 
+func calculateImageSize(ctx gocontext.Context, repo distribution.Repository, image *api.Image, cache *imageStreamImporterCache) error {
```
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Add Godoc indicating why this method is necessary, i.e. for v2 schemas converted to v1 which have no stat info.  Also include a description of what an error means (we couldn't calculate the sizes) and why we have to exit out, as opposed to continuing (because quota may be on).

File: test/integration/imageimporter_test.go [hunk 13]
```diff
@@ -103,18 +103,9 @@ func TestImageStreamImport(t *testing.T) {
 		t.Fatalf("unexpected responses: %v %#v %#v", err, isi, isi.Status.Import)
 	}
 
-	if isi.Status.Images[0].Image == nil || len(isi.Status.Images[0].Image.DockerImageLayers) == 0 {
+	if isi.Status.Images[0].Image == nil || isi.Status.Images[0].Image.DockerImageMetadata.Size == 0 || len(isi.Status.Images[0].Image.DockerImageLayers) == 0 {
```
Comment (smarterclayton) [inline test/integration/imageimporter_test.go]: Add another test that verifies that image size metadata is loaded for v2 manifests converted to v1 in the registry.

File: pkg/image/importer/importer.go [hunk 14]
```diff
@@ -50,6 +50,9 @@ type ImageStreamImporter struct {
 	limiter   flowcontrol.RateLimiter
 
 	digestToRepositoryCache map[gocontext.Context]map[manifestKey]*api.Image
+
+	// digestToLayerSizeCache maps layer digests to size.
+	digestToLayerSizeCache map[string]int64
```
Comment (miminar) [inline pkg/image/importer/importer.go]: Can we make it thread-safe. And let it be passed to `NewImageStreamImporter` so it can be shared among multiple importers invoked by image import controller?

File: pkg/image/importer/importer.go [hunk 15]
```diff
@@ -299,9 +305,41 @@ func formatRepositoryError(repository *importRepository, refName string, refID s
 	return
 }
 
+func (isi *ImageStreamImporter) calculateImageSize(ctx gocontext.Context, repo distribution.Repository, image *api.Image) error {
```
Comment (miminar) [inline pkg/image/importer/importer.go]: Please add a godoc explaining what it does and why it is needed.

File: test/integration/imageimporter_test.go [hunk 16]
```diff
@@ -993,3 +1121,67 @@ const phpManifest = `{
 }`
 
 const danglingDigest = `sha256:f374c0d9b59e6fdf9f8922d59e946b05fbeabaed70b0639d7b6b524f3299e87b`
+
+const convertDigest = `sha256:2a3b2f1a74f4351d1faf7ca48ea7f0ca97fad0801053fcf16df8474af6b89229`
+const convertedManifest = `{
```
Comment (miminar) [inline test/integration/imageimporter_test.go]: Make it match the name of manifest.

Comment (miminar) [inline test/integration/imageimporter_test.go]: Also make it clear that it's v2->v1 conversion (either reflect it in the name or godoc).

File: pkg/image/importer/importer.go (hunk 14 above)
Comment (legionus) [inline pkg/image/importer/importer.go]: I agree, but I think it should not be part of this PR.

File: test/integration/imageimporter_test.go [hunk 17]
```diff
@@ -183,6 +183,134 @@ func mockRegistryHandler(t *testing.T, requireAuth bool, count *int) http.Handle
...
+		if image.Image.Name != convertDigest {
+			t.Errorf("unexpected image %d: %#v (expect %q)", i, image.Image.Name, convertDigest)
+		}
+
+		// the image size is calculated
+		if image.Image.DockerImageMetadata.Size == 0 {
+			t.Errorf("unexpected image size %d: %#v", i, image.Image.DockerImageMetadata.Size)
+		}
+
+		if image.Image.DockerImageMetadata.Size != 3210 {
```
Comment (miminar) [inline test/integration/imageimporter_test.go]: Magic numbers.

File: test/integration/imageimporter_test.go [hunk 18]
```diff
@@ -183,6 +183,134 @@ func mockRegistryHandler(t *testing.T, requireAuth bool, count *int) http.Handle
...
+						w.Header().Set("Content-Length", fmt.Sprintf("%d", size))
+						w.Header().Set("Docker-Content-Digest", dgst)
+						w.WriteHeader(http.StatusOK)
+						countStat++
+						return
+					}
+				}
+			}
+			t.Fatalf("unexpected request %s: %#v", r.URL.Path, r)
+		}
```
Comment (miminar) [inline test/integration/imageimporter_test.go]: There's a high potential for sharing most of this handler's code with the other tests.

Comment (legionus) [inline test/integration/imageimporter_test.go]: It would make sense if there is another such test.

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by legionus** [comment]
[test]

**Comment by soltysh** [comment]
Flake from #9766.

File: pkg/image/importer/importer.go [hunk 19]
```diff
@@ -50,6 +50,9 @@ type ImageStreamImporter struct {
 	limiter   flowcontrol.RateLimiter
 
 	digestToRepositoryCache map[gocontext.Context]map[manifestKey]*api.Image
```
Comment (miminar) [inline pkg/image/importer/importer.go]: @smarterclayton Can you explain, why is it necessary to group the entries by context? Does the same scenario apply to the `digestToLayerSizeCache` below?

**Comment by soltysh** [comment]
LGTM, need @smarterclayton approval and answer @miminar question. Also please link an issue/PR addressing multithreaded access to the cache.

**Comment by miminar** [comment]
Created #9779 for a proper caching if this PR neglects it.

File: pkg/image/importer/importer.go (hunk 19 above)
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: Because access to an image may only be allowed given the credentials associated with your context.  So you cannot retry it.  It does not apply to digest to layer size.

File: pkg/image/importer/importer.go (hunk 14 above)
Comment (smarterclayton) [inline pkg/image/importer/importer.go]: If you're going to share it, then it needs to be an LRU.

File: test/integration/imageimporter_test.go (hunk 13 above)
Comment (smarterclayton) [inline test/integration/imageimporter_test.go]: Was the other test added?

Comment (smarterclayton) [inline test/integration/imageimporter_test.go]: If it's `TestImageStreamImportFromV2Repository` can you give it a more descriptive name `TestImageStreamImportOfV1ImageFromV2Repository`

Comment (legionus) [inline test/integration/imageimporter_test.go]: @smarterclayton Sure. Done.

**Comment by legionus** [comment]
@smarterclayton It's ready for merge ?

**Comment by soltysh** [comment]
I don't see any objections so merging.

[merge[
