### PR TITLE
test-cmd: Check for removed rc

### LINKED ISSUE #2342: hack/test-cmd flaking on deleting replication controllers
```
I0519 01:35:41.928006   12351 replication_controller.go:353] Replication Controller has been deleted default/docker-registry-1
error: Resizing the controller failed with: replicationControllers "docker-registry-1" not found; Current resource version Unknown
!!! Error in hack/test-cmd.sh:321
  'osc delete rc docker-registry-1' exited with status 1
Call stack:
  1: hack/test-cmd.sh:321 main(...)
```

### PR DESCRIPTION
**Pull request by kargakis**
Fixes #2342

### CODE REVIEW

**Comment by kargakis** [comment]
[test]

File: hack/test-cmd.sh [hunk 1]
```diff
@@ -308,7 +308,7 @@ osadm registry --create --credentials="${OPENSHIFTCONFIG}"
 # delete the registry resources
 osc delete dc docker-registry
 osc delete svc docker-registry
-osc delete rc docker-registry-1
+[ ! "$(osc get rc docker-registry-1)" ]
```
Comment (ncdc) [inline hack/test-cmd.sh]: Is there any way that this could flake, perhaps if there's a delay in the dc deletion cascading to delete the rc?

Comment (kargakis) [inline hack/test-cmd.sh]: Deleting the dc first deletes its replication controller and then deletes the config. Iff `osc delete dc docker-registry` fails to find the dc or fails to resize the replication controller then this will fail as well but these are corner cases are there are such in any command.

Comment (smarterclayton) [inline hack/test-cmd.sh]: If delete dc docker-registry leaves anything behind that's a bug in delete.

**Comment by smarterclayton** [comment]
LGTM [merge]
