### PR TITLE
Handle role binding AlreadyExists errors on project creation

### LINKED ISSUE #18982: [Feature:DeploymentConfig] deploymentconfigs won't deploy RC with unresolved images [Conformance] when patched with empty image
Sound slike a flake:
```
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:134
Expected error:
    <*errors.StatusError | 0xc420d413b0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},
            Status: "Failure",
            Message: "Internal error occurred: rolebindings.rbac.authorization.k8s.io \"system:image-pullers\" already exists",
            Reason: "InternalError",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "",
                        Message: "rolebindings.rbac.authorization.k8s.io \"system:image-pullers\" already exists",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
    Internal error occurred: rolebindings.rbac.authorization.k8s.io "system:image-pullers" already exists
not to have occurred
/tmp/openshift/build-rpms/rpm/BUILD/origin-3.10.0/_output/local/go/src/github.com/openshift/origin/vendor/k8s.io/kubernetes/test/e2e/framework/framework.go:190```

### PR DESCRIPTION
**Pull request by enj**
This change correctly allows AlreadyExists errors for the default role bindings during project creation (which is race between the API master and the default role binding controller).  However, it does
not generically ignore these errors.

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #18982
Alternative to #18994
/kind bug
/assign @simo5 @deads2k
@openshift/sig-master

### CODE REVIEW

File: pkg/project/registry/projectrequest/delegated/delegated.go [hunk 1]
```diff
@@ -82,6 +83,9 @@ var _ = rest.Creater(&REST{})
 var (
 	ForbiddenNames    = []string{"openshift", "kubernetes", "kube"}
 	ForbiddenPrefixes = []string{"openshift-", "kubernetes-", "kube-"}
+
+	defaultRoleBindingNames = bootstrappolicy.GetBootstrapServiceAccountProjectRoleBindingNames()
+	roleBindingKind         = rbac.Kind("RoleBinding")
```
Comment (deads2k) [inline pkg/project/registry/projectrequest/delegated/delegated.go]: template can be old enough that it's openshift groupified and openshift non-groupified too.

File: pkg/project/registry/projectrequest/delegated/delegated.go [hunk 2]
```diff
@@ -184,10 +188,10 @@ func (r *REST) Create(ctx apirequest.Context, obj runtime.Object, createValidati
...
 
 	// Stop on the first error, since we have to delete the whole project if any item in the template fails
-	stopOnErr := configcmd.AfterFunc(func(_ *resource.Info, err error) bool {
-		// if something already exists, we're probably racing a controller.  Don't die
-		if kapierror.IsAlreadyExists(err) {
-			return false
+	stopOnErr := configcmd.AfterFunc(func(info *resource.Info, err error) bool {
+		// if a default role binding already exists or is being created, we're probably racing the controller.  Don't die
+		if defaultRoleBindingNames.Has(info.Name) && info.Mapping.GroupVersionKind.GroupKind() == roleBindingKind {
+			return utilerrors.FilterOut(err, kapierror.IsAlreadyExists, kapierror.IsConflict) != nil
```
Comment (deads2k) [inline pkg/project/registry/projectrequest/delegated/delegated.go]: you'll never have a conflict on a create

**Comment by deads2k** [comment]
I don't really care.  If you want this, make sure that you get the type restrictions correct and I'm fine with it.  If you want the smaller one, you can choose to merge it instead.

File: pkg/project/registry/projectrequest/delegated/delegated.go (hunk 2 above)
Comment (enj) [reply pkg/project/registry/projectrequest/delegated/delegated.go]: Ah misread the failure cause in the logs, will remove.

File: pkg/project/registry/projectrequest/delegated/delegated.go (hunk 1 above)
Comment (enj) [reply pkg/project/registry/projectrequest/delegated/delegated.go]: OK

**Comment by enj** [comment]
> I don't really care. If you want this, make sure that you get the type restrictions correct and I'm fine with it. If you want the smaller one, you can choose to merge it instead.

I prefer the explicit, specific checks.  I updated the restrictions.

/retest

File: pkg/project/registry/projectrequest/delegated/delegated.go [hunk 3]
```diff
@@ -198,6 +202,10 @@ func (r *REST) Create(ctx apirequest.Context, obj runtime.Object, createValidati
 			ObjectTyper:  legacyscheme.Scheme,
 			ClientMapper: configcmd.ClientMapperFromConfig(r.restConfig),
 		},
+		IgnoreError: func(err error) bool {
```
[the remark this answers is not in the document]
Comment (soltysh) [reply pkg/project/registry/projectrequest/delegated/delegated.go]: :+1: the other code looks like a refactor.

**Comment by simo5** [comment]
I iwsh refactors and fixes were two separate commits, but I like to overall outcome
/lgtm
