### PR TITLE
Perform live OAuth client check only if scopes were added to the client authorization

### LINKED ISSUE #15007: Failure trying to storage migrate some oauthclientauthorizations
Saw this on 319 oauthclientauthorizations in a migration of a 3.5 prod data set to 3.6 in #14999 

```
error:      oauthclientauthorizations/XXX:system:serviceaccount:XXX:jenkins: OAuthClientAuthorization "XXX:system:serviceaccount:XXX:jenkins" is invalid: clientName: Internal error: serviceaccounts "jenkins" not found
```

This is a migrate, so blind GET then UPDATE, and since i'm not modifying the client, I wouldn't expect this to fail.  Marking this P1 so it gets triaged prior to the 3.6 prod update.

@jupierce @openshift/security

### PR DESCRIPTION
**Pull request by enj**
This change makes it so that `OAuthClientAuthorization` update validation only does a live OAuth client check to validate scopes if new scopes were added to the client authorization.  If the scopes were unchanged or only removed (removal of all scopes is considered an addition since an empty slice means all scopes), than no live lookup is performed under the assumption that the create method did a successful live lookup at some earlier point.  This makes it so that an update to a client authorization with identical data (for example, during storage migration) will not fail if the referenced client is no longer valid or has been deleted.

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #15007 

xref: https://github.com/openshift/origin/issues/15007#issuecomment-314310463

> issue was with lookup of OAuth client in order to validate scopes. we only need to do this if scopes are being added to the authorization. @enj will make the lookup conditional

[test]

@jupierce @openshift/security 

@liggitt PTAL

### CODE REVIEW

**Comment by smarterclayton** [comment]
[severity:blocker]

**Comment by smarterclayton** [comment]
xref #14999

**Comment by liggitt** [comment]
LGTM

**Comment by mrogers950** [comment]
LGTM.

**Comment by abstractj** [comment]
:+1:

**Comment by smarterclayton** [comment]
[test]

File: pkg/oauth/registry/oauthclientauthorization/strategy.go [hunk 1]
```diff
@@ -79,17 +80,33 @@ func (s strategy) ValidateUpdate(ctx apirequest.Context, obj runtime.Object, old
...
+	// an empty slice of scopes means all scopes, so we consider that a new scope
+	newHasAllScopes := len(obj) == 0
+	oldHasAllScopes := len(old) == 0
+	if newHasAllScopes && !oldHasAllScopes {
+		return true
+	}
+
+	newScopes := sets.NewString(obj...)
+	oldScopes := sets.NewString(old...)
+	return len(newScopes.Difference(oldScopes)) > 0
```
Comment (php-coder) [inline pkg/oauth/registry/oauthclientauthorization/strategy.go]: (I'm not sure but) why not use `oldScopes.IsSuperset(newScopes)` instead? It won't collect the items that we don't need anyway.
