### PR TITLE
Prune image configs of manifest V2 schema 2

### LINKED ISSUE #10375: Extended.[images] openshift limit range admission should deny a push of built image exceeding limit on openshift.io/images resource
```
[Fail] [images] openshift limit range admission [It] should deny a push of built image exceeding openshift.io/Image limit 
/data/src/github.com/openshift/origin/test/extended/images/helper.go:148

[Fail] [images] openshift limit range admission [It] should deny a push of built image exceeding limit on openshift.io/images resource 
/data/src/github.com/openshift/origin/test/extended/images/helper.go:148
```

https://ci.openshift.redhat.com/jenkins/job/origin_extended_image_tests/395/consoleFull

Please fix or disable this test asap, it's getting run in the image bucket and causing that bucket to report failure.

### PR DESCRIPTION
**Pull request by miminar**
A follow-up for #10805.

Resolves #10375

### CODE REVIEW

**Comment by miminar** [comment]
I'm working on extended test now. Otherwise ready for review. /cc @soltysh, @legionus 

[test]

File: pkg/image/prune/prune.go [hunk 1]
```diff
@@ -39,8 +39,12 @@ const (
...
 	WeakReferencedImageEdgeKind = "WeakReferencedImage"
 
+	// ReferencedImageConfigEdgeKind defines an edge from an ImageStreamNode or an
+	// ImageNode to an ImageComponentNode.
+	ReferencedImageConfigEdgeKind = "ReferencedImageConfig"
+
 	// ReferencedImageLayerEdgeKind defines an edge from an ImageStreamNode or an
-	// ImageNode to an ImageLayerNode.
+	// ImageNode to an ImageComponentNode.
 	ReferencedImageLayerEdgeKind = "ReferencedImageLayer"
```
Comment (soltysh) [inline pkg/image/prune/prune.go]: If you're replacing all, this should be renamed to `ReferencedImageComponent`, right?

Comment (soltysh) [inline pkg/image/prune/prune.go]: Actually on second thought, you renamed the `ImageLayerNode` in the comment unnecessarily.

File: pkg/image/graph/nodes/nodes.go [hunk 2]
```diff
@@ -161,12 +161,27 @@ func FindOrCreateSyntheticImageStreamNode(g osgraph.MutableUniqueGraph, is *imag
 	).(*ImageStreamNode)
 }
 
-// EnsureImageLayerNode adds a graph node for the layer if it does not already exist.
-func EnsureImageLayerNode(g osgraph.MutableUniqueGraph, layer string) graph.Node {
-	return osgraph.EnsureUnique(g,
-		ImageLayerNodeName(layer),
+// EnsureImageComponentNode adds a graph node for the image config or layer if it does not already exist.
+func EnsureImageComponentNode(g osgraph.MutableUniqueGraph, name string, t ImageComponentType) graph.Node {
```
Comment (soltysh) [inline pkg/image/graph/nodes/nodes.go]: I think it would be better to actually have two methods `EnsureImageLayerNode` and `EnsumreImageConfigNode` rather than single with over-bloated list of parameters and unnecessarily revealing internal implementation details.

File: pkg/image/prune/prune.go [hunk 3]
```diff
@@ -799,13 +823,14 @@ func (p *pruner) Prune(imagePruner ImageDeleter, streamPruner ImageStreamDeleter
 
 	prunableImageNodes, prunableImageIDs := calculatePrunableImages(p.g, imageNodes)
 	graphWithoutPrunableImages := subgraphWithoutPrunableImages(p.g, prunableImageIDs)
-	prunableLayers := calculatePrunableLayers(graphWithoutPrunableImages)
+	prunableConfigs, prunableLayers := calculatePrunableImageComponents(graphWithoutPrunableImages)
```
Comment (soltysh) [inline pkg/image/prune/prune.go]: I'm not sure why you need to separate lists if both are deleted in exactly the same list.

File: pkg/image/prune/prune.go (hunk 1 above)
Comment (miminar) [inline pkg/image/prune/prune.go]: Well, I'm differentiating whether the image refers to the component as its *layer* or as its *config*. I'm using different edges for both cases. The edges don't serve any purpose later on. So instead of two, we could have just one `ReferencedImageComponent`, as you suggest. I kind of like the differentiation though.

File: pkg/image/graph/nodes/nodes.go (hunk 2 above)
Comment (miminar) [inline pkg/image/graph/nodes/nodes.go]: The reason why I have merged both cases into single component is that theoretically, the same blob may be referred by an image as a config and by another image as a layer. The both cases need to be represented as a single node in the graph. Otherwise, they would be pruned separately - first as a config, second as a layer. The second prune would fail naturally.

We could keep them separated with different nodes but we'd have to make sure not to delete them twice.

File: pkg/image/prune/prune.go (hunk 3 above)
Comment (miminar) [inline pkg/image/prune/prune.go]: > I'm not sure why you need to separate lists if both are deleted in exactly the same list.

Originally I wanted to separate deletion of configs from deletion of layers to make it appear nice in the output. But in the end, I don't think it will make the output more readable. There's enough sections being produced already. Adding  a new section `Image Configs` exposes unnecessary details.

File: pkg/image/prune/prune.go (hunk 1 above)
Comment (soltysh) [inline pkg/image/prune/prune.go]: I don't mind the differentiation. The first comment was too quick, I've later noticed you've renamed the variable in the comment but all the rest is left. I'm just saying one should reflect the other.

File: pkg/image/graph/nodes/nodes.go (hunk 2 above)
Comment (soltysh) [inline pkg/image/graph/nodes/nodes.go]: The reasoning is perfectly fine, I'm just saying that you'll end up calling the method twice either way, one for the config and again for the layer. It's the internal logic that has to deal with it properly. Or am I missing something here?

**Comment by soltysh** [comment]
In the end I'm still wondering if having the separation between layers and configs worth the trouble. They both end up being treated in the same way, we just need to make sure when adding config to the graph not to added if a layer was already added, right?

File: pkg/image/graph/nodes/nodes.go (hunk 2 above)
Comment (miminar) [inline pkg/image/graph/nodes/nodes.go]: > The reasoning is perfectly fine, I'm just saying that you'll end up calling the method twice either way, one for the config and again for the layer. It's the internal logic that has to deal with it properly. Or am I missing something here?

I see your point. Yes, having two separate functions instead of one makes sense.

**Comment by miminar** [comment]
> In the end I'm still wondering if having the separation between layers and configs worth the trouble. They both end up being treated in the same way, we just need to make sure when adding config to the graph not to added if a layer was already added, right?

For debugging purposes, I'd like to know whether the digest being deleted is a layer or a config. Also in the future, we might prefer to keep the configs only in etcd. Keeping some level of separation now will make it easier.

**Comment by miminar** [comment]
Added extended test.

**Comment by miminar** [comment]
[testextended][extended:core(images)][extended:core(builds)][extended:core(imageapis)]

File: test/extended/util/framework.go [hunk 4]
```diff
@@ -607,6 +608,42 @@ var CheckImageStreamTagNotFoundFn = func(i *imageapi.ImageStream) bool {
 		strings.Contains(i.Annotations[imageapi.DockerImageRepositoryCheckAnnotation], "error")
 }
 
+// cmpResourceControllerNames compares names of two resource controllers. It returns:
+//  -1 if rc a is older than b
+//   1 if rc a is newer than b
+//   0 if their names are the same
+func cmpResourceControllerNames(a, b string) int {
```
Comment (soltysh) [inline test/extended/util/framework.go]: Use full names `compareResourceControllerNames`

File: test/extended/util/framework.go [hunk 5]
```diff
@@ -870,6 +965,20 @@ var CheckPodIsSucceededFn = func(pod kapi.Pod) bool {
 	return pod.Status.Phase == kapi.PodSucceeded
 }
 
+// CheckPodIsReadyFn returns true if the pod's ready probe determined that the pod is ready.
+var CheckPodIsReadyFn = func(pod kapi.Pod) bool {
```
Comment (soltysh) [inline test/extended/util/framework.go]: Can this be a regular function, like:
```
func CheckPodIsReadyFn(pod kapi.Pod) bool {
...
```
why this construct?

File: test/extended/images/prune.go [hunk 6]
```diff
@@ -0,0 +1,261 @@
...
+	tearDown := func(cleanUp *cleanUpContainer) {
+		for _, image := range cleanUp.imageNames {
+			err := oc.AsAdmin().REST().Images().Delete(image)
+			if err != nil {
+				fmt.Fprintf(g.GinkgoWriter, "clean up of image %q failed: %v\n", image, err)
+			}
+		}
+	}
+
+	testPruneImagesOfSchema := func(version int) {
```
Comment (soltysh) [inline test/extended/images/prune.go]: Turn this into regular function as well.

File: test/extended/images/prune.go [hunk 7]
```diff
@@ -0,0 +1,261 @@
...
+
+		err := exutil.WaitForBuilderAccount(oc.KubeREST().ServiceAccounts(oc.Namespace()))
+		o.Expect(err).NotTo(o.HaveOccurred())
+
+		g.By(fmt.Sprintf("give a user %s a right to prune images with %s role", oc.Username(), "system:image-pruner"))
+		err = oc.AsAdmin().Run("adm").Args("policy", "add-cluster-role-to-user", "system:image-pruner", oc.Username()).Execute()
+		o.Expect(err).NotTo(o.HaveOccurred())
+	})
+
+	tearDown := func(cleanUp *cleanUpContainer) {
```
Comment (soltysh) [inline test/extended/images/prune.go]: Same - regular function.

File: test/extended/images/prune.go [hunk 8]
```diff
@@ -0,0 +1,261 @@
...
+
+func doesRegistryAcceptSchema2(oc *exutil.CLI) (bool, error) {
+	ns := oc.Namespace()
+	defer oc.SetNamespace(ns)
+	env, err := oc.SetNamespace(kapi.NamespaceDefault).AsAdmin().Run("env").Args("dc/docker-registry", "--list").Output()
+	if err != nil {
+		return false, err
+	}
+
+	return strings.Contains(env, "REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true"), nil
```
Comment (soltysh) [inline test/extended/images/prune.go]: Can you use a constant here?

Comment (soltysh) [inline test/extended/images/prune.go]: I'm talking about this https://github.com/openshift/origin/blob/aa08313961b117b323d6c04c56409882072043fd/pkg/dockerregistry/server/repositorymiddleware.go#L51

File: test/extended/images/prune.go [hunk 9]
```diff
@@ -0,0 +1,261 @@
...
+func ensureRegistryAcceptsSchema2(oc *exutil.CLI, accept bool) error {
+	ns := oc.Namespace()
+	oc = oc.SetNamespace(kapi.NamespaceDefault).AsAdmin()
+	defer oc.SetNamespace(ns)
+	env, err := oc.Run("env").Args("dc/docker-registry", "--list").Output()
+	if err != nil {
+		return err
+	}
+
+	value := fmt.Sprintf("REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=%t", accept)
```
Comment (soltysh) [inline test/extended/images/prune.go]: Same env, please.

File: test/extended/images/prune.go [hunk 10]
```diff
@@ -0,0 +1,261 @@
...
+		return false, err
+	}
+
+	return strings.Contains(env, "REGISTRY_MIDDLEWARE_REPOSITORY_OPENSHIFT_ACCEPTSCHEMA2=true"), nil
+}
+
+// ensureRegistryAcceptsSchema2 checks whether the registry is configured to accept manifests V2 schema 2 or
+// not. If the result doesn't match given accept argument, registry's deployment config is updated accordingly
+// and the function blocks until the registry is re-deployed and ready for new requests.
+func ensureRegistryAcceptsSchema2(oc *exutil.CLI, accept bool) error {
```
Comment (soltysh) [inline test/extended/images/prune.go]: The only worry I have here, is that we might leave the registry in a state different than at the beginning, you are aware that this might influence other tests in the future? How about reverting it back to is original?

File: test/extended/util/framework.go (hunk 5 above)
Comment (miminar) [inline test/extended/util/framework.go]: It could, I'm just following a convention used to define other callback function defined in this file. See https://github.com/openshift/origin/blob/313c88ce55f3f109e2d8c9d4dd87fcd750e16eda/test/extended/util/framework.go#L964, https://github.com/openshift/origin/blob/313c88ce55f3f109e2d8c9d4dd87fcd750e16eda/test/extended/util/framework.go#L492, https://github.com/openshift/origin/blob/313c88ce55f3f109e2d8c9d4dd87fcd750e16eda/test/extended/util/framework.go#L600 as examples. I'm not really sure why, but I'd rather stay consistent.

File: test/extended/images/prune.go (hunk 8 above)
Comment (miminar) [inline test/extended/images/prune.go]: Sure, I'll use the constant.

File: test/extended/images/prune.go (hunk 10 above)
Comment (miminar) [inline test/extended/images/prune.go]: See https://github.com/openshift/origin/blob/313c88ce55f3f109e2d8c9d4dd87fcd750e16eda/test/extended/images/prune.go#L170 and https://github.com/openshift/origin/blob/313c88ce55f3f109e2d8c9d4dd87fcd750e16eda/test/extended/images/prune.go#L189.

**Comment by miminar** [comment]
>  I've left some comments, mind addressing them?

Of course! Always a pleasure.

File: test/extended/util/framework.go (hunk 4 above)
Comment (miminar) [inline test/extended/util/framework.go]: Renamed.

File: test/extended/images/prune.go (hunk 7 above)
Comment (miminar) [inline test/extended/images/prune.go]: Done.

File: test/extended/util/framework.go (hunk 5 above)
Comment (soltysh) [inline test/extended/util/framework.go]: Ok

**Comment by miminar** [comment]
Flake #10987

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
[merge]

**Comment by soltysh** [comment]
Flake #11079.

[merge]

**Comment by miminar** [comment]
@soltysh you made it happen! :fireworks: :tada:

Sorry for the pain.

**Comment by soltysh** [comment]
party
