### PR TITLE
[#5182] Improve generation of name based on a git repo url to make it valid

### LINKED ISSUE #5182: oc new-app chooses invalid name
I get this error:

```
[deads@main origin]$ oc new-app https://github.com/deads2k/Emby.Build --context-dir=Docker
ImageStream "baseimage" created
ImageStream "emby.build" created
BuildConfig "emby.build" created
error: DeploymentConfig "emby.build" is invalid: template.controllerTemplate.template.spec.containers[0].name: invalid value 'emby.build': must be a DNS label (at most 63 characters, matching regex [a-z0-9]([-a-z0-9]*[a-z0-9])?): e.g. "my-name"
Service "embybuild" created
```

You're choosing a name for me, don't choose one that doesn't work.

@bparees @csrwng

### PR DESCRIPTION
**Pull request by php-coder**
@bparees @mfojtik PTAL. I'm going to write unit tests after yours approval if this fix is correct (I've tested it and it works, but may be we should fix it somewhere else?)

Additional idea:  may be we should replace invalid characters by hyphen instead of space (and `amby.build` becomes to `amby-build` instead of `ambybuild`) WDYT?

Fixes #5182

### CODE REVIEW

File: pkg/generate/app/app.go [hunk 1]
```diff
@@ -26,9 +27,12 @@ import (
 )
 
 const (
-	volumeNameInfix = "volume"
+	volumeNameInfix       = "volume"
+	invalidNameCharacters = "[^-a-z0-9]" // the opposite of kvalidation.DNS1123LabelFmt
 )
 
+var invalidNameCharactersRegexp = regexp.MustCompile(invalidNameCharacters)
```
Comment (mfojtik) [inline pkg/generate/app/app.go]: just write the regexp string here :-) no need for constant

File: pkg/generate/app/app.go [hunk 2]
```diff
@@ -81,6 +85,28 @@ func nameFromGitURL(url *url.URL) (string, bool) {
 	}
 	// from path
 	if name, ok := git.NameFromRepositoryURL(url); ok {
+
+		if !kvalidation.IsDNS1123Label(name) {
+			name = strings.ToLower(name)
+
+			// remove everything except [-0-9a-z]
+			name = invalidNameCharactersRegexp.ReplaceAllString(name, "")
```
Comment (smarterclayton) [inline pkg/generate/app/app.go]: There should be a function somewhere else that already does this, if not it would be better to have it in one common place in generation.  However, I'm not totally sure that this belongs down at this level.  The code that uses the name suggestion should probably apply this logic, instead of within this segment.

File: pkg/generate/app/app.go (hunk 1 above)
Comment (php-coder) [inline pkg/generate/app/app.go]: Fixed, thanks.

File: pkg/generate/app/app.go (hunk 2 above)
Comment (bparees) [inline pkg/generate/app/app.go]: why shouldn't a name suggester suggest valid names?  suggesting a name that the consumer then has to further modify seems odd to me.

Comment (bparees) [inline pkg/generate/app/app.go]: i agree that this logic should be a function (CovertToDNS1123Label or some such thing)

Comment (smarterclayton) [inline pkg/generate/app/app.go]: Name suggester does not know the context under which it is used.  It's
inappropriate for NameSuggester have to be aware of the LCD of names.
Instead, suggestions have to be resolved to a context.

Comment (bparees) [inline pkg/generate/app/app.go]: is the NameSuggester implementation was actually named DNS123NameSuggester it would be ok to do it this way and that would be more sane imho than invoking a suggester and then having to go change the name it suggests.

Comment (php-coder) [inline pkg/generate/app/app.go]: >There should be a function somewhere else that already does this ...

@smarterclayton Yes, I've found it and moved checks to that method (some of them already was there).

But. In this method, when we are checking for a max length, we are using `kvalidation.DNS1123SubdomainMaxLength` (= 253) but I believe that we should use `kvalidation.DNS1123LabelMaxLength` (= 63), because the latter will be used for name validation (see original error message). Would you mind if I update this check?

File: pkg/generate/app/cmd/newapp_test.go [hunk 3]
```diff
@@ -1265,6 +1265,11 @@ func TestEnsureValidUniqueName(t *testing.T) {
 			expected: []string{"one", "one-1", "two"},
 		},
 		{
+			name:     "non-standart characters",
```
Comment (bparees) [inline pkg/generate/app/cmd/newapp_test.go]: standard

File: pkg/generate/app/cmd/newapp_test.go [hunk 4]
```diff
@@ -1265,6 +1265,11 @@ func TestEnsureValidUniqueName(t *testing.T) {
...
+			input:    []string{"Emby.One", "test-_test", "_-_"},
+			expected: []string{"embyone", "test-test", ""},
```
Comment (bparees) [inline pkg/generate/app/cmd/newapp_test.go]: add a test case for your prefix hyphen case ("@-MyRepo")

**Comment by bparees** [comment]
2 nits and lgtm.

File: pkg/generate/app/cmd/newapp_test.go (hunk 4 above)
Comment (php-coder) [inline pkg/generate/app/cmd/newapp_test.go]: Is it possible to have repo on GitHub with `@-MyRepo` name? Or it's not only for GitHub repositories?

File: pkg/generate/app/cmd/newapp_test.go (hunk 3 above)
Comment (php-coder) [inline pkg/generate/app/cmd/newapp_test.go]: Thanks, fixed.

File: pkg/generate/app/cmd/newapp_test.go (hunk 4 above)
Comment (bparees) [inline pkg/generate/app/cmd/newapp_test.go]: not sure what's valid, I'm just suggesting having a test case that will validate your "strip the dash if the regex leaves the name prefixed with a dash" logic.

**Comment by bparees** [comment]
needs a rebase

**Comment by php-coder** [comment]
@bparees Ok, done.

File: pkg/generate/app/cmd/newapp.go [hunk 5]
```diff
@@ -587,14 +591,23 @@ func ensureValidUniqueName(names map[string]int, name string) (string, error) {
...
 	}
+
+	// Make all names lowercase
+	name = strings.ToLower(name)
+
+	// Remove everything except [-0-9a-z]
+	name = invalidNameCharactersRegexp.ReplaceAllString(name, "")
+
+	// Remove leading hyphen (that may be introduced by the previous step)
+	if strings.HasPrefix(name, "-") {
```
Comment (mfojtik) [inline pkg/generate/app/cmd/newapp.go]: this if is unnecessary, just TrimLeft, if there is no "-" character on left side, it will be no-op.

**Comment by mfojtik** [comment]
one small nit and LGTM

File: pkg/generate/app/cmd/newapp.go (hunk 5 above)
Comment (php-coder) [inline pkg/generate/app/cmd/newapp.go]: @mfojtik Thanks, fixed now.

**Comment by bparees** [comment]
i'm still not seeing a test case for the dash-prefix logic.

**Comment by bparees** [comment]
nm, misread the array. i see it now.

**Comment by bparees** [comment]
[merge]
