### PR TITLE
Use service port name as route targetPort in 'oc expose service'

### LINKED ISSUE #6265: using targetPort with a name in service definition doesn't seem to work via route
Using `targetPort` in the service definition to map to a named port in a pod definition doesn't seem to work. Everything looks like it works and the web interface even has `80/TCP → apacheport` in the display, but I can never establish a connection. If I instead use `targetPort : 8080` in openshift it works. Mapping to a name works in kubernetes-1.1.0-0.17.git388061f.fc23.x86_64 so I think I'm not doing something wrong, but I can't be sure. My target ose environment is 3.1.

Example Pod
```
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "labels": {
            "app": "helloapache"
        },
        "name": "helloapache"
    },
    "spec": {
        "containers": [
            {
                "image": "dustymabe/httpd:latest",
                "name": "helloapache",
                "ports": [
                    {
                        "name": "apacheport",
                        "containerPort": 8080,
                        "protocol": "TCP"
                    }
                ]
            }
        ]
    }
}
```

Example service
```
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "labels": {
            "name": "apacheservice"
        },
        "name": "apacheservice"
    },
    "spec": {
        "ports": [
            {
                "port": 80,
                "targetPort": "apacheport"
            }
        ],
        "selector": {
            "app": "helloapache"
        },
        "type": "LoadBalancer"
    }
}
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #6265

There are 6 possible scenarios for services with ports we will hit in `oc expose`
1. 1 unnamed service port -> numbered container port
2. 1 unnamed service port -> named container port
3. 1 named service port -> numbered container port
4. 1 named service port -> named container port
5. 2+ named service ports -> numbered container port
6. 2+ named service ports -> named container port

Whenever a service port is named (cases 3,4,5,6), we should use the name as the route targetPort

When a service port is unnamed (which means it is the only port), we could try to set a targetPort that will point to the right containers, or we could omit the targetPort and let the route "round-robin" to the single port. In case 1 (numbered container port), we could set a numbered targetPort, but the route would break if the service was edited to set a different targetPort. In case 2 (named container port), we have no choice but to round-robin (container port names aren't available in the endpoints).

This PR updates `oc expose service <svc>` to generate a route that has a named targetPort when possible, and no targetPort otherwise.

### CODE REVIEW

**Comment by liggitt** [comment]
@kargakis PTAL

**Comment by liggitt** [comment]
[test]

File: pkg/cmd/cli/cmd/expose.go [hunk 1]
```diff
@@ -119,8 +119,13 @@ func validate(cmd *cobra.Command, f *clientcmd.Factory, args []string) error {
...
 			for _, port := range svc.Spec.Ports {
 				if port.Protocol == kapi.ProtocolTCP {
-					// Pass service target port as the route port
-					cmd.Flags().Set("port", port.TargetPort.String())
+					if len(port.Name) > 0 {
+						// Pass service port name as the route target port, if it is named
+						cmd.Flags().Set("port", port.Name)
+					} else {
+						// Otherwise, omit the targetPort from the route and let it round-robin the one service port
+						cmd.Flags().Set("omit-target-port", "true")
```
Comment (liggitt) [inline pkg/cmd/cli/cmd/expose.go]: ugly, I don't see a better way to explicitly tell the route generator we want it to leave out the port

Comment (kargakis) [inline pkg/cmd/cli/cmd/expose.go]: Can we decide on using port vs target-port as the name of the parameter (and subsequently the name of the flag for setting the route port)? I think the intention is to use target-port. Then we will not require portString to not be zero in the generator, instead of introducing another field to explicitly pass info.

Comment (liggitt) [inline pkg/cmd/cli/cmd/expose.go]: I think I agree

**Comment by kargakis** [comment]
You also need to update ParamsNames to include `target-port` (and drop `port` and `ports`)

**Comment by kargakis** [comment]
> You also need to update ParamsNames to include target-port (and drop port and ports)

And then update the unit tests for the route generator

**Comment by liggitt** [comment]
updated tests and cmd tests

File: test/cmd/basicresources.sh [hunk 2]
```diff
@@ -68,7 +68,8 @@ os::cmd::expect_success 'oc create -f test/integration/fixtures/test-service.jso
 os::cmd::expect_failure 'oc expose service frontend --create-external-load-balancer'
 os::cmd::expect_failure 'oc expose service frontend --port=40 --type=NodePort'
 os::cmd::expect_success 'oc expose service frontend'
-os::cmd::expect_success_and_text 'oc get route frontend' 'name=frontend'
+os::cmd::expect_success_and_text "oc get route frontend --output-version=v1 --template='{{.spec.to.name}}'" "frontend"           # routes to correct service
+os::cmd::expect_success_and_text "oc get route frontend --output-version=v1 --template='{{.spec.port.targetPort}}'" "<no value>" # no target port for services with unnamed ports
```
Comment (kargakis) [inline test/cmd/basicresources.sh]: Is this `<no value>` what is really returned?

**Comment by kargakis** [comment]
A question, LGTM in general

**Comment by liggitt** [comment]
that's what template rendering returns when you reference something that doesn't exist in the struct

**Comment by kargakis** [comment]
```
The command '/bin/sh -c yum install -y libmnl libnetfilter_conntrack openvswitch     libnfnetlink iptables iproute bridge-utils procps-ng ethtool socat openssl     binutils xz kmod-libs kmod sysvinit-tools device-mapper-libs dbus     && yum clean all' returned a non-zero code: 1
!!! Error in hack/build-images.sh:62
	'docker build -t $1:latest $2' exited with status 1
Call stack:
	1: hack/build-images.sh:62 image(...)
	2: hack/build-images.sh:81 main(...)
Exiting with status 1
make: *** [release] Error 1
```
[merge]

@liggitt thanks for this

**Comment by kargakis** [comment]
https://github.com/openshift/origin/issues/6312 flake

[merge]
