### PR TITLE
Fix race of Kubelet vs SDN on node startup

### LINKED ISSUE #2655: SDN conflicts with node self-registration
When configuring a previously unregistered node with the sdn plugin enabled, the openshift-node process times out waiting for an assigned sdn subnet.

The node should attempt to self-register before initializing the sdn plugin, or at least not fail to reach the self-registration step before failing when an sdn subnet is not present.

### PR DESCRIPTION
**Pull request by smarterclayton**
Fixes #2655

### CODE REVIEW

File: pkg/cmd/server/start/start_node.go [hunk 1]
```diff
@@ -225,17 +226,17 @@ func (o NodeOptions) CreateNodeConfig() error {
...
-			glog.Fatal("Failed to get kube client for SDN")
-		}
 		oclient, _, err := configapi.GetOpenShiftClient(config.MasterKubeConfig)
 		if err != nil {
 			glog.Fatal("Failed to get kube client for SDN")
 		}
-		osdn.Node(*oclient, *kclient, config.NodeName, "")
+		ch := make(chan struct{})
+		nodeConfig.KubeletConfig.StartUpdates = ch
+		go osdn.Node(oclient, nodeConfig.Client, config.NodeName, "", ch)
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: why use the node config's client instead of getting our own?

File: pkg/cmd/server/start/start_node.go [hunk 2]
```diff
@@ -225,17 +226,17 @@ func (o NodeOptions) CreateNodeConfig() error {
...
+		// no plugin necessary
+		nodeConfig.KubeletConfig.NetworkPluginName = ""
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: mutating inside here isn't great... means controller order startup can do weird things... can we conditionally set this in BuildKubernetesNodeConfig?

File: pkg/cmd/server/start/start_node.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: They're different?

File: pkg/cmd/server/start/start_node.go [hunk 3]
```diff
@@ -225,17 +226,17 @@ func (o NodeOptions) CreateNodeConfig() error {
 	return nil
 }
 
-func RunSDNController(config configapi.NodeConfig) {
+func RunSDNController(config configapi.NodeConfig, nodeConfig *kubernetes.NodeConfig) {
```
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: also, best arg names ever :)
use the config. the node config? no, the node config.

Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: I try.

----- Original Message -----

File: pkg/cmd/server/start/start_node.go (hunk 2 above)
Comment (rajatchopra) [inline pkg/cmd/server/start/start_node.go]: This line is wrong.. it breaks the SDN. Why do you think we do not need the plugin now?

**Comment by rajatchopra** [comment]
Except the 'wrong' disabling of networkPluginName in [here](https://github.com/openshift/origin/pull/2984#discussion-diff-31981409R238), I have tested the code and it all seems to work.

 - The nodes get registered alright, and kubelet does not start watching for pods (or even listening to its 10250 port) before the SDN is ready. 
 - Restarting the pods renews the SDN leases and rules, but pods come back up right after docker is good. The IPs of the pods change but services pick them up correctly too. 
 - After several restarts of the kubelet, the pods still serve alright and get deleted properly. New pods get created fine too after multiple restarts.

File: pkg/cmd/server/start/start_node.go (hunk 2 above)
Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: The Kubelet does not have your plugin registered and so it fails to start.  My understanding was that you were programming the bridge so you didn't need a plugin?  Where is your plugin code registered.

----- Original Message -----

File: pkg/cmd/server/start/start_allinone.go [hunk 4]
```diff
@@ -224,6 +224,7 @@ func (o AllInOneOptions) StartAllInOne() error {
 	}
 
 	masterOptions := MasterOptions{o.MasterArgs, o.CreateCerts, o.MasterConfigFile, o.Output}
+	masterOptions.MasterArgs.NetworkArgs.NetworkPluginName = o.NodeArgs.NetworkPluginName
```
Comment (liggitt) [inline pkg/cmd/server/start/start_allinone.go]: do this in `AllInOneOptions#Complete`

File: pkg/cmd/server/start/start_node.go (hunk 2 above)
Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: @rajatchopra rajat, https://github.com/openshift/origin/pull/2984/files#diff-ef4c2b4de3a6a004d532acc3fccf5779R210 set the plugin in the nodeConfig... @smarterclayton is there a better way to plumb it through?

Comment (liggitt) [inline pkg/cmd/server/start/start_node.go]: nm, that line was fixing a bug where the arg wasn't persisted when --write-config was used

Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: This is ready for a second try - it preserves the plugin name, moves the systemd ready notification to the options.Start* methods, and ensures the kubelet is run in a goroutine so as to not block start.

----- Original Message -----

File: pkg/cmd/server/start/start_master.go [hunk 5]
```diff
@@ -169,6 +169,7 @@ func (o MasterOptions) StartMaster() error {
 		return nil
 	}
 
+	go daemon.SdNotify("READY=1")
```
Comment (liggitt) [inline pkg/cmd/server/start/start_master.go]: pretty sure allinone doesn't hit this path

File: pkg/cmd/server/start/start_node.go [hunk 6]
```diff
@@ -225,18 +227,18 @@ func (o NodeOptions) CreateNodeConfig() error {
...
+		return
 	}
+
+	oclient, _, err := configapi.GetOpenShiftClient(clientConfigFile)
+	if err != nil {
+		glog.Fatal("Failed to get kube client for SDN")
+	}
+	ch := make(chan struct{})
+	config.KubeletConfig.StartUpdates = ch
+	go osdn.Node(oclient, config.Client, config.KubeletConfig.Hostname, "", ch)
```
Comment (rajatchopra) [inline pkg/cmd/server/start/start_node.go]: config.KubeletConfig.Hostname is empty in my latest run

Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Sigh.  Is

Comment (rajatchopra) [inline pkg/cmd/server/start/start_node.go]: Kubelet is not even run yet. So we need to use HostameOverride instead.

Comment (smarterclayton) [inline pkg/cmd/server/start/start_node.go]: Both fixed

**Comment by rajatchopra** [comment]
Okay it all works. Looks ready for merge.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]
