### PR TITLE
IPFailover was broken for alpha.1

### LINKED ISSUE #9077: openshift/origin-keepalived-ipfailover is broken after v1.3.0-alpha.0 (regression)
```
$ docker run -it --rm openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1
docker: Error response from daemon: Container command '/var/lib/origin/ipfailover/keepalived/monitor.sh' not found or does not exist..
```

##### Version
images `openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1` and `openshift/origin-keepalived-ipfailover:latest` are impacted

##### Steps To Reproduce
1. Deploy a new cluster with the ansible recipe
2. OR run directly the image as above

##### Current Result

```
$ docker run -it --rm openshift/origin-keepalived-ipfailover:v1.3.0-alpha.1
docker: Error response from daemon: Container command '/var/lib/origin/ipfailover/keepalived/monitor.sh' not found or does not exist..
```
##### Expected Result

```
Initializing ipvs 2.6
Keepalived_healthcheckers[2214]: Initializing ipvs 2.6
IPVS: Can't initialize ipvs: Permission denied (you must be root)
Keepalived_healthcheckers[2214]: IPVS: Can't initialize ipvs: Permission denied (you must be root)
Healthcheck child process(2214) died: Respawning
Keepalived[60]: Healthcheck child process(2214) died: Respawning
[...]
```

##### Additional Information

It's working fine until `v1.3.0-alpha.0`

### PR DESCRIPTION
**Pull request by smarterclayton**
/var/lib/origin is now a docker volume, which results in the contents
being lost. Moved it to /var/lib/ipfailover, and added a slightly better
error message when no arguments are provided.

Fixes #9077

@ramr will repush this image as v1.3.0-alpha.1 afterwards

### CODE REVIEW

**Comment by smarterclayton** [comment]
@sdodson @knobunc PTAL, this is p0 on alpha.1

**Comment by smarterclayton** [comment]
[test]

**Comment by knobunc** [comment]
Makes sense, and the change LGTM.

**Comment by sdodson** [comment]
LGTM, this problem was introduced after 3.2 was branched FWIW.

**Comment by smarterclayton** [comment]
Adding an e2e test to verify that ipfailover actually starts (which we never had before).  We need an extended test for it at some point.

**Comment by knobunc** [comment]
@smarterclayton Added the need for that test to our "moar tests" card. https://trello.com/c/GGqetI5f/65-epic-test-networking-integration-tests

**Comment by smarterclayton** [comment]
[test]

File: hack/test-end-to-end-docker.sh [hunk 1]
```diff
@@ -36,7 +36,7 @@ function cleanup()
 	dump_container_logs
 
 	echo "[INFO] Dumping all resources to ${LOG_DIR}/export_all.json"
-	oc export all --all-namespaces --raw -o json --config=${ADMIN_KUBECONFIG} > ${LOG_DIR}/export_all.json
+	oc export all --all-namespaces --raw -o json --config=${ADMIN_KUBECONFIG-} > ${LOG_DIR}/export_all.json
```
Comment (stevekuznetsov) [inline hack/test-end-to-end-docker.sh]: We prefer to use `${var:-default}` because it's rare that someone wants the set-but-null behavior from `${var-default}` and keeping that nuance in mind is hard.

Also, why do we expect this export to work if we *don't* have `$ADMIN_KUBECONFIG`? AFAICT, it is *always* set once a cluster has been successfully stood up. If one hasn't, would we expect `oc export` to work? If one has, would we expect the output of `oc export` to be useful without the admin credentials?

Comment (smarterclayton) [inline hack/test-end-to-end-docker.sh]: This can be called before ADMIN_KUBECONFIG is set up if the failure happens
early enough.

Comment (stevekuznetsov) [inline hack/test-end-to-end-docker.sh]: Right, I understand this, so I'm asking in what case would that be valid? In that case would we a) expect the cluster to be up already and b) if so, do we expect to get any useful information from the cluster without admin role?

Comment (smarterclayton) [inline hack/test-end-to-end-docker.sh]: In which case we don't want export to fail the output, we just don't want
to log.

Comment (smarterclayton) [inline hack/test-end-to-end-docker.sh]: cleanup() has to assume all calls fail, and guard appropriately.

Comment (stevekuznetsov) [inline hack/test-end-to-end-docker.sh]: Alright. I was hoping that the detection there was going to be more involved than `set +e` and ignoring the failure, but alright. Comment about syntax remains.

File: hack/test-end-to-end-docker.sh [hunk 2]
```diff
@@ -36,7 +36,7 @@ function cleanup()
 	dump_container_logs
 
 	echo "[INFO] Dumping all resources to ${LOG_DIR}/export_all.json"
-	oc export all --all-namespaces --raw -o json --config=${ADMIN_KUBECONFIG} > ${LOG_DIR}/export_all.json
+	oc export all --all-namespaces --raw -o json --config=${ADMIN_KUBECONFIG:-} > ${LOG_DIR}/export_all.json
```
Comment (stevekuznetsov) [inline hack/test-end-to-end-docker.sh]: I still maintain that forcing this to fail the line but not the script by injecting the null flag value is pretty far from ideal. Just do

```sh
# we only dump etcd contents if cluster is up; we can use presence of $ADMIN_KUBECONFIG as a proxy for
# detecting if the cluster got brought up correctly
if [[ -n "${ADMIN_KUBECONFIG:-}" ]]; then
    echo "[INFO] Dumping all resources to ${LOG_DIR}/export_all.json"
    oc export all --all-namespaces --raw -o json --config=${ADMIN_KUBECONFIG} > ${LOG_DIR}/export_all.json
fi
```

We should also make this change to all of the other cleanup functions we have floating around...

**Comment by smarterclayton** [comment]
[merge]

**Comment by smarterclayton** [comment]
Test is passing, [merge]

**Comment by smarterclayton** [comment]
Bizarre,
https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_check/1478/testReport/junit/github/com_openshift_origin_test_cmd_router/test_cmd_router_sh_29__executing__oadm_router___dry_run__o_yaml__expecting_failure_and_text__name/

[merge]

**Comment by smarterclayton** [comment]
[test]
