### PR TITLE
Record events for initial deployment failures

### LINKED ISSUE #2743: can't find out about wayward deployment
Usually if your deployment goes south, you have *something* to look at. But not always it seems.

```
[joe@master beta4]$ osc status
In project OpenShift 3 Demo (demo)

service mysql (172.30.213.58:3306)
  mysql deploys mysql:latest
    #1 deployment waiting on image or update

hello-openshift deploys hello-openshift:latest
  #1 deployment waiting on image or update

To see more information about a Service or DeploymentConfig, use 'osc describe service <name>' or 'osc describe dc <name>'.
You can use 'osc get all' to see lists of each of the types described above.
[joe@master beta4]$ osc describe dc mysql
Name:           mysql
Created:        About an hour ago
Labels:         <none>
Latest Version: Not deployed
Triggers:       Config, Image(mysql@latest, auto=true)
Strategy:       Recreate
Template:
                        Selector:       deploymentconfig=mysql
                        Replicas:       1
                        Containers:
                                NAME    IMAGE           ENV
                                mysql   library/mysql
Latest Deployment:      <none>
No events.
[joe@master beta4]$ osc deploy mysql
mysql #1 deployment waiting on image or update
[joe@master beta4]$ osc get rc
CONTROLLER   CONTAINER(S)   IMAGE(S)   SELECTOR   REPLICAS
[joe@master beta4]$ osc get pods
POD       IP        CONTAINER(S)   IMAGE(S)   HOST      LABELS    STATUS    CREATED   MESSAGE
[joe@master beta4]$ 
```

I assume there's something wrong with my docker or SDN config or something, but I don't even know which node to look on. I have literally no information about what is going wrong. Is there a command for describing a deployment? Don't see a pod, obviously.

### PR DESCRIPTION
**Pull request by ironcladlou**
Records events for initial deployment failures so users can diagnose
things like invalid trigger configurations which prevent deployment.

Closes #2743

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @abhgupta @smarterclayton

File: pkg/deploy/controller/configchange/controller.go [hunk 1]
```diff
@@ -52,6 +55,7 @@ func (c *DeploymentConfigChangeController) Handle(config *deployapi.DeploymentCo
 			if kerrors.IsConflict(err) {
 				return fatalError(fmt.Sprintf("DeploymentConfig %s updated since retrieval; aborting trigger: %v", deployutil.LabelForDeploymentConfig(config), err))
 			}
+			c.recorder.Eventf(config, "failedCreate", "Couldn't create initial deployment: %v", err)
```
Comment (smarterclayton) [inline pkg/deploy/controller/configchange/controller.go]: Is this going to record an event over and over and over?

Comment (smarterclayton) [inline pkg/deploy/controller/configchange/controller.go]: Every second for 3 days?

Comment (ironcladlou) [inline pkg/deploy/controller/configchange/controller.go]: Not at the moment. It'll only happen when more DC events roll in. The reflector for this controller only resyncs every few minutes. The configChange controller currently only retries once until #3051 is resolved (at which point this should be rate limited/time based).

Comment (ironcladlou) [inline pkg/deploy/controller/configchange/controller.go]: Just to be 100% sure, I've verified this manually (letting my initial deployment rot, I got 2 events up front from the retry and another couple a few minutes later- both treated as dupes by k8s; the "count" increases for a single event).

Comment (smarterclayton) [inline pkg/deploy/controller/configchange/controller.go]: K

----- Original Message -----

**Comment by smarterclayton** [comment]
LGTM [merge]
