### PR TITLE
Not found errors must match object in migration

### LINKED ISSUE #15006: Some rolebindingrestrictions cannot be storage migrated because of a missing namespace
From a prod dataset being tested in #14999.  Migration being run on some role binding restrictions is failing.

```
error:     -n AAA rolebindingrestrictions/match-project-admin-user: namespaces "AAA" not found
error:     -n BBB rolebindingrestrictions/match-project-admin-user: namespaces "BBB" not found
```

First, this means that something in the update path is checking for namespace existence on these RBRs.  However, if the namespace isn't being changed during an RBR, it shouldn't be checked.  That's probably the minimal bug that needs to be fixed here.  

However, if the namespace doesn't exist, why is the RBR blocking?  RBR shouldn't require a namespace to exist in order to mutate it, unless permission checks are required, and if permission checks ARE required, then it needs to be cleaned up prior to deletion, which it apparently was not.

Would like an answer before we deploy 3.6 to a prod env on Wednesday

@jupierce @Miciah

### PR DESCRIPTION
**Pull request by enj**
This change tightens the code to not tolerate not found errors that refer to a different object than what was being migrated.  For example, the previous code would not error if the not found error refereed to the namespace being missing instead of the actual object. Thus we can detect objects that have been orphaned inside of a deleted namespace.

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #15006

@openshift/security

@smarterclayton PTAL

[test]

```
$ oc adm migrate storage --include=serviceaccounts --confirm
error:     -n bahbah serviceaccounts/default: namespaces "bahbah" not found
summary: total=51 errors=1 ignored=0 unchanged=50 migrated=0
info: to rerun only failing resources, add --include=serviceaccounts
error: 1 resources failed to migrate
```

### CODE REVIEW

File: pkg/cmd/admin/migrate/migrator.go [hunk 1]
```diff
@@ -502,3 +502,20 @@ func DefaultRetriable(info *resource.Info, err error) error {
...
+	}
+	status, ok := err.(errors.APIStatus)
+	if !ok {
+		return false
+	}
+	details := status.Status().Details
+	if details == nil {
+		return false
+	}
+	gvk := info.Object.GetObjectKind().GroupVersionKind()
```
Comment (liggitt) [inline pkg/cmd/admin/migrate/migrator.go]: does this work correctly with not found errors for legacy group and new API groups?

Comment (enj) [inline pkg/cmd/admin/migrate/migrator.go]: I assume the group in the returned status would line up with info group (so legacy or new depending on which endpoint migrate was using).

Comment (enj) [inline pkg/cmd/admin/migrate/migrator.go]: I went ahead and special cased the legacy group and opened kubernetes/kubernetes/issues/48959 for the general problem.  Maybe I should just ignore the group here?

**Comment by enj** [comment]
@smarterclayton @liggitt Do we want to move forward with this?

**Comment by smarterclayton** [comment]
In 3.7

On Jul 14, 2017, at 5:31 PM, OpenShift Bot <notifications@github.com> wrote:

continuous-integration/openshift-jenkins/test FAILURE (
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin/3164/)
(Base Commit: 05b9ea8
<https://github.com/openshift/origin/commit/05b9ea884e842546bde220700684388a27beb7bc>)
(PR Branch Commit: fb62005
<https://github.com/openshift/origin/commit/fb6200578147e3c93aab3b59e117a90ed265f5b0>
)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin/pull/15213#issuecomment-315472937>,
or mute
the thread

**Comment by enj** [comment]
@smarterclayton @liggitt can we merge this now?

File: pkg/oc/admin/migrate/migrator.go [hunk 2]
```diff
@@ -503,3 +503,20 @@ func DefaultRetriable(info *resource.Info, err error) error {
 	}
 	return err
 }
+
+// isNotFoundForInfo returns true iff the error is a not found for the the specific info object.
```
Comment (smarterclayton) [inline pkg/oc/admin/migrate/migrator.go]: `the the`

**Comment by smarterclayton** [comment]
Looks fine to me except the one nit.

**Comment by enj** [comment]
Addressed nit / added LGTM.
