### PR TITLE
Correct missing sizes for manifest schema 1 images

### LINKED ISSUE #16306: Images don't have size property
The image size is not set on images pushed to recent (latest) registry/master.

See the image built with OpenShift builder:

```
oc describe image sha256:12e63f54fca507b2016d2746dd4747e9a5aa0587204a02efc6d25ba51a311e74
Docker Image:   172.30.30.30:5000/extended-test-limitrange-admission-bn8kz-splls/sized@sha256:12e63f54fca507b2016d2746dd4747e9a5aa0587204a02efc6d25ba51a311e74
Name:           sha256:12e63f54fca507b2016d2746dd4747e9a5aa0587204a02efc6d25ba51a311e74
Created:        About a minute ago
Annotations:    openshift.io/image.managed=true
Image Size:     0 B (first layer 15.09 kB, last binary layer 32 B)
Image Created:  About a minute ago
Author:         <none>
Arch:           amd64
Command:        <none>
Working Dir:    <none>
User:           <none>
Exposes Ports:  <none>
Docker Labels:  io.openshift.build.name=sized-1
                io.openshift.build.namespace=extended-test-limitrange-admission-bn8kz-splls
Environment:    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
                OPENSHIFT_BUILD_NAME=sized-1
                OPENSHIFT_BUILD_NAMESPACE=extended-test-limitrange-admission-bn8kz-splls
```

Note the `Image Size`. Because of that, quota/limits don't work. And our extended tests are failing.

### PR DESCRIPTION
**Pull request by miminar**
Instead of filling metadata in the image object in the registry, send the manifest and config blobs to the master and let it do the job.

Resolves #16306
Resolves: [bz#1491589](https://bugzilla.redhat.com/show_bug.cgi?id=1491589)

### CODE REVIEW

**Comment by miminar** [comment]
@dmage PTAL
@mfojtik FYI

**Comment by miminar** [comment]
The code is covered by `extended_image_registry` tests which will be part of a nightly job.

File: pkg/dockerregistry/server/manifestschema1handler.go [hunk 1]
```diff
@@ -102,7 +102,7 @@ func (h *manifestSchema1Handler) FillImageMetadata(ctx context.Context, image *i
 	}
 	image.DockerImageMetadata.Object = meta
 
-	return nil
+	return encodeRawDockerImageMetadata(image, true)
```
Comment (dmage) [inline pkg/dockerregistry/server/manifestschema1handler.go]: above, imageMetadataFromManifest is called, which calls encodeRawDockerImageMetadata. Can't we merge the code above into imageMetadataFromManifest?

**Comment by smarterclayton** [comment]
Add test so this doesn't regress

**Comment by miminar** [comment]
I moved the metadata filling into separate schema handlers since they differ a lot. I've also added few unit tests. I'll add some more coverage, especially for schema2. 

@legionus, @dmage PTAL

File: pkg/dockerregistry/server/manifestschema1handler.go [hunk 2]
```diff
@@ -53,56 +53,75 @@ type manifestSchema1Handler struct {
 var _ ManifestHandler = &manifestSchema1Handler{}
 
 func (h *manifestSchema1Handler) FillImageMetadata(ctx context.Context, image *imageapiv1.Image) error {
```
Comment (dmage) [inline pkg/dockerregistry/server/manifestschema1handler.go]: As it's our internal type, I'd like to propose to split this function into 3 parts:

    Layers(ctx context.Context) (layers []imageapi.ImageLayer, annotations map[string]string, error)
    Signatures(ctx context.Context) ([][]byte, error)
    Metadata(ctx context.Context, layers []imageapi.ImageLayer) (imageapi.DockerImage, err error)

The output of these functions should depend only on the input manifest. And we do not need to parse manifest data in this functions, because we already have `h.manifest` (in this case we can remove DockerImageManifest in caller).

These functions can be reused in pkg/image/apis/image.ImageWithMetadata.

**Comment by smarterclayton** [comment]
sgtm

File: pkg/dockerregistry/server/manifestschema1handler.go (hunk 2 above)
Comment (miminar) [reply pkg/dockerregistry/server/manifestschema1handler.go]: Good idea, I'll rework.

Comment (miminar) [reply pkg/dockerregistry/server/manifestschema1handler.go]: Reworked. I modified the declarations a bit. PTAL

**Comment by miminar** [comment]
Added more tests.
Instead of filling metadata to the image object in the registry, the manifest and config blobs are sent to master API, which should do the job.

File: pkg/dockerregistry/server/manifestservice.go [hunk 3]
```diff
@@ -143,6 +148,7 @@ func (m *manifestService) Put(ctx context.Context, manifest distribution.Manifes
 			DockerImageReference:         fmt.Sprintf("%s/%s/%s@%s", m.repo.config.registryAddr, m.repo.namespace, m.repo.name, dgst.String()),
 			DockerImageManifest:          string(payload),
 			DockerImageManifestMediaType: mediaType,
+			DockerImageConfig:            string(config),
```
Comment (dmage) [inline pkg/dockerregistry/server/manifestservice.go]: It will land in etcd, won't it?

Comment (miminar) [reply pkg/dockerregistry/server/manifestservice.go]: > It will land in etcd, won't it?

I've updated the image strategy to unset `DockerImageConfig` and `DockerImageManifest`.

**Comment by miminar** [comment]
The annotation `openshift.io/image.manifestBlobLocations=registry` is a protection against removing manifest/config from image object when image is created/updated outside of latest registry version that makes sure to store the blobs on its storage and setting the annotation.

File: pkg/image/apis/image/types.go [hunk 4]
```diff
@@ -51,6 +51,14 @@ const (
 	// downconverted.
 	ImporterPreferOSAnnotation = "importer.image.openshift.io/prefer-os"
 
+	// DockerImageManifestBlobLocationsAnnotation is a comma-separated list with locations of image's manifest
+	// blob and its configuration blob.
+	DockerImageManifestBlobLocationsAnnotation = "openshift.io/image.manifestBlobLocations"
```
Comment (dmage) [inline pkg/image/apis/image/types.go]: Do you expect values other than "registry"?

Comment (miminar) [reply pkg/image/apis/image/types.go]: There are three different possible locations: `registry`, `etcd` and `external`. We may want to record known manifest locations in the future (like docker daemon). The annotation would allow for encoded urls as well. Although, some new image attribute would fit better for such a purpose.

**Comment by miminar** [comment]
Another rebase needed.

File: pkg/image/apis/image/types.go (hunk 4 above)
Comment (smarterclayton) [reply pkg/image/apis/image/types.go]: If you plan on using URLs in the future you should be using an array of structs, JSON encoded.

Comment (smarterclayton) [reply pkg/image/apis/image/types.go]: Also, constants used in apis should always be `CamelCase`

Comment (miminar) [reply pkg/image/apis/image/types.go]: > If you plan on using URLs in the future you should be using an array of structs, JSON encoded.

I'd rather avoid it using annotation. Let's add another attribute if the need arises in the future.

I've turned the annotation into boolean `"image.openshift.io/manifestBlobLocations"`.

> Also, constants used in apis should always be CamelCase

I may be missing something, but all the other image annotation names are in `lowerCamelCase`. On the other hand, builds [use](https://github.com/openshift/origin/blob/848776c00ea084f991a6a8b51c8f20fecc53efbc/pkg/build/apis/build/types.go#L15) `dash-separated-lower-case`.

**Comment by miminar** [comment]
@stevekuznetsov 

When I click on detail link of ci/openshift-jenkins/extended_image_registry, I get:

```
Unable to load build details from gs://origin-ci-test/pr-logs/pull/16325/test_pull_request_origin_extended_image_registry/24
This may mean the job has not yet uploaded any artifacts, or that it failed to upload. Take a look at the job in Jenkins for more information.
```

The job link works fine though. Is this openshift/test-infra issue?

**Comment by stevekuznetsov** [comment]
@miminar yeah we had some issues yesterday... should be fixed from now on :)

**Comment by miminar** [comment]
@smarterclayton @dmage any other comments?

**Comment by smarterclayton** [comment]
Looks fine to me but I'll let @dmage have the final say

**Comment by bparees** [comment]
@dmage can you sign off on this?  looks like this is the fix for a blocking bug.

**Comment by bparees** [comment]
(it also appears to be blocking https://github.com/openshift/origin/pull/15807, it would be great to clear this logjam)

**Comment by legionus** [comment]
@miminar @dmage Should we add the `imageapi.ImageManifestBlobStoredAnnotation` annotation in the `TagService` ?

https://github.com/miminar/origin/blob/5ac2762a6e0874359683a32567350917f7321b19/pkg/dockerregistry/server/tagservice.go#L170-L177

**Comment by legionus** [comment]
> Should we add the imageapi.ImageManifestBlobStoredAnnotation annotation in the TagService ?

I will answer myself. No. This should not be done because the image we get from the API.

/lgtm
/approve
