### PR TITLE
Fix e2e test's check for determining that the router is up.

### LINKED ISSUE #8250: Change how router status is checked in the end-to-end tests
As per discussion in #7935 

In test/end-to-end/core.sh, there's a check to ensure that the haproxy router is started which does an 
`oc get endpoints router` till an endpoint gets added: 
https://github.com/openshift/origin/blob/master/test/end-to-end/core.sh#L290 

That's not really a valid test as it could return before the router is actually ready.
Change to use the health check URI:  curl to http://<ip>:1936/healthz

*Edited* typos

### PR DESCRIPTION
**Pull request by ramr**
fixes #8250   

Change how we determine a router is up in the end-to-end test - check for the healthz port to respond with success - HTTP status code 200.

@smarterclayton  PTAL thx

### CODE REVIEW

File: test/end-to-end/core.sh [hunk 1]
```diff
@@ -287,11 +287,12 @@ os::cmd::expect_success "oc project ${CLUSTER_ADMIN_CONTEXT}"
 
 # ensure the router is started
 # TODO: simplify when #4702 is fixed upstream
-os::cmd::try_until_text "oc get endpoints router --output-version=v1beta3 --template='{{ if .subsets }}{{ len .subsets }}{{ else }}0{{ end }}'" '[1-9]+' $((5*TIME_MIN))
+router_pod=$(oc get pod -n default -l deploymentconfig=router --template='{{(index .items 0).metadata.name}}')
+healthz_uri=http://$(oc get pod "${router_pod}" --template='{{.status.podIP}}'):1936/healthz
+os::cmd::try_until_text "curl -s -o /dev/null -I -w '%{http_code}' ${healthz_uri}" '200' $((5*TIME_MIN))
```
Comment (smarterclayton) [inline test/end-to-end/core.sh]: We should already have wait_for_url somewhere.

**Comment by ramr** [comment]
@smarterclayton   changed to `wait_for_url_timed`.  PTAL thx

**Comment by ramr** [comment]
[test]

**Comment by smarterclayton** [comment]
Lgtm [merge]

**Comment by smarterclayton** [comment]
Failure looks related (or is another failure in the router)

**Comment by ramr** [comment]
Its related - looks like the original code was waiting for the pod to be born and so looks like this will need a combination of the birth check and then the healthz check.

**Comment by ramr** [comment]
[test]

**Comment by smarterclayton** [comment]
Lgtm [merge]
