### PR TITLE
Issue 2293 - fixes options help message

### LINKED ISSUE #2293: Options help message is not rooted properly under `start`
Options help message is not rooted properly.

```
$ openshift start master --help
Use "openshift start options" for a list of global command-line options (applies to all commands).
```

Should be `openshift options`

### PR DESCRIPTION
**Pull request by fabianofranz**
Fixes #2293.

### CODE REVIEW

**Comment by fabianofranz** [comment]
[merge]

File: pkg/cmd/templates/templater.go [hunk 1]
```diff
@@ -58,38 +59,61 @@ func UseOptionsTemplates(cmd *cobra.Command) {
...
+			appendCmd(x.Parent())
+			root = append(root, x.Parent())
 		}
 	}
-	appendCmdName(c)
+	appendCmd(c)
 
-	if cName := c.Name(); c.HasSubCommands() && len(root) == 1 && root[0] == "openshift" && cName != "openshift" {
-		root = append(root, cName)
+	if c.HasSubCommands() && len(root) == 1 && root[0].Name() == "openshift" && c.Name() != "openshift" {
```
Comment (smarterclayton) [inline pkg/cmd/templates/templater.go]: This is now no longer safe (at all) because the master binary is going to change to be dual role.  We're going to have to make this be an argument to the generator.
