### PR TITLE
Web console fix log follow after window.resize event

### LINKED ISSUE #7146: Web console: follow logs doesn't keep following
Still some issues where follow logs doesn't work consistently.

/cc @jwforres @benjaminapetersen

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix attachScrollEvents on window.resize causing affixed follow links in logViewer to behave inconsistently

Fixes #7146

- attachScrollEvents now removes all resize events before attaching new
	- ensures only one event attached at any single moment
  - follow/stop following links now continue to function appropriately after resize

- lingering issues:
	- TL;DR
		- affix is set about 50px off to accomodate certain DOM nodes with ng-show & differences w/mobile
	- LONG:
  	- affix position is set once in markup, but ng-show may add or remove log dates from DOM, which affects position
    	- current position is set with additional space in mind, but this means affix does not take effect immediately
    - possible fix:
			- use a hack to detect DOM nodes added to document
      - MutationObserver is one way to detect added nodes
			- detect logViewer distance from top of document
      - update affix accordingly

@spadgett @jwforres @sg00dwin

### CODE REVIEW

File: assets/app/scripts/directives/logViewer.js [hunk 1]
```diff
@@ -93,19 +93,21 @@ angular.module('openshiftConsole')
               } else {
                 // If the user scrolled the window manually, stop auto-scrolling.
                 $scope.$evalAsync(function() {
-                  $scope.autoScroll = false;
+                  $scope.autoScrollIsActive = false;
```
Comment (spadgett) [inline assets/app/scripts/directives/logViewer.js]: This is a better name, thanks. Maybe just `autoScrollActive`?

File: assets/app/scripts/directives/logViewer.js [hunk 2]
```diff
@@ -71,8 +71,8 @@ angular.module('openshiftConsole')
 
 
 
-
-            var updateScrollLinks = function() {
+            // is just toggling show/hide, nothing else.
+            var toggleScrollLinks = function() {
```
Comment (spadgett) [inline assets/app/scripts/directives/logViewer.js]: Toggle implies you are flipping the state with each call. This function doesn't do that.

File: assets/app/scripts/directives/logViewer.js (hunk 1 above)
Comment (benjaminapetersen) [inline assets/app/scripts/directives/logViewer.js]: Yeah, these are getting long... but the little bugs have pushed me to be more and more specific :)
Ill update that.

File: assets/app/scripts/directives/logViewer.js (hunk 2 above)
Comment (benjaminapetersen) [inline assets/app/scripts/directives/logViewer.js]: Ah... true, it sets `showScrollLinks` to `true || false`, but via calculation.  hmm.  `setScrollLinksVisibility`?  Dunno if i like that either...

Comment (spadgett) [inline assets/app/scripts/directives/logViewer.js]: I'm OK with that, although "set" to me implies you are passing in the new value. Maybe `updateScrollLinksVisibility`? Wordy, but descriptive.

Comment (benjaminapetersen) [inline assets/app/scripts/directives/logViewer.js]: Agree on set... in this directive I definitely prefer descriptive though, so that may be good.

**Comment by benjaminapetersen** [comment]
Opinion on issue #5799... Follow doesn't appear immediately, but appears as soon as log hits bottom of window. I think we may have resolved this issue as well with all the tinkering we have done.

**Comment by spadgett** [comment]
> Follow doesn't appear immediately, but appears as soon as log hits bottom of window. I think we may have resolved this issue as well with all the tinkering we have done.

Sorry, not clear on what the issue or resolution was? :)

**Comment by benjaminapetersen** [comment]
Hmm. Re-reading.  I misread a part of it, lets leave that one.

File: assets/app/scripts/directives/logViewer.js (hunk 1 above)
Comment (benjaminapetersen) [inline assets/app/scripts/directives/logViewer.js]: updated

**Comment by benjaminapetersen** [comment]
updated.

[TEST]

**Comment by spadgett** [comment]
LGTM [merge]
