### PR TITLE
Not every registry has library

### LINKED ISSUE #5327: Deploy config pulling from library/<image> not imagestream
Using this template[1], deploy config from `image: helloapache` with a trigger from ImageStreamTag `helloapache:latest`[2]. Imagestream helloapache[3] has latest tag. When build completes and pushes image it does not trigger a deployment (unexpected). When deployment is started manually it fails trying to pull from docker hub `library/helloapache:latest` (also unexpected). Curiously, this template[4] works on the same environment.

Verbose logs here[5].

```
# oc version
oc v1.0.6-805-g3f0e8f6
kubernetes v1.2.0-alpha.1-1107-g4c8e6f4
```

[1] https://github.com/aweiteka/ose-build-pipeline/blob/master/ose-build-template.yaml
[2] deployconfig
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: 2015-10-22T11:45:19Z
  labels:
    app: helloapache
    template: automated-build
  name: helloapache
  namespace: build-demo
  resourceVersion: "381"
  selfLink: /oapi/v1/namespaces/build-demo/deploymentconfigs/helloapache
  uid: 5ef557e4-78b2-11e5-9c3b-54ee75102ab0
spec:
  replicas: 1
  selector:
    name: helloapache
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: helloapache
    spec:
      containers:
      - image: helloapache
        imagePullPolicy: IfNotPresent
        name: helloapache
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - helloapache
      from:
        kind: ImageStreamTag
        name: helloapache:latest
    type: imageChange
status:
  latestVersion: 1
```
[3]
```
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: 2015-10-22T11:45:19Z
    labels:
      app: helloapache
      template: automated-build
    name: helloapache
    namespace: build-demo
    resourceVersion: "371"
    selfLink: /oapi/v1/namespaces/build-demo/imagestreams/helloapache
    uid: 5ef57014-78b2-11e5-9c3b-54ee75102ab0
  spec: {}
  status:
    dockerImageRepository: 172.30.155.105:5000/build-demo/helloapache
    tags:
    - items:
      - created: 2015-10-22T11:48:11Z
        dockerImageReference: 172.30.155.105:5000/build-demo/helloapache@sha256:065ae90bc9c0b99318f3bf710c12e9c1a77ad8217e9f6d238485fe15fbc026c2
        image: sha256:065ae90bc9c0b99318f3bf710c12e9c1a77ad8217e9f6d238485fe15fbc026c2
      tag: latest
kind: List
metadata: {}
```
[4] https://github.com/mfojtik/jenkins-ci/blob/master/openshift/jenkins-master-ephemeral.json
[5] deploy ~11:49 https://s3.amazonaws.com/aweiteka.bucket/openshift_logs/ose.log

### LINKED ISSUE #6570: Extra Path Added to Docker Image Name After App Creation
After running `new-app` with a Docker image as the parameter, the app gets created, but deployment fails due to the Docker image name being incorrect. `/library` is added to the path, changing an image name from `my.registry.com/test` to `my.registry.com/library/test`. The deployment fails as a result since the latter image does not exist on the remote registry.
```
oc new-app my.registry.com/test
--> Found Docker image 386c08c (6 weeks old) from my.registry.com for "my.registry.com/test:latest"
    * This image will be deployed in deployment config "test"
--> Creating resources with label app=test ...
    DeploymentConfig "test" created
    Service "test" created
--> Success

oc status
In project test on server https://10.101.7.110:8443

svc/test - 172.30.100.49
  dc/test deploys my.registry.com/library/test:latest
    #1 deployment running for 18 seconds - 1 pod
```
I thought this might be the same issue as #6516, but the problem there was that the private registry required authentication (mine does not). I should note that I'm using the integrated Docker image (https://hub.docker.com/r/openshift/origin/) for this testing.

### PR DESCRIPTION
**Pull request by miminar**
Add 'library/' prefix only for images belonging to Docker Hub.

Resolves #6570
Resolves #5327

### CODE REVIEW

**Comment by miminar** [comment]
@bparees, @soltysh can you please take a look?

**Comment by soltysh** [comment]
LGTM

**Comment by miminar** [comment]
[test]

**Comment by kargakis** [comment]
Also related https://github.com/openshift/origin/issues/5327 ?

**Comment by miminar** [comment]
I'm fixing cmd tests now.

**Comment by miminar** [comment]
Flake [#6259](https://github.com/openshift/origin/issues/6259):

    Running hack/../test/cmd/builds.sh:76: executing 'oc get is ruby-22-centos7' expecting any result and text 'latest'; re-trying every 0.2s until completion or 60.000s...
    FAILURE after 59.581s: hack/../test/cmd/builds.sh:76: executing 'oc get is ruby-22-centos7' expecting any result and text 'latest'; re-trying every 0.2s until completion or 60.000s: the command timed out
    Standard output from the command:
    NAME              DOCKER REPO              TAGS      UPDATED
    ruby-22-centos7   centos/ruby-22-centos7
    ... repeated 144 times
    There was no error output from the command.
    !!! Error in hack/../test/cmd/../../hack/cmd_util.sh:501
            'return 1' exited with status 1
    Call stack:
            1: hack/../test/cmd/../../hack/cmd_util.sh:501 os::cmd::try_until_text(...)
            2: hack/../test/cmd/builds.sh:76 main(...)

re-[test]

File: pkg/image/api/helper_test.go [hunk 1]
```diff
@@ -96,14 +107,36 @@ func TestParseDockerImageReference(t *testing.T) {
...
+		},
+		{
+			From:      "docker.io/myapp",
+			Registry:  "docker.io",
 			Namespace: DockerDefaultNamespace,
-			Name:      "foo",
+			Name:      "myapp",
 		},
 		{
-			From:      "localhost/bar",
```
Comment (liggitt) [inline pkg/image/api/helper_test.go]: Why did the local host test get removed. I really want to touch as few existing tests as possible here

Comment (miminar) [inline pkg/image/api/helper_test.go]: It didn't get removed. It may seems like it in *unified* view. See the [split view](https://github.com/openshift/origin/pull/6777/files?diff=split#diff-c7ce025f36a3834873271fcff866fdb4R118). Only the namespace part has been removed.

**Comment by bparees** [comment]
commits should be squashed, otherwise lgtm.

**Comment by miminar** [comment]
squashed

**Comment by miminar** [comment]
Resolves #5327

**Comment by smarterclayton** [comment]
LGTM [merge]

**Comment by miminar** [comment]
Same flake #6259 but a bit later in the cmd tests:

    Running hack/../test/cmd/newapp.sh:148: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s...
    FAILURE after 59.525s: hack/../test/cmd/newapp.sh:148: executing 'oc get imagestreamtags installable:file' expecting success; re-trying every 0.2s until completion or 60.000s: the command timed out
    There was no output from the command.
    There was no error output from the command.

File: pkg/image/api/helper.go [hunk 2]
```diff
@@ -150,8 +166,8 @@ func (r DockerImageReference) DaemonMinimal() DockerImageReference {
 		r.Namespace = ""
```
Comment (miminar) [inline pkg/image/api/helper.go]: Hmm this seems to be another bug. It should be cleared only in case of Docker registry. If I only noticed it earlier :-(. I'll create a follow-up.
