### PR TITLE
Only set masterIP with valid IPs, avoid calling OverrideConfig when writing config

### LINKED ISSUE #4383: --master=https://localhost:8443 --write-config sets masterIP incorrectly
`openshift start master --write-config=foo --master=https://localhost:8443` generates this config, with an invalid masterIP:

```
kubernetesMasterConfig:
  ...
  masterIP: localhost
```

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #4383

@smarterclayton PTAL

### CODE REVIEW

File: pkg/cmd/server/start/start_api.go [hunk 1]
```diff
@@ -92,8 +92,10 @@ func NewCommandStartMasterAPI(name, basename string, out io.Writer) (*cobra.Comm
 		config.EtcdConfig = nil
 		if config.KubernetesMasterConfig != nil {
 			if masterAddr.Provided {
-				glog.V(2).Infof("Using a master address override %q", masterAddr.Host)
-				config.KubernetesMasterConfig.MasterIP = masterAddr.Host
+				if ip := net.ParseIP(masterAddr.Host); ip != nil {
```
Comment (liggitt) [inline pkg/cmd/server/start/start_api.go]: @smarterclayton would you rather conditionally set it here, or let it get in and fail validation? calling `OverrideConfig` only in the non-write-config case fixes the bug just as well

Comment (liggitt) [inline pkg/cmd/server/start/start_api.go]: yeah, actually, I want to parse and ignore if it's not an IP... otherwise, this breaks, which feels stupid:
```
openshift start master --master=https://localhost:8443 --write-config=foo
openshift start master --master=https://localhost:8443 --config=foo/master-config.yaml
```

**Comment by smarterclayton** [comment]
LGTM [merge]
