### PR TITLE
Fix /.well-known/oauth-authorization-server panic and add test

### LINKED ISSUE #12453: Go panic on get to /.well-known/oauth-authorization-server
after an origin/master rebase this morning (post 1.5 k8s rebase into origin/master I believe), I'm seeing a go panic on a http get to the noted oauth endpoint during a jenkins extended test.

See https://ci.openshift.redhat.com/jenkins/job/test_pr_origin_extended/973/s3/download/test-extended/core/logs/openshift.log and pull https://github.com/openshift/origin/pull/12440, specifically comments https://github.com/openshift/origin/pull/12440#issuecomment-271969759 https://github.com/openshift/origin/pull/12440#issuecomment-272000596

@enj @liggitt FYI

### PR DESCRIPTION
**Pull request by sttts**
Fixes #12453

### CODE REVIEW

**Comment by sttts** [comment]
[test]

File: test/integration/master_routes_test.go [hunk 1]
```diff
@@ -108,3 +109,35 @@ func TestRootRedirect(t *testing.T) {
...
+		t.Fatalf("Unexpected error: %v", err)
+	}
+	if resp.StatusCode != http.StatusOK {
+		t.Fatalf("Expected %d, got %d", http.StatusOK, resp.StatusCode)
+	}
+	body, err := ioutil.ReadAll(resp.Body)
+	if err != nil {
+		t.Fatalf("Unexpected error reading the body: %v", err)
+	}
+	if !strings.Contains(string(body), "authorization_endpoint") {
```
Comment (enj) [inline test/integration/master_routes_test.go]: This should probably parse the json and assert the contents make sense.

File: test/integration/master_routes_test.go [hunk 2]
```diff
@@ -108,3 +109,35 @@ func TestRootRedirect(t *testing.T) {
...
+	testutil.RequireEtcd(t)
+	defer testutil.DumpEtcdOnFailure(t)
+	masterConfig, _, err := testserver.StartTestMasterAPI()
+	if err != nil {
+		t.Fatalf("unexpected error: %v", err)
+	}
+
+	transport := knet.SetTransportDefaults(&http.Transport{
+		TLSClientConfig: &tls.Config{
+			InsecureSkipVerify: true,
```
Comment (enj) [inline test/integration/master_routes_test.go]: Any simple way to avoid turning off verification here?

File: test/integration/master_routes_test.go [hunk 3]
```diff
@@ -108,3 +109,35 @@ func TestRootRedirect(t *testing.T) {
...
+		},
+	})
+
+	req, err := http.NewRequest("GET", masterConfig.AssetConfig.MasterPublicURL+"/.well-known/oauth-authorization-server", nil)
+	req.Header.Set("Accept", "*/*")
+	resp, err := transport.RoundTrip(req)
+	if err != nil {
+		t.Fatalf("Unexpected error: %v", err)
+	}
+	if resp.StatusCode != http.StatusOK {
```
Comment (enj) [inline test/integration/master_routes_test.go]: We also need a check when OAuth is turned off (should be 404).

**Comment by sttts** [comment]
@enj thanks for the comments, all make sense. But I would prefer to get this in first as a quick fix for the regression. We can always test more and should extend tests. Looks like oauth has a lack of  coverage e2e- or integration-wise? @liggitt has a better overview.

File: test/integration/master_routes_test.go (hunk 1 above)
Comment (sttts) [inline test/integration/master_routes_test.go]: For now this is meant as a smoke test.

File: test/integration/master_routes_test.go (hunk 2 above)
Comment (liggitt) [inline test/integration/master_routes_test.go]: should be simple to build transport from the admin kubeconfig struct

**Comment by liggitt** [comment]
the OAuth endpoints themselves have tons of integration coverage. this discovery doc isn't used in-tree yet, and was missing an integration test

File: test/integration/master_routes_test.go (hunk 2 above)
Comment (sttts) [inline test/integration/master_routes_test.go]: done

File: test/integration/master_routes_test.go (hunk 3 above)
Comment (sttts) [inline test/integration/master_routes_test.go]: done

**Comment by sttts** [comment]
@enj ptal

**Comment by enj** [comment]
LGTM

Please open a tech debt issue to make the smoke test actually check the returned JSON.

**Comment by liggitt** [comment]
[merge]

**Comment by gabemontero** [comment]
One of the merge tests, https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_conformance/10112/console, was aborted, perhaps due to the github.com hiccup a few minutes ago.  Does the whole merge process need to be restarted, or can that one jenkins job be restarted ?

**Comment by gabemontero** [comment]
it is official - merge marked as failed; I believe a flake needs to be noted (presumably for the github.com hiccup I noted earlier) and the merge tag reposted

**Comment by stevekuznetsov** [comment]
Today we require the full merge process to be re-triggered.

**Comment by liggitt** [comment]
[merge]

**Comment by smarterclayton** [comment]
[merge]
