### PR TITLE
fixed readiness endpoint route listing

### LINKED ISSUE #4069: /ready is listed as a path in the apiserver
Probably should be removed - only /healthz/ready is exposed.

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Fixes #4069 

@smarterclayton PTAL

### CODE REVIEW

**Comment by deads2k** [comment]
Can you refactor this enough to make use of the list in a unit test to make sure the endpoints listed exist?

File: pkg/authorization/authorizer/attributes_builder.go [hunk 1]
```diff
@@ -21,7 +21,7 @@ func (a *openshiftAuthorizationAttributeBuilder) GetAttributes(req *http.Request
 	// any url that starts with an API prefix and is more than one step long is considered to be a resource URL.
 	// That means that /api is non-resource, /api/v1 is resource, /healthz is non-resource, and /swagger/anything is non-resource
 	urlSegments := splitPath(req.URL.Path)
-	isResourceURL := (len(urlSegments) > 1) && a.infoResolver.APIPrefixes.Has(urlSegments[0])
+	isResourceURL := (len(urlSegments) > 2) && a.infoResolver.APIPrefixes.Has(urlSegments[0])
```
Comment (stevekuznetsov) [inline pkg/authorization/authorizer/attributes_builder.go]: This change was necessary because the previous rules were incorrectly identifying endpoints like `/api/v1` as a resource URL. No valid resource URL can be just two segments long, so changing the minimum length to 2 should be valid.

Comment (smarterclayton) [inline pkg/authorization/authorizer/attributes_builder.go]: You could create an API endpoint that is "api.myserver.com/v1" - we don't
work throughout with that today, but it's not unreasonable.

On Mon, Aug 10, 2015 at 3:34 PM, Steve Kuznetsov <notifications@github.com>
wrote:

> In pkg/authorization/authorizer/attributes_builder.go
> <https://github.com/openshift/origin/pull/4074#discussion_r36674212>:
>
> > @@ -21,7 +21,7 @@ func (a *openshiftAuthorizationAttributeBuilder) GetAttributes(req *http.Request
> >  	// any url that starts with an API prefix and is more than one step long is considered to be a resource URL.
> >  	// That means that /api is non-resource, /api/v1 is resource, /healthz is non-resource, and /swagger/anything is non-resource
> >  	urlSegments := splitPath(req.URL.Path)
> > -	isResourceURL := (len(urlSegments) > 1) && a.infoResolver.APIPrefixes.Has(urlSegments[0])
> > +	isResourceURL := (len(urlSegments) > 2) && a.infoResolver.APIPrefixes.Has(urlSegments[0])
>
> This change was necessary because the previous rules were incorrectly
> identifying endpoints like /api/v1 as a resource URL. No valid resource
> URL can be just two segments long, so changing the minimum length to 2
> should be valid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4074/files#r36674212>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

Comment (stevekuznetsov) [inline pkg/authorization/authorizer/attributes_builder.go]: Would `api.myserver.com` also be valid?

Comment (liggitt) [inline pkg/authorization/authorizer/attributes_builder.go]: the doc "/api/v1 is resource" clearly indicates the problem

**Comment by stevekuznetsov** [comment]
After conferring with @smarterclayton I decided to keep the versioned endpoints in the test but expect them to `404`. Here's the reasoning:  If the previous behavior was to expose Swagger spec at these endpoints, it was unintentional. We want to at some point to refactor to use a `MuxHelper` like upstream Kube. Therefore, we can look at what they expose at `/` as a reference for what we need to - they list versioned api endpoints, but a `curl` to them always results in a `404`. We can therefore expect us to expose the versioned endpoints but also `404` there.

**Comment by stevekuznetsov** [comment]
@deads2k PTAL

**Comment by stevekuznetsov** [comment]
[test]

File: pkg/cmd/server/origin/handlers.go [hunk 2]
```diff
@@ -21,30 +21,32 @@ import (
 	"github.com/openshift/origin/pkg/authorization/authorizer"
 )
 
+// TODO once we have a MuxHelper we will not need to hardcode this list of paths
+// RootPaths are paths we server on from root
+var RootPaths kapi.RootPaths = kapi.RootPaths{Paths: []string{
+	"/api",
+	"/api/v1beta3",
```
Comment (liggitt) [inline pkg/cmd/server/origin/handlers.go]: @smarterclayton do we want to expose the API versions at the root or require traversing to /api to get the list of enabled versions? This static list won't reflect which versions are actually enabled/disabled (which we make configurable)

Comment (smarterclayton) [inline pkg/cmd/server/origin/handlers.go]: It was only for consistency with upstream.  I am utterly ambivalent.

On Mon, Aug 10, 2015 at 4:48 PM, Jordan Liggitt <notifications@github.com>
wrote:

> In pkg/cmd/server/origin/handlers.go
> <https://github.com/openshift/origin/pull/4074#discussion_r36682438>:
>
> > @@ -21,30 +21,32 @@ import (
> >  	"github.com/openshift/origin/pkg/authorization/authorizer"
> >  )
> >
> > +// TODO once we have a MuxHelper we will not need to hardcode this list of paths
> > +// RootPaths are paths we server on from root
> > +var RootPaths kapi.RootPaths = kapi.RootPaths{Paths: []string{
> > +	"/api",
> > +	"/api/v1beta3",
>
> @smarterclayton <https://github.com/smarterclayton> do we want to expose
> the API versions at the root or require traversing to /api to get the list
> of enabled versions? This static list won't reflect which versions are
> actually enabled/disabled (which we make configurable)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4074/files#r36682438>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

File: pkg/cmd/server/origin/master.go [hunk 3]
```diff
@@ -163,6 +163,13 @@ func (c *MasterConfig) Run(protected []APIInstaller, unprotected []APIInstaller)
 	swagger.RegisterSwaggerService(swaggerConfig, open)
 	extra = append(extra, fmt.Sprintf("Started Swagger Schema API at %%s%s", swaggerAPIPrefix))
 
+	for _, service := range open.RegisteredWebServices() {
+		for _, route := range service.Routes() {
+			fmt.Printf("%8s %s", route.Method, route.Path)
```
Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: Just add a `\n`.

File: pkg/cmd/server/origin/master.go [hunk 4]
```diff
@@ -163,6 +163,13 @@ func (c *MasterConfig) Run(protected []APIInstaller, unprotected []APIInstaller)
 	swagger.RegisterSwaggerService(swaggerConfig, open)
 	extra = append(extra, fmt.Sprintf("Started Swagger Schema API at %%s%s", swaggerAPIPrefix))
 
+	for _, service := range open.RegisteredWebServices() {
```
Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: Wait, why are we doing this?

File: pkg/cmd/server/origin/master.go [hunk 5]
```diff
@@ -263,6 +270,10 @@ func (c *MasterConfig) InstallProtectedAPI(container *restful.Container) []strin
 
 	var root *restful.WebService
 	for _, service := range container.RegisteredWebServices() {
+		for _, route := range service.Routes() {
```
Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: Why are we doing this?

File: test/integration/api_paths_test.go [hunk 6]
```diff
@@ -0,0 +1,60 @@
...
+	for _, route := range origin.RootPaths.Paths {
+		req, err := http.NewRequest("GET", masterConfig.AssetConfig.MasterPublicURL+route, nil)
+		req.Header.Set("Accept", "*/*")
+		resp, err := transport.RoundTrip(req)
+		if err != nil {
+			t.Errorf("unexpected error: %v", err)
+			continue
+		}
+		// Look up expected code if exceptional or default to 200
+		expetedCode, exists := ExceptionalExpectedCodes[route]
```
Comment (deads2k) [inline test/integration/api_paths_test.go]: typo

Comment (stevekuznetsov) [inline test/integration/api_paths_test.go]: Good catch, thanks.

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
[test]

**Comment by stevekuznetsov** [comment]
@deads2k @smarterclayton thoughts?

File: pkg/authorization/authorizer/attributes_builder.go (hunk 1 above)
Comment (deads2k) [inline pkg/authorization/authorizer/attributes_builder.go]: > the doc "/api/v1 is resource" clearly indicates the problem

fix the comment @liggitt  is referring to.

File: pkg/cmd/server/origin/handlers.go (hunk 2 above)
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: @stevekuznetsov Can you get reasonable access to the master config as this point to build the correct list of versioned endpoints?  If so, may as well specify them correctly to stay consistent with upstream, but correct to our config.

That would require a second integration test.

Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: Probability of @deads2k asking for another integration test any given day... rising.

Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: > Probability of @deads2k asking for another integration test any given day... rising.

Probability of anyone regretting a good test that ensures we stay in sync as we rebase on kube and update our master config: zero?

Comment (smarterclayton) [inline pkg/cmd/server/origin/handlers.go]: Probability of snark in this thread: 100%

On Thu, Aug 13, 2015 at 11:16 AM, David Eads <notifications@github.com>
wrote:

> In pkg/cmd/server/origin/handlers.go
> <https://github.com/openshift/origin/pull/4074#discussion_r36986219>:
>
> > @@ -21,30 +21,32 @@ import (
> >  	"github.com/openshift/origin/pkg/authorization/authorizer"
> >  )
> >
> > +// TODO once we have a MuxHelper we will not need to hardcode this list of paths
> > +// RootPaths are paths we server on from root
> > +var RootPaths kapi.RootPaths = kapi.RootPaths{Paths: []string{
> > +	"/api",
> > +	"/api/v1beta3",
>
> Probability of @deads2k <https://github.com/deads2k> asking for another
> integration test any given day... rising.
>
> Probability of anyone regretting a good test that ensures we stay in sync
> as we rebase on kube and update our master config: zero?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/origin/pull/4074/files#r36986219>.
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by danmcp** [comment]
Bump

**Comment by danmcp** [comment]
@stevekuznetsov @deads2k @smarterclayton @liggitt Bump

File: pkg/cmd/server/origin/handlers.go [hunk 7]
```diff
@@ -14,7 +14,6 @@ import (
 	kapi "k8s.io/kubernetes/pkg/api"
 	kapierrors "k8s.io/kubernetes/pkg/api/errors"
 	klatest "k8s.io/kubernetes/pkg/api/latest"
-	"k8s.io/kubernetes/pkg/api/unversioned"
```
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: `goimports` did this

File: pkg/cmd/server/origin/handlers.go [hunk 8]
```diff
@@ -21,27 +21,35 @@ import (
 	"github.com/openshift/origin/pkg/authorization/authorizer"
 )
 
+// RootPaths is the list of root paths we serve under "/". We expose it here so that we can
+// access it from integration tests
+var RootPaths = unversioned.RootPaths{}
```
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: @deads2k is there a better way of plumbing this through to the integration tests?

File: test/integration/api_paths_test.go [hunk 9]
```diff
@@ -0,0 +1,76 @@
...
+	// any not specified are not
+	expectedLevels := sets.NewString(masterConfig.APILevels...)
+	actualLevels := sets.String{}
+	for _, route := range origin.RootPaths.Paths {
+		if strings.HasPrefix(route, "/api/") {
+			actualLevels.Insert(route[5:])
+		}
+	}
+	if !expectedLevels.Equal(actualLevels) {
+		t.Errorf("actual API levels served don't match expected levels:\n\texpected:\n\t%s\n\tgot:\n\t%s", expectedLevels.List(), actualLevels.List())
```
Comment (stevekuznetsov) [inline test/integration/api_paths_test.go]: "second" integration test that makes sure we only serve the levels we are asked to here @deads2k

**Comment by stevekuznetsov** [comment]
@deads2k PTAL

File: pkg/cmd/server/origin/handlers.go (hunk 8 above)
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: No globals, can you pass in what you mean?

Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: We'd need to create a field and accessor method on the internal `MasterConfig` - is this OK?

File: pkg/cmd/server/origin/handlers.go [hunk 10]
```diff
@@ -21,27 +21,35 @@ import (
...
+		rootPaths = append(rootPaths, "/api/"+path)
+	}
+	rootPaths = append(rootPaths, []string{"/controllers",
+		"/healthz",
+		"/healthz/ping",
+		"/healthz/ready",
+		"/logs/",
+		"/metrics",
+		"/osapi",
+		"/osapi/v1beta3",
```
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: isn't this dead now?

File: pkg/cmd/server/origin/handlers.go [hunk 11]
```diff
@@ -21,27 +21,35 @@ import (
...
 )
 
+// RootPaths is the list of root paths we serve under "/". We expose it here so that we can
+// access it from integration tests
+var RootPaths = unversioned.RootPaths{}
+
 // TODO We would like to use the IndexHandler from k8s but we do not yet have a
 // MuxHelper to track all registered paths
-func indexAPIPaths(handler http.Handler) http.Handler {
+func indexAPIPaths(apiVersions []string, handler http.Handler) http.Handler {
```
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: openshift and kube versions are configured separately.

File: pkg/cmd/server/origin/handlers.go (hunk 10 above)
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: Apparently not... the integration test picks it up. Should the `osapi` endpoints be generated the same way as the `api` endpoints?

File: pkg/cmd/server/origin/handlers.go (hunk 8 above)
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: Will get this list from a `GET` to `/`

File: pkg/cmd/server/origin/handlers.go (hunk 10 above)
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: Disregard previous comment.

**Comment by stevekuznetsov** [comment]
@deads2k I can't tell how to get a whitelist of Kube API endpoints - just going to use the list of [default levels](https://github.com/openshift/origin/blob/master/pkg/cmd/server/api/types.go#L25)

**Comment by stevekuznetsov** [comment]
@deads2k addressed comments, PTAL
[test]

File: pkg/cmd/server/origin/handlers.go [hunk 12]
```diff
@@ -23,25 +23,28 @@ import (
...
 // TODO We would like to use the IndexHandler from k8s but we do not yet have a
 // MuxHelper to track all registered paths
-func indexAPIPaths(handler http.Handler) http.Handler {
+func indexAPIPaths(osAPIVersions, kubeAPIVersions []string, handler http.Handler) http.Handler {
+	// TODO once we have a MuxHelper we will not need to hardcode this list of paths
+	rootPaths := []string{"/api"}
+	for _, path := range kubeAPIVersions {
+		rootPaths = append(rootPaths, "/api/"+path)
+	}
+	rootPaths = append(rootPaths, []string{"/controllers",
```
Comment (kargakis) [inline pkg/cmd/server/origin/handlers.go]: Indent "/controllers" with the rest paths

Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: :+1:

**Comment by stevekuznetsov** [comment]
flake on getting an image stream [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8129/console):
```
FAILURE after 59.775s: hack/../test/cmd/builds.sh:76: executing 'oc get is ruby-22-centos7' expecting any result and text 'latest'; re-trying every 0.2s until completion or 60.000s: the command timed out
Standard output from the command:
NAME              DOCKER REPO              TAGS      UPDATED
ruby-22-centos7   centos/ruby-22-centos7
... repeated 161 times
There was no error output from the command.
```

seems like https://github.com/openshift/origin/issues/6259

**Comment by stevekuznetsov** [comment]
currently we only 404 on `/logs/`, just wanted to confirm with @deads2k @smarterclayton that this remains desired behavior

**Comment by stevekuznetsov** [comment]
@deads2k PTAL

File: pkg/cmd/server/origin/handlers.go [hunk 13]
```diff
@@ -23,25 +23,29 @@ import (
...
+	}
+	rootPaths = append(rootPaths, []string{
+		"/controllers",
+		"/healthz",
+		"/healthz/ping",
+		"/healthz/ready",
+		"/logs/",
+		"/metrics",
+		"/oapi"}...)
+	for _, path := range osAPIVersions {
```
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: move up and do the sort afterwards.

File: pkg/cmd/server/origin/master.go [hunk 14]
```diff
@@ -152,7 +152,7 @@ func (c *MasterConfig) Run(protected []APIInstaller, unprotected []APIInstaller)
 		extra = append(extra, i.InstallAPI(open)...)
 	}
 
-	handler = indexAPIPaths(handler)
+	handler = indexAPIPaths(c.Options.APILevels, configapi.DefaultKubernetesAPILevels, handler)
```
Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: `configapi.GetEnabledAPIVersionsForGroup`.  See the callers for usage.

File: test/integration/api_paths_test.go [hunk 15]
```diff
@@ -0,0 +1,88 @@
...
+
+	var broadcastRootPaths unversioned.RootPaths
+	if err := json.NewDecoder(rootResponse.Body).Decode(&broadcastRootPaths); err != nil {
+		t.Fatalf("unexpected error decoding root path response: %v", err)
+	}
+	defer rootResponse.Body.Close()
+
+	// We need to make sure that any APILevels specified in the config are present in the RootPaths, and that
+	// any not specified are not
+	expectedLevels := sets.NewString(masterConfig.APILevels...)
```
Comment (deads2k) [inline test/integration/api_paths_test.go]: do this same check for the kube api versions.

**Comment by stevekuznetsov** [comment]
@deads2k addressed comments

File: pkg/cmd/server/origin/handlers.go [hunk 16]
```diff
@@ -23,25 +24,29 @@ import (
...
-				"/healthz",
-				"/healthz/ping",
-				"/logs/",
-				"/metrics",
-				"/ready",
-				"/oapi",
-				"/oapi/v1",
-				"/swaggerapi/",
-			}}
 			// TODO it would be nice if apiserver.writeRawJSON was not private
```
Comment (deads2k) [inline pkg/cmd/server/origin/handlers.go]: crufty comment?

File: pkg/cmd/server/origin/master.go [hunk 17]
```diff
@@ -152,7 +152,7 @@ func (c *MasterConfig) Run(protected []APIInstaller, unprotected []APIInstaller)
 		extra = append(extra, i.InstallAPI(open)...)
 	}
 
-	handler = indexAPIPaths(handler)
+	handler = indexAPIPaths(c.Options.APILevels, configapi.GetEnabledAPIVersionsForGroup(*c.Options.KubernetesMasterConfig, configapi.APIGroupKube), handler)
```
Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: nil check needed.

Comment (stevekuznetsov) [inline pkg/cmd/server/origin/master.go]: When dereferencing the Kube master config?

Why does that method need an instance of the master config, instead of a pointer to it? Seems like a huge object to be copying for this use.

Comment (deads2k) [inline pkg/cmd/server/origin/master.go]: > Why does that method need an instance of the master config, instead of a pointer to it? Seems like a huge object to be copying for this use.

It's a pretty tiny object, already available locally, that is copied once per startup.  The copy is fine.  And yeah, that's a pointer because its allowed to be nil.

Comment (stevekuznetsov) [inline pkg/cmd/server/origin/master.go]: Sorry, got confused with Origin master config type. Added the nil check.

**Comment by deads2k** [comment]
The bad comment is my last comment.

File: pkg/cmd/server/origin/handlers.go (hunk 16 above)
Comment (stevekuznetsov) [inline pkg/cmd/server/origin/handlers.go]: Do we want to push a change upstream to make it public? Or should we just forget about this?

**Comment by stevekuznetsov** [comment]
@deads2k addressed

**Comment by deads2k** [comment]
lgtm [merge]

**Comment by stevekuznetsov** [comment]
flake [here](https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin/8155/console):
```
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
!!! Error in hack/../test/end-to-end/core.sh:346
	'grunt test-integration' exited with status 3
Call stack:
	1: hack/../test/end-to-end/core.sh:346 main(...)
Exiting with status 1
```

#4536 

@deads2k please re-tag

**Comment by stevekuznetsov** [comment]
end-to-end flake [here]():
```
Error from server: 501: All the given peers are not reachable (failed to propose on members [https://172.18.5.153:4001] twice [last error: Unexpected HTTP status code]) [0]
```

#6447 
@deads2k please re-tag

**Comment by deads2k** [comment]
re[merge]
