### PR TITLE
tests: wait_for_registry: use oc rollout status

### LINKED ISSUE #11406: Running individual core extended tests may fail with timeout when waiting for image registry
Running individual core extended test blocks forever
##### Version

```
oc v1.4.0-alpha.0+49de813
kubernetes v1.4.0+776c994
features: Basic-Auth
```
##### Steps To Reproduce

Try and run a individual core test via:

```
~> test/extended/core.sh --ginkgo.focus=<regex>
```
##### Current Result

It hangs while waiting for docker registry to be up. It stops at following step:

```
enshift.local.config/master/admin.kubeconfig'' expecting success; re-trying every 0.25s until completion or 80.000s
[INFO] OpenShift server health checks done at: 
Mon Oct 17 17:22:28 EDT 2016
[INFO] Installing the registry
serviceaccount "registry" created
clusterrolebinding "registry-registry-role" created
deploymentconfig "docker-registry" created
service "docker-registry" created
[INFO] Waiting for command to finish: 'oc get dc/docker-registry -o 'jsonpath={.status.observedGeneration},{.status.replicas},{.status.updatedReplicas},{.status.availableReplicas}' --config='/tmp/openshift/test-extended/core/openshift.local.config/master/admin.kubeconfig' | grep '^1,1,1,1$''...
```

In my testing I found the docker registry to be up, but it the version/generation of `dc/docker-registry` does not matches with what is expected of the test. The same thing works if I run whole extended suite.
##### Expected Result

It should be possible to run individual tests.

### PR DESCRIPTION
**Pull request by mmilata**
Prevents the function from hanging when observedGeneration is higher than the number we're waiting for.

Fixes #11406
Related to #11410

### CODE REVIEW

File: hack/util.sh [hunk 1]
```diff
@@ -459,9 +459,7 @@ function install_registry() {
 readonly -f install_registry
 
 function wait_for_registry() {
-	local generation="$(oc get dc/docker-registry -o 'jsonpath={.metadata.generation}')"
-	local onereplicajs='{.status.observedGeneration},{.status.replicas},{.status.updatedReplicas},{.status.availableReplicas}'
-	wait_for_command "oc get dc/docker-registry -o 'jsonpath=${onereplicajs}' --config='${ADMIN_KUBECONFIG}' | grep '^${generation},1,1,1$'"  "$((5*TIME_MIN))"
+	wait_for_command "oc rollout status dc/docker-registry --request-timeout=1m"  "$((5*TIME_MIN))"
```
Comment (stevekuznetsov) [inline hack/util.sh]: As @liggitt mentioned, one of the core functional bits of this method _is_ the fact that it's pegging to a specific generation and waiting for that generation to be ready. `oc rollout status` may be appropriate in the initial deploy & wait for readiness stage, but not in the update stages.

Comment (mmilata) [inline hack/util.sh]: Fair enough, thanks for explanation.

Comment (kargakis) [inline hack/util.sh]: We also don't need to wait and use a separate timeout since `oc rollout status` uses a watch until the rollout is finished which means the deployment timeout is used implicitly.

Comment (stevekuznetsov) [inline hack/util.sh]:
```sh
local generation; generation="$(oc get dc/docker-registry -o 'jsonpath={.metadata.generation}')"
wait_for_command "oc rollout status dc/docker-registry --revision='${generation}' --request-timeout=1m"  "$((5*TIME_MIN))"
```

Comment (kargakis) [inline hack/util.sh]: @stevekuznetsov generation has nothing to do with this test. --revision needs a revision and not a generation. All we need for this helper is to see that the inital deployment of the registry is complete. We have a test specific to generation in the extended suite.

Comment (kargakis) [inline hack/util.sh]: Also wait_for_command doesn't make sense since oc rollout status uses a watcher under the hood.

Comment (stevekuznetsov) [inline hack/util.sh]: > All we need for this helper is to see that the inital deployment of the registry is complete

I was under the impression that @liggitt's point was that we _also_ used this helper to do tests later after changing this component?

Comment (kargakis) [inline hack/util.sh]: Not sure about what comment are you talking about but you can still use `oc rollout status` wherever you need this helper.

Comment (stevekuznetsov) [inline hack/util.sh]: Right, but in that case setting the version to 1 wouldn't work, right?

Comment (stevekuznetsov) [inline hack/util.sh]: @kargakis https://github.com/openshift/origin/pull/11410#issuecomment-254507371

Comment (liggitt) [inline hack/util.sh]: I'm also ok replacing those other uses of this function with calls to `oc rollout status` if if does everything we need

Comment (kargakis) [inline hack/util.sh]: @stevekuznetsov here is my reply at https://github.com/openshift/origin/pull/11410#issuecomment-254574288

We don't even need a separate helper for waiting for dc/xxxx to be ready now. Let's just use `oc rollout status` (waits for a complete status on top of a synced config (dc.generation <= dc.status.observedGeneration).

**Comment by PI-Victor** [comment]
i was hoping the discussion for this PR wouldn't get stuck so that i can run my tests locally without a headache :)
/resume?

**Comment by kargakis** [comment]
@mmilata can you update this? I would suggest remove the registry helper and use `oc rollout status` directly.

**Comment by mmilata** [comment]
@kargakis PTAL ... or did you want me to remove the part that checks readiness as well?

Note: in case of registry deployment failure this commit effectively increases the timeout from 5 to 10 minutes.

**Comment by kargakis** [comment]
> @kargakis PTAL ... or did you want me to remove the part that checks readiness as well?

Yes, it's redundant

> Note: in case of registry deployment failure this commit effectively increases the timeout from 5 to 10 minutes.

If you want the same timeout as now, set TimeoutSeconds in the deployment strategy before creating the registry.

**Comment by mmilata** [comment]
@kargakis updated, PTAL

**Comment by kargakis** [comment]
LGTM [test]

File: test/extended/gssapi.sh [hunk 2]
```diff
@@ -89,7 +89,7 @@ os::start::server
 export KUBECONFIG="${ADMIN_KUBECONFIG}"
 
 install_registry
-wait_for_registry
+oc rollout status dc/docker-registry
```
Comment (stevekuznetsov) [inline test/extended/gssapi.sh]: Expect success here since you're in a jUnit context

File: test/extended/cmd.sh [hunk 3]
```diff
@@ -38,7 +38,7 @@ oc login -u system:admin -n default
 oadm policy add-role-to-group view system:authenticated -n default
 
 install_registry
-wait_for_registry
+oc rollout status dc/docker-registry
```
Comment (stevekuznetsov) [inline test/extended/cmd.sh]: Expect success here since you're in a jUnit context

**Comment by mmilata** [comment]
@stevekuznetsov fixed

**Comment by kargakis** [comment]
@mfojtik or @liggitt merge?

**Comment by mfojtik** [comment]
@mmilata can you address https://github.com/openshift/origin/pull/11487/files#r86203222 ?

I'm fine with merging this after that.

**Comment by mmilata** [comment]
@mfojtik the junit context actually starts few lines after the change (we've discussed this on IRC, sorry).

**Comment by liggitt** [comment]
LGTM, [merge]
