### PR TITLE
Make pod eviction timeout configurable

### LINKED ISSUE #2393: Make Pod eviction timeout configurable
Currently in openshift, node controller uses default pod eviction timeout of 5 mins. We need to make this value configurable to give flexibility to the user when dealing with failed nodes.

### PR DESCRIPTION
**Pull request by pravisankar**
config option, podEvictionTimeout: "<time.Duration>"

closes #2393

### CODE REVIEW

**Comment by pravisankar** [comment]
@derekwaynecarr @abhgupta please review/merge

File: pkg/cmd/server/api/types.go [hunk 1]
```diff
@@ -473,8 +473,11 @@ type KubernetesMasterConfig struct {
 	ServicesSubnet string
 	// StaticNodeNames is the list of nodes that are statically known
 	StaticNodeNames []string
-	// SchedulerConfigFile points to a file that describes how to set up the scheduler.  If empty, you get the default scheduling rules.
+	// SchedulerConfigFile points to a file that describes how to set up the scheduler. If empty, you get the default scheduling rules.
 	SchedulerConfigFile string
+	// PodEvictionTimeout controls grace peroid for deleting pods on failed nodes.
+	// It takes valid time duration string. If empty, you get the default pod eviction timeout.
+	PodEvictionTimeout string
```
Comment (liggitt) [inline pkg/cmd/server/api/types.go]: time durations as a string is weird

File: pkg/cmd/server/start/master_args.go [hunk 2]
```diff
@@ -386,7 +386,7 @@ func (args MasterArgs) BuildSerializeableKubeMasterConfig() (*configapi.Kubernet
 	}
 	masterHost, _, err := net.SplitHostPort(masterAddr.Host)
 	if err != nil {
-
+		return nil, err
```
Comment (liggitt) [inline pkg/cmd/server/start/master_args.go]: shouldn't return here... set `masterHost = masterAddr.Host` in that case

Comment (liggitt) [inline pkg/cmd/server/start/master_args.go]: you can get an err is the masterAddr.Host doesn't include a port

File: pkg/cmd/server/kubernetes/master.go [hunk 3]
```diff
@@ -142,11 +142,22 @@ func (c *MasterConfig) RunResourceQuotaManager() {
...
 func (c *MasterConfig) RunNodeController() {
+	var podEvictionTimeout time.Duration
+	var err error
+	if len(c.Options.PodEvictionTimeout) > 0 {
+		podEvictionTimeout, err = time.ParseDuration(c.Options.PodEvictionTimeout)
+		if err != nil {
+			glog.Fatalf("Unable to parse PodEvictionTimeout: %v", err)
+		}
+	} else {
+		podEvictionTimeout = 5 * time.Minute
```
Comment (liggitt) [inline pkg/cmd/server/kubernetes/master.go]: defaults should be applied in `server/v1/conversions.go#AddDefaultingFuncs`

File: pkg/cmd/server/api/v1/types.go [hunk 4]
```diff
@@ -451,6 +451,7 @@ type KubernetesMasterConfig struct {
 	ServicesSubnet      string   `json:"servicesSubnet"`
 	StaticNodeNames     []string `json:"staticNodeNames"`
 	SchedulerConfigFile string   `json:"schedulerConfigFile"`
+	PodEvictionTimeout  string   `json:"podEvictionTimeout"`
```
Comment (liggitt) [inline pkg/cmd/server/api/v1/types.go]: need to update types_test.go to include the new field, and open a doc and config change issue with details

**Comment by pravisankar** [comment]
Updated, PTAL

**Comment by pravisankar** [comment]
[test]

File: pkg/cmd/server/api/types.go [hunk 5]
```diff
@@ -473,8 +473,11 @@ type KubernetesMasterConfig struct {
 	ServicesSubnet string
 	// StaticNodeNames is the list of nodes that are statically known
 	StaticNodeNames []string
-	// SchedulerConfigFile points to a file that describes how to set up the scheduler.  If empty, you get the default scheduling rules.
+	// SchedulerConfigFile points to a file that describes how to set up the scheduler. If empty, you get the default scheduling rules.
 	SchedulerConfigFile string
+	// PodEvictionTimeout controls grace peroid for deleting pods on failed nodes.
```
Comment (liggitt) [inline pkg/cmd/server/api/types.go]: s/peroid/period/

**Comment by liggitt** [comment]
config bits look fine, please open an issue in openshift-docs and openshift-ansible to track adding the config option

**Comment by pravisankar** [comment]
[merge]
