### PR TITLE
Fix import-image --all

### LINKED ISSUE #8952: oc import-image --all doesn't import all
If you ask for --all tags, you kind of expect to get all of them, not some random subset. If there's some performance reason for limiting them, then there should be an alternative flag that does what the user expects like --recent.

##### Version

```
$ oc version
oc v1.3.0-alpha.0-510-gb7275b5
kubernetes v1.3.0-alpha.1-331-g0522e63
```

##### Steps To Reproduce

1. `oc import-image logging-fluentd --from registry.access.redhat.com/openshift3/logging-fluentd --all --confirm`

##### Current Result

```
The import completed successfully.

Name:                   logging-fluentd
Created:                6 minutes ago
Labels:                 <none>
Annotations:            openshift.io/image.dockerRepositoryCheck=2016-05-19T03:31:45Z
Docker Pull Spec:       172.30.26.232:5000/logging/logging-fluentd


Tag     Spec                                                            Created                 PullSpec        Image
latest  registry.access.redhat.com/openshift3/logging-fluentd:latest    Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a
v3.2    registry.access.redhat.com/openshift3/logging-fluentd:v3.2      Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a
v3.1    registry.access.redhat.com/openshift3/logging-fluentd:v3.1      Less than a second ago  <same>          6c2cc79545d4b30b5d4f45756f1a06223ee3bfb4d2f3ba5b665d484c8dce60b1
3.2.0-8 registry.access.redhat.com/openshift3/logging-fluentd:3.2.0-8   Less than a second ago  <same>          e1a07eb99c004aa2b244305171ebc3970b2e2c4a89864fb97a528ca17f69a72a


info: The remote repository contained 10 additional tags which were not imported: 3.2.0-6, 3.1.1, 3.1.1-11, 3.1.1-10, 3.1.1-8, 3.1.1-6, 3.1.1-5, v3.1, 3.1.0-6, 3.1.0-1
```

##### Expected Result

Well, first I would expect *all* of the tags to be imported.

Second, tag `3.2.0` doesn't appear to be in the list at all, though it's definitely in the registry (is same as v3.2).

##### Additional

Could there be an annotation on imagestreams to accomplish the same thing at auto-import time?

If you have a DC trigger based on the `3.2.0` tag but only the `v3.2` tag is imported, then your DC doesn't deploy. So this has significant consequences for logging where exactly that is happening now.

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #8952.

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

**Comment by soltysh** [comment]
Rebased due to weird test failures. This is ready for review @smarterclayton or @miminar ptal

File: pkg/cmd/cli/cmd/importimage.go [hunk 1]
```diff
@@ -249,151 +249,134 @@ func (o *ImportImageOptions) waitForImport(resourceVersion string) (*imageapi.Im
...
+			from = stream.Spec.DockerImageRepository
+		} else {
+			tags := make(map[string]string)
+			for name, tag := range stream.Spec.Tags {
+				if tag.From != nil && tag.From.Kind == "DockerImage" {
+					tags[name] = tag.From.Name
+				}
+			}
+			if len(tags) == 0 {
+				return nil, fmt.Errorf("image stream does not have importable tags (pointing to DockerImage)")
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: The message needs to be improved

File: pkg/cmd/cli/cmd/importimage.go [hunk 2]
```diff
@@ -249,151 +249,134 @@ func (o *ImportImageOptions) waitForImport(resourceVersion string) (*imageapi.Im
...
+		if err != nil {
+			return nil, nil, err
+		}
 	}
 
 	return stream, isi, nil
 }
 
-func (o *ImportImageOptions) newImageStream() (string, *imageapi.ImageStream) {
+func (o *ImportImageOptions) newImageStream() (*imageapi.ImageStream, *imageapi.ImageStreamImport) {
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: This should be down with the other methods below.

File: pkg/cmd/cli/cmd/importimage.go [hunk 3]
```diff
@@ -249,151 +249,134 @@ func (o *ImportImageOptions) waitForImport(resourceVersion string) (*imageapi.Im
...
+		stream, isi = o.newImageStream()
+		return stream, isi, nil
 	}
 
-	if len(from) == 0 {
-		// catch programmer error
-		return nil, nil, fmt.Errorf("unexpected error, from is empty")
+	// the stream already exists
+	if len(stream.Spec.DockerImageRepository) == 0 && len(stream.Spec.Tags) == 0 {
+		return nil, nil, fmt.Errorf("image stream has not defined anything to import")
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: Better message

File: pkg/cmd/cli/cmd/importimage.go [hunk 4]
```diff
@@ -249,151 +249,134 @@ func (o *ImportImageOptions) waitForImport(resourceVersion string) (*imageapi.Im
...
 	stream, err := o.isClient.Get(o.Name)
-	from := o.From
-	tag := o.Tag
-
+	// no stream, try creating one
 	if err != nil {
 		if !errors.IsNotFound(err) {
 			return nil, nil, err
 		}
 		if !o.Confirm {
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: Let's remove this check - it's annoying to end users and doesn't really protect you from anything (if you typo, you can just delete it)

File: pkg/cmd/cli/cmd/importimage_test.go [hunk 5]
```diff
@@ -13,128 +13,186 @@ import (
 )
 
 func TestCreateImageImport(t *testing.T) {
-	testCases := []struct {
+	testCases := map[string]struct {
```
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage_test.go]: Tests look good.

File: pkg/cmd/cli/cmd/importimage.go (hunk 1 above)
Comment (soltysh) [inline pkg/cmd/cli/cmd/importimage.go]: Apparently it'll be fixed/changed, due to https://bugzilla.redhat.com/show_bug.cgi?id=1343681. But that will be rather a followup to this one. For now I'll go with: 'image stream does not have tags pointing to external docker images'

File: pkg/cmd/cli/cmd/importimage.go (hunk 3 above)
Comment (soltysh) [inline pkg/cmd/cli/cmd/importimage.go]: That is an old message, I didn't change anything here, except for moving it into different method. What about 'image stream does not have valid docker images to be imported'?

File: pkg/cmd/cli/cmd/importimage.go (hunk 4 above)
Comment (soltysh) [inline pkg/cmd/cli/cmd/importimage.go]: Not quite sure, I'd prefer to leave it as is. I feel more comfortable with warning users than forcing them to delete afterwards. They'll end up wondering what happened and that's not desirable imho.

File: pkg/cmd/cli/cmd/importimage.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: "image stream does not contain tag definitions or a pointer to an image
repository and cannot be imported"

maybe.

File: pkg/cmd/cli/cmd/importimage.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: I would agree, except 100% of new users hit this, and only a very small
percentage of existing users will ever hit this.  I don't have to run
"--confirm" to run new-app, even though I might have made a typo.  I think
--confirm on create new IS is overkill.

Comment (smarterclayton) [inline pkg/cmd/cli/cmd/importimage.go]: "I would agree, except 100% of new users would be annoyed by this, and only
a very small percentage of existing users would be helped by this"

**Comment by soltysh** [comment]
@smarterclayton does this look good to you now?

**Comment by smarterclayton** [comment]
Yeah, squash

**Comment by soltysh** [comment]
Done.

**Comment by smarterclayton** [comment]
LGTM [merge]
