### PR TITLE
Reorder groups in cert Subjects

### LINKED ISSUE #18715: 3.9 alpha 3/4 regression: Certificate verification fails with GnuTLS
SSL certificate based authentication fails with 3.9 alpha 3 when using GnuTLS (which Cockpit does, via glib-networking). This has worked fine so far, up to 3.7.

Things work fine with the `oc` client:
```
❱❱❱ oc whoami
system:admin
```

To illustrate it with OpenSSL vs GnuTLS, let's extract the certificate into standard X.509 files:
```
awk '/client-certificate-data:/ { print $2 }'  ~/.kube/config | base64 -d > /tmp/cert.pem
awk '/client-key-data:/ { print $2 }'  ~/.kube/config | base64 -d > /tmp/cert.key
awk '/certificate-authority-data:/ { print $2 }' ~/.kube/config | base64 -d > /tmp/ca.pem
```

Now, authentication with curl works:
```
❱❱❱ curl --cert /tmp/cert.pem --key /tmp/cert.key --cacert /tmp/ca.pem https://10.111.112.101:8443/api
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "10.111.112.101:8443"
    }
  ]
}
```

It also works with OpenSSL:
```
❱❱❱ (printf 'GET /api HTTP/1.0\n\n'; sleep 1) | openssl s_client -CAfile /tmp/ca.pem -cert /tmp/cert.pem -key /tmp/cert.key -connect 10.111.112.101:8443
CONNECTED(00000003)
depth=1 CN = openshift-signer@1518732226
verify return:1
depth=0 CN = 10.111.112.101
verify return:1
[...]
---
HTTP/1.0 200 OK
Cache-Control: no-store
Content-Type: application/json
Date: Thu, 22 Feb 2018 09:28:46 GMT
Content-Length: 137

{"kind":"APIVersions","versions":["v1"],"serverAddressByClientCIDRs":[{"clientCIDR":"0.0.0.0/0","serverAddress":"10.111.112.101:8443"}]}
closed
```

But not with GnuTLS:
```
❱❱ (printf 'GET /api HTTP/1.0\n\n'; sleep 1)  | gnutls-cli --x509certfile=/tmp/cert.pem --x509keyfile=/tmp/cert.key --x509cafile=/tmp/ca.pem -p 8443 10.111.112.101
Processed 1 CA certificate(s).
Processed 1 client X.509 certificates...
Resolving '10.111.112.101:8443'...
Connecting to '10.111.112.101:8443'...
- Certificate type: X.509
- Got a certificate list of 2 certificates.
- Certificate[0] info:
 - subject `CN=10.111.112.101', issuer `CN=openshift-signer@1518732226', serial 0x02, RSA key 2048 bits, signed using RSA-SHA256, activated `2018-02-15 22:03:46 UTC', expires `2020-02-15 22:03:47 UTC', pin-sha256="8s1sXBqKC8Vvwk/Mj/UawpbMS83ZFJDCiaKTZTEwK2w="
[...]
HTTP/1.0 401 Unauthorized
Cache-Control: no-store
Content-Type: application/json
Date: Thu, 22 Feb 2018 09:29:24 GMT
Content-Length: 129

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
- Peer has closed the GnuTLS connection
```

For that, openshift logs an error message:
```
Feb 22 04:30:15 f1.cockpit.lan openshift-run[814]: E0222 04:30:15.791838     816 authentication.go:64] Unable to authenticate the request due to an error: [x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "openshift-signer@1518732226"), x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "openshift-signer@1518732226")]
```

##### Version
oc v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://10.111.112.101:8443
openshift v3.9.0-alpha.3+78ddc10
kubernetes v1.9.1+a0ce1bc657

### PR DESCRIPTION
**Pull request by simo5**
This is to workaround Bug #18715, which is caused by Golang Crypto's x509
certificate generation ordering Subjects RDN incorrectly *and* GNUTLS'
bug that "fixes" client certs on read with the correct encoding.

To avoid issues until both are fixed we set the correct ordering ourself

Fixes #18715
xref https://github.com/golang/go/issues/24254 https://gitlab.com/gnutls/gnutls/issues/403#note_61687722

### CODE REVIEW

**Comment by simo5** [comment]
@martinpitt PTAL

**Comment by enj** [comment]
If there is a bug in Go itself, should not we fix this generically in:

https://github.com/openshift/origin/blob/3addbb0b9aa147de9440774c5e1d3b36e57611df/pkg/cmd/server/crypto/crypto.go#L595

by forcing the ordering that DER expects?  Otherwise any other cert we generate with more than one organization will have this issue.

**Comment by simo5** [comment]
We might do that as well, let's see if the bug goes away with this simple fix first.
Ideally we get golang fixed and we do not need no complex workaround code.

**Comment by enj** [comment]
> Ideally we get golang fixed and we do not need no complex workaround code.

If the Go bug gets fixed today, it will take 3 - 6+ months to show up in origin.

**Comment by martinpitt** [comment]
Thanks, this looks like an okay first bandaid!

This still feels a bit unpredictable, though - is there any chance this could not be a set (using the `+` syntax) but a plain good old list with two `O:` entries? Same as what would be generated by `-subj '/O=system:masters/O=system:cluster-admins/CN=system:admin'`?

**Comment by enj** [comment]
> is there any chance this could not be a set

The DER encoding is handled by the Go standard library, which uses the SET notation and is not configurable.

**Comment by simo5** [comment]
@martinpitt I see no reason why we are trying to use multivalued RDNs, @liggitt may know if there is a good reason. We could certainly just have many RDNs and a deeper tree, but this PR fixes the iimediate Pain in an easy backportable way.
Once we know how we want to proceed we can make more complex changes in a different PR?

File: pkg/cmd/server/admin/default_certs.go [hunk 1]
```diff
@@ -145,7 +145,7 @@ func DefaultClusterAdminClientCertInfo(certDir string) ClientCertInfo {
 		},
 		UnqualifiedUser: "admin",
 		User:            "system:admin",
-		Groups:          sets.NewString(bootstrappolicy.ClusterAdminGroup, bootstrappolicy.MastersGroup),
+		Groups:          sets.NewString(bootstrappolicy.MastersGroup, bootstrappolicy.ClusterAdminGroup),
```
Comment (liggitt) [inline pkg/cmd/server/admin/default_certs.go]: A string set is an order independent map. You cannot depend on order in a go map. This could easily change in different go versions or in different invocations (map iteration order is randomized per invocation)

Comment (simo5) [reply pkg/cmd/server/admin/default_certs.go]: It can never be simple :-)

**Comment by simo5** [comment]
@liggit would it be ok to change ClientCertInfo to use []string instead of sets.String ?
Or is it preferable, at this point to introduce and explit reordering function in userToSubject() ?

**Comment by liggitt** [comment]
> Golang Crypto's x509 certificate generation ordering Subjects RDN incorrectly

can you clarify the bug here? either order should result in a valid x509 cert, right?

**Comment by liggitt** [comment]
> at this point to introduce and explit reordering function in userToSubject() ?

userToSubject isn't involved... the code that turns ClientCertInfo into a cert template for creation is at 
https://github.com/openshift/origin/blob/master/pkg/cmd/server/admin/create_mastercerts.go#L306 and calls `clientCertInfo.Groups.List()`, which returns the groups in sorted order.

**Comment by enj** [comment]
> userToSubject isn't involved

It is the last thing we do to set the cert subject, but the order fixing could be done elsewhere.  For example:

https://github.com/openshift/origin/blob/95e262011438642410959914c3db9868c57739ff/pkg/cmd/server/crypto/crypto.go#L740

could have the fixup logic.

**Comment by simo5** [comment]
@liggitt you need to go deeper, that code ends up calling https://github.com/openshift/origin/blob/master/pkg/cmd/server/crypto/crypto.go#L555 which ends up calling userToSubject() in signCertificate()

**Comment by simo5** [comment]
> can you clarify the bug here? either order should result in a valid x509 cert, right?

If golang crypto correctly implemented DER encoding for certs then we
wouldn't have to do anything special on our side.
Unfortunately golang's pkix.Name defines RelativeDistinguishedNameSET
as a simple SET instead of a SET OF and then does *not* order it
according to DER rules. DER requires SET OF to be ordered (by length of
string in this case, shortest strings first).

**Comment by liggitt** [comment]
> that code ends up calling https://github.com/openshift/origin/blob/master/pkg/cmd/server/crypto/crypto.go#L555 which ends up calling userToSubject() in signCertificate()

userToSubject just passes through whatever order was set in CreateClientCertOptions, it doesn't impose any ordering at all

**Comment by simo5** [comment]
@liggit I know userToSubject() does not impose any ordering, but it is the place where all caller of signCertificate ends up into. If I change only CreateClientCertOptions I may miss some code paths.

**Comment by liggitt** [comment]
> @liggit I know userToSubject() does not impose any ordering, but it is the place where all caller of signCertificate ends up into. If I change only CreateClientCertOptions I may miss some code paths.

I see. Something like:
```go
func userToSubject(u user.Info) pkix.Name {
	// Sort shortest first to workaround go DER encoding bug
	groups := u.GetGroups()
	sort.Slice(groups, func(i, j int) bool {
		if l := len(groups[i]) - len(groups[j]); l != 0 {
			return l < 0
		}
		return groups[i] < groups[j]
	})

	return pkix.Name{
		CommonName:   u.GetName(),
		SerialNumber: u.GetUID(),
		Organization: groups,
	}
}
```

**Comment by liggitt** [comment]
I don't object to that. if you do that, please reference the go issue and reproducer so we don't lose track of it

**Comment by simo5** [comment]
@liggitt Yeah that's what I was planning with a big FAT comment on why it is needed

**Comment by mrogers950** [comment]
https://github.com/golang/go/issues/24254

**Comment by simo5** [comment]
@liggit PTAL and lift hold if you are ok with this

**Comment by simo5** [comment]
@liggitt [damn fingers stop messing with is name :-)] PTAL

**Comment by simo5** [comment]
Flake #16832

File: pkg/cmd/server/crypto/crypto.go [hunk 2]
```diff
@@ -588,11 +588,44 @@ func (ca *CA) MakeClientCertificate(certFile, keyFile string, u user.Info, expir
...
+	// and try to "correct" this issue when reading client certs.
+	//
+	// This workaround should be killed once Golang's pkix module is fixed to
+	// generate a correct DER encoding.
+	//
+	// The workaround relies on the fact that the first octect that differs
+	// between the encoding of two group RDNs will end up being the encoded
+	// length which is directly related to the group name's length. So we'll
+	// sort such that shortest names come first.
+	groups := u.GetGroups()
```
Comment (liggitt) [inline pkg/cmd/server/crypto/crypto.go]: actually, make a new slice and copy the groups into it, so we don't share memory and introduce the possibility of races.

Comment (simo5) [reply pkg/cmd/server/crypto/crypto.go]: Done
