### PR TITLE
Use default scrub pod template for NFS recycler

### LINKED ISSUE #10230: NFS recycler pod does not have correct service account, fails
The pod is running as user 'pv-binder-controller' instead of 'pv-recycler-controller.' Only 'pv-recycler-controller' uses hostmount-anyuid SCC needed for permission to use nfs
Tracked it down to this change https://github.com/openshift/origin/commit/edbd37275083588ff64521b928f12f77d07c4c00#diff-62e1d6e1ea7f763bd41c44733aa2fba2L209 (If the fix is to just revert that, I can open a PR.)

from https://bugzilla.redhat.com/show_bug.cgi?id=1360658

### PR DESCRIPTION
**Pull request by wongma7**
Pretty sure the change from defaultScrubPod to the plain upstream pod template was unintentional, this reverts the one line. The important thing here for fixing #10230 is that ServiceAccountName gets set.

fixes #10230

### CODE REVIEW

**Comment by liggitt** [comment]
originally changed in https://github.com/openshift/origin/commit/edbd37275083588ff64521b928f12f77d07c4c00#diff-62e1d6e1ea7f763bd41c44733aa2fba2R226

LGTM, @markturansky can you take a second look?

File: pkg/cmd/server/kubernetes/master.go [hunk 1]
```diff
@@ -223,7 +223,7 @@ func probeRecyclableVolumePlugins(config componentconfig.VolumeConfiguration, na
 	nfsConfig := volume.VolumeConfig{
 		RecyclerMinimumTimeout:   int(config.PersistentVolumeRecyclerConfiguration.MinimumTimeoutNFS),
 		RecyclerTimeoutIncrement: int(config.PersistentVolumeRecyclerConfiguration.IncrementTimeoutNFS),
-		RecyclerPodTemplate:      volume.NewPersistentVolumeRecyclerPodTemplate(),
+		RecyclerPodTemplate:      defaultScrubPod,
```
Comment (markturansky) [inline pkg/cmd/server/kubernetes/master.go]: @liggitt This change is correct.  The default was already set on line 194 above and the overridden, so  this line should be the `defaultScrubPod` variable.

**Comment by markturansky** [comment]
LGTM

**Comment by liggitt** [comment]
[merge]

**Comment by wongma7** [comment]
`--- FAIL: TestGetImageStreamTag (1.23s)
panic: backend: cannot open database at /tmp/etcd253332776/member/snap/db (write /tmp/etcd253332776/member/snap/db: no space left on device) [recovered]`

@liggitt is this a flake? How do I get the bot to try again

**Comment by liggitt** [comment]
flake https://github.com/openshift/origin/issues/10302 in https://ci.openshift.redhat.com/jenkins/job/test_pr_origin/7640/
re[merge]

**Comment by wongma7** [comment]
https://github.com/openshift/origin/issues/9938
[merge]

**Comment by wongma7** [comment]
@liggitt @markturansky ping, ran into another flake and not sure what to do :-1:
