### PR TITLE
Retry deployment resource updates

### LINKED ISSUE #4678: Rolling updater init can fail with resource conflicts updating deployment
The rolling updater initialization can sometimes fail to prepare the deployment for update due to a resource conflict updating the deployment resource. The code should use retries so that the deployment doesn't fail unnecessarily.

### PR DESCRIPTION
**Pull request by ironcladlou**
Make the rolling updater more resilient to update conflicts by
retrying updates.

Fixes #4678

### CODE REVIEW

**Comment by ironcladlou** [comment]
@kargakis PTAL

File: pkg/deploy/strategy/rolling/rolling.go [hunk 1]
```diff
@@ -202,6 +210,24 @@ func (s *RollingDeploymentStrategy) Deploy(from *kapi.ReplicationController, to
 	return nil
 }
 
+// retry runs fn up to maxTries times until no error is returned, sleeping for
+// period between each try.
+func retry(maxTries int, period time.Duration, desc string, fn func() error) error {
```
Comment (kargakis) [inline pkg/deploy/strategy/rolling/rolling.go]: I think you want to use [wait.Poll](https://github.com/kubernetes/kubernetes/blob/0902f80f8b94fd23c66398118fcdf9e845c165b1/pkg/util/wait/wait.go#L49) which supports timeouts instead of maxTries

Comment (ironcladlou) [inline pkg/deploy/strategy/rolling/rolling.go]: Oh man, you're right. I can use that instead and remove all this other stuff.

Comment (ironcladlou) [inline pkg/deploy/strategy/rolling/rolling.go]: Refactored

File: pkg/deploy/strategy/rolling/rolling.go [hunk 2]
```diff
@@ -150,17 +151,25 @@ func (s *RollingDeploymentStrategy) Deploy(from *kapi.ReplicationController, to
 	//
 	// Related upstream issue:
 	// https://github.com/kubernetes/kubernetes/pull/7183
-	to, err = s.client.ReplicationControllers(to.Namespace).Get(to.Name)
+	err = wait.Poll(1*time.Second, 10*time.Second, func() (done bool, err error) {
```
Comment (kargakis) [inline pkg/deploy/strategy/rolling/rolling.go]: Move the times into constants?

File: pkg/deploy/strategy/rolling/rolling.go [hunk 3]
```diff
@@ -150,17 +151,25 @@ func (s *RollingDeploymentStrategy) Deploy(from *kapi.ReplicationController, to
...
+		existing, err := s.client.ReplicationControllers(to.Namespace).Get(to.Name)
+		if err != nil {
+			return false, fmt.Errorf("couldn't look up deployment %s: %s", deployutil.LabelForDeployment(to), err)
```
Comment (kargakis) [inline pkg/deploy/strategy/rolling/rolling.go]: Be careful because this is different than what you had before. With your custom retry func, you would retry on errors, here Poll will [exit](https://github.com/kubernetes/kubernetes/blob/0902f80f8b94fd23c66398118fcdf9e845c165b1/pkg/util/wait/wait.go#L73).

Comment (ironcladlou) [inline pkg/deploy/strategy/rolling/rolling.go]: Good catch, thanks

File: pkg/deploy/strategy/rolling/rolling.go (hunk 2 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/rolling/rolling.go]: Done; overridden in the test cases for speed.

File: pkg/deploy/strategy/rolling/rolling.go (hunk 3 above)
Comment (ironcladlou) [inline pkg/deploy/strategy/rolling/rolling.go]: I refactored this so that notfound errors are considered fatal while all others are logged and retried. PTAL.

File: pkg/deploy/strategy/rolling/rolling_test.go [hunk 4]
```diff
@@ -18,6 +18,8 @@ import (
 )
 
 func TestRolling_deployInitial(t *testing.T) {
+	annotationUpdatePeriod = 1 * time.Millisecond
```
Comment (kargakis) [inline pkg/deploy/strategy/rolling/rolling_test.go]: not sure about this:) i think it's better to have separate constants for master and separate for tests

File: pkg/deploy/strategy/rolling/rolling.go [hunk 5]
```diff
@@ -22,6 +24,9 @@ import (
 // https://github.com/kubernetes/kubernetes/issues/7851
 const sourceIdAnnotation = "kubectl.kubernetes.io/update-source-id"
 
+var annotationUpdatePeriod = 1 * time.Second
```
Comment (kargakis) [inline pkg/deploy/strategy/rolling/rolling.go]: Make these consts and use separate for testing

**Comment by ironcladlou** [comment]
@kargakis feedback addressed; refactored to use constants and injected state for the values.

**Comment by kargakis** [comment]
LGTM

**Comment by ironcladlou** [comment]
[merge]

**Comment by kargakis** [comment]
squash first? :)

**Comment by ironcladlou** [comment]
OMG, oops

**Comment by ironcladlou** [comment]
Squashed, [merge] again. Thanks, @kargakis
