### PR TITLE
Make client authorizations tolerant of UID changes

### LINKED ISSUE #15119: oauthclientauthorizations should be reentrant with user UID changes
User UID mismatches should restart the grant flow instead of failing with an internal error.

### PR DESCRIPTION
**Pull request by enj**
This change makes it so that if an OAuthClientAuthorization references a user with the wrong UID, that client authorization is deleted.  This UID mismatch is caused by the deletion and recreation of users.  Thus this makes it so that the "new" user is unaffected by the "old" user's client authorization.  The new user simply goes through the grant flow just as if no client authorization existed.

Signed-off-by: Monis Khan <mkhan@redhat.com>

Fixes #15119

---

/kind bug

/assign @liggitt @smarterclayton @simo5

@openshift/sig-security

### CODE REVIEW

**Comment by enj** [comment]
These are the only resources that I am aware of that can get "stuck" due to a UID mismatch.  197e2549b053a7b72eafe55fdb121234758643af is straight forward and probably non-controversial.  72ea40d470ab4cc8abf7539b5f2f0aa23f37d262 will probably require some discussion, though I could not think of how it could get exploited.

File: pkg/auth/oauth/registry/grantchecker.go [hunk 1]
```diff
@@ -30,12 +30,22 @@ func (c *ClientAuthorizationGrantChecker) HasAuthorizedClient(user user.Info, gr
...
 		return false, err
 	}
-	if len(authorization.UserUID) != 0 && authorization.UserUID != user.GetUID() {
-		return false, fmt.Errorf("user %s UID %s does not match stored client authorization value for UID %s", user.GetName(), user.GetUID(), authorization.UserUID)
+
+	// Validation prevents authorization.UserUID from being empty (and always has).
+	// However, user.GetUID() is empty during impersonation, meaning this flow does not work for impersonation.
+	// This is fine because no OAuth / grant flow works with impersonation in general.
+	if user.GetUID() != authorization.UserUID {
+		glog.Infof("%#v does not match stored client authorization %#v, attempting to delete stale authorization", user, authorization)
```
Comment (simo5) [inline pkg/auth/oauth/registry/grantchecker.go]: based on the comment above, won't this remove *valid* authorizations if a grant flow is performed after impersonation ?

Comment (simo5) [reply pkg/auth/oauth/registry/grantchecker.go]: If so we may want to just return an error (like before) if user.GetUID() is nil, and avoid deleting a valid authorization.

**Comment by simo5** [comment]
Except for the use of the term "reentrant" which does not convey what you are actually doing in this PR (perhaps use resistant ? or oblivious ? or selfhealing ? or tolerant ?) the approach looks generally good to me.

File: pkg/auth/oauth/registry/grantchecker.go [hunk 2]
```diff
@@ -30,12 +30,22 @@ func (c *ClientAuthorizationGrantChecker) HasAuthorizedClient(user user.Info, gr
...
+		if err := c.client.Delete(id, nil); err != nil && !errors.IsNotFound(err) {
```
Comment (liggitt) [inline pkg/auth/oauth/registry/grantchecker.go]: add delete options with a precondition that ensures the authorization we delete *this* oauthclientauthorization:

NewPreconditionDeleteOptions(authorization.UID)

determine how to handle an error from deletion (tolerate notfound, refetch/check on conflict?, fail on other errors)

**Comment by enj** [comment]
Spoke with @liggitt yesterday.  Client authorizations are downstream of users, and are owned by them.  Thus it is safe to delete them when the user gets replaced.

Identities are considered upstream of users, and are owned by the IDP, not the user.  It is not safe to delete these since they contain mapping information that would be lost.  Thus if something deletes / replaces / edits a user manually, it must take ownership of fixing the identity in whatever way is appropriate (delete, update, etc).

@simo5 please LGTM if you are happy.

**Comment by enj** [comment]
@stevekuznetsov why is the queue saying a green test is not green?

**Comment by stevekuznetsov** [comment]
Infra error, fixed
