### PR TITLE
The router command should keep support for hostPort

### LINKED ISSUE #8252: Router creation doesn't configure hostPort
When running:

```
oadm router management-metrics \
  -n default \
  --credentials=/etc/origin/master/openshift-router.kubeconfig \
  --service-account=router \
  --ports='443:5000' \
  --selector='kubernetes.io/hostname=vm-oshift01.vn1.bytenix.com' \
  --stats-port=1937 \
  --host-network=false
```

The resulting dc is not configured with the `hostPort` (5000):

```
# oc get dc management-metrics -o yaml
 ....
        name: router
        ports:
        - containerPort: 443
          protocol: TCP
```

##### Version
origin-1.1.4-0.git.0.9d8230b.el7.centos.x86_64
oc v1.1.4
kubernetes v1.2.0-origin-41-g91d3e75

##### Steps To Reproduce
Provided above.

##### Current Result
The `hostPort` is not configured (it was in the past).

##### Expected Result
The `hostPort` should be configured:

```
        name: router
        ports:
        - containerPort: 443
          hostPort: 5000
          protocol: TCP
```

cc @deads2k

### PR DESCRIPTION
**Pull request by smarterclayton**
Add a new `--host-ports=false` flag for people who don't want host port.
Restore the old functionality of setting hostPorts when
`--host-network=false`. Allow `--ports` to apply to hostPort AND the service
mappings (so user sees consistent ports on service port and hosts).
`--host-ports` defaults to true, but `--host-network` has priority.

If specifying `-o yaml` and SCC does not match, we should still output
yaml (but return a non-zero exit code).

Add more tests to router.sh for more scenarios.

Fixes #8252

@simon3z

### CODE REVIEW

**Comment by smarterclayton** [comment]
[test

**Comment by smarterclayton** [comment]
@liggitt

**Comment by smarterclayton** [comment]
[test]

File: pkg/cmd/admin/router/router.go [hunk 1]
```diff
@@ -470,6 +479,9 @@ func RunCmdRouter(f *clientcmd.Factory, cmd *cobra.Command, out io.Writer, cfg *
 			ContainerPort: cfg.StatsPort,
 			Protocol:      kapi.ProtocolTCP,
 		}
+		if cfg.HostPorts {
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: doesn't this need to check `!cfg.HostNetwork`? the flag help seemed to indicate it only does something if HostNetwork is false

File: pkg/cmd/admin/router/router.go [hunk 2]
```diff
@@ -705,6 +724,7 @@ func RunCmdRouter(f *clientcmd.Factory, cmd *cobra.Command, out io.Writer, cfg *
 
 	objects = app.AddServices(objects, false)
 	// set the service port to the provided hostport value
+	//if !cfg.HostPorts {
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: ?

File: pkg/cmd/admin/router/router.go [hunk 3]
```diff
@@ -536,8 +548,13 @@ func RunCmdRouter(f *clientcmd.Factory, cmd *cobra.Command, out io.Writer, cfg *
...
 
-	if err := validateServiceAccount(kClient, namespace, cfg.ServiceAccount, cfg.HostNetwork); err != nil {
-		return fmt.Errorf("router could not be created; %v", err)
+	if err := validateServiceAccount(kClient, namespace, cfg.ServiceAccount, cfg.HostNetwork, cfg.HostPorts); err != nil {
+		err = fmt.Errorf("router could not be created; %v", err)
+		if !output {
+			return err
+		}
+		fmt.Fprintf(cmd.Out(), "error: %v\n", err)
+		defaultOutputErr = cmdutil.ErrExit
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: this is so we still output all the objects in output mode, but also return an error code? won't writing the error to cmd.Out() mess up using the objects?

File: pkg/cmd/admin/router/router.go [hunk 4]
```diff
@@ -777,12 +797,21 @@ func validateServiceAccount(client *kclient.Client, ns string, serviceAccount st
 	for _, scc := range sccList.Items {
 		if admission.ConstraintAppliesTo(&scc, userInfo) {
 			switch {
+			case hostPorts && scc.AllowHostPorts:
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: shouldn't hostnetwork take priority? (I'm basing that on my reading of the flag help for `--host-ports` which made it sound like it only applied when `--host-network` was false)

**Comment by smarterclayton** [comment]
@ramr if you can look too (jordan changed registry today so he owns the big review)

File: pkg/cmd/admin/router/router.go (hunk 1 above)
Comment (smarterclayton) [inline pkg/cmd/admin/router/router.go]: oh, we should be setting hostPorts to false if hostNetwork is true.

File: pkg/cmd/admin/router/router.go (hunk 3 above)
Comment (smarterclayton) [inline pkg/cmd/admin/router/router.go]: cmd.Out() is stderr, unintuitively enough.

File: pkg/cmd/admin/router/router.go (hunk 4 above)
Comment (smarterclayton) [inline pkg/cmd/admin/router/router.go]: Added a condition for host network to set host ports false.

**Comment by smarterclayton** [comment]
Updated

File: pkg/cmd/admin/router/router.go [hunk 5]
```diff
@@ -267,6 +271,7 @@ func NewCmdRouter(f *clientcmd.Factory, parentName, name string, out io.Writer)
 	cmd.Flags().StringVar(&cfg.ExternalHostPartitionPath, "external-host-partition-path", cfg.ExternalHostPartitionPath, "If the underlying router implementation uses partitions for control boundaries, this is the path to use for that partition.")
 
 	cmd.MarkFlagFilename("credentials", "kubeconfig")
+	cmd.Flags().MarkDeprecated("credentials", "use --service-account to specify the service account the router will use to make API calls")
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: weird... I thought I already added this in master

File: pkg/cmd/admin/router/router.go [hunk 6]
```diff
@@ -457,10 +464,17 @@ func RunCmdRouter(f *clientcmd.Factory, cmd *cobra.Command, out io.Writer, cfg *
 		return fmt.Errorf("unable to parse --ports: %v", err)
 	}
 
-	// For the host networking case, ensure the ports match. Otherwise, remove host ports
-	for i := 0; i < len(ports); i++ {
-		if cfg.HostNetwork && ports[i].HostPort != 0 && ports[i].ContainerPort != ports[i].HostPort {
-			return fmt.Errorf("when using host networking mode, container port %d and host port %d must be equal", ports[i].ContainerPort, ports[i].HostPort)
+	// HostNetwork overrides HostPorts
+	if cfg.HostNetwork {
+		cfg.HostPorts = false
```
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: weird to mutate the options in Run()

Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: unfortunate we can't tell here if the user explicitly passed `--host-network --host-ports` (which should probably be a validation error?) or if we're just adjusting the default

File: pkg/cmd/admin/router/router.go (hunk 3 above)
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: of course it is

File: pkg/cmd/admin/router/router.go (hunk 6 above)
Comment (smarterclayton) [inline pkg/cmd/admin/router/router.go]: Until we refactor for Complete it's hard to do.

Comment (smarterclayton) [inline pkg/cmd/admin/router/router.go]: We can't, we'd need to refactor to options.  Net new flag, I'm ok with that
being a bug.

**Comment by smarterclayton** [comment]
[test]

**Comment by smarterclayton** [comment]
@knobuc @ramr router flake

```
Server message: accept tcp 172.18.0.188:8443: use of closed network
connectionServer message: accept tcp 172.18.0.188:8889: use of closed
network connectionStopping listener at 172.18.0.188:8080
Stopping listener at 172.18.0.188:8888
Stopping listener at 172.18.0.188:8889
Stopping listener at 172.18.0.188:8443
--- FAIL: TestRouter-2 (6.95s)
router_test.go:351: TC reencrypt failed: Get https://0.0.0.0: dial tcp
0.0.0.0:443: connection reset by peer
```

Shouldn't we *never* get a reset by peer?  Or is this the REUSEPORT handoff bug?

**Comment by smarterclayton** [comment]
[test]

File: pkg/cmd/admin/router/router.go (hunk 6 above)
Comment (liggitt) [inline pkg/cmd/admin/router/router.go]: Ok

**Comment by smarterclayton** [comment]
[merge]
