### PR TITLE
Tolerate deletion of resources during migration

### LINKED ISSUE #15122: Failure trying to storage migrate imagestream
Encountered in a upgrade from 3.6.116 to 3.6.133 on free-int cluster.

```
error:     imagestreams/pull-07042210z-gy -n ops-health-monitoring: the server could not find the requested resource (get imagestreams pull-07042210z-gy)
```

Maybe a race condition with imagestreams being deleted during migration?


Full error output:
```
TASK [Upgrade all storage] *****************************************************
task path: /home/opsmedic/aos-cd/tmp/tmp.rjT22dTJiR/openshift-ansible_extract/playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml:11
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/commands/command.py
<54.147.205.250> ESTABLISH SSH CONNECTION FOR USER: root
<54.147.205.250> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/opsmedic/.ansible/cp/ansible-ssh-%h-%p-%r 54.147.205.250 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [free-int-master-3c664]: FAILED! => {
    "changed": true, 
    "cmd": [
        "oc", 
        "adm", 
        "--config=/etc/origin/master/admin.kubeconfig", 
        "migrate", 
        "storage", 
        "--include=*", 
        "--confirm"
    ], 
    "delta": "0:37:13.586299", 
    "end": "2017-07-04 22:35:47.082837", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_raw_params": "oc adm --config=/etc/origin/master/admin.kubeconfig migrate storage --include=* --confirm", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 1, 
    "start": "2017-07-04 21:58:33.496538", 
    "stderr": "error: exit directly", 
    "stdout": "error:     imagestreams/pull-07042210z-gy -n ops-health-monitoring: the server could not find the requested resource (get imagestreams pull-07042210z-gy)\nerror:     oauthclientauthorizations/arubinge@redhat.com:launchpad : OAuthClientAuthorization \"arubinge@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:boot-health-check-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:boot-health-check-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:boot-http-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:boot-http-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:hc-boot-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:hc-boot-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:hc-swarm-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:hc-swarm-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:oso-fabric8slave-test:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:oso-fabric8slave-test:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:oso-jenkins32-test:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:oso-jenkins32-test:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:test-vertx-pipelines:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:test-vertx-pipelines:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:testvertx:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:testvertx:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-healthcheck-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-healthcheck-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-32bit:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-32bit:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-alrubinger:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-alrubinger:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-image:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-image:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-memerror-alr:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-memerror-alr:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-memerror:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-memerror:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-oso-hooks:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-oso-hooks:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-osofree:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-osofree:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertxhttp-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertxhttp-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertxhttpapi:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertxhttpapi:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/bingli-1:system:serviceaccount:binglifjdw:jenkinsbingli : OAuthClientAuthorization \"bingli-1:system:serviceaccount:binglifjdw:jenkinsbingli\" is invalid: clientName: Internal error: serviceaccounts \"jenkinsbingli\" not found\nerror:     oauthclientauthorizations/chuyu@redhat.com:system:serviceaccount:chuyutest:jenkins : OAuthClientAuthorization \"chuyu@redhat.com:system:serviceaccount:chuyutest:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/cmoulliard@redhat.com:system:serviceaccount:zz1:jenkins : OAuthClientAuthorization \"cmoulliard@redhat.com:system:serviceaccount:zz1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dgutride:system:serviceaccount:dgutride-jenkins:jenkins : OAuthClientAuthorization \"dgutride:system:serviceaccount:dgutride-jenkins:jenkins\" is invalid: clientName: Internal error: system:serviceaccount:dgutride-jenkins:jenkins has no redirectURIs; set serviceaccounts.openshift.io/oauth-redirecturi.<some-value>=<redirect> or create a dynamic URI using serviceaccounts.openshift.io/oauth-redirectreference.<some-value>=<reference>\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan1:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan2:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan3:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan3:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan7:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan7:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan8:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan8:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan9:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan9:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyantest:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyantest:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/edewit@redhat.com:launchpad : OAuthClientAuthorization \"edewit@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/gtrikler@redhat.com:launchpad : OAuthClientAuthorization \"gtrikler@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/gtrikler@redhat.com:system:serviceaccount:tmp-sb-health:jenkins : OAuthClientAuthorization \"gtrikler@redhat.com:system:serviceaccount:tmp-sb-health:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jastrachan:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"jastrachan:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:launchpad : OAuthClientAuthorization \"jbalunas@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:boot-healthcheck-01:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:boot-healthcheck-01:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:health-booster-swarm:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:health-booster-swarm:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:rest-vertx-demo:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:rest-vertx-demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:swarm-http-demo:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:swarm-http-demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:vert-health-01:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:vert-health-01:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jclingan@redhat.com:system:serviceaccount:demo-swarm-online:jenkins : OAuthClientAuthorization \"jclingan@redhat.com:system:serviceaccount:demo-swarm-online:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jclingan@redhat.com:system:serviceaccount:demo-vertx-online:jenkins : OAuthClientAuthorization \"jclingan@redhat.com:system:serviceaccount:demo-vertx-online:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/jf.cron0@gmail.com:system:serviceaccount:jf-cron0-jenkins:jenkins : OAuthClientAuthorization \"jf.cron0@gmail.com:system:serviceaccount:jf-cron0-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/lfuka:launchpad : OAuthClientAuthorization \"lfuka:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/lthon@redhat.com:launchpad : OAuthClientAuthorization \"lthon@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/lthon@redhat.com:system:serviceaccount:test-1:jenkins : OAuthClientAuthorization \"lthon@redhat.com:system:serviceaccount:test-1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/lthon@redhat.com:system:serviceaccount:test-2:jenkins : OAuthClientAuthorization \"lthon@redhat.com:system:serviceaccount:test-2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/michal-9:system:serviceaccount:michal-9-jenkins:jenkins : OAuthClientAuthorization \"michal-9:system:serviceaccount:michal-9-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/mmasters1@redhat.com:system:serviceaccount:mmasters3:jenkins : OAuthClientAuthorization \"mmasters1@redhat.com:system:serviceaccount:mmasters3:jenkins\" is invalid: clientName: Internal error: system:serviceaccount:mmasters3:jenkins has no redirectURIs; set serviceaccounts.openshift.io/oauth-redirecturi.<some-value>=<redirect> or create a dynamic URI using serviceaccounts.openshift.io/oauth-redirectreference.<some-value>=<reference>\nerror:     oauthclientauthorizations/pmuir-demo:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"pmuir-demo:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/pmuir-launch:launchpad : OAuthClientAuthorization \"pmuir-launch:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/rbehera-1:system:serviceaccount:default-foo:jenkins : OAuthClientAuthorization \"rbehera-1:system:serviceaccount:default-foo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-ggastald:launchpad : OAuthClientAuthorization \"rhn-support-ggastald:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:demo-ggastald:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:demo-ggastald:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:hc:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:hc:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-jrawling:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"rhn-support-jrawling:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-jrawling:system:serviceaccount:rhn-support-jrawling-vxwe-jenkins:jenkins : OAuthClientAuthorization \"rhn-support-jrawling:system:serviceaccount:rhn-support-jrawling-vxwe-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/rhn-support-pmuir:launchpad : OAuthClientAuthorization \"rhn-support-pmuir:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/skrupa-1:launchpad : OAuthClientAuthorization \"skrupa-1:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/skrupa-1:system:serviceaccount:vx2:jenkins : OAuthClientAuthorization \"skrupa-1:system:serviceaccount:vx2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/sspeiche@redhat.com:system:serviceaccount:p1:jenkins : OAuthClientAuthorization \"sspeiche@redhat.com:system:serviceaccount:p1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/tschotan@redhat.com:launchpad : OAuthClientAuthorization \"tschotan@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/tschotan@redhat.com:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"tschotan@redhat.com:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/wzheng@redhat.com:system:serviceaccount:wzheng123:jenkins : OAuthClientAuthorization \"wzheng@redhat.com:system:serviceaccount:wzheng123:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/wzheng@redhat.com:system:serviceaccount:wzheng2:jenkins : OAuthClientAuthorization \"wzheng@redhat.com:system:serviceaccount:wzheng2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/xipang-1:system:serviceaccount:xipang-07:jenkins : OAuthClientAuthorization \"xipang-1:system:serviceaccount:xipang-07:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/xiuwang-1:system:serviceaccount:xiuwang:jenkins : OAuthClientAuthorization \"xiuwang-1:system:serviceaccount:xiuwang:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/xiuwang:system:serviceaccount:xiuwang1:jenkins : OAuthClientAuthorization \"xiuwang:system:serviceaccount:xiuwang1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/xiuwang:system:serviceaccount:xiuwang:jenkins : OAuthClientAuthorization \"xiuwang:system:serviceaccount:xiuwang:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/yufchang:system:serviceaccount:cindy:jenkins : OAuthClientAuthorization \"yufchang:system:serviceaccount:cindy:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/zach.rhoads@amentra.com:launchpad : OAuthClientAuthorization \"zach.rhoads@amentra.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found\nerror:     oauthclientauthorizations/zach.rhoads@amentra.com:system:serviceaccount:demo4265:jenkins : OAuthClientAuthorization \"zach.rhoads@amentra.com:system:serviceaccount:demo4265:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/zach.rhoads@amentra.com:system:serviceaccount:demo4272:jenkins : OAuthClientAuthorization \"zach.rhoads@amentra.com:system:serviceaccount:demo4272:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/zhezli-10:system:serviceaccount:test10-5:jenkins : OAuthClientAuthorization \"zhezli-10:system:serviceaccount:test10-5:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     oauthclientauthorizations/zhezli-1:system:serviceaccount:jks:jenkins : OAuthClientAuthorization \"zhezli-1:system:serviceaccount:jks:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0--gn: namespaces \"0--gn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 04n3r: namespaces \"04n3r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 04zv9: namespaces \"04zv9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 07dlb: namespaces \"07dlb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 08mx7: namespaces \"08mx7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0ad8p: namespaces \"0ad8p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0b4i7: namespaces \"0b4i7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0bd5j: namespaces \"0bd5j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0bgnp: namespaces \"0bgnp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0bxs9: namespaces \"0bxs9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0d530: namespaces \"0d530\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0e5po: namespaces \"0e5po\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0ftpd: namespaces \"0ftpd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0hqp0: namespaces \"0hqp0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0lfzl: namespaces \"0lfzl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0n20m: namespaces \"0n20m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0nd8x: namespaces \"0nd8x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0ofmi: namespaces \"0ofmi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0otxs: namespaces \"0otxs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0q8bn: namespaces \"0q8bn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0uode: namespaces \"0uode\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0vhje: namespaces \"0vhje\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0w35h: namespaces \"0w35h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0x-ls: namespaces \"0x-ls\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0xhrv: namespaces \"0xhrv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0yyb5: namespaces \"0yyb5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 0z2zc: namespaces \"0z2zc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1-tc4: namespaces \"1-tc4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 11hap: namespaces \"11hap\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 13okc: namespaces \"13okc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 17gms: namespaces \"17gms\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 17w6k: namespaces \"17w6k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 17x0a: namespaces \"17x0a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 18bvu: namespaces \"18bvu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 18pji: namespaces \"18pji\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1d8wu: namespaces \"1d8wu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1dg1k: namespaces \"1dg1k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1f84x: namespaces \"1f84x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1fh1i: namespaces \"1fh1i\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1gcfs: namespaces \"1gcfs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1ksa3: namespaces \"1ksa3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1mwlh: namespaces \"1mwlh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1n6kh: namespaces \"1n6kh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1nhqz: namespaces \"1nhqz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1pef6: namespaces \"1pef6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1u2gu: namespaces \"1u2gu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1umj1: namespaces \"1umj1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 1w9lp: namespaces \"1w9lp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2-mz0: namespaces \"2-mz0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2059r: namespaces \"2059r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 20rzl: namespaces \"20rzl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 21i4q: namespaces \"21i4q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 22n6p: namespaces \"22n6p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 243bx: namespaces \"243bx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 24cy4: namespaces \"24cy4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 27a7d: namespaces \"27a7d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 28y7z: namespaces \"28y7z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2cjky: namespaces \"2cjky\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2evpx: namespaces \"2evpx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2f-e4: namespaces \"2f-e4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2jo54: namespaces \"2jo54\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2n-ex: namespaces \"2n-ex\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2nvvs: namespaces \"2nvvs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2qahp: namespaces \"2qahp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2qcqa: namespaces \"2qcqa\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2rq2z: namespaces \"2rq2z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2s1gg: namespaces \"2s1gg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2uctt: namespaces \"2uctt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2ut25: namespaces \"2ut25\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2v9gf: namespaces \"2v9gf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2xemy: namespaces \"2xemy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2xod9: namespaces \"2xod9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2xxeg: namespaces \"2xxeg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2y2lt: namespaces \"2y2lt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 2z1fw: namespaces \"2z1fw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3-oad: namespaces \"3-oad\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3-yjm: namespaces \"3-yjm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 308hm: namespaces \"308hm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 35r-n: namespaces \"35r-n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 36nkg: namespaces \"36nkg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3h8uj: namespaces \"3h8uj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3kte9: namespaces \"3kte9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3muja: namespaces \"3muja\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3nnqt: namespaces \"3nnqt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3nv8j: namespaces \"3nv8j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3oa44: namespaces \"3oa44\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3ouit: namespaces \"3ouit\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3rppl: namespaces \"3rppl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3rsxd: namespaces \"3rsxd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3rz8p: namespaces \"3rz8p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3sbh9: namespaces \"3sbh9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3tf8k: namespaces \"3tf8k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3u5z0: namespaces \"3u5z0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3u92b: namespaces \"3u92b\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3uez4: namespaces \"3uez4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3w0lt: namespaces \"3w0lt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3w4ru: namespaces \"3w4ru\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3y3ik: namespaces \"3y3ik\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3ypiy: namespaces \"3ypiy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3zq2b: namespaces \"3zq2b\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 3zy34: namespaces \"3zy34\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4-xuw: namespaces \"4-xuw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 40ul3: namespaces \"40ul3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 40ymz: namespaces \"40ymz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 42u-n: namespaces \"42u-n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 44vu0: namespaces \"44vu0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 49ps5: namespaces \"49ps5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4ahou: namespaces \"4ahou\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4az3f: namespaces \"4az3f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4c26f: namespaces \"4c26f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4corm: namespaces \"4corm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4dngd: namespaces \"4dngd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4fm3m: namespaces \"4fm3m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4hzkw: namespaces \"4hzkw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4m8z8: namespaces \"4m8z8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4ne7z: namespaces \"4ne7z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4rd5y: namespaces \"4rd5y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4tupz: namespaces \"4tupz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4vfok: namespaces \"4vfok\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4xi7o: namespaces \"4xi7o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 4z9y2: namespaces \"4z9y2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 556jr: namespaces \"556jr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 55cch: namespaces \"55cch\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5fskr: namespaces \"5fskr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5j94k: namespaces \"5j94k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5mgj7: namespaces \"5mgj7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5miof: namespaces \"5miof\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5nytu: namespaces \"5nytu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5oamj: namespaces \"5oamj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5p5me: namespaces \"5p5me\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5q-mp: namespaces \"5q-mp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5rmeu: namespaces \"5rmeu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5t0x9: namespaces \"5t0x9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5tz5u: namespaces \"5tz5u\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 5vycg: namespaces \"5vycg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 60bfc: namespaces \"60bfc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 637pq: namespaces \"637pq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 647m0: namespaces \"647m0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 65qwz: namespaces \"65qwz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 65u7n: namespaces \"65u7n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 68-3m: namespaces \"68-3m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6agt8: namespaces \"6agt8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6fcwl: namespaces \"6fcwl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6gjtb: namespaces \"6gjtb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6he28: namespaces \"6he28\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6hfgc: namespaces \"6hfgc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6i5od: namespaces \"6i5od\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6ii-u: namespaces \"6ii-u\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6jenb: namespaces \"6jenb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6lh6a: namespaces \"6lh6a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6psum: namespaces \"6psum\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6qgod: namespaces \"6qgod\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6t4nx: namespaces \"6t4nx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6tyg3: namespaces \"6tyg3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6uauh: namespaces \"6uauh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6wtpm: namespaces \"6wtpm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6wwu5: namespaces \"6wwu5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 6zpxe: namespaces \"6zpxe\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 70fcr: namespaces \"70fcr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 70wil: namespaces \"70wil\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 72--g: namespaces \"72--g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 729qk: namespaces \"729qk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 72lnd: namespaces \"72lnd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7577v: namespaces \"7577v\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 79cac: namespaces \"79cac\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7aymi: namespaces \"7aymi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7b0-y: namespaces \"7b0-y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7bhoy: namespaces \"7bhoy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7j42f: namespaces \"7j42f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7j7nd: namespaces \"7j7nd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7j9on: namespaces \"7j9on\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7k7yb: namespaces \"7k7yb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7kfwi: namespaces \"7kfwi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7m82d: namespaces \"7m82d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7pwh2: namespaces \"7pwh2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7pyzi: namespaces \"7pyzi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7tdfh: namespaces \"7tdfh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7u8xj: namespaces \"7u8xj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7wma1: namespaces \"7wma1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7wy-1: namespaces \"7wy-1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7x0mr: namespaces \"7x0mr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 7xual: namespaces \"7xual\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 84d5i: namespaces \"84d5i\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 85ww9: namespaces \"85ww9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8agr4: namespaces \"8agr4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8b1we: namespaces \"8b1we\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8bb4e: namespaces \"8bb4e\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8d0v9: namespaces \"8d0v9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8evpk: namespaces \"8evpk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8f6ju: namespaces \"8f6ju\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8fwon: namespaces \"8fwon\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8jzhh: namespaces \"8jzhh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8l7ub: namespaces \"8l7ub\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8o89j: namespaces \"8o89j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8px0m: namespaces \"8px0m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8tcdf: namespaces \"8tcdf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8tn1y: namespaces \"8tn1y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8wtlv: namespaces \"8wtlv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 8yb8n: namespaces \"8yb8n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9--n3: namespaces \"9--n3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9-1sn: namespaces \"9-1sn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9-kgt: namespaces \"9-kgt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 90jxz: namespaces \"90jxz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 91-wk: namespaces \"91-wk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 93ksz: namespaces \"93ksz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 98uvz: namespaces \"98uvz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 99egr: namespaces \"99egr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9arqt: namespaces \"9arqt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9b1qq: namespaces \"9b1qq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9b72d: namespaces \"9b72d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9bvtx: namespaces \"9bvtx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9dv-x: namespaces \"9dv-x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9j714: namespaces \"9j714\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9jhhm: namespaces \"9jhhm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9jzl6: namespaces \"9jzl6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9k7a5: namespaces \"9k7a5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9k847: namespaces \"9k847\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9lm37: namespaces \"9lm37\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9m3xw: namespaces \"9m3xw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9o6ec: namespaces \"9o6ec\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9r9y2: namespaces \"9r9y2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9s-0h: namespaces \"9s-0h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9s77c: namespaces \"9s77c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9snbl: namespaces \"9snbl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9uz88: namespaces \"9uz88\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9vbj9: namespaces \"9vbj9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9w8r0: namespaces \"9w8r0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9wa5s: namespaces \"9wa5s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n 9y501: namespaces \"9y501\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a-1mg: namespaces \"a-1mg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a-25f: namespaces \"a-25f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a1qms: namespaces \"a1qms\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a1uhz: namespaces \"a1uhz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a244w: namespaces \"a244w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a2qc2: namespaces \"a2qc2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a5aa3: namespaces \"a5aa3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a7qd9: namespaces \"a7qd9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a8-5c: namespaces \"a8-5c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n a8xtg: namespaces \"a8xtg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aaeh0: namespaces \"aaeh0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aas5r: namespaces \"aas5r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ab3p2: namespaces \"ab3p2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n adi6h: namespaces \"adi6h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n adlt7: namespaces \"adlt7\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n agupta-dem: namespaces \"agupta-dem\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-dem: namespaces \"agupta-dem\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n agupta-dem: namespaces \"agupta-dem\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo: namespaces \"agupta-demo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo2: namespaces \"agupta-demo2\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n agupta-demo3: namespaces \"agupta-demo3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo3: namespaces \"agupta-demo3\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n agupta-demo3: namespaces \"agupta-demo3\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n agupta-demo4: namespaces \"agupta-demo4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo4: namespaces \"agupta-demo4\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n agupta-demo4: namespaces \"agupta-demo4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-1: namespaces \"agupta-project-1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-2: namespaces \"agupta-project-2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-3: namespaces \"agupta-project-3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-test: namespaces \"agupta-test\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta-test5: namespaces \"agupta-test5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta1: namespaces \"agupta1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n agupta2: namespaces \"agupta2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aijqf: namespaces \"aijqf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aivdy: namespaces \"aivdy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n alr93: namespaces \"alr93\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n amdvk: namespaces \"amdvk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n antwo: namespaces \"antwo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aoiur: namespaces \"aoiur\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n aslak-dwpq: namespaces \"aslak-dwpq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aslak-dwpq: namespaces \"aslak-dwpq\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n aslak-dwpq: namespaces \"aslak-dwpq\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n aslak-gfau: namespaces \"aslak-gfau\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aslak-gfau: namespaces \"aslak-gfau\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n aslak-gfau: namespaces \"aslak-gfau\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n aug15: namespaces \"aug15\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n axhx5: namespaces \"axhx5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n axi7y: namespaces \"axi7y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n axpn0: namespaces \"axpn0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ay7pn: namespaces \"ay7pn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ayxi2: namespaces \"ayxi2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n b009a: namespaces \"b009a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n b0sys: namespaces \"b0sys\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n b6ymg: namespaces \"b6ymg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n b7pr5: namespaces \"b7pr5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n b8pjy: namespaces \"b8pjy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bad60: namespaces \"bad60\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bbs2ywbi: namespaces \"bbs2ywbi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bc7el: namespaces \"bc7el\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bcudh: namespaces \"bcudh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bdlof: namespaces \"bdlof\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bem8t: namespaces \"bem8t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bfdtx: namespaces \"bfdtx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bgo84: namespaces \"bgo84\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bhrhc: namespaces \"bhrhc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bitl0: namespaces \"bitl0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bj1v6: namespaces \"bj1v6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bl6xv: namespaces \"bl6xv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n blah-1: namespaces \"blah-1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n blah-2: namespaces \"blah-2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bldrw: namespaces \"bldrw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bnv4f: namespaces \"bnv4f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bphfa: namespaces \"bphfa\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bqyrp: namespaces \"bqyrp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bvclh: namespaces \"bvclh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bxwrh: namespaces \"bxwrh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n bzwhn: namespaces \"bzwhn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n c1tux: namespaces \"c1tux\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n c2ttz: namespaces \"c2ttz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n c4ci6: namespaces \"c4ci6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n c6z9p: namespaces \"c6z9p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n c9bth: namespaces \"c9bth\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n caiso: namespaces \"caiso\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n caovs: namespaces \"caovs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cgka7: namespaces \"cgka7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ch631: namespaces \"ch631\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n chfp0: namespaces \"chfp0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ci41i: namespaces \"ci41i\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cindypro: namespaces \"cindypro\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ckica: namespaces \"ckica\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cmr1c: namespaces \"cmr1c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cnpan: namespaces \"cnpan\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cpw62: namespaces \"cpw62\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ct2wr: namespaces \"ct2wr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cxw9f: namespaces \"cxw9f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cyiq1: namespaces \"cyiq1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n cyw86: namespaces \"cyw86\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n d-40c: namespaces \"d-40c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n d5169: namespaces \"d5169\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n d7-r0: namespaces \"d7-r0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n d9czj: namespaces \"d9czj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-3: namespaces \"dakinitest20170405-3\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dakinitest201704051: namespaces \"dakinitest201704051\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dakinitest201704052: namespaces \"dakinitest201704052\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dbfn3: namespaces \"dbfn3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ddy68: namespaces \"ddy68\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n demo-vertx-ggastald: namespaces \"demo-vertx-ggastald\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n df6-b: namespaces \"df6-b\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dgy7q: namespaces \"dgy7q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n difjk: namespaces \"difjk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dma: namespaces \"dma\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dnush: namespaces \"dnush\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dokuq: namespaces \"dokuq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dopvx: namespaces \"dopvx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dr67t: namespaces \"dr67t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dsb41: namespaces \"dsb41\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dsj6r: namespaces \"dsj6r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dtjcx: namespaces \"dtjcx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n du0gb: namespaces \"du0gb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dwnm5: namespaces \"dwnm5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dyi1c: namespaces \"dyi1c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dz6hl: namespaces \"dz6hl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dz7vn: namespaces \"dz7vn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n dzcme: namespaces \"dzcme\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e-h6d: namespaces \"e-h6d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e09iz: namespaces \"e09iz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e0kdr: namespaces \"e0kdr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e1ovy: namespaces \"e1ovy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e307n: namespaces \"e307n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e558n: namespaces \"e558n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e77qf: namespaces \"e77qf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e8go1: namespaces \"e8go1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e8t45: namespaces \"e8t45\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e8zrx: namespaces \"e8zrx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n e94mn: namespaces \"e94mn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ea1is: namespaces \"ea1is\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ecj5n: namespaces \"ecj5n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ee4ve: namespaces \"ee4ve\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n eg2ds: namespaces \"eg2ds\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n egsj7: namespaces \"egsj7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ehqkq: namespaces \"ehqkq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ej47q: namespaces \"ej47q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ekr47: namespaces \"ekr47\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n en4rt: namespaces \"en4rt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n eows0: namespaces \"eows0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ep8kq: namespaces \"ep8kq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n estyl: namespaces \"estyl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n et6qr: namespaces \"et6qr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n eu6wx: namespaces \"eu6wx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ev5-o: namespaces \"ev5-o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ewk6d: namespaces \"ewk6d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n eybak: namespaces \"eybak\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f-1hl: namespaces \"f-1hl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f-aqf: namespaces \"f-aqf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f211q: namespaces \"f211q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f3mtn: namespaces \"f3mtn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f3xn7: namespaces \"f3xn7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f42nb: namespaces \"f42nb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f42x0: namespaces \"f42x0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f77go: namespaces \"f77go\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f7lt9: namespaces \"f7lt9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f87j5: namespaces \"f87j5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f8cp9: namespaces \"f8cp9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f8p36: namespaces \"f8p36\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f9-bs: namespaces \"f9-bs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n f983t: namespaces \"f983t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fa72m: namespaces \"fa72m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fa9uf: namespaces \"fa9uf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fde98: namespaces \"fde98\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fdi0d: namespaces \"fdi0d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fdy0s: namespaces \"fdy0s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fekxt: namespaces \"fekxt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ff7sw: namespaces \"ff7sw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fflna: namespaces \"fflna\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fiajs: namespaces \"fiajs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fj4ck: namespaces \"fj4ck\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fjkd4: namespaces \"fjkd4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fjn97: namespaces \"fjn97\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fjokv: namespaces \"fjokv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fmox1: namespaces \"fmox1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fnk97: namespaces \"fnk97\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fowow: namespaces \"fowow\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fpj5y: namespaces \"fpj5y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fpvji: namespaces \"fpvji\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fs35z: namespaces \"fs35z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ft77k: namespaces \"ft77k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ftvj8: namespaces \"ftvj8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fu5zd: namespaces \"fu5zd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fxcy8: namespaces \"fxcy8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n fxwwp: namespaces \"fxwwp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n g33k2: namespaces \"g33k2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n g5bsz: namespaces \"g5bsz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n g63te: namespaces \"g63te\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n g82sx: namespaces \"g82sx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ga4g5: namespaces \"ga4g5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ggwn7: namespaces \"ggwn7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gh0qr: namespaces \"gh0qr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ghb6e: namespaces \"ghb6e\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gke4g: namespaces \"gke4g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n glt2i: namespaces \"glt2i\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gnzde: namespaces \"gnzde\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gshxs: namespaces \"gshxs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gufdb: namespaces \"gufdb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gwe40: namespaces \"gwe40\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gwg0c: namespaces \"gwg0c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gwtff: namespaces \"gwtff\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gxczk: namespaces \"gxczk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n gxkwg: namespaces \"gxkwg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h-po2: namespaces \"h-po2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h2j31: namespaces \"h2j31\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h31rw: namespaces \"h31rw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h3bmy: namespaces \"h3bmy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h4ss9: namespaces \"h4ss9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n h5gc4: namespaces \"h5gc4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n haf0q: namespaces \"haf0q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hdqff: namespaces \"hdqff\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n hello: namespaces \"hello\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hello: namespaces \"hello\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n hello: namespaces \"hello\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hello2: namespaces \"hello2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hgsuc: namespaces \"hgsuc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hh1tv: namespaces \"hh1tv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hhrdj: namespaces \"hhrdj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hin6y: namespaces \"hin6y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hk2r1: namespaces \"hk2r1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hl-09: namespaces \"hl-09\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hongli2: namespaces \"hongli2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n honrt: namespaces \"honrt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hqx9g: namespaces \"hqx9g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hu33r: namespaces \"hu33r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hu3g4: namespaces \"hu3g4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hwgb8: namespaces \"hwgb8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hwpsz: namespaces \"hwpsz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hyncn: namespaces \"hyncn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hz88r: namespaces \"hz88r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n hzozd: namespaces \"hzozd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i19rs: namespaces \"i19rs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i29py: namespaces \"i29py\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i4ro8: namespaces \"i4ro8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i5kuo: namespaces \"i5kuo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i67v6: namespaces \"i67v6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n i8z-3: namespaces \"i8z-3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ia8ga: namespaces \"ia8ga\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ias9o: namespaces \"ias9o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ibp6z: namespaces \"ibp6z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ievmn: namespaces \"ievmn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ifvk6psku6mz1z26nhhl3-qja1qlmzv4mm8wqas5jvromj: namespaces \"ifvk6psku6mz1z26nhhl3-qja1qlmzv4mm8wqas5jvromj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ifw0z: namespaces \"ifw0z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ih84t: namespaces \"ih84t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n iito6: namespaces \"iito6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ikv93: namespaces \"ikv93\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ikz-7: namespaces \"ikz-7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ipacd: namespaces \"ipacd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n iqemp: namespaces \"iqemp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n iu1j4: namespaces \"iu1j4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j168t: namespaces \"j168t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j1df3: namespaces \"j1df3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j3wip: namespaces \"j3wip\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j4yh5: namespaces \"j4yh5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j52y2: namespaces \"j52y2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j9dqg: namespaces \"j9dqg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n j9l2t: namespaces \"j9l2t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ja6ao: namespaces \"ja6ao\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jcpsj: namespaces \"jcpsj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n je7iy: namespaces \"je7iy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jhcdn: namespaces \"jhcdn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jhmpv: namespaces \"jhmpv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jjhim: namespaces \"jjhim\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jjlen: namespaces \"jjlen\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jktm6: namespaces \"jktm6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jompb: namespaces \"jompb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n joz6t: namespaces \"joz6t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jpil3: namespaces \"jpil3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jqgen: namespaces \"jqgen\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jqlu5: namespaces \"jqlu5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jsrxk: namespaces \"jsrxk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ju9l0: namespaces \"ju9l0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n juzhao: namespaces \"juzhao\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jvm: namespaces \"jvm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jwfsv: namespaces \"jwfsv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jxbrh: namespaces \"jxbrh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n jz4rt: namespaces \"jz4rt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k-vuu: namespaces \"k-vuu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k0a5e: namespaces \"k0a5e\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k1z4c: namespaces \"k1z4c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k5a2v: namespaces \"k5a2v\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k5p87: namespaces \"k5p87\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k6gdg: namespaces \"k6gdg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k73yo: namespaces \"k73yo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k7c0y: namespaces \"k7c0y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n k85kc: namespaces \"k85kc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kax3a: namespaces \"kax3a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kcf6c: namespaces \"kcf6c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kkghl: namespaces \"kkghl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kkiel: namespaces \"kkiel\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kl0ir: namespaces \"kl0ir\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n klqk0: namespaces \"klqk0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kmbs4: namespaces \"kmbs4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kmhbi: namespaces \"kmhbi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kq3qb: namespaces \"kq3qb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ks818: namespaces \"ks818\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ksfow: namespaces \"ksfow\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ksggd: namespaces \"ksggd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kvsgv: namespaces \"kvsgv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kvtos: namespaces \"kvtos\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kywkm: namespaces \"kywkm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n kzspp: namespaces \"kzspp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l-hlw: namespaces \"l-hlw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l2yoh: namespaces \"l2yoh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l2z30: namespaces \"l2z30\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l3wub: namespaces \"l3wub\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l5f0s: namespaces \"l5f0s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l6qxn: namespaces \"l6qxn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n l882w: namespaces \"l882w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n laa7m: namespaces \"laa7m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n le287: namespaces \"le287\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lf5io: namespaces \"lf5io\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lf6p5: namespaces \"lf6p5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lgbm2: namespaces \"lgbm2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lgz8p: namespaces \"lgz8p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lio5s: namespaces \"lio5s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ljm4g: namespaces \"ljm4g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ll483: namespaces \"ll483\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lm354: namespaces \"lm354\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lnz13: namespaces \"lnz13\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lpsvr: namespaces \"lpsvr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lt27o: namespaces \"lt27o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ltia4: namespaces \"ltia4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lu1kr: namespaces \"lu1kr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lui5x: namespaces \"lui5x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lxixf: namespaces \"lxixf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n lxk12: namespaces \"lxk12\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m-gzk: namespaces \"m-gzk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m20vo: namespaces \"m20vo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m2omu: namespaces \"m2omu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m56qy: namespaces \"m56qy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m6hnc: namespaces \"m6hnc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m6n5n: namespaces \"m6n5n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m6r-m: namespaces \"m6r-m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m7aqt: namespaces \"m7aqt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m9jco: namespaces \"m9jco\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n m9rac: namespaces \"m9rac\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mb5x9: namespaces \"mb5x9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n md2s8: namespaces \"md2s8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n me13x: namespaces \"me13x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mfgrj: namespaces \"mfgrj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mg9dq: namespaces \"mg9dq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mj0hb: namespaces \"mj0hb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mj9ua: namespaces \"mj9ua\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mk: namespaces \"mk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mkvp6: namespaces \"mkvp6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mo47k: namespaces \"mo47k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mr7il: namespaces \"mr7il\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mrjih: namespaces \"mrjih\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mrp-s: namespaces \"mrp-s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ms24h: namespaces \"ms24h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mtpy1: namespaces \"mtpy1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mvyqk: namespaces \"mvyqk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mwxuh: namespaces \"mwxuh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mxj4m: namespaces \"mxj4m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n mzdja: namespaces \"mzdja\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n n0gnp: namespaces \"n0gnp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n n0jjp: namespaces \"n0jjp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n n4m1rp74y5bmiapgw9yyx60fd07dtxoxdlxkyeiq2y89h69: namespaces \"n4m1rp74y5bmiapgw9yyx60fd07dtxoxdlxkyeiq2y89h69\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n n4nnf: namespaces \"n4nnf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n n6ttq: namespaces \"n6ttq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nav3h: namespaces \"nav3h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nb358: namespaces \"nb358\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ne068: namespaces \"ne068\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n netqr: namespaces \"netqr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ngu4k: namespaces \"ngu4k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n njtjx: namespaces \"njtjx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nk0ub: namespaces \"nk0ub\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nm337: namespaces \"nm337\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n noy9p: namespaces \"noy9p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n npvu6: namespaces \"npvu6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nspyl: namespaces \"nspyl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ntbne: namespaces \"ntbne\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nxadm: namespaces \"nxadm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n nz0-o: namespaces \"nz0-o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o-57e: namespaces \"o-57e\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o1jc3: namespaces \"o1jc3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o1r6x: namespaces \"o1r6x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o49xu: namespaces \"o49xu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o4wmn: namespaces \"o4wmn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o5gsu: namespaces \"o5gsu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o6pzs: namespaces \"o6pzs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o79mh: namespaces \"o79mh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n o8ego: namespaces \"o8ego\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n obdhg: namespaces \"obdhg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n of42a: namespaces \"of42a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n of62d: namespaces \"of62d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n oh8rh: namespaces \"oh8rh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n oii0q: namespaces \"oii0q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n oksio: namespaces \"oksio\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n omis9: namespaces \"omis9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n oq84c: namespaces \"oq84c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n otur0: namespaces \"otur0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ox7mk: namespaces \"ox7mk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n oxwgu: namespaces \"oxwgu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p1cwe: namespaces \"p1cwe\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p1w9n: namespaces \"p1w9n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p2mj6: namespaces \"p2mj6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p2mx7: namespaces \"p2mx7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p5nfi: namespaces \"p5nfi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n p9562: namespaces \"p9562\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pc8n4: namespaces \"pc8n4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pczk1: namespaces \"pczk1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pdy27: namespaces \"pdy27\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pee-6: namespaces \"pee-6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pfjvn: namespaces \"pfjvn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pfmqw: namespaces \"pfmqw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pg0xp: namespaces \"pg0xp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pgtwx: namespaces \"pgtwx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n phno6: namespaces \"phno6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pk6t4: namespaces \"pk6t4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pkxe1: namespaces \"pkxe1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ppy6r: namespaces \"ppy6r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n prkm3: namespaces \"prkm3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pro-lc: namespaces \"pro-lc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pucbt: namespaces \"pucbt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n puqvo: namespaces \"puqvo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n puu9x: namespaces \"puu9x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pw-10: namespaces \"pw-10\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n px3ln: namespaces \"px3ln\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pxac9nsf: namespaces \"pxac9nsf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n py18j: namespaces \"py18j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pyky3: namespaces \"pyky3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n pyzwg: namespaces \"pyzwg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n q-e0dzyz144nq2m9406g5dmrykimwobrbm2g7x86tzx1pbwr1417hhnl13lcin2: namespaces \"q-e0dzyz144nq2m9406g5dmrykimwobrbm2g7x86tzx1pbwr1417hhnl13lcin2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n q0hxy: namespaces \"q0hxy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n q1a71: namespaces \"q1a71\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n q5idx: namespaces \"q5idx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n q778j: namespaces \"q778j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qep3p: namespaces \"qep3p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qezxn: namespaces \"qezxn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qluqm: namespaces \"qluqm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qlxp2: namespaces \"qlxp2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qmsjx: namespaces \"qmsjx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qnj8w: namespaces \"qnj8w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qnslt: namespaces \"qnslt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qo6x5: namespaces \"qo6x5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qpond: namespaces \"qpond\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n quy18: namespaces \"quy18\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qz8ci: namespaces \"qz8ci\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n qztfz: namespaces \"qztfz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r-01p: namespaces \"r-01p\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r0svq: namespaces \"r0svq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r4lpi: namespaces \"r4lpi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r4w2g: namespaces \"r4w2g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r6kwk: namespaces \"r6kwk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r8q1d: namespaces \"r8q1d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r9ixm: namespaces \"r9ixm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n r9tq7: namespaces \"r9tq7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rb34y: namespaces \"rb34y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rbm8v: namespaces \"rbm8v\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rd6z9: namespaces \"rd6z9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rhn-support-jrawling-iukr: namespaces \"rhn-support-jrawling-iukr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rhn-support-jrawling-pqku: namespaces \"rhn-support-jrawling-pqku\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ri6ow: namespaces \"ri6ow\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rlp3n: namespaces \"rlp3n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rn86m: namespaces \"rn86m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rnae2: namespaces \"rnae2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rph9d: namespaces \"rph9d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rq91k: namespaces \"rq91k\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rqglo: namespaces \"rqglo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rsxja: namespaces \"rsxja\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rt99m: namespaces \"rt99m\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rvhkp: namespaces \"rvhkp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rxrmf: namespaces \"rxrmf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ry9cw: namespaces \"ry9cw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n rym2r: namespaces \"rym2r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s0405: namespaces \"s0405\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s129t: namespaces \"s129t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s2fls: namespaces \"s2fls\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s2oxu: namespaces \"s2oxu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s76sw: namespaces \"s76sw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s8-av: namespaces \"s8-av\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s9g1v: namespaces \"s9g1v\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s9oqc: namespaces \"s9oqc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n s9qgs: namespaces \"s9qgs\" not found\nerror:     rolebindingrestrictions/match-own-service-account-group -n sample: namespaces \"sample\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sample: namespaces \"sample\" not found\nerror:     rolebindingrestrictions/match-project-admin-user -n sample: namespaces \"sample\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n scpmv: namespaces \"scpmv\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ser0a: namespaces \"ser0a\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sgzes: namespaces \"sgzes\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sicid: namespaces \"sicid\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sj2zb: namespaces \"sj2zb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sk58d: namespaces \"sk58d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ski72: namespaces \"ski72\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sl4h1: namespaces \"sl4h1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sm-sp: namespaces \"sm-sp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n smtgb: namespaces \"smtgb\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sn-b7: namespaces \"sn-b7\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sntfd: namespaces \"sntfd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sos4o: namespaces \"sos4o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sox1r: namespaces \"sox1r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ss1ro: namespaces \"ss1ro\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ssrl1: namespaces \"ssrl1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n suvnf: namespaces \"suvnf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n svm-9: namespaces \"svm-9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n svuws: namespaces \"svuws\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n swb3u: namespaces \"swb3u\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n sy9c5: namespaces \"sy9c5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n syens: namespaces \"syens\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t0uz1: namespaces \"t0uz1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t2-6b: namespaces \"t2-6b\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t55tf: namespaces \"t55tf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t69f5: namespaces \"t69f5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t758n: namespaces \"t758n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t7z9e: namespaces \"t7z9e\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n t966u: namespaces \"t966u\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tamxl: namespaces \"tamxl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n td7ki: namespaces \"td7ki\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n test3: namespaces \"test3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n test4: namespaces \"test4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n test5: namespaces \"test5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n test6: namespaces \"test6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tff0x: namespaces \"tff0x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tfvax: namespaces \"tfvax\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tfzls: namespaces \"tfzls\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tggi5: namespaces \"tggi5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n thc2j: namespaces \"thc2j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tj0ws: namespaces \"tj0ws\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tjxz4: namespaces \"tjxz4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tl-60: namespaces \"tl-60\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tl4un: namespaces \"tl4un\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tmmju: namespaces \"tmmju\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tmr96: namespaces \"tmr96\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tn8my: namespaces \"tn8my\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tnk30: namespaces \"tnk30\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n to0ti: namespaces \"to0ti\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n todn6: namespaces \"todn6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tq3o9: namespaces \"tq3o9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tracy: namespaces \"tracy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n trj8n: namespaces \"trj8n\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tscro: namespaces \"tscro\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ttecs: namespaces \"ttecs\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ttluj: namespaces \"ttluj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tv1mr: namespaces \"tv1mr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n twiest-1: namespaces \"twiest-1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n twydn: namespaces \"twydn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tyetc: namespaces \"tyetc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n tzmh2: namespaces \"tzmh2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u-m6w: namespaces \"u-m6w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u16ks: namespaces \"u16ks\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u3e9q: namespaces \"u3e9q\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u66f9: namespaces \"u66f9\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u673u: namespaces \"u673u\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n u9na0: namespaces \"u9na0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uf4nf: namespaces \"uf4nf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ugu8r: namespaces \"ugu8r\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uh49f: namespaces \"uh49f\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ui231: namespaces \"ui231\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uizah: namespaces \"uizah\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uj5cy: namespaces \"uj5cy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ujjtx: namespaces \"ujjtx\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ujwfz: namespaces \"ujwfz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uk9vt: namespaces \"uk9vt\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ukgu0: namespaces \"ukgu0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ul092: namespaces \"ul092\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ulfkd: namespaces \"ulfkd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n unsz0: namespaces \"unsz0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n untkm: namespaces \"untkm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uqboh: namespaces \"uqboh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uqw7w: namespaces \"uqw7w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uqxh2: namespaces \"uqxh2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n urpdr: namespaces \"urpdr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uz5mh: namespaces \"uz5mh\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n uzxt2: namespaces \"uzxt2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n v2j9j: namespaces \"v2j9j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n v3y2s: namespaces \"v3y2s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n v5oea: namespaces \"v5oea\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n va662: namespaces \"va662\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ve4aq: namespaces \"ve4aq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n veith: namespaces \"veith\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vg0ei: namespaces \"vg0ei\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vkmuj: namespaces \"vkmuj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vlb6z: namespaces \"vlb6z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vm5vm: namespaces \"vm5vm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vofy3: namespaces \"vofy3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vqxfp: namespaces \"vqxfp\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vssfo: namespaces \"vssfo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vv7y6: namespaces \"vv7y6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vwi7l: namespaces \"vwi7l\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vz0mj: namespaces \"vz0mj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n vz4u0: namespaces \"vz4u0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w-p0g: namespaces \"w-p0g\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w2-4x: namespaces \"w2-4x\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w3tjm: namespaces \"w3tjm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w6-9z: namespaces \"w6-9z\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w6rds: namespaces \"w6rds\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w7hc0: namespaces \"w7hc0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n w8byf: namespaces \"w8byf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wbfer: namespaces \"wbfer\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wbxpl: namespaces \"wbxpl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wdbne: namespaces \"wdbne\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n whqp5: namespaces \"whqp5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wljnr: namespaces \"wljnr\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wm6qy: namespaces \"wm6qy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wmeng1: namespaces \"wmeng1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wmeng2: namespaces \"wmeng2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wn7ll: namespaces \"wn7ll\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wnjoi: namespaces \"wnjoi\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wo-x3: namespaces \"wo-x3\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wo433: namespaces \"wo433\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wovre: namespaces \"wovre\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wpd29: namespaces \"wpd29\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wqjrg: namespaces \"wqjrg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wte1j: namespaces \"wte1j\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wv8tf: namespaces \"wv8tf\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wwh5t: namespaces \"wwh5t\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wx5jm: namespaces \"wx5jm\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wxqvy: namespaces \"wxqvy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wyfq5: namespaces \"wyfq5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n wysiz: namespaces \"wysiz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n x-rp0: namespaces \"x-rp0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n x18ea: namespaces \"x18ea\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n x44eu: namespaces \"x44eu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n x45xd: namespaces \"x45xd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n x65j5: namespaces \"x65j5\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xa8yz: namespaces \"xa8yz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xazjn: namespaces \"xazjn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xdi59: namespaces \"xdi59\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xe636: namespaces \"xe636\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xea0s: namespaces \"xea0s\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xgq1w: namespaces \"xgq1w\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xiaocwan-1: namespaces \"xiaocwan-1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xiaocwan-2: namespaces \"xiaocwan-2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xifks: namespaces \"xifks\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xkas8: namespaces \"xkas8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xllh0: namespaces \"xllh0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xlz42: namespaces \"xlz42\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xoltq: namespaces \"xoltq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xp0sw: namespaces \"xp0sw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xrfgw: namespaces \"xrfgw\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xw3n0: namespaces \"xw3n0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xwn48: namespaces \"xwn48\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n xxgaq: namespaces \"xxgaq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y-izu: namespaces \"y-izu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y1315: namespaces \"y1315\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y1cxg: namespaces \"y1cxg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y369y: namespaces \"y369y\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y4lw6: namespaces \"y4lw6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y607h: namespaces \"y607h\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y62az: namespaces \"y62az\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y65mo: namespaces \"y65mo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y71df: namespaces \"y71df\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y7evy: namespaces \"y7evy\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n y82xe: namespaces \"y82xe\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yaet4: namespaces \"yaet4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yb9t2: namespaces \"yb9t2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ybxk0: namespaces \"ybxk0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yc6u4: namespaces \"yc6u4\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ydouo: namespaces \"ydouo\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ye54c: namespaces \"ye54c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yeiyu: namespaces \"yeiyu\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yhxea: namespaces \"yhxea\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yidsd: namespaces \"yidsd\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yiuko: namespaces \"yiuko\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ylomn: namespaces \"ylomn\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ym7q0: namespaces \"ym7q0\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ymx94: namespaces \"ymx94\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yp041: namespaces \"yp041\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ypfk6: namespaces \"ypfk6\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yrhsj: namespaces \"yrhsj\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ysg4d: namespaces \"ysg4d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ysluc: namespaces \"ysluc\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n ywzsg: namespaces \"ywzsg\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yyhhk: namespaces \"yyhhk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n yylah: namespaces \"yylah\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n z-r2v: namespaces \"z-r2v\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n z2115: namespaces \"z2115\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n z8q-o: namespaces \"z8q-o\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n z9miz: namespaces \"z9miz\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zawum: namespaces \"zawum\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zd-3c: namespaces \"zd-3c\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zkkcl: namespaces \"zkkcl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zl-eq: namespaces \"zl-eq\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zlqzk: namespaces \"zlqzk\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zo2y2: namespaces \"zo2y2\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zpjt1: namespaces \"zpjt1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zss7d: namespaces \"zss7d\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zutt8: namespaces \"zutt8\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zuuzl: namespaces \"zuuzl\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zyqt1: namespaces \"zyqt1\" not found\nerror:     rolebindingrestrictions/match-own-service-accounts -n zzm3b: namespaces \"zzm3b\" not found\nsummary: total=26850 errors=1003 ignored=0 unchanged=3486 migrated=22361\ninfo: to rerun only failing resources, add --include=imagestreams,oauthclientauthorizations,rolebindingrestrictions\nerror: 1003 resources failed to migrate", 
    "stdout_lines": [
        "error:     imagestreams/pull-07042210z-gy -n ops-health-monitoring: the server could not find the requested resource (get imagestreams pull-07042210z-gy)", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:launchpad : OAuthClientAuthorization \"arubinge@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:boot-health-check-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:boot-health-check-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:boot-http-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:boot-http-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:hc-boot-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:hc-boot-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:hc-swarm-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:hc-swarm-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:oso-fabric8slave-test:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:oso-fabric8slave-test:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:oso-jenkins32-test:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:oso-jenkins32-test:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:test-vertx-pipelines:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:test-vertx-pipelines:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:testvertx:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:testvertx:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-healthcheck-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-healthcheck-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-32bit:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-32bit:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-alrubinger:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-alrubinger:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-image:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-image:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-memerror-alr:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-memerror-alr:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-memerror:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-memerror:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-oso-hooks:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-oso-hooks:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertx-http-osofree:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertx-http-osofree:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertxhttp-oso:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertxhttp-oso:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/arubinge@redhat.com:system:serviceaccount:vertxhttpapi:jenkins : OAuthClientAuthorization \"arubinge@redhat.com:system:serviceaccount:vertxhttpapi:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/bingli-1:system:serviceaccount:binglifjdw:jenkinsbingli : OAuthClientAuthorization \"bingli-1:system:serviceaccount:binglifjdw:jenkinsbingli\" is invalid: clientName: Internal error: serviceaccounts \"jenkinsbingli\" not found", 
        "error:     oauthclientauthorizations/chuyu@redhat.com:system:serviceaccount:chuyutest:jenkins : OAuthClientAuthorization \"chuyu@redhat.com:system:serviceaccount:chuyutest:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/cmoulliard@redhat.com:system:serviceaccount:zz1:jenkins : OAuthClientAuthorization \"cmoulliard@redhat.com:system:serviceaccount:zz1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dgutride:system:serviceaccount:dgutride-jenkins:jenkins : OAuthClientAuthorization \"dgutride:system:serviceaccount:dgutride-jenkins:jenkins\" is invalid: clientName: Internal error: system:serviceaccount:dgutride-jenkins:jenkins has no redirectURIs; set serviceaccounts.openshift.io/oauth-redirecturi.<some-value>=<redirect> or create a dynamic URI using serviceaccounts.openshift.io/oauth-redirectreference.<some-value>=<reference>", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan1:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan2:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan3:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan3:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan7:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan7:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan8:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan8:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan9:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan9:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyan:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyan:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/dyan@redhat.com:system:serviceaccount:dyantest:jenkins : OAuthClientAuthorization \"dyan@redhat.com:system:serviceaccount:dyantest:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/edewit@redhat.com:launchpad : OAuthClientAuthorization \"edewit@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/gtrikler@redhat.com:launchpad : OAuthClientAuthorization \"gtrikler@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/gtrikler@redhat.com:system:serviceaccount:tmp-sb-health:jenkins : OAuthClientAuthorization \"gtrikler@redhat.com:system:serviceaccount:tmp-sb-health:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jastrachan:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"jastrachan:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:launchpad : OAuthClientAuthorization \"jbalunas@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:boot-healthcheck-01:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:boot-healthcheck-01:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:health-booster-swarm:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:health-booster-swarm:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:rest-vertx-demo:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:rest-vertx-demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:swarm-http-demo:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:swarm-http-demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jbalunas@redhat.com:system:serviceaccount:vert-health-01:jenkins : OAuthClientAuthorization \"jbalunas@redhat.com:system:serviceaccount:vert-health-01:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jclingan@redhat.com:system:serviceaccount:demo-swarm-online:jenkins : OAuthClientAuthorization \"jclingan@redhat.com:system:serviceaccount:demo-swarm-online:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jclingan@redhat.com:system:serviceaccount:demo-vertx-online:jenkins : OAuthClientAuthorization \"jclingan@redhat.com:system:serviceaccount:demo-vertx-online:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/jf.cron0@gmail.com:system:serviceaccount:jf-cron0-jenkins:jenkins : OAuthClientAuthorization \"jf.cron0@gmail.com:system:serviceaccount:jf-cron0-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/lfuka:launchpad : OAuthClientAuthorization \"lfuka:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/lthon@redhat.com:launchpad : OAuthClientAuthorization \"lthon@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/lthon@redhat.com:system:serviceaccount:test-1:jenkins : OAuthClientAuthorization \"lthon@redhat.com:system:serviceaccount:test-1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/lthon@redhat.com:system:serviceaccount:test-2:jenkins : OAuthClientAuthorization \"lthon@redhat.com:system:serviceaccount:test-2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/michal-9:system:serviceaccount:michal-9-jenkins:jenkins : OAuthClientAuthorization \"michal-9:system:serviceaccount:michal-9-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/mmasters1@redhat.com:system:serviceaccount:mmasters3:jenkins : OAuthClientAuthorization \"mmasters1@redhat.com:system:serviceaccount:mmasters3:jenkins\" is invalid: clientName: Internal error: system:serviceaccount:mmasters3:jenkins has no redirectURIs; set serviceaccounts.openshift.io/oauth-redirecturi.<some-value>=<redirect> or create a dynamic URI using serviceaccounts.openshift.io/oauth-redirectreference.<some-value>=<reference>", 
        "error:     oauthclientauthorizations/pmuir-demo:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"pmuir-demo:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/pmuir-launch:launchpad : OAuthClientAuthorization \"pmuir-launch:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/rbehera-1:system:serviceaccount:default-foo:jenkins : OAuthClientAuthorization \"rbehera-1:system:serviceaccount:default-foo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-ggastald:launchpad : OAuthClientAuthorization \"rhn-support-ggastald:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:demo-ggastald:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:demo-ggastald:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-ggastald:system:serviceaccount:hc:jenkins : OAuthClientAuthorization \"rhn-support-ggastald:system:serviceaccount:hc:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-jrawling:system:serviceaccount:pmuir-demo-jenkins:jenkins : OAuthClientAuthorization \"rhn-support-jrawling:system:serviceaccount:pmuir-demo-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-jrawling:system:serviceaccount:rhn-support-jrawling-vxwe-jenkins:jenkins : OAuthClientAuthorization \"rhn-support-jrawling:system:serviceaccount:rhn-support-jrawling-vxwe-jenkins:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/rhn-support-pmuir:launchpad : OAuthClientAuthorization \"rhn-support-pmuir:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/skrupa-1:launchpad : OAuthClientAuthorization \"skrupa-1:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/skrupa-1:system:serviceaccount:vx2:jenkins : OAuthClientAuthorization \"skrupa-1:system:serviceaccount:vx2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/sspeiche@redhat.com:system:serviceaccount:p1:jenkins : OAuthClientAuthorization \"sspeiche@redhat.com:system:serviceaccount:p1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/tschotan@redhat.com:launchpad : OAuthClientAuthorization \"tschotan@redhat.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/tschotan@redhat.com:system:serviceaccount:demo:jenkins : OAuthClientAuthorization \"tschotan@redhat.com:system:serviceaccount:demo:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/wzheng@redhat.com:system:serviceaccount:wzheng123:jenkins : OAuthClientAuthorization \"wzheng@redhat.com:system:serviceaccount:wzheng123:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/wzheng@redhat.com:system:serviceaccount:wzheng2:jenkins : OAuthClientAuthorization \"wzheng@redhat.com:system:serviceaccount:wzheng2:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/xipang-1:system:serviceaccount:xipang-07:jenkins : OAuthClientAuthorization \"xipang-1:system:serviceaccount:xipang-07:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/xiuwang-1:system:serviceaccount:xiuwang:jenkins : OAuthClientAuthorization \"xiuwang-1:system:serviceaccount:xiuwang:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/xiuwang:system:serviceaccount:xiuwang1:jenkins : OAuthClientAuthorization \"xiuwang:system:serviceaccount:xiuwang1:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/xiuwang:system:serviceaccount:xiuwang:jenkins : OAuthClientAuthorization \"xiuwang:system:serviceaccount:xiuwang:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/yufchang:system:serviceaccount:cindy:jenkins : OAuthClientAuthorization \"yufchang:system:serviceaccount:cindy:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/zach.rhoads@amentra.com:launchpad : OAuthClientAuthorization \"zach.rhoads@amentra.com:launchpad\" is invalid: clientName: Internal error: oauthclients.oauth.openshift.io \"launchpad\" not found", 
        "error:     oauthclientauthorizations/zach.rhoads@amentra.com:system:serviceaccount:demo4265:jenkins : OAuthClientAuthorization \"zach.rhoads@amentra.com:system:serviceaccount:demo4265:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/zach.rhoads@amentra.com:system:serviceaccount:demo4272:jenkins : OAuthClientAuthorization \"zach.rhoads@amentra.com:system:serviceaccount:demo4272:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/zhezli-10:system:serviceaccount:test10-5:jenkins : OAuthClientAuthorization \"zhezli-10:system:serviceaccount:test10-5:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     oauthclientauthorizations/zhezli-1:system:serviceaccount:jks:jenkins : OAuthClientAuthorization \"zhezli-1:system:serviceaccount:jks:jenkins\" is invalid: clientName: Internal error: serviceaccounts \"jenkins\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0--gn: namespaces \"0--gn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 04n3r: namespaces \"04n3r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 04zv9: namespaces \"04zv9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 07dlb: namespaces \"07dlb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 08mx7: namespaces \"08mx7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0ad8p: namespaces \"0ad8p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0b4i7: namespaces \"0b4i7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0bd5j: namespaces \"0bd5j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0bgnp: namespaces \"0bgnp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0bxs9: namespaces \"0bxs9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0d530: namespaces \"0d530\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0e5po: namespaces \"0e5po\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0ftpd: namespaces \"0ftpd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0hqp0: namespaces \"0hqp0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0lfzl: namespaces \"0lfzl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0n20m: namespaces \"0n20m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0nd8x: namespaces \"0nd8x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0ofmi: namespaces \"0ofmi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0otxs: namespaces \"0otxs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0q8bn: namespaces \"0q8bn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0uode: namespaces \"0uode\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0vhje: namespaces \"0vhje\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0w35h: namespaces \"0w35h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0x-ls: namespaces \"0x-ls\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0xhrv: namespaces \"0xhrv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0yyb5: namespaces \"0yyb5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 0z2zc: namespaces \"0z2zc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1-tc4: namespaces \"1-tc4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 11hap: namespaces \"11hap\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 13okc: namespaces \"13okc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 17gms: namespaces \"17gms\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 17w6k: namespaces \"17w6k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 17x0a: namespaces \"17x0a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 18bvu: namespaces \"18bvu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 18pji: namespaces \"18pji\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1d8wu: namespaces \"1d8wu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1dg1k: namespaces \"1dg1k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1f84x: namespaces \"1f84x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1fh1i: namespaces \"1fh1i\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1gcfs: namespaces \"1gcfs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1ksa3: namespaces \"1ksa3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1mwlh: namespaces \"1mwlh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1n6kh: namespaces \"1n6kh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1nhqz: namespaces \"1nhqz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1pef6: namespaces \"1pef6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1u2gu: namespaces \"1u2gu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1umj1: namespaces \"1umj1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 1w9lp: namespaces \"1w9lp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2-mz0: namespaces \"2-mz0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2059r: namespaces \"2059r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 20rzl: namespaces \"20rzl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 21i4q: namespaces \"21i4q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 22n6p: namespaces \"22n6p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 243bx: namespaces \"243bx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 24cy4: namespaces \"24cy4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 27a7d: namespaces \"27a7d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 28y7z: namespaces \"28y7z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2cjky: namespaces \"2cjky\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2evpx: namespaces \"2evpx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2f-e4: namespaces \"2f-e4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2jo54: namespaces \"2jo54\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2n-ex: namespaces \"2n-ex\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2nvvs: namespaces \"2nvvs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2qahp: namespaces \"2qahp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2qcqa: namespaces \"2qcqa\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2rq2z: namespaces \"2rq2z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2s1gg: namespaces \"2s1gg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2uctt: namespaces \"2uctt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2ut25: namespaces \"2ut25\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2v9gf: namespaces \"2v9gf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2xemy: namespaces \"2xemy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2xod9: namespaces \"2xod9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2xxeg: namespaces \"2xxeg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2y2lt: namespaces \"2y2lt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 2z1fw: namespaces \"2z1fw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3-oad: namespaces \"3-oad\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3-yjm: namespaces \"3-yjm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 308hm: namespaces \"308hm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 35r-n: namespaces \"35r-n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 36nkg: namespaces \"36nkg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3h8uj: namespaces \"3h8uj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3kte9: namespaces \"3kte9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3muja: namespaces \"3muja\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3nnqt: namespaces \"3nnqt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3nv8j: namespaces \"3nv8j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3oa44: namespaces \"3oa44\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3ouit: namespaces \"3ouit\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3rppl: namespaces \"3rppl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3rsxd: namespaces \"3rsxd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3rz8p: namespaces \"3rz8p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3sbh9: namespaces \"3sbh9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3tf8k: namespaces \"3tf8k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3u5z0: namespaces \"3u5z0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3u92b: namespaces \"3u92b\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3uez4: namespaces \"3uez4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3w0lt: namespaces \"3w0lt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3w4ru: namespaces \"3w4ru\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3y3ik: namespaces \"3y3ik\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3ypiy: namespaces \"3ypiy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3zq2b: namespaces \"3zq2b\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 3zy34: namespaces \"3zy34\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4-xuw: namespaces \"4-xuw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 40ul3: namespaces \"40ul3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 40ymz: namespaces \"40ymz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 42u-n: namespaces \"42u-n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 44vu0: namespaces \"44vu0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 49ps5: namespaces \"49ps5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4ahou: namespaces \"4ahou\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4az3f: namespaces \"4az3f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4c26f: namespaces \"4c26f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4corm: namespaces \"4corm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4dngd: namespaces \"4dngd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4fm3m: namespaces \"4fm3m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4hzkw: namespaces \"4hzkw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4m8z8: namespaces \"4m8z8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4ne7z: namespaces \"4ne7z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4rd5y: namespaces \"4rd5y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4tupz: namespaces \"4tupz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4vfok: namespaces \"4vfok\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4xi7o: namespaces \"4xi7o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 4z9y2: namespaces \"4z9y2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 556jr: namespaces \"556jr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 55cch: namespaces \"55cch\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5fskr: namespaces \"5fskr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5j94k: namespaces \"5j94k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5mgj7: namespaces \"5mgj7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5miof: namespaces \"5miof\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5nytu: namespaces \"5nytu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5oamj: namespaces \"5oamj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5p5me: namespaces \"5p5me\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5q-mp: namespaces \"5q-mp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5rmeu: namespaces \"5rmeu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5t0x9: namespaces \"5t0x9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5tz5u: namespaces \"5tz5u\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 5vycg: namespaces \"5vycg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 60bfc: namespaces \"60bfc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 637pq: namespaces \"637pq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 647m0: namespaces \"647m0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 65qwz: namespaces \"65qwz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 65u7n: namespaces \"65u7n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 68-3m: namespaces \"68-3m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6agt8: namespaces \"6agt8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6fcwl: namespaces \"6fcwl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6gjtb: namespaces \"6gjtb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6he28: namespaces \"6he28\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6hfgc: namespaces \"6hfgc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6i5od: namespaces \"6i5od\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6ii-u: namespaces \"6ii-u\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6jenb: namespaces \"6jenb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6lh6a: namespaces \"6lh6a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6psum: namespaces \"6psum\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6qgod: namespaces \"6qgod\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6t4nx: namespaces \"6t4nx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6tyg3: namespaces \"6tyg3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6uauh: namespaces \"6uauh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6wtpm: namespaces \"6wtpm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6wwu5: namespaces \"6wwu5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 6zpxe: namespaces \"6zpxe\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 70fcr: namespaces \"70fcr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 70wil: namespaces \"70wil\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 72--g: namespaces \"72--g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 729qk: namespaces \"729qk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 72lnd: namespaces \"72lnd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7577v: namespaces \"7577v\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 79cac: namespaces \"79cac\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7aymi: namespaces \"7aymi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7b0-y: namespaces \"7b0-y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7bhoy: namespaces \"7bhoy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7j42f: namespaces \"7j42f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7j7nd: namespaces \"7j7nd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7j9on: namespaces \"7j9on\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7k7yb: namespaces \"7k7yb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7kfwi: namespaces \"7kfwi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7m82d: namespaces \"7m82d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7pwh2: namespaces \"7pwh2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7pyzi: namespaces \"7pyzi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7tdfh: namespaces \"7tdfh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7u8xj: namespaces \"7u8xj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7wma1: namespaces \"7wma1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7wy-1: namespaces \"7wy-1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7x0mr: namespaces \"7x0mr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 7xual: namespaces \"7xual\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 84d5i: namespaces \"84d5i\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 85ww9: namespaces \"85ww9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8agr4: namespaces \"8agr4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8b1we: namespaces \"8b1we\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8bb4e: namespaces \"8bb4e\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8d0v9: namespaces \"8d0v9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8evpk: namespaces \"8evpk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8f6ju: namespaces \"8f6ju\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8fwon: namespaces \"8fwon\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8jzhh: namespaces \"8jzhh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8l7ub: namespaces \"8l7ub\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8o89j: namespaces \"8o89j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8px0m: namespaces \"8px0m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8tcdf: namespaces \"8tcdf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8tn1y: namespaces \"8tn1y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8wtlv: namespaces \"8wtlv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 8yb8n: namespaces \"8yb8n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9--n3: namespaces \"9--n3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9-1sn: namespaces \"9-1sn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9-kgt: namespaces \"9-kgt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 90jxz: namespaces \"90jxz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 91-wk: namespaces \"91-wk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 93ksz: namespaces \"93ksz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 98uvz: namespaces \"98uvz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 99egr: namespaces \"99egr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9arqt: namespaces \"9arqt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9b1qq: namespaces \"9b1qq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9b72d: namespaces \"9b72d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9bvtx: namespaces \"9bvtx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9dv-x: namespaces \"9dv-x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9j714: namespaces \"9j714\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9jhhm: namespaces \"9jhhm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9jzl6: namespaces \"9jzl6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9k7a5: namespaces \"9k7a5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9k847: namespaces \"9k847\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9lm37: namespaces \"9lm37\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9m3xw: namespaces \"9m3xw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9o6ec: namespaces \"9o6ec\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9r9y2: namespaces \"9r9y2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9s-0h: namespaces \"9s-0h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9s77c: namespaces \"9s77c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9snbl: namespaces \"9snbl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9uz88: namespaces \"9uz88\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9vbj9: namespaces \"9vbj9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9w8r0: namespaces \"9w8r0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9wa5s: namespaces \"9wa5s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n 9y501: namespaces \"9y501\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a-1mg: namespaces \"a-1mg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a-25f: namespaces \"a-25f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a1qms: namespaces \"a1qms\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a1uhz: namespaces \"a1uhz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a244w: namespaces \"a244w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a2qc2: namespaces \"a2qc2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a5aa3: namespaces \"a5aa3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a7qd9: namespaces \"a7qd9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a8-5c: namespaces \"a8-5c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n a8xtg: namespaces \"a8xtg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aaeh0: namespaces \"aaeh0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aas5r: namespaces \"aas5r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ab3p2: namespaces \"ab3p2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n adi6h: namespaces \"adi6h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n adlt7: namespaces \"adlt7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n agupta-dem: namespaces \"agupta-dem\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-dem: namespaces \"agupta-dem\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n agupta-dem: namespaces \"agupta-dem\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo: namespaces \"agupta-demo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo2: namespaces \"agupta-demo2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n agupta-demo3: namespaces \"agupta-demo3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo3: namespaces \"agupta-demo3\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n agupta-demo3: namespaces \"agupta-demo3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n agupta-demo4: namespaces \"agupta-demo4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-demo4: namespaces \"agupta-demo4\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n agupta-demo4: namespaces \"agupta-demo4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-1: namespaces \"agupta-project-1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-2: namespaces \"agupta-project-2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-project-3: namespaces \"agupta-project-3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-test: namespaces \"agupta-test\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta-test5: namespaces \"agupta-test5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta1: namespaces \"agupta1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n agupta2: namespaces \"agupta2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aijqf: namespaces \"aijqf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aivdy: namespaces \"aivdy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n alr93: namespaces \"alr93\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n amdvk: namespaces \"amdvk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n antwo: namespaces \"antwo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aoiur: namespaces \"aoiur\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n aslak-dwpq: namespaces \"aslak-dwpq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aslak-dwpq: namespaces \"aslak-dwpq\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n aslak-dwpq: namespaces \"aslak-dwpq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n aslak-gfau: namespaces \"aslak-gfau\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aslak-gfau: namespaces \"aslak-gfau\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n aslak-gfau: namespaces \"aslak-gfau\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n aug15: namespaces \"aug15\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n axhx5: namespaces \"axhx5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n axi7y: namespaces \"axi7y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n axpn0: namespaces \"axpn0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ay7pn: namespaces \"ay7pn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ayxi2: namespaces \"ayxi2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n b009a: namespaces \"b009a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n b0sys: namespaces \"b0sys\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n b6ymg: namespaces \"b6ymg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n b7pr5: namespaces \"b7pr5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n b8pjy: namespaces \"b8pjy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bad60: namespaces \"bad60\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bbs2ywbi: namespaces \"bbs2ywbi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bc7el: namespaces \"bc7el\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bcudh: namespaces \"bcudh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bdlof: namespaces \"bdlof\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bem8t: namespaces \"bem8t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bfdtx: namespaces \"bfdtx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bgo84: namespaces \"bgo84\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bhrhc: namespaces \"bhrhc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bitl0: namespaces \"bitl0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bj1v6: namespaces \"bj1v6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bl6xv: namespaces \"bl6xv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n blah-1: namespaces \"blah-1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n blah-2: namespaces \"blah-2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bldrw: namespaces \"bldrw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bnv4f: namespaces \"bnv4f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bphfa: namespaces \"bphfa\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bqyrp: namespaces \"bqyrp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bvclh: namespaces \"bvclh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bxwrh: namespaces \"bxwrh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n bzwhn: namespaces \"bzwhn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n c1tux: namespaces \"c1tux\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n c2ttz: namespaces \"c2ttz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n c4ci6: namespaces \"c4ci6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n c6z9p: namespaces \"c6z9p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n c9bth: namespaces \"c9bth\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n caiso: namespaces \"caiso\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n caovs: namespaces \"caovs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cgka7: namespaces \"cgka7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ch631: namespaces \"ch631\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n chfp0: namespaces \"chfp0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ci41i: namespaces \"ci41i\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cindypro: namespaces \"cindypro\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ckica: namespaces \"ckica\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cmr1c: namespaces \"cmr1c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cnpan: namespaces \"cnpan\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cpw62: namespaces \"cpw62\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ct2wr: namespaces \"ct2wr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cxw9f: namespaces \"cxw9f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cyiq1: namespaces \"cyiq1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n cyw86: namespaces \"cyw86\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n d-40c: namespaces \"d-40c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n d5169: namespaces \"d5169\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n d7-r0: namespaces \"d7-r0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n d9czj: namespaces \"d9czj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-3: namespaces \"dakinitest20170405-3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n dakinitest20170405-4: namespaces \"dakinitest20170405-4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n dakinitest20170405-5: namespaces \"dakinitest20170405-5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dakinitest201704051: namespaces \"dakinitest201704051\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dakinitest201704052: namespaces \"dakinitest201704052\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dbfn3: namespaces \"dbfn3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ddy68: namespaces \"ddy68\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n demo-vertx-ggastald: namespaces \"demo-vertx-ggastald\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n df6-b: namespaces \"df6-b\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dgy7q: namespaces \"dgy7q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n difjk: namespaces \"difjk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dma: namespaces \"dma\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dnush: namespaces \"dnush\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dokuq: namespaces \"dokuq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dopvx: namespaces \"dopvx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dr67t: namespaces \"dr67t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dsb41: namespaces \"dsb41\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dsj6r: namespaces \"dsj6r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dtjcx: namespaces \"dtjcx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n du0gb: namespaces \"du0gb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dwnm5: namespaces \"dwnm5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dyi1c: namespaces \"dyi1c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dz6hl: namespaces \"dz6hl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dz7vn: namespaces \"dz7vn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n dzcme: namespaces \"dzcme\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e-h6d: namespaces \"e-h6d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e09iz: namespaces \"e09iz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e0kdr: namespaces \"e0kdr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e1ovy: namespaces \"e1ovy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e307n: namespaces \"e307n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e558n: namespaces \"e558n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e77qf: namespaces \"e77qf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e8go1: namespaces \"e8go1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e8t45: namespaces \"e8t45\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e8zrx: namespaces \"e8zrx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n e94mn: namespaces \"e94mn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ea1is: namespaces \"ea1is\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ecj5n: namespaces \"ecj5n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ee4ve: namespaces \"ee4ve\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n eg2ds: namespaces \"eg2ds\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n egsj7: namespaces \"egsj7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ehqkq: namespaces \"ehqkq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ej47q: namespaces \"ej47q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ekr47: namespaces \"ekr47\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n en4rt: namespaces \"en4rt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n eows0: namespaces \"eows0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ep8kq: namespaces \"ep8kq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n estyl: namespaces \"estyl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n et6qr: namespaces \"et6qr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n eu6wx: namespaces \"eu6wx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ev5-o: namespaces \"ev5-o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ewk6d: namespaces \"ewk6d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n eybak: namespaces \"eybak\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f-1hl: namespaces \"f-1hl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f-aqf: namespaces \"f-aqf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f211q: namespaces \"f211q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f3mtn: namespaces \"f3mtn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f3xn7: namespaces \"f3xn7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f42nb: namespaces \"f42nb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f42x0: namespaces \"f42x0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f77go: namespaces \"f77go\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f7lt9: namespaces \"f7lt9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f87j5: namespaces \"f87j5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f8cp9: namespaces \"f8cp9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f8p36: namespaces \"f8p36\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f9-bs: namespaces \"f9-bs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n f983t: namespaces \"f983t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fa72m: namespaces \"fa72m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fa9uf: namespaces \"fa9uf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fde98: namespaces \"fde98\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fdi0d: namespaces \"fdi0d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fdy0s: namespaces \"fdy0s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fekxt: namespaces \"fekxt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ff7sw: namespaces \"ff7sw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fflna: namespaces \"fflna\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fiajs: namespaces \"fiajs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fj4ck: namespaces \"fj4ck\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fjkd4: namespaces \"fjkd4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fjn97: namespaces \"fjn97\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fjokv: namespaces \"fjokv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fmox1: namespaces \"fmox1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fnk97: namespaces \"fnk97\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fowow: namespaces \"fowow\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fpj5y: namespaces \"fpj5y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fpvji: namespaces \"fpvji\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fs35z: namespaces \"fs35z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ft77k: namespaces \"ft77k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ftvj8: namespaces \"ftvj8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fu5zd: namespaces \"fu5zd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fxcy8: namespaces \"fxcy8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n fxwwp: namespaces \"fxwwp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n g33k2: namespaces \"g33k2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n g5bsz: namespaces \"g5bsz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n g63te: namespaces \"g63te\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n g82sx: namespaces \"g82sx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ga4g5: namespaces \"ga4g5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ggwn7: namespaces \"ggwn7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gh0qr: namespaces \"gh0qr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ghb6e: namespaces \"ghb6e\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gke4g: namespaces \"gke4g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n glt2i: namespaces \"glt2i\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gnzde: namespaces \"gnzde\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gshxs: namespaces \"gshxs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gufdb: namespaces \"gufdb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gwe40: namespaces \"gwe40\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gwg0c: namespaces \"gwg0c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gwtff: namespaces \"gwtff\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gxczk: namespaces \"gxczk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n gxkwg: namespaces \"gxkwg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h-po2: namespaces \"h-po2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h2j31: namespaces \"h2j31\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h31rw: namespaces \"h31rw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h3bmy: namespaces \"h3bmy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h4ss9: namespaces \"h4ss9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n h5gc4: namespaces \"h5gc4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n haf0q: namespaces \"haf0q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hdqff: namespaces \"hdqff\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n hello: namespaces \"hello\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hello: namespaces \"hello\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n hello: namespaces \"hello\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hello2: namespaces \"hello2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hgsuc: namespaces \"hgsuc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hh1tv: namespaces \"hh1tv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hhrdj: namespaces \"hhrdj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hin6y: namespaces \"hin6y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hk2r1: namespaces \"hk2r1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hl-09: namespaces \"hl-09\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hongli2: namespaces \"hongli2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n honrt: namespaces \"honrt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hqx9g: namespaces \"hqx9g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hu33r: namespaces \"hu33r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hu3g4: namespaces \"hu3g4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hwgb8: namespaces \"hwgb8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hwpsz: namespaces \"hwpsz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hyncn: namespaces \"hyncn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hz88r: namespaces \"hz88r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n hzozd: namespaces \"hzozd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i19rs: namespaces \"i19rs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i29py: namespaces \"i29py\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i4ro8: namespaces \"i4ro8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i5kuo: namespaces \"i5kuo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i67v6: namespaces \"i67v6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n i8z-3: namespaces \"i8z-3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ia8ga: namespaces \"ia8ga\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ias9o: namespaces \"ias9o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ibp6z: namespaces \"ibp6z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ievmn: namespaces \"ievmn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ifvk6psku6mz1z26nhhl3-qja1qlmzv4mm8wqas5jvromj: namespaces \"ifvk6psku6mz1z26nhhl3-qja1qlmzv4mm8wqas5jvromj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ifw0z: namespaces \"ifw0z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ih84t: namespaces \"ih84t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n iito6: namespaces \"iito6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ikv93: namespaces \"ikv93\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ikz-7: namespaces \"ikz-7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ipacd: namespaces \"ipacd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n iqemp: namespaces \"iqemp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n iu1j4: namespaces \"iu1j4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j168t: namespaces \"j168t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j1df3: namespaces \"j1df3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j3wip: namespaces \"j3wip\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j4yh5: namespaces \"j4yh5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j52y2: namespaces \"j52y2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j9dqg: namespaces \"j9dqg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n j9l2t: namespaces \"j9l2t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ja6ao: namespaces \"ja6ao\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jcpsj: namespaces \"jcpsj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n je7iy: namespaces \"je7iy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jhcdn: namespaces \"jhcdn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jhmpv: namespaces \"jhmpv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jjhim: namespaces \"jjhim\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jjlen: namespaces \"jjlen\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jktm6: namespaces \"jktm6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jompb: namespaces \"jompb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n joz6t: namespaces \"joz6t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jpil3: namespaces \"jpil3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jqgen: namespaces \"jqgen\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jqlu5: namespaces \"jqlu5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jsrxk: namespaces \"jsrxk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ju9l0: namespaces \"ju9l0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n juzhao: namespaces \"juzhao\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jvm: namespaces \"jvm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jwfsv: namespaces \"jwfsv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jxbrh: namespaces \"jxbrh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n jz4rt: namespaces \"jz4rt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k-vuu: namespaces \"k-vuu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k0a5e: namespaces \"k0a5e\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k1z4c: namespaces \"k1z4c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k5a2v: namespaces \"k5a2v\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k5p87: namespaces \"k5p87\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k6gdg: namespaces \"k6gdg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k73yo: namespaces \"k73yo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k7c0y: namespaces \"k7c0y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n k85kc: namespaces \"k85kc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kax3a: namespaces \"kax3a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kcf6c: namespaces \"kcf6c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kkghl: namespaces \"kkghl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kkiel: namespaces \"kkiel\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kl0ir: namespaces \"kl0ir\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n klqk0: namespaces \"klqk0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kmbs4: namespaces \"kmbs4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kmhbi: namespaces \"kmhbi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kq3qb: namespaces \"kq3qb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ks818: namespaces \"ks818\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ksfow: namespaces \"ksfow\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ksggd: namespaces \"ksggd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kvsgv: namespaces \"kvsgv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kvtos: namespaces \"kvtos\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kywkm: namespaces \"kywkm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n kzspp: namespaces \"kzspp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l-hlw: namespaces \"l-hlw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l2yoh: namespaces \"l2yoh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l2z30: namespaces \"l2z30\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l3wub: namespaces \"l3wub\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l5f0s: namespaces \"l5f0s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l6qxn: namespaces \"l6qxn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n l882w: namespaces \"l882w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n laa7m: namespaces \"laa7m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n le287: namespaces \"le287\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lf5io: namespaces \"lf5io\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lf6p5: namespaces \"lf6p5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lgbm2: namespaces \"lgbm2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lgz8p: namespaces \"lgz8p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lio5s: namespaces \"lio5s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ljm4g: namespaces \"ljm4g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ll483: namespaces \"ll483\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lm354: namespaces \"lm354\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lnz13: namespaces \"lnz13\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lpsvr: namespaces \"lpsvr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lt27o: namespaces \"lt27o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ltia4: namespaces \"ltia4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lu1kr: namespaces \"lu1kr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lui5x: namespaces \"lui5x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lxixf: namespaces \"lxixf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n lxk12: namespaces \"lxk12\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m-gzk: namespaces \"m-gzk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m20vo: namespaces \"m20vo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m2omu: namespaces \"m2omu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m56qy: namespaces \"m56qy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m6hnc: namespaces \"m6hnc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m6n5n: namespaces \"m6n5n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m6r-m: namespaces \"m6r-m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m7aqt: namespaces \"m7aqt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m9jco: namespaces \"m9jco\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n m9rac: namespaces \"m9rac\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mb5x9: namespaces \"mb5x9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n md2s8: namespaces \"md2s8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n me13x: namespaces \"me13x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mfgrj: namespaces \"mfgrj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mg9dq: namespaces \"mg9dq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mj0hb: namespaces \"mj0hb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mj9ua: namespaces \"mj9ua\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mk: namespaces \"mk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mkvp6: namespaces \"mkvp6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mo47k: namespaces \"mo47k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mr7il: namespaces \"mr7il\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mrjih: namespaces \"mrjih\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mrp-s: namespaces \"mrp-s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ms24h: namespaces \"ms24h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mtpy1: namespaces \"mtpy1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mvyqk: namespaces \"mvyqk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mwxuh: namespaces \"mwxuh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mxj4m: namespaces \"mxj4m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n mzdja: namespaces \"mzdja\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n n0gnp: namespaces \"n0gnp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n n0jjp: namespaces \"n0jjp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n n4m1rp74y5bmiapgw9yyx60fd07dtxoxdlxkyeiq2y89h69: namespaces \"n4m1rp74y5bmiapgw9yyx60fd07dtxoxdlxkyeiq2y89h69\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n n4nnf: namespaces \"n4nnf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n n6ttq: namespaces \"n6ttq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nav3h: namespaces \"nav3h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nb358: namespaces \"nb358\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ne068: namespaces \"ne068\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n netqr: namespaces \"netqr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ngu4k: namespaces \"ngu4k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n njtjx: namespaces \"njtjx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nk0ub: namespaces \"nk0ub\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nm337: namespaces \"nm337\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n noy9p: namespaces \"noy9p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n npvu6: namespaces \"npvu6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nspyl: namespaces \"nspyl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ntbne: namespaces \"ntbne\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nxadm: namespaces \"nxadm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n nz0-o: namespaces \"nz0-o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o-57e: namespaces \"o-57e\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o1jc3: namespaces \"o1jc3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o1r6x: namespaces \"o1r6x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o49xu: namespaces \"o49xu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o4wmn: namespaces \"o4wmn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o5gsu: namespaces \"o5gsu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o6pzs: namespaces \"o6pzs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o79mh: namespaces \"o79mh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n o8ego: namespaces \"o8ego\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n obdhg: namespaces \"obdhg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n of42a: namespaces \"of42a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n of62d: namespaces \"of62d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n oh8rh: namespaces \"oh8rh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n oii0q: namespaces \"oii0q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n oksio: namespaces \"oksio\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n omis9: namespaces \"omis9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n oq84c: namespaces \"oq84c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n otur0: namespaces \"otur0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ox7mk: namespaces \"ox7mk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n oxwgu: namespaces \"oxwgu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p1cwe: namespaces \"p1cwe\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p1w9n: namespaces \"p1w9n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p2mj6: namespaces \"p2mj6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p2mx7: namespaces \"p2mx7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p5nfi: namespaces \"p5nfi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n p9562: namespaces \"p9562\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pc8n4: namespaces \"pc8n4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pczk1: namespaces \"pczk1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pdy27: namespaces \"pdy27\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pee-6: namespaces \"pee-6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pfjvn: namespaces \"pfjvn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pfmqw: namespaces \"pfmqw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pg0xp: namespaces \"pg0xp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pgtwx: namespaces \"pgtwx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n phno6: namespaces \"phno6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pk6t4: namespaces \"pk6t4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pkxe1: namespaces \"pkxe1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ppy6r: namespaces \"ppy6r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n prkm3: namespaces \"prkm3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pro-lc: namespaces \"pro-lc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pucbt: namespaces \"pucbt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n puqvo: namespaces \"puqvo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n puu9x: namespaces \"puu9x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pw-10: namespaces \"pw-10\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n px3ln: namespaces \"px3ln\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pxac9nsf: namespaces \"pxac9nsf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n py18j: namespaces \"py18j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pyky3: namespaces \"pyky3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n pyzwg: namespaces \"pyzwg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n q-e0dzyz144nq2m9406g5dmrykimwobrbm2g7x86tzx1pbwr1417hhnl13lcin2: namespaces \"q-e0dzyz144nq2m9406g5dmrykimwobrbm2g7x86tzx1pbwr1417hhnl13lcin2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n q0hxy: namespaces \"q0hxy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n q1a71: namespaces \"q1a71\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n q5idx: namespaces \"q5idx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n q778j: namespaces \"q778j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qep3p: namespaces \"qep3p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qezxn: namespaces \"qezxn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qluqm: namespaces \"qluqm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qlxp2: namespaces \"qlxp2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qmsjx: namespaces \"qmsjx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qnj8w: namespaces \"qnj8w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qnslt: namespaces \"qnslt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qo6x5: namespaces \"qo6x5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qpond: namespaces \"qpond\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n quy18: namespaces \"quy18\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qz8ci: namespaces \"qz8ci\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n qztfz: namespaces \"qztfz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r-01p: namespaces \"r-01p\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r0svq: namespaces \"r0svq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r4lpi: namespaces \"r4lpi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r4w2g: namespaces \"r4w2g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r6kwk: namespaces \"r6kwk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r8q1d: namespaces \"r8q1d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r9ixm: namespaces \"r9ixm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n r9tq7: namespaces \"r9tq7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rb34y: namespaces \"rb34y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rbm8v: namespaces \"rbm8v\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rd6z9: namespaces \"rd6z9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rhn-support-jrawling-iukr: namespaces \"rhn-support-jrawling-iukr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rhn-support-jrawling-pqku: namespaces \"rhn-support-jrawling-pqku\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ri6ow: namespaces \"ri6ow\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rlp3n: namespaces \"rlp3n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rn86m: namespaces \"rn86m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rnae2: namespaces \"rnae2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rph9d: namespaces \"rph9d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rq91k: namespaces \"rq91k\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rqglo: namespaces \"rqglo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rsxja: namespaces \"rsxja\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rt99m: namespaces \"rt99m\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rvhkp: namespaces \"rvhkp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rxrmf: namespaces \"rxrmf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ry9cw: namespaces \"ry9cw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n rym2r: namespaces \"rym2r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s0405: namespaces \"s0405\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s129t: namespaces \"s129t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s2fls: namespaces \"s2fls\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s2oxu: namespaces \"s2oxu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s76sw: namespaces \"s76sw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s8-av: namespaces \"s8-av\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s9g1v: namespaces \"s9g1v\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s9oqc: namespaces \"s9oqc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n s9qgs: namespaces \"s9qgs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-account-group -n sample: namespaces \"sample\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sample: namespaces \"sample\" not found", 
        "error:     rolebindingrestrictions/match-project-admin-user -n sample: namespaces \"sample\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n scpmv: namespaces \"scpmv\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ser0a: namespaces \"ser0a\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sgzes: namespaces \"sgzes\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sicid: namespaces \"sicid\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sj2zb: namespaces \"sj2zb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sk58d: namespaces \"sk58d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ski72: namespaces \"ski72\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sl4h1: namespaces \"sl4h1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sm-sp: namespaces \"sm-sp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n smtgb: namespaces \"smtgb\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sn-b7: namespaces \"sn-b7\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sntfd: namespaces \"sntfd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sos4o: namespaces \"sos4o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sox1r: namespaces \"sox1r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ss1ro: namespaces \"ss1ro\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ssrl1: namespaces \"ssrl1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n suvnf: namespaces \"suvnf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n svm-9: namespaces \"svm-9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n svuws: namespaces \"svuws\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n swb3u: namespaces \"swb3u\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n sy9c5: namespaces \"sy9c5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n syens: namespaces \"syens\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t0uz1: namespaces \"t0uz1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t2-6b: namespaces \"t2-6b\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t55tf: namespaces \"t55tf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t69f5: namespaces \"t69f5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t758n: namespaces \"t758n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t7z9e: namespaces \"t7z9e\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n t966u: namespaces \"t966u\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tamxl: namespaces \"tamxl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n td7ki: namespaces \"td7ki\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n test3: namespaces \"test3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n test4: namespaces \"test4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n test5: namespaces \"test5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n test6: namespaces \"test6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tff0x: namespaces \"tff0x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tfvax: namespaces \"tfvax\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tfzls: namespaces \"tfzls\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tggi5: namespaces \"tggi5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n thc2j: namespaces \"thc2j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tj0ws: namespaces \"tj0ws\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tjxz4: namespaces \"tjxz4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tl-60: namespaces \"tl-60\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tl4un: namespaces \"tl4un\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tmmju: namespaces \"tmmju\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tmr96: namespaces \"tmr96\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tn8my: namespaces \"tn8my\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tnk30: namespaces \"tnk30\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n to0ti: namespaces \"to0ti\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n todn6: namespaces \"todn6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tq3o9: namespaces \"tq3o9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tracy: namespaces \"tracy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n trj8n: namespaces \"trj8n\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tscro: namespaces \"tscro\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ttecs: namespaces \"ttecs\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ttluj: namespaces \"ttluj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tv1mr: namespaces \"tv1mr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n twiest-1: namespaces \"twiest-1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n twydn: namespaces \"twydn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tyetc: namespaces \"tyetc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n tzmh2: namespaces \"tzmh2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u-m6w: namespaces \"u-m6w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u16ks: namespaces \"u16ks\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u3e9q: namespaces \"u3e9q\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u66f9: namespaces \"u66f9\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u673u: namespaces \"u673u\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n u9na0: namespaces \"u9na0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uf4nf: namespaces \"uf4nf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ugu8r: namespaces \"ugu8r\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uh49f: namespaces \"uh49f\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ui231: namespaces \"ui231\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uizah: namespaces \"uizah\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uj5cy: namespaces \"uj5cy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ujjtx: namespaces \"ujjtx\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ujwfz: namespaces \"ujwfz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uk9vt: namespaces \"uk9vt\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ukgu0: namespaces \"ukgu0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ul092: namespaces \"ul092\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ulfkd: namespaces \"ulfkd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n unsz0: namespaces \"unsz0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n untkm: namespaces \"untkm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uqboh: namespaces \"uqboh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uqw7w: namespaces \"uqw7w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uqxh2: namespaces \"uqxh2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n urpdr: namespaces \"urpdr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uz5mh: namespaces \"uz5mh\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n uzxt2: namespaces \"uzxt2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n v2j9j: namespaces \"v2j9j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n v3y2s: namespaces \"v3y2s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n v5oea: namespaces \"v5oea\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n va662: namespaces \"va662\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ve4aq: namespaces \"ve4aq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n veith: namespaces \"veith\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vg0ei: namespaces \"vg0ei\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vkmuj: namespaces \"vkmuj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vlb6z: namespaces \"vlb6z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vm5vm: namespaces \"vm5vm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vofy3: namespaces \"vofy3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vqxfp: namespaces \"vqxfp\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vssfo: namespaces \"vssfo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vv7y6: namespaces \"vv7y6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vwi7l: namespaces \"vwi7l\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vz0mj: namespaces \"vz0mj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n vz4u0: namespaces \"vz4u0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w-p0g: namespaces \"w-p0g\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w2-4x: namespaces \"w2-4x\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w3tjm: namespaces \"w3tjm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w6-9z: namespaces \"w6-9z\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w6rds: namespaces \"w6rds\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w7hc0: namespaces \"w7hc0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n w8byf: namespaces \"w8byf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wbfer: namespaces \"wbfer\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wbxpl: namespaces \"wbxpl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wdbne: namespaces \"wdbne\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n whqp5: namespaces \"whqp5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wljnr: namespaces \"wljnr\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wm6qy: namespaces \"wm6qy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wmeng1: namespaces \"wmeng1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wmeng2: namespaces \"wmeng2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wn7ll: namespaces \"wn7ll\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wnjoi: namespaces \"wnjoi\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wo-x3: namespaces \"wo-x3\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wo433: namespaces \"wo433\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wovre: namespaces \"wovre\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wpd29: namespaces \"wpd29\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wqjrg: namespaces \"wqjrg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wte1j: namespaces \"wte1j\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wv8tf: namespaces \"wv8tf\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wwh5t: namespaces \"wwh5t\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wx5jm: namespaces \"wx5jm\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wxqvy: namespaces \"wxqvy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wyfq5: namespaces \"wyfq5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n wysiz: namespaces \"wysiz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n x-rp0: namespaces \"x-rp0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n x18ea: namespaces \"x18ea\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n x44eu: namespaces \"x44eu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n x45xd: namespaces \"x45xd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n x65j5: namespaces \"x65j5\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xa8yz: namespaces \"xa8yz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xazjn: namespaces \"xazjn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xdi59: namespaces \"xdi59\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xe636: namespaces \"xe636\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xea0s: namespaces \"xea0s\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xgq1w: namespaces \"xgq1w\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xiaocwan-1: namespaces \"xiaocwan-1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xiaocwan-2: namespaces \"xiaocwan-2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xifks: namespaces \"xifks\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xkas8: namespaces \"xkas8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xllh0: namespaces \"xllh0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xlz42: namespaces \"xlz42\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xoltq: namespaces \"xoltq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xp0sw: namespaces \"xp0sw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xrfgw: namespaces \"xrfgw\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xw3n0: namespaces \"xw3n0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xwn48: namespaces \"xwn48\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n xxgaq: namespaces \"xxgaq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y-izu: namespaces \"y-izu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y1315: namespaces \"y1315\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y1cxg: namespaces \"y1cxg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y369y: namespaces \"y369y\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y4lw6: namespaces \"y4lw6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y607h: namespaces \"y607h\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y62az: namespaces \"y62az\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y65mo: namespaces \"y65mo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y71df: namespaces \"y71df\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y7evy: namespaces \"y7evy\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n y82xe: namespaces \"y82xe\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yaet4: namespaces \"yaet4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yb9t2: namespaces \"yb9t2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ybxk0: namespaces \"ybxk0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yc6u4: namespaces \"yc6u4\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ydouo: namespaces \"ydouo\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ye54c: namespaces \"ye54c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yeiyu: namespaces \"yeiyu\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yhxea: namespaces \"yhxea\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yidsd: namespaces \"yidsd\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yiuko: namespaces \"yiuko\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ylomn: namespaces \"ylomn\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ym7q0: namespaces \"ym7q0\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ymx94: namespaces \"ymx94\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yp041: namespaces \"yp041\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ypfk6: namespaces \"ypfk6\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yrhsj: namespaces \"yrhsj\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ysg4d: namespaces \"ysg4d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ysluc: namespaces \"ysluc\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n ywzsg: namespaces \"ywzsg\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yyhhk: namespaces \"yyhhk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n yylah: namespaces \"yylah\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n z-r2v: namespaces \"z-r2v\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n z2115: namespaces \"z2115\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n z8q-o: namespaces \"z8q-o\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n z9miz: namespaces \"z9miz\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zawum: namespaces \"zawum\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zd-3c: namespaces \"zd-3c\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zkkcl: namespaces \"zkkcl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zl-eq: namespaces \"zl-eq\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zlqzk: namespaces \"zlqzk\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zo2y2: namespaces \"zo2y2\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zpjt1: namespaces \"zpjt1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zss7d: namespaces \"zss7d\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zutt8: namespaces \"zutt8\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zuuzl: namespaces \"zuuzl\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zyqt1: namespaces \"zyqt1\" not found", 
        "error:     rolebindingrestrictions/match-own-service-accounts -n zzm3b: namespaces \"zzm3b\" not found", 
        "summary: total=26850 errors=1003 ignored=0 unchanged=3486 migrated=22361", 
        "info: to rerun only failing resources, add --include=imagestreams,oauthclientauthorizations,rolebindingrestrictions", 
        "error: 1003 resources failed to migrate"
    ], 
    "warnings": []
}
```

full log: https://atomic-e2e-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/aos-cd/job/cluster%252Foperation/252/consoleFull

@smarterclayton

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

@jupierce I believe this should prevent the occurrence of:

`"error:     imagestreams/pull-07042210z-gy -n ops-health-monitoring: the server could not find the requested resource (get imagestreams pull-07042210z-gy)"`

Fixes #15122

xref: #15007 

[test]

### CODE REVIEW

File: pkg/cmd/admin/migrate/migrator.go [hunk 1]
```diff
@@ -485,7 +485,7 @@ func canRetry(err error) bool {
 // All other errors are left in their natural state - they will not be retried unless
 // they define a Temporary() method that returns true.
 func DefaultRetriable(info *resource.Info, err error) error {
-	if err == nil {
+	if err == nil || errors.IsNotFound(err) { // tolerate the deletion of resources during migration
```
Comment (smarterclayton) [inline pkg/cmd/admin/migrate/migrator.go]: nit, put this on the line above

**Comment by enj** [comment]
[merge] comments addressed and tests passed on earlier run with identical code.

**Comment by smarterclayton** [comment]
Tests passed
