### PR TITLE
BuildConfig: emit event on missing ImageStream

### LINKED ISSUE #8523: Build error is not communicated to the user when ImageStream is missing
When creating an application from a template, the build fails silently if the referenced ImageStream does not exist. From the user's perspective there are no errors and at the same time no pods or builds get created:
```
$ oc get pods
$ oc get builds
$ oc get events
```

All the above return empty result. The error is only visible on the master node through _journalctl_:
```
$ sudo journalctl | grep employee-app
Apr 15 09:32:01 rhel-cdk sh[18153]: E0415 09:32:01.650542   18313 config_controller.go:55] error instantiating Build from BuildConfig eap7/employee-app: imageStream "jboss-eap70-openshift" not found

```

##### Version
oc v3.1.0.4-16-g112fcc4
kubernetes v1.1.0-origin-1107-g4c8e6f4
openshift v3.1.0.4-16-g112fcc4
etcd 2.1.2

##### Steps To Reproduce

$ oc new-project eap7
$ oc create -f https://raw.githubusercontent.com/siamaksade/wildfly-swarm-hystrix-example/eap7/eap7-microservices-example.yaml
$ oc new-app eap7-microservices-example

##### Current Result
Build fails silently and no errors are communicated to the user.

##### Expected Result
The user needs to be notified (through events?) that build is failing due to missing Image Stream.

### PR DESCRIPTION
**Pull request by mmilata**
Fixes #8523.

This is probably not the right fix but I'd like to open a PR to ask some questions:

* Where in the chain of `if err != nil ... return err` should the event be created? It probably makes sense to do it right after `resolveImageStream` returns error in `pkg/build/generator/generator.go:generateBuildFromConfig` however I'm not really sure how to get hold of `EventRecorder` or how to initialize it if it should be a new member of `BuildGenerator` struct.
* Because BuildConfigs haven't generated events before they are not displayed in `oc describe bc foo`, should I extend `oc` to do this?
* I noticed some harmless bugs, like [this redundant if](https://github.com/openshift/origin/blob/v1.3.0-rc1/pkg/build/generator/generator.go#L577), should I include it in this commit, open separate PR or just ignore it?

### CODE REVIEW

**Comment by mmilata** [comment]
Rewrote the commit to include namespace in the error message that is displayed by `oc start-build`.

**Comment by bparees** [comment]
@mmilata 
> Because BuildConfigs haven't generated events before they are not displayed in oc describe bc foo, should I extend oc to do this?

yes

> I noticed some harmless bugs, like this redundant if, should I include it in this commit, open separate PR or just ignore it?

looks like you already did, but the answer is for minor code cleanup that you encounter while working a file, it's fine to include it in your feature commit.

Once you update this PR to augment the describe output, please provide an example of the new output of oc start-build and oc describe when the missing imagestream scenario is encountered.

Thanks!

File: pkg/build/generator/generator.go [hunk 1]
```diff
@@ -585,10 +583,8 @@ func (g *BuildGenerator) resolveImageStreamReference(ctx kapi.Context, from kapi
 	case "ImageStreamTag":
 		imageStreamTag, err := g.Client.GetImageStreamTag(kapi.WithNamespace(ctx, namespace), from.Name)
 		if err != nil {
-			glog.V(2).Infof("Error resolving ImageStreamTag reference %s in namespace %s: %v", from.Name, namespace, err)
-			if errors.IsNotFound(err) {
-				return "", err
-			}
+			err = fmt.Errorf("Error resolving ImageStreamTag reference %s in namespace %s: %v", from.Name, namespace, err)
```
Comment (bparees) [inline pkg/build/generator/generator.go]: this needs to be wrapped into a NewNotFound error or some other appropriate StatusError so it comes back as a proper http status code error.  (see kubernetes/pkg/api/errors/errors.go)

same for the block above.

Comment (mmilata) [inline pkg/build/generator/generator.go]: Not sure if NotFound is appropriate here, seems like something the server would return if the BuildConfig itself didn't exist. Perhaps BadRequest or UnprocessableEntity?

Comment (bparees) [inline pkg/build/generator/generator.go]: UnprocessableEntity seems reasonable.

**Comment by mmilata** [comment]
@bparees `Instantiate` now returns `UnprocessableEntity` that client knows how to display. Also added simple test.

```
# oc start-build employee-app
The ImageStreamTag "jboss-eap70-openshift:1.3-Beta" is invalid.
from: Error resolving ImageStreamTag jboss-eap70-openshift:1.3-Beta in namespace openshift: imagestreams "jboss-eap70-openshift" not found

# oc describe bc employee-app
Name:           employee-app
Namespace:      eap7
Created:        2 hours ago
Labels:         app=eap7-microservices-example
                application=eap7-microservices-example
                template=eap7-microservices-example
                xpaas=1.3.0
Annotations:    openshift.io/generated-by=OpenShiftNewApp
Latest Version: Never built

Strategy:       Source
URL:            https://github.com/siamaksade/wildfly-swarm-hystrix-example.git
Ref:            eap7
ContextDir:     employee-service
From Image:     ImageStreamTag openshift/jboss-eap70-openshift:1.3-Beta
Force Pull:     yes
Output to:      ImageStreamTag employee-app:latest

Build Run Policy:       Serial
Triggered by:           ImageChange, Config
Webhook GitHub:
        URL:    https://192.168.121.14:8443/oapi/v1/namespaces/eap7/buildconfigs/employee-app/webhooks/Yx9viFu9zBxcGmdN/github
Webhook Generic:
        URL:            https://192.168.121.14:8443/oapi/v1/namespaces/eap7/buildconfigs/employee-app/webhooks/Yx9viFu9zBxcGmdN/generic
        AllowEnv:       false

Events:
  FirstSeen     LastSeen        Count   From                            SubobjectPath   Type            Reason                          Message
  ---------     --------        -----   ----                            -------------   --------        ------                          -------
  2h            1s              4455    {build-config-controller }                      Warning         BuildConfigInstantiateFailed    error instantiating Build from BuildConfig eap7/employee-app: Error resolving ImageStreamTag jboss-eap70-openshift:1.3-Beta in namespace openshift: imagestreams "jboss-eap70-openshift" not found
```

**Comment by bparees** [comment]
lgtm, will merge post 3.3.

**Comment by bparees** [comment]
[test]

**Comment by mmilata** [comment]
Rebased.
[test]?

**Comment by bparees** [comment]
known deployment flakes.
[merge]
