### PR TITLE
Make image trigger test more reliable

### LINKED ISSUE #5161: TestTriggers flake
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin/3645/console
--- FAIL: TestTriggers_imageChange-2 (5.89s)
	deploy_trigger_test.go:165: Waiting for image stream mapping to be reflected in the IS status...
	deploy_trigger_test.go:175: Still waiting for latest tag status on ImageStream test-image-stream
	deploy_trigger_test.go:172: ImageStream test-image-stream now has Status with tags: map[string]api.TagEventList{"latest":api.TagEventList{Items:[]api.TagEvent{api.TagEvent{Created:util.Time{Time:time.Time{sec:63580568103, nsec:0, loc:(*time.Location)(0x42caa60)}}, DockerImageReference:"registry:8080/openshift/test-image@sha256:00000000000000000000000000000001", Image:"sha256:00000000000000000000000000000001"}}}}
	deploy_trigger_test.go:188: Waiting for a new deployment config in response to ImageStream update
	deploy_trigger_test.go:201: expected config version 1, got 0

### PR DESCRIPTION
**Pull request by ironcladlou**
This trigger test only expected a single update to the deploymentConfig
during the test, which is not reliable. Refactor the test to be tolerant
of multiple updates to the deploymentConfig.

Fixes #5161

### CODE REVIEW

**Comment by ironcladlou** [comment]
cc @kargakis @liggitt

**Comment by ironcladlou** [comment]
[test]

File: test/integration/deploy_trigger_test.go [hunk 1]
```diff
@@ -192,14 +194,18 @@ waitForNewConfig:
 		case event := <-configWatch.ResultChan():
 			if event.Type == watchapi.Modified {
 				newConfig = event.Object.(*deployapi.DeploymentConfig)
-				break waitForNewConfig
+				// Multiple updates to the config can be expected (e.g. status
+				// updates), so wait for a significant update (e.g. version).
+				if newConfig.LatestVersion > 0 {
```
Comment (liggitt) [inline test/integration/deploy_trigger_test.go]: if we never see it, the test will just timeout, right? do we want to set a timeout on that earlier than the integration test timeout?

Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: The previous factoring also relied on watch or integration test timeouts, so it's no worse off. Makes sense to me to rely on the global timeout. Otherwise you have to choose arbitrary values or make config per test.

Comment (liggitt) [inline test/integration/deploy_trigger_test.go]: ok. you still sweeping for other similar tests or ready to merge this one?

**Comment by liggitt** [comment]
LGTM

File: test/integration/deploy_trigger_test.go (hunk 1 above)
Comment (ironcladlou) [inline test/integration/deploy_trigger_test.go]: Haven't found anything yet, will make followups as necessary. I'd like to knock this one out now.

**Comment by ironcladlou** [comment]
[merge]

**Comment by pmorie** [comment]
[merge]
