### PR TITLE
dump logs from all containers in pod in DumpPodLogs

### LINKED ISSUE #16773: validate build logging
1) https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/16765/test_pull_request_origin_extended_conformance_install_update/7591

Lots of `Error on reading termination message from logs: failed to open log file "/var/log/pods/c4da4899-ad45-11e7-a77e-525400fdd4ef/git-clone_0.log": open /var/log/pods/c4da4899-ad45-11e7-a77e-525400fdd4ef/git-clone_0.log: no such file or directory`

2) When a clone fails (e.g. bad URI), get:

```
Oct  9 23:01:29.228: INFO: Running 'oc logs --config=/tmp/extended-test-templates-c2jqd-chlbc-user.kubeconfig --namespace=extended-test-templates-c2jqd-chlbc pod/cakephp-mysql-example-1-build'
Oct  9 23:01:29.381: INFO: Error running &{/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64/oc [oc logs --config=/tmp/extended-test-templates-c2jqd-chlbc-user.kubeconfig --namespace=extended-test-templates-c2jqd-chlbc pod/cakephp-mysql-example-1-build] []   Error from server (BadRequest): container "sti-build" in pod "cakephp-mysql-example-1-build" is waiting to start: PodInitializing
 Error from server (BadRequest): container "sti-build" in pod "cakephp-mysql-example-1-build" is waiting to start: PodInitializing
 [] <nil> 0xc421637dd0 exit status 1 <nil> <nil> true [0xc420bad110 0xc420bad138 0xc420bad138] [0xc420bad110 0xc420bad138] [0xc420bad118 0xc420bad130] [0x17c11c0 0x17c12c0] 0xc42163b3e0 <nil>}:
Error from server (BadRequest): container "sti-build" in pod "cakephp-mysql-example-1-build" is waiting to start: PodInitializing
Oct  9 23:01:29.382: INFO: Error retrieving logs for pod "cakephp-mysql-example-1-build": exit status 1
```

### PR DESCRIPTION
**Pull request by jim-minter**
fixes #16773

### CODE REVIEW

File: test/extended/util/framework.go [hunk 1]
```diff
@@ -237,23 +237,13 @@ func DumpPodLogs(pods []kapiv1.Pod, oc *CLI) {
...
-}
-
-func DumpPodContainerLogs(podName string, containerNames []string, oc *CLI) {
-	for _, c := range containerNames {
-		output, err := oc.Run("logs").Args(podName, "-c", c).Output()
-		if err == nil {
-			e2e.Logf("Log for pod %q container %q\n---->\n%s\n<----end of log for %[1]q%[2]q\n", podName, c, output)
-		} else {
-			e2e.Logf("Error retrieving logs for pod %q container %q: %v\n\n", podName, c, err)
+		for _, container := range pod.Spec.Containers {
```
Comment (bparees) [inline test/extended/util/framework.go]: will this catch init containers?  if not, this won't fix the build logs dumping issue.  (and dumping the init containers would be a good idea for this function anyway).

Comment (bparees) [reply test/extended/util/framework.go]: looks like it will not, you need to iterate InitContainers also: 
https://github.com/openshift/origin/blob/master/pkg/build/controller/strategy/sti.go#L136

Comment (jim-minter) [reply test/extended/util/framework.go]: Thanks Ben...  Updated and pushed.
