### PR TITLE
extended: fixed registry tests 

### LINKED ISSUE #15763: extended test cannot talk to integrated docker registry
Extended tests trying to curl integrated registry directly fail with this error:

```
failed to get image "sha256:a4948c96a4784dc2a5b6e9c0dbaca7e14942c3f1185b32081219e20cdea74512" manifest: Get http://docker-registry.default.svc:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
```

The `Get` request made to the registry doesn't generate any entry in registry's log. Pull/push made by Docker daemon works like a charm.

Examples of failed tests:

<details><p>

        Failure [11.080 seconds]
        [Feature:ImagePrune] Image prune
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:127
          with default --all flag
          /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:107
            should prune both internally managed and external images [It]
            /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:106

            Expected error:
                <*url.Error | 0xc4215c1560>: {
                    Op: "Get",
                    URL: "http://172.30.228.91:5000/v2/extended-test-prune-images-hxlqx-hj7c0/origin-release/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0",
                    Err: {
                        what: "malformed HTTP response",
                        str: "\x15\x03\x01\x00\x02\x02",
                    },
                }
                Get http://172.30.228.91:5000/v2/extended-test-prune-images-hxlqx-hj7c0/origin-release/blobs/sha256:ae60289ae57f6a7da4a23756109b6078c209a2e280be031a70bf00e198b6b1a0: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
            not to have occurred

            /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:267

</p></details>

<details><p>

        • Failure [119.714 seconds]
        [imageapis][registry] image signature workflow
        /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:113
          can push a signed image to openshift registry and verify it [It]
          /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:112

          Expected
              <string>: error verifying signature sha256:a4948c96a4784dc2a5b6e9c0dbaca7e14942c3f1185b32081219e20cdea74512@3009b28d3715141e65f04d51ff25a066 for image sha256:a4948c96a4784dc2a5b6e9c0dbaca7e14942c3f1185b32081219e20cdea74512 (verification status will be removed): failed to get image "sha256:a4948c96a4784dc2a5b6e9c0dbaca7e14942c3f1185b32081219e20cdea74512" manifest: Get http://docker-registry.default.svc:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
          to contain substring
              <string>: identity is now confirmed

          /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:106

</p></details>

See jobs
https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_image_registry/3/consoleFull
and https://ci.openshift.redhat.com/jenkins/job/test_pull_request_origin_extended_image_registry/2/consoleFull

### PR DESCRIPTION
**Pull request by miminar**
The extended test suite now secures the registry. This patch allows for
secure connection to the registry.

Resolves #15763

### CODE REVIEW

**Comment by miminar** [comment]
/assign @stevekuznetsov 

This is a second PR to  address #15763.

There will be one more to resolve:

```
• Failure [138.715 seconds]
[imageapis][registry] image signature workflow
/go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:113
  can push a signed image to openshift registry and verify it [It]
  /go/src/github.com/openshift/origin/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:112

  Expected
      <string>: error verifying signature sha256:9a88965479ffee0b415ccd63ddb19ab16ff36c2de3b33dd2a9f1899919e2f569@3ca3e534347bbb4b6617d3bd25ccc52d for image sha256:9a88965479ffee0b415ccd63ddb19ab16ff36c2de3b33dd2a9f1899919e2f569 (verification status will be removed): failed to get image "sha256:9a88965479ffee0b415ccd63ddb19ab16ff36c2de3b33dd2a9f1899919e2f569" manifest: Get http://docker-registry.default.svc:5000/v2/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"
  to contain substring
      <string>: identity is now confirmed
```

… which is a bit more difficult.

File: test/extended/images/helper.go [hunk 1]
```diff
@@ -517,20 +519,36 @@ func MirrorBlobInRegistry(oc *exutil.CLI, dgst digest.Digest, repository string,
...
+		c := http.Client{
+			Transport: knet.SetTransportDefaults(&http.Transport{
+				TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
+			}),
+		}
+		resp, getErr = c.Do(req)
+		if getErr == nil {
+			break
+		}
+		fmt.Fprintf(g.GinkgoWriter, "failed to %s %s: %v (%#+v)\n", req.Method, req.URL, err, err)
```
Comment (dmage) [inline test/extended/images/helper.go]: `err, err`? Does it make sense to print the same error in two different ways?

Comment (miminar) [inline test/extended/images/helper.go]: If the error is a wrapper for some other errors, `%#+v` will not render the embedded string.

File: test/extended/images/helper.go [hunk 2]
```diff
@@ -517,20 +519,36 @@ func MirrorBlobInRegistry(oc *exutil.CLI, dgst digest.Digest, repository string,
...
-	resp, err := c.Do(req)
-	if err != nil {
-		return err
+
+	var (
+		req    *http.Request
+		resp   *http.Response
+		getErr error
+	)
+	for _, schema := range []string{"https", "http"} {
```
Comment (stevekuznetsov) [inline test/extended/images/helper.go]: Instead of having logic here from the ordering of these in the list, could make it more explicit:

```go
func MirrorBlobInRegistry(oc *exutil.CLI, dgst digest.Digest, repository string, timeout time.Duration) error {
    // ...
	c := http.Client{
		Transport: knet.SetTransportDefaults(&http.Transport{
			TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
		}),
	}

	func getBlob(schema string) (*http.Request, *http.Response, error) {
		req, err := http.NewRequest("GET", fmt.Sprintf("%s://%s/v2/%s/blobs/%s", schema, registryURL, repository, dgst.String()), nil)
		if err != nil {
			return req, nil, err
		}
		req.Header.Set("range", "bytes=0-1")
		req.Header.Set("Authorization", "Bearer "+token)
		resp, err := c.Do(req)
		return req, resp, err
	}

	var (
		req    *http.Request
		resp   *http.Response
		getErr error
	)
	if req, resp, getErr = getBlob("https"); getErr != nil {
		// fallback to http (why is this appropriate?)
		if req, resp, getErr = getBlob("http"); getErr != nil {
			fmt.Fprintf(g.GinkgoWriter, "failed to %s %s: %v (%#+v)\n", req.Method, req.URL, err, err)
			return getErr
		}
	}
    // ...
}
```

Comment (miminar) [reply test/extended/images/helper.go]: Good suggestion. Rewritten with a slight modification.

**Comment by miminar** [comment]
@stevekuznetsov please take a look again.

**Comment by miminar** [comment]
@stevekuznetsov has `extended_image_registry` test been somehow disabled? I see it neither among tests nor in PR test history.

**Comment by stevekuznetsov** [comment]
@miminar robot is misbehaving. Will be taken care of.

**Comment by stevekuznetsov** [comment]
Working now!

**Comment by miminar** [comment]
@stevekuznetsov :+1: :beer:

**Comment by miminar** [comment]
Flake #16143 once again:

```
Failure summary:


  1. Hosts:    localhost
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "package_version":
               Not all of the required packages are available at their requested version
               docker:1.12 
               Please check your subscriptions and enabled repositories.
```

@stevekuznetsov I thought you've [disabled](https://github.com/openshift/origin/issues/16143#issuecomment-327214223) the check. Does it need to be disabled on its own for the extended test?

**Comment by stevekuznetsov** [comment]
Ugh -- we have an issue with an old version of the config being around in the base AMI right now, and the extended job does not explicitly refresh the repo -- new AMIs are being built but it may take a couple hours for them to be ready

**Comment by miminar** [comment]
One more try...
/retest

**Comment by miminar** [comment]
The extended registry tests got broken again (6 out of 14 fail). Not sure, what's the cause. I'll try to fix them in this PR.

<details><p>

```
: [Feature:ImagePrune] Image hard prune should delete orphaned blobs 1m20s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/hardprune.go:56
Expected error:
    <*util.ExitError | 0xc421186b70>: {
        Cmd: "oc exec --config=/etc/origin/master/admin.kubeconfig --namespace=default --stdin docker-registry-4-qwpbh -- /bin/sh -s",
        StdErr: "time=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_PORT\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_PORT_9000_TCP\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_PORT_9000_TCP_ADDR\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_PORT_9000_TCP_PORT\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_PORT_9000_TCP_PROTO\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_SERVICE_HOST\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_SERVICE_PORT\" \ntime=\"2017-09-07T14:31:28Z\" level=warning msg=\"Ignoring unrecognized environment variable REGISTRY_CONSOLE_SERVICE_PORT_REGISTRY_CONSOLE\" \ntime=\"2017-09-07T14:31:28.821345689Z\" level=info msg=\"start prune\" distribution_version=\"v2.6.2+unknown\" kubernetes_version=v1.7.0+695f48a16f openshift_version=v3.7.0-alpha.1+d918faf-203 \ntime=\"2017-09-07T14:31:28.892326316Z\" level=error msg=\"filesystem: Path not found: /docker/registry/v2/blobs\" \nDeleted 0 blobs\nFreed up 0 B of disk space\ncommand terminated with exit code 1",
        ExitError: {
            ProcessState: {
                pid: 28630,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 198041},
                    Stime: {Sec: 0, Usec: 36869},
                    Maxrss: 49684,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 13342,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 996,
                    Nivcsw: 11,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/hardprune.go:55from junit_02.xml
Filter through log files

: [Feature:ImagePrune] Image hard prune should show orphaned blob deletions in dry-run mode 1m3s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/hardprune.go:355
Expected error:
    <*util.ExitError | 0xc421940bd0>: {
        Cmd: "oc tag --config=/tmp/extended-test-prune-images-22wpb-vn6sq-user.kubeconfig --namespace=extended-test-prune-images-22wpb-vn6sq --source=istag a:latest a-tagged:latest",
        StdErr: "error: \"a:latest\" is not currently pointing to an image, cannot use it as the source of a tag",
        ExitError: {
            ProcessState: {
                pid: 37493,
                status: 256,
                rusage: {
                    Utime: {Sec: 0, Usec: 182447},
                    Stime: {Sec: 0, Usec: 27149},
                    Maxrss: 49776,
                    Ixrss: 0,
                    Idrss: 0,
                    Isrss: 0,
                    Minflt: 13335,
                    Majflt: 0,
                    Nswap: 0,
                    Inblock: 0,
                    Oublock: 0,
                    Msgsnd: 0,
                    Msgrcv: 0,
                    Nsignals: 0,
                    Nvcsw: 844,
                    Nivcsw: 4,
                },
            },
            Stderr: nil,
        },
    }
    exit status 1
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/hardprune.go:129from junit_02.xml
Filter through log files

: [Feature:ImagePrune] Image prune of schema 1 should prune old image 1m53s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:68
Expected
    <string>: application/vnd.docker.distribution.manifest.v2+json
to equal
    <string>: application/vnd.docker.distribution.manifest.v1+json
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/prune.go:169from junit_02.xml
Filter through log files

: [Feature:ImageQuota] Image limit range should deny a push of built image exceeding limit on openshift.io/images resource 1m58s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/imageapis/limitrange_admission.go:123
Expected error:
    <*errors.errorString | 0xc42041aa90>: {
        s: "Failed to match expected \"(?i)requested access to the resource is denied|failed to push image: denied|^denied$\" in: \"2017-09-07T14:32:31.228951000Z Receiving source from STDIN as archive ...\\n2017-09-07T14:32:40.003419000Z Step 1 : FROM scratch\\n2017-09-07T14:32:40.003958000Z  ---> \\n2017-09-07T14:32:40.004471000Z Step 2 : COPY data1 /data1\\n2017-09-07T14:32:43.638010000Z  ---> efa3efcc320b\\n2017-09-07T14:32:43.899235000Z Removing intermediate container 2ae9ea13b75b\\n2017-09-07T14:32:43.899703000Z Step 3 : COPY data2 /data2\\n2017-09-07T14:32:46.452883000Z  ---> ad0a53b55d25\\n2017-09-07T14:32:46.625080000Z Removing intermediate container 6ea1a7db281c\\n2017-09-07T14:32:46.627349000Z Step 4 : ENV \\\"OPENSHIFT_BUILD_NAME\\\" \\\"sized-3\\\" \\\"OPENSHIFT_BUILD_NAMESPACE\\\" \\\"extended-test-limitrange-admission-c18d5-290lc\\\"\\n2017-09-07T14:32:47.373392000Z  ---> Running in 15762662be8d\\n2017-09-07T14:32:48.540727000Z  ---> 6d09333b7736\\n2017-09-07T14:32:48.569853000Z Removing intermediate container 15762662be8d\\n2017-09-07T14:32:48.570246000Z Step 5 : LABEL \\\"io.openshift.build.name\\\" \\\"sized-3\\\" \\\"io.openshift.build.namespace\\\" \\\"extended-test-limitrange-admission-c18d5-290lc\\\"\\n2017-09-07T14:32:49.365946000Z  ---> Running in 0927402e3646\\n2017-09-07T14:32:51.514398000Z  ---> 7ef3371b7f6c\\n2017-09-07T14:32:51.904800000Z Removing intermediate container 0927402e3646\\n2017-09-07T14:32:51.906489000Z Successfully built 7ef3371b7f6c\"",
    }
    Failed to match expected "(?i)requested access to the resource is denied|failed to push image: denied|^denied$" in: "2017-09-07T14:32:31.228951000Z Receiving source from STDIN as archive ...\n2017-09-07T14:32:40.003419000Z Step 1 : FROM scratch\n2017-09-07T14:32:40.003958000Z  ---> \n2017-09-07T14:32:40.004471000Z Step 2 : COPY data1 /data1\n2017-09-07T14:32:43.638010000Z  ---> efa3efcc320b\n2017-09-07T14:32:43.899235000Z Removing intermediate container 2ae9ea13b75b\n2017-09-07T14:32:43.899703000Z Step 3 : COPY data2 /data2\n2017-09-07T14:32:46.452883000Z  ---> ad0a53b55d25\n2017-09-07T14:32:46.625080000Z Removing intermediate container 6ea1a7db281c\n2017-09-07T14:32:46.627349000Z Step 4 : ENV \"OPENSHIFT_BUILD_NAME\" \"sized-3\" \"OPENSHIFT_BUILD_NAMESPACE\" \"extended-test-limitrange-admission-c18d5-290lc\"\n2017-09-07T14:32:47.373392000Z  ---> Running in 15762662be8d\n2017-09-07T14:32:48.540727000Z  ---> 6d09333b7736\n2017-09-07T14:32:48.569853000Z Removing intermediate container 15762662be8d\n2017-09-07T14:32:48.570246000Z Step 5 : LABEL \"io.openshift.build.name\" \"sized-3\" \"io.openshift.build.namespace\" \"extended-test-limitrange-admission-c18d5-290lc\"\n2017-09-07T14:32:49.365946000Z  ---> Running in 0927402e3646\n2017-09-07T14:32:51.514398000Z  ---> 7ef3371b7f6c\n2017-09-07T14:32:51.904800000Z Removing intermediate container 0927402e3646\n2017-09-07T14:32:51.906489000Z Successfully built 7ef3371b7f6c"
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/imageapis/limitrange_admission.go:99from junit_02.xml
Filter through log files

: [Feature:ImageQuota] Image limit range should deny a push of built image exceeding openshift.io/Image limit 40s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/imageapis/limitrange_admission.go:70
Expected
    <bool>: false
to be true
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/images/helper.go:212from junit_02.xml
Filter through log files

: [imageapis][registry] image signature workflow can push a signed image to openshift registry and verify it 5m7s
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:112
Expected error:
    <*errors.errorString | 0xc42026e740>: {
        s: "timed out while waiting of an image stream tag extended-test-registry-signing-p3rtw-w5vnx/signer:latest",
    }
    timed out while waiting of an image stream tag extended-test-registry-signing-p3rtw-w5vnx/signer:latest
not to have occurred
/tmp/openshift/build-rpm-release/tito/rpmbuild-originutGOgZ/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/test/extended/registry/signature.go:33
```

</p></details>

File: test/extended/util/cli.go [hunk 3]
```diff
@@ -135,9 +135,9 @@ func (c *CLI) SetNamespace(ns string) *CLI {
 }
 
 // WithoutNamespace instructs the command should be invoked without adding --namespace parameter
-func (c *CLI) WithoutNamespace() *CLI {
+func (c CLI) WithoutNamespace() *CLI {
```
Comment (dmage) [inline test/extended/util/cli.go]: Is this method supposed to change the original object?

**Comment by miminar** [comment]
Lot of the failing tests will be fixed by #16325. This PR includes the commit with the fix.

**Comment by miminar** [comment]
I've opened an issue to re-enable signature workflow test  #16344. Let's merge this first to make the extended registry test suite green and great again.

**Comment by miminar** [comment]
@dmage PTAL

**Comment by kargakis** [comment]
@miminar the test failure seems related

**Comment by miminar** [comment]
@kargakis yes, this needs to wait for #16325

**Comment by miminar** [comment]
Flake #13014
/retest

**Comment by bparees** [comment]
@miminar #16325 has merged, should this be unheld?

**Comment by miminar** [comment]
/test extended_image_registry

@bparees yes; I'm still struggling with disabling the signatures workflow test though

File: test/extended/setup.sh [hunk 4]
```diff
@@ -11,17 +11,25 @@ function os::test::extended::focus () {
 	if [[ -n "${FOCUS:-}" ]]; then
 		exitstatus=0
 
+		local excludesFile="${ARTIFACT_DIR}/parallel_test_names.txt"
+
 		# first run anything that isn't explicitly declared [Serial], and matches the $FOCUS, in a parallel mode.
 		os::log::info "Running parallel tests N=${PARALLEL_NODES:-<default>} with focus ${FOCUS}"
-		TEST_REPORT_FILE_NAME=focus_parallel TEST_PARALLEL="${PARALLEL_NODES:-5}" os::test::extended::run -- -ginkgo.skip "\[Serial\]" -test.timeout 6h ${TEST_EXTENDED_ARGS-} || exitstatus=$?
+		TEST_REPORT_FILE_NAME=focus_parallel TEST_PARALLEL="${PARALLEL_NODES:-5}" \
```
Comment (miminar) [inline test/extended/setup.sh]: @stevekuznetsov PTAL

File: test/extended/setup.sh [hunk 5]
```diff
@@ -11,17 +11,25 @@ function os::test::extended::focus () {
...
+			os::test::extended::run -- \
+				-print-test-names-to "${excludesFile}" \
+				-ginkgo.skip "\[Serial\]" \
+				-test.timeout 6h ${TEST_EXTENDED_ARGS-} || exitstatus=$?
 
 		# Then run everything that requires serial and matches the $FOCUS, serially.
 		# there is bit of overlap here because not all serial tests declare [Serial], so they might have run in the
 		# parallel section above.  Hopefully your focus was precise enough to exclude them, and we should be adding
 		# the [Serial] tag to them as needed.
```
Comment (bparees) [inline test/extended/setup.sh]: since you're fixing this, please clean up the comments related to the potential for tests to be run twice.

File: test/extended/setup.sh [hunk 6]
```diff
@@ -11,17 +11,25 @@ function os::test::extended::focus () {
...
 		os::log::info ""
 		os::log::info "Running serial tests with focus ${FOCUS}"
-		TEST_REPORT_FILE_NAME=focus_serial os::test::extended::run -- -suite "serial.conformance.openshift.io" -test.timeout 6h ${TEST_EXTENDED_ARGS-} || exitstatus=$?
+		TEST_REPORT_FILE_NAME=focus_serial os::test::extended::run -- \
+			-excludes-from-file "${excludesFile}" \
+			-test.timeout 6h ${TEST_EXTENDED_ARGS-} || exitstatus=$?
```
Comment (bparees) [inline test/extended/setup.sh]: this still needs to set the serial suite, otherwise you're going to run everything that wasn't run parallel, which will include tests the user wasn't trying to FOCUS on.

Comment (miminar) [reply test/extended/setup.sh]: Currently, `-suite` argument overrides the focus entirely.

With focus applied to both parallel and serial tests, where the former excluded `\[Serial\]` tests, we only need to run those excluded from the former run (while still keeping the focus).

**Comment by miminar** [comment]
> I don't love the amount of complexity we are building around ginkgo and focus management. Can we take a step back and define the problem we're trying to solve here before we bolt more complexity on?

When the focus is applied (like with `extended_image_registry`), I'm interested only in tests matched by the focus. With the current `-suite` logic, the focus is ignored and all the serial tests are run which is not desired.

Alternative approach to *exlucdesfile* would be to modify `extended.test` to apply all `-suite`, `FOCUS` and `SKIP` at the same time. So the `FOCUS` would further reduce tests from the particular suite. The implementation would be similar but without additional flags. Would that be acceptable?

File: test/extended/setup.sh (hunk 6 above)
Comment (dmage) [reply test/extended/setup.sh]: @bparees as I can see "serial.conformance.openshift.io" shouldn't be used there, pruning tests are not labeled as conformance tests.

**Comment by bparees** [comment]
> Alternative approach to exlucdesfile would be to modify extended.test to apply all -suite, FOCUS and SKIP at the same time. So the FOCUS would further reduce tests from the particular suite. The implementation would be similar but without additional flags. Would that be acceptable?

Well it seems more straigthforward, but since not all serial tests are in "serial.conformance.openshift.io" it's probably not sufficient.  I think the current model of "FOCUS overrides everything else and runs exactly you asked for via $FOCUS" is the most intuitive behavior and the only problem is how to deal w/ Serial vs Parallel tests.

Now that I understand your current approach is going to just list the explicitly excluded tests (not all tests that were not selected by the FOCUS) in the parallel run, I feel a bit better about that approach but I still feel like we're working harder than we should have to here.  I'll think about it some more and meanwhile let's see what @smarterclayton and @stevekuznetsov have to say.

We really need a way to just specify two focuses and AND them together (focus1=$FOCUS, focus2=[Serial]).  I don't suppose there's a way to ask Ginkgo to do that?  (if we knew that [Serial] always came first, we could just do a regex like `[Serial].*$FOCUS`......)

**Comment by miminar** [comment]
> if we knew that [Serial] always came first, we could just do a regex like [Serial].*$FOCUS......)

I considered this option as well but was afraid that someone will try to anchor the regexp with `^` and I wanted to avoid regexp modifications.

File: test/extended/setup.sh (hunk 5 above)
Comment (miminar) [reply test/extended/setup.sh]: Cleaned up.

File: test/extended/registry/util/util.go [hunk 7]
```diff
@@ -120,6 +120,19 @@ func GetRegistryPod(podsGetter kcoreclient.PodsGetter) (*kapiv1.Pod, error) {
 	return &podList.Items[0], nil
 }
 
+// LogRegistryPod attempts to write registry log to a file to recent test's output directory.
+func LogRegistryPod(oc *exutil.CLI) error {
+	pod, err := GetRegistryPod(oc.KubeClient().Core())
+	if err != nil {
+		return fmt.Errorf("failed to get registry pod: %v", err)
+	}
+	path, err := oc.Run("logs").Args("dc/docker-registry").OutputToFile("pod-" + pod.Name + ".log")
```
Comment (bparees) [inline test/extended/registry/util/util.go]: @jim-minter if you want to change the Pod log dumping logic to put it in a file, this looks like a promising way to do it instead of spamming the stdout.

**Comment by bparees** [comment]
this lgtm but should probably be split into two prs, one that's changing the extended test infrastructure and one for the imageregistry test changes.

I also want @stevekuznetsov and/or @smarterclayton to sign off on the extended test infrastructure changes.

**Comment by miminar** [comment]
> this lgtm but should probably be split into two prs, one that's changing the extended test infrastructure and one for the imageregistry test changes.

done. The reworked FOCUS commit has been extracted to #16806

/test extended_image_registry

File: test/extended/imageapis/limitrange_admission.go [hunk 8]
```diff
@@ -40,7 +40,8 @@ var _ = g.Describe("[Feature:ImageQuota] Image limit range", func() {
 		deleteTestImagesAndStreams(oc)
 	}
 
-	g.It(fmt.Sprintf("should deny a push of built image exceeding %s limit", imageapi.LimitTypeImage), func() {
+	g.It(fmt.Sprintf("[Skipped] should deny a push of built image exceeding %s limit", imageapi.LimitTypeImage), func() {
+		g.Skip("FIXME: fill image metadata for schema1 in the registry")
```
Comment (bparees) [inline test/extended/imageapis/limitrange_admission.go]: do we have an issue for this?  if not, please open one to track fixing this.

File: test/extended/registry/signature.go [hunk 9]
```diff
@@ -21,6 +22,7 @@ var _ = g.Describe("[imageapis][registry] image signature workflow", func() {
 	)
 
 	g.It("can push a signed image to openshift registry and verify it", func() {
+		g.Skip("FIXME: fix oadm verify-image-signature to work with secured registry")
```
Comment (bparees) [inline test/extended/registry/signature.go]: same here, please open an issue to track fixing this if we don't have one.

**Comment by bparees** [comment]
@miminar please squash the commits and lgtm.  (also please open issues to track enabling the currently skipped tests, if we don't have issues for that already)

**Comment by bparees** [comment]
(and take the hold label off the PR assuming you're ready for it to be merged)

**Comment by miminar** [comment]
Here's issue for the skipped signature workflow test: #16344
And here's a PR for the other skipped test: #16776
Squashed. Removing hold label.

File: test/extended/registry/util/util.go (hunk 7 above)
Comment (jim-minter) [reply test/extended/registry/util/util.go]: @bparees yes, but currently it ends up in /tmp, not as an artifact.

Comment (bparees) [reply test/extended/registry/util/util.go]: well that's not very useful...  and it makes me think @miminar should update this to dump to stdout then because this won't be accessible when the job is done, right?

 (or use one of the existing DumpPodLogs methods)

Comment (jim-minter) [reply test/extended/registry/util/util.go]: +1, @miminar I don't think this output will be retrievable when run in the CI system?

Comment (miminar) [reply test/extended/registry/util/util.go]: > +1, @miminar I don't think this output will be retrievable when run in the CI system?

I was happy using it locally. I didn't realize it won't be preserved in CI system.
Addressed by #16859
