### PR TITLE
Wait for the token to be added to serviceaccount before running command

### LINKED ISSUE #12558: test/end-to-end/core.sh:376: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Seen in https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_integration/10167/consoleFull:

```
FAILURE after 0.223s: test/end-to-end/core.sh:375: executing 'oc logs kubectl-with-token' expecting success and text 'Using in-cluster configuration': the output content test failed
Standard output from the command:
NAME                 READY     STATUS    RESTARTS   AGE
kubectl-with-token   1/1       Running   0          5s
```

### PR DESCRIPTION
**Pull request by soltysh**
Apparently between line 358 and 359 it takes a bit longer, sometime to get the token available in the serviceaccount. I'm adding there a small wait time to bypass the problem. 

Fixes #12558

@deads2k @ncdc @smarterclayton ptal

### CODE REVIEW

**Comment by soltysh** [comment]
[test]

File: test/end-to-end/core.sh [hunk 1]
```diff
@@ -356,6 +356,7 @@ os::cmd::expect_success 'oc whoami'
 
 os::log::info "Running a CLI command in a container using the service account"
 os::cmd::expect_success 'oc policy add-role-to-user view -z default'
+os::cmd::try_until_text 'oc get -n test serviceaccount/default --template="{{.secrets}}"' 'token'
```
Comment (deads2k) [inline test/end-to-end/core.sh]: Can you use the `oc sa gettoken` command instead?

Comment (soltysh) [inline test/end-to-end/core.sh]: oh, I didn't know we have something like that, will rework right away.

Comment (stevekuznetsov) [inline test/end-to-end/core.sh]: Whoever added that was a real team player ;)

**Comment by soltysh** [comment]
Hmm... interesting previous version still failed on that `oc logs kubectl-with-token`

**Comment by soltysh** [comment]
Based on IRC approval, we'll dig further when this is in.

[merge]
