### PR TITLE
Ensure client can delete a buildconfig with no associated builds, eve…

### LINKED ISSUE #8655: can't delete docker-type buildconfigs if docker strategy permission is removed
Create a docker type buildconfig

then (w/o running any builds), remove docker strategy permission from your user:
https://github.com/openshift/openshift-docs/pull/1909/files

then attempt to oc delete the buildconfig.

it will fail with:
```
Error from server: buildconfigs "ruby-hello-world" is forbidden: build strategy Docker is not allowed
```
This is because the reaper is attempting to first update the buildconfig to "paused" and the update is not permitted when you don't have docker buildconfig permissions.

The reaper should be slightly smarter:  check if there are any builds to delete.  If there are no builds to delete, don't bother to pause the buildconfig, just let it get deleted.

### PR DESCRIPTION
**Pull request by jupierce**
@bparees    Fixes #8655

### CODE REVIEW

**Comment by jupierce** [comment]
[testextended][extended:core(images)]

**Comment by jupierce** [comment]
[testextended][extended:core(builds)]

**Comment by bparees** [comment]
@jupierce if you put "fixes [issue link]" in your PR summary, github will auto-close the issue when the PR merges.

**Comment by bparees** [comment]
(there are some other syntaxes that work, but i think think "issue XXX" is one of them)

File: pkg/build/reaper/reaper.go [hunk 1]
```diff
@@ -43,6 +44,17 @@ func (reaper *BuildConfigReaper) Stop(namespace, name string, timeout time.Durat
 			return err
 		}
 
+		// Collect builds related to the config.
+		builds, err = reaper.oc.Builds(namespace).List(kapi.ListOptions{LabelSelector: buildutil.BuildConfigSelector(name)})
+		if err != nil {
+			return err
+		}
```
Comment (bparees) [inline pkg/build/reaper/reaper.go]: you also need to check the deprecated label.

**Comment by bparees** [comment]
There is a bigger issue in this code that i'd like @csrwng to weigh in on...   now that we are truncating the buildconfig label value, we can't just do straight selection using the buildconfig name, we also need to truncate the buildconfig name first, then filter the selection results using the annotation value.

@csrwng i thought you updated all uses of the buildconfig label(s), did this just get missed or is there a reason this didn't need to change that i'm not seeing? It looks like the code was updated (since it uses the annotation) but it's still doing the label selection using the full name.  Does the label selection process itself truncate the value?

File: pkg/build/reaper/reaper.go (hunk 1 above)
Comment (bparees) [inline pkg/build/reaper/reaper.go]: and, due to the truncation issue, you need to filter the results using the annotation value, like the rest of the code does, to determine if a build is really related to the buildconfig.

**Comment by bparees** [comment]
might be worth adding a test as well that ensures we delete only the correct set of builds when someone has created two buildconfigs with very long names, a set of builds associated with each, and then deletes one of those buildconfigs.

File: pkg/build/reaper/reaper.go [hunk 2]
```diff
@@ -30,78 +31,93 @@ type BuildConfigReaper struct {
 
 // Stop deletes the build configuration and all of the associated builds.
 func (reaper *BuildConfigReaper) Stop(namespace, name string, timeout time.Duration, gracePeriod *kapi.DeleteOptions) error {
-	noBcFound := false
-
-	// Add deletion pending annotation to the build config
-	err := unversioned.RetryOnConflict(unversioned.DefaultRetry, func() error {
-		bc, err := reaper.oc.BuildConfigs(namespace).Get(name)
-		if kerrors.IsNotFound(err) {
```
Comment (jupierce) [inline pkg/build/reaper/reaper.go]: I could not determine a reason for the special handling of not found. Any non-conflict error returned to RetryOnConflict appears to terminate retries immediately. The only effect of manually creating a NewNotFound seemed to be removing the "s" from the ultimate error message:
Error from server: buildconfig**s** "test" not found

Comment (bparees) [inline pkg/build/reaper/reaper.go]: i think there was a point in time at which we would still attempt to delete builds that were associated with the buildconfig, even if we couldn't find the buildconfig.

that behavior was recently changed such that we just error out if we can't find the buildconfig and do nothing further.  So yeah, this logic is probably no longer needed.

**Comment by jupierce** [comment]
@bparees Looks like the build config selector is truncated automatically during its instantiation. 
https://github.com/openshift/origin/blob/master/pkg/build/util/util.go#L106-L108
https://github.com/openshift/origin/blob/master/pkg/build/api/util.go#L57-L62
Verified longs names are not problematic in my dev environment, but definitely agree that a test should be added.

**Comment by jupierce** [comment]
The submitted implementation does not attempt to address the race condition between deletion of a build configuration by client A and triggering of a new build by a competing client B. Because of https://github.com/coreos/etcd/issues/741  and the fact that OpenShift does not use quorum reads, we would need to redesign the buildconfig deletion process to use a controller/reconciliation loop to ensure deterministic cascading deletions. 

If we are OK with the race window existing, we could requery associated builds after pausing the build config to reduce the window further (with a slight performance impact).

**Comment by bparees** [comment]
lgtm, can you add the test for long buildconfig names?

**Comment by bparees** [comment]
(i'm ok w/ the race window, given that we can't eliminate it completely i don't know if it's worth jumping through hoops to make it a little smaller)

**Comment by jupierce** [comment]
@bparees Added test case for your perusal.

**Comment by jupierce** [comment]
[test]

File: test/extended/testdata/long_names/fixture.json [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+                    "type": "Source",
+                    "env": [],
+                    "sourceStrategy": {
+                        "from": {
+                            "kind": "DockerImage",
+                            "name": "centos/ruby-22-centos7"
+                        }
+                    }
+                },
+                "output": {
```
Comment (bparees) [inline test/extended/testdata/long_names/fixture.json]: you can make this buildconfig execute faster by leaving out the output so it doesn't have to push the resulting image anywhere.

File: test/extended/testdata/long_names/fixture.json [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
```
Comment (bparees) [inline test/extended/testdata/long_names/fixture.json]: same here

File: test/extended/builds/long_names.go [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+
+import (
+	"path/filepath"
+
+	g "github.com/onsi/ginkgo"
+	o "github.com/onsi/gomega"
+	exutil "github.com/openshift/origin/test/extended/util"
+)
+
+var _ = g.Describe("[builds][Slow] extremely long build/bc names are not problematic", func() {
```
Comment (bparees) [inline test/extended/builds/long_names.go]: Next time around, consider doing an integration test by creating mock objects (mock oc client object that returns builds/buildconfigs and records what delete operations are called) for the reaper.  Then you can just invoke reaper.Stop() directly w/o having all the cluster infrastructure, running builds, etc.

(The problem w/ extended tests are that they are slower, and because they are slower, most of them do not get run as part of the merge queue, which makes it easier for people to accidentally regression functionality until we catch it when running the extended tests explicitly)

Comment (jupierce) [inline test/extended/builds/long_names.go]: Added a test in reaper_test.go which uses mock library.

**Comment by jupierce** [comment]
[test]

File: pkg/build/reaper/reaper_test.go [hunk 6]
```diff
@@ -119,48 +124,70 @@ func TestStop(t *testing.T) {
...
 		err      bool
 	}{
 		"simple stop": {
-			oc: newBuildListFake(makeBuildConfig(0, false)),
+			targetBC: configName,
+			oc:       newBuildListFake(makeBuildConfig(configName, 0, false)),
 			expected: []ktestclient.Action{
 				ktestclient.NewGetAction("buildconfigs", "default", configName),
-				ktestclient.NewUpdateAction("buildconfigs", "default", makeBuildConfig(0, true)),
+				// Since tehre are no builds associated with this build config, do not expect an update
```
Comment (bparees) [inline pkg/build/reaper/reaper_test.go]: there

**Comment by bparees** [comment]
[testextended][extended:core(extremely long build/bc names are not problematic)]

File: pkg/build/reaper/reaper_test.go (hunk 6 above)
Comment (jupierce) [inline pkg/build/reaper/reaper_test.go]: sigh.. I'm coming from an IDE with spellcheck.

**Comment by bparees** [comment]
@jupierce i deleted your builds and images test tags so we can see if we can get a clean run just on your new extended test.

**Comment by bparees** [comment]
lgtm
[merge]

**Comment by bparees** [comment]
known flake https://github.com/openshift/origin/issues/9681
[merge]

**Comment by bparees** [comment]
flake https://github.com/openshift/origin/issues/9444
[merge]
