### PR TITLE
Bug 1281735 - remove the internal docker registry information from imagestream

### LINKED ISSUE #5927: Too much information presented about image streams
Currently doing `oc describe` on an image stream will give us 3 pull specs, pointing to somehow different docker images:

```
$ oc describe is/python -n openshift
Name:           python
Created:        33 minutes ago
Labels:         <none>
Annotations:        openshift.io/image.dockerRepositoryCheck=2015-11-17T14:36:21Z
Docker Pull Spec:   172.30.248.198:5000/openshift/python

Tag Spec                    Created     PullSpec                                Image
2.7 centos/python-27-centos7:latest     33 minutes ago  docker.io/centos/python-27-centos7@sha256:...   
                                        33 minutes ago  centos/python-27-centos7:latest                     
3.3 openshift/python-33-centos7:latest  33 minutes ago  docker.io/openshift/python-33-centos7@sha256:...    
                                        33 minutes ago  openshift/python-33-centos7:latest                  
3.4 centos/python-34-centos7:latest     33 minutes ago  docker.io/centos/python-34-centos7@sha256:...   
                                        33 minutes ago  centos/python-34-centos7:latest                     
latest  3.3                             33 minutes ago  docker.io/openshift/python-33-centos7@sha256:...    
                                        33 minutes ago  openshift/python-33-centos7:latest                  
```

`Docker Pull Spec` comes from internal docker registry, `Spec` comes from tag's spec, `PullSpec` comes from tag's status. The outcome from today's CLI meeting is we should:
1. Change `Docker Pull Spec` into something like `Following` and present there `spec.dockerImageRepository` instead of `status.dockerImageRepository`.
2. Show only relevant information on tags, what could that be? Annotation, description, else? This will inevitably require extending our API to accommodate that information.

Additionally our `oc get` will return internal docker repo, which looking at what was proposed for `oc describe` should be removed as well, showing just the tags list.

```
$ oc get is/python -n openshift
NAME      DOCKER REPO                            TAGS                      UPDATED
python    172.30.248.198:5000/openshift/python   2.7,3.4,3.3 + 1 more...   41 minutes ago
```

The above changes will apply to web UI as well.

@jwforres @bparees @smarterclayton @ncdc @miminar

### PR DESCRIPTION
**Pull request by soltysh**
Fixes #5927 and https://bugzilla.redhat.com/show_bug.cgi?id=1281735.

@mfojtik ptal

### CODE REVIEW

File: pkg/cmd/cli/describe/describer.go [hunk 1]
```diff
@@ -640,7 +640,9 @@ func (d *ImageStreamDescriber) Describe(namespace, name string, settings kctl.De
 
 	return tabbedString(func(out *tabwriter.Writer) error {
 		formatMeta(out, imageStream.ObjectMeta)
-		formatString(out, "Docker Pull Spec", imageStream.Status.DockerImageRepository)
+		if len(imageStream.Spec.DockerImageRepository) > 0 {
+			formatString(out, "Imported From", imageStream.Spec.DockerImageRepository)
```
Comment (mfojtik) [inline pkg/cmd/cli/describe/describer.go]: why "Imported From" ? I thought this field contains the docker pull spec (so I can docker pull <image>).

Comment (mfojtik) [inline pkg/cmd/cli/describe/describer.go]: Also this will break all scripts that are grepping this from oc describe output ;-)

File: pkg/cmd/cli/describe/printer.go [hunk 2]
```diff
@@ -34,7 +34,7 @@ var (
 	imageColumns            = []string{"NAME", "DOCKER REF"}
 	imageStreamTagColumns   = []string{"NAME", "DOCKER REF", "UPDATED", "IMAGENAME"}
 	imageStreamImageColumns = []string{"NAME", "DOCKER REF", "UPDATED", "IMAGENAME"}
-	imageStreamColumns      = []string{"NAME", "DOCKER REPO", "TAGS", "UPDATED"}
+	imageStreamColumns      = []string{"NAME", "TAGS", "UPDATED"}
```
Comment (mfojtik) [inline pkg/cmd/cli/describe/printer.go]: why we wouldn't want to display the docker repository?

Comment (liggitt) [inline pkg/cmd/cli/describe/printer.go]: Agree, that seems important

Comment (soltysh) [inline pkg/cmd/cli/describe/printer.go]: Again, everything in the original issue #5927. Generally, the idea is that in most cases this represents the internal registry which is confusing, because in all cases it points to internal registry and not every image can be docker pulled. Additionally, with current IS implementation there's no single point of docker pull, any IS can point multiple docker registries and this is the way we're going to.

File: pkg/cmd/cli/describe/describer.go (hunk 1 above)
Comment (soltysh) [inline pkg/cmd/cli/describe/describer.go]: Decision [here](https://github.com/openshift/origin/issues/5927#issuecomment-157420530)

File: pkg/cmd/cli/describe/printer.go (hunk 2 above)
Comment (mfojtik) [inline pkg/cmd/cli/describe/printer.go]: hrm, "not every image can be docker pulled" - example? (I can think of online where the registry is not exposed with route). 

just to double-check, we are exposing this information (docker pull spec) when you get the "oc get ist/foo:bar" right?

Comment (soltysh) [inline pkg/cmd/cli/describe/printer.go]: > hrm, "not every image can be docker pulled" - example? (I can think of online where the registry is not exposed with route). 

Example:
```
$ oc get is -n openshift
NAME         DOCKER REPO                               TAGS                          UPDATED
jenkins      172.30.208.39:5000/openshift/jenkins      1,latest                      3 minutes ago
mariadb      172.30.208.39:5000/openshift/mariadb      10.1,latest                   3 minutes ago
...
```
None of the above `DOCKER REPO` addresses is pullable. 

> just to double-check, we are exposing this information (docker pull spec) when you get the "oc get ist/foo:bar" right?

Correct, you're getting full docker pull spec including id of the image:
```
$ oc get istag/django-ex:latest
NAME               DOCKER REF                                                                                                  UPDATED              IMAGENAME
django-ex:latest   172.30.208.39:5000/test/django-ex@sha256:f39a7ee286d0c922c3838f0449f3364ee18d007ebfbcea6f9cefbceeb47b6933   About a minute ago   sha256:f39a7ee286d0c922c3838f0449f3364ee18d007ebfbcea6f9cefbceeb47b6933
```

**Comment by soltysh** [comment]
@mfojtik || @liggitt  feel convinced enough to approve this?

**Comment by mfojtik** [comment]
@soltysh they are not pullable but it tells you the name of the "repository" (which is why it is called "DOCKER REPO"). I don't think it was meant to guarantee to be pullable.

So I'm not convinced but I can approve this ;-)

**Comment by soltysh** [comment]
> I don't think it was meant to guarantee to be pullable.

Unfortunately that's the biggest problem that users do try to pull those, assuming if we import something one is able to pull it. 

Merging with above approval.

[merge]

**Comment by smarterclayton** [comment]
We are going to change URLs to be public.  At which point these will be pullable.  So we just removed something that is usable today.

**Comment by smarterclayton** [comment]
This info isn't explicitly internal.  It just so happens to be external right now.  I reverted this - let's discuss it more.
