### PR TITLE
Fix masterCA conversion

### LINKED ISSUE #5050: master crashes when oauth is not configured
OAuthConfig has the following comment:
```
type OAuthConfig struct {
	// MasterCA is the CA for verifying the TLS connection back to the MasterURL.
	// "" to use system roots, set to use custom roots, never nil (guaranteed by conversion defaults)
	MasterCA *string
```

But master start (using git ref 04bfa26) crashes on startup unless the following patch is applied
```
diff --git a/pkg/cmd/server/api/validation/oauth.go b/pkg/cmd/server/api/validation/oauth.go
index dc69ea3..d5ff22a 100644
--- a/pkg/cmd/server/api/validation/oauth.go
+++ b/pkg/cmd/server/api/validation/oauth.go
@@ -18,7 +18,7 @@ import (
 func ValidateOAuthConfig(config *api.OAuthConfig) ValidationResults {
        validationResults := ValidationResults{}

-       if len(*config.MasterCA) > 0 {
+       if config.MasterCA != nil && len(*config.MasterCA) > 0 {
                validationResults.AddErrors(ValidateFile(*config.MasterCA, "masterCA")...)
        }

diff --git a/pkg/cmd/server/origin/auth.go b/pkg/cmd/server/origin/auth.go
index 323b7f4..889da58 100644
--- a/pkg/cmd/server/origin/auth.go
+++ b/pkg/cmd/server/origin/auth.go
@@ -153,7 +153,7 @@ func (c *AuthConfig) InstallAPI(container *restful.Container) []string {
        osOAuthClientConfig.RedirectUrl = c.Options.MasterPublicURL + path.Join(OpenShiftOAuthAPIPrefix, tokenrequest.D

        osOAuthClient, _ := osincli.NewClient(osOAuthClientConfig)
-       if len(*c.Options.MasterCA) > 0 {
+       if c.Options.MasterCA != nil && len(*c.Options.MasterCA) > 0 {
                rootCAs, err := cmdutil.CertPoolFromFile(*c.Options.MasterCA)
                if err != nil {
                        glog.Fatal(err)
```

My cluster was configured via ansible using pre-compiled packages but OAuth is not configured (AFAIK). It seems that the assumption in the comment doesn't match the code.

### PR DESCRIPTION
**Pull request by liggitt**
Fixes #5050

### CODE REVIEW

**Comment by liggitt** [comment]
@deads2k PTAL

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
race https://github.com/openshift/origin/issues/5025

**Comment by liggitt** [comment]
[merge] to fix master, will take comments as follow up

**Comment by liggitt** [comment]
race #5025

File: pkg/cmd/server/api/conversions.go [hunk 1]
```diff
@@ -1,15 +0,0 @@
-package api
-
-func init() {
-	Scheme.AddDefaultingFuncs(
```
Comment (deads2k) [inline pkg/cmd/server/api/conversions.go]: I didn't catch this in the previous review.  Defaulters belong to versions.  This would need to be in the `v1/conversions.go` with the rest of the defaulters.
